id: netlify
name: netlify
version: v0.1.0
providerServices:
  builds:
    description: Builds
    id: builds:v0.1.0
    name: builds
    preferred: true
    service:
      $ref: netlify/v0.1.0/services/builds.yaml
    title: Netlify's API documentation - builds
    version: v0.1.0
  deploys:
    description: Deploys
    id: deploys:v0.1.0
    name: deploys
    preferred: true
    service:
      $ref: netlify/v0.1.0/services/deploys.yaml
    title: Netlify's API documentation - deploys
    version: v0.1.0
  domain_names:
    description: Domain Names
    id: domain_names:v0.1.0
    name: domain_names
    preferred: true
    service:
      $ref: netlify/v0.1.0/services/domain_names.yaml
    title: Netlify's API documentation - domain_names
    version: v0.1.0
  forms:
    description: Forms
    id: forms:v0.1.0
    name: forms
    preferred: true
    service:
      $ref: netlify/v0.1.0/services/forms.yaml
    title: Netlify's API documentation - forms
    version: v0.1.0
  functions:
    description: Functions
    id: functions:v0.1.0
    name: functions
    preferred: true
    service:
      $ref: netlify/v0.1.0/services/functions.yaml
    title: Netlify's API documentation - functions
    version: v0.1.0
  large_media:
    description: Large Media
    id: large_media:v0.1.0
    name: large_media
    preferred: true
    service:
      $ref: netlify/v0.1.0/services/large_media.yaml
    title: Netlify's API documentation - large_media
    version: v0.1.0
  notifications:
    description: Webhooks and Notifications
    id: notifications:v0.1.0
    name: notifications
    preferred: true
    service:
      $ref: netlify/v0.1.0/services/notifications.yaml
    title: Netlify's API documentation - notifications
    version: v0.1.0
  oauth:
    description: OAuth
    id: oauth:v0.1.0
    name: oauth
    preferred: true
    service:
      $ref: netlify/v0.1.0/services/oauth.yaml
    title: Netlify's API documentation - oauth
    version: v0.1.0
  services:
    description: Services
    id: services:v0.1.0
    name: services
    preferred: true
    service:
      $ref: netlify/v0.1.0/services/services.yaml
    title: Netlify's API documentation - services
    version: v0.1.0
  site:
    description: Site
    id: site:v0.1.0
    name: site
    preferred: true
    service:
      $ref: netlify/v0.1.0/services/site.yaml
    title: Netlify's API documentation - site
    version: v0.1.0
  split_tests:
    description: Split Tests
    id: split_tests:v0.1.0
    name: split_tests
    preferred: true
    service:
      $ref: netlify/v0.1.0/services/split_tests.yaml
    title: Netlify's API documentation - split_tests
    version: v0.1.0
  user_accounts:
    description: User Accounts
    id: user_accounts:v0.1.0
    name: user_accounts
    preferred: true
    service:
      $ref: netlify/v0.1.0/services/user_accounts.yaml
    title: Netlify's API documentation - user_accounts
    version: v0.1.0
openapi: 3.0.0
