openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Google Site Verification API
  description: Verifies ownership of websites or domains with Google.
  version: v1
  x-discovery-doc-revision: '20191119'
  x-generated-date: '2023-01-06'
externalDocs:
  url: https://developers.google.com/site-verification/
servers:
  - url: https://www.googleapis.com/siteVerification/v1
components:
  schemas:
    SiteVerificationWebResourceGettokenRequest:
      id: SiteVerificationWebResourceGettokenRequest
      type: object
      properties:
        site:
          description: The site for which a verification token will be generated.
          properties:
            identifier:
              type: string
              description: The site identifier. If the type is set to SITE, the identifier is a URL. If the type is set to INET_DOMAIN, the site identifier is a domain name.
            type:
              description: The type of resource to be verified. Can be SITE or INET_DOMAIN (domain name).
              type: string
          type: object
        verificationMethod:
          type: string
          description: The verification method that will be used to verify this site. For sites, 'FILE' or 'META' methods may be used. For domains, only 'DNS' may be used.
    SiteVerificationWebResourceListResponse:
      type: object
      properties:
        items:
          items:
            $ref: '#/components/schemas/SiteVerificationWebResourceResource'
          type: array
          description: The list of sites that are owned by the authenticated user.
      id: SiteVerificationWebResourceListResponse
    SiteVerificationWebResourceGettokenResponse:
      type: object
      id: SiteVerificationWebResourceGettokenResponse
      properties:
        method:
          description: The verification method to use in conjunction with this token. For FILE, the token should be placed in the top-level directory of the site, stored inside a file of the same name. For META, the token should be placed in the HEAD tag of the default page that is loaded for the site. For DNS, the token should be placed in a TXT record of the domain.
          type: string
        token:
          type: string
          description: The verification token. The token must be placed appropriately in order for verification to succeed.
    SiteVerificationWebResourceResource:
      properties:
        id:
          description: The string used to identify this site. This value should be used in the "id" portion of the REST URL for the Get, Update, and Delete operations.
          type: string
        owners:
          items:
            type: string
          type: array
          description: The email addresses of all verified owners.
        site:
          description: The address and type of a site that is verified or will be verified.
          properties:
            identifier:
              description: The site identifier. If the type is set to SITE, the identifier is a URL. If the type is set to INET_DOMAIN, the site identifier is a domain name.
              type: string
            type:
              type: string
              description: The site type. Can be SITE or INET_DOMAIN (domain name).
          type: object
      type: object
      id: SiteVerificationWebResourceResource
  parameters:
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    alt:
      description: Data format for the response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
    userIp:
      description: Deprecated. Please use quotaUser instead.
      in: query
      name: userIp
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    quotaUser:
      description: An opaque string that represents a user for quota purposes. Must not exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
    key:
      description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      in: query
      name: key
      schema:
        type: string
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/siteverification.verify_only: Manage your new site verifications with Google
            https://www.googleapis.com/auth/siteverification: Manage the list of sites and domains you control
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
  x-stackQL-resources:
    web_resource__token:
      id: googleworkspace.siteVerification.web_resource__token
      name: web_resource__token
      title: Web_resource__token
      methods:
        webResource_getToken:
          operation:
            $ref: '#/paths/~1token/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    web_resource:
      id: googleworkspace.siteVerification.web_resource
      name: web_resource
      title: Web_resource
      methods:
        webResource_get:
          operation:
            $ref: '#/paths/~1webResource~1{id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        webResource_update:
          operation:
            $ref: '#/paths/~1webResource~1{id}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        webResource_delete:
          operation:
            $ref: '#/paths/~1webResource~1{id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        webResource_patch:
          operation:
            $ref: '#/paths/~1webResource~1{id}/patch'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        webResource_insert:
          operation:
            $ref: '#/paths/~1webResource/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        webResource_list:
          operation:
            $ref: '#/paths/~1webResource/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/web_resource/methods/webResource_get'
          - $ref: '#/components/x-stackQL-resources/web_resource/methods/webResource_list'
        insert: []
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/web_resource/methods/webResource_delete'
paths:
  /token:
    parameters: &ref_1
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/userIp'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/key'
    post:
      description: Get a verification token for placing on a website or domain.
      operationId: siteVerification.webResource.getToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiteVerificationWebResourceGettokenRequest'
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/siteverification
          Oauth2c:
            - https://www.googleapis.com/auth/siteverification
        - Oauth2:
            - https://www.googleapis.com/auth/siteverification.verify_only
          Oauth2c:
            - https://www.googleapis.com/auth/siteverification.verify_only
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteVerificationWebResourceGettokenResponse'
      x-stackQL-resource: web_resource__token
      x-stackQL-verb: select
  /webResource/{id}:
    parameters: *ref_1
    get:
      description: Get the most current data for a website or domain.
      operationId: siteVerification.webResource.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/siteverification
          Oauth2c:
            - https://www.googleapis.com/auth/siteverification
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteVerificationWebResourceResource'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      x-stackQL-resource: web_resource
      x-stackQL-verb: select
    put:
      description: Modify the list of owners for your website or domain.
      operationId: siteVerification.webResource.update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiteVerificationWebResourceResource'
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/siteverification
          Oauth2c:
            - https://www.googleapis.com/auth/siteverification
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteVerificationWebResourceResource'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      x-stackQL-resource: web_resource
      x-stackQL-verb: exec
    delete:
      description: Relinquish ownership of a website or domain.
      operationId: siteVerification.webResource.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/siteverification
          Oauth2c:
            - https://www.googleapis.com/auth/siteverification
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      x-stackQL-resource: web_resource
      x-stackQL-verb: delete
    patch:
      description: Modify the list of owners for your website or domain. This method supports patch semantics.
      operationId: siteVerification.webResource.patch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiteVerificationWebResourceResource'
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/siteverification
          Oauth2c:
            - https://www.googleapis.com/auth/siteverification
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteVerificationWebResourceResource'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      x-stackQL-resource: web_resource
      x-stackQL-verb: exec
  /webResource:
    parameters: *ref_1
    post:
      description: Attempt verification of a website or domain.
      operationId: siteVerification.webResource.insert
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SiteVerificationWebResourceResource'
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/siteverification
          Oauth2c:
            - https://www.googleapis.com/auth/siteverification
        - Oauth2:
            - https://www.googleapis.com/auth/siteverification.verify_only
          Oauth2c:
            - https://www.googleapis.com/auth/siteverification.verify_only
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteVerificationWebResourceResource'
      parameters:
        - in: query
          name: verificationMethod
          required: true
          schema:
            type: string
      x-stackQL-resource: web_resource
      x-stackQL-verb: insert
    get:
      description: Get the list of your verified websites and domains.
      operationId: siteVerification.webResource.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/siteverification
          Oauth2c:
            - https://www.googleapis.com/auth/siteverification
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteVerificationWebResourceListResponse'
      x-stackQL-resource: web_resource
      x-stackQL-verb: select
