id: firebase
name: firebase
version: v1.0.1
providerServices:
  fcm:
    description: FCM send API that provides a cross-platform messaging solution to reliably deliver messages at no cost.
    id: fcm:v1.0.1
    name: fcm
    preferred: true
    service:
      $ref: firebase/v1.0.1/services/fcm.yaml
    title: Firebase Cloud Messaging API
    version: v1.0.1
  fcmdata:
    description: Provides additional information about Firebase Cloud Messaging (FCM) message sends and deliveries.
    id: fcmdata:v1.0.1
    name: fcmdata
    preferred: true
    service:
      $ref: firebase/v1.0.1/services/fcmdata.yaml
    title: Firebase Cloud Messaging Data API
    version: v1.0.1
  firebaseappcheck:
    description: Firebase App Check works alongside other Firebase services to help protect your backend resources from abuse, such as billing fraud or phishing.
    id: firebaseappcheck:v1.0.1
    name: firebaseappcheck
    preferred: true
    service:
      $ref: firebase/v1.0.1/services/firebaseappcheck.yaml
    title: Firebase App Check API
    version: v1.0.1
  firebasedatabase:
    description: The Firebase Realtime Database Management API enables programmatic provisioning and management of Realtime Database instances.
    id: firebasedatabase:v1.0.1
    name: firebasedatabase
    preferred: true
    service:
      $ref: firebase/v1.0.1/services/firebasedatabase.yaml
    title: Firebase Realtime Database Management API
    version: v1.0.1
  firebasedynamiclinks:
    description: Programmatically creates and manages Firebase Dynamic Links.
    id: firebasedynamiclinks:v1.0.1
    name: firebasedynamiclinks
    preferred: true
    service:
      $ref: firebase/v1.0.1/services/firebasedynamiclinks.yaml
    title: Firebase Dynamic Links API
    version: v1.0.1
  firebasehosting:
    description: The Firebase Hosting REST API enables programmatic and customizable management and deployments to your Firebase-hosted sites. Use this REST API to create and manage channels and sites as well as to deploy new or updated hosting configurations and content files.
    id: firebasehosting:v1.0.1
    name: firebasehosting
    preferred: true
    service:
      $ref: firebase/v1.0.1/services/firebasehosting.yaml
    title: Firebase Hosting API
    version: v1.0.1
  firebaserules:
    description: 'Creates and manages rules that determine when a Firebase Rules-enabled service should permit a request. '
    id: firebaserules:v1.0.1
    name: firebaserules
    preferred: true
    service:
      $ref: firebase/v1.0.1/services/firebaserules.yaml
    title: Firebase Rules API
    version: v1.0.1
  firebasestorage:
    description: The Cloud Storage for Firebase API enables programmatic management of Cloud Storage buckets for use in Firebase projects
    id: firebasestorage:v1.0.1
    name: firebasestorage
    preferred: true
    service:
      $ref: firebase/v1.0.1/services/firebasestorage.yaml
    title: Cloud Storage for Firebase API
    version: v1.0.1
  toolresults:
    description: API to publish and access results from developer tools.
    id: toolresults:v1.0.1
    name: toolresults
    preferred: true
    service:
      $ref: firebase/v1.0.1/services/toolresults.yaml
    title: Cloud Tool Results API
    version: v1.0.1
openapi: 3.1.0
