openapi: 3.0.3
info:
  title: api_tokens API
  description: okta api_tokens API
  version: 5.1.0
paths:
  /api/v1/api-tokens:
    get:
      summary: List all API token metadata
      description: Lists all the metadata of the active API tokens
      operationId: listApiTokens
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiToken'
              examples:
                List Tokens:
                  $ref: '#/components/examples/ApiTokenListMetadataResponse'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.apiTokens.read
      tags:
        - ApiToken
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
  /api/v1/api-tokens/current:
    delete:
      summary: Revoke the current API token
      description: Revokes the API token provided in the Authorization header
      operationId: revokeCurrentApiToken
      responses:
        '204':
          description: No Content
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
      tags:
        - ApiToken
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
  /api/v1/api-tokens/{apiTokenId}:
    get:
      summary: Retrieve an API token's metadata
      description: Retrieves the metadata for an active API token by `apiTokenId`
      operationId: getApiToken
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiToken'
              examples:
                HCaptcha:
                  $ref: '#/components/examples/ApiTokenMetadataResponse'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.apiTokens.read
      tags:
        - ApiToken
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    put:
      summary: Upsert an API token network condition
      description: Upserts an API Token Network Condition by `apiTokenId`
      operationId: upsertApiToken
      requestBody:
        content:
          application/json:
            example:
              name: api_token_name
              clientName: client_name
              userId: 00uabcdefg1234567890
              network:
                connection: ANYWHERE
              created: '2021-11-09T20:38:10.000Z'
            schema:
              $ref: '#/components/schemas/ApiTokenUpdate'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiToken'
              examples:
                HCaptcha:
                  $ref: '#/components/examples/ApiTokenMetadataResponse'
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.apiTokens.manage
      tags:
        - ApiToken
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    delete:
      summary: Revoke an API token
      description: Revokes an API token by `apiTokenId`
      operationId: revokeApiToken
      responses:
        '204':
          description: No Content
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.apiTokens.manage
      tags:
        - ApiToken
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    parameters:
      - $ref: '#/components/parameters/pathApiTokenId'
components:
  schemas:
    ApiToken:
      title: API Token
      description: >-
        An API token for an Okta User. This token is NOT scoped any further and
        can be used for any API the user has permissions to call.
      type: object
      properties:
        clientName:
          type: string
          readOnly: true
        created:
          type: string
          format: date-time
          readOnly: true
        expiresAt:
          type: string
          format: date-time
          readOnly: true
        id:
          type: string
          readOnly: true
        lastUpdated:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
        network:
          type: object
          description: The Network Condition of the API Token
          properties:
            connection:
              type: string
              description: The connection type of the Network Condition
            include:
              type: array
              description: List of included IP network zones
              items:
                type: string
            exclude:
              type: array
              description: List of excluded IP network zones
              items:
                type: string
        tokenWindow:
          $ref: '#/components/schemas/TimeDuration'
        userId:
          type: string
        _link:
          $ref: '#/components/schemas/LinksSelf'
      required:
        - name
    ApiTokenUpdate:
      title: API Token Update
      description: >-
        An API Token Update Object for an Okta user. This token is NOT scoped
        any further and can be used for any API that the user has permissions to
        call.
      type: object
      properties:
        clientName:
          type: string
          description: The client name associated with the API Token
          readOnly: true
        created:
          type: string
          description: The creation date of the API Token
          format: date-time
          readOnly: true
        name:
          type: string
          description: The name associated with the API Token
        network:
          type: object
          description: The Network Condition of the API Token
          properties:
            connection:
              type: string
              description: The connection type of the Network Condition
            include:
              type: array
              description: List of included IP network zones
              items:
                type: string
            exclude:
              type: array
              description: List of excluded IP network zones
              items:
                type: string
        userId:
          type: string
          description: The userId of the user who created the API Token
    TimeDuration:
      description: >-
        A time duration specified as an [ISO 8601
        duration](https://en.wikipedia.org/wiki/ISO_8601#Durations).
      type: string
      pattern: ^P(?:$)(\d+Y)?(\d+M)?(\d+W)?(\d+D)?(T(?:\d)(\d+H)?(\d+M)?(\d+S)?)?$
    LinksSelf:
      description: >-
        Specifies link relations (see [Web
        Linking](https://www.rfc-editor.org/rfc/rfc8288)) available using the
        [JSON Hypertext Application
        Language](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal-06)
        specification. This object is used for dynamic discovery of related
        resources and lifecycle operations.
      type: object
      properties:
        self:
          $ref: '#/components/schemas/HrefObjectSelfLink'
      readOnly: true
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    HrefObjectSelfLink:
      allOf:
        - $ref: '#/components/schemas/HrefObject'
        - description: Link to the resource (self)
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
    HrefObject:
      title: Link Object
      additionalProperties: true
      type: object
      properties:
        hints:
          $ref: '#/components/schemas/HrefHints'
          readOnly: true
        href:
          type: string
          description: Link URI
        name:
          type: string
          description: Link name
          readOnly: true
        templated:
          type: boolean
          description: >-
            Indicates whether the link object's `href` property is a URI
            template.
          readOnly: true
        type:
          type: string
          description: >-
            The media type of the link. If omitted, it is implicitly
            `application/json`.
          readOnly: true
      required:
        - href
    HrefHints:
      description: Describes allowed HTTP verbs for the `href`
      type: object
      properties:
        allow:
          type: array
          items:
            $ref: '#/components/schemas/HttpMethod'
    HttpMethod:
      type: string
      enum:
        - DELETE
        - GET
        - POST
        - PUT
  responses:
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorTooManyRequests429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            TooManyRequests:
              $ref: '#/components/examples/ErrorTooManyRequests'
    ErrorResourceNotFound404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            ResourceNotFound:
              $ref: '#/components/examples/ErrorResourceNotFound'
    ErrorApiValidationFailed400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            APIValidationFailed:
              $ref: '#/components/examples/ErrorApiValidationFailed'
  parameters:
    pathApiTokenId:
      name: apiTokenId
      in: path
      schema:
        type: string
        example: 00Tabcdefg1234567890
      required: true
      description: id of the API Token
  examples:
    ApiTokenListMetadataResponse:
      value:
        - name: My API Token
          userId: 00uabcdefg1234567890
          tokenWindow: P30D
          network:
            connection: ANYWHERE
          id: 00Tabcdefg1234567890
          clientName: Okta API
          expiresAt: '2021-12-11T20:38:10.000Z'
          created: '2021-11-09T20:38:10.000Z'
          lastUpdated: '2021-11-11T20:38:10.000Z'
          _links:
            self:
              href: https://{yourOktaDomain}/api/v1/api-tokens/00Tabcdefg1234567890
              hints:
                allow:
                  - GET
                  - DELETE
            user:
              href: https://{yourOktaDomain}/api/v1/users/00uabcdefg1234567890
              hints:
                allow:
                  - GET
        - name: Another API Token
          userId: 00uabcdefg1234567890
          tokenWindow: PT5M
          id: 00T1234567890abcdefg
          clientName: Okta API
          expiresAt: '2021-11-11T20:43:10.000Z'
          created: '2021-11-09T20:38:10.000Z'
          lastUpdated: '2021-11-11T20:38:10.000Z'
          _links:
            self:
              href: https://{yourOktaDomain}/api/v1/api-tokens/00T1234567890abcdefg
              hints:
                allow:
                  - GET
                  - DELETE
            user:
              href: https://{yourOktaDomain}/api/v1/users/00uabcdefg1234567890
              hints:
                allow:
                  - GET
    ApiTokenMetadataResponse:
      value:
        name: My API Token
        userId: 00uXXXXXXXXXXXXXXXXX
        tokenWindow: P30D
        network:
          connection: ANYWHERE
        id: 00Tabcdefg1234567890
        clientName: Okta API
        expiresAt: '2021-12-11T20:38:10.000Z'
        created: '2021-11-09T20:38:10.000Z'
        lastUpdated: '2021-11-11T20:38:10.000Z'
        _links:
          self:
            href: https://{yourOktaDomain}/api/v1/api-tokens/00Tabcdefg1234567890
            hints:
              allow:
                - GET
                - DELETE
          user:
            href: https://{yourOktaDomain}/api/v1/users/00uXXXXXXXXXXXXXXXXX
            hints:
              allow:
                - GET
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorTooManyRequests:
      summary: Too Many Requests
      value:
        errorCode: E0000047
        errorSummary: API call exceeded rate limit due to too many requests.
        errorLink: E0000047
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
    ErrorResourceNotFound:
      summary: Resource Not Found
      value:
        errorCode: E0000007
        errorSummary: 'Not found: {0}'
        errorLink: E0000007
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
    ErrorApiValidationFailed:
      summary: API Validation Failed
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: {0}'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses: []
  x-stackQL-resources:
    api_tokens:
      id: okta.api_tokens.api_tokens
      name: api_tokens
      title: Api Tokens
      methods:
        list_api_tokens:
          operation:
            $ref: '#/paths/~1api~1v1~1api-tokens/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        revoke_current_api_token:
          operation:
            $ref: '#/paths/~1api~1v1~1api-tokens~1current/delete'
          response:
            mediaType: ''
            openAPIDocKey: '204'
        get_api_token:
          operation:
            $ref: '#/paths/~1api~1v1~1api-tokens~1{apiTokenId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        upsert_api_token:
          operation:
            $ref: '#/paths/~1api~1v1~1api-tokens~1{apiTokenId}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        revoke_api_token:
          operation:
            $ref: '#/paths/~1api~1v1~1api-tokens~1{apiTokenId}/delete'
          response:
            mediaType: ''
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/api_tokens/methods/list_api_tokens
          - $ref: '#/components/x-stackQL-resources/api_tokens/methods/get_api_token'
        insert: []
        update: []
        delete:
          - $ref: >-
              #/components/x-stackQL-resources/api_tokens/methods/revoke_current_api_token
          - $ref: >-
              #/components/x-stackQL-resources/api_tokens/methods/revoke_api_token
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/api_tokens/methods/upsert_api_token
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
        description: >-
          The domain of your organization. This can be a provided subdomain of
          an official okta domain (okta.com, oktapreview.com, etc) or one of
          your configured custom domains.
