openapi: 3.0.3
info:
  title: behaviors API
  description: okta behaviors API
  version: 5.1.0
paths:
  /api/v1/behaviors:
    get:
      summary: List all behavior detection rules
      description: Lists all behavior detection rules with pagination support
      operationId: listBehaviorDetectionRules
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BehaviorRule'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.behaviors.read
      tags:
        - Behavior
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    post:
      summary: Create a behavior detection rule
      description: Creates a new behavior detection rule
      operationId: createBehaviorDetectionRule
      x-codegen-request-body-name: rule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BehaviorRule'
            examples:
              Behavior Rule Request:
                $ref: '#/components/examples/BehaviorRuleRequest'
        required: true
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BehaviorRule'
              examples:
                Behavior Rule Response:
                  $ref: '#/components/examples/BehaviorRuleResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                API Validation Failed:
                  $ref: '#/components/examples/ErrorApiValidationFailed'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.behaviors.manage
      tags:
        - Behavior
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
  /api/v1/behaviors/{behaviorId}:
    get:
      summary: Retrieve a behavior detection rule
      description: Retrieves a Behavior Detection Rule by `behaviorId`
      operationId: getBehaviorDetectionRule
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BehaviorRule'
              examples:
                Behavior Rule Response:
                  $ref: '#/components/examples/BehaviorRuleResponse'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Resource Not Found:
                  $ref: '#/components/examples/ErrorResourceNotFound'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.behaviors.read
      tags:
        - Behavior
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    put:
      summary: Replace a behavior detection rule
      description: Replaces a Behavior Detection Rule by `behaviorId`
      operationId: replaceBehaviorDetectionRule
      x-codegen-request-body-name: rule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BehaviorRule'
            examples:
              Behavior Rule Request:
                $ref: '#/components/examples/BehaviorRuleRequest'
        required: true
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BehaviorRule'
              examples:
                Behavior Rule Response:
                  $ref: '#/components/examples/BehaviorRuleResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                API Validation Failed:
                  $ref: '#/components/examples/ErrorApiValidationFailed'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Resource Not Found:
                  $ref: '#/components/examples/ErrorResourceNotFound'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.behaviors.manage
      tags:
        - Behavior
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    delete:
      summary: Delete a behavior detection rule
      description: Deletes a Behavior Detection Rule by `behaviorId`
      operationId: deleteBehaviorDetectionRule
      responses:
        '204':
          description: No Content
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Resource Not Found:
                  $ref: '#/components/examples/ErrorResourceNotFound'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.behaviors.manage
      tags:
        - Behavior
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    parameters:
      - $ref: '#/components/parameters/pathBehaviorId'
  /api/v1/behaviors/{behaviorId}/lifecycle/activate:
    post:
      summary: Activate a behavior detection rule
      description: Activates a behavior detection rule
      operationId: activateBehaviorDetectionRule
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BehaviorRule'
              examples:
                Behavior Rule Response:
                  $ref: '#/components/examples/BehaviorRuleResponse'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.behaviors.manage
      tags:
        - Behavior
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    parameters:
      - $ref: '#/components/parameters/pathBehaviorId'
  /api/v1/behaviors/{behaviorId}/lifecycle/deactivate:
    post:
      summary: Deactivate a behavior detection rule
      description: Deactivates a behavior detection rule
      operationId: deactivateBehaviorDetectionRule
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BehaviorRule'
              examples:
                Behavior Rule Response:
                  $ref: '#/components/examples/BehaviorRuleResponse'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.behaviors.manage
      tags:
        - Behavior
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    parameters:
      - $ref: '#/components/parameters/pathBehaviorId'
components:
  schemas:
    BehaviorRule:
      title: Behavior Detection Rule
      type: object
      properties:
        created:
          type: string
          description: Timestamp when the Behavior Detection Rule was created
          readOnly: true
        id:
          type: string
          description: ID of the Behavior Detection Rule
          readOnly: true
        lastUpdated:
          type: string
          description: Timestamp when the Behavior Detection Rule was last modified
          readOnly: true
        name:
          type: string
          description: Name of the Behavior Detection Rule
          maxLength: 128
        status:
          $ref: '#/components/schemas/LifecycleStatus'
        type:
          $ref: '#/components/schemas/BehaviorRuleType'
        _link:
          $ref: '#/components/schemas/LinksSelf'
      required:
        - name
        - type
      discriminator:
        propertyName: type
        mapping:
          ANOMALOUS_LOCATION: '#/components/schemas/BehaviorRuleAnomalousLocation'
          ANOMALOUS_IP: '#/components/schemas/BehaviorRuleAnomalousIP'
          ANOMALOUS_DEVICE: '#/components/schemas/BehaviorRuleAnomalousDevice'
          VELOCITY: '#/components/schemas/BehaviorRuleVelocity'
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    LifecycleStatus:
      type: string
      enum:
        - ACTIVE
        - INACTIVE
    BehaviorRuleType:
      type: string
      enum:
        - ANOMALOUS_DEVICE
        - ANOMALOUS_IP
        - ANOMALOUS_LOCATION
        - VELOCITY
    LinksSelf:
      description: >-
        Specifies link relations (see [Web
        Linking](https://www.rfc-editor.org/rfc/rfc8288)) available using the
        [JSON Hypertext Application
        Language](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal-06)
        specification. This object is used for dynamic discovery of related
        resources and lifecycle operations.
      type: object
      properties:
        self:
          $ref: '#/components/schemas/HrefObjectSelfLink'
      readOnly: true
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
    HrefObjectSelfLink:
      allOf:
        - $ref: '#/components/schemas/HrefObject'
        - description: Link to the resource (self)
    HrefObject:
      title: Link Object
      additionalProperties: true
      type: object
      properties:
        hints:
          $ref: '#/components/schemas/HrefHints'
          readOnly: true
        href:
          type: string
          description: Link URI
        name:
          type: string
          description: Link name
          readOnly: true
        templated:
          type: boolean
          description: >-
            Indicates whether the link object's `href` property is a URI
            template.
          readOnly: true
        type:
          type: string
          description: >-
            The media type of the link. If omitted, it is implicitly
            `application/json`.
          readOnly: true
      required:
        - href
    HrefHints:
      description: Describes allowed HTTP verbs for the `href`
      type: object
      properties:
        allow:
          type: array
          items:
            $ref: '#/components/schemas/HttpMethod'
    HttpMethod:
      type: string
      enum:
        - DELETE
        - GET
        - POST
        - PUT
  responses:
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorTooManyRequests429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            TooManyRequests:
              $ref: '#/components/examples/ErrorTooManyRequests'
    ErrorResourceNotFound404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            ResourceNotFound:
              $ref: '#/components/examples/ErrorResourceNotFound'
  parameters:
    pathBehaviorId:
      name: behaviorId
      in: path
      schema:
        type: string
        example: abcd1234
      required: true
      description: ID of the Behavior Detection Rule
  examples:
    BehaviorRuleRequest:
      value:
        name: My Behavior Rule
        type: VELOCITY
    BehaviorRuleResponse:
      value:
        id: abcd1234
        name: My Behavior Rule
        type: VELOCITY
        settings:
          velocityKph: 805
        status: ACTIVE
        created: '2021-11-09 20:38:10.0'
        lastUpdated: '2021-11-11 20:38:10.0'
        _link:
          self:
            href: https://your-subdomain.okta.com/api/v1/behaviors/abcd1234
            hints:
              allow:
                - GET
                - POST
                - PUT
                - DELETE
    ErrorApiValidationFailed:
      summary: API Validation Failed
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: {0}'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses: []
    ErrorResourceNotFound:
      summary: Resource Not Found
      value:
        errorCode: E0000007
        errorSummary: 'Not found: {0}'
        errorLink: E0000007
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorTooManyRequests:
      summary: Too Many Requests
      value:
        errorCode: E0000047
        errorSummary: API call exceeded rate limit due to too many requests.
        errorLink: E0000047
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
  x-stackQL-resources:
    behavior_detection_rules:
      id: okta.behaviors.behavior_detection_rules
      name: behavior_detection_rules
      title: Behavior Detection Rules
      methods:
        list_behavior_detection_rules:
          operation:
            $ref: '#/paths/~1api~1v1~1behaviors/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        create_behavior_detection_rule:
          operation:
            $ref: '#/paths/~1api~1v1~1behaviors/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get_behavior_detection_rule:
          operation:
            $ref: '#/paths/~1api~1v1~1behaviors~1{behaviorId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        replace_behavior_detection_rule:
          operation:
            $ref: '#/paths/~1api~1v1~1behaviors~1{behaviorId}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete_behavior_detection_rule:
          operation:
            $ref: '#/paths/~1api~1v1~1behaviors~1{behaviorId}/delete'
          response:
            mediaType: ''
            openAPIDocKey: '204'
        activate_behavior_detection_rule:
          operation:
            $ref: >-
              #/paths/~1api~1v1~1behaviors~1{behaviorId}~1lifecycle~1activate/post
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        deactivate_behavior_detection_rule:
          operation:
            $ref: >-
              #/paths/~1api~1v1~1behaviors~1{behaviorId}~1lifecycle~1deactivate/post
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/behavior_detection_rules/methods/list_behavior_detection_rules
          - $ref: >-
              #/components/x-stackQL-resources/behavior_detection_rules/methods/get_behavior_detection_rule
        insert:
          - $ref: >-
              #/components/x-stackQL-resources/behavior_detection_rules/methods/create_behavior_detection_rule
        update: []
        delete:
          - $ref: >-
              #/components/x-stackQL-resources/behavior_detection_rules/methods/delete_behavior_detection_rule
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/behavior_detection_rules/methods/replace_behavior_detection_rule
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
        description: >-
          The domain of your organization. This can be a provided subdomain of
          an official okta domain (okta.com, oktapreview.com, etc) or one of
          your configured custom domains.
