openapi: 3.0.3
info:
  title: bot_protection API
  description: okta bot_protection API
  version: 2026.07.2
paths:
  /api/v1/bot-protection/configuration:
    get:
      summary: Retrieve the bot protection configuration
      description: Retrieves the bot protection configuration for your org
      operationId: getBotProtectionConfiguration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BotProtectionConfiguration'
              examples:
                Default:
                  $ref: '#/components/examples/BotProtectionConfigurationDefault'
                Enforced:
                  $ref: '#/components/examples/BotProtectionConfigurationEnforced'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.botProtection.read
      tags:
        - BotProtection
      x-okta-lifecycle:
        lifecycle: LIMITED_GA
        isGenerallyAvailable: false
        SKUs: []
    post:
      summary: Update the bot protection configuration
      description: Updates the bot protection configuration for your org
      operationId: updateBotProtectionConfiguration
      x-codegen-request-body-name: botProtectionConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BotProtectionConfiguration'
            examples:
              LogOnly:
                $ref: '#/components/examples/BotProtectionConfigurationRequestLogOnly'
              Enforced:
                $ref: >-
                  #/components/examples/BotProtectionConfigurationRequestEnforced
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BotProtectionConfiguration'
              examples:
                LogOnly:
                  $ref: '#/components/examples/BotProtectionConfigurationDefault'
                Enforced:
                  $ref: '#/components/examples/BotProtectionConfigurationEnforced'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                ApiValidationFailed:
                  $ref: '#/components/examples/ErrorApiValidationFailed'
                LevelRequired:
                  $ref: '#/components/examples/ErrorBotProtectionLevelRequired'
                ModeRequired:
                  $ref: '#/components/examples/ErrorBotProtectionModeRequired'
                EnforcementTypeRequired:
                  $ref: >-
                    #/components/examples/ErrorBotProtectionEnforcementTypeRequired
                SupportedFlowsRequired:
                  $ref: >-
                    #/components/examples/ErrorBotProtectionSupportedFlowsRequired
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.botProtection.manage
      tags:
        - BotProtection
      x-okta-lifecycle:
        lifecycle: LIMITED_GA
        isGenerallyAvailable: false
        SKUs: []
components:
  schemas:
    BotProtectionConfiguration:
      title: BotProtectionConfiguration
      description: Bot protection configuration for the org
      type: object
      properties:
        enforcementType:
          $ref: '#/components/schemas/BotProtectionEnforcementType'
        level:
          $ref: '#/components/schemas/BotProtectionLevel'
        mode:
          $ref: '#/components/schemas/BotProtectionMode'
        supportedFlows:
          description: An array of authentication flows that have bot protection enabled
          type: array
          items:
            $ref: '#/components/schemas/BotProtectionSupportedFlow'
        _links:
          $ref: '#/components/schemas/LinksSelf'
      required:
        - level
        - mode
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    BotProtectionEnforcementType:
      description: The type of enforcement to trigger when a bot is detected
      type: string
      enum:
        - OKTA_CHALLENGE
      x-enumDescriptions:
        OKTA_CHALLENGE: The Okta built-in challenge mechanism
    BotProtectionLevel:
      description: The sensitivity level of bot detection
      type: string
      enum:
        - ANY
        - HIGH
        - LOW
        - MEDIUM
      x-enumDescriptions:
        HIGH: >-
          High - Flags only high-confidence bot requests. Prioritizes a
          frictionless user experience.
        MEDIUM: >-
          Medium and above - Flags moderate and high-confidence bot requests.
          Provides a balanced experience and security.
        LOW: >-
          Low and above - Flags low-confidence bot requests. Prioritizes a
          rigorous security.
        ANY: >-
          Always flag all requests to trigger enforcement settings, regardless
          of bot likeliness confidence level.
    BotProtectionMode:
      description: The enforcement mode for bot protection
      type: string
      enum:
        - DISABLED
        - ENFORCED
        - LOG_ONLY
      x-enumDescriptions:
        DISABLED: Bot protection is disabled
        LOG_ONLY: Bot detection events are logged but not enforced
        ENFORCED: Enforcement is applied to events where bots are detected
    BotProtectionSupportedFlow:
      description: Authentication flows that support bot protection
      type: string
      enum:
        - SIGN_IN
        - SSPR
        - SSR
      x-enumDescriptions:
        SIGN_IN: User sign-in page
        SSPR: Self-Service Password Recovery page
        SSR: Self-Service Registration page
    LinksSelf:
      description: >-
        Specifies link relations (see [Web
        Linking](https://www.rfc-editor.org/rfc/rfc8288)) available using the
        [JSON Hypertext Application
        Language](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal-06)
        specification. This object is used for dynamic discovery of related
        resources and lifecycle operations.
      type: object
      properties:
        self:
          $ref: '#/components/schemas/HrefObjectSelfLink'
      readOnly: true
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
    HrefObjectSelfLink:
      x-okta-ignore-redocly-rules-for-sdk: true
      title: Link Object
      additionalProperties: true
      type: object
      properties:
        hints:
          $ref: '#/components/schemas/HrefHints'
          readOnly: true
        href:
          type: string
          description: Link URI
        name:
          type: string
          description: Link name
          readOnly: true
        templated:
          type: boolean
          description: >-
            Indicates whether the link object's `href` property is a URI
            template.
          readOnly: true
        type:
          type: string
          description: >-
            The media type of the link. If omitted, it is implicitly
            `application/json`.
          readOnly: true
      required:
        - href
      description: Link to the resource (self)
    HrefObject:
      x-okta-ignore-redocly-rules-for-sdk: true
      title: Link Object
      additionalProperties: true
      type: object
      properties:
        hints:
          $ref: '#/components/schemas/HrefHints'
          readOnly: true
        href:
          type: string
          description: Link URI
        name:
          type: string
          description: Link name
          readOnly: true
        templated:
          type: boolean
          description: >-
            Indicates whether the link object's `href` property is a URI
            template.
          readOnly: true
        type:
          type: string
          description: >-
            The media type of the link. If omitted, it is implicitly
            `application/json`.
          readOnly: true
      required:
        - href
    HrefHints:
      description: Describes allowed HTTP verbs for the `href`
      type: object
      properties:
        allow:
          type: array
          items:
            $ref: '#/components/schemas/HttpMethod'
    HttpMethod:
      type: string
      enum:
        - DELETE
        - GET
        - POST
        - PUT
  responses:
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorTooManyRequests429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            TooManyRequests:
              $ref: '#/components/examples/ErrorTooManyRequests'
  examples:
    BotProtectionConfigurationDefault:
      summary: Default bot protection configuration (`LOG_ONLY` mode)
      value:
        level: LOW
        mode: LOG_ONLY
        supportedFlows:
          - SIGN_IN
          - SSR
          - SSPR
        _links:
          self:
            href: https://{yourOktaDomain}/api/v1/bot-protection/configuration
            hints:
              allow:
                - GET
                - POST
    BotProtectionConfigurationEnforced:
      summary: Enforced bot protection configuration
      value:
        level: MEDIUM
        mode: ENFORCED
        enforcementType: OKTA_CHALLENGE
        supportedFlows:
          - SIGN_IN
          - SSR
          - SSPR
        _links:
          self:
            href: https://{yourOktaDomain}/api/v1/bot-protection/configuration
            hints:
              allow:
                - GET
                - POST
    BotProtectionConfigurationRequestLogOnly:
      summary: Update to `LOG_ONLY` mode
      value:
        level: LOW
        mode: LOG_ONLY
        supportedFlows:
          - SIGN_IN
          - SSR
          - SSPR
    BotProtectionConfigurationRequestEnforced:
      summary: Update to `ENFORCED` mode
      value:
        level: MEDIUM
        mode: ENFORCED
        enforcementType: OKTA_CHALLENGE
        supportedFlows:
          - SSR
          - SSPR
    ErrorApiValidationFailed:
      summary: API Validation Failed
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: {0}'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses: []
    ErrorBotProtectionLevelRequired:
      summary: Level is required
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: level'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses:
          - errorSummary: 'level: The field cannot be left blank'
    ErrorBotProtectionModeRequired:
      summary: Mode is required
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: mode'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses:
          - errorSummary: 'mode: The field cannot be left blank'
    ErrorBotProtectionEnforcementTypeRequired:
      summary: Enforcement type is required when mode is ENFORCED
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: enforcementType'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses:
          - errorSummary: >-
              enforcementType: Api validation failed: enforcementType must be
              provided when mode is ENFORCED
    ErrorBotProtectionSupportedFlowsRequired:
      summary: Supported flows must have at least one flow
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: supportedFlows'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses:
          - errorSummary: >-
              supportedFlows: Api validation failed: supportedFlows must have at
              least one supported flow
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorTooManyRequests:
      summary: Too Many Requests
      value:
        errorCode: E0000047
        errorSummary: API call exceeded rate limit due to too many requests.
        errorLink: E0000047
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
  x-stackQL-resources:
    bot_protection_configuration:
      id: okta.bot_protection.bot_protection_configuration
      name: bot_protection_configuration
      title: Bot Protection Configuration
      methods:
        get_bot_protection_configuration:
          operation:
            $ref: '#/paths/~1api~1v1~1bot-protection~1configuration/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        update_bot_protection_configuration:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1api~1v1~1bot-protection~1configuration/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/bot_protection_configuration/methods/get_bot_protection_configuration
        insert: []
        update:
          - $ref: >-
              #/components/x-stackQL-resources/bot_protection_configuration/methods/update_bot_protection_configuration
        delete: []
        replace: []
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
x-stackQL-config:
  pagination:
    requestToken:
      key: ''
      location: request
    responseToken:
      key: Link
      location: header
  queryParamPushdown:
    top:
      paramName: limit
      maxValue: 200
