openapi: 3.0.3
info:
  title: device_access API
  description: okta device_access API
  version: 5.1.0
paths:
  /device-access/api/v1/desktop-mfa/enforce-number-matching-challenge-settings:
    get:
      summary: Retrieve the Desktop MFA Enforce Number Matching Challenge org setting
      description: >-
        Retrieves the status of the Desktop MFA Enforce Number Matching
        Challenge push notifications feature. That is, whether or not the
        feature is enabled for your org.
      operationId: getDesktopMFAEnforceNumberMatchingChallengeOrgSetting
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/DesktopMFAEnforceNumberMatchingChallengeOrgSetting
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.orgs.read
      tags:
        - DeviceAccess
      x-okta-lifecycle:
        lifecycle: LIMITED_GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
    put:
      summary: Replace the Desktop MFA Enforce Number Matching Challenge org setting
      description: >-
        Replaces the status of the Desktop MFA Enforce Number Matching Challenge
        push notifications feature. That is, whether or not the feature is
        enabled for your org.
      operationId: replaceDesktopMFAEnforceNumberMatchingChallengeOrgSetting
      x-codegen-request-body-name: DesktopMFAEnforceNumberMatchingChallengeOrgSetting
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/DesktopMFAEnforceNumberMatchingChallengeOrgSetting
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/DesktopMFAEnforceNumberMatchingChallengeOrgSetting
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Access Denied:
                  $ref: '#/components/examples/ErrorAccessDenied'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.orgs.manage
      tags:
        - DeviceAccess
      x-okta-lifecycle:
        lifecycle: LIMITED_GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
  /device-access/api/v1/desktop-mfa/recovery-pin-settings:
    get:
      summary: Retrieve the Desktop MFA Recovery PIN org setting
      description: >-
        Retrieves the status of the Desktop MFA Recovery PIN feature. That is,
        whether or not the feature is enabled for your org.
      operationId: getDesktopMFARecoveryPinOrgSetting
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DesktopMFARecoveryPinOrgSetting'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.orgs.read
      tags:
        - DeviceAccess
      x-okta-lifecycle:
        lifecycle: LIMITED_GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
    put:
      summary: Replace the Desktop MFA Recovery PIN org setting
      description: Replaces the Desktop MFA Recovery PIN feature for your org
      operationId: replaceDesktopMFARecoveryPinOrgSetting
      x-codegen-request-body-name: DesktopMFARecoveryPinOrgSetting
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DesktopMFARecoveryPinOrgSetting'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DesktopMFARecoveryPinOrgSetting'
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Access Denied:
                  $ref: '#/components/examples/ErrorAccessDenied'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.orgs.manage
      tags:
        - DeviceAccess
      x-okta-lifecycle:
        lifecycle: LIMITED_GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
components:
  schemas:
    DesktopMFAEnforceNumberMatchingChallengeOrgSetting:
      type: object
      properties:
        desktopMFAEnforceNumberMatchingChallengeEnabled:
          type: boolean
          description: >-
            Indicates whether or not the Desktop MFA Enforce Number Matching
            Challenge push notifications feature is enabled
          default: false
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    DesktopMFARecoveryPinOrgSetting:
      type: object
      properties:
        desktopMFARecoveryPinEnabled:
          type: boolean
          description: >-
            Indicates whether or not the Desktop MFA Recovery PIN feature is
            enabled
          default: false
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
  responses:
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorTooManyRequests429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            TooManyRequests:
              $ref: '#/components/examples/ErrorTooManyRequests'
    ErrorApiValidationFailed400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            APIValidationFailed:
              $ref: '#/components/examples/ErrorApiValidationFailed'
  examples:
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorTooManyRequests:
      summary: Too Many Requests
      value:
        errorCode: E0000047
        errorSummary: API call exceeded rate limit due to too many requests.
        errorLink: E0000047
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
    ErrorApiValidationFailed:
      summary: API Validation Failed
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: {0}'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses: []
  x-stackQL-resources:
    mfa_challenge_org_setting:
      id: okta.device_access.mfa_challenge_org_setting
      name: mfa_challenge_org_setting
      title: Mfa Challenge Org Setting
      methods:
        get_desktop_mfaenforce_number_matching_challenge_org_setting:
          operation:
            $ref: >-
              #/paths/~1device-access~1api~1v1~1desktop-mfa~1enforce-number-matching-challenge-settings/get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        replace_desktop_mfaenforce_number_matching_challenge_org_setting:
          operation:
            $ref: >-
              #/paths/~1device-access~1api~1v1~1desktop-mfa~1enforce-number-matching-challenge-settings/put
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/mfa_challenge_org_setting/methods/get_desktop_mfaenforce_number_matching_challenge_org_setting
        insert: []
        update: []
        delete: []
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/mfa_challenge_org_setting/methods/replace_desktop_mfaenforce_number_matching_challenge_org_setting
    mfa_recovery_pin_setting:
      id: okta.device_access.mfa_recovery_pin_setting
      name: mfa_recovery_pin_setting
      title: Mfa Recovery Pin Setting
      methods:
        get_desktop_mfarecovery_pin_org_setting:
          operation:
            $ref: >-
              #/paths/~1device-access~1api~1v1~1desktop-mfa~1recovery-pin-settings/get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        replace_desktop_mfarecovery_pin_org_setting:
          operation:
            $ref: >-
              #/paths/~1device-access~1api~1v1~1desktop-mfa~1recovery-pin-settings/put
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/mfa_recovery_pin_setting/methods/get_desktop_mfarecovery_pin_org_setting
        insert: []
        update: []
        delete: []
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/mfa_recovery_pin_setting/methods/replace_desktop_mfarecovery_pin_org_setting
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
        description: >-
          The domain of your organization. This can be a provided subdomain of
          an official okta domain (okta.com, oktapreview.com, etc) or one of
          your configured custom domains.
