openapi: 3.0.3
info:
  title: directories API
  description: okta directories API
  version: 5.1.0
paths:
  /api/v1/directories/{appInstanceId}/groups/modify:
    post:
      summary: Update an Active Directory group membership
      description: >-
        Updates an Active Directory group membership directly in Active
        Directory


        > **Note:** See **Before you begin: Active Directory integration with
        the following setup** in the [Use Okta Access Certifications to manage
        AD group
        membership](https://help.okta.com/okta_help.htm?type=oie&id=ad-bidirectional-group-mgt-configure)
        product documentation.
      operationId: updateADGroupMembership
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentAction'
            examples:
              addUserToGroup:
                $ref: '#/components/examples/add-user-request'
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                APIValidationFailed:
                  $ref: '#/components/examples/ErrorApiValidationFailed'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '502':
          $ref: '#/components/responses/Error502NoConnectedAgents'
        '504':
          $ref: '#/components/responses/Error504AgentTimeOut'
      security:
        - oauth2:
            - okta.directories.groups.manage
      tags:
        - DirectoriesIntegration
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    parameters:
      - $ref: '#/components/parameters/appInstanceId'
components:
  schemas:
    AgentAction:
      description: Details about the Active Directory group membership update
      type: object
      properties:
        id:
          type: string
          description: ID of the Active Directory group to update
        parameters:
          $ref: '#/components/schemas/Parameters'
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    Parameters:
      description: Attributes used for processing Active Directory group membership update
      type: object
      properties:
        action:
          type: string
          description: The update action to take
          enum:
            - ADD
            - REMOVE
          x-enumDescriptions:
            ADD: Add to the membership of the group
            REMOVE: Remove from the membership of the group
        attribute:
          type: string
          description: >-
            The attribute that tracks group memberships in Active Directory. For
            Active Directory, use `member`.
          example: member
        values:
          type: array
          description: List of user IDs whose group memberships to update
          items:
            type: string
            description: ID of an existing user
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
  responses:
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorResourceNotFound404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            ResourceNotFound:
              $ref: '#/components/examples/ErrorResourceNotFound'
    Error502NoConnectedAgents:
      description: There are no connected agents.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AgentTimeOut:
              $ref: '#/components/examples/ErrorNoConnectedAgents'
    Error504AgentTimeOut:
      description: Timed out waiting for agent
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AgentTimeOut:
              $ref: '#/components/examples/ErrorAgentTimeOut'
  parameters:
    appInstanceId:
      name: appInstanceId
      in: path
      description: ID of the Active Directory app instance in Okta
      schema:
        type: string
      required: true
  examples:
    add-user-request:
      summary: Add user to group
      value:
        id: 00g1xucgTZFrziXg10g4
        parameters:
          action: ADD
          attribute: member
          values:
            - 00u1bh5efGKMsSiLv0g4
    ErrorApiValidationFailed:
      summary: API Validation Failed
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: {0}'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses: []
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorResourceNotFound:
      summary: Resource Not Found
      value:
        errorCode: E0000007
        errorSummary: 'Not found: {0}'
        errorLink: E0000007
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
    ErrorNoConnectedAgents:
      value:
        errorCode: E0000236
        errorSummary: There are no connected agents
        errorLink: E0000236
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
    ErrorAgentTimeOut:
      value:
        errorCode: E0000237
        errorSummary: Timed out waiting for agent
        errorLink: E0000237
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
  x-stackQL-resources:
    directories_integration:
      id: okta.directories.directories_integration
      name: directories_integration
      title: Directories Integration
      methods:
        update_adgroup_membership:
          operation:
            $ref: >-
              #/paths/~1api~1v1~1directories~1{appInstanceId}~1groups~1modify/post
          response:
            mediaType: ''
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update:
          - $ref: >-
              #/components/x-stackQL-resources/directories_integration/methods/update_adgroup_membership
        delete: []
        replace: []
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
        description: >-
          The domain of your organization. This can be a provided subdomain of
          an official okta domain (okta.com, oktapreview.com, etc) or one of
          your configured custom domains.
