openapi: 3.0.3
info:
  title: directories API
  description: okta directories API
  version: 2026.07.2
paths:
  /api/v1/directories/{appInstanceId}/groups/modify:
    post:
      summary: Update an external directory group membership
      description: |-
        Updates an Active Directory or LDAP  group membership directly in the Active Directory or LDAP server.

        You can add or remove users from groups based on their identity and access requirements. This ensures that changes made to user access in Okta are reflected in AD or LDAP. When you use Okta Access Certifications to revoke a user's membership to an AD or LDAP group, the removal is reflected in AD or LDAP.

        See [AD Bidirectional Group Management](https://help.okta.com/okta_help.htm?type=oie&id=ad-bidirectional-group-mgmt) and [LDAP Bidirectional Group Management](https://help.okta.com/okta_help.htm?type=oie&id=ldap-bidirectional-group-mgmt).
      operationId: updateGroupMembership
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentAction'
            examples:
              addADUserToGroup:
                $ref: '#/components/examples/add-user-request'
              addLdapUserToGroup:
                $ref: '#/components/examples/add-ldap-user-request'
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                APIValidationFailed:
                  $ref: '#/components/examples/ErrorApiValidationFailed'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '502':
          $ref: '#/components/responses/Error502NoConnectedAgents'
        '504':
          $ref: '#/components/responses/Error504AgentTimeOut'
      security:
        - oauth2:
            - okta.directories.groups.manage
      tags:
        - DirectoriesIntegration
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
      parameters:
        - $ref: '#/components/parameters/appInstanceId'
  /api/v1/directories/{appInstanceId}/groups/{groupId}/query:
    post:
      summary: Submit a query for AD Group
      description: |-
        Submits a query search on the on-premises agent to asynchronously fetch specific Active Directory (AD) attributes for a group.
        Returns a `resultId` that is used to poll for the results.
      operationId: submitGroupAttributeQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupQueryRequest'
      responses:
        '202':
          description: Accepted. Query initiated.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '502':
          $ref: '#/components/responses/Error502NoConnectedAgents'
        '504':
          $ref: '#/components/responses/Error504AgentTimeOut'
      security:
        - oauth2:
            - okta.directories.groups.read
      tags:
        - DirectoriesIntegration
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
      parameters:
        - $ref: '#/components/parameters/adAppInstanceId'
        - $ref: '#/components/parameters/groupId'
  /api/v1/directories/{appInstanceId}/groups/{groupId}/query/{resultId}:
    get:
      summary: Retrieve the results of an AD group query
      description: |-
        Retrieves the results of the requested Active Directory (AD) group attributes using the `resultId` returned from the `POST /api/v1/directories/{appInstanceId}/groups/{groupId}/query` call.
        If the operation has expired or if the `resultId` is invalid, returns a `404` status.
      operationId: getGroupAttributeQueryResult
      responses:
        '200':
          description: OK. Returns the group profile.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupProfileResult'
        '202':
          description: Accepted. Query is still in progress.
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
      security:
        - oauth2:
            - okta.directories.groups.read
      tags:
        - DirectoriesIntegration
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
      parameters:
        - $ref: '#/components/parameters/adAppInstanceId'
        - $ref: '#/components/parameters/groupId'
        - $ref: '#/components/parameters/queryResultId'
components:
  schemas:
    AgentAction:
      description: Details about the Active Directory or LDAP group membership update
      type: object
      properties:
        id:
          type: string
          description: ID of the Active Directory or LDAP group to update
        parameters:
          $ref: '#/components/schemas/Parameters'
      required:
        - id
        - parameters
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: A unique identifier for this error. This can be used by Okta Support to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: A short description of what caused this error. Sometimes this contains dynamically-generated information about your specific error.
    GroupQueryRequest:
      type: object
      properties:
        attributes:
          type: array
          items:
            type: string
          description: 'An array of LDAP group attribute names to retrieve. Restricted attributes: member, memberOf, *'
          example:
            - distinguishedName
            - description
            - cn
            - whenCreated
      required:
        - attributes
    GroupQueryResponse:
      type: object
      properties:
        resultId:
          type: string
          description: Identifier used to poll for the query result
          example: rdj4edr7pSDGv8QF10g4
    GroupProfileResult:
      type: object
      properties:
        id:
          type: string
          description: The ID of the group
          example: 00g19oiNHkbKFvNTX0g4
        profile:
          type: object
          additionalProperties: true
          description: Map of requested attributes and their values
          example:
            distinguishedName: CN=Finance,OU=Groups,DC=example,DC=com
            description: Finance Department Group
            cn: CN=Finance
            whenCreated: 20230101000000.0Z
    Parameters:
      description: Attributes used for processing Active Directory or LDAP group membership update
      type: object
      properties:
        action:
          type: string
          description: The update action to take
          enum:
            - ADD
            - REMOVE
          x-enumDescriptions:
            ADD: Add to the membership of the group
            REMOVE: Remove from the membership of the group
        attribute:
          type: string
          description: The attribute that tracks group memberships in Active Directory or LDAP. For Active Directory, use `member`. For LDAP, use the appropriate attribute found in the LDAP server such as, but not limited to, `uniqueMember` or `member`.
          example: member
        values:
          type: array
          description: List of user IDs whose group memberships to update
          items:
            type: string
            description: ID of an existing user
      required:
        - action
        - attribute
        - values
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
  responses:
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorResourceNotFound404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            ResourceNotFound:
              $ref: '#/components/examples/ErrorResourceNotFound'
    Error502NoConnectedAgents:
      description: There are no connected agents.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AgentTimeOut:
              $ref: '#/components/examples/ErrorNoConnectedAgents'
    Error504AgentTimeOut:
      description: Timed out waiting for agent
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AgentTimeOut:
              $ref: '#/components/examples/ErrorAgentTimeOut'
  parameters:
    appInstanceId:
      name: appInstanceId
      in: path
      description: ID of the Active Directory or LDAP app instance in Okta
      schema:
        type: string
      required: true
    adAppInstanceId:
      name: appInstanceId
      in: path
      description: ID of the AD instance in Okta
      schema:
        type: string
      required: true
      example: 00a1xucgTZFrziXg10g4
    groupId:
      name: groupId
      in: path
      description: ID of the Okta group
      required: true
      schema:
        type: string
      example: 00g1xucgTZFrziXg10g4
    queryResultId:
      name: resultId
      in: path
      description: The unique identifier returned by the initial POST request (`POST /api/v1/directories/{appInstanceId}/groups/{groupId}/query`)
      required: true
      schema:
        type: string
  examples:
    add-user-request:
      summary: Add AD user to group
      value:
        id: 00g1xucgTZFrziXg10g4
        parameters:
          action: ADD
          attribute: member
          values:
            - 00u1bh5efGKMsSiLv0g4
    add-ldap-user-request:
      summary: Add LDAP user to group
      value:
        id: 00g1xucgTZFrziXg10g4
        parameters:
          action: ADD
          attribute: uniqueMember
          values:
            - 00u1bh5efGKMsSiLv0g4
    ErrorApiValidationFailed:
      summary: API Validation Failed
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: {0}'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses: []
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorResourceNotFound:
      summary: Resource Not Found
      value:
        errorCode: E0000007
        errorSummary: 'Not found: {0}'
        errorLink: E0000007
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
    ErrorNoConnectedAgents:
      value:
        errorCode: E0000236
        errorSummary: There are no connected agents
        errorLink: E0000236
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
    ErrorAgentTimeOut:
      value:
        errorCode: E0000237
        errorSummary: Timed out waiting for agent
        errorLink: E0000237
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
  x-stackQL-resources:
    directories_integration:
      id: okta.directories.directories_integration
      name: directories_integration
      title: Directories Integration
      methods:
        update_group_membership:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1api~1v1~1directories~1{appInstanceId}~1groups~1modify/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        submit_group_attribute_query:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1api~1v1~1directories~1{appInstanceId}~1groups~1{groupId}~1query/post'
          response:
            mediaType: application/json
            openAPIDocKey: '202'
        get_group_attribute_query_result:
          operation:
            $ref: '#/paths/~1api~1v1~1directories~1{appInstanceId}~1groups~1{groupId}~1query~1{resultId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/directories_integration/methods/get_group_attribute_query_result'
        insert: []
        update: []
        delete: []
        replace: []
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
x-stackQL-config:
  pagination:
    requestToken:
      key: ''
      location: request
    responseToken:
      key: Link
      location: header
  queryParamPushdown:
    top:
      paramName: limit
      maxValue: 200
