openapi: 3.0.3
info:
  title: dr API
  description: okta dr API
  version: 2026.07.2
paths:
  /api/v1/dr/failback:
    post:
      x-okta-lifecycle:
        lifecycle: EA
      summary: Start the failback of your org
      description: Starts the failback of your org
      operationId: startOrgFailback
      requestBody:
        required: false
        description: >-
          The request body is optional. You can specify a domain to failback, an
          empty object (`{}`), or no payload.
        content:
          application/json:
            schema:
              x-okta-ignore-redocly-rules-for-sdk: true
              title: Domains
              type: object
              properties:
                domains:
                  type: array
                  description: The Okta domain to failback
                  items:
                    type: string
                    description: Okta domain to failback
                    example: yourOktaDomain.okta.com
              description: Empty object payload
              additionalProperties: false
            examples:
              example1:
                summary: A sample Okta domain to failback
                value:
                  domains:
                    - yourOktaDomain.okta.com
              example2:
                summary: An empty object
                value: {}
      responses:
        '200':
          $ref: '#/components/responses/FailbackResponse'
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '401':
          $ref: '#/components/responses/ErrorInvalidToken401'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
        '500':
          $ref: '#/components/responses/ErrorInternalServer500'
      security:
        - oauth2:
            - okta.dr.manage
      tags:
        - DisasterRecovery
  /api/v1/dr/failover:
    post:
      x-okta-lifecycle:
        lifecycle: EA
      summary: Start the failover of your org
      description: Starts the failover of your org
      operationId: startOrgFailover
      requestBody:
        required: false
        description: >-
          The request body is optional. You can specify a domain to failover, an
          empty object (`{}`), or no payload.
        content:
          application/json:
            schema:
              x-okta-ignore-redocly-rules-for-sdk: true
              title: Domains
              type: object
              properties:
                domains:
                  type: array
                  description: The Okta domain to failover
                  items:
                    type: string
                    description: Okta domain to failover
                    example: yourOktaDomain.okta.com
              description: Empty object payload
              additionalProperties: false
            examples:
              example1:
                summary: A sample Okta domain to failover
                value:
                  domains:
                    - yourOktaDomain.okta.com
              example2:
                summary: An empty object
                value: {}
      responses:
        '200':
          $ref: '#/components/responses/FailoverResponse'
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '401':
          $ref: '#/components/responses/ErrorInvalidToken401'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
        '500':
          $ref: '#/components/responses/ErrorInternalServer500'
      security:
        - oauth2:
            - okta.dr.manage
      tags:
        - DisasterRecovery
  /api/v1/dr/status:
    get:
      x-okta-lifecycle:
        lifecycle: EA
      summary: Retrieve the disaster recovery status for all domains
      description: >-
        Retrieves the failover or failback status for all the domains for your
        org
      operationId: getDRStatus
      responses:
        '200':
          $ref: '#/components/responses/DRStatusResponse'
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '401':
          $ref: '#/components/responses/ErrorInvalidToken401'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
        '500':
          $ref: '#/components/responses/ErrorInternalServer500'
      security:
        - oauth2:
            - okta.dr.read
      tags:
        - DisasterRecovery
  /api/v1/dr/status/{domain}:
    get:
      x-okta-lifecycle:
        lifecycle: EA
      summary: Retrieve the disaster recovery status for a domain
      description: >-
        Retrieves the failover or failback status for the domain specified in
        the request path
      operationId: getDRStatusForDomain
      responses:
        '200':
          $ref: '#/components/responses/DRStatusResponse'
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '401':
          $ref: '#/components/responses/ErrorInvalidToken401'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
        '500':
          $ref: '#/components/responses/ErrorInternalServer500'
      security:
        - oauth2:
            - okta.dr.read
      tags:
        - DisasterRecovery
      parameters:
        - $ref: '#/components/parameters/domain'
components:
  schemas:
    FailbackRequestSchema:
      title: Domains
      type: object
      properties:
        domains:
          type: array
          description: The Okta domain to failback
          items:
            type: string
            description: Okta domain to failback
            example: yourOktaDomain.okta.com
    EmptyRequestSchema:
      x-okta-ignore-redocly-rules-for-sdk: true
      title: Empty
      description: Empty object payload
      additionalProperties: false
      type: object
    FailoverRequestSchema:
      title: Domains
      type: object
      properties:
        domains:
          type: array
          description: The Okta domain to failover
          items:
            type: string
            description: Okta domain to failover
            example: yourOktaDomain.okta.com
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    DRStatusItem:
      description: Status whether a domain has been failed over or not
      type: object
      properties:
        domain:
          type: string
          description: Domain for your org
        isFailedOver:
          type: boolean
          description: Indicates if the domain has been failed over
          nullable: false
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
  responses:
    FailbackResponse:
      description: OK
      content:
        application/json:
          schema:
            properties:
              results:
                type: array
                description: Results of the failback operation
                items:
                  properties:
                    domain:
                      type: string
                      description: Domain for your org
                      example: yourOktaDomain.okta.com
                    message:
                      type: string
                      description: Domain failback message
                      example: Failback was successful
                  type: object
            type: object
    ErrorApiValidationFailed400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            APIValidationFailed:
              $ref: '#/components/examples/ErrorApiValidationFailed'
    ErrorInvalidToken401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            InvalidTokenProvided:
              $ref: '#/components/examples/ErrorInvalidTokenProvided'
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorTooManyRequests429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            TooManyRequests:
              $ref: '#/components/examples/ErrorTooManyRequests'
    ErrorInternalServer500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            InternalServerError:
              $ref: '#/components/examples/ErrorInternalServer'
    FailoverResponse:
      description: OK
      content:
        application/json:
          schema:
            properties:
              results:
                type: array
                description: Results of the failover operation
                items:
                  properties:
                    domain:
                      type: string
                      description: Domain for your org
                      example: yourOktaDomain.okta.com
                    message:
                      type: string
                      description: Domain failover message
                      example: Failover was successful
                  type: object
            type: object
    DRStatusResponse:
      description: OK
      content:
        application/json:
          schema:
            properties:
              status:
                type: array
                description: List of domains and their disaster recovery status
                items:
                  $ref: '#/components/schemas/DRStatusItem'
            type: object
          example:
            status:
              - domain: yourOktaDomain.okta.com
                isFailedOver: true
      headers:
        Link:
          description: A link to the next page of responses
          schema:
            type: string
  parameters:
    domain:
      name: domain
      in: path
      description: The Okta domain name of your org or one of your custom domains
      required: true
      schema:
        type: string
  examples:
    ErrorApiValidationFailed:
      summary: API Validation Failed
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: {0}'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses: []
    ErrorInvalidTokenProvided:
      summary: Invalid Token Provided
      value:
        errorCode: E0000011
        errorSummary: Invalid token provided
        errorLink: E0000011
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorTooManyRequests:
      summary: Too Many Requests
      value:
        errorCode: E0000047
        errorSummary: API call exceeded rate limit due to too many requests.
        errorLink: E0000047
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
    ErrorInternalServer:
      summary: Internal Server Error
      value:
        errorCode: E0000009
        errorSummary: Internal Server Error
        errorLink: E0000000
        errorId: sampleAlJ82XS2SDB_vaNIWgcA
        errorCauses: []
  x-stackQL-resources:
    dr_operations:
      id: okta.dr.dr_operations
      name: dr_operations
      title: Dr Operations
      methods:
        start_org_failback:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1api~1v1~1dr~1failback/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        start_org_failover:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1api~1v1~1dr~1failover/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
        replace: []
    dr_status:
      id: okta.dr.dr_status
      name: dr_status
      title: Dr Status
      methods:
        get_drstatus:
          operation:
            $ref: '#/paths/~1api~1v1~1dr~1status/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.status
        get_drstatus_for_domain:
          operation:
            $ref: '#/paths/~1api~1v1~1dr~1status~1{domain}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.status
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/dr_status/methods/get_drstatus_for_domain
          - $ref: '#/components/x-stackQL-resources/dr_status/methods/get_drstatus'
        insert: []
        update: []
        delete: []
        replace: []
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
x-stackQL-config:
  pagination:
    requestToken:
      key: ''
      location: request
    responseToken:
      key: Link
      location: header
  queryParamPushdown:
    top:
      paramName: limit
      maxValue: 200
