openapi: 3.0.3
info:
  title: okta_personal_settings API
  description: okta okta_personal_settings API
  version: 5.1.0
paths:
  /okta-personal-settings/api/v1/edit-feature:
    put:
      summary: Replace the Okta Personal admin settings
      description: Replaces Okta Personal admin settings in a Workforce org
      operationId: replaceOktaPersonalAdminSettings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OktaPersonalAdminFeatureSettings'
            examples:
              exampleSettings:
                $ref: '#/components/examples/editFeatureExample'
        required: true
      responses:
        '204':
          description: No Content
          content: {}
        '401':
          $ref: '#/components/responses/Error-FF-NotEnabled-Response-401'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.personal.adminSettings.manage
      tags:
        - OktaPersonalSettings
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
  /okta-personal-settings/api/v1/export-blocklists:
    get:
      summary: List all blocked email domains
      description: Lists all blocked email domains which are excluded from app migration
      operationId: listPersonalAppsExportBlockList
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalAppsBlockList'
              examples:
                exampleSettings:
                  $ref: '#/components/examples/getBlockListExample'
        '401':
          $ref: '#/components/responses/Error-FF-NotEnabled-Response-401'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.personal.adminSettings.read
      tags:
        - OktaPersonalSettings
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    put:
      summary: Replace the blocked email domains
      description: >-
        Replaces the list of blocked email domains which are excluded from app
        migration
      operationId: replaceBlockedEmailDomains
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonalAppsBlockList'
            examples:
              exampleSettings:
                $ref: '#/components/examples/getBlockListExample'
        required: true
      responses:
        '204':
          description: No Content
          content: {}
        '401':
          $ref: '#/components/responses/Error-FF-NotEnabled-Response-401'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.personal.adminSettings.manage
      tags:
        - OktaPersonalSettings
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
components:
  schemas:
    OktaPersonalAdminFeatureSettings:
      description: >-
        Defines a list of Okta Personal settings that can be enabled or disabled
        for the org
      type: object
      properties:
        enableEnduserEntryPoints:
          type: boolean
          description: Allow entry points for an Okta Personal account in a Workforce org
        enableExportApps:
          type: boolean
          description: >-
            Allow users to migrate apps from a Workforce account to an Okta
            Personal account
    PersonalAppsBlockList:
      description: >-
        Defines a list of email domains with a subset of the properties for each
        domain
      type: object
      properties:
        domains:
          type: array
          description: List of blocked email domains
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
  responses:
    Error-FF-NotEnabled-Response-401:
      description: Unauthorized
      content:
        application/json:
          examples:
            Unauthorized:
              value:
                errorCode: E0000015
                errorSummary: >-
                  You do not have permission to access the feature you are
                  requesting
                errorLink: E0000015
                errorId: oaeStOuPPxDRUm3PJhf-tL7bQ
                errorCauses: []
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorResourceNotFound404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            ResourceNotFound:
              $ref: '#/components/examples/ErrorResourceNotFound'
    ErrorTooManyRequests429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            TooManyRequests:
              $ref: '#/components/examples/ErrorTooManyRequests'
  examples:
    editFeatureExample:
      summary: Enable Okta Personal admin settings
      value:
        enableExportApps: true
        enableEnduserEntryPoints: true
    getBlockListExample:
      summary: List of blocked email domains
      value:
        domains:
          - yahoo.com
          - google.com
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorResourceNotFound:
      summary: Resource Not Found
      value:
        errorCode: E0000007
        errorSummary: 'Not found: {0}'
        errorLink: E0000007
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
    ErrorTooManyRequests:
      summary: Too Many Requests
      value:
        errorCode: E0000047
        errorSummary: API call exceeded rate limit due to too many requests.
        errorLink: E0000047
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
  x-stackQL-resources:
    settings:
      id: okta.okta_personal_settings.settings
      name: settings
      title: Settings
      methods:
        replace_okta_personal_admin_settings:
          operation:
            $ref: '#/paths/~1okta-personal-settings~1api~1v1~1edit-feature/put'
          response:
            mediaType: ''
            openAPIDocKey: '204'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/settings/methods/replace_okta_personal_admin_settings
    personal_apps_export_block_list:
      id: okta.okta_personal_settings.personal_apps_export_block_list
      name: personal_apps_export_block_list
      title: Personal Apps Export Block List
      methods:
        list_personal_apps_export_block_list:
          operation:
            $ref: '#/paths/~1okta-personal-settings~1api~1v1~1export-blocklists/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/personal_apps_export_block_list/methods/list_personal_apps_export_block_list
        insert: []
        update: []
        delete: []
        replace: []
    blocked_email_domains:
      id: okta.okta_personal_settings.blocked_email_domains
      name: blocked_email_domains
      title: Blocked Email Domains
      methods:
        replace_blocked_email_domains:
          operation:
            $ref: '#/paths/~1okta-personal-settings~1api~1v1~1export-blocklists/put'
          response:
            mediaType: ''
            openAPIDocKey: '204'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/blocked_email_domains/methods/replace_blocked_email_domains
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
        description: >-
          The domain of your organization. This can be a provided subdomain of
          an official okta domain (okta.com, oktapreview.com, etc) or one of
          your configured custom domains.
