openapi: 3.0.3
info:
  title: principal_rate_limits API
  description: okta principal_rate_limits API
  version: 5.1.0
paths:
  /api/v1/principal-rate-limits:
    get:
      summary: List all principal rate limits
      description: >-
        Lists all Principal Rate Limit entities considering the provided
        parameters
      operationId: listPrincipalRateLimitEntities
      parameters:
        - name: filter
          in: query
          description: >-
            Filters the list of principal rate limit entities by the provided
            principal type (`principalType`). For example,

            `filter=principalType eq "SSWS_TOKEN"` or `filter=principalType eq
            "OAUTH_CLIENT"`.
          schema:
            type: string
          required: true
        - name: after
          in: query
          description: >-
            The cursor to use for pagination. It's an opaque string that
            specifies your current location in the list and is obtained from the
            `Link` response header. See
            [Pagination](https://developer.okta.com/docs/api/#pagination).
          schema:
            type: string
        - name: limit
          in: query
          description: Specifies the number of items to return in a single response page.
          schema:
            type: integer
            format: int32
            default: 20
            maximum: 50
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrincipalRateLimitEntity'
              examples:
                SSWSListAll:
                  $ref: '#/components/examples/PrincipalRateLimitsSSWSListAllExample'
                OAuthClientListAll:
                  $ref: >-
                    #/components/examples/PrincipalRateLimitsOAuthClientListAllExample
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.principalRateLimits.read
      tags:
        - PrincipalRateLimit
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    post:
      summary: Create a principal rate limit
      description: >-
        Creates a new principal rate limit entity. Okta only allows one
        principal rate limit entity per org and principal.
      operationId: createPrincipalRateLimitEntity
      x-codegen-request-body-name: entity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrincipalRateLimitEntity'
            examples:
              SSWSToken:
                $ref: '#/components/examples/PrincipalRateLimitEntityRequestSSWSToken'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrincipalRateLimitEntity'
              examples:
                SSWSToken:
                  $ref: >-
                    #/components/examples/PrincipalRateLimitEntityResponseSSWSToken
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.principalRateLimits.manage
      tags:
        - PrincipalRateLimit
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
  /api/v1/principal-rate-limits/{principalRateLimitId}:
    get:
      summary: Retrieve a principal rate limit
      description: Retrieves a principal rate limit entity by `principalRateLimitId`
      operationId: getPrincipalRateLimitEntity
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrincipalRateLimitEntity'
              examples:
                SSWSToken:
                  $ref: >-
                    #/components/examples/PrincipalRateLimitEntityResponseSSWSToken
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.principalRateLimits.read
      tags:
        - PrincipalRateLimit
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    put:
      summary: Replace a principal rate limit
      description: Replaces a principal rate limit entity by `principalRateLimitId`
      operationId: replacePrincipalRateLimitEntity
      x-codegen-request-body-name: entity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrincipalRateLimitEntity'
            examples:
              SSWSToken:
                $ref: >-
                  #/components/examples/PrincipalRateLimitEntityReplaceRequestSSWSToken
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrincipalRateLimitEntity'
              examples:
                SSWSToken:
                  $ref: >-
                    #/components/examples/PrincipalRateLimitEntityReplaceResponseSSWSToken
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.principalRateLimits.manage
      tags:
        - PrincipalRateLimit
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    parameters:
      - $ref: '#/components/parameters/pathPrincipalRateLimitId'
components:
  schemas:
    PrincipalRateLimitEntity:
      title: PrincipalRateLimitEntity
      description: ''
      type: object
      properties:
        createdBy:
          description: >-
            The Okta user ID of the user who created the principle rate limit
            entity
          type: string
          readOnly: true
        createdDate:
          description: The date and time the principle rate limit entity was created
          type: string
          format: date-time
          readOnly: true
        defaultConcurrencyPercentage:
          description: >-
            The default percentage of a given concurrency limit threshold that
            the owning principal can consume
          type: integer
        defaultPercentage:
          description: >-
            The default percentage of a given rate limit threshold that the
            owning principal can consume
          type: integer
        id:
          description: The unique identifier of the principle rate limit entity
          type: string
          readOnly: true
        lastUpdate:
          description: The date and time the principle rate limit entity was last updated
          type: string
          format: date-time
          readOnly: true
        lastUpdatedBy:
          description: >-
            The Okta user ID of the user who last updated the principle rate
            limit entity
          type: string
          readOnly: true
        orgId:
          description: The unique identifier of the Okta org
          type: string
          readOnly: true
        principalId:
          description: >-
            The unique identifier of the principal. This is the ID of the API
            token or OAuth 2.0 app.
          type: string
        principalType:
          $ref: '#/components/schemas/PrincipalType'
      required:
        - principalId
        - principalType
    PrincipalType:
      description: The type of principal, either an API token or an OAuth 2.0 app
      type: string
      enum:
        - OAUTH_CLIENT
        - SSWS_TOKEN
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
  responses:
    ErrorApiValidationFailed400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            APIValidationFailed:
              $ref: '#/components/examples/ErrorApiValidationFailed'
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorTooManyRequests429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            TooManyRequests:
              $ref: '#/components/examples/ErrorTooManyRequests'
    ErrorResourceNotFound404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            ResourceNotFound:
              $ref: '#/components/examples/ErrorResourceNotFound'
  parameters:
    pathPrincipalRateLimitId:
      name: principalRateLimitId
      in: path
      schema:
        type: string
        example: 0oacamvryxiyMqgiY1d7
      required: true
      description: ID of the principal rate limit
  examples:
    PrincipalRateLimitsSSWSListAllExample:
      summary: List all SSWS API token principal rate limits
      value:
        - id: prlh5hd7qct3aHDry1f6
          orgId: 00o7xut90ucsjAQ7S1e6
          principalId: 00T14q3ns31qMEJUU1d7
          principalType: SSWS_TOKEN
          defaultPercentage: 50
          defaultConcurrencyPercentage: 50
          lastUpdate: '2024-09-12T17:28:56.000Z'
          lastUpdatedBy: 00uid52637YwIXkJq1d4
          createdDate: '2024-09-12T17:28:56.000Z'
          createdBy: 00u7xut94qEWYx5ss1d4
        - id: prlid6w9ilOWlVbpG1f6
          orgId: 00o7xut90ucsjAQ7S1e6
          principalId: 00T16ewcxyIrMV6Lb1d7
          principalType: SSWS_TOKEN
          defaultPercentage: 50
          defaultConcurrencyPercentage: 50
          lastUpdate: '2024-11-13T17:07:14.000Z'
          lastUpdatedBy: 00uid52637YwIXkJq1d4
          createdDate: '2024-11-13T17:07:14.000Z'
          createdBy: 00uid52637YwIXkJq1d4
    PrincipalRateLimitsOAuthClientListAllExample:
      summary: List all OAuth 2.0 client principal rate limits
      value:
        - id: prl7yh347wuzN5P1C1e7
          orgId: 00o7xut90ucsjAQ7S1e6
          principalId: 0oa7yh346zIE1y84p1e7
          principalType: OAUTH_CLIENT
          defaultPercentage: 40
          defaultConcurrencyPercentage: 40
          lastUpdate: '2024-11-29T14:56:06.000Z'
          lastUpdatedBy: 00uid52637YwIXkJq1d4
          createdDate: '2023-05-02T20:37:38.000Z'
          createdBy: 00uid52637YwIXkJq1d4
        - id: prlbqdob5bhM6nff61e7
          orgId: 00o7xut90ucsjAQ7S1e6
          principalId: 0oabqdob4da0JGuMf1e7
          principalType: OAUTH_CLIENT
          defaultPercentage: 50
          defaultConcurrencyPercentage: 50
          lastUpdate: '2023-12-07T21:58:02.000Z'
          lastUpdatedBy: 00uid52637YwIXkJq1d4
          createdDate: '2023-12-07T21:58:02.000Z'
          createdBy: 00uid52637YwIXkJq1d4
        - id: prlcamvrzvkglWHqR1e7
          orgId: 00o7xut90ucsjAQ7S1d7
          principalId: 0oacamvryxiyMqgiY1e7
          principalType: OAUTH_CLIENT
          defaultPercentage: 50
          defaultConcurrencyPercentage: 50
          lastUpdate: '2024-01-12T20:59:18.000Z'
          lastUpdatedBy: 00uid52637YwIXkJq1d4
          createdDate: '2024-01-12T20:59:18.000Z'
          createdBy: 00uid52637YwIXkJq1d4
    PrincipalRateLimitEntityRequestSSWSToken:
      summary: Create a principal rate limit entity request example
      value:
        principalId: prlh5hd6act3aHDrr1f5
        principalType: SSWS_TOKEN
        defaultPercentage: 50
        defaultConcurrencyPercentage: 75
    PrincipalRateLimitEntityResponseSSWSToken:
      summary: Create a principal rate limit entity response example
      value:
        id: 0oacamvryxiyMqgiY1e5
        orgId: org1234
        principalId: prlh5hd6act3aHDrr1f5
        principalType: SSWS_TOKEN
        defaultPercentage: 50
        defaultConcurrencyPercentage: 75
        createdDate: '2022-05-19T20:05:32.720Z'
        createdBy: 00u7xut94qEWYx5ss1d4
        lastUpdate: '2022-05-20T21:13:07.410Z'
        lastUpdatedBy: 00u7xut94qEWYx5ss1d4
    PrincipalRateLimitEntityReplaceRequestSSWSToken:
      summary: Replace a principal rate limit entity request
      value:
        principalId: prlh5hd6act3aHDrr1f5
        principalType: SSWS_TOKEN
        defaultPercentage: 50
        defaultConcurrencyPercentage: 75
    PrincipalRateLimitEntityReplaceResponseSSWSToken:
      summary: Replace a principal rate limit entity response example
      value:
        id: 0oacamvryxiyMqgiY1e5
        orgId: org1234
        principalId: prlh5hd6act3aHDrr1f5
        principalType: SSWS_TOKEN
        defaultPercentage: 50
        defaultConcurrencyPercentage: 75
        createdDate: '2022-05-19T20:05:32.720Z'
        createdBy: 00u7xut94qEWYx5ss1d4
        lastUpdate: '2022-05-20T21:13:07.410Z'
        lastUpdatedBy: 00u7xut94qEWYx5ss1d4
    ErrorApiValidationFailed:
      summary: API Validation Failed
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: {0}'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses: []
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorTooManyRequests:
      summary: Too Many Requests
      value:
        errorCode: E0000047
        errorSummary: API call exceeded rate limit due to too many requests.
        errorLink: E0000047
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
    ErrorResourceNotFound:
      summary: Resource Not Found
      value:
        errorCode: E0000007
        errorSummary: 'Not found: {0}'
        errorLink: E0000007
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
  x-stackQL-resources:
    principal_rate_limit_entities:
      id: okta.principal_rate_limits.principal_rate_limit_entities
      name: principal_rate_limit_entities
      title: Principal Rate Limit Entities
      methods:
        list_principal_rate_limit_entities:
          operation:
            $ref: '#/paths/~1api~1v1~1principal-rate-limits/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        create_principal_rate_limit_entity:
          operation:
            $ref: '#/paths/~1api~1v1~1principal-rate-limits/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        get_principal_rate_limit_entity:
          operation:
            $ref: >-
              #/paths/~1api~1v1~1principal-rate-limits~1{principalRateLimitId}/get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        replace_principal_rate_limit_entity:
          operation:
            $ref: >-
              #/paths/~1api~1v1~1principal-rate-limits~1{principalRateLimitId}/put
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/principal_rate_limit_entities/methods/list_principal_rate_limit_entities
          - $ref: >-
              #/components/x-stackQL-resources/principal_rate_limit_entities/methods/get_principal_rate_limit_entity
        insert:
          - $ref: >-
              #/components/x-stackQL-resources/principal_rate_limit_entities/methods/create_principal_rate_limit_entity
        update: []
        delete: []
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/principal_rate_limit_entities/methods/replace_principal_rate_limit_entity
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
        description: >-
          The domain of your organization. This can be a provided subdomain of
          an official okta domain (okta.com, oktapreview.com, etc) or one of
          your configured custom domains.
