openapi: 3.0.3
info:
  title: push_providers API
  description: okta push_providers API
  version: 5.1.0
paths:
  /api/v1/push-providers:
    get:
      summary: List all push providers
      description: Lists all push providers
      operationId: listPushProviders
      parameters:
        - name: type
          in: query
          description: Filters push providers by `providerType`
          schema:
            $ref: '#/components/schemas/ProviderType'
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                value:
                  - id: ppchvbeucdTgqeiGxR0g4
                    providerType: APNS
                    name: Example Push Provider 1
                    lastUpdatedDate: '2022-01-00T00:00:00.000Z'
                    configuration:
                      keyId: ABC123DEFG
                      teamId: DEF123GHIJ
                      fileName: fileName.p8
                    _links:
                      self:
                        href: >-
                          https://your-subdomain.okta.com/api/v1/push-providers/{pushProviderId}
                        hints:
                          allow:
                            - DELETE
                            - GET
                            - PUT
                  - id: ppctekcmngGaqeiBxB0g4
                    providerType: FCM
                    name: Example Push Provider 2
                    lastUpdatedDate: '2022-01-00T00:00:00.000Z'
                    configuration:
                      projectId: PROJECT_ID
                      fileName: fileName.json
                    _links:
                      self:
                        href: >-
                          https://your-subdomain.okta.com/api/v1/push-providers/{pushProviderId}
                        hints:
                          allow:
                            - DELETE
                            - GET
                            - PUT
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PushProvider'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.pushProviders.read
      tags:
        - PushProvider
      x-okta-lifecycle:
        lifecycle: LIMITED_GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
    post:
      summary: Create a push provider
      description: >-
        Creates a new push provider. Each Push Provider must have a unique
        `name`.
      operationId: createPushProvider
      x-codegen-request-body-name: pushProvider
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushProvider'
            examples:
              APNs:
                $ref: '#/components/examples/PushProviderAPNsRequest'
              FCM:
                $ref: '#/components/examples/PushProviderFCMRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PushProvider'
              examples:
                APNs:
                  $ref: '#/components/examples/PushProviderAPNsResponse'
                FCM:
                  $ref: '#/components/examples/PushProviderFCMResponse'
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.pushProviders.manage
      tags:
        - PushProvider
      x-okta-lifecycle:
        lifecycle: LIMITED_GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
  /api/v1/push-providers/{pushProviderId}:
    get:
      summary: Retrieve a push provider
      description: Retrieves a push provider by `pushProviderId`
      operationId: getPushProvider
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PushProvider'
              examples:
                APNs:
                  $ref: '#/components/examples/PushProviderAPNsResponse'
                FCM:
                  $ref: '#/components/examples/PushProviderFCMResponse'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.pushProviders.read
      tags:
        - PushProvider
      x-okta-lifecycle:
        lifecycle: LIMITED_GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
    put:
      summary: Replace a push provider
      description: Replaces a push provider by `pushProviderId`
      operationId: replacePushProvider
      x-codegen-request-body-name: pushProvider
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushProvider'
            examples:
              APNs:
                $ref: '#/components/examples/PushProviderAPNsRequest'
              FCM:
                $ref: '#/components/examples/PushProviderFCMRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PushProvider'
              examples:
                APNs:
                  $ref: '#/components/examples/PushProviderAPNsResponse'
                FCM:
                  $ref: '#/components/examples/PushProviderFCMResponse'
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.pushProviders.manage
      tags:
        - PushProvider
      x-okta-lifecycle:
        lifecycle: LIMITED_GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
    delete:
      summary: Delete a push provider
      description: >-
        Deletes a push provider by `pushProviderId`. If the push provider is
        currently being used in the org by a custom authenticator, the delete
        will not be allowed.
      operationId: deletePushProvider
      responses:
        '204':
          description: No Content
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '409':
          description: Conflict
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Cannot remove push provider in use by a custom app authenticator:
                  $ref: >-
                    #/components/examples/ErrorPushProviderUsedByCustomAppAuthenticator
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.pushProviders.manage
      tags:
        - PushProvider
      x-okta-lifecycle:
        lifecycle: LIMITED_GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
    parameters:
      - $ref: '#/components/parameters/pathPushProviderId'
components:
  schemas:
    ProviderType:
      type: string
      enum:
        - APNS
        - FCM
    PushProvider:
      title: PushProvider
      type: object
      properties:
        id:
          type: string
          readOnly: true
          description: Unique key for the Push Provider
        lastUpdatedDate:
          type: string
          readOnly: true
          description: Timestamp when the Push Provider was last modified
        name:
          type: string
          description: Display name of the push provider
        providerType:
          $ref: '#/components/schemas/ProviderType'
        _links:
          $ref: '#/components/schemas/LinksSelf'
      discriminator:
        propertyName: providerType
        mapping:
          APNS: '#/components/schemas/APNSPushProvider'
          FCM: '#/components/schemas/FCMPushProvider'
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    LinksSelf:
      description: >-
        Specifies link relations (see [Web
        Linking](https://www.rfc-editor.org/rfc/rfc8288)) available using the
        [JSON Hypertext Application
        Language](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal-06)
        specification. This object is used for dynamic discovery of related
        resources and lifecycle operations.
      type: object
      properties:
        self:
          $ref: '#/components/schemas/HrefObjectSelfLink'
      readOnly: true
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
    HrefObjectSelfLink:
      allOf:
        - $ref: '#/components/schemas/HrefObject'
        - description: Link to the resource (self)
    HrefObject:
      title: Link Object
      additionalProperties: true
      type: object
      properties:
        hints:
          $ref: '#/components/schemas/HrefHints'
          readOnly: true
        href:
          type: string
          description: Link URI
        name:
          type: string
          description: Link name
          readOnly: true
        templated:
          type: boolean
          description: >-
            Indicates whether the link object's `href` property is a URI
            template.
          readOnly: true
        type:
          type: string
          description: >-
            The media type of the link. If omitted, it is implicitly
            `application/json`.
          readOnly: true
      required:
        - href
    HrefHints:
      description: Describes allowed HTTP verbs for the `href`
      type: object
      properties:
        allow:
          type: array
          items:
            $ref: '#/components/schemas/HttpMethod'
    HttpMethod:
      type: string
      enum:
        - DELETE
        - GET
        - POST
        - PUT
  responses:
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorTooManyRequests429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            TooManyRequests:
              $ref: '#/components/examples/ErrorTooManyRequests'
    ErrorApiValidationFailed400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            APIValidationFailed:
              $ref: '#/components/examples/ErrorApiValidationFailed'
    ErrorResourceNotFound404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            ResourceNotFound:
              $ref: '#/components/examples/ErrorResourceNotFound'
  parameters:
    pathPushProviderId:
      in: path
      name: pushProviderId
      required: true
      description: Id of the push provider
      schema:
        type: string
  examples:
    PushProviderAPNsRequest:
      value:
        name: APNs Example
        providerType: APNS
        configuration:
          keyId: KEY_ID
          teamId: TEAM_ID
          tokenSigningKey: >-
            -----BEGIN PRIVATE KEY-----\nPRIVATE_KEY\n-----END PRIVATE
            KEY-----\n
          fileName: fileName.p8
    PushProviderFCMRequest:
      value:
        name: FCM Example
        providerType: FCM
        configuration:
          serviceAccountJson:
            type: service_account
            project_id: PROJECT_ID
            private_key_id: KEY_ID
            private_key: >-
              -----BEGIN PRIVATE KEY-----\nPRIVATE_KEY\n-----END PRIVATE
              KEY-----\n
            client_email: SERVICE_ACCOUNT_EMAIL
            client_id: CLIENT_ID
            auth_uri: https://accounts.google.com/o/oauth2/auth
            token_uri: https://accounts.google.com/o/oauth2/token
            auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
            client_x509_cert_url: >-
              https://www.googleapis.com/robot/v1/metadata/x509/SERVICE_ACCOUNT_EMAIL
          fileName: fileName.json
    PushProviderAPNsResponse:
      value:
        id: ppctekcmngGaqeiBxB0g4
        name: APNs Example
        providerType: APNS
        lastUpdatedDate: '2022-01-01T00:00:00.000Z'
        configuration:
          keyId: KEY_ID
          teamId: TEAM_ID
          fileName: fileName.p8
        _links:
          self:
            href: >-
              https://your-subdomain.okta.com/api/v1/push-providers/ppctekcmngGaqeiBxB0g4
            hints:
              allow:
                - DELETE
                - GET
                - PUT
    PushProviderFCMResponse:
      value:
        id: ppctekcmngGaqeiBxB0g4
        name: FCM Example
        providerType: FCM
        lastUpdatedDate: '2022-01-01T00:00:00.000Z'
        configuration:
          projectId: PROJECT_ID
          fileName: fileName.p8
        _links:
          self:
            href: >-
              https://your-subdomain.okta.com/api/v1/push-providers/ppctekcmngGaqeiBxB0g4
            hints:
              allow:
                - DELETE
                - GET
                - PUT
    ErrorPushProviderUsedByCustomAppAuthenticator:
      value:
        errorCode: E0000187
        errorSummary: >-
          Cannot delete push provider because it is being used by a custom app
          authenticator.
        errorLink: E0000187
        errorId: oaenwA1ra80S9W-pvbh4m6haA
        errorCauses: []
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorTooManyRequests:
      summary: Too Many Requests
      value:
        errorCode: E0000047
        errorSummary: API call exceeded rate limit due to too many requests.
        errorLink: E0000047
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
    ErrorApiValidationFailed:
      summary: API Validation Failed
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: {0}'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses: []
    ErrorResourceNotFound:
      summary: Resource Not Found
      value:
        errorCode: E0000007
        errorSummary: 'Not found: {0}'
        errorLink: E0000007
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
  x-stackQL-resources:
    push_providers:
      id: okta.push_providers.push_providers
      name: push_providers
      title: Push Providers
      methods:
        list_push_providers:
          operation:
            $ref: '#/paths/~1api~1v1~1push-providers/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        create_push_provider:
          operation:
            $ref: '#/paths/~1api~1v1~1push-providers/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get_push_provider:
          operation:
            $ref: '#/paths/~1api~1v1~1push-providers~1{pushProviderId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        replace_push_provider:
          operation:
            $ref: '#/paths/~1api~1v1~1push-providers~1{pushProviderId}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete_push_provider:
          operation:
            $ref: '#/paths/~1api~1v1~1push-providers~1{pushProviderId}/delete'
          response:
            mediaType: ''
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/push_providers/methods/list_push_providers
          - $ref: >-
              #/components/x-stackQL-resources/push_providers/methods/get_push_provider
        insert:
          - $ref: >-
              #/components/x-stackQL-resources/push_providers/methods/create_push_provider
        update: []
        delete:
          - $ref: >-
              #/components/x-stackQL-resources/push_providers/methods/delete_push_provider
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/push_providers/methods/replace_push_provider
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
        description: >-
          The domain of your organization. This can be a provided subdomain of
          an official okta domain (okta.com, oktapreview.com, etc) or one of
          your configured custom domains.
