openapi: 3.0.3
info:
  title: rate_limit_settings API
  description: okta rate_limit_settings API
  version: 5.1.0
paths:
  /api/v1/rate-limit-settings/admin-notifications:
    get:
      summary: Retrieve the rate limit admin notification settings
      description: >-
        Retrieves the currently configured Rate Limit Admin Notification
        Settings
      operationId: getRateLimitSettingsAdminNotifications
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimitAdminNotifications'
              examples:
                Enabled:
                  $ref: '#/components/examples/RateLimitAdminNotificationsEnabled'
                Disabled:
                  $ref: '#/components/examples/RateLimitAdminNotificationsDisabled'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.rateLimits.read
      tags:
        - RateLimitSettings
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    put:
      summary: Replace the rate limit admin notification settings
      description: >-
        Replaces the Rate Limit Admin Notification Settings and returns the
        configured properties
      operationId: replaceRateLimitSettingsAdminNotifications
      x-codegen-request-body-name: RateLimitAdminNotifications
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RateLimitAdminNotifications'
            examples:
              Enabled:
                $ref: '#/components/examples/RateLimitAdminNotificationsEnabled'
              Disabled:
                $ref: '#/components/examples/RateLimitAdminNotificationsDisabled'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimitAdminNotifications'
              examples:
                Enabled:
                  $ref: '#/components/examples/RateLimitAdminNotificationsEnabled'
                Disabled:
                  $ref: '#/components/examples/RateLimitAdminNotificationsDisabled'
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.rateLimits.manage
      tags:
        - RateLimitSettings
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
  /api/v1/rate-limit-settings/per-client:
    get:
      summary: Retrieve the per-client rate limit settings
      description: Retrieves the currently configured Per-Client Rate Limit Settings
      operationId: getRateLimitSettingsPerClient
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerClientRateLimitSettings'
              examples:
                EnforceDefault:
                  $ref: >-
                    #/components/examples/PerClientRateLimitSettingsEnforceDefault
                EnforceDefaultWithOverrides:
                  $ref: >-
                    #/components/examples/PerClientRateLimitSettingsEnforceDefaultWithOverrides
                PreviewDefaultWithOverrides:
                  $ref: >-
                    #/components/examples/PerClientRateLimitSettingsPreviewDefaultWithOverrides
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.rateLimits.read
      tags:
        - RateLimitSettings
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    put:
      summary: Replace the per-client rate limit settings
      description: >-
        Replaces the Per-Client Rate Limit Settings and returns the configured
        properties
      operationId: replaceRateLimitSettingsPerClient
      x-codegen-request-body-name: perClientRateLimitSettings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PerClientRateLimitSettings'
            examples:
              EnforceDefault:
                $ref: '#/components/examples/PerClientRateLimitSettingsEnforceDefault'
              EnforceDefaultWithOverrides:
                $ref: >-
                  #/components/examples/PerClientRateLimitSettingsEnforceDefaultWithOverrides
              PreviewDefaultWithOverrides:
                $ref: >-
                  #/components/examples/PerClientRateLimitSettingsPreviewDefaultWithOverrides
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerClientRateLimitSettings'
              examples:
                EnforceDefault:
                  $ref: >-
                    #/components/examples/PerClientRateLimitSettingsEnforceDefault
                EnforceDefaultWithOverrides:
                  $ref: >-
                    #/components/examples/PerClientRateLimitSettingsEnforceDefaultWithOverrides
                PreviewDefaultWithOverrides:
                  $ref: >-
                    #/components/examples/PerClientRateLimitSettingsPreviewDefaultWithOverrides
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.rateLimits.manage
      tags:
        - RateLimitSettings
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
  /api/v1/rate-limit-settings/warning-threshold:
    get:
      summary: Retrieve the rate limit warning threshold percentage
      description: >-
        Retrieves the currently configured threshold for warning notifications
        when the API's rate limit is exceeded
      operationId: getRateLimitSettingsWarningThreshold
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimitWarningThresholdResponse'
              examples:
                ExampleThreshold:
                  $ref: '#/components/examples/RateLimitWarningThresholdValidExample'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.rateLimits.read
      tags:
        - RateLimitSettings
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    put:
      summary: Replace the rate limit warning threshold percentage
      description: >-
        Replaces the Rate Limit Warning Threshold Percentage and returns the
        configured property
      operationId: replaceRateLimitSettingsWarningThreshold
      x-codegen-request-body-name: RateLimitWarningThreshold
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RateLimitWarningThresholdRequest'
            examples:
              ExampleThreshold:
                $ref: '#/components/examples/RateLimitWarningThresholdValidExample'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RateLimitWarningThresholdResponse'
              examples:
                ExampleThreshold:
                  $ref: '#/components/examples/RateLimitWarningThresholdValidExample'
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.rateLimits.manage
      tags:
        - RateLimitSettings
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
components:
  schemas:
    RateLimitAdminNotifications:
      title: RateLimitAdminNotifications
      description: ''
      type: object
      properties:
        notificationsEnabled:
          type: boolean
      required:
        - notificationsEnabled
    PerClientRateLimitSettings:
      title: PerClientRateLimitSettings
      description: ''
      type: object
      properties:
        defaultMode:
          $ref: '#/components/schemas/PerClientRateLimitMode'
          description: >-
            The default PerClientRateLimitMode that applies to any use case in
            the absence of a more specific override
        useCaseModeOverrides:
          description: >-
            A map of Per-Client Rate Limit Use Case to the applicable
            PerClientRateLimitMode. Overrides the `defaultMode` property for the
            specified use cases.
          type: object
          properties:
            LOGIN_PAGE:
              $ref: '#/components/schemas/PerClientRateLimitMode'
            OAUTH2_AUTHORIZE:
              $ref: '#/components/schemas/PerClientRateLimitMode'
            OIE_APP_INTENT:
              $ref: '#/components/schemas/PerClientRateLimitMode'
      required:
        - defaultMode
    RateLimitWarningThresholdResponse:
      title: RateLimitWarningThreshold
      description: ''
      type: object
      properties:
        warningThreshold:
          description: >-
            The threshold value (percentage) of a rate limit that, when
            exceeded, triggers a warning notification. By default, this value is
            90 for Workforce orgs and 60 for CIAM orgs.
          type: integer
          minimum: 30
          maximum: 90
    RateLimitWarningThresholdRequest:
      title: RateLimitWarningThreshold
      description: ''
      type: object
      properties:
        warningThreshold:
          description: >-
            The threshold value (percentage) of a rate limit that, when
            exceeded, triggers a warning notification. By default, this value is
            90 for Workforce orgs and 60 for CIAM orgs.
          type: integer
          minimum: 30
          maximum: 90
      required:
        - warningThreshold
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    PerClientRateLimitMode:
      type: string
      enum:
        - DISABLE
        - ENFORCE
        - PREVIEW
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
  responses:
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorTooManyRequests429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            TooManyRequests:
              $ref: '#/components/examples/ErrorTooManyRequests'
    ErrorApiValidationFailed400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            APIValidationFailed:
              $ref: '#/components/examples/ErrorApiValidationFailed'
  examples:
    RateLimitAdminNotificationsEnabled:
      value:
        notificationsEnabled: true
    RateLimitAdminNotificationsDisabled:
      value:
        notificationsEnabled: false
    PerClientRateLimitSettingsEnforceDefault:
      value:
        defaultMode: ENFORCE
    PerClientRateLimitSettingsEnforceDefaultWithOverrides:
      value:
        defaultMode: ENFORCE
        useCaseModeOverrides:
          OAUTH2_AUTHORIZE: PREVIEW
          OIE_APP_INTENT: DISABLE
    PerClientRateLimitSettingsPreviewDefaultWithOverrides:
      value:
        defaultMode: PREVIEW
        useCaseModeOverrides:
          LOGIN_PAGE: ENFORCE
    RateLimitWarningThresholdValidExample:
      value:
        warningThreshold: 66
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorTooManyRequests:
      summary: Too Many Requests
      value:
        errorCode: E0000047
        errorSummary: API call exceeded rate limit due to too many requests.
        errorLink: E0000047
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
    ErrorApiValidationFailed:
      summary: API Validation Failed
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: {0}'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses: []
  x-stackQL-resources:
    admin_notifications:
      id: okta.rate_limit_settings.admin_notifications
      name: admin_notifications
      title: Admin Notifications
      methods:
        get_rate_limit_settings_admin_notifications:
          operation:
            $ref: '#/paths/~1api~1v1~1rate-limit-settings~1admin-notifications/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        replace_rate_limit_settings_admin_notifications:
          operation:
            $ref: '#/paths/~1api~1v1~1rate-limit-settings~1admin-notifications/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/admin_notifications/methods/get_rate_limit_settings_admin_notifications
        insert: []
        update: []
        delete: []
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/admin_notifications/methods/replace_rate_limit_settings_admin_notifications
    rate_limit_settings_per_client:
      id: okta.rate_limit_settings.rate_limit_settings_per_client
      name: rate_limit_settings_per_client
      title: Rate Limit Settings Per Client
      methods:
        get_rate_limit_settings_per_client:
          operation:
            $ref: '#/paths/~1api~1v1~1rate-limit-settings~1per-client/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        replace_rate_limit_settings_per_client:
          operation:
            $ref: '#/paths/~1api~1v1~1rate-limit-settings~1per-client/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/rate_limit_settings_per_client/methods/get_rate_limit_settings_per_client
        insert: []
        update: []
        delete: []
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/rate_limit_settings_per_client/methods/replace_rate_limit_settings_per_client
    warning_thresholds:
      id: okta.rate_limit_settings.warning_thresholds
      name: warning_thresholds
      title: Warning Thresholds
      methods:
        get_rate_limit_settings_warning_threshold:
          operation:
            $ref: '#/paths/~1api~1v1~1rate-limit-settings~1warning-threshold/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        replace_rate_limit_settings_warning_threshold:
          operation:
            $ref: '#/paths/~1api~1v1~1rate-limit-settings~1warning-threshold/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/warning_thresholds/methods/get_rate_limit_settings_warning_threshold
        insert: []
        update: []
        delete: []
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/warning_thresholds/methods/replace_rate_limit_settings_warning_threshold
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
        description: >-
          The domain of your organization. This can be a provided subdomain of
          an official okta domain (okta.com, oktapreview.com, etc) or one of
          your configured custom domains.
