openapi: 3.0.3
info:
  title: security API
  description: okta security API
  version: 5.1.0
paths:
  /security/api/v1/security-events:
    post:
      summary: Publish a security event token
      description: >-
        Publishes a Security Event Token (SET) sent by a Security Events
        Provider. After the token is verified, Okta ingests the event and
        performs any appropriate action.
      operationId: publishSecurityEventTokens
      x-codegen-request-body-name: Security Event Token
      requestBody:
        required: true
        description: >
          The request body is a signed
          [SET](https://datatracker.ietf.org/doc/html/rfc8417), which is a type
          of JSON Web Token (JWT).


          For SET JWT header and body descriptions, see [SET JWT
          header](https://developer.okta.com/docs/apihttps://developer.okta.com/docs/apihttps://developer.okta.com/docs/apihttps://developer.okta.com/docs/api/openapi/okta-management/management/tag/SSFSecurityEventToken/#tag/SSFSecurityEventToken/schema/SecurityEventTokenRequestJwtHeader)
          and [SET JWT body
          payload](https://developer.okta.com/docs/apihttps://developer.okta.com/docs/apihttps://developer.okta.com/docs/apihttps://developer.okta.com/docs/api/openapi/okta-management/management/tag/SSFSecurityEventToken/#tag/SSFSecurityEventToken/schema/SecurityEventTokenRequestJwtBody).
        content:
          application/secevent+jwt:
            schema:
              type: string
            examples:
              SET:
                value: eyJraWQiOiJzYW1wbGVfa2lkIiwidHlwIjoic2ZXZlbnQra ... mrtmw
      responses:
        '202':
          description: Accepted
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityEventTokenError'
      security: []
      tags:
        - SSFSecurityEventToken
      x-okta-lifecycle:
        lifecycle: LIMITED_GA
        isGenerallyAvailable: false
        SKUs:
          - Okta Identity Engine
components:
  schemas:
    SecurityEventTokenError:
      title: Security Event Token Error
      description: Error object thrown when parsing the Security Event Token
      type: object
      properties:
        description:
          type: string
          description: >
            Describes the error

            > **Note:** SET claim fields with underscores (snake case) are
            presented in camelcase. For example, `previous_status` appears as
            `previousStatus`.
          example: >-
            Failed claim validation in security event token.
            'events.mediationDeviceComplianceChangeEvent.previousStatus': The
            field cannot be left blank
        err:
          type: string
          description: A code that describes the category of the error
          example: invalid_request
          enum:
            - authentication_failed
            - invalid_audience
            - invalid_issuer
            - invalid_key
            - invalid_request
  x-stackQL-resources:
    ssf_security_event_tokens:
      id: okta.security.ssf_security_event_tokens
      name: ssf_security_event_tokens
      title: Ssf Security Event Tokens
      methods:
        publish_security_event_tokens:
          operation:
            $ref: '#/paths/~1security~1api~1v1~1security-events/post'
          response:
            mediaType: ''
            openAPIDocKey: '202'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
        replace: []
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
        description: >-
          The domain of your organization. This can be a provided subdomain of
          an official okta domain (okta.com, oktapreview.com, etc) or one of
          your configured custom domains.
