openapi: 3.0.3
info:
  title: sessions API
  description: okta sessions API
  version: 2026.07.2
paths:
  /api/v1/sessions/{sessionId}:
    get:
      summary: Retrieve a session
      description: >-
        Retrieves information about the session specified by the given session
        ID
      operationId: getSession
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
              examples:
                SessionsRetrieve:
                  summary: Retrieve session information for a single session ID
                  $ref: '#/components/examples/RetrieveSessionResponse'
        '400':
          description: Bad Request
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          description: Not Found
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.sessions.read
      tags:
        - Session
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
      parameters:
        - $ref: '#/components/parameters/pathSessionId'
    delete:
      summary: Revoke a session
      description: Revokes the specified session
      operationId: revokeSession
      responses:
        '204':
          description: No Content
          content: {}
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.sessions.manage
      tags:
        - Session
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
      parameters:
        - $ref: '#/components/parameters/pathSessionId'
  /api/v1/sessions/{sessionId}/lifecycle/refresh:
    post:
      summary: Refresh a session
      description: >-
        Refreshes an existing session using the `id` for that session. A
        successful response contains the refreshed session with an updated
        `expiresAt` timestamp.
      operationId: refreshSession
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
              examples:
                SessionsRefresh:
                  summary: Refresh an existing session using the session ID
                  $ref: '#/components/examples/RefreshSessionResponse'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          description: Not Found
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.sessions.manage
      tags:
        - Session
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
      parameters:
        - $ref: '#/components/parameters/pathSessionId'
components:
  schemas:
    Session:
      type: object
      properties:
        amr:
          type: array
          readOnly: true
          description: Authentication method reference
          items:
            $ref: '#/components/schemas/SessionAuthenticationMethod'
        createdAt:
          type: string
          format: date-time
          readOnly: true
        expiresAt:
          type: string
          format: date-time
          readOnly: true
          description: A timestamp when the session expires
        id:
          type: string
          readOnly: true
          description: A unique key for the session
        idp:
          $ref: '#/components/schemas/SessionIdentityProvider'
        lastFactorVerification:
          type: string
          format: date-time
          readOnly: true
          description: A timestamp when the user last performed multifactor authentication
        lastPasswordVerification:
          type: string
          format: date-time
          readOnly: true
          description: >-
            A timestamp when the user last performed the primary or step-up
            authentication with a password
        login:
          type: string
          readOnly: true
          description: A unique identifier for the user (username)
        status:
          $ref: '#/components/schemas/SessionStatus'
          description: Current session status
        userId:
          type: string
          readOnly: true
          description: A unique key for the user
        _links:
          $ref: '#/components/schemas/LinksSelf'
    SessionAuthenticationMethod:
      type: string
      enum:
        - fpt
        - geo
        - hwk
        - kba
        - mca
        - mfa
        - otp
        - pwd
        - sc
        - sms
        - swk
        - tel
      x-enumDescriptions:
        pwd: >-
          Password authentication. **Inline hook value:** `PASSWORD`
          **Example:** Standard password-based sign-in flow
        swk: >-
          Proof-of-possession (PoP) of a software key. **Inline hook value:**
          `POP_SOFTWARE_KEY` **Example:** Okta Verify with Push
        hwk: >-
          Proof-of-possession (PoP) of a hardware key. **Inline hook value:**
          `POP_HARDWARE_KEY` **Example:** Yubikey factor
        opt: >-
          One-time passcode. **Inline hook value:** `ONE_TIME_PASSWORD`.
          **Example:** Okta Verify, Google Authenticator
        sms: >-
          SMS text message to the user at a registered number. **Inline hook
          value:** `SMS_MESSAGE`. **Example:** SMS factor
        tel: >-
          Telephone call to the user at a registered number. **Inline hook
          value:** `TELEPHONE_CALL`. **Example:** Phone call factor
        geo: >-
          Use of geo-location information. **Inline hook value:** `GEOLOCATION`.
          **Example:** IP Trust and Network Zone policy conditions
        fpt: >-
          Fingerprint biometric authentication. **Inline hook value:**
          `BIO_FINGERPRINT`. **Example:** Okta Verify with Touch ID
        kba: >-
          Knowledge-based authentication. **Inline hook value:**
          `KNOWLEDGE_BASED_AUTHENTICATION`. **Example:** Security Question
          factor
        mfa: >-
          Multifactor authentication. **Inline hook value:**
          `MULTIFACTOR_AUTHENTICATION`. **Example:** This value is present
          whenever any MFA factor verification is performed.
        mca: >-
          Multiple-channel authentication. **Inline hook value:**
          `MULTIPLE_CHANNEL_AUTHENTICATION`. **Example:** Authentication
          requires communication over more than one channel, such as the
          Internet and a mobile network
        sc: >-
          Smart card authentication. **Inline hook value:** `SMART_CARD.
          **Example:** User authenticated using a smart card, such as a Personal
          Identity Verification (PIV) card or Common Access Card (CAC)
    SessionIdentityProvider:
      type: object
      properties:
        id:
          type: string
          readOnly: true
          description: >-
            Identity Provider ID. If the `type` is `OKTA`, then the `id` is the
            org ID.
        type:
          $ref: '#/components/schemas/SessionIdentityProviderType'
    SessionStatus:
      type: string
      enum:
        - ACTIVE
        - MFA_ENROLL
        - MFA_REQUIRED
      x-enumDescriptions:
        ACTIVE: The session is established and fully validated.
        MFA_REQUIRED: The session is established, but requires second factor verification.
        MFA_ENROLL: >-
          The session is established, but the user needs to enroll a second
          factor.
    LinksSelf:
      description: >-
        Specifies link relations (see [Web
        Linking](https://www.rfc-editor.org/rfc/rfc8288)) available using the
        [JSON Hypertext Application
        Language](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal-06)
        specification. This object is used for dynamic discovery of related
        resources and lifecycle operations.
      type: object
      properties:
        self:
          $ref: '#/components/schemas/HrefObjectSelfLink'
      readOnly: true
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    SessionIdentityProviderType:
      type: string
      enum:
        - ACTIVE_DIRECTORY
        - FEDERATION
        - LDAP
        - OKTA
        - SOCIAL
    HrefObjectSelfLink:
      x-okta-ignore-redocly-rules-for-sdk: true
      title: Link Object
      additionalProperties: true
      type: object
      properties:
        hints:
          $ref: '#/components/schemas/HrefHints'
          readOnly: true
        href:
          type: string
          description: Link URI
        name:
          type: string
          description: Link name
          readOnly: true
        templated:
          type: boolean
          description: >-
            Indicates whether the link object's `href` property is a URI
            template.
          readOnly: true
        type:
          type: string
          description: >-
            The media type of the link. If omitted, it is implicitly
            `application/json`.
          readOnly: true
      required:
        - href
      description: Link to the resource (self)
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
    HrefObject:
      x-okta-ignore-redocly-rules-for-sdk: true
      title: Link Object
      additionalProperties: true
      type: object
      properties:
        hints:
          $ref: '#/components/schemas/HrefHints'
          readOnly: true
        href:
          type: string
          description: Link URI
        name:
          type: string
          description: Link name
          readOnly: true
        templated:
          type: boolean
          description: >-
            Indicates whether the link object's `href` property is a URI
            template.
          readOnly: true
        type:
          type: string
          description: >-
            The media type of the link. If omitted, it is implicitly
            `application/json`.
          readOnly: true
      required:
        - href
    HrefHints:
      description: Describes allowed HTTP verbs for the `href`
      type: object
      properties:
        allow:
          type: array
          items:
            $ref: '#/components/schemas/HttpMethod'
    HttpMethod:
      type: string
      enum:
        - DELETE
        - GET
        - POST
        - PUT
  responses:
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorTooManyRequests429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            TooManyRequests:
              $ref: '#/components/examples/ErrorTooManyRequests'
    ErrorResourceNotFound404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            ResourceNotFound:
              $ref: '#/components/examples/ErrorResourceNotFound'
  parameters:
    pathSessionId:
      name: sessionId
      description: '`id` of the session'
      in: path
      required: true
      schema:
        type: string
        example: l7FbDVqS8zHSy65uJD85
  examples:
    RetrieveSessionResponse:
      summary: Retrieve session information for a single session ID
      value:
        amr:
          - pwd
        createdAt: '2019-08-24T14:15:22Z'
        expiresAt: '2019-08-24T14:15:22Z'
        id: l7FbDVqS8zHSy65uJD85
        idp:
          id: 01a2bcdef3GHIJKLMNOP
          type: ACTIVE_DIRECTORY
        lastFactorVerification: '2019-08-24T14:15:22Z'
        lastPasswordVerification: '2019-08-24T14:15:22Z'
        login: user@example.com
        status: ACTIVE
        userId: 00u0abcdefGHIJKLMNOP
        _links:
          self:
            hints:
              allow:
                - DELETE
          href: https://{yourOktaDomain}/api/v1/sessions/l7FbDVqS8zHSy65uJD85
    RefreshSessionResponse:
      summary: Refresh an existing session using the session ID
      value:
        amr:
          - pwd
        createdAt: '2019-08-25T14:17:22Z'
        expiresAt: '2019-08-25T14:17:22Z'
        id: l7FbDVqS8zHSy65uJD85
        idp:
          id: 01a2bcdef3GHIJKLMNOP
          type: ACTIVE_DIRECTORY
        lastFactorVerification: '2019-08-24T14:15:22Z'
        lastPasswordVerification: '2019-08-24T14:15:22Z'
        login: user@example.com
        status: ACTIVE
        userId: 00u0abcdefGHIJKLMNOP
        _links:
          self:
            hints:
              allow:
                - DELETE
          href: https://{yourOktaDomain}/api/v1/sessions/l7FbDVqS8zHSy65uJD85
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorTooManyRequests:
      summary: Too Many Requests
      value:
        errorCode: E0000047
        errorSummary: API call exceeded rate limit due to too many requests.
        errorLink: E0000047
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
    ErrorResourceNotFound:
      summary: Resource Not Found
      value:
        errorCode: E0000007
        errorSummary: 'Not found: {0}'
        errorLink: E0000007
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
  x-stackQL-resources:
    sessions:
      id: okta.sessions.sessions
      name: sessions
      title: Sessions
      methods:
        get_session:
          operation:
            $ref: '#/paths/~1api~1v1~1sessions~1{sessionId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        revoke_session:
          operation:
            $ref: '#/paths/~1api~1v1~1sessions~1{sessionId}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        refresh_session:
          operation:
            $ref: '#/paths/~1api~1v1~1sessions~1{sessionId}~1lifecycle~1refresh/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/sessions/methods/get_session'
        insert: []
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/sessions/methods/revoke_session'
        replace: []
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
x-stackQL-config:
  pagination:
    requestToken:
      key: ''
      location: request
    responseToken:
      key: Link
      location: header
  queryParamPushdown:
    top:
      paramName: limit
      maxValue: 200
