openapi: 3.0.3
info:
  title: templates API
  description: okta templates API
  version: 5.1.0
paths:
  /api/v1/templates/sms:
    get:
      summary: List all SMS templates
      description: >-
        Lists all custom SMS templates. A subset of templates can be returned
        that match a template type.
      operationId: listSmsTemplates
      parameters:
        - name: templateType
          in: query
          schema:
            $ref: '#/components/schemas/SmsTemplateType'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SmsTemplate'
              examples:
                SMS Template List response:
                  $ref: '#/components/examples/SMSTemplateListResponse'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.templates.read
      tags:
        - Template
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    post:
      summary: Create an SMS template
      description: Creates a new custom SMS template
      operationId: createSmsTemplate
      x-codegen-request-body-name: smsTemplate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmsTemplate'
            examples:
              Create an SMS Template request:
                $ref: '#/components/examples/CreateOrReplaceSMSTemplateRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsTemplate'
              examples:
                Create an SMS Template response:
                  $ref: '#/components/examples/CreateOrReplaceSMSTemplateResponse'
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.templates.manage
      tags:
        - Template
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
  /api/v1/templates/sms/{templateId}:
    get:
      summary: Retrieve an SMS template
      description: Retrieves a specific template by `id`
      operationId: getSmsTemplate
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsTemplate'
              examples:
                Get an SMS template response:
                  $ref: '#/components/examples/CreateOrReplaceSMSTemplateResponse'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.templates.read
      tags:
        - Template
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    post:
      summary: Update an SMS template
      description: |
        Updates only some of the SMS Template properties:
          * All properties within the custom SMS Template that have values are updated.
          * Any translation that doesn't exist is added.
          * Any translation with a null or empty value is removed.
          * Any translation with non-empty/null value is updated.
      operationId: updateSmsTemplate
      x-codegen-request-body-name: smsTemplate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmsTemplate'
            examples:
              Update an SMS Template request:
                $ref: '#/components/examples/UpdateSMSTemplateRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsTemplate'
              examples:
                Update an SMS Template response:
                  $ref: '#/components/examples/UpdateSMSTemplateResponse'
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.templates.manage
      tags:
        - Template
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    put:
      summary: Replace an SMS template
      description: |
        Replaces the SMS Template
        > **Notes:** You can't update the default SMS Template.
      operationId: replaceSmsTemplate
      x-codegen-request-body-name: smsTemplate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmsTemplate'
            examples:
              Replace an SMS Template request:
                $ref: '#/components/examples/CreateOrReplaceSMSTemplateRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsTemplate'
              examples:
                Replace an SMS Template response:
                  $ref: '#/components/examples/CreateOrReplaceSMSTemplateResponse'
        '400':
          $ref: '#/components/responses/ErrorApiValidationFailed400'
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.templates.manage
      tags:
        - Template
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    delete:
      summary: Delete an SMS template
      description: Deletes an SMS template
      operationId: deleteSmsTemplate
      responses:
        '204':
          description: No Content
          content: {}
        '403':
          $ref: '#/components/responses/ErrorAccessDenied403'
        '404':
          $ref: '#/components/responses/ErrorResourceNotFound404'
        '429':
          $ref: '#/components/responses/ErrorTooManyRequests429'
      security:
        - apiToken: []
        - oauth2:
            - okta.templates.manage
      tags:
        - Template
      x-okta-lifecycle:
        lifecycle: GA
        isGenerallyAvailable: true
    parameters:
      - $ref: '#/components/parameters/pathTemplateId'
components:
  schemas:
    SmsTemplateType:
      description: Type of the Template
      maxLength: 50
      minLength: 1
      type: string
      enum:
        - SMS_VERIFY_CODE
    SmsTemplate:
      type: object
      properties:
        created:
          type: string
          format: date-time
          readOnly: true
        id:
          type: string
          readOnly: true
        lastUpdated:
          type: string
          format: date-time
          readOnly: true
        name:
          type: string
          description: Human-readable name of the Template
          maxLength: 50
          minLength: 1
        template:
          type: string
          description: >-
            Text of the Template, including any
            [macros](https://developer.okta.com/docs/apihttps://developer.okta.com/docs/api/openapi/okta-management/management/tag/Template/)
          maxLength: 161
          minLength: 1
        translations:
          $ref: '#/components/schemas/SmsTemplateTranslations'
        type:
          $ref: '#/components/schemas/SmsTemplateType'
    SmsTemplateTranslations:
      description: >
        - Template translations are optionally provided when you want to
        localize the SMS messages. Translations are provided as an object that
        contains `key:value` pairs: the language and the translated Template
        text. The key portion is a two-letter country code that conforms to [ISO
        639-1](https://www.loc.gov/standards/iso639-2/php/code_list.php). The
        value is the translated SMS Template.

        - Just like with regular SMS Templates, the length of the SMS message
        can't exceed 160 characters.
      type: object
      x-okta-extensible: true
    Error:
      title: Error
      type: object
      properties:
        errorCauses:
          type: array
          items:
            $ref: '#/components/schemas/ErrorCause'
        errorCode:
          type: string
          description: An Okta code for this type of error
        errorId:
          type: string
          description: >-
            A unique identifier for this error. This can be used by Okta Support
            to help with troubleshooting.
        errorLink:
          type: string
          description: An Okta code for this type of error
        errorSummary:
          type: string
          description: >-
            A short description of what caused this error. Sometimes this
            contains dynamically-generated information about your specific
            error.
    ErrorCause:
      type: object
      properties:
        errorSummary:
          type: string
  responses:
    ErrorAccessDenied403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            AccessDenied:
              $ref: '#/components/examples/ErrorAccessDenied'
    ErrorTooManyRequests429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            TooManyRequests:
              $ref: '#/components/examples/ErrorTooManyRequests'
    ErrorApiValidationFailed400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            APIValidationFailed:
              $ref: '#/components/examples/ErrorApiValidationFailed'
    ErrorResourceNotFound404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            ResourceNotFound:
              $ref: '#/components/examples/ErrorResourceNotFound'
  parameters:
    pathTemplateId:
      name: templateId
      description: '`id` of the Template'
      in: path
      required: true
      schema:
        type: string
        example: 6NQUJ5yR3bpgEiYmq8IC
  examples:
    SMSTemplateListResponse:
      value:
        - id: 6NQUJ5yR3bpgEiYmq8IC
          name: Custom
          type: SMS_VERIFY_CODE
          template: '${org.name}: your verification code is ${code}'
          translations:
            es: '${org.name}: el código de verificación es ${code}'
            fr: '${org.name}: votre code de vérification est ${code}'
            it: '${org.name}: il codice di verifica è ${code}'
          created: '2024-04-25T17:35:02.000Z'
          lastUpdated: '2024-04-25T17:35:02.000Z'
    CreateOrReplaceSMSTemplateRequest:
      value:
        name: Custom
        type: SMS_VERIFY_CODE
        template: '${org.name}: your verification code is ${code}'
        translations:
          es: '${org.name}: el código de verificación es ${code}'
          fr: '${org.name}: votre code de vérification est ${code}'
          it: '${org.name}: il codice di verifica è ${code}'
    CreateOrReplaceSMSTemplateResponse:
      value:
        id: 6NQUJ5yR3bpgEiYmq8IC
        name: Custom
        type: SMS_VERIFY_CODE
        template: '${org.name}: your verification code is ${code}'
        translations:
          es: '${org.name}: el código de verificación es ${code}'
          fr: '${org.name}: votre code de vérification est ${code}'
          it: '${org.name}: il codice di verifica è ${code}'
        created: '2024-04-25T17:35:02.000Z'
        lastUpdated: '2024-04-25T17:35:02.000Z'
    UpdateSMSTemplateRequest:
      value:
        translations:
          de: '${org.name}: ihre bestätigungscode ist ${code}.'
    UpdateSMSTemplateResponse:
      value:
        id: 6NQUJ5yR3bpgEiYmq8IC
        name: Custom
        type: SMS_VERIFY_CODE
        template: '${org.name}: your verification code is ${code}'
        translations:
          es: '${org.name}: el código de verificación es ${code}'
          fr: '${org.name}: votre code de vérification est ${code}'
          it: '${org.name}: il codice di verifica è ${code}'
          de: '${org.name}: ihre bestätigungscode ist ${code}.'
        created: '2024-04-25T17:35:02.000Z'
        lastUpdated: '2024-04-25T17:35:02.000Z'
    ErrorAccessDenied:
      summary: Access Denied
      value:
        errorCode: E0000006
        errorSummary: You do not have permission to perform the requested action
        errorLink: E0000006
        errorId: sampleNUSD_8fdkFd8fs8SDBK
        errorCauses: []
    ErrorTooManyRequests:
      summary: Too Many Requests
      value:
        errorCode: E0000047
        errorSummary: API call exceeded rate limit due to too many requests.
        errorLink: E0000047
        errorId: sampleQPivGUj_ND5v78vbYWW
        errorCauses: []
    ErrorApiValidationFailed:
      summary: API Validation Failed
      value:
        errorCode: E0000001
        errorSummary: 'Api validation failed: {0}'
        errorLink: E0000001
        errorId: sampleiCF-8D5rLW6myqiPItW
        errorCauses: []
    ErrorResourceNotFound:
      summary: Resource Not Found
      value:
        errorCode: E0000007
        errorSummary: 'Not found: {0}'
        errorLink: E0000007
        errorId: sampleMlLvGUj_YD5v16vkYWY
        errorCauses: []
  x-stackQL-resources:
    sms_templates:
      id: okta.templates.sms_templates
      name: sms_templates
      title: Sms Templates
      methods:
        list_sms_templates:
          operation:
            $ref: '#/paths/~1api~1v1~1templates~1sms/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        create_sms_template:
          operation:
            $ref: '#/paths/~1api~1v1~1templates~1sms/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get_sms_template:
          operation:
            $ref: '#/paths/~1api~1v1~1templates~1sms~1{templateId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        update_sms_template:
          operation:
            $ref: '#/paths/~1api~1v1~1templates~1sms~1{templateId}/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        replace_sms_template:
          operation:
            $ref: '#/paths/~1api~1v1~1templates~1sms~1{templateId}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete_sms_template:
          operation:
            $ref: '#/paths/~1api~1v1~1templates~1sms~1{templateId}/delete'
          response:
            mediaType: ''
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/sms_templates/methods/list_sms_templates
          - $ref: >-
              #/components/x-stackQL-resources/sms_templates/methods/get_sms_template
        insert:
          - $ref: >-
              #/components/x-stackQL-resources/sms_templates/methods/create_sms_template
        update:
          - $ref: >-
              #/components/x-stackQL-resources/sms_templates/methods/update_sms_template
        delete:
          - $ref: >-
              #/components/x-stackQL-resources/sms_templates/methods/delete_sms_template
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/sms_templates/methods/replace_sms_template
servers:
  - url: https://{subdomain}.okta.com/
    variables:
      subdomain:
        default: my-org
        description: >-
          The domain of your organization. This can be a provided subdomain of
          an official okta domain (okta.com, oktapreview.com, etc) or one of
          your configured custom domains.
