components:
  schemas:
    ThreatInsightConfiguration:
      properties:
        _links:
          additionalProperties:
            properties: {}
            type: object
          readOnly: true
          type: object
        action:
          type: string
        created:
          format: date-time
          readOnly: true
          type: string
        excludeZones:
          items:
            type: string
          type: array
        lastUpdated:
          format: date-time
          readOnly: true
          type: string
      type: object
      x-okta-crud:
      - alias: read
        arguments: []
        operationId: getCurrentConfiguration
      - alias: update
        arguments:
        - dest: threatInsightConfiguration
          self: true
        operationId: updateConfiguration
      x-okta-tags:
      - ThreatInsight
  securitySchemes:
    api_token:
      description: SSWS {API Token}
      in: header
      name: Authorization
      type: apiKey
  x-stackQL-resources:
    configuration:
      id: okta.threatinsight.configuration
      methods:
        get:
          operation:
            $ref: '#/paths/~1api~1v1~1threats~1configuration/GET'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      name: configuration
      title: configuration
externalDocs:
  description: Find more info here
  url: https://developer.okta.com/docs/api/getting_started/design_principles.html
info:
  contact:
    email: devex-public@okta.com
    name: Okta Developer Team
    url: https://developer.okta.com/
  description: Allows customers to easily access the Okta API
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developer.okta.com/terms/
  title: Okta API
  version: 2.8.0
openapi: 3.0.1
paths:
  /api/v1/threats/configuration:
    get:
      description: Gets current ThreatInsight configuration
      operationId: getCurrentConfiguration
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreatInsightConfiguration'
          description: Success
      security:
      - api_token: []
      tags:
      - ThreatInsight
    post:
      description: Updates ThreatInsight configuration
      operationId: updateConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThreatInsightConfiguration'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreatInsightConfiguration'
          description: Success
      security:
      - api_token: []
      tags:
      - ThreatInsight
      x-codegen-request-body-name: ThreatInsightConfiguration
servers:
- url: https://{subdomain}.okta.com/
  variables:
    subdomain:
      default: my-domain
