components:
  schemas:
    AllowedForEnum:
      enum:
      - recovery
      - sso
      - any
      - none
      type: string
      x-okta-tags:
      - Authenticator
    Authenticator:
      properties:
        _links:
          additionalProperties:
            properties: {}
            type: object
          readOnly: true
          type: object
        created:
          format: date-time
          readOnly: true
          type: string
        id:
          readOnly: true
          type: string
        key:
          type: string
        lastUpdated:
          format: date-time
          readOnly: true
          type: string
        name:
          type: string
        settings:
          $ref: '#/components/schemas/AuthenticatorSettings'
        status:
          $ref: '#/components/schemas/AuthenticatorStatus'
        type:
          $ref: '#/components/schemas/AuthenticatorType'
      type: object
      x-okta-operations:
      - alias: activate
        arguments:
        - dest: authenticatorId
          src: id
        operationId: activateAuthenticator
      - alias: deactivate
        arguments:
        - dest: authenticatorId
          src: id
        operationId: deactivateAuthenticator
      x-okta-tags:
      - Authenticator
    AuthenticatorSettings:
      properties:
        allowedFor:
          $ref: '#/components/schemas/AllowedForEnum'
        tokenLifetimeInMinutes:
          type: integer
      type: object
      x-okta-tags:
      - Authenticator
    AuthenticatorStatus:
      enum:
      - ACTIVE
      - INACTIVE
      type: string
      x-okta-tags:
      - Authenticator
    AuthenticatorType:
      enum:
      - app
      - password
      - security_question
      - phone
      - email
      - security_key
      - federated
      type: string
      x-okta-tags:
      - Authenticator
  securitySchemes:
    api_token:
      description: SSWS {API Token}
      in: header
      name: Authorization
      type: apiKey
  x-stackQL-resources:
    authenticators:
      id: okta.authenticator.authenticators
      methods:
        activate:
          operation:
            $ref: POST
          path:
            $ref: /api/v1/authenticators/{authenticatorId}/lifecycle/activate
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        deactivate:
          operation:
            $ref: POST
          path:
            $ref: /api/v1/authenticators/{authenticatorId}/lifecycle/deactivate
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get:
          operation:
            $ref: GET
          path:
            $ref: /api/v1/authenticators/{authenticatorId}
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        list:
          operation:
            $ref: GET
          path:
            $ref: /api/v1/authenticators
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      name: authenticators
      title: authenticators
externalDocs:
  description: Find more info here
  url: https://developer.okta.com/docs/api/getting_started/design_principles.html
info:
  contact:
    email: devex-public@okta.com
    name: Okta Developer Team
    url: https://developer.okta.com/
  description: Allows customers to easily access the Okta API
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developer.okta.com/terms/
  title: Okta API
  version: 2.8.0
openapi: 3.0.1
paths:
  /api/v1/authenticators:
    get:
      description: Success
      operationId: listAuthenticators
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Authenticator'
                type: array
          description: Success
      security:
      - api_token: []
      tags:
      - Authenticator
  /api/v1/authenticators/{authenticatorId}:
    get:
      description: Success
      operationId: getAuthenticator
      parameters:
      - in: path
        name: authenticatorId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authenticator'
          description: Success
      security:
      - api_token: []
      tags:
      - Authenticator
  /api/v1/authenticators/{authenticatorId}/lifecycle/activate:
    post:
      description: Success
      operationId: activateAuthenticator
      parameters:
      - in: path
        name: authenticatorId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authenticator'
          description: Success
      security:
      - api_token: []
      tags:
      - Authenticator
  /api/v1/authenticators/{authenticatorId}/lifecycle/deactivate:
    post:
      description: Success
      operationId: deactivateAuthenticator
      parameters:
      - in: path
        name: authenticatorId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authenticator'
          description: Success
      security:
      - api_token: []
      tags:
      - Authenticator
servers:
- url: https://{subdomain}.okta.com/
  variables:
    subdomain:
      default: my-domain
