components:
  schemas:
    InlineHook:
      properties:
        _links:
          additionalProperties:
            properties: {}
            type: object
          readOnly: true
          type: object
        channel:
          $ref: '#/components/schemas/InlineHookChannel'
        created:
          format: date-time
          readOnly: true
          type: string
        id:
          readOnly: true
          type: string
        lastUpdated:
          format: date-time
          readOnly: true
          type: string
        name:
          type: string
        status:
          $ref: '#/components/schemas/InlineHookStatus'
        type:
          $ref: '#/components/schemas/InlineHookType'
        version:
          type: string
      type: object
      x-okta-crud:
      - alias: create
        arguments:
        - dest: inlineHook
          self: true
        operationId: createInlineHook
      - alias: read
        arguments: []
        operationId: getInlineHook
      - alias: update
        arguments:
        - dest: inlineHookId
          src: id
        - dest: inlineHook
          self: true
        operationId: updateInlineHook
      - alias: delete
        arguments:
        - dest: inlineHookId
          src: id
        operationId: deleteInlineHook
      x-okta-operations:
      - alias: activate
        arguments:
        - dest: inlineHookId
          src: id
        operationId: activateInlineHook
      - alias: deactivate
        arguments:
        - dest: inlineHookId
          src: id
        operationId: deactivateInlineHook
      - alias: execute
        arguments:
        - dest: inlineHookId
          src: id
        operationId: executeInlineHook
      x-okta-tags:
      - InlineHook
    InlineHookChannel:
      properties:
        config:
          $ref: '#/components/schemas/InlineHookChannelConfig'
        type:
          enum:
          - HTTP
          type: string
        version:
          type: string
      type: object
      x-okta-tags:
      - InlineHook
    InlineHookChannelConfig:
      properties:
        authScheme:
          $ref: '#/components/schemas/InlineHookChannelConfigAuthScheme'
        headers:
          items:
            $ref: '#/components/schemas/InlineHookChannelConfigHeaders'
          type: array
        method:
          type: string
        uri:
          type: string
      type: object
      x-okta-tags:
      - InlineHook
    InlineHookChannelConfigAuthScheme:
      properties:
        key:
          type: string
        type:
          type: string
        value:
          type: string
      type: object
      x-okta-tags:
      - InlineHook
    InlineHookChannelConfigHeaders:
      properties:
        key:
          type: string
        value:
          type: string
      type: object
      x-okta-tags:
      - InlineHook
    InlineHookPayload:
      type: object
      x-okta-extensible: true
      x-okta-tags:
      - InlineHook
    InlineHookResponse:
      properties:
        commands:
          items:
            $ref: '#/components/schemas/InlineHookResponseCommands'
          type: array
      type: object
      x-okta-tags:
      - InlineHook
    InlineHookResponseCommandValue:
      properties:
        op:
          type: string
        path:
          type: string
        value:
          type: string
      type: object
      x-okta-tags:
      - InlineHook
    InlineHookResponseCommands:
      properties:
        type:
          type: string
        value:
          items:
            $ref: '#/components/schemas/InlineHookResponseCommandValue'
          type: array
      type: object
      x-okta-tags:
      - InlineHook
    InlineHookStatus:
      enum:
      - ACTIVE
      - INACTIVE
      type: string
      x-okta-tags:
      - InlineHook
    InlineHookType:
      enum:
      - com.okta.oauth2.tokens.transform
      - com.okta.import.transform
      - com.okta.saml.tokens.transform
      - com.okta.user.pre-registration
      - com.okta.user.credential.password.import
      type: string
      x-okta-tags:
      - InlineHook
  securitySchemes:
    api_token:
      description: SSWS {API Token}
      in: header
      name: Authorization
      type: apiKey
  x-stackQL-resources:
    idps:
      id: okta.inlinehook.idps
      methods:
        activate:
          operation:
            $ref: POST
          path:
            $ref: /api/v1/inlineHooks/{inlineHookId}/lifecycle/activate
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        deactivate:
          operation:
            $ref: POST
          path:
            $ref: /api/v1/inlineHooks/{inlineHookId}/lifecycle/deactivate
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete:
          operation:
            $ref: DELETE
          path:
            $ref: /api/v1/inlineHooks/{inlineHookId}
          response:
            openAPIDocKey: '204'
        execute:
          operation:
            $ref: POST
          path:
            $ref: /api/v1/inlineHooks/{inlineHookId}/execute
          request:
            mediaType: application/json
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get:
          operation:
            $ref: GET
          path:
            $ref: /api/v1/inlineHooks/{inlineHookId}
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        insert:
          operation:
            $ref: POST
          path:
            $ref: /api/v1/inlineHooks
          request:
            mediaType: application/json
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        list:
          operation:
            $ref: GET
          path:
            $ref: /api/v1/inlineHooks
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        update:
          operation:
            $ref: PUT
          path:
            $ref: /api/v1/inlineHooks/{inlineHookId}
          request:
            mediaType: application/json
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      name: idps
      title: idps
externalDocs:
  description: Find more info here
  url: https://developer.okta.com/docs/api/getting_started/design_principles.html
info:
  contact:
    email: devex-public@okta.com
    name: Okta Developer Team
    url: https://developer.okta.com/
  description: Allows customers to easily access the Okta API
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developer.okta.com/terms/
  title: Okta API
  version: 2.8.0
openapi: 3.0.1
paths:
  /api/v1/inlineHooks:
    get:
      description: Success
      operationId: listInlineHooks
      parameters:
      - in: query
        name: type
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/InlineHook'
                type: array
          description: Success
      security:
      - api_token: []
      tags:
      - InlineHook
    post:
      description: Success
      operationId: createInlineHook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InlineHook'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InlineHook'
          description: Success
      security:
      - api_token: []
      tags:
      - InlineHook
      x-codegen-request-body-name: inlineHook
  /api/v1/inlineHooks/{inlineHookId}:
    delete:
      description: Deletes the Inline Hook matching the provided id. Once deleted,
        the Inline Hook is unrecoverable. As a safety precaution, only Inline Hooks
        with a status of INACTIVE are eligible for deletion.
      operationId: deleteInlineHook
      parameters:
      - in: path
        name: inlineHookId
        required: true
        schema:
          type: string
      responses:
        '204':
          content: {}
          description: No Content
      security:
      - api_token: []
      tags:
      - InlineHook
    get:
      description: Gets an inline hook by ID
      operationId: getInlineHook
      parameters:
      - in: path
        name: inlineHookId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InlineHook'
          description: Success
      security:
      - api_token: []
      tags:
      - InlineHook
    put:
      description: Updates an inline hook by ID
      operationId: updateInlineHook
      parameters:
      - in: path
        name: inlineHookId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InlineHook'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InlineHook'
          description: Success
      security:
      - api_token: []
      tags:
      - InlineHook
      x-codegen-request-body-name: inlineHook
  /api/v1/inlineHooks/{inlineHookId}/execute:
    post:
      description: Executes the Inline Hook matching the provided inlineHookId using
        the request body as the input. This will send the provided data through the
        Channel and return a response if it matches the correct data contract. This
        execution endpoint should only be used for testing purposes.
      operationId: executeInlineHook
      parameters:
      - in: path
        name: inlineHookId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InlineHookPayload'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InlineHookResponse'
          description: Success
      security:
      - api_token: []
      tags:
      - InlineHook
      x-codegen-request-body-name: payloadData
  /api/v1/inlineHooks/{inlineHookId}/lifecycle/activate:
    post:
      description: Activates the Inline Hook matching the provided id
      operationId: activateInlineHook
      parameters:
      - in: path
        name: inlineHookId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InlineHook'
          description: Success
      security:
      - api_token: []
      tags:
      - InlineHook
  /api/v1/inlineHooks/{inlineHookId}/lifecycle/deactivate:
    post:
      description: Deactivates the Inline Hook matching the provided id
      operationId: deactivateInlineHook
      parameters:
      - in: path
        name: inlineHookId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InlineHook'
          description: Success
      security:
      - api_token: []
      tags:
      - InlineHook
servers:
- url: https://{subdomain}.okta.com/
  variables:
    subdomain:
      default: my-domain
