components:
  schemas:
    NetworkZone:
      properties:
        _links:
          additionalProperties:
            properties: {}
            type: object
          readOnly: true
          type: object
        asns:
          items:
            type: string
          type: array
        created:
          format: date-time
          readOnly: true
          type: string
        gateways:
          items:
            $ref: '#/components/schemas/NetworkZoneAddress'
          type: array
        id:
          readOnly: true
          type: string
        lastUpdated:
          format: date-time
          readOnly: true
          type: string
        locations:
          items:
            $ref: '#/components/schemas/NetworkZoneLocation'
          type: array
        name:
          type: string
        proxies:
          items:
            $ref: '#/components/schemas/NetworkZoneAddress'
          type: array
        proxyType:
          type: string
        status:
          $ref: '#/components/schemas/NetworkZoneStatus'
        system:
          type: boolean
        type:
          $ref: '#/components/schemas/NetworkZoneType'
        usage:
          $ref: '#/components/schemas/NetworkZoneUsage'
      type: object
      x-okta-crud:
      - alias: read
        arguments:
        - dest: zoneId
          src: id
        operationId: getNetworkZone
      - alias: update
        arguments:
        - dest: zoneId
          src: id
        - dest: zone
          self: true
        operationId: updateNetworkZone
      - alias: delete
        arguments:
        - dest: zoneId
          src: id
        operationId: deleteNetworkZone
      x-okta-operations:
      - alias: activate
        arguments:
        - dest: zoneId
          src: id
        operationId: activateNetworkZone
      - alias: deactivate
        arguments:
        - dest: zoneId
          src: id
        operationId: deactivateNetworkZone
      x-okta-tags:
      - NetworkZone
    NetworkZoneAddress:
      properties:
        type:
          $ref: '#/components/schemas/NetworkZoneAddressType'
        value:
          type: string
      type: object
      x-okta-tags:
      - NetworkZone
    NetworkZoneAddressType:
      enum:
      - CIDR
      - RANGE
      type: string
      x-okta-tags:
      - NetworkZone
    NetworkZoneLocation:
      properties:
        country:
          type: string
        region:
          type: string
      type: object
      x-okta-tags:
      - NetworkZone
    NetworkZoneStatus:
      enum:
      - ACTIVE
      - INACTIVE
      type: string
      x-okta-tags:
      - NetworkZone
    NetworkZoneType:
      enum:
      - IP
      - DYNAMIC
      type: string
      x-okta-tags:
      - NetworkZone
    NetworkZoneUsage:
      enum:
      - POLICY
      - BLOCKLIST
      type: string
      x-okta-tags:
      - NetworkZone
  securitySchemes:
    api_token:
      description: SSWS {API Token}
      in: header
      name: Authorization
      type: apiKey
  x-stackQL-resources:
    zones:
      id: okta.networkzone.zones
      methods:
        activate:
          operation:
            $ref: POST
          path:
            $ref: /api/v1/zones/{zoneId}/lifecycle/activate
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        deactivate:
          operation:
            $ref: POST
          path:
            $ref: /api/v1/zones/{zoneId}/lifecycle/deactivate
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete:
          operation:
            $ref: DELETE
          path:
            $ref: /api/v1/zones/{zoneId}
          response:
            openAPIDocKey: '200'
        get:
          operation:
            $ref: GET
          path:
            $ref: /api/v1/zones/{zoneId}
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        insert:
          operation:
            $ref: POST
          path:
            $ref: /api/v1/zones
          request:
            mediaType: application/json
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        list:
          operation:
            $ref: GET
          path:
            $ref: /api/v1/zones
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        update:
          operation:
            $ref: PUT
          path:
            $ref: /api/v1/zones/{zoneId}
          request:
            mediaType: application/json
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      name: zones
      title: zones
externalDocs:
  description: Find more info here
  url: https://developer.okta.com/docs/api/getting_started/design_principles.html
info:
  contact:
    email: devex-public@okta.com
    name: Okta Developer Team
    url: https://developer.okta.com/
  description: Allows customers to easily access the Okta API
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developer.okta.com/terms/
  title: Okta API
  version: 2.8.0
openapi: 3.0.1
paths:
  /api/v1/zones:
    get:
      description: Enumerates network zones added to your organization with pagination.
        A subset of zones can be returned that match a supported filter expression
        or query.
      operationId: listNetworkZones
      parameters:
      - description: Specifies the pagination cursor for the next page of network
          zones
        in: query
        name: after
        schema:
          type: string
      - description: Specifies the number of results for a page
        in: query
        name: limit
        schema:
          default: -1
          format: int32
          type: integer
      - description: Filters zones by usage or id expression
        in: query
        name: filter
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/NetworkZone'
                type: array
          description: Success
      security:
      - api_token: []
      summary: List Network Zones
      tags:
      - NetworkZone
    post:
      description: Adds a new network zone to your Okta organization.
      operationId: createNetworkZone
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetworkZone'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkZone'
          description: Success
      security:
      - api_token: []
      summary: Add Network Zone
      tags:
      - NetworkZone
      x-codegen-request-body-name: zone
  /api/v1/zones/{zoneId}:
    delete:
      description: Removes network zone.
      operationId: deleteNetworkZone
      parameters:
      - in: path
        name: zoneId
        required: true
        schema:
          type: string
      responses:
        '200':
          content: {}
          description: Success
      security:
      - api_token: []
      summary: Delete Network Zone
      tags:
      - NetworkZone
    get:
      description: Fetches a network zone from your Okta organization by `id`.
      operationId: getNetworkZone
      parameters:
      - in: path
        name: zoneId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkZone'
          description: Success
      security:
      - api_token: []
      summary: Get Network Zone
      tags:
      - NetworkZone
    put:
      description: Updates a network zone in your organization.
      operationId: updateNetworkZone
      parameters:
      - in: path
        name: zoneId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NetworkZone'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkZone'
          description: Success
      security:
      - api_token: []
      summary: Update Network Zone
      tags:
      - NetworkZone
      x-codegen-request-body-name: zone
  /api/v1/zones/{zoneId}/lifecycle/activate:
    post:
      description: Activate Network Zone
      operationId: activateNetworkZone
      parameters:
      - in: path
        name: zoneId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkZone'
          description: Success
      security:
      - api_token: []
      summary: Activate Network Zone
      tags:
      - NetworkZone
  /api/v1/zones/{zoneId}/lifecycle/deactivate:
    post:
      description: Deactivates a network zone.
      operationId: deactivateNetworkZone
      parameters:
      - in: path
        name: zoneId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkZone'
          description: Success
      security:
      - api_token: []
      summary: Deactivate Network Zone
      tags:
      - NetworkZone
servers:
- url: https://{subdomain}.okta.com/
  variables:
    subdomain:
      default: my-domain
