id: aws
name: aws
version: v0.1.3
providerServices:
  cloud_control:
    description: cloud_control
    id: cloud_control:v0.1.3
    name: cloud_control
    preferred: true
    service:
      $ref: aws/v0.1.3/services/cloud_control.yaml
    title: Cloud Control API
    version: v0.1.3
  ec2:
    description: ec2
    id: ec2:v0.1.3
    name: ec2
    preferred: true
    service:
      $ref: aws/v0.1.3/services/ec2.yaml
    title: EC2
    version: v0.1.3
  iam:
    description: iam
    id: iam:v0.1.3
    name: ec2
    preferred: true
    service:
      $ref: aws/v0.1.3/services/iam.yaml
    title: IAM
    version: v0.1.3
  s3:
    description: s3
    id: s3:v0.1.3
    name: s3
    preferred: true
    service:
      $ref: aws/v0.1.3/services/s3.yaml
    title: S3
    version: v0.1.3
openapi: 3.0.0
