paths:
  /user/interaction-limits:
    get:
      summary: Get interaction restrictions for your public repositories
      description: Shows which type of GitHub user can interact with your public repositories and when the restriction expires.
      tags:
        - interactions
      operationId: interactions/get-restrictions-for-authenticated-user
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/reference/interactions#get-interaction-restrictions-for-your-public-repositories
      responses:
        '200':
          description: Default response
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/interaction-limit-response'
                  - type: object
                    properties: {}
                    additionalProperties: false
              examples:
                default:
                  $ref: '#/components/examples/interaction-limit-response'
        '204':
          description: Response when there are no restrictions
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: interactions
        subcategory: user
    put:
      summary: Set interaction restrictions for your public repositories
      description: Temporarily restricts which type of GitHub user can interact with your public repositories. Setting the interaction limit at the user level will overwrite any interaction limits that are set for individual repositories owned by the user.
      tags:
        - interactions
      operationId: interactions/set-restrictions-for-authenticated-user
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/reference/interactions#set-interaction-restrictions-for-your-public-repositories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/interaction-limit'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/interaction-limit-response'
              examples:
                default:
                  $ref: '#/components/examples/interaction-limit-user'
        '422':
          $ref: '#/components/responses/validation_failed'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: interactions
        subcategory: user
    delete:
      summary: Remove interaction restrictions from your public repositories
      description: Removes any interaction restrictions from your public repositories.
      tags:
        - interactions
      operationId: interactions/remove-restrictions-for-authenticated-user
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/reference/interactions#remove-interaction-restrictions-from-your-public-repositories
      responses:
        '204':
          description: Response
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: interactions
        subcategory: user
components:
  schemas:
    interaction-limit-response:
      title: Interaction Limits
      description: Interaction limit settings.
      type: object
      properties:
        limit:
          $ref: '#/components/schemas/interaction-group'
        origin:
          type: string
          example: repository
        expires_at:
          type: string
          format: date-time
          example: '2018-08-17T04:18:39Z'
      required:
        - limit
        - origin
        - expires_at
    interaction-group:
      type: string
      description: 'The type of GitHub user that can comment, open issues, or create pull requests while the interaction limit is in effect. Can be one of: `existing_users`, `contributors_only`, `collaborators_only`.'
      example: collaborators_only
      enum:
        - existing_users
        - contributors_only
        - collaborators_only
    interaction-limit:
      title: Interaction Restrictions
      description: Limit interactions to a specific type of user for a specified duration
      type: object
      properties:
        limit:
          $ref: '#/components/schemas/interaction-group'
        expiry:
          $ref: '#/components/schemas/interaction-expiry'
      required:
        - limit
    interaction-expiry:
      type: string
      description: 'The duration of the interaction restriction. Can be one of: `one_day`, `three_days`, `one_week`, `one_month`, `six_months`. Default: `one_day`.'
      example: one_month
      enum:
        - one_day
        - three_days
        - one_week
        - one_month
        - six_months
    validation-error:
      title: Validation Error
      description: Validation Error
      type: object
      required:
        - message
        - documentation_url
      properties:
        message:
          type: string
        documentation_url:
          type: string
        errors:
          type: array
          items:
            type: object
            required:
              - code
            properties:
              resource:
                type: string
              field:
                type: string
              message:
                type: string
              code:
                type: string
              index:
                type: integer
              value:
                oneOf:
                  - type: string
                    nullable: true
                  - type: integer
                    nullable: true
                  - type: array
                    nullable: true
                    items:
                      type: string
  parameters: {}
  responses:
    validation_failed:
      description: Validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/validation-error'
  securitySchemes: {}
  callbacks: {}
  examples:
    interaction-limit-response:
      value:
        limit: collaborators_only
        origin: organization
        expires_at: '2018-08-17T04:18:39Z'
    interaction-limit-user:
      value:
        limit: collaborators_only
        origin: user
        expires_at: '2018-08-17T04:18:39Z'
  requestBodies: {}
  headers: {}
  links: {}
  x-stackQL-resources:
    user:
      id: github.interactions.user
      name: user
      title: user
      methods:
        get_restrictions_for_authenticated_user:
          operation:
            $ref: '#/paths/~1user~1interaction-limits/get'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        set_restrictions_for_authenticated_user:
          operation:
            $ref: '#/paths/~1user~1interaction-limits/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        remove_restrictions_for_authenticated_user:
          operation:
            $ref: '#/paths/~1user~1interaction-limits/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/user/methods/get_restrictions_for_authenticated_user'
        insert: []
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/user/methods/remove_restrictions_for_authenticated_user'
openapi: 3.0.3
servers:
  - url: https://api.github.com
tags:
  - name: actions
    description: Endpoints to manage GitHub Actions using the REST API.
  - name: activity
    description: Activity APIs provide access to notifications, subscriptions, and timelines.
  - name: apps
    description: Information for integrations and installations.
  - name: billing
    description: Monitor charges and usage from Actions and Packages.
  - name: checks
    description: Rich interactions with checks run by your integrations.
  - name: code-scanning
    description: Retrieve code scanning alerts from a repository.
  - name: codes-of-conduct
    description: Insight into codes of conduct for your communities.
  - name: codespaces
    description: Endpoints to manage Codespaces using the REST API.
  - name: emojis
    description: List emojis available to use on GitHub.
  - name: enterprise-admin
    description: Administer a GitHub enterprise.
  - name: dependabot
    description: Endpoints to manage Dependabot.
  - name: gists
    description: View, modify your gists.
  - name: git
    description: Raw Git functionality.
  - name: gitignore
    description: View gitignore templates
  - name: interactions
    description: Owner or admin management of users interactions.
  - name: issues
    description: Interact with GitHub Issues.
  - name: licenses
    description: View various OSS licenses.
  - name: markdown
    description: Render GitHub flavored markdown
  - name: meta
    description: Endpoints that give information about the API.
  - name: migrations
    description: Move projects to or from GitHub.
  - name: oauth-authorizations
    description: Manage access of OAuth applications
  - name: orgs
    description: Interact with GitHub Orgs.
  - name: packages
    description: Manage packages for authenticated users and organizations.
  - name: projects
    description: Interact with GitHub Projects.
  - name: pulls
    description: Interact with GitHub Pull Requests.
  - name: rate-limit
    description: Check your current rate limit status
  - name: reactions
    description: Interact with reactions to various GitHub entities.
  - name: repos
    description: Interact with GitHub Repos.
  - name: scim
    description: Provisioning of GitHub organization membership for SCIM-enabled providers.
  - name: search
    description: Look for stuff on GitHub.
  - name: secret-scanning
    description: Retrieve secret scanning alerts from a repository.
  - name: server-statistics
    description: GHES statistics
  - name: teams
    description: Interact with GitHub Teams.
  - name: users
    description: Interact with and view information about users and also current user.
externalDocs:
  description: GitHub v3 REST API
  url: https://docs.github.com/rest/
info:
  version: 1.1.4
  title: GitHub v3 REST API - interactions
  description: Owner or admin management of users interactions.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
