openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: 'https://github.com/stackql/google-discovery-to-openapi'
    email: info@stackql.io
  title: Advisory Notifications API
  description: An API for accessing Advisory Notifications in Google Cloud
  version: v1
  x-discovery-doc-revision: '20230820'
  x-generated-date: '2023-08-23'
externalDocs:
  url: 'https://cloud.google.com/advisory-notifications'
servers:
  - url: 'https://advisorynotifications.googleapis.com'
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
          scopes: &ref_0
            'https://www.googleapis.com/auth/cloud-platform': 'See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account.'
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
          tokenUrl: 'https://accounts.google.com/o/oauth2/token'
          scopes: *ref_0
  schemas:
    GoogleCloudAdvisorynotificationsV1CsvCsvRow:
      properties:
        entries:
          items:
            type: string
          type: array
          description: 'The data entries in a CSV file row, as a string array rather than a single comma-separated string.'
      id: GoogleCloudAdvisorynotificationsV1CsvCsvRow
      type: object
      description: A representation of a single data row in a CSV file.
    GoogleCloudAdvisorynotificationsV1Notification:
      properties:
        notificationType:
          type: string
          enumDescriptions:
            - Default type
            - Security and privacy advisory notifications
            - Sensitive action notifications
            - General security MSA
            - Threat horizons MSA
          enum:
            - NOTIFICATION_TYPE_UNSPECIFIED
            - NOTIFICATION_TYPE_SECURITY_PRIVACY_ADVISORY
            - NOTIFICATION_TYPE_SENSITIVE_ACTIONS
            - NOTIFICATION_TYPE_SECURITY_MSA
            - NOTIFICATION_TYPE_THREAT_HORIZONS
          description: Type of notification
        createTime:
          description: Output only. Time the notification was created.
          readOnly: true
          type: string
          format: google-datetime
        subject:
          $ref: '#/components/schemas/GoogleCloudAdvisorynotificationsV1Subject'
          description: The subject line of the notification.
        messages:
          description: A list of messages in the notification.
          type: array
          items:
            $ref: '#/components/schemas/GoogleCloudAdvisorynotificationsV1Message'
        name:
          description: 'The resource name of the notification. Format: organizations/{organization}/locations/{location}/notifications/{notification}.'
          type: string
      description: A notification object for notifying customers about security and privacy issues.
      id: GoogleCloudAdvisorynotificationsV1Notification
      type: object
    GoogleCloudAdvisorynotificationsV1Text:
      description: A text object containing the English text and its localized copies.
      properties:
        localizedText:
          type: string
          description: The requested localized copy (if applicable).
        localizationState:
          enumDescriptions:
            - Not used.
            - 'Localization is not applicable for requested language. This can happen when: - The requested language was not supported by Advisory Notifications at the time of localization (including notifications created before the localization feature was launched). - The requested language is English, so only the English text is returned.'
            - 'Localization for requested language is in progress, and not ready yet.'
            - Localization for requested language is completed.
          description: Status of the localization.
          enum:
            - LOCALIZATION_STATE_UNSPECIFIED
            - LOCALIZATION_STATE_NOT_APPLICABLE
            - LOCALIZATION_STATE_PENDING
            - LOCALIZATION_STATE_COMPLETED
          type: string
        enText:
          type: string
          description: The English copy.
      id: GoogleCloudAdvisorynotificationsV1Text
      type: object
    GoogleCloudAdvisorynotificationsV1ListNotificationsResponse:
      description: Response of ListNotifications endpoint.
      type: object
      properties:
        totalSize:
          type: integer
          description: Estimation of a total number of notifications.
          format: int32
        nextPageToken:
          description: 'A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.'
          type: string
        notifications:
          type: array
          items:
            $ref: '#/components/schemas/GoogleCloudAdvisorynotificationsV1Notification'
          description: List of notifications under a given parent.
      id: GoogleCloudAdvisorynotificationsV1ListNotificationsResponse
    GoogleCloudAdvisorynotificationsV1Csv:
      properties:
        dataRows:
          type: array
          items:
            $ref: '#/components/schemas/GoogleCloudAdvisorynotificationsV1CsvCsvRow'
          description: 'The list of data rows in a CSV file, as string arrays rather than as a single comma-separated string.'
        headers:
          description: The list of headers for data columns in a CSV file.
          type: array
          items:
            type: string
      description: 'A representation of a CSV file attachment, as a list of column headers and a list of data rows.'
      id: GoogleCloudAdvisorynotificationsV1Csv
      type: object
    GoogleCloudAdvisorynotificationsV1Subject:
      properties:
        text:
          $ref: '#/components/schemas/GoogleCloudAdvisorynotificationsV1Text'
          description: The text content.
      description: A subject line of a notification.
      id: GoogleCloudAdvisorynotificationsV1Subject
      type: object
    GoogleCloudAdvisorynotificationsV1Attachment:
      description: Attachment with specific information about the issue.
      id: GoogleCloudAdvisorynotificationsV1Attachment
      type: object
      properties:
        csv:
          $ref: '#/components/schemas/GoogleCloudAdvisorynotificationsV1Csv'
          description: A CSV file attachment. Max size is 10 MB.
        displayName:
          type: string
          description: The title of the attachment.
    GoogleCloudAdvisorynotificationsV1MessageBody:
      properties:
        text:
          description: The text content of the message body.
          $ref: '#/components/schemas/GoogleCloudAdvisorynotificationsV1Text'
      description: A message body containing text.
      type: object
      id: GoogleCloudAdvisorynotificationsV1MessageBody
    GoogleCloudAdvisorynotificationsV1Message:
      properties:
        localizationTime:
          description: Time when Message was localized
          format: google-datetime
          type: string
        attachments:
          type: array
          description: The attachments to download.
          items:
            $ref: '#/components/schemas/GoogleCloudAdvisorynotificationsV1Attachment'
        createTime:
          type: string
          format: google-datetime
          description: The Message creation timestamp.
        body:
          description: The message content.
          $ref: '#/components/schemas/GoogleCloudAdvisorynotificationsV1MessageBody'
      description: A message which contains notification details.
      type: object
      id: GoogleCloudAdvisorynotificationsV1Message
  parameters:
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    key:
      description: 'API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.'
      in: query
      name: key
      schema:
        type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    uploadType:
      description: 'Legacy upload protocol for media (e.g. "media", "multipart").'
      in: query
      name: uploadType
      schema:
        type: string
    quotaUser:
      description: 'Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.'
      in: query
      name: quotaUser
      schema:
        type: string
    upload_protocol:
      description: 'Upload protocol for media (e.g. "raw", "multipart").'
      in: query
      name: upload_protocol
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
  x-stackQL-resources:
    notifications:
      id: google.advisorynotifications.notifications
      name: notifications
      title: Notifications
      methods:
        list:
          operation:
            $ref: '#/paths/~1v1~1organizations~1{organizationsId}~1locations~1{locationsId}~1notifications/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.notifications
        _list:
          operation:
            $ref: '#/paths/~1v1~1organizations~1{organizationsId}~1locations~1{locationsId}~1notifications/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get:
          operation:
            $ref: '#/paths/~1v1~1organizations~1{organizationsId}~1locations~1{locationsId}~1notifications~1{notificationsId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/notifications/methods/list'
          - $ref: '#/components/x-stackQL-resources/notifications/methods/get'
        insert: []
        update: []
        delete: []
paths:
  '/v1/organizations/{organizationsId}/locations/{locationsId}/notifications':
    parameters: &ref_1
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/fields'
    get:
      description: Lists notifications under a given parent.
      operationId: advisorynotifications.organizations.locations.notifications.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleCloudAdvisorynotificationsV1ListNotificationsResponse'
      parameters:
        - in: path
          name: organizationsId
          required: true
          schema:
            type: string
        - in: path
          name: locationsId
          required: true
          schema:
            type: string
        - in: query
          name: view
          schema:
            type: string
        - in: query
          name: languageCode
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: pageToken
          schema:
            type: string
      x-stackQL-resource: notifications
      x-stackQL-method: list
      x-stackQL-verb: select
      x-stackQL-objectKey: $.notifications
  '/v1/organizations/{organizationsId}/locations/{locationsId}/notifications/{notificationsId}':
    parameters: *ref_1
    get:
      description: Gets a notification.
      operationId: advisorynotifications.organizations.locations.notifications.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleCloudAdvisorynotificationsV1Notification'
      parameters:
        - in: path
          name: organizationsId
          required: true
          schema:
            type: string
        - in: path
          name: locationsId
          required: true
          schema:
            type: string
        - in: path
          name: notificationsId
          required: true
          schema:
            type: string
        - in: query
          name: languageCode
          schema:
            type: string
      x-stackQL-resource: notifications
      x-stackQL-method: get
      x-stackQL-verb: select
