openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Agent Identity Credentials API
  description: agentidentitycredentials.googleapis.com API.
  version: v1
  x-discovery-doc-revision: '20260724'
  x-generated-date: '2026-07-31'
externalDocs:
  url: https://cloud.google.com/iam/docs/
servers:
  - url: https://agentidentitycredentials.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/cloud-platform: >-
              See, edit, configure, and delete your Google Cloud data and see
              the email address for your Google Account.
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
  schemas:
    GoogleCloudAgentidentitycredentialsV1_UriConsentRequired:
      id: GoogleCloudAgentidentitycredentialsV1_UriConsentRequired
      description: >-
        Indicates that the user must visit the provided URI to consent to
        delegate permission to the agent to act on their behalf. The caller can
        either poll the `RetrieveCredentials` method, or await the
        /ValidateUserId callback
      type: object
      properties:
        authorizationUri:
          description: >-
            Output only. The URL where the user should be redirected to grant
            consent. This will always be present.
          readOnly: true
          type: string
        consentNonce:
          description: >-
            Output only. A one-time, randomly generated value that validates the
            entire consent flow is handled by a single user, avoiding CSRF
            attacks. It must be submitted with the FinalizeCredentials request
            to complete the OAuth exchange. This will always be present.
            Implemented per https://www.rfc-editor.org/rfc/rfc6819#section-5.3.5
          readOnly: true
          type: string
        uid:
          description: Output only. The unique ID of the credentials retrieval operation.
          readOnly: true
          type: string
    GoogleCloudAgentidentitycredentialsV1_RetrieveCredentialsRequest:
      properties:
        scopes:
          description: Optional. The OAuth scopes required for this access.
          type: array
          items:
            type: string
        userId:
          description: Required. The identity of the end user.
          type: string
        continueUri:
          description: >-
            Optional. The URI to redirect the user to after consent is
            completed. This field is required for authproviders using the
            3-legged OAuth flow. For other authprovider types, this field is
            unused but not rejected.
          type: string
        forceRefreshToken:
          description: >-
            Optional. Input only. Set this field only if the previous token was
            expired or invalid. This value must be the full, previously returned
            token string. Will trigger a refresh of the access token with a
            stored refresh token, if possible, or a new consent flow.
          type: string
      id: GoogleCloudAgentidentitycredentialsV1_RetrieveCredentialsRequest
      description: Request message for RetrieveCredentials.
      type: object
    GoogleCloudAgentidentitycredentialsV1_RetrieveCredentialsResponse:
      properties:
        consentRejected:
          description: Message indicating consent was rejected.
          $ref: >-
            #/components/schemas/GoogleCloudAgentidentitycredentialsV1_ConsentRejected
        success:
          description: Message indicating credentials were successfully retrieved.
          $ref: '#/components/schemas/GoogleCloudAgentidentitycredentialsV1_Success'
        pending:
          description: Message indicating credential retrieval is pending.
          $ref: '#/components/schemas/GoogleCloudAgentidentitycredentialsV1_Pending'
        uriConsentRequired:
          description: Message indicating uri based consent is required.
          $ref: >-
            #/components/schemas/GoogleCloudAgentidentitycredentialsV1_UriConsentRequired
      id: GoogleCloudAgentidentitycredentialsV1_RetrieveCredentialsResponse
      description: >-
        Response message for RetrieveCredentials. Contains the access tokens and
        related artifacts.
      type: object
    GoogleCloudAgentidentitycredentialsV1_FinalizeCredentialsRequest:
      properties:
        userIdValidationState:
          description: Required. The encrypted state passed back from the consent flow.
          type: string
          format: byte
        consentNonce:
          description: >-
            Required. The same consent_nonce value that was provided during
            redirect in the UriConsentRequired metadata.
          type: string
        userId:
          description: Required. The identity of the end user.
          type: string
      id: GoogleCloudAgentidentitycredentialsV1_FinalizeCredentialsRequest
      description: Request message for FinalizeCredentials.
      type: object
    GoogleCloudAgentidentitycredentialsV1_FinalizeCredentialsResponse:
      id: GoogleCloudAgentidentitycredentialsV1_FinalizeCredentialsResponse
      description: Response message for FinalizeCredentials. Intentionally empty
      type: object
      properties: {}
    GoogleCloudAgentidentitycredentialsV1_ConsentRejected:
      id: GoogleCloudAgentidentitycredentialsV1_ConsentRejected
      description: >-
        Indicates the user has rejected the permission delegation or cancelled
        the request.
      type: object
      properties: {}
    GoogleCloudAgentidentitycredentialsV1_Success:
      properties:
        expireTime:
          description: >-
            The expiration time of the token. This does not guarantee that the
            token will be valid until this time, since the token could be
            revoked earlier. There could also be clock skew between the auth
            provider and the client so it may expire slightly earlier. If not
            set, the token might be permanent or it may be that the service does
            not (or cannot) know when it will expire.
          type: string
          format: google-datetime
        header:
          description: The HTTP header name where the token should be placed.
          type: string
        token:
          description: >-
            The retrieved access token or credential for the end user. On
            MCPTool call, for an invalid token OAuth spec says this should
            return 401 or 403, but MCPServers may implement this differently. If
            you get any flavor of `PERMISSION_DENIED`, retry your original
            request to RetrieveCredentials with force_refresh_token set to the
            expired/invalid token string, which will fetch a new token or
            initiate a new consent flow.
          type: string
        scopes:
          description: >-
            The scopes actually associated with the retrieved token. End users
            may have rejected some requested scopes, or the third-party
            authorization servers can return a different set of scopes than what
            was asked for. Callers should verify that all required scopes for
            their intended use are included in this list.
          type: array
          items:
            type: string
      id: GoogleCloudAgentidentitycredentialsV1_Success
      description: Message indicating successful retrieval of credentials.
      type: object
    GoogleCloudAgentidentitycredentialsV1_Pending:
      properties: {}
      id: GoogleCloudAgentidentitycredentialsV1_Pending
      description: >-
        Indicates that the credential retrieval is pending. The caller should
        retry the RetrieveCredentials request after some time.
      type: object
  parameters:
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    uploadType:
      description: Legacy upload protocol for media (e.g. "media", "multipart").
      in: query
      name: uploadType
      schema:
        type: string
    _.xgafv:
      description: V1 error format.
      in: query
      name: $.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    quotaUser:
      description: >-
        Available to use for quota purposes for server-side applications. Can be
        any arbitrary string assigned to a user, but should not exceed 40
        characters.
      in: query
      name: quotaUser
      schema:
        type: string
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    upload_protocol:
      description: Upload protocol for media (e.g. "raw", "multipart").
      in: query
      name: upload_protocol
      schema:
        type: string
    key:
      description: >-
        API key. Your API key identifies your project and provides you with API
        access, quota, and reports. Required unless you provide an OAuth 2.0
        token.
      in: query
      name: key
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
  x-stackQL-resources:
    credentials:
      id: google.agentidentitycredentials.credentials
      name: credentials
      title: Credentials
      methods:
        retrieve:
          operation:
            $ref: >-
              #/paths/~1v1~1projects~1{projectsId}~1locations~1{locationsId}~1authProviders~1{authProvidersId}~1credentials:retrieve/post
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        finalize:
          operation:
            $ref: >-
              #/paths/~1v1~1projects~1{projectsId}~1locations~1{locationsId}~1authProviders~1{authProvidersId}~1credentials:finalize/post
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        replace: []
        delete: []
paths:
  /v1/projects/{projectsId}/locations/{locationsId}/authProviders/{authProvidersId}/credentials:retrieve:
    parameters: &ref_1
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/oauth_token'
    post:
      description: >-
        Retrieves authorization credentials for an authprovider, or indicates
        what action needs to be taken to obtain credentials. If the `token`
        field in the response is populated, credential retrieval was successful.
        If one of the fields in the `status` oneof is populated, further action
        is required to obtain credentials, such as redirecting the user for
        consent. View comments on `RetrieveCredentialsResponse` for more
        information.
      operationId: >-
        agentidentitycredentials.projects.locations.authProviders.credentials.retrieve
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/GoogleCloudAgentidentitycredentialsV1_RetrieveCredentialsRequest
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/GoogleCloudAgentidentitycredentialsV1_RetrieveCredentialsResponse
      parameters:
        - in: path
          name: projectsId
          required: true
          schema:
            type: string
        - in: path
          name: locationsId
          required: true
          schema:
            type: string
        - in: path
          name: authProvidersId
          required: true
          schema:
            type: string
  /v1/projects/{projectsId}/locations/{locationsId}/authProviders/{authProvidersId}/credentials:finalize:
    parameters: *ref_1
    post:
      description: Finalizes the credentials after a successful consent flow.
      operationId: >-
        agentidentitycredentials.projects.locations.authProviders.credentials.finalize
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/GoogleCloudAgentidentitycredentialsV1_FinalizeCredentialsRequest
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/GoogleCloudAgentidentitycredentialsV1_FinalizeCredentialsResponse
      parameters:
        - in: path
          name: projectsId
          required: true
          schema:
            type: string
        - in: path
          name: locationsId
          required: true
          schema:
            type: string
        - in: path
          name: authProvidersId
          required: true
          schema:
            type: string
