openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Cloud Location Finder API
  description: ''
  version: v1
  x-discovery-doc-revision: '20251203'
  x-generated-date: '2025-12-10'
externalDocs:
  url: https://cloud.google.com/location-finder/docs
servers:
  - url: https://cloudlocationfinder.googleapis.com
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/cloud-platform: >-
              See, edit, configure, and delete your Google Cloud data and see
              the email address for your Google Account.
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
  schemas:
    CloudLocation:
      description: Represents resource cloud locations.
      properties:
        cloudLocationType:
          type: string
          enum:
            - CLOUD_LOCATION_TYPE_UNSPECIFIED
            - CLOUD_LOCATION_TYPE_REGION
            - CLOUD_LOCATION_TYPE_ZONE
            - CLOUD_LOCATION_TYPE_REGION_EXTENSION
            - CLOUD_LOCATION_TYPE_GDCC_ZONE
          description: Optional. The type of the cloud location.
          enumDescriptions:
            - Unspecified type.
            - CloudLocation type for region.
            - CloudLocation type for zone.
            - CloudLocation type for region extension.
            - CloudLocation type for Google Distributed Cloud Connected Zone.
        displayName:
          type: string
          description: >-
            Optional. The human-readable name of the cloud location. Example:
            us-east-2, us-east1.
        name:
          type: string
          description: >-
            Identifier. Name of the cloud location. Unique name of the cloud
            location including project and location using the form:
            `projects/{project_id}/locations/{location}/cloudLocations/{cloud_location}`
        containingCloudLocation:
          description: >-
            Output only. The containing cloud location in the strict nesting
            hierarchy. For example, the containing cloud location of a zone is a
            region.
          type: string
          readOnly: true
        cloudProvider:
          enumDescriptions:
            - Unspecified type.
            - Cloud provider type for Google Cloud.
            - Cloud provider type for AWS.
            - Cloud provider type for Azure.
            - Cloud provider type for OCI.
          type: string
          description: >-
            Optional. The provider of the cloud location. Values can be Google
            Cloud or third-party providers, including AWS, Azure, or Oracle
            Cloud Infrastructure.
          enum:
            - CLOUD_PROVIDER_UNSPECIFIED
            - CLOUD_PROVIDER_GCP
            - CLOUD_PROVIDER_AWS
            - CLOUD_PROVIDER_AZURE
            - CLOUD_PROVIDER_OCI
        territoryCode:
          description: >-
            Optional. The two-letter ISO 3166-1 alpha-2 code of the cloud
            location. Examples: US, JP, KR.
          type: string
        carbonFreeEnergyPercentage:
          format: float
          type: number
          description: >-
            Optional. The carbon free energy percentage of the cloud location.
            This represents the average percentage of time customers'
            application will be running on carbon-free energy. See
            https://cloud.google.com/sustainability/region-carbon for more
            details. There is a difference between default value 0 and unset
            value. 0 means the carbon free energy percentage is 0%, while unset
            value means the carbon footprint data is not available.
      type: object
      id: CloudLocation
    Location:
      id: Location
      type: object
      description: A resource that represents a Google Cloud location.
      properties:
        displayName:
          description: >-
            The friendly name for this location, typically a nearby city name.
            For example, "Tokyo".
          type: string
        metadata:
          additionalProperties:
            type: any
            description: Properties of the object. Contains field @type with type URL.
          description: >-
            Service-specific metadata. For example the available capacity at the
            given location.
          type: object
        labels:
          additionalProperties:
            type: string
          description: >-
            Cross-service attributes for the location. For example
            {"cloud.googleapis.com/region": "us-east1"}
          type: object
        name:
          type: string
          description: >-
            Resource name for the location, which may vary between
            implementations. For example:
            `"projects/example-project/locations/us-east1"`
        locationId:
          description: 'The canonical id for this location. For example: `"us-east1"`.'
          type: string
    ListCloudLocationsResponse:
      id: ListCloudLocationsResponse
      description: Message for response to listing cloud locations.
      type: object
      properties:
        cloudLocations:
          type: array
          readOnly: true
          description: Output only. List of cloud locations.
          items:
            $ref: '#/components/schemas/CloudLocation'
        nextPageToken:
          description: >-
            Output only. The continuation token, used to page through large
            result sets. Provide this value in a subsequent request as
            page_token in subsequent requests to retrieve the next page. If this
            field is not present, there are no subsequent results.
          readOnly: true
          type: string
    SearchCloudLocationsResponse:
      description: Message for response to searching cloud locations.
      properties:
        nextPageToken:
          description: >-
            Output only. The continuation token, used to page through large
            result sets. Provide this value in a subsequent request as
            page_token in subsequent requests to retrieve the next page. If this
            field is not present, there are no subsequent results.
          readOnly: true
          type: string
        cloudLocations:
          type: array
          readOnly: true
          description: Output only. List of cloud locations.
          items:
            $ref: '#/components/schemas/CloudLocation'
      id: SearchCloudLocationsResponse
      type: object
    ListLocationsResponse:
      type: object
      id: ListLocationsResponse
      properties:
        nextPageToken:
          description: The standard List next-page token.
          type: string
        locations:
          description: >-
            A list of locations that matches the specified filter in the
            request.
          type: array
          items:
            $ref: '#/components/schemas/Location'
      description: The response message for Locations.ListLocations.
  parameters:
    key:
      description: >-
        API key. Your API key identifies your project and provides you with API
        access, quota, and reports. Required unless you provide an OAuth 2.0
        token.
      in: query
      name: key
      schema:
        type: string
    upload_protocol:
      description: Upload protocol for media (e.g. "raw", "multipart").
      in: query
      name: upload_protocol
      schema:
        type: string
    uploadType:
      description: Legacy upload protocol for media (e.g. "media", "multipart").
      in: query
      name: uploadType
      schema:
        type: string
    _.xgafv:
      description: V1 error format.
      in: query
      name: $.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    quotaUser:
      description: >-
        Available to use for quota purposes for server-side applications. Can be
        any arbitrary string assigned to a user, but should not exceed 40
        characters.
      in: query
      name: quotaUser
      schema:
        type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
  x-stackQL-resources:
    cloud_locations:
      id: google.cloudlocationfinder.cloud_locations
      name: cloud_locations
      title: Cloud_locations
      methods:
        list:
          operation:
            $ref: >-
              #/paths/~1v1~1projects~1{projectsId}~1locations~1{locationsId}~1cloudLocations/get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.cloudLocations
        get:
          operation:
            $ref: >-
              #/paths/~1v1~1projects~1{projectsId}~1locations~1{locationsId}~1cloudLocations~1{cloudLocationsId}/get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        search:
          operation:
            $ref: >-
              #/paths/~1v1~1projects~1{projectsId}~1locations~1{locationsId}~1cloudLocations:search/get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/cloud_locations/methods/get'
          - $ref: '#/components/x-stackQL-resources/cloud_locations/methods/list'
        insert: []
        update: []
        replace: []
        delete: []
    locations:
      id: google.cloudlocationfinder.locations
      name: locations
      title: Locations
      methods:
        list:
          operation:
            $ref: '#/paths/~1v1~1projects~1{projectsId}~1locations/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.locations
        get:
          operation:
            $ref: '#/paths/~1v1~1projects~1{projectsId}~1locations~1{locationsId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/locations/methods/get'
          - $ref: '#/components/x-stackQL-resources/locations/methods/list'
        insert: []
        update: []
        replace: []
        delete: []
paths:
  /v1/projects/{projectsId}/locations/{locationsId}/cloudLocations:
    parameters: &ref_1
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/callback'
    get:
      description: Lists cloud locations under a given project and location.
      operationId: cloudlocationfinder.projects.locations.cloudLocations.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCloudLocationsResponse'
      parameters:
        - in: path
          name: projectsId
          required: true
          schema:
            type: string
        - in: path
          name: locationsId
          required: true
          schema:
            type: string
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
            format: int32
        - in: query
          name: pageToken
          schema:
            type: string
  /v1/projects/{projectsId}/locations/{locationsId}/cloudLocations/{cloudLocationsId}:
    parameters: *ref_1
    get:
      description: Retrieves a resource containing information about a cloud location.
      operationId: cloudlocationfinder.projects.locations.cloudLocations.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudLocation'
      parameters:
        - in: path
          name: projectsId
          required: true
          schema:
            type: string
        - in: path
          name: locationsId
          required: true
          schema:
            type: string
        - in: path
          name: cloudLocationsId
          required: true
          schema:
            type: string
  /v1/projects/{projectsId}/locations/{locationsId}/cloudLocations:search:
    parameters: *ref_1
    get:
      description: Searches for cloud locations from a given source location.
      operationId: cloudlocationfinder.projects.locations.cloudLocations.search
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchCloudLocationsResponse'
      parameters:
        - in: path
          name: projectsId
          required: true
          schema:
            type: string
        - in: path
          name: locationsId
          required: true
          schema:
            type: string
        - in: query
          name: pageToken
          schema:
            type: string
        - in: query
          name: sourceCloudLocation
          schema:
            type: string
        - in: query
          name: query
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
            format: int32
  /v1/projects/{projectsId}/locations:
    parameters: *ref_1
    get:
      description: Lists information about the supported locations for this service.
      operationId: cloudlocationfinder.projects.locations.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListLocationsResponse'
      parameters:
        - in: path
          name: projectsId
          required: true
          schema:
            type: string
        - in: query
          name: extraLocationTypes
          schema:
            type: string
        - in: query
          name: pageToken
          schema:
            type: string
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
            format: int32
  /v1/projects/{projectsId}/locations/{locationsId}:
    parameters: *ref_1
    get:
      description: Gets information about a location.
      operationId: cloudlocationfinder.projects.locations.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
      parameters:
        - in: path
          name: projectsId
          required: true
          schema:
            type: string
        - in: path
          name: locationsId
          required: true
          schema:
            type: string
