openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Firebase Cloud Messaging Data API
  description: Provides additional information about Firebase Cloud Messaging (FCM) message sends and deliveries.
  version: v1beta1
  x-discovery-doc-revision: '20230104'
  x-generated-date: '2023-01-06'
externalDocs:
  url: https://firebase.google.com/docs/cloud-messaging
servers:
  - url: https://fcmdata.googleapis.com
components:
  schemas:
    GoogleFirebaseFcmDataV1beta1MessageInsightPercents:
      id: GoogleFirebaseFcmDataV1beta1MessageInsightPercents
      type: object
      properties:
        priorityLowered:
          format: float
          type: number
          description: The percentage of accepted messages that had their priority lowered from high to normal. See [documentation for setting message priority](https://firebase.google.com/docs/cloud-messaging/android/message-priority).
      description: Additional information about message delivery. All percentages are calculated with countMessagesAccepted as the denominator.
    GoogleFirebaseFcmDataV1beta1AndroidDeliveryData:
      description: Message delivery data for a given date, app, and analytics label combination.
      properties:
        appId:
          description: The app ID to which the messages were sent.
          type: string
        date:
          description: The date represented by this entry.
          $ref: '#/components/schemas/GoogleTypeDate'
        data:
          $ref: '#/components/schemas/GoogleFirebaseFcmDataV1beta1Data'
          description: The data for the specified appId, date, and analyticsLabel.
        analyticsLabel:
          description: The analytics label associated with the messages sent. All messages sent without an analytics label will be grouped together in a single entry.
          type: string
      id: GoogleFirebaseFcmDataV1beta1AndroidDeliveryData
      type: object
    GoogleFirebaseFcmDataV1beta1ListAndroidDeliveryDataResponse:
      type: object
      properties:
        nextPageToken:
          description: A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.
          type: string
        androidDeliveryData:
          description: The delivery data for the provided app. There will be one entry per combination of app, date, and analytics label.
          items:
            $ref: '#/components/schemas/GoogleFirebaseFcmDataV1beta1AndroidDeliveryData'
          type: array
      description: Response message for ListAndroidDeliveryData.
      id: GoogleFirebaseFcmDataV1beta1ListAndroidDeliveryDataResponse
    GoogleFirebaseFcmDataV1beta1Data:
      properties:
        messageInsightPercents:
          description: Additional general insights about message delivery.
          $ref: '#/components/schemas/GoogleFirebaseFcmDataV1beta1MessageInsightPercents'
        deliveryPerformancePercents:
          $ref: '#/components/schemas/GoogleFirebaseFcmDataV1beta1DeliveryPerformancePercents'
          description: Additional information about delivery performance for messages that were successfully delivered.
        messageOutcomePercents:
          $ref: '#/components/schemas/GoogleFirebaseFcmDataV1beta1MessageOutcomePercents'
          description: Mutually exclusive breakdown of message delivery outcomes.
        countMessagesAccepted:
          type: string
          format: int64
          description: Count of messages accepted by FCM intended to Android devices. The targeted device must have opted in to the collection of usage and diagnostic information.
      description: Data detailing messaging delivery
      id: GoogleFirebaseFcmDataV1beta1Data
      type: object
    GoogleTypeDate:
      description: 'Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following: * A full date, with non-zero year, month, and day values. * A month and day, with a zero year (for example, an anniversary). * A year on its own, with a zero month and a zero day. * A year and month, with a zero day (for example, a credit card expiration date). Related types: * google.type.TimeOfDay * google.type.DateTime * google.protobuf.Timestamp'
      type: object
      id: GoogleTypeDate
      properties:
        day:
          format: int32
          description: Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.
          type: integer
        year:
          format: int32
          description: Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.
          type: integer
        month:
          type: integer
          description: Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.
          format: int32
    GoogleFirebaseFcmDataV1beta1DeliveryPerformancePercents:
      id: GoogleFirebaseFcmDataV1beta1DeliveryPerformancePercents
      description: Overview of delivery performance for messages that were successfully delivered. All percentages are calculated with countMessagesAccepted as the denominator. These categories are not mutually exclusive; a message can be delayed for multiple reasons.
      type: object
      properties:
        delayedDeviceDoze:
          type: number
          description: The percentage of accepted messages that were delayed because the device was in doze mode. Only [normal priority messages](https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message) should be delayed due to doze mode.
          format: float
        delayedDeviceOffline:
          description: The percentage of accepted messages that were delayed because the target device was not connected at the time of sending. These messages were eventually delivered when the device reconnected.
          format: float
          type: number
        deliveredNoDelay:
          description: The percentage of accepted messages that were delivered to the device without delay from the FCM system.
          type: number
          format: float
        delayedUserStopped:
          format: float
          description: The percentage of accepted messages that were delayed because the intended device user-profile was [stopped](https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages) on the target device at the time of the send. The messages were eventually delivered when the user-profile was started again.
          type: number
        delayedMessageThrottled:
          description: The percentage of accepted messages that were delayed due to message throttling, such as [collapsible message throttling](https://firebase.google.com/docs/cloud-messaging/concept-options#collapsible_throttling) or [maximum message rate throttling](https://firebase.google.com/docs/cloud-messaging/concept-options#device_throttling).
          format: float
          type: number
    GoogleFirebaseFcmDataV1beta1MessageOutcomePercents:
      description: Percentage breakdown of message delivery outcomes. These categories are mutually exclusive. All percentages are calculated with countMessagesAccepted as the denominator. These categories may not account for all message outcomes.
      type: object
      properties:
        droppedTooManyPendingMessages:
          format: float
          description: The percentage of accepted messages that were dropped due to [too many undelivered non-collapsible messages](https://firebase.google.com/docs/cloud-messaging/concept-options#collapsible_and_non-collapsible_messages). Specifically, each app instance can only have 100 pending messages stored on our servers for a device which is disconnected. When that device reconnects, those messages are delivered. When there are more than the maximum pending messages, we call [OnDeletedMessages()](https://firebase.google.com/docs/cloud-messaging/android/receive#override-ondeletedmessages) in our SDK instead of delivering the messages.
          type: number
        droppedDeviceInactive:
          format: float
          type: number
          description: The percentage of accepted messages that were dropped because the target device is inactive. FCM will drop messages if the target device is deemed inactive by our servers. If a device does reconnect, we call [OnDeletedMessages()](https://firebase.google.com/docs/cloud-messaging/android/receive#override-ondeletedmessages) in our SDK instead of delivering the messages.
        delivered:
          format: float
          description: The percentage of all accepted messages that were successfully delivered to the device.
          type: number
        droppedAppForceStopped:
          type: number
          description: The percentage of accepted messages that were dropped because the application was force stopped on the device at the time of delivery and retries were unsuccessful.
          format: float
        pending:
          description: The percentage of messages accepted on this day that were not dropped and not delivered, due to the device being disconnected (as of the end of the America/Los_Angeles day when the message was sent to FCM). A portion of these messages will be delivered the next day when the device connects but others may be destined to devices that ultimately never reconnect.
          type: number
          format: float
      id: GoogleFirebaseFcmDataV1beta1MessageOutcomePercents
  parameters:
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    key:
      description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      in: query
      name: key
      schema:
        type: string
    uploadType:
      description: Legacy upload protocol for media (e.g. "media", "multipart").
      in: query
      name: uploadType
      schema:
        type: string
    upload_protocol:
      description: Upload protocol for media (e.g. "raw", "multipart").
      in: query
      name: upload_protocol
      schema:
        type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    quotaUser:
      description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/cloud-platform: See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account.
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
  x-stackQL-resources:
    delivery_data:
      id: google.fcmdata.delivery_data
      name: delivery_data
      title: Delivery_data
      methods:
        projects_androidApps_deliveryData_list:
          operation:
            $ref: '#/paths/~1v1beta1~1projects~1{projectsId}~1androidApps~1{androidAppsId}~1deliveryData/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/delivery_data/methods/projects_androidApps_deliveryData_list'
        insert: []
        update: []
        delete: []
paths:
  /v1beta1/projects/{projectsId}/androidApps/{androidAppsId}/deliveryData:
    parameters:
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/fields'
    get:
      description: List aggregate delivery data for the given Android application.
      operationId: fcmdata.projects.androidApps.deliveryData.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleFirebaseFcmDataV1beta1ListAndroidDeliveryDataResponse'
      parameters:
        - in: path
          name: projectsId
          required: true
          schema:
            type: string
        - in: path
          name: androidAppsId
          required: true
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: pageToken
          schema:
            type: string
      x-stackQL-resource: delivery_data
      x-stackQL-verb: select
