openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Idea Hub API
  description: This is an invitation-only API.
  version: v1beta
  x-discovery-doc-revision: '20230105'
  x-generated-date: '2023-01-06'
externalDocs:
  url: https://console.cloud.google.com/apis/library/ideahub.googleapis.com
servers:
  - url: https://ideahub.googleapis.com
components:
  schemas:
    GoogleSearchIdeahubV1betaIdea:
      type: object
      id: GoogleSearchIdeahubV1betaIdea
      properties:
        name:
          description: 'Unique identifier for the idea. Format: ideas/{ideaId}'
          type: string
        topics:
          description: The Topics that match the idea.
          items:
            $ref: '#/components/schemas/GoogleSearchIdeahubV1betaTopic'
          type: array
        text:
          type: string
          description: The idea’s text.
      description: A single Idea that we want to show the end user.
    GoogleSearchIdeahubV1betaListAvailableLocalesResponse:
      id: GoogleSearchIdeahubV1betaListAvailableLocalesResponse
      properties:
        nextPageToken:
          description: A token that can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.
          type: string
        availableLocales:
          description: Locales for which ideas are available for the given Creator.
          type: array
          items:
            $ref: '#/components/schemas/GoogleSearchIdeahubV1betaAvailableLocale'
      type: object
      description: Response for whether ideas are available for a given web property on a platform, for the currently logged-in user.
    GoogleSearchIdeahubV1betaTopicState:
      id: GoogleSearchIdeahubV1betaTopicState
      type: object
      description: Represents topic state specific to a web property.
      properties:
        dismissed:
          type: boolean
          description: Whether the topic is dismissed.
        name:
          description: 'Unique identifier for the topic state. Format: platforms/{platform}/properties/{property}/topicStates/{topic_state}'
          type: string
        saved:
          description: Whether the topic is saved.
          type: boolean
    GoogleSearchIdeahubV1betaIdeaState:
      type: object
      description: Represents idea state specific to a web property.
      id: GoogleSearchIdeahubV1betaIdeaState
      properties:
        dismissed:
          type: boolean
          description: Whether the idea is dismissed.
        saved:
          description: Whether the idea is saved.
          type: boolean
        name:
          type: string
          description: 'Unique identifier for the idea state. Format: platforms/{platform}/properties/{property}/ideaStates/{idea_state}'
    GoogleSearchIdeahubV1betaListIdeasResponse:
      type: object
      properties:
        nextPageToken:
          description: Used to fetch the next page in a subsequent request.
          type: string
        ideas:
          description: Results for the ListIdeasRequest.
          type: array
          items:
            $ref: '#/components/schemas/GoogleSearchIdeahubV1betaIdea'
      id: GoogleSearchIdeahubV1betaListIdeasResponse
    GoogleSearchIdeahubV1betaIdeaActivity:
      description: An idea activity entry.
      id: GoogleSearchIdeahubV1betaIdeaActivity
      type: object
      properties:
        topics:
          items:
            type: string
          description: The Topic IDs for this entry. If empty, ideas should be set.
          type: array
        name:
          type: string
          description: 'Unique identifier for the idea activity. The name is ignored when creating an idea activity. Format: platforms/{platform}/properties/{property}/ideaActivities/{idea_activity}'
        type:
          type: string
          description: The type of activity performed.
          enum:
            - TYPE_UNSPECIFIED
            - POST_DRAFTED
            - POST_PUBLISHED
            - POST_DELETED
            - POST_UNPUBLISHED
          enumDescriptions:
            - An unspecified, unknown type of idea activity.
            - An idea activity type indicating a post has been drafted.
            - An idea activity type indicating a post has been published.
            - An idea activity type indicating a post has been deleted.
            - An idea activity type indicating a post has been unpublished.
        uri:
          type: string
          description: The uri the activity relates to.
        ideas:
          type: array
          description: The Idea IDs for this entry. If empty, topics should be set.
          items:
            type: string
    GoogleSearchIdeahubV1betaTopic:
      properties:
        mid:
          type: string
          description: The mID of the topic.
        displayName:
          description: String displayed to the creator indicating the name of the Topic.
          type: string
        name:
          description: 'Unique identifier for the topic. Format: topics/{topic}'
          type: string
      id: GoogleSearchIdeahubV1betaTopic
      description: Represents a Topic umbrella for a list of questions that a Creator may want to respond to.
      type: object
    GoogleSearchIdeahubV1betaAvailableLocale:
      type: object
      description: Represents locales that are available for a web property.
      properties:
        name:
          type: string
          description: 'A string in BCP 47 format, prefixed with the platform and property name, and "locales/". Format: platforms/{platform}/properties/{property}/locales/{locale}'
        locale:
          type: string
          description: A string in BCP 47 format, without a resource prefix.
      id: GoogleSearchIdeahubV1betaAvailableLocale
  parameters:
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    upload_protocol:
      description: Upload protocol for media (e.g. "raw", "multipart").
      in: query
      name: upload_protocol
      schema:
        type: string
    quotaUser:
      description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
    uploadType:
      description: Legacy upload protocol for media (e.g. "media", "multipart").
      in: query
      name: uploadType
      schema:
        type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    key:
      description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      in: query
      name: key
      schema:
        type: string
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/cloud-platform: See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account.
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
  x-stackQL-resources:
    locales:
      id: google.ideahub.locales
      name: locales
      title: Locales
      methods:
        platforms_properties_locales_list:
          operation:
            $ref: '#/paths/~1v1beta~1platforms~1{platformsId}~1properties~1{propertiesId}~1locales/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/locales/methods/platforms_properties_locales_list'
        insert: []
        update: []
        delete: []
    idea_states:
      id: google.ideahub.idea_states
      name: idea_states
      title: Idea_states
      methods:
        platforms_properties_ideaStates_patch:
          operation:
            $ref: '#/paths/~1v1beta~1platforms~1{platformsId}~1properties~1{propertiesId}~1ideaStates~1{ideaStatesId}/patch'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    idea_activities:
      id: google.ideahub.idea_activities
      name: idea_activities
      title: Idea_activities
      methods:
        platforms_properties_ideaActivities_create:
          operation:
            $ref: '#/paths/~1v1beta~1platforms~1{platformsId}~1properties~1{propertiesId}~1ideaActivities/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert:
          - $ref: '#/components/x-stackQL-resources/idea_activities/methods/platforms_properties_ideaActivities_create'
        update: []
        delete: []
    ideas:
      id: google.ideahub.ideas
      name: ideas
      title: Ideas
      methods:
        platforms_properties_ideas_list:
          operation:
            $ref: '#/paths/~1v1beta~1platforms~1{platformsId}~1properties~1{propertiesId}~1ideas/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/ideas/methods/platforms_properties_ideas_list'
        insert: []
        update: []
        delete: []
    topic_states:
      id: google.ideahub.topic_states
      name: topic_states
      title: Topic_states
      methods:
        platforms_properties_topicStates_patch:
          operation:
            $ref: '#/paths/~1v1beta~1platforms~1{platformsId}~1properties~1{propertiesId}~1topicStates~1{topicStatesId}/patch'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /v1beta/platforms/{platformsId}/properties/{propertiesId}/locales:
    parameters: &ref_1
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/prettyPrint'
    get:
      description: Returns which locales ideas are available in for a given Creator.
      operationId: ideahub.platforms.properties.locales.list
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleSearchIdeahubV1betaListAvailableLocalesResponse'
      parameters:
        - in: path
          name: platformsId
          required: true
          schema:
            type: string
        - in: path
          name: propertiesId
          required: true
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: pageToken
          schema:
            type: string
      x-stackQL-resource: locales
      x-stackQL-verb: select
  /v1beta/platforms/{platformsId}/properties/{propertiesId}/ideaStates/{ideaStatesId}:
    parameters: *ref_1
    patch:
      description: Update an idea state resource.
      operationId: ideahub.platforms.properties.ideaStates.patch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoogleSearchIdeahubV1betaIdeaState'
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleSearchIdeahubV1betaIdeaState'
      parameters:
        - in: path
          name: platformsId
          required: true
          schema:
            type: string
        - in: path
          name: propertiesId
          required: true
          schema:
            type: string
        - in: path
          name: ideaStatesId
          required: true
          schema:
            type: string
        - in: query
          name: updateMask
          schema:
            type: string
      x-stackQL-resource: idea_states
      x-stackQL-verb: exec
  /v1beta/platforms/{platformsId}/properties/{propertiesId}/ideaActivities:
    parameters: *ref_1
    post:
      description: Creates an idea activity entry.
      operationId: ideahub.platforms.properties.ideaActivities.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoogleSearchIdeahubV1betaIdeaActivity'
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleSearchIdeahubV1betaIdeaActivity'
      parameters:
        - in: path
          name: platformsId
          required: true
          schema:
            type: string
        - in: path
          name: propertiesId
          required: true
          schema:
            type: string
      x-stackQL-resource: idea_activities
      x-stackQL-verb: insert
  /v1beta/platforms/{platformsId}/properties/{propertiesId}/ideas:
    parameters: *ref_1
    get:
      description: List ideas for a given Creator and filter and sort options.
      operationId: ideahub.platforms.properties.ideas.list
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleSearchIdeahubV1betaListIdeasResponse'
      parameters:
        - in: path
          name: platformsId
          required: true
          schema:
            type: string
        - in: path
          name: propertiesId
          required: true
          schema:
            type: string
        - in: query
          name: orderBy
          schema:
            type: string
        - in: query
          name: pageToken
          schema:
            type: string
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
      x-stackQL-resource: ideas
      x-stackQL-verb: select
  /v1beta/platforms/{platformsId}/properties/{propertiesId}/topicStates/{topicStatesId}:
    parameters: *ref_1
    patch:
      description: Update a topic state resource.
      operationId: ideahub.platforms.properties.topicStates.patch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoogleSearchIdeahubV1betaTopicState'
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleSearchIdeahubV1betaTopicState'
      parameters:
        - in: path
          name: platformsId
          required: true
          schema:
            type: string
        - in: path
          name: propertiesId
          required: true
          schema:
            type: string
        - in: path
          name: topicStatesId
          required: true
          schema:
            type: string
        - in: query
          name: updateMask
          schema:
            type: string
      x-stackQL-resource: topic_states
      x-stackQL-verb: exec
