openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: 'https://github.com/stackql/google-discovery-to-openapi'
    email: info@stackql.io
  title: Policy Analyzer API
  description: ''
  version: v1
  x-discovery-doc-revision: '20230820'
  x-generated-date: '2023-09-01'
externalDocs:
  url: 'https://www.google.com'
servers:
  - url: 'https://policyanalyzer.googleapis.com'
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
          scopes: &ref_0
            'https://www.googleapis.com/auth/cloud-platform': 'See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account.'
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
          tokenUrl: 'https://accounts.google.com/o/oauth2/token'
          scopes: *ref_0
  schemas:
    GoogleCloudPolicyanalyzerV1ObservationPeriod:
      description: Represents data observation period.
      type: object
      properties:
        endTime:
          type: string
          description: 'The observation end time. The time in this timestamp is always `07:00:00Z`.'
          format: google-datetime
        startTime:
          format: google-datetime
          description: 'The observation start time. The time in this timestamp is always `07:00:00Z`.'
          type: string
      id: GoogleCloudPolicyanalyzerV1ObservationPeriod
    GoogleCloudPolicyanalyzerV1QueryActivityResponse:
      properties:
        activities:
          items:
            $ref: '#/components/schemas/GoogleCloudPolicyanalyzerV1Activity'
          description: The set of activities that match the filter included in the request.
          type: array
        nextPageToken:
          type: string
          description: 'If there might be more results than those appearing in this response, then `nextPageToken` is included. To get the next set of results, call this method again using the value of `nextPageToken` as `pageToken`.'
      id: GoogleCloudPolicyanalyzerV1QueryActivityResponse
      type: object
      description: Response to the `QueryActivity` method.
    GoogleCloudPolicyanalyzerV1Activity:
      id: GoogleCloudPolicyanalyzerV1Activity
      properties:
        fullResourceName:
          description: 'The full resource name that identifies the resource. For examples of full resource names for Google Cloud services, see https://cloud.google.com/iam/help/troubleshooter/full-resource-names.'
          type: string
        observationPeriod:
          description: The data observation period to build the activity.
          $ref: '#/components/schemas/GoogleCloudPolicyanalyzerV1ObservationPeriod'
        activityType:
          type: string
          description: The type of the activity.
        activity:
          description: A struct of custom fields to explain the activity.
          additionalProperties:
            type: any
            description: Properties of the object.
          type: object
      type: object
  parameters:
    upload_protocol:
      description: 'Upload protocol for media (e.g. "raw", "multipart").'
      in: query
      name: upload_protocol
      schema:
        type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    quotaUser:
      description: 'Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.'
      in: query
      name: quotaUser
      schema:
        type: string
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    uploadType:
      description: 'Legacy upload protocol for media (e.g. "media", "multipart").'
      in: query
      name: uploadType
      schema:
        type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    key:
      description: 'API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.'
      in: query
      name: key
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
  x-stackQL-resources:
    activities:
      id: google.policyanalyzer.activities
      name: activities
      title: Activities
      methods:
        query:
          operation:
            $ref: '#/paths/~1v1~1projects~1{projectsId}~1locations~1{locationsId}~1activityTypes~1{activityTypesId}~1activities:query/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  '/v1/projects/{projectsId}/locations/{locationsId}/activityTypes/{activityTypesId}/activities:query':
    parameters:
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/callback'
    get:
      description: Queries policy activities on Google Cloud resources.
      operationId: policyanalyzer.projects.locations.activityTypes.activities.query
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleCloudPolicyanalyzerV1QueryActivityResponse'
      parameters:
        - in: path
          name: projectsId
          required: true
          schema:
            type: string
        - in: path
          name: locationsId
          required: true
          schema:
            type: string
        - in: path
          name: activityTypesId
          required: true
          schema:
            type: string
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: pageToken
          schema:
            type: string
      x-stackQL-resource: activities
      x-stackQL-method: query
      x-stackQL-verb: exec
