openapi: 3.0.0
info:
  title: dev_servers API
  description: netlify dev_servers API
  version: 2.57.0
paths:
  /sites/{site_id}/dev_servers:
    get:
      operationId: listSiteDevServers
      tags:
        - devServer
      parameters:
        - name: page
          required: false
          in: query
          schema:
            type: integer
            format: int32
        - name: per_page
          required: false
          in: query
          schema:
            type: integer
            format: int32
        - name: site_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    site_id:
                      type: string
                    branch:
                      type: string
                    url:
                      type: string
                    state:
                      type: string
                    created_at:
                      type: string
                      format: dateTime
                    updated_at:
                      type: string
                      format: dateTime
                    starting_at:
                      type: string
                      format: dateTime
                    error_at:
                      type: string
                      format: dateTime
                    live_at:
                      type: string
                      format: dateTime
                    done_at:
                      type: string
                      format: dateTime
                    title:
                      type: string
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
    post:
      operationId: createSiteDevServer
      tags:
        - devServer
      parameters:
        - name: branch
          in: query
          schema:
            type: string
        - name: site_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    site_id:
                      type: string
                    branch:
                      type: string
                    url:
                      type: string
                    state:
                      type: string
                    created_at:
                      type: string
                      format: dateTime
                    updated_at:
                      type: string
                      format: dateTime
                    starting_at:
                      type: string
                      format: dateTime
                    error_at:
                      type: string
                      format: dateTime
                    live_at:
                      type: string
                      format: dateTime
                    done_at:
                      type: string
                      format: dateTime
                    title:
                      type: string
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
    delete:
      operationId: deleteSiteDevServers
      tags:
        - devServer
      parameters:
        - name: branch
          in: query
          schema:
            type: string
        - name: site_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '202':
          description: OK
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
  /sites/{site_id}/dev_servers/{dev_server_id}:
    get:
      operationId: getSiteDevServer
      tags:
        - devServer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  site_id:
                    type: string
                  branch:
                    type: string
                  url:
                    type: string
                  state:
                    type: string
                  created_at:
                    type: string
                    format: dateTime
                  updated_at:
                    type: string
                    format: dateTime
                  starting_at:
                    type: string
                    format: dateTime
                  error_at:
                    type: string
                    format: dateTime
                  live_at:
                    type: string
                    format: dateTime
                  done_at:
                    type: string
                    format: dateTime
                  title:
                    type: string
      parameters:
        - name: site_id
          in: path
          required: true
          schema:
            type: string
        - name: dev_server_id
          in: path
          required: true
          schema:
            type: string
  /sites/{site_id}/dev_servers/{dev_server_id}/activity:
    post:
      x-internal: true
      operationId: markDevServerActivity
      tags:
        - devServer
      responses:
        '200':
          description: OK
      parameters:
        - name: site_id
          in: path
          required: true
          schema:
            type: string
        - name: dev_server_id
          in: path
          required: true
          schema:
            type: string
  /sites/{site_id}/dev_servers/{dev_server_id}/state:
    post:
      operationId: updateDevServerState
      tags:
        - devServer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - state
              properties:
                state:
                  type: string
                  enum:
                    - starting
                    - live
                    - error
                    - done
                task_id:
                  type: string
                error:
                  type: string
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  site_id:
                    type: string
                  branch:
                    type: string
                  url:
                    type: string
                  state:
                    type: string
                  created_at:
                    type: string
                    format: dateTime
                  updated_at:
                    type: string
                    format: dateTime
                  starting_at:
                    type: string
                    format: dateTime
                  error_at:
                    type: string
                    format: dateTime
                  live_at:
                    type: string
                    format: dateTime
                  done_at:
                    type: string
                    format: dateTime
                  title:
                    type: string
        '409':
          description: Conflict
      parameters:
        - name: site_id
          in: path
          required: true
          schema:
            type: string
        - name: dev_server_id
          in: path
          required: true
          schema:
            type: string
  /sites/{site_id}/dev_server_hooks:
    get:
      operationId: listSiteDevServerHooks
      tags:
        - devServerHook
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    branch:
                      type: string
                    url:
                      type: string
                    site_id:
                      type: string
                    created_at:
                      type: string
                      format: dateTime
                    type:
                      type: string
                      enum:
                        - new_dev_server
                        - content_refresh
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
      parameters:
        - name: site_id
          in: path
          required: true
          schema:
            type: string
    post:
      operationId: createSiteDevServerHook
      tags:
        - devServerHook
      requestBody:
        $ref: '#/components/requestBodies/createSiteDevServerHookDevserverhook'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  branch:
                    type: string
                  url:
                    type: string
                  site_id:
                    type: string
                  created_at:
                    type: string
                    format: dateTime
                  type:
                    type: string
                    enum:
                      - new_dev_server
                      - content_refresh
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
      parameters:
        - name: site_id
          in: path
          required: true
          schema:
            type: string
  /sites/{site_id}/dev_server_hooks/{id}:
    get:
      operationId: getSiteDevServerHook
      tags:
        - devServerHook
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  branch:
                    type: string
                  url:
                    type: string
                  site_id:
                    type: string
                  created_at:
                    type: string
                    format: dateTime
                  type:
                    type: string
                    enum:
                      - new_dev_server
                      - content_refresh
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
      parameters:
        - name: site_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
    put:
      operationId: updateSiteDevServerHook
      tags:
        - devServerHook
      requestBody:
        $ref: '#/components/requestBodies/createSiteDevServerHookDevserverhook'
      responses:
        '204':
          description: No content
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
      parameters:
        - name: site_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
    delete:
      operationId: deleteSiteDevServerHook
      tags:
        - devServerHook
      responses:
        '204':
          description: No content
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
      parameters:
        - name: site_id
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
components:
  requestBodies:
    createSiteDevServerHookDevserverhook:
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
              branch:
                type: string
              type:
                type: string
                enum:
                  - new_dev_server
                  - content_refresh
      required: true
  schemas: {}
  x-stackQL-resources:
    dev_servers:
      id: netlify.dev_servers.dev_servers
      name: dev_servers
      title: Dev Servers
      methods:
        list:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1dev_servers/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        create:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1dev_servers/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1dev_servers/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '202'
        get:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1dev_servers~1{dev_server_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        mark_activity:
          operation:
            $ref: >-
              #/paths/~1sites~1{site_id}~1dev_servers~1{dev_server_id}~1activity/post
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        update_state:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: >-
              #/paths/~1sites~1{site_id}~1dev_servers~1{dev_server_id}~1state/post
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/dev_servers/methods/get'
          - $ref: '#/components/x-stackQL-resources/dev_servers/methods/list'
        insert:
          - $ref: '#/components/x-stackQL-resources/dev_servers/methods/create'
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/dev_servers/methods/delete'
        replace: []
    dev_server_hooks:
      id: netlify.dev_servers.dev_server_hooks
      name: dev_server_hooks
      title: Dev Server Hooks
      methods:
        list:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1dev_server_hooks/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        create:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1dev_server_hooks/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        get:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1dev_server_hooks~1{id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        update:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1dev_server_hooks~1{id}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        delete:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1dev_server_hooks~1{id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/dev_server_hooks/methods/get'
          - $ref: '#/components/x-stackQL-resources/dev_server_hooks/methods/list'
        insert:
          - $ref: '#/components/x-stackQL-resources/dev_server_hooks/methods/create'
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/dev_server_hooks/methods/delete'
        replace:
          - $ref: '#/components/x-stackQL-resources/dev_server_hooks/methods/update'
servers:
  - url: https://api.netlify.com/api/v1
x-stackQL-config:
  pagination:
    requestToken:
      key: ''
      location: request
    responseToken:
      key: Link
      location: header
