openapi: 3.0.0
info:
  title: forms API
  description: netlify forms API
  version: 2.57.0
paths:
  /sites/{site_id}/forms:
    get:
      operationId: listSiteForms
      tags:
        - form
      parameters:
        - name: site_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    site_id:
                      type: string
                    name:
                      type: string
                    paths:
                      type: array
                      items:
                        type: string
                    submission_count:
                      type: integer
                      format: int32
                    fields:
                      type: array
                      items:
                        type: string
                        description: (opaque JSON object)
                    created_at:
                      type: string
                      format: dateTime
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
  /sites/{site_id}/forms/{form_id}:
    delete:
      operationId: deleteSiteForm
      tags:
        - form
      parameters:
        - name: site_id
          in: path
          required: true
          schema:
            type: string
        - name: form_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
  /sites/{site_id}/submissions:
    get:
      operationId: listSiteSubmissions
      tags:
        - submission
      parameters:
        - name: site_id
          in: path
          required: true
          schema:
            type: string
        - name: page
          required: false
          in: query
          schema:
            type: integer
            format: int32
        - name: per_page
          required: false
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    number:
                      type: integer
                      format: int32
                    email:
                      type: string
                    name:
                      type: string
                    first_name:
                      type: string
                    last_name:
                      type: string
                    company:
                      type: string
                    summary:
                      type: string
                    body:
                      type: string
                    data:
                      type: string
                      description: (opaque JSON object)
                    created_at:
                      type: string
                      format: dateTime
                    site_url:
                      type: string
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
  /forms/{form_id}/submissions:
    get:
      operationId: listFormSubmissions
      tags:
        - submission
      parameters:
        - name: form_id
          in: path
          required: true
          schema:
            type: string
        - name: page
          required: false
          in: query
          schema:
            type: integer
            format: int32
        - name: per_page
          required: false
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    number:
                      type: integer
                      format: int32
                    email:
                      type: string
                    name:
                      type: string
                    first_name:
                      type: string
                    last_name:
                      type: string
                    company:
                      type: string
                    summary:
                      type: string
                    body:
                      type: string
                    data:
                      type: string
                      description: (opaque JSON object)
                    created_at:
                      type: string
                      format: dateTime
                    site_url:
                      type: string
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
  /submissions/{submission_id}:
    get:
      operationId: listFormSubmission
      tags:
        - submission
      parameters:
        - name: query
          in: query
          schema:
            type: string
        - name: page
          required: false
          in: query
          schema:
            type: integer
            format: int32
        - name: per_page
          required: false
          in: query
          schema:
            type: integer
            format: int32
        - name: submission_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    number:
                      type: integer
                      format: int32
                    email:
                      type: string
                    name:
                      type: string
                    first_name:
                      type: string
                    last_name:
                      type: string
                    company:
                      type: string
                    summary:
                      type: string
                    body:
                      type: string
                    data:
                      type: string
                      description: (opaque JSON object)
                    created_at:
                      type: string
                      format: dateTime
                    site_url:
                      type: string
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
    delete:
      operationId: deleteSubmission
      tags:
        - submission
      responses:
        '204':
          description: Deleted
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
      parameters:
        - name: submission_id
          in: path
          required: true
          schema:
            type: string
components:
  schemas: {}
  x-stackQL-resources:
    forms:
      id: netlify.forms.forms
      name: forms
      title: Forms
      methods:
        list:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1forms/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1forms~1{form_id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/forms/methods/list'
        insert: []
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/forms/methods/delete'
        replace: []
    submissions:
      id: netlify.forms.submissions
      name: submissions
      title: Submissions
      methods:
        list_for_site:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1submissions/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        list:
          operation:
            $ref: '#/paths/~1forms~1{form_id}~1submissions/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get:
          operation:
            $ref: '#/paths/~1submissions~1{submission_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete:
          operation:
            $ref: '#/paths/~1submissions~1{submission_id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/submissions/methods/list_for_site'
          - $ref: '#/components/x-stackQL-resources/submissions/methods/list'
          - $ref: '#/components/x-stackQL-resources/submissions/methods/get'
        insert: []
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/submissions/methods/delete'
        replace: []
servers:
  - url: https://api.netlify.com/api/v1
x-stackQL-config:
  pagination:
    requestToken:
      key: ''
      location: request
    responseToken:
      key: Link
      location: header
