openapi: 3.0.0
info:
  title: functions API
  description: netlify functions API
  version: 2.57.0
paths:
  /sites/{site_id}/functions:
    get:
      operationId: searchSiteFunctions
      tags:
        - function
      parameters:
        - name: site_id
          in: path
          required: true
          schema:
            type: string
        - name: filter
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    branch:
                      type: string
                    created_at:
                      type: string
                      format: dateTime
                    functions:
                      type: array
                      items:
                        type: string
                        description: (opaque JSON object)
                    id:
                      type: string
                    log_type:
                      type: string
                    provider:
                      type: string
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
components:
  schemas: {}
  x-stackQL-resources:
    functions:
      id: netlify.functions.functions
      name: functions
      title: Functions
      methods:
        list:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1functions/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/functions/methods/list'
        insert: []
        update: []
        delete: []
        replace: []
servers:
  - url: https://api.netlify.com/api/v1
x-stackQL-config:
  pagination:
    requestToken:
      key: ''
      location: request
    responseToken:
      key: Link
      location: header
