openapi: 3.0.0
info:
  title: hooks API
  description: netlify hooks API
  version: 2.57.0
paths:
  /hooks:
    get:
      operationId: listHooksBySiteId
      tags:
        - hook
      parameters:
        - name: site_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    site_id:
                      type: string
                    type:
                      type: string
                    event:
                      type: string
                    data:
                      type: string
                      description: (opaque JSON object)
                    created_at:
                      type: string
                      format: dateTime
                    updated_at:
                      type: string
                      format: dateTime
                    disabled:
                      type: boolean
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
    post:
      operationId: createHookBySiteId
      tags:
        - hook
      parameters:
        - name: site_id
          in: query
          required: true
          schema:
            type: string
      requestBody:
        $ref: '#/components/requestBodies/createHookBySiteIdHook'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  site_id:
                    type: string
                  type:
                    type: string
                  event:
                    type: string
                  data:
                    type: string
                    description: (opaque JSON object)
                  created_at:
                    type: string
                    format: dateTime
                  updated_at:
                    type: string
                    format: dateTime
                  disabled:
                    type: boolean
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
  /hooks/{hook_id}:
    get:
      operationId: getHook
      tags:
        - hook
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  site_id:
                    type: string
                  type:
                    type: string
                  event:
                    type: string
                  data:
                    type: string
                    description: (opaque JSON object)
                  created_at:
                    type: string
                    format: dateTime
                  updated_at:
                    type: string
                    format: dateTime
                  disabled:
                    type: boolean
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
      parameters:
        - name: hook_id
          in: path
          required: true
          schema:
            type: string
    put:
      operationId: updateHook
      tags:
        - hook
      requestBody:
        $ref: '#/components/requestBodies/createHookBySiteIdHook'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  site_id:
                    type: string
                  type:
                    type: string
                  event:
                    type: string
                  data:
                    type: string
                    description: (opaque JSON object)
                  created_at:
                    type: string
                    format: dateTime
                  updated_at:
                    type: string
                    format: dateTime
                  disabled:
                    type: boolean
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
      parameters:
        - name: hook_id
          in: path
          required: true
          schema:
            type: string
    delete:
      operationId: deleteHook
      tags:
        - hook
      responses:
        '204':
          description: No content
      parameters:
        - name: hook_id
          in: path
          required: true
          schema:
            type: string
  /hooks/{hook_id}/enable:
    post:
      operationId: enableHook
      tags:
        - hook
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  site_id:
                    type: string
                  type:
                    type: string
                  event:
                    type: string
                  data:
                    type: string
                    description: (opaque JSON object)
                  created_at:
                    type: string
                    format: dateTime
                  updated_at:
                    type: string
                    format: dateTime
                  disabled:
                    type: boolean
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
      parameters:
        - name: hook_id
          in: path
          required: true
          schema:
            type: string
  /hooks/types:
    get:
      operationId: listHookTypes
      tags:
        - hookType
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    events:
                      type: array
                      items:
                        type: string
                    fields:
                      type: array
                      items:
                        type: string
                        description: (opaque JSON object)
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
components:
  requestBodies:
    createHookBySiteIdHook:
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
              site_id:
                type: string
              type:
                type: string
              event:
                type: string
              data:
                type: string
                description: (opaque JSON object)
              created_at:
                type: string
                format: dateTime
              updated_at:
                type: string
                format: dateTime
              disabled:
                type: boolean
      required: true
  schemas: {}
  x-stackQL-resources:
    hooks:
      id: netlify.hooks.hooks
      name: hooks
      title: Hooks
      methods:
        list:
          operation:
            $ref: '#/paths/~1hooks/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        create:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1hooks/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        get:
          operation:
            $ref: '#/paths/~1hooks~1{hook_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        update:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1hooks~1{hook_id}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete:
          operation:
            $ref: '#/paths/~1hooks~1{hook_id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        enable:
          operation:
            $ref: '#/paths/~1hooks~1{hook_id}~1enable/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/hooks/methods/get'
          - $ref: '#/components/x-stackQL-resources/hooks/methods/list'
        insert:
          - $ref: '#/components/x-stackQL-resources/hooks/methods/create'
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/hooks/methods/delete'
        replace:
          - $ref: '#/components/x-stackQL-resources/hooks/methods/update'
    hook_types:
      id: netlify.hooks.hook_types
      name: hook_types
      title: Hook Types
      methods:
        list:
          operation:
            $ref: '#/paths/~1hooks~1types/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/hook_types/methods/list'
        insert: []
        update: []
        delete: []
        replace: []
servers:
  - url: https://api.netlify.com/api/v1
x-stackQL-config:
  pagination:
    requestToken:
      key: ''
      location: request
    responseToken:
      key: Link
      location: header
