openapi: 3.0.0
info:
  title: oauth API
  description: netlify oauth API
  version: 2.57.0
paths:
  /oauth/tickets:
    post:
      operationId: createTicket
      tags:
        - ticket
      parameters:
        - name: client_id
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  client_id:
                    type: string
                  authorized:
                    type: boolean
                  created_at:
                    type: string
                    format: dateTime
        '401':
          description: OAuth application not found
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
  /oauth/tickets/{ticket_id}:
    get:
      operationId: showTicket
      tags:
        - ticket
      parameters:
        - name: ticket_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  client_id:
                    type: string
                  authorized:
                    type: boolean
                  created_at:
                    type: string
                    format: dateTime
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
  /oauth/tickets/{ticket_id}/exchange:
    post:
      operationId: exchangeTicket
      tags:
        - accessToken
      parameters:
        - name: ticket_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  access_token:
                    type: string
                  user_id:
                    type: string
                  user_email:
                    type: string
                  created_at:
                    type: string
                    format: dateTime
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
components:
  x-stackQL-resources:
    tickets:
      id: netlify.oauth.tickets
      name: tickets
      title: Tickets
      methods:
        create:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1oauth~1tickets/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        get:
          operation:
            $ref: '#/paths/~1oauth~1tickets~1{ticket_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        exchange:
          operation:
            $ref: '#/paths/~1oauth~1tickets~1{ticket_id}~1exchange/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/tickets/methods/get'
        insert:
          - $ref: '#/components/x-stackQL-resources/tickets/methods/create'
        update: []
        delete: []
        replace: []
servers:
  - url: https://api.netlify.com/api/v1
x-stackQL-config:
  pagination:
    requestToken:
      key: ''
      location: request
    responseToken:
      key: Link
      location: header
