openapi: 3.0.0
info:
  title: users API
  description: netlify users API
  version: 2.57.0
paths:
  /user:
    get:
      operationId: getCurrentUser
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  uid:
                    type: string
                  full_name:
                    type: string
                  avatar_url:
                    type: string
                  email:
                    type: string
                  affiliate_id:
                    type: string
                  site_count:
                    type: integer
                    format: int64
                  created_at:
                    type: string
                    format: dateTime
                  last_login:
                    type: string
                    format: dateTime
                  login_providers:
                    type: array
                    items:
                      type: string
                  onboarding_progress:
                    type: object
                    properties:
                      slides:
                        type: string
        default:
          description: error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  code:
                    type: integer
                    format: int64
                  message:
                    type: string
                    nullable: false
components:
  x-stackQL-resources:
    users:
      id: netlify.users.users
      name: users
      title: Users
      methods:
        get_current:
          operation:
            $ref: '#/paths/~1user/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/users/methods/get_current'
        insert: []
        update: []
        delete: []
        replace: []
servers:
  - url: https://api.netlify.com/api/v1
x-stackQL-config:
  pagination:
    requestToken:
      key: ''
      location: request
    responseToken:
      key: Link
      location: header
