paths:
  /accounts:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/accountMembership'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - accountMembership
      operationId: listAccountsForUser
    post:
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accountMembership'
          description: Created
        default:
          $ref: '#/components/responses/error'
      tags:
        - accountMembership
      operationId: createAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/accountSetup'
        required: true
  /accounts/{account_id}:
    delete:
      responses:
        '204':
          description: Not Content
        default:
          $ref: '#/components/responses/error'
      tags:
        - accountMembership
      operationId: cancelAccount
      parameters: &ref_0
        - in: path
          name: account_id
          required: true
          schema:
            type: string
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/accountMembership'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - accountMembership
      operationId: getAccount
      parameters: *ref_0
    put:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/accountMembership'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - accountMembership
      operationId: updateAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/accountUpdateSetup'
      parameters: *ref_0
components:
  schemas:
    accountMembership:
      properties:
        billing_details:
          type: string
        billing_email:
          type: string
        billing_name:
          type: string
        billing_period:
          type: string
        capabilities:
          properties:
            collaborators:
              $ref: '#/components/schemas/accountUsageCapability'
            sites:
              $ref: '#/components/schemas/accountUsageCapability'
          type: object
        created_at:
          format: dateTime
          type: string
        id:
          type: string
        name:
          type: string
        owner_ids:
          items:
            type: string
          type: array
        payment_method_id:
          type: string
        roles_allowed:
          items:
            type: string
          type: array
        slug:
          type: string
        type:
          type: string
        type_id:
          type: string
        type_name:
          type: string
        updated_at:
          format: dateTime
          type: string
      type: object
    accountUsageCapability:
      properties:
        included:
          type: integer
        used:
          type: integer
      type: object
    error:
      properties:
        code:
          format: int64
          type: integer
        message:
          nullable: false
          type: string
      required:
        - message
      type: object
    accountSetup:
      properties:
        extra_seats_block:
          type: integer
        name:
          type: string
        payment_method_id:
          type: string
        period:
          enum:
            - monthly
            - yearly
          type: string
        type_id:
          type: string
      required:
        - name
        - type_id
      type: object
    accountUpdateSetup:
      properties:
        billing_details:
          type: string
        billing_email:
          type: string
        billing_name:
          type: string
        extra_seats_block:
          type: integer
        name:
          type: string
        slug:
          type: string
        type_id:
          type: string
      type: object
  parameters: {}
  responses:
    error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: error
  securitySchemes: {}
  callbacks: {}
  examples: {}
  requestBodies: {}
  headers: {}
  links: {}
  x-stackQL-resources:
    accounts:
      id: netlify.account_membership.accounts
      name: accounts
      title: Accounts
      methods:
        listAccountsForUser:
          operation:
            $ref: '#/paths/~1accounts/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        createAccount:
          operation:
            $ref: '#/paths/~1accounts/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        cancelAccount:
          operation:
            $ref: '#/paths/~1accounts~1{account_id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        getAccount:
          operation:
            $ref: '#/paths/~1accounts~1{account_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        updateAccount:
          operation:
            $ref: '#/paths/~1accounts~1{account_id}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/accounts/methods/getAccount'
          - $ref: '#/components/x-stackQL-resources/accounts/methods/listAccountsForUser'
        insert:
          - $ref: '#/components/x-stackQL-resources/accounts/methods/createAccount'
        update: []
        delete: []
openapi: 3.0.0
servers:
  - url: https://api.netlify.com/api/v1
security:
  - netlifyAuth: []
tags:
  - name: ticket
    x-displayName: Ticket
  - name: accessToken
    x-displayName: Access token
  - name: user
    x-displayName: User
  - name: accountMembership
    x-displayName: Accounts
  - name: member
    x-displayName: Member
  - name: accountType
    x-displayName: Access type
  - name: paymentMethod
    x-displayName: Payment method
  - name: auditLog
    x-displayName: Audit log
  - name: site
    x-displayName: Site
  - name: file
    x-displayName: File
  - name: metadata
    x-displayName: Metadata
  - name: snippet
    x-displayName: Snippet
  - name: dnsZone
    x-displayName: DNS zone
  - name: sniCertificate
    x-displayName: SNI certificate
  - name: deploy
    x-displayName: Deploy
  - name: deployedBranch
    x-displayName: Deployed branch
  - name: deployKey
    x-displayName: Deploy key
  - name: build
    x-displayName: Build
  - name: buildLogMsg
    x-displayName: Build log message
  - name: hook
    x-displayName: Hook
  - name: hookType
    x-displayName: Hook type
  - name: buildHook
    x-displayName: Build hook
  - name: service
    x-displayName: Service
  - name: serviceInstance
    x-displayName: Service instance
  - name: function
    x-displayName: Function
  - name: form
    x-displayName: Form
  - name: submission
    x-displayName: Form submission
  - name: splitTest
    x-displayName: Split test
  - name: asset
    x-displayName: Asset
  - name: assetPublicSignature
    x-displayName: Asset public signature
externalDocs:
  description: Online documentation
  url: https://www.netlify.com/docs/api/
info:
  description: accountMembership
  termsOfService: https://www.netlify.com/legal/terms-of-use/
  title: Netlify's API documentation - account_membership
  version: 2.9.0
  x-logo:
    altText: Netlify
    href: https://www.netlify.com/docs/
    url: netlify-logo.png
