paths:
  /sites/{site_id}/build_hooks:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/buildHook'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - buildHook
      operationId: listSiteBuildHooks
      parameters: &ref_0
        - in: path
          name: site_id
          required: true
          schema:
            type: string
    post:
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/buildHook'
          description: Created
        default:
          $ref: '#/components/responses/error'
      tags:
        - buildHook
      operationId: createSiteBuildHook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/buildHookSetup'
        required: true
      parameters: *ref_0
  /sites/{site_id}/build_hooks/{id}:
    delete:
      responses:
        '204':
          description: No content
        default:
          $ref: '#/components/responses/error'
      tags:
        - buildHook
      operationId: deleteSiteBuildHook
      parameters: &ref_1
        - in: path
          name: site_id
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/buildHook'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - buildHook
      operationId: getSiteBuildHook
      parameters: *ref_1
    put:
      responses:
        '204':
          description: No content
        default:
          $ref: '#/components/responses/error'
      tags:
        - buildHook
      operationId: updateSiteBuildHook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/buildHookSetup'
        required: true
      parameters: *ref_1
components:
  schemas:
    buildHook:
      properties:
        branch:
          type: string
        created_at:
          format: dateTime
          type: string
        id:
          type: string
        site_id:
          type: string
        title:
          type: string
        url:
          type: string
      type: object
    error:
      properties:
        code:
          format: int64
          type: integer
        message:
          nullable: false
          type: string
      required:
        - message
      type: object
    buildHookSetup:
      properties:
        branch:
          type: string
        title:
          type: string
      type: object
  parameters: {}
  responses:
    error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: error
  securitySchemes: {}
  callbacks: {}
  examples: {}
  requestBodies: {}
  headers: {}
  links: {}
  x-stackQL-resources:
    sites_build_hooks:
      id: netlify.build_hook.sites_build_hooks
      name: sites_build_hooks
      title: Sites_build_hooks
      methods:
        listSiteBuildHooks:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1build_hooks/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        createSiteBuildHook:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1build_hooks/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        deleteSiteBuildHook:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1build_hooks~1{id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        getSiteBuildHook:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1build_hooks~1{id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        updateSiteBuildHook:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1build_hooks~1{id}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/sites_build_hooks/methods/getSiteBuildHook'
          - $ref: '#/components/x-stackQL-resources/sites_build_hooks/methods/listSiteBuildHooks'
        insert:
          - $ref: '#/components/x-stackQL-resources/sites_build_hooks/methods/createSiteBuildHook'
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/sites_build_hooks/methods/deleteSiteBuildHook'
openapi: 3.0.0
servers:
  - url: https://api.netlify.com/api/v1
security:
  - netlifyAuth: []
tags:
  - name: ticket
    x-displayName: Ticket
  - name: accessToken
    x-displayName: Access token
  - name: user
    x-displayName: User
  - name: accountMembership
    x-displayName: Accounts
  - name: member
    x-displayName: Member
  - name: accountType
    x-displayName: Access type
  - name: paymentMethod
    x-displayName: Payment method
  - name: auditLog
    x-displayName: Audit log
  - name: site
    x-displayName: Site
  - name: file
    x-displayName: File
  - name: metadata
    x-displayName: Metadata
  - name: snippet
    x-displayName: Snippet
  - name: dnsZone
    x-displayName: DNS zone
  - name: sniCertificate
    x-displayName: SNI certificate
  - name: deploy
    x-displayName: Deploy
  - name: deployedBranch
    x-displayName: Deployed branch
  - name: deployKey
    x-displayName: Deploy key
  - name: build
    x-displayName: Build
  - name: buildLogMsg
    x-displayName: Build log message
  - name: hook
    x-displayName: Hook
  - name: hookType
    x-displayName: Hook type
  - name: buildHook
    x-displayName: Build hook
  - name: service
    x-displayName: Service
  - name: serviceInstance
    x-displayName: Service instance
  - name: function
    x-displayName: Function
  - name: form
    x-displayName: Form
  - name: submission
    x-displayName: Form submission
  - name: splitTest
    x-displayName: Split test
  - name: asset
    x-displayName: Asset
  - name: assetPublicSignature
    x-displayName: Asset public signature
externalDocs:
  description: Online documentation
  url: https://www.netlify.com/docs/api/
info:
  description: buildHook
  termsOfService: https://www.netlify.com/legal/terms-of-use/
  title: Netlify's API documentation - build_hook
  version: 2.9.0
  x-logo:
    altText: Netlify
    href: https://www.netlify.com/docs/
    url: netlify-logo.png
