paths:
  /deploy_keys:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/deployKey'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - deployKey
      operationId: listDeployKeys
    post:
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deployKey'
          description: Created
        default:
          $ref: '#/components/responses/error'
      tags:
        - deployKey
      operationId: createDeployKey
  /deploy_keys/{key_id}:
    delete:
      responses:
        '204':
          description: Not Content
        default:
          $ref: '#/components/responses/error'
      tags:
        - deployKey
      operationId: deleteDeployKey
      parameters: &ref_0
        - in: path
          name: key_id
          required: true
          schema:
            type: string
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deployKey'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - deployKey
      operationId: getDeployKey
      parameters: *ref_0
components:
  schemas:
    deployKey:
      properties:
        created_at:
          format: dateTime
          type: string
        id:
          type: string
        public_key:
          type: string
      type: object
    error:
      properties:
        code:
          format: int64
          type: integer
        message:
          nullable: false
          type: string
      required:
        - message
      type: object
  parameters: {}
  responses:
    error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: error
  securitySchemes: {}
  callbacks: {}
  examples: {}
  requestBodies: {}
  headers: {}
  links: {}
  x-stackQL-resources:
    deploy_keys:
      id: netlify.deploy_key.deploy_keys
      name: deploy_keys
      title: Deploy_keys
      methods:
        listDeployKeys:
          operation:
            $ref: '#/paths/~1deploy_keys/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        createDeployKey:
          operation:
            $ref: '#/paths/~1deploy_keys/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        deleteDeployKey:
          operation:
            $ref: '#/paths/~1deploy_keys~1{key_id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        getDeployKey:
          operation:
            $ref: '#/paths/~1deploy_keys~1{key_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/deploy_keys/methods/getDeployKey'
          - $ref: '#/components/x-stackQL-resources/deploy_keys/methods/listDeployKeys'
        insert:
          - $ref: '#/components/x-stackQL-resources/deploy_keys/methods/createDeployKey'
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/deploy_keys/methods/deleteDeployKey'
openapi: 3.0.0
servers:
  - url: https://api.netlify.com/api/v1
security:
  - netlifyAuth: []
tags:
  - name: ticket
    x-displayName: Ticket
  - name: accessToken
    x-displayName: Access token
  - name: user
    x-displayName: User
  - name: accountMembership
    x-displayName: Accounts
  - name: member
    x-displayName: Member
  - name: accountType
    x-displayName: Access type
  - name: paymentMethod
    x-displayName: Payment method
  - name: auditLog
    x-displayName: Audit log
  - name: site
    x-displayName: Site
  - name: file
    x-displayName: File
  - name: metadata
    x-displayName: Metadata
  - name: snippet
    x-displayName: Snippet
  - name: dnsZone
    x-displayName: DNS zone
  - name: sniCertificate
    x-displayName: SNI certificate
  - name: deploy
    x-displayName: Deploy
  - name: deployedBranch
    x-displayName: Deployed branch
  - name: deployKey
    x-displayName: Deploy key
  - name: build
    x-displayName: Build
  - name: buildLogMsg
    x-displayName: Build log message
  - name: hook
    x-displayName: Hook
  - name: hookType
    x-displayName: Hook type
  - name: buildHook
    x-displayName: Build hook
  - name: service
    x-displayName: Service
  - name: serviceInstance
    x-displayName: Service instance
  - name: function
    x-displayName: Function
  - name: form
    x-displayName: Form
  - name: submission
    x-displayName: Form submission
  - name: splitTest
    x-displayName: Split test
  - name: asset
    x-displayName: Asset
  - name: assetPublicSignature
    x-displayName: Asset public signature
externalDocs:
  description: Online documentation
  url: https://www.netlify.com/docs/api/
info:
  description: deployKey
  termsOfService: https://www.netlify.com/legal/terms-of-use/
  title: Netlify's API documentation - deploy_key
  version: 2.9.0
  x-logo:
    altText: Netlify
    href: https://www.netlify.com/docs/
    url: netlify-logo.png
