paths:
  /deploys/{deploy_id}/files/{path}:
    put:
      parameters:
        - in: path
          name: deploy_id
          required: true
          schema:
            type: string
        - in: path
          name: path
          required: true
          schema:
            type: string
        - in: query
          name: size
          schema:
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/file'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - file
      operationId: uploadDeployFile
      requestBody:
        content:
          application/json:
            schema:
              format: binary
              type: string
          application/octet-stream:
            schema:
              format: binary
              type: string
        required: true
  /sites/{site_id}/files:
    get:
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/file'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - file
      operationId: listSiteFiles
  /sites/{site_id}/files/{file_path}:
    get:
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
        - in: path
          name: file_path
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/file'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - file
      operationId: getSiteFileByPathName
components:
  schemas:
    file:
      properties:
        id:
          type: string
        mime_type:
          type: string
        path:
          type: string
        sha:
          type: string
        size:
          format: int64
          type: integer
      type: object
    error:
      properties:
        code:
          format: int64
          type: integer
        message:
          nullable: false
          type: string
      required:
        - message
      type: object
  parameters: {}
  responses:
    error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: error
  securitySchemes: {}
  callbacks: {}
  examples: {}
  requestBodies: {}
  headers: {}
  links: {}
  x-stackQL-resources:
    deploys_files:
      id: netlify.file.deploys_files
      name: deploys_files
      title: Deploys_files
      methods:
        uploadDeployFile:
          operation:
            $ref: '#/paths/~1deploys~1{deploy_id}~1files~1{path}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    sites_files:
      id: netlify.file.sites_files
      name: sites_files
      title: Sites_files
      methods:
        listSiteFiles:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1files/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        getSiteFileByPathName:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1files~1{file_path}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/sites_files/methods/getSiteFileByPathName'
          - $ref: '#/components/x-stackQL-resources/sites_files/methods/listSiteFiles'
        insert: []
        update: []
        delete: []
openapi: 3.0.0
servers:
  - url: https://api.netlify.com/api/v1
security:
  - netlifyAuth: []
tags:
  - name: ticket
    x-displayName: Ticket
  - name: accessToken
    x-displayName: Access token
  - name: user
    x-displayName: User
  - name: accountMembership
    x-displayName: Accounts
  - name: member
    x-displayName: Member
  - name: accountType
    x-displayName: Access type
  - name: paymentMethod
    x-displayName: Payment method
  - name: auditLog
    x-displayName: Audit log
  - name: site
    x-displayName: Site
  - name: file
    x-displayName: File
  - name: metadata
    x-displayName: Metadata
  - name: snippet
    x-displayName: Snippet
  - name: dnsZone
    x-displayName: DNS zone
  - name: sniCertificate
    x-displayName: SNI certificate
  - name: deploy
    x-displayName: Deploy
  - name: deployedBranch
    x-displayName: Deployed branch
  - name: deployKey
    x-displayName: Deploy key
  - name: build
    x-displayName: Build
  - name: buildLogMsg
    x-displayName: Build log message
  - name: hook
    x-displayName: Hook
  - name: hookType
    x-displayName: Hook type
  - name: buildHook
    x-displayName: Build hook
  - name: service
    x-displayName: Service
  - name: serviceInstance
    x-displayName: Service instance
  - name: function
    x-displayName: Function
  - name: form
    x-displayName: Form
  - name: submission
    x-displayName: Form submission
  - name: splitTest
    x-displayName: Split test
  - name: asset
    x-displayName: Asset
  - name: assetPublicSignature
    x-displayName: Asset public signature
externalDocs:
  description: Online documentation
  url: https://www.netlify.com/docs/api/
info:
  description: file
  termsOfService: https://www.netlify.com/legal/terms-of-use/
  title: Netlify's API documentation - file
  version: 2.9.0
  x-logo:
    altText: Netlify
    href: https://www.netlify.com/docs/
    url: netlify-logo.png
