paths:
  /services/:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/service'
                type: array
          description: services
        default:
          $ref: '#/components/responses/error'
      tags:
        - service
      operationId: getServices
      parameters:
        - in: query
          name: search
          schema:
            type: string
  /services/{addonName}:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service'
          description: services
        default:
          $ref: '#/components/responses/error'
      tags:
        - service
      operationId: showService
      parameters:
        - in: path
          name: addonName
          required: true
          schema:
            type: string
  /services/{addonName}/manifest:
    get:
      responses:
        '201':
          content:
            application/json:
              schema:
                type: object
          description: retrieving from provider
        default:
          $ref: '#/components/responses/error'
      tags:
        - service
      operationId: showServiceManifest
      parameters:
        - in: path
          name: addonName
          required: true
          schema:
            type: string
components:
  schemas:
    service:
      properties:
        tags:
          items:
            type: string
          type: array
        created_at:
          format: dateTime
          type: string
        description:
          type: string
        environments:
          items:
            type: string
          type: array
        events:
          items:
            type: object
          type: array
        icon:
          type: string
        id:
          type: string
        long_description:
          type: string
        manifest_url:
          type: string
        name:
          type: string
        service_path:
          type: string
        slug:
          type: string
        updated_at:
          format: dateTime
          type: string
      type: object
    error:
      properties:
        code:
          format: int64
          type: integer
        message:
          nullable: false
          type: string
      required:
        - message
      type: object
  parameters: {}
  responses:
    error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: error
  securitySchemes: {}
  callbacks: {}
  examples: {}
  requestBodies: {}
  headers: {}
  links: {}
  x-stackQL-resources:
    services:
      id: netlify.service.services
      name: services
      title: Services
      methods:
        getServices:
          operation:
            $ref: '#/paths/~1services~1/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        showService:
          operation:
            $ref: '#/paths/~1services~1{addonName}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/services/methods/getServices'
        insert: []
        update: []
        delete: []
    services_manifest:
      id: netlify.service.services_manifest
      name: services_manifest
      title: Services_manifest
      methods:
        showServiceManifest:
          operation:
            $ref: '#/paths/~1services~1{addonName}~1manifest/get'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
openapi: 3.0.0
servers:
  - url: https://api.netlify.com/api/v1
security:
  - netlifyAuth: []
tags:
  - name: ticket
    x-displayName: Ticket
  - name: accessToken
    x-displayName: Access token
  - name: user
    x-displayName: User
  - name: accountMembership
    x-displayName: Accounts
  - name: member
    x-displayName: Member
  - name: accountType
    x-displayName: Access type
  - name: paymentMethod
    x-displayName: Payment method
  - name: auditLog
    x-displayName: Audit log
  - name: site
    x-displayName: Site
  - name: file
    x-displayName: File
  - name: metadata
    x-displayName: Metadata
  - name: snippet
    x-displayName: Snippet
  - name: dnsZone
    x-displayName: DNS zone
  - name: sniCertificate
    x-displayName: SNI certificate
  - name: deploy
    x-displayName: Deploy
  - name: deployedBranch
    x-displayName: Deployed branch
  - name: deployKey
    x-displayName: Deploy key
  - name: build
    x-displayName: Build
  - name: buildLogMsg
    x-displayName: Build log message
  - name: hook
    x-displayName: Hook
  - name: hookType
    x-displayName: Hook type
  - name: buildHook
    x-displayName: Build hook
  - name: service
    x-displayName: Service
  - name: serviceInstance
    x-displayName: Service instance
  - name: function
    x-displayName: Function
  - name: form
    x-displayName: Form
  - name: submission
    x-displayName: Form submission
  - name: splitTest
    x-displayName: Split test
  - name: asset
    x-displayName: Asset
  - name: assetPublicSignature
    x-displayName: Asset public signature
externalDocs:
  description: Online documentation
  url: https://www.netlify.com/docs/api/
info:
  description: service
  termsOfService: https://www.netlify.com/legal/terms-of-use/
  title: Netlify's API documentation - service
  version: 2.9.0
  x-logo:
    altText: Netlify
    href: https://www.netlify.com/docs/
    url: netlify-logo.png
