paths:
  /sites/{site_id}/snippets:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/snippet'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - snippet
      operationId: listSiteSnippets
      parameters: &ref_0
        - in: path
          name: site_id
          required: true
          schema:
            type: string
    post:
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/snippet'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - snippet
      operationId: createSiteSnippet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/snippet'
        required: true
      parameters: *ref_0
  /sites/{site_id}/snippets/{snippet_id}:
    delete:
      responses:
        '204':
          description: No content
        default:
          $ref: '#/components/responses/error'
      tags:
        - snippet
      operationId: deleteSiteSnippet
      parameters: &ref_1
        - in: path
          name: site_id
          required: true
          schema:
            type: string
        - in: path
          name: snippet_id
          required: true
          schema:
            type: string
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/snippet'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - snippet
      operationId: getSiteSnippet
      parameters: *ref_1
    put:
      responses:
        '204':
          description: No content
        default:
          $ref: '#/components/responses/error'
      tags:
        - snippet
      operationId: updateSiteSnippet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/snippet'
        required: true
      parameters: *ref_1
components:
  schemas:
    snippet:
      properties:
        general:
          type: string
        general_position:
          type: string
        goal:
          type: string
        goal_position:
          type: string
        id:
          format: int32
          type: integer
        site_id:
          type: string
        title:
          type: string
      type: object
    error:
      properties:
        code:
          format: int64
          type: integer
        message:
          nullable: false
          type: string
      required:
        - message
      type: object
  parameters: {}
  responses:
    error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: error
  securitySchemes: {}
  callbacks: {}
  examples: {}
  requestBodies: {}
  headers: {}
  links: {}
  x-stackQL-resources:
    sites_snippets:
      id: netlify.snippet.sites_snippets
      name: sites_snippets
      title: Sites_snippets
      methods:
        listSiteSnippets:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1snippets/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        createSiteSnippet:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1snippets/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        deleteSiteSnippet:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1snippets~1{snippet_id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        getSiteSnippet:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1snippets~1{snippet_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        updateSiteSnippet:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1snippets~1{snippet_id}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/sites_snippets/methods/getSiteSnippet'
          - $ref: '#/components/x-stackQL-resources/sites_snippets/methods/listSiteSnippets'
        insert:
          - $ref: '#/components/x-stackQL-resources/sites_snippets/methods/createSiteSnippet'
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/sites_snippets/methods/deleteSiteSnippet'
openapi: 3.0.0
servers:
  - url: https://api.netlify.com/api/v1
security:
  - netlifyAuth: []
tags:
  - name: ticket
    x-displayName: Ticket
  - name: accessToken
    x-displayName: Access token
  - name: user
    x-displayName: User
  - name: accountMembership
    x-displayName: Accounts
  - name: member
    x-displayName: Member
  - name: accountType
    x-displayName: Access type
  - name: paymentMethod
    x-displayName: Payment method
  - name: auditLog
    x-displayName: Audit log
  - name: site
    x-displayName: Site
  - name: file
    x-displayName: File
  - name: metadata
    x-displayName: Metadata
  - name: snippet
    x-displayName: Snippet
  - name: dnsZone
    x-displayName: DNS zone
  - name: sniCertificate
    x-displayName: SNI certificate
  - name: deploy
    x-displayName: Deploy
  - name: deployedBranch
    x-displayName: Deployed branch
  - name: deployKey
    x-displayName: Deploy key
  - name: build
    x-displayName: Build
  - name: buildLogMsg
    x-displayName: Build log message
  - name: hook
    x-displayName: Hook
  - name: hookType
    x-displayName: Hook type
  - name: buildHook
    x-displayName: Build hook
  - name: service
    x-displayName: Service
  - name: serviceInstance
    x-displayName: Service instance
  - name: function
    x-displayName: Function
  - name: form
    x-displayName: Form
  - name: submission
    x-displayName: Form submission
  - name: splitTest
    x-displayName: Split test
  - name: asset
    x-displayName: Asset
  - name: assetPublicSignature
    x-displayName: Asset public signature
externalDocs:
  description: Online documentation
  url: https://www.netlify.com/docs/api/
info:
  description: snippet
  termsOfService: https://www.netlify.com/legal/terms-of-use/
  title: Netlify's API documentation - snippet
  version: 2.9.0
  x-logo:
    altText: Netlify
    href: https://www.netlify.com/docs/
    url: netlify-logo.png
