paths:
  /sites/{site_id}/traffic_splits:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/splitTests'
          description: split_tests
        default:
          $ref: '#/components/responses/error'
      tags:
        - splitTest
      operationId: getSplitTests
      parameters: &ref_0
        - in: path
          name: site_id
          required: true
          schema:
            type: string
    post:
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/splitTest'
          description: Created
        default:
          $ref: '#/components/responses/error'
      tags:
        - splitTest
      operationId: createSplitTest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/splitTestSetup'
        required: true
      parameters: *ref_0
  /sites/{site_id}/traffic_splits/{split_test_id}:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/splitTest'
          description: split_test
        default:
          $ref: '#/components/responses/error'
      tags:
        - splitTest
      operationId: getSplitTest
      parameters: &ref_1
        - in: path
          name: site_id
          required: true
          schema:
            type: string
        - in: path
          name: split_test_id
          required: true
          schema:
            type: string
    put:
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/splitTest'
          description: Created
        default:
          $ref: '#/components/responses/error'
      tags:
        - splitTest
      operationId: updateSplitTest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/splitTestSetup'
        required: true
      parameters: *ref_1
  /sites/{site_id}/traffic_splits/{split_test_id}/publish:
    post:
      responses:
        '204':
          description: enable
        default:
          $ref: '#/components/responses/error'
      tags:
        - splitTest
      operationId: enableSplitTest
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
        - in: path
          name: split_test_id
          required: true
          schema:
            type: string
  /sites/{site_id}/traffic_splits/{split_test_id}/unpublish:
    post:
      responses:
        '204':
          description: disabled
        default:
          $ref: '#/components/responses/error'
      tags:
        - splitTest
      operationId: disableSplitTest
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
        - in: path
          name: split_test_id
          required: true
          schema:
            type: string
components:
  schemas:
    splitTests:
      items:
        $ref: '#/components/schemas/splitTest'
      type: array
    splitTest:
      properties:
        active:
          type: boolean
        branches:
          items:
            type: object
          type: array
        created_at:
          format: dateTime
          type: string
        id:
          type: string
        name:
          type: string
        path:
          type: string
        site_id:
          type: string
        unpublished_at:
          format: dateTime
          type: string
        updated_at:
          format: dateTime
          type: string
      type: object
    error:
      properties:
        code:
          format: int64
          type: integer
        message:
          nullable: false
          type: string
      required:
        - message
      type: object
    splitTestSetup:
      properties:
        branch_tests:
          type: object
      type: object
  parameters: {}
  responses:
    error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: error
  securitySchemes: {}
  callbacks: {}
  examples: {}
  requestBodies: {}
  headers: {}
  links: {}
  x-stackQL-resources:
    sites_traffic_splits:
      id: netlify.split_test.sites_traffic_splits
      name: sites_traffic_splits
      title: Sites_traffic_splits
      methods:
        getSplitTests:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1traffic_splits/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        createSplitTest:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1traffic_splits/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        getSplitTest:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1traffic_splits~1{split_test_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        updateSplitTest:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1traffic_splits~1{split_test_id}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/sites_traffic_splits/methods/getSplitTest'
          - $ref: '#/components/x-stackQL-resources/sites_traffic_splits/methods/getSplitTests'
        insert:
          - $ref: '#/components/x-stackQL-resources/sites_traffic_splits/methods/createSplitTest'
        update: []
        delete: []
    sites_traffic_splits_publish:
      id: netlify.split_test.sites_traffic_splits_publish
      name: sites_traffic_splits_publish
      title: Sites_traffic_splits_publish
      methods:
        enableSplitTest:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1traffic_splits~1{split_test_id}~1publish/post'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    sites_traffic_splits_unpublish:
      id: netlify.split_test.sites_traffic_splits_unpublish
      name: sites_traffic_splits_unpublish
      title: Sites_traffic_splits_unpublish
      methods:
        disableSplitTest:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1traffic_splits~1{split_test_id}~1unpublish/post'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
openapi: 3.0.0
servers:
  - url: https://api.netlify.com/api/v1
security:
  - netlifyAuth: []
tags:
  - name: ticket
    x-displayName: Ticket
  - name: accessToken
    x-displayName: Access token
  - name: user
    x-displayName: User
  - name: accountMembership
    x-displayName: Accounts
  - name: member
    x-displayName: Member
  - name: accountType
    x-displayName: Access type
  - name: paymentMethod
    x-displayName: Payment method
  - name: auditLog
    x-displayName: Audit log
  - name: site
    x-displayName: Site
  - name: file
    x-displayName: File
  - name: metadata
    x-displayName: Metadata
  - name: snippet
    x-displayName: Snippet
  - name: dnsZone
    x-displayName: DNS zone
  - name: sniCertificate
    x-displayName: SNI certificate
  - name: deploy
    x-displayName: Deploy
  - name: deployedBranch
    x-displayName: Deployed branch
  - name: deployKey
    x-displayName: Deploy key
  - name: build
    x-displayName: Build
  - name: buildLogMsg
    x-displayName: Build log message
  - name: hook
    x-displayName: Hook
  - name: hookType
    x-displayName: Hook type
  - name: buildHook
    x-displayName: Build hook
  - name: service
    x-displayName: Service
  - name: serviceInstance
    x-displayName: Service instance
  - name: function
    x-displayName: Function
  - name: form
    x-displayName: Form
  - name: submission
    x-displayName: Form submission
  - name: splitTest
    x-displayName: Split test
  - name: asset
    x-displayName: Asset
  - name: assetPublicSignature
    x-displayName: Asset public signature
externalDocs:
  description: Online documentation
  url: https://www.netlify.com/docs/api/
info:
  description: splitTest
  termsOfService: https://www.netlify.com/legal/terms-of-use/
  title: Netlify's API documentation - split_test
  version: 2.9.0
  x-logo:
    altText: Netlify
    href: https://www.netlify.com/docs/
    url: netlify-logo.png
