paths:
  /users/{username}/settings/billing/actions:
    get:
      summary: Get GitHub Actions billing for a user
      description: |-
        Gets the summary of the free and paid GitHub Actions minutes used.

        Paid minutes only apply to workflows in private repositories that use GitHub-hosted runners. Minutes used is listed for each GitHub-hosted runner operating system. Any job re-runs are also included in the usage. The usage returned includes any minute multipliers for macOS and Windows runners, and is rounded up to the nearest whole minute. For more information, see "[Managing billing for GitHub Actions](https://docs.github.com/github/setting-up-and-managing-billing-and-payments-on-github/managing-billing-for-github-actions)".

        Access tokens must have the `user` scope.
      operationId: billing/get-github-actions-billing-user
      tags:
        - billing
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/reference/billing#get-github-actions-billing-for-a-user
      parameters:
        - $ref: '#/components/parameters/username'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/actions-billing-usage'
              examples:
                default:
                  $ref: '#/components/examples/actions-billing-usage'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: billing
        subcategory: null
  /users/{username}/settings/billing/packages:
    get:
      summary: Get GitHub Packages billing for a user
      description: |-
        Gets the free and paid storage used for GitHub Packages in gigabytes.

        Paid minutes only apply to packages stored for private repositories. For more information, see "[Managing billing for GitHub Packages](https://docs.github.com/github/setting-up-and-managing-billing-and-payments-on-github/managing-billing-for-github-packages)."

        Access tokens must have the `user` scope.
      operationId: billing/get-github-packages-billing-user
      tags:
        - billing
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/reference/billing#get-github-packages-billing-for-a-user
      parameters:
        - $ref: '#/components/parameters/username'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/packages-billing-usage'
              examples:
                default:
                  $ref: '#/components/examples/packages-billing-usage'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: billing
        subcategory: null
  /users/{username}/settings/billing/shared-storage:
    get:
      summary: Get shared storage billing for a user
      description: |-
        Gets the estimated paid and estimated total storage used for GitHub Actions and GitHub Packages.

        Paid minutes only apply to packages stored for private repositories. For more information, see "[Managing billing for GitHub Packages](https://docs.github.com/github/setting-up-and-managing-billing-and-payments-on-github/managing-billing-for-github-packages)."

        Access tokens must have the `user` scope.
      operationId: billing/get-shared-storage-billing-user
      tags:
        - billing
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/reference/billing#get-shared-storage-billing-for-a-user
      parameters:
        - $ref: '#/components/parameters/username'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/combined-billing-usage'
              examples:
                default:
                  $ref: '#/components/examples/combined-billing-usage'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: billing
        subcategory: null
components:
  schemas:
    actions-billing-usage:
      type: object
      properties:
        total_minutes_used:
          type: integer
          description: The sum of the free and paid GitHub Actions minutes used.
        total_paid_minutes_used:
          type: integer
          description: The total paid GitHub Actions minutes used.
        included_minutes:
          type: integer
          description: The amount of free GitHub Actions minutes available.
        minutes_used_breakdown:
          type: object
          properties:
            UBUNTU:
              type: integer
              description: Total minutes used on Ubuntu runner machines.
            MACOS:
              type: integer
              description: Total minutes used on macOS runner machines.
            WINDOWS:
              type: integer
              description: Total minutes used on Windows runner machines.
      required:
        - total_minutes_used
        - total_paid_minutes_used
        - included_minutes
        - minutes_used_breakdown
    packages-billing-usage:
      type: object
      properties:
        total_gigabytes_bandwidth_used:
          type: integer
          description: Sum of the free and paid storage space (GB) for GitHuub Packages.
        total_paid_gigabytes_bandwidth_used:
          type: integer
          description: Total paid storage space (GB) for GitHuub Packages.
        included_gigabytes_bandwidth:
          type: integer
          description: Free storage space (GB) for GitHub Packages.
      required:
        - total_gigabytes_bandwidth_used
        - total_paid_gigabytes_bandwidth_used
        - included_gigabytes_bandwidth
    combined-billing-usage:
      type: object
      properties:
        days_left_in_billing_cycle:
          type: integer
          description: Numbers of days left in billing cycle.
        estimated_paid_storage_for_month:
          type: integer
          description: Estimated storage space (GB) used in billing cycle.
        estimated_storage_for_month:
          type: integer
          description: Estimated sum of free and paid storage space (GB) used in billing cycle.
      required:
        - days_left_in_billing_cycle
        - estimated_paid_storage_for_month
        - estimated_storage_for_month
  parameters:
    username:
      name: username
      in: path
      required: true
      schema:
        type: string
  responses: {}
  securitySchemes: {}
  callbacks: {}
  examples:
    actions-billing-usage:
      value:
        total_minutes_used: 305
        total_paid_minutes_used: 0
        included_minutes: 3000
        minutes_used_breakdown:
          UBUNTU: 205
          MACOS: 10
          WINDOWS: 90
    packages-billing-usage:
      value:
        total_gigabytes_bandwidth_used: 50
        total_paid_gigabytes_bandwidth_used: 40
        included_gigabytes_bandwidth: 10
    combined-billing-usage:
      value:
        days_left_in_billing_cycle: 20
        estimated_paid_storage_for_month: 15
        estimated_storage_for_month: 40
  requestBodies: {}
  headers: {}
  links: {}
  x-stackQL-resources:
    billing:
      id: github.billing.billing
      name: billing
      title: billing
      methods:
        get_github_actions_billing_user:
          operation:
            $ref: '#/paths/~1users~1{username}~1settings~1billing~1actions/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get_github_packages_billing_user:
          operation:
            $ref: '#/paths/~1users~1{username}~1settings~1billing~1packages/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get_shared_storage_billing_user:
          operation:
            $ref: '#/paths/~1users~1{username}~1settings~1billing~1shared-storage/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/billing/methods/get_github_actions_billing_user'
        insert: []
        update: []
        delete: []
openapi: 3.0.3
servers:
  - url: https://api.github.com
tags:
  - name: actions
    description: Endpoints to manage GitHub Actions using the REST API.
  - name: activity
    description: Activity APIs provide access to notifications, subscriptions, and timelines.
  - name: apps
    description: Information for integrations and installations.
  - name: billing
    description: Monitor charges and usage from Actions and Packages.
  - name: checks
    description: Rich interactions with checks run by your integrations.
  - name: code-scanning
    description: Retrieve code scanning alerts from a repository.
  - name: codes-of-conduct
    description: Insight into codes of conduct for your communities.
  - name: codespaces
    description: Endpoints to manage Codespaces using the REST API.
  - name: emojis
    description: List emojis available to use on GitHub.
  - name: enterprise-admin
    description: Administer a GitHub enterprise.
  - name: dependabot
    description: Endpoints to manage Dependabot.
  - name: gists
    description: View, modify your gists.
  - name: git
    description: Raw Git functionality.
  - name: gitignore
    description: View gitignore templates
  - name: interactions
    description: Owner or admin management of users interactions.
  - name: issues
    description: Interact with GitHub Issues.
  - name: licenses
    description: View various OSS licenses.
  - name: markdown
    description: Render GitHub flavored markdown
  - name: meta
    description: Endpoints that give information about the API.
  - name: migrations
    description: Move projects to or from GitHub.
  - name: oauth-authorizations
    description: Manage access of OAuth applications
  - name: orgs
    description: Interact with GitHub Orgs.
  - name: packages
    description: Manage packages for authenticated users and organizations.
  - name: projects
    description: Interact with GitHub Projects.
  - name: pulls
    description: Interact with GitHub Pull Requests.
  - name: rate-limit
    description: Check your current rate limit status
  - name: reactions
    description: Interact with reactions to various GitHub entities.
  - name: repos
    description: Interact with GitHub Repos.
  - name: scim
    description: Provisioning of GitHub organization membership for SCIM-enabled providers.
  - name: search
    description: Look for stuff on GitHub.
  - name: secret-scanning
    description: Retrieve secret scanning alerts from a repository.
  - name: server-statistics
    description: GHES statistics
  - name: teams
    description: Interact with GitHub Teams.
  - name: users
    description: Interact with and view information about users and also current user.
externalDocs:
  description: GitHub v3 REST API
  url: https://docs.github.com/rest/
info:
  version: 1.1.4
  title: GitHub v3 REST API - billing
  description: Monitor charges and usage from Actions and Packages.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
