openapi: 3.0.0
info:
  title: Sumo Logic Dynamic Parsing Rules API
  description: Dynamic parsing rules that extract fields automatically from JSON logs.
  version: 1.0.0
paths:
  /v1/dynamicParsingRules:
    get:
      tags:
        - dynamicParsingRuleManagement
      summary: Get a list of dynamic parsing rules.
      description: Get a list of all dynamic parsing rules. The response is paginated with a default limit of 100 dynamic parsing rules per page.
      operationId: listDynamicParsingRules
      parameters:
        - name: limit
          in: query
          description: Limit the number of dynamic parsing rules returned in the response. The number of dynamic parsing rules returned may be less than the `limit`.
          required: false
          schema:
            maximum: 1000
            minimum: 1
            type: integer
            format: int32
            example: 10
            default: 100
        - name: token
          in: query
          description: Continuation token to get the next page of results. A page object with the next continuation token is returned in the response body. Subsequent GET requests should specify the continuation token to get the next page of results.
          required: false
          schema:
            type: string
            example: 0000000001C51FF7
      responses:
        '200':
          description: A paginated list of dynamic parsing rules.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDynamicRulesResponse'
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
        - dynamicParsingRuleManagement
      summary: Create a new dynamic parsing rule.
      description: Create a new dynamic parsing rule.
      operationId: createDynamicParsingRule
      requestBody:
        description: Information about the new dynamic parsing rule.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DynamicRuleDefinition'
        required: true
      responses:
        '200':
          description: The dynamic parsing rule has been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DynamicRule'
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /v1/dynamicParsingRules/{id}:
    get:
      tags:
        - dynamicParsingRuleManagement
      summary: Get a dynamic parsing rule.
      description: Get a dynamic parsing rule with the given identifier.
      operationId: getDynamicParsingRule
      parameters:
        - name: id
          in: path
          description: Identifier of dynamic parsing rule to return.
          required: true
          schema:
            type: string
            example: 0000000001C41EE4
      responses:
        '200':
          description: Dynamic parsing rule object that was requested.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DynamicRule'
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - dynamicParsingRuleManagement
      summary: Update a dynamic parsing rule.
      description: Update an existing dynamic parsing rule. All properties specified in the request are replaced. Missing properties are set to their default values.
      operationId: updateDynamicParsingRule
      parameters:
        - name: id
          in: path
          description: Identifier of the dynamic parsing rule to update.
          required: true
          schema:
            type: string
            example: 0000000001C41EE4
      requestBody:
        description: Information to update about the dynamic parsing rule.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DynamicRuleDefinition'
        required: true
      responses:
        '200':
          description: The dynamic parsing rule was successfully modified.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DynamicRule'
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - dynamicParsingRuleManagement
      summary: Delete a dynamic parsing rule.
      description: Delete a dynamic parsing rule with the given identifier.
      operationId: deleteDynamicParsingRule
      parameters:
        - name: id
          in: path
          description: Identifier of the dynamic parsing rule to delete.
          required: true
          schema:
            type: string
            example: 0000000001C41EE4
      responses:
        '204':
          description: Dynamic parsing rule was deleted successfully.
        default:
          description: Operation failed with an error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ListDynamicRulesResponse:
      required:
        - data
      type: object
      properties:
        data:
          type: array
          description: List of dynamic parsing rules.
          items:
            $ref: '#/components/schemas/DynamicRule'
        next:
          type: string
          description: Next continuation token.
          example: 0000000001C51FF7
    ErrorResponse:
      required:
        - errors
        - id
      type: object
      properties:
        id:
          type: string
          description: An identifier for the error; this is unique to the specific API request.
          example: IUUQI-DGH5I-TJ045
        errors:
          type: array
          description: A list of one or more causes of the error.
          example:
            - code: auth:password_too_short
              message: Your password was too short.
            - code: auth:password_character_classes
              message: Your password did not contain any non-alphanumeric characters
          items:
            $ref: '#/components/schemas/ErrorDescription'
    DynamicRuleDefinition:
      required:
        - enabled
        - name
        - scope
      type: object
      properties:
        name:
          maxLength: 256
          minLength: 1
          type: string
          description: Name of the dynamic parsing rule. Use a name that makes it easy to identify the rule.
          example: DynamicParsingRule123
        scope:
          maxLength: 2048
          minLength: 1
          type: string
          description: Scope of the dynamic parsing rule. This could be a sourceCategory, sourceHost, or any other metadata that describes the data you want to extract from. Think of the Scope as the first portion of an ad hoc search, before the first pipe ( | ). You'll use the Scope to run a search against the rule.
          example: _sourceHost=127.0.0.1
        enabled:
          type: boolean
          description: Is the dynamic parsing rule enabled.
          example: false
          default: true
    DynamicRule:
      type: object
      required:
        - enabled
        - name
        - scope
        - createdAt
        - createdBy
        - modifiedAt
        - modifiedBy
        - id
        - isSystemRule
      properties:
        name:
          maxLength: 256
          minLength: 1
          type: string
          description: Name of the dynamic parsing rule. Use a name that makes it easy to identify the rule.
          example: DynamicParsingRule123
        scope:
          maxLength: 2048
          minLength: 1
          type: string
          description: Scope of the dynamic parsing rule. This could be a sourceCategory, sourceHost, or any other metadata that describes the data you want to extract from. Think of the Scope as the first portion of an ad hoc search, before the first pipe ( | ). You'll use the Scope to run a search against the rule.
          example: _sourceHost=127.0.0.1
        enabled:
          type: boolean
          description: Is the dynamic parsing rule enabled.
          example: false
          default: true
        createdAt:
          type: string
          description: Creation timestamp in UTC in [RFC3339](https://tools.ietf.org/html/rfc3339) format.
          format: dateTime
        createdBy:
          type: string
          description: Identifier of the user who created the resource.
        modifiedAt:
          type: string
          description: Last modification timestamp in UTC.
          format: dateTime
        modifiedBy:
          type: string
          description: Identifier of the user who last modified the resource.
        id:
          type: string
          description: Unique identifier for the dynamic parsing rule.
          example: 0000000001C41EE4
        isSystemRule:
          type: boolean
          description: Whether the rule has been defined by the system, rather than by a user.
          example: false
    ErrorDescription:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
          description: An error code describing the type of error.
          example: auth:password_too_short
        message:
          type: string
          description: A short English-language description of the error.
          example: Your password was too short.
        detail:
          type: string
          description: An optional fuller English-language description of the error.
          example: Your password was 5 characters long, the minimum length is 12 characters. See http://example.com/password for more information.
        meta:
          type: string
          description: An optional list of metadata about the error. (opaque JSON object)
          example:
            minLength: 12
            actualLength: 5
    Metadata:
      required:
        - createdAt
        - createdBy
        - modifiedAt
        - modifiedBy
      type: object
      properties:
        createdAt:
          type: string
          description: Creation timestamp in UTC in [RFC3339](https://tools.ietf.org/html/rfc3339) format.
          format: dateTime
        createdBy:
          type: string
          description: Identifier of the user who created the resource.
        modifiedAt:
          type: string
          description: Last modification timestamp in UTC.
          format: dateTime
        modifiedBy:
          type: string
          description: Identifier of the user who last modified the resource.
  x-stackQL-resources:
    dynamic_parsing_rules:
      id: sumologic.dynamic_parsing_rules.dynamic_parsing_rules
      name: dynamic_parsing_rules
      title: Dynamic Parsing Rules
      methods:
        list:
          operation:
            $ref: '#/paths/~1v1~1dynamicParsingRules/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.data
          request:
            nativeCasing: camel
        create:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1v1~1dynamicParsingRules/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
          request:
            mediaType: application/json
            nativeCasing: camel
        get:
          operation:
            $ref: '#/paths/~1v1~1dynamicParsingRules~1{id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
          request:
            nativeCasing: camel
        update:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1v1~1dynamicParsingRules~1{id}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
          request:
            mediaType: application/json
            nativeCasing: camel
        delete:
          operation:
            $ref: '#/paths/~1v1~1dynamicParsingRules~1{id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
          request:
            nativeCasing: camel
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/dynamic_parsing_rules/methods/get'
          - $ref: '#/components/x-stackQL-resources/dynamic_parsing_rules/methods/list'
        insert:
          - $ref: '#/components/x-stackQL-resources/dynamic_parsing_rules/methods/create'
        update:
          - $ref: '#/components/x-stackQL-resources/dynamic_parsing_rules/methods/update'
        delete:
          - $ref: '#/components/x-stackQL-resources/dynamic_parsing_rules/methods/delete'
        replace: []
servers:
  - url: https://api.{region}.sumologic.com/api
    description: Sumo Logic deployment API endpoint
    variables:
      region:
        description: Sumo Logic deployment (au, ca, ch, de, eu, fed, in, jp, kr, us1, us2). Resolved from the SUMOLOGIC_ENVIRONMENT environment variable when it is set (x-stackQL-envVar, the same variable the Terraform provider reads); otherwise defaults to us2. A WHERE region = '...' value always takes precedence.
        enum:
          - au
          - ca
          - ch
          - de
          - eu
          - fed
          - in
          - jp
          - kr
          - us1
          - us2
        default: us2
        x-stackQL-envVar: SUMOLOGIC_ENVIRONMENT
x-stackQL-config:
  pagination:
    requestToken:
      key: token
      location: query
    responseToken:
      key: next
      location: body
