openapi: 3.0.0
servers:
  - url: https://{endpoint}
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme), e.g. myaccount.table.cosmos.azure.com:443 - value of the client `endpoint` parameter.
info:
  title: Chat Completions Client
  description: ChatCompletionsClient.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2024-05-01-preview-stackql-generated
  x-serviceAlias: ai_inference
  x-sdkPackage: azure-ai-inference
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ModelType:
      type: string
      enum:
        - embeddings
        - image_generation
        - text_generation
        - image_embeddings
        - audio_generation
        - chat_completion
    ModelInfo:
      type: object
      description: Represents some basic information about the AI model.
      properties:
        model_name:
          type: string
          description: "The name of the AI model. For example: `Phi21`. Required."
        model_type:
          $ref: "#/components/schemas/ModelType"
          description: 'The type of the AI model. A Unique identifier for the profile. Required. Known values are: "embeddings", "image_generation", "text_generation", "image_embeddings", "audio_generation", and "chat_completion".'
        model_provider_name:
          type: string
          description: "The model provider name. For example: `Microsoft Research`. Required."
      required:
        - model_name
        - model_type
        - model_provider_name
    ChatCompletions:
      type: object
      description: Representation of the response data from a chat completions request. Completions support a wide variety of tasks and generate text that continues from or "completes" provided prompt data.
      properties:
        id:
          type: string
          description: A unique identifier associated with this chat completions response. Required.
        created:
          type: string
          format: date-time
          description: The first timestamp associated with generation activity for this completions response, represented as seconds since the beginning of the Unix epoch of 00:00 on 1 Jan 1970. Required.
        model:
          type: string
          description: The model used for the chat completion. Required.
        choices:
          type: array
          items:
            $ref: "#/components/schemas/ChatChoice"
          description: The collection of completions choices associated with this completions response. Generally, `n` choices are generated per provided prompt with a default value of 1. Token limits and other settings may limit the number of choices generated. Required.
        usage:
          $ref: "#/components/schemas/CompletionsUsage"
          description: Usage information for tokens processed and generated as part of this completions operation. Required.
      required:
        - id
        - created
        - model
        - choices
        - usage
    ChatChoice:
      type: object
      description: The representation of a single prompt completion as part of an overall chat completions request. Generally, `n` choices are generated per provided prompt with a default value of 1. Token limits and other settings may limit the number of choices generated.
      properties:
        index:
          type: integer
          description: The ordered index associated with this chat completions choice. Required.
        finish_reason:
          $ref: "#/components/schemas/CompletionsFinishReason"
          description: 'The reason that this chat completions choice completed its generated. Required. Known values are: "stop", "length", "content_filter", and "tool_calls".'
        message:
          $ref: "#/components/schemas/ChatResponseMessage"
          description: The chat message for a given chat completions prompt. Required.
      required:
        - index
        - finish_reason
        - message
    CompletionsFinishReason:
      type: string
      enum:
        - stop
        - length
        - content_filter
        - tool_calls
    ChatResponseMessage:
      type: object
      description: A representation of a chat message as received in a response.
      properties:
        role:
          $ref: "#/components/schemas/ChatRole"
          description: 'The chat role associated with the message. Required. Known values are: "system", "user", "assistant", "tool", and "developer".'
        content:
          type: string
          description: The content of the message. Required.
        tool_calls:
          type: array
          items:
            $ref: "#/components/schemas/ChatCompletionsToolCall"
          description: The tool calls that must be resolved and have their outputs appended to subsequent input messages for the chat completions request to resolve as configured.
      required:
        - role
        - content
    ChatRole:
      type: string
      enum:
        - system
        - user
        - assistant
        - tool
        - developer
    ChatCompletionsToolCall:
      type: object
      description: A function tool call requested by the AI model.
      properties:
        id:
          type: string
          description: The ID of the tool call. Required.
        type:
          type: string
          description: The type of tool call. Currently, only `function` is supported. Required. Default value is "function".
        function:
          $ref: "#/components/schemas/FunctionCall"
          description: The details of the function call requested by the AI model. Required.
      required:
        - id
        - type
        - function
    FunctionCall:
      type: object
      description: The name and arguments of a function that should be called, as generated by the model.
      properties:
        name:
          type: string
          description: The name of the function to call. Required.
        arguments:
          type: string
          description: The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function. Required.
      required:
        - name
        - arguments
    CompletionsUsage:
      type: object
      description: Representation of the token counts processed for a completions request. Counts consider all tokens across prompts, choices, choice alternates, best_of generations, and other consumers.
      properties:
        completion_tokens:
          type: integer
          description: The number of tokens generated across all completions emissions. Required.
        prompt_tokens:
          type: integer
          description: The number of tokens in the provided prompts for the completions request. Required.
        total_tokens:
          type: integer
          description: The total number of tokens processed for the completions request and response. Required.
      required:
        - completion_tokens
        - prompt_tokens
        - total_tokens
    EmbeddingsResult:
      type: object
      description: Representation of the response data from an embeddings request. Embeddings measure the relatedness of text strings and are commonly used for search, clustering, recommendations, and other similar scenarios.
      properties:
        id:
          type: string
          description: Unique identifier for the embeddings result. Required.
        data:
          type: array
          items:
            $ref: "#/components/schemas/EmbeddingItem"
          description: Embedding values for the prompts submitted in the request. Required.
        usage:
          $ref: "#/components/schemas/EmbeddingsUsage"
          description: Usage counts for tokens input using the embeddings API. Required.
        model:
          type: string
          description: The model ID used to generate this result. Required.
      required:
        - id
        - data
        - usage
        - model
    EmbeddingItem:
      type: object
      description: Representation of a single embeddings relatedness comparison.
      properties:
        embedding:
          type: string
          description: List of embedding values for the input prompt. These represent a measurement of the vector-based relatedness of the provided input. Or a base64 encoded string of the embedding vector. Required. Is either a str type or a [float] type.
        index:
          type: integer
          description: Index of the prompt to which the EmbeddingItem corresponds. Required.
      required:
        - embedding
        - index
    EmbeddingsUsage:
      type: object
      description: Measurement of the amount of tokens used in this request and response.
      properties:
        prompt_tokens:
          type: integer
          description: Number of tokens in the request. Required.
        total_tokens:
          type: integer
          description: Total number of tokens transacted in this request/response. Should equal the number of tokens in the request. Required.
      required:
        - prompt_tokens
        - total_tokens
  x-stackQL-resources:
    model_infos:
      id: azure.ai_inference.model_infos
      name: model_infos
      title: model_infos
      methods:
        get_model_info:
          operation:
            $ref: "#/paths/~1info?api-version=2024-05-01-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/model_infos/methods/get_model_info"
        insert: []
        update: []
        delete: []
    completes:
      id: azure.ai_inference.completes
      name: completes
      title: completes
      methods:
        complete:
          operation:
            $ref: "#/paths/~1chat~1completions?api-version=2024-05-01-preview/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    embeds:
      id: azure.ai_inference.embeds
      name: embeds
      title: embeds
      methods:
        embed:
          operation:
            $ref: "#/paths/~1embeddings?api-version=2024-05-01-preview/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /info?api-version=2024-05-01-preview:
    get:
      operationId: ChatCompletionsClient_get_model_info
      description: Returns information about the AI model. The method makes a REST API call to the `/info` route on the given endpoint. This method will only work when using Serverless API or Managed Compute endpoint. It will not work for GitHub Models endpoint or Azure OpenAI endpoint.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ModelInfo"
  /chat/completions?api-version=2024-05-01-preview:
    post:
      operationId: ChatCompletionsClient_complete
      description: Gets chat completions for the provided chat messages. Completions support a wide variety of tasks and generate text that continues from or "completes" provided prompt data. The method makes a REST API call to the `/chat/completions` route on the given endpoint.
      parameters:
        - name: extra-parameters
          in: header
          required: false
          schema:
            type: string
          description: 'Controls what happens if extra parameters, undefined by the REST API, are passed in the JSON request payload. This sets the HTTP request header `extra-parameters`. Known values are: "error", "drop", and "pass-through". Default value is None.'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChatCompletions"
  /embeddings?api-version=2024-05-01-preview:
    post:
      operationId: EmbeddingsClient_embed
      description: Return the embedding vectors for given text prompts. The method makes a REST API call to the `/embeddings` route on the given endpoint.
      parameters:
        - name: extra-parameters
          in: header
          required: false
          schema:
            type: string
          description: 'Controls what happens if extra parameters, undefined by the REST API, are passed in the JSON request payload. This sets the HTTP request header `extra-parameters`. Known values are: "error", "drop", and "pass-through". Default value is None.'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmbeddingsResult"
  /images/embeddings?api-version=2024-05-01-preview:
    post:
      operationId: ImageEmbeddingsClient_embed
      description: Return the embedding vectors for given images. The method makes a REST API call to the `/images/embeddings` route on the given endpoint.
      parameters:
        - name: extra-parameters
          in: header
          required: false
          schema:
            type: string
          description: 'Controls what happens if extra parameters, undefined by the REST API, are passed in the JSON request payload. This sets the HTTP request header `extra-parameters`. Known values are: "error", "drop", and "pass-through". Default value is None.'
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmbeddingsResult"
