openapi: 3.0.0
servers:
  - url: https://{endpoint}/language
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme), e.g. myaccount.table.cosmos.azure.com:443 - value of the client `Endpoint` parameter.
info:
  title: Question Answering Client
  description: QuestionAnsweringClient.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2025-05-15-preview-stackql-generated
  x-serviceAlias: ai_language_questionanswering
  x-sdkPackage: azure-ai-language-questionanswering
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    KnowledgeBaseAnswerContext:
      type: object
      description: Context object with previous QnA's information.
      properties:
        previousQnaId:
          type: integer
          description: Previous turn top answer result QnA ID. Required.
        previousUserQuery:
          type: string
          description: Previous user query.
      required:
        - previousQnaId
    RankerKind:
      type: string
      enum:
        - QuestionOnly
        - Default
    QueryFilters:
      type: object
      description: filters over knowledge base.
      properties:
        metadataFilter:
          $ref: "#/components/schemas/MetadataFilter"
          description: Find QnAs that are associated with the given list of metadata.
        sourceFilter:
          type: array
          items:
            type: string
          description: Find QnAs that are associated with any of the given list of sources in knowledge base.
        logicalOperation:
          $ref: "#/components/schemas/LogicalOperationKind"
          description: 'Logical operation used to join metadata filter with source filter. Known values are: "AND" and "OR".'
    MetadataFilter:
      type: object
      description: Find QnAs that are associated with the given list of metadata.
      properties:
        metadata:
          type: array
          items:
            $ref: "#/components/schemas/MetadataRecord"
          description: Dictionary of string.
        logicalOperation:
          $ref: "#/components/schemas/LogicalOperationKind"
          description: 'Operation used to join metadata filters. Known values are: "AND" and "OR".'
    MetadataRecord:
      type: object
      description: Object to provide the key value pair for each metadata.
      properties:
        key:
          type: string
          description: Metadata Key from Metadata dictionary used in the QnA. Required.
        value:
          type: string
          description: Metadata Value from Metadata dictionary used in the QnA. Required.
      required:
        - key
        - value
    LogicalOperationKind:
      type: string
      enum:
        - AND
        - OR
    ShortAnswerOptions:
      type: object
      description: To configure Answer span prediction feature.
      properties:
        enable:
          type: boolean
          description: Enable or disable Answer Span prediction. Required.
        confidenceScoreThreshold:
          type: number
          description: Minimum threshold score required to include an answer span, value ranges from 0 to 1.
        topAnswersWithSpan:
          type: integer
          description: Number of Top answers to be considered for span prediction from 1 to 10.
      required:
        - enable
    QueryPreferences:
      type: object
      description: Additional properties to fine tune query results.
      properties:
        scorer:
          $ref: "#/components/schemas/Scorer"
          description: 'To specify what scoring algorithm is preferred. Known values are: "Classic", "Transformer", and "Semantic".'
        matchingPolicy:
          $ref: "#/components/schemas/MatchingPolicy"
          description: Policy for controling exact query match behavior.
    Scorer:
      type: string
      enum:
        - Classic
        - Transformer
        - Semantic
    MatchingPolicy:
      type: object
      description: "Specify parameters for query matching. You probably want to use the sub-classes and not this class directly. Known sub-classes are: PrebuiltQueryMatchingPolicy"
      properties:
        kind:
          type: string
          description: Kind of matching policy to be applied. Required. "Prebuilt"
      required:
        - kind
    AnswersResult:
      type: object
      description: Represents List of Question Answers.
      properties:
        answers:
          type: array
          items:
            $ref: "#/components/schemas/KnowledgeBaseAnswer"
          description: Represents Answer Result list.
    KnowledgeBaseAnswer:
      type: object
      description: Represents knowledge base answer.
      properties:
        questions:
          type: array
          items:
            type: string
          description: List of questions associated with the answer.
        answer:
          type: string
          description: Answer text.
        confidenceScore:
          type: number
          description: Answer confidence score, value ranges from 0 to 1.
        id:
          type: integer
          description: ID of the QnA result.
        source:
          type: string
          description: Source of QnA result.
        metadata:
          type: object
          properties: {}
          description: Metadata associated with the answer, useful to categorize or filter question answers.
        dialog:
          $ref: "#/components/schemas/KnowledgeBaseAnswerDialog"
          description: Dialog associated with Answer.
        answerSpan:
          $ref: "#/components/schemas/AnswerSpan"
          description: Answer span object of QnA with respect to user's question.
    KnowledgeBaseAnswerDialog:
      type: object
      description: Dialog associated with Answer.
      properties:
        isContextOnly:
          type: boolean
          description: To mark if a prompt is relevant only with a previous question or not. If true, do not include this QnA as search result for queries without context; otherwise, if false, ignores context and includes this QnA in search result.
        prompts:
          type: array
          items:
            $ref: "#/components/schemas/KnowledgeBaseAnswerPrompt"
          description: List of prompts associated with the answer.
    KnowledgeBaseAnswerPrompt:
      type: object
      description: Prompt for an answer.
      properties:
        displayOrder:
          type: integer
          description: Index of the prompt - used in ordering of the prompts.
        qnaId:
          type: integer
          description: QnA ID corresponding to the prompt.
        displayText:
          type: string
          description: Text displayed to represent a follow up question prompt.
    AnswerSpan:
      type: object
      description: Answer span object of QnA.
      properties:
        text:
          type: string
          description: Predicted text of answer span.
        confidenceScore:
          type: number
          description: Predicted score of answer span, value ranges from 0 to 1.
        offset:
          type: integer
          description: The answer span offset from the start of answer.
        length:
          type: integer
          description: The length of the answer span.
    TextDocument:
      type: object
      description: Represent input text record to be queried.
      properties:
        id:
          type: string
          description: Unique identifier for the text record. Required.
        text:
          type: string
          description: Text contents of the record. Required.
      required:
        - id
        - text
    StringIndexType:
      type: string
      enum:
        - TextElements_v8
        - UnicodeCodePoint
        - Utf16CodeUnit
    AnswersFromTextResult:
      type: object
      description: Represents the answer results.
      properties:
        answers:
          type: array
          items:
            $ref: "#/components/schemas/TextAnswer"
          description: Represents the answer results.
    TextAnswer:
      type: object
      description: Represents answer result.
      properties:
        answer:
          type: string
          description: Answer.
        confidenceScore:
          type: number
          description: answer confidence score, value ranges from 0 to 1.
        id:
          type: string
          description: record ID.
        answerSpan:
          $ref: "#/components/schemas/AnswerSpan"
          description: Answer span object with respect to user's question.
        offset:
          type: integer
          description: The sentence offset from the start of the document.
        length:
          type: integer
          description: The length of the sentence.
  x-stackQL-resources:
    answers:
      id: azure.ai_language_questionanswering.answers
      name: answers
      title: answers
      methods:
        get_answers:
          operation:
            $ref: "#/paths/~1:query-knowledgebases?api-version=2025-05-15-preview/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    answers_from_texts:
      id: azure.ai_language_questionanswering.answers_from_texts
      name: answers_from_texts
      title: answers_from_texts
      methods:
        get_answers_from_text:
          operation:
            $ref: "#/paths/~1:query-text?api-version=2025-05-15-preview/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /:query-knowledgebases?api-version=2025-05-15-preview:
    post:
      operationId: _QuestionAnsweringClient_get_answers
      description: Answers the specified question using your knowledge base.
      parameters:
        - name: projectName
          in: query
          required: true
          schema:
            type: string
          description: The name of the project to use. Required.
        - name: deploymentName
          in: query
          required: true
          schema:
            type: string
          description: The name of the specific deployment of the project to use. Required.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                qnaId:
                  type: integer
                  description: Exact QnA ID to fetch from the knowledge base, this field takes priority over question.
                question:
                  type: string
                  description: User question to query against the knowledge base.
                top:
                  type: integer
                  description: Max number of answers to be returned for the question.
                userId:
                  type: string
                  description: Unique identifier for the user.
                confidenceScoreThreshold:
                  type: number
                  description: Minimum threshold score for answers, value ranges from 0 to 1.
                context:
                  $ref: "#/components/schemas/KnowledgeBaseAnswerContext"
                  description: Context object with previous QnA's information.
                rankerType:
                  $ref: "#/components/schemas/RankerKind"
                  description: 'Type of ranker to be used. Known values are: "QuestionOnly" and "Default".'
                filters:
                  $ref: "#/components/schemas/QueryFilters"
                  description: Filter QnAs based on given metadata list and knowledge base sources.
                answerSpanRequest:
                  $ref: "#/components/schemas/ShortAnswerOptions"
                  description: To configure Answer span prediction feature.
                includeUnstructuredSources:
                  type: boolean
                  description: (Optional) Flag to enable Query over Unstructured Sources.
                queryPreferences:
                  $ref: "#/components/schemas/QueryPreferences"
                  description: To fine tune query results.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnswersResult"
  /:query-text?api-version=2025-05-15-preview:
    post:
      operationId: _QuestionAnsweringClient_get_answers_from_text
      description: Answers the specified question using the provided text in the body.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: User question to query against the given text records. Required.
                records:
                  type: array
                  items:
                    $ref: "#/components/schemas/TextDocument"
                  description: Text records to be searched for given question. Required.
                language:
                  type: string
                  description: Language of the text records. This is BCP-47 representation of a language. For example, use "en" for English; "es" for Spanish etc. If not set, use "en" for English as default.
                stringIndexType:
                  $ref: "#/components/schemas/StringIndexType"
                  description: 'Specifies the method used to interpret string offsets. Defaults to Text Elements (Graphemes) according to Unicode v8.0.0. For additional information see `https://aka.ms/text-analytics-offsets `_. Known values are: "TextElements_v8", "UnicodeCodePoint", and "Utf16CodeUnit".'
              required:
                - question
                - records
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnswersFromTextResult"
