openapi: 3.0.0
servers:
  - url: https://{endpoint}
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme), e.g. myaccount.table.cosmos.azure.com:443 - value of the client `Endpoint` parameter.
info:
  title: Text Translation Client
  description: Azure Translator is a cloud-based, multilingual, neural machine translation service. The Text Translation API enables robust and scalable translation capabilities suitable for diverse applications.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2026-06-06-stackql-generated
  x-serviceAlias: ai_translation_text
  x-sdkPackage: azure-ai-translation-text
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    GetSupportedLanguagesResult:
      type: object
      description: Response for the languages API.
      properties:
        translation:
          type: object
          properties: {}
          description: Languages that support translate API.
        transliteration:
          type: object
          properties: {}
          description: Languages that support transliteration API.
        models:
          type: array
          items:
            type: string
          description: LLM models supported.
    TranslateInputItem:
      type: object
      description: Element containing the text for translation.
      properties:
        text:
          type: string
          description: Text to translate. Required.
        script:
          type: string
          description: Specifies the script of the input text.
        language:
          type: string
          description: "Specifies the language of the input text. Find which languages are available to translate by looking up supported languages using the translation scope. If the language parameter isn't specified, automatic language detection is applied to determine the source language. You must use the language parameter rather than autodetection when using the dynamic dictionary feature. Note: the dynamic dictionary feature is case-sensitive."
        textType:
          $ref: "#/components/schemas/TextType"
          description: 'Defines whether the text being translated is plain text or HTML text. Any HTML needs to be a well-formed, complete element. Possible values are: plain (default) or html. Known values are: "Plain" and "Html".'
        targets:
          type: array
          items:
            $ref: "#/components/schemas/TranslationTarget"
          description: Translation target parameters. Required.
      required:
        - text
        - targets
    TextType:
      type: string
      enum:
        - Plain
        - Html
    TranslationTarget:
      type: object
      description: Target language and translation configuration parameters.
      properties:
        language:
          type: string
          description: Specifies the language of the output text. The target language must be one of the supported languages included in the translation scope. It's possible to translate to multiple languages simultaneously by including multiple string values in the targetsLanguage array. Required.
        script:
          type: string
          description: Specifies the script of the translated text.
        profanityAction:
          $ref: "#/components/schemas/ProfanityAction"
          description: 'Specifies how profanities should be treated in translations. Possible values are: NoAction (default), Marked or Deleted. Known values are: "NoAction", "Marked", and "Deleted".'
        profanityMarker:
          $ref: "#/components/schemas/ProfanityMarker"
          description: 'Specifies how profanities should be marked in translations. Possible values are: Asterisk (default) or Tag. Known values are: "Asterisk" and "Tag".'
        deploymentName:
          type: string
          description: Default is 'general', which uses NMT system. 'abc-inc-gpt-4o', and 'abc-inc-gpt-4o-mini' are examples of deployment names which use GPT-4o uses or GPT-4o-mini model. 'gpt-4o' uses GPT-4o model. '' uses the custom NMT model tuned by customer. 'best' system determines which is the best model to use for the request. This intelligence could be introduced in future. Customer should have deployed it in their resource.
        allowFallback:
          type: boolean
          description: "In the case where a custom system is being used, specifies that the service is allowed to fall back to a general system when a custom system doesn't exist. In the case where a Large Language Model is being used, specifies that the service is allowed to fall back to a Small Language Model if an error occurs. Possible values are: true (default) or false. allowFallback=false specifies that the translation should only use systems trained for the category specified by the request. If a translation for language X to language Y requires chaining through a pivot language E, then all the systems in the chain (X → E and E → Y) will need to be custom and have the same category. If no system is found with the specific category, the request will return a 400 status code. allowFallback=true specifies that the service is allowed to fall back to a general system when a custom system doesn't exist."
        tone:
          $ref: "#/components/schemas/TranslationTone"
          description: 'Desired tone of target translation. Accepted values are formal, informal, or neutral. Known values are: "neutral", "formal", and "informal".'
        gender:
          $ref: "#/components/schemas/TranslationGender"
          description: 'Desired gender of target translation. Accepted values are female, male, or neutral. Known values are: "neutral", "male", and "female".'
        adaptiveDatasetId:
          type: string
          description: Reference dataset ID having sentence pair to generate adaptive customized translation.
        referenceTextPairs:
          type: array
          items:
            $ref: "#/components/schemas/ReferenceTextPair"
          description: Reference text pairs to generate adaptive customized translation.
      required:
        - language
    ProfanityAction:
      type: string
      enum:
        - NoAction
        - Marked
        - Deleted
    ProfanityMarker:
      type: string
      enum:
        - Asterisk
        - Tag
    TranslationTone:
      type: string
      enum:
        - neutral
        - formal
        - informal
    TranslationGender:
      type: string
      enum:
        - neutral
        - male
        - female
    ReferenceTextPair:
      type: object
      description: Reference text pair to generate adaptive customized translation.
      properties:
        source:
          type: string
          description: Source reference sentence. Required.
        target:
          type: string
          description: Target reference sentence. Required.
      required:
        - source
        - target
    TranslationResult:
      type: object
      description: Response for the translation API.
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/TranslatedTextItem"
          description: Array of the translated text elements. Required.
    TranslatedTextItem:
      type: object
      description: Element containing the translated text.
      properties:
        detectedLanguage:
          $ref: "#/components/schemas/DetectedLanguage"
          description: The detectedLanguage property is only present in the result object when language auto-detection is requested.
        translations:
          type: array
          items:
            $ref: "#/components/schemas/TranslationText"
          description: An array of translation results. The size of the array matches the number of target languages specified through the to query parameter. Required.
    DetectedLanguage:
      type: object
      description: An object describing the detected language.
      properties:
        language:
          type: string
          description: A string representing the code of the detected language. Required.
        score:
          type: number
          description: A float value indicating the confidence in the result. The score is between zero and one and a low score indicates a low confidence. Required.
      required:
        - language
        - score
    TranslationText:
      type: object
      description: Translation result.
      properties:
        language:
          type: string
          description: A string representing the language code of the target language. Required.
        sourceCharacters:
          type: integer
          description: An integer indicating the number of characters in the source text string.
        instructionTokens:
          type: integer
          description: An integer indicating the number of tokens used in generating the translated text.
        sourceTokens:
          type: integer
          description: An integer indicating the number of tokens used in the source sentence.
        responseTokens:
          type: integer
          description: An integer indicating the number of tokens used in the translation response.
        targetTokens:
          type: integer
          description: An integer indicating the number of tokens used in the target sentence.
        text:
          type: string
          description: A string giving the translated text. Required.
      required:
        - language
        - text
    InputTextItem:
      type: object
      description: Element containing the text for translation.
      properties:
        text:
          type: string
          description: Text to translate. Required.
      required:
        - text
    TransliterateResult:
      type: object
      description: Response for the transliteration API.
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/TransliteratedText"
          description: Array of transliterated texts. Required.
    TransliteratedText:
      type: object
      description: Transliterated text element.
      properties:
        text:
          type: string
          description: A string which is the result of converting the input string to the output script. Required.
        script:
          type: string
          description: A string specifying the script used in the output. Required.
      required:
        - text
        - script
  x-stackQL-resources:
    supported_languages:
      id: azure.ai_translation_text.supported_languages
      name: supported_languages
      title: supported_languages
      methods:
        get_supported_languages:
          operation:
            $ref: "#/paths/~1languages?api-version=2026-06-06/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/supported_languages/methods/get_supported_languages"
        insert: []
        update: []
        delete: []
    translates:
      id: azure.ai_translation_text.translates
      name: translates
      title: translates
      methods:
        translate:
          operation:
            $ref: "#/paths/~1translate?api-version=2026-06-06/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    transliterates:
      id: azure.ai_translation_text.transliterates
      name: transliterates
      title: transliterates
      methods:
        transliterate:
          operation:
            $ref: "#/paths/~1transliterate?api-version=2026-06-06/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /languages?api-version=2026-06-06:
    get:
      operationId: _TextTranslationClient_get_supported_languages
      description: Gets the set of languages currently supported by other operations of the Translator. Gets the set of languages currently supported by other operations of the Translator.
      parameters:
        - name: X-ClientTraceId
          in: header
          required: false
          schema:
            type: string
          description: A client-generated GUID to uniquely identify the request. Default value is None.
        - name: scope
          in: query
          required: false
          schema:
            type: string
          description: "A comma-separated list of names defining the group of languages to return. Allowed group names are: `translation`, `transliteration` and `dictionary`. If no scope is given, then all groups are returned, which is equivalent to passing `scope=translation,transliteration,dictionary`. To decide which set of supported languages is appropriate for your scenario, see the description of the `response object <#response-body>`_. Default value is None."
        - name: Accept-Language
          in: header
          required: false
          schema:
            type: string
          description: The language to use for user interface strings. Some of the fields in the response are names of languages or names of regions. Use this parameter to define the language in which these names are returned. The language is specified by providing a well-formed BCP 47 language tag. For instance, use the value `fr` to request names in French or use the value `zh-Hant` to request names in Chinese Traditional. Names are provided in the English language when a target language is not specified or when localization is not available. Default value is None.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetSupportedLanguagesResult"
  /translate?api-version=2026-06-06:
    post:
      operationId: _TextTranslationClient_translate
      description: Translate Text. Translate Text.
      parameters:
        - name: X-ClientTraceId
          in: header
          required: false
          schema:
            type: string
          description: A client-generated GUID to uniquely identify the request. Default value is None.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                inputs:
                  type: array
                  items:
                    $ref: "#/components/schemas/TranslateInputItem"
                  description: Array of the input text elements to translate. Required.
              required:
                - inputs
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TranslationResult"
  /transliterate?api-version=2026-06-06:
    post:
      operationId: _TextTranslationClient_transliterate
      description: Transliterate Text. Transliterate Text.
      parameters:
        - name: language
          in: query
          required: true
          schema:
            type: string
          description: Specifies the language of the text to convert from one script to another. Possible languages are listed in the transliteration scope obtained by querying the service for its supported languages. Required.
        - name: fromScript
          in: query
          required: true
          schema:
            type: string
          description: Specifies the script used by the input text. Look up supported languages using the transliteration scope, to find input scripts available for the selected language. Required.
        - name: toScript
          in: query
          required: true
          schema:
            type: string
          description: Specifies the output script. Look up supported languages using the transliteration scope, to find output scripts available for the selected combination of input language and input script. Required.
        - name: X-ClientTraceId
          in: header
          required: false
          schema:
            type: string
          description: A client-generated GUID to uniquely identify the request. Default value is None.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                inputs:
                  type: array
                  items:
                    $ref: "#/components/schemas/InputTextItem"
                  description: Array of the input text elements to transliterate. Required.
              required:
                - inputs
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransliterateResult"
