openapi: 3.0.0
servers:
  - url: https://{endpoint}/computervision
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme), e.g. myaccount.table.cosmos.azure.com:443 - value of the client `endpoint` parameter.
info:
  title: Image Analysis Client
  description: ImageAnalysisClient.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2023-10-01-stackql-generated
  x-serviceAlias: ai_vision_imageanalysis
  x-sdkPackage: azure-ai-vision-imageanalysis
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ImageAnalysisResult:
      type: object
      description: Represents the outcome of an Image Analysis operation.
      properties:
        captionResult:
          $ref: "#/components/schemas/CaptionResult"
          description: The generated phrase that describes the content of the analyzed image.
        denseCaptionsResult:
          $ref: "#/components/schemas/DenseCaptionsResult"
          description: The up to 10 generated phrases, the first describing the content of the whole image, and the others describing the content of different regions of the image.
        metadata:
          $ref: "#/components/schemas/ImageMetadata"
          description: Metadata associated with the analyzed image. Required.
        modelVersion:
          type: string
          description: The cloud AI model used for the analysis. Required.
        objectsResult:
          $ref: "#/components/schemas/ObjectsResult"
          description: A list of detected physical objects in the analyzed image, and their location.
        peopleResult:
          $ref: "#/components/schemas/PeopleResult"
          description: A list of detected people in the analyzed image, and their location.
        readResult:
          $ref: "#/components/schemas/ReadResult"
          description: The extracted printed and hand-written text in the analyze image. Also knows as OCR.
        smartCropsResult:
          $ref: "#/components/schemas/SmartCropsResult"
          description: A list of crop regions at the desired as aspect ratios (if provided) that can be used as image thumbnails. These regions preserve as much content as possible from the analyzed image, with priority given to detected faces.
        tagsResult:
          $ref: "#/components/schemas/TagsResult"
          description: A list of content tags in the analyzed image.
      required:
        - metadata
        - modelVersion
    CaptionResult:
      type: object
      description: Represents a generated phrase that describes the content of the whole image.
      properties:
        confidence:
          type: number
          description: A score, in the range of 0 to 1 (inclusive), representing the confidence that this description is accurate. Higher values indicating higher confidence. Required.
        text:
          type: string
          description: The text of the caption. Required.
      required:
        - confidence
        - text
    DenseCaptionsResult:
      type: object
      description: Represents a list of up to 10 image captions for different regions of the image. The first caption always applies to the whole image.
      properties:
        values:
          type: array
          items:
            $ref: "#/components/schemas/DenseCaption"
          description: The list of image captions. Required.
      required:
        - values
    DenseCaption:
      type: object
      description: Represents a generated phrase that describes the content of the whole image or a region in the image.
      properties:
        confidence:
          type: number
          description: A score, in the range of 0 to 1 (inclusive), representing the confidence that this description is accurate. Higher values indicating higher confidence. Required.
        text:
          type: string
          description: The text of the caption. Required.
        boundingBox:
          $ref: "#/components/schemas/ImageBoundingBox"
          description: The image region of which this caption applies. Required.
      required:
        - confidence
        - text
        - boundingBox
    ImageBoundingBox:
      type: object
      description: A basic rectangle specifying a sub-region of the image.
      properties:
        x:
          type: integer
          description: X-coordinate of the top left point of the area, in pixels. Required.
        "y":
          type: integer
          description: Y-coordinate of the top left point of the area, in pixels. Required.
        w:
          type: integer
          description: Width of the area, in pixels. Required.
        h:
          type: integer
          description: Height of the area, in pixels. Required.
      required:
        - x
        - "y"
        - w
        - h
    ImageMetadata:
      type: object
      description: Metadata associated with the analyzed image.
      properties:
        height:
          type: integer
          description: The height of the image in pixels. Required.
        width:
          type: integer
          description: The width of the image in pixels. Required.
      required:
        - height
        - width
    ObjectsResult:
      type: object
      description: Represents a list of physical object detected in an image and their location.
      properties:
        values:
          type: array
          items:
            $ref: "#/components/schemas/DetectedObject"
          description: A list of physical object detected in an image and their location. Required.
      required:
        - values
    DetectedObject:
      type: object
      description: Represents a physical object detected in an image.
      properties:
        boundingBox:
          $ref: "#/components/schemas/ImageBoundingBox"
          description: A rectangular boundary where the object was detected. Required.
        tags:
          type: array
          items:
            $ref: "#/components/schemas/DetectedTag"
          description: A single-item list containing the object information. Required.
      required:
        - boundingBox
        - tags
    DetectedTag:
      type: object
      description: A content entity observation in the image. A tag can be a physical object, living being, scenery, or action that appear in the image.
      properties:
        confidence:
          type: number
          description: A score, in the range of 0 to 1 (inclusive), representing the confidence that this entity was observed. Higher values indicating higher confidence. Required.
        name:
          type: string
          description: Name of the entity. Required.
      required:
        - confidence
        - name
    PeopleResult:
      type: object
      description: Represents a list of people detected in an image and their location.
      properties:
        values:
          type: array
          items:
            $ref: "#/components/schemas/DetectedPerson"
          description: A list of people detected in an image and their location. Required.
      required:
        - values
    DetectedPerson:
      type: object
      description: Represents a person detected in an image. Readonly variables are only populated by the server, and will be ignored when sending a request.
      properties:
        boundingBox:
          $ref: "#/components/schemas/ImageBoundingBox"
          description: A rectangular boundary where the person was detected. Required.
        confidence:
          type: number
          description: A score, in the range of 0 to 1 (inclusive), representing the confidence that this detection was accurate. Higher values indicating higher confidence. Required.
    ReadResult:
      type: object
      description: The results of a Read (OCR) operation.
      properties:
        blocks:
          type: array
          items:
            $ref: "#/components/schemas/DetectedTextBlock"
          description: A list of text blocks in the image. At the moment only one block is returned, containing all the text detected in the image. Required.
      required:
        - blocks
    DetectedTextBlock:
      type: object
      description: Represents a single block of detected text in the image.
      properties:
        lines:
          type: array
          items:
            $ref: "#/components/schemas/DetectedTextLine"
          description: A list of text lines in this block. Required.
      required:
        - lines
    DetectedTextLine:
      type: object
      description: Represents a single line of text in the image.
      properties:
        text:
          type: string
          description: Text content of the detected text line. Required.
        boundingPolygon:
          type: array
          items:
            $ref: "#/components/schemas/ImagePoint"
          description: A bounding polygon around the text line. At the moment only quadrilaterals are supported (represented by 4 image points). Required.
        words:
          type: array
          items:
            $ref: "#/components/schemas/DetectedTextWord"
          description: A list of words in this line. Required.
      required:
        - text
        - boundingPolygon
        - words
    ImagePoint:
      type: object
      description: Represents the coordinates of a single pixel in the image.
      properties:
        x:
          type: integer
          description: The horizontal x-coordinate of this point, in pixels. Zero values corresponds to the left-most pixels in the image. Required.
        "y":
          type: integer
          description: The vertical y-coordinate of this point, in pixels. Zero values corresponds to the top-most pixels in the image. Required.
      required:
        - x
        - "y"
    DetectedTextWord:
      type: object
      description: A word object consisting of a contiguous sequence of characters. For non-space delimited languages, such as Chinese, Japanese, and Korean, each character is represented as its own word.
      properties:
        text:
          type: string
          description: Text content of the word. Required.
        boundingPolygon:
          type: array
          items:
            $ref: "#/components/schemas/ImagePoint"
          description: A bounding polygon around the word. At the moment only quadrilaterals are supported (represented by 4 image points). Required.
        confidence:
          type: number
          description: The level of confidence that the word was detected. Confidence scores span the range of 0.0 to 1.0 (inclusive), with higher values indicating a higher confidence of detection. Required.
      required:
        - text
        - boundingPolygon
        - confidence
    SmartCropsResult:
      type: object
      description: Smart cropping result. A list of crop regions at the desired as aspect ratios (if provided) that can be used as image thumbnails. These regions preserve as much content as possible from the analyzed image, with priority given to detected faces.
      properties:
        values:
          type: array
          items:
            $ref: "#/components/schemas/CropRegion"
          description: A list of crop regions. Required.
      required:
        - values
    CropRegion:
      type: object
      description: A region at the desired aspect ratio that can be used as image thumbnail. The region preserves as much content as possible from the analyzed image, with priority given to detected faces.
      properties:
        aspectRatio:
          type: number
          description: The aspect ratio of the crop region. Aspect ratio is calculated by dividing the width of the region in pixels by its height in pixels. The aspect ratio will be in the range 0.75 to 1.8 (inclusive) if provided by the developer during the analyze call. Otherwise, it will be in the range 0.5 to 2.0 (inclusive). Required.
        boundingBox:
          $ref: "#/components/schemas/ImageBoundingBox"
          description: The bounding box of the region. Required.
      required:
        - aspectRatio
        - boundingBox
    TagsResult:
      type: object
      description: A list of entities observed in the image. Tags can be physical objects, living being, scenery, or actions that appear in the image.
      properties:
        values:
          type: array
          items:
            $ref: "#/components/schemas/DetectedTag"
          description: A list of tags. Required.
      required:
        - values
  x-stackQL-resources:
    analyze_from_image_datas:
      id: azure.ai_vision_imageanalysis.analyze_from_image_datas
      name: analyze_from_image_datas
      title: analyze_from_image_datas
      methods:
        analyze_from_image_data:
          operation:
            $ref: "#/paths/~1imageanalysis:analyze?api-version=2023-10-01/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /imageanalysis:analyze?api-version=2023-10-01:
    post:
      operationId: ImageAnalysisClient_analyze_from_image_data
      description: Performs a single Image Analysis operation.
      parameters:
        - name: features
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
          description: "A list of visual features to analyze. Seven visual features are supported: Caption, DenseCaptions, Read (OCR), Tags, Objects, SmartCrops, and People. At least one visual feature must be specified. Required."
        - name: language
          in: query
          required: false
          schema:
            type: string
          description: The desired language for result generation (a two-letter language code). If this option is not specified, the default value 'en' is used (English). See https://aka.ms/cv-languages for a list of supported languages. Default value is None.
        - name: gender-neutral-caption
          in: query
          required: false
          schema:
            type: boolean
          description: "Boolean flag for enabling gender-neutral captioning for Caption and Dense Captions features. By default captions may contain gender terms (for example: 'man', 'woman', or 'boy', 'girl'). If you set this to \"true\", those will be replaced with gender-neutral terms (for example: 'person' or 'child'). Default value is None."
        - name: smartcrops-aspect-ratios
          in: query
          required: false
          schema:
            type: array
            items:
              type: number
          description: A list of aspect ratios to use for smart cropping. Aspect ratios are calculated by dividing the target crop width in pixels by the height in pixels. Supported values are between 0.75 and 1.8 (inclusive). If this parameter is not specified, the service will return one crop region with an aspect ratio it sees fit between 0.5 and 2.0 (inclusive). Default value is None.
        - name: model-version
          in: query
          required: false
          schema:
            type: string
          description: "The version of cloud AI-model used for analysis. The format is the following: 'latest' (default value) or 'YYYY-MM-DD' or 'YYYY-MM-DD-preview', where 'YYYY', 'MM', 'DD' are the year, month and day associated with the model. This is not commonly set, as the default always gives the latest AI model with recent improvements. If however you would like to make sure analysis results do not change over time, set this value to a specific model version. Default value is None."
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImageAnalysisResult"
