openapi: 3.0.0
servers:
  - url: https://management.azure.com/
info:
  title: Carbon Optimization Mgmt Client
  description: Carbon Report Resource Provider query API.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2025-04-01-stackql-generated
  x-serviceAlias: carbonoptimization
  x-sdkPackage: azure-mgmt-carbonoptimization
  x-plane: mgmt
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    DateRange:
      type: object
      description: Date range to be used with QueryParameter, it should be within 12 months between start and end date. In certain cases, start and end dates must be the same date.
      properties:
        start:
          type: string
          format: date
          description: Start date parameter in yyyy-MM-01 format. Only the first day of each month is accepted. Required.
        end:
          type: string
          format: date
          description: End date parameter in yyyy-MM-01 format. Only the first day of each month is accepted. Required.
      required:
        - start
        - end
    EmissionScopeEnum:
      type: string
      enum:
        - Scope1
        - Scope2
        - Scope3
    CarbonEmissionData:
      type: object
      description: "The basic response for different query report, all query report result will have these information. You probably want to use the sub-classes and not this class directly. Known sub-classes are: CarbonEmissionItemDetailData, CarbonEmissionMonthlySummaryData, CarbonEmissionOverallSummaryData, ResourceGroupCarbonEmissionItemDetailData, ResourceGroupCarbonEmissionTopItemMonthlySummaryData, ResourceGroupCarbonEmissionTopItemsSummaryData, ResourceCarbonEmissionItemDetailData, ResourceCarbonEmissionTopItemMonthlySummaryData, ResourceCarbonEmissionTopItemsSummaryData, CarbonEmissionTopItemMonthlySummaryData, CarbonEmissionTopItemsSummaryData"
      properties:
        dataType:
          type: string
          description: 'The data type of the query result, indicating the format of the returned response. Required. Known values are: "OverallSummaryData", "MonthlySummaryData", "TopItemsSummaryData", "ResourceTopItemsSummaryData", "ResourceGroupTopItemsSummaryData", "TopItemsMonthlySummaryData", "ResourceTopItemsMonthlySummaryData", "ResourceGroupTopItemsMonthlySummaryData", "ItemDetailsData", "ResourceItemDetailsData", and "ResourceGroupItemDetailsData".'
        latestMonthEmissions:
          type: number
          description: Total carbon emissions for the specified query parameters, measured in kgCO2E. This value represents total emissions over the specified date range (e.g., March-June). Required.
        previousMonthEmissions:
          type: number
          description: Total carbon emissions for the previous month’s date range, which is the same period as the specified date range but shifted left by one month (e.g., if the specified range is March - June, the previous month’s range will be Feb - May). The value is measured in kgCO2E. Required.
        monthOverMonthEmissionsChangeRatio:
          type: number
          description: "The percentage change in carbon emissions between the current and previous DateRange. This is calculated as: (latestMonthEmissions - previousMonthEmissions) / previousMonthEmissions."
        monthlyEmissionsChangeValue:
          type: number
          description: "The change in carbon emissions between the current and previous period, calculated as: latestMonthEmissions - previousMonthEmissions."
      required:
        - dataType
        - latestMonthEmissions
        - previousMonthEmissions
    CarbonEmissionDataListResult:
      type: object
      description: List of carbon emission results.
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/CarbonEmissionData"
          description: The CarbonEmissionData items on this page. Required.
        skipToken:
          type: string
          description: The pagination token to fetch next page data, it's null or empty if it doesn't have next page data.
        subscriptionAccessDecisionList:
          type: array
          items:
            $ref: "#/components/schemas/SubscriptionAccessDecision"
          description: The access decision list for each input subscription.
      required:
        - value
    SubscriptionAccessDecision:
      type: object
      description: Access Decision for each Subscription.
      properties:
        subscriptionId:
          type: string
          description: Id of Subscription. Required.
        decision:
          $ref: "#/components/schemas/AccessDecisionEnum"
          description: 'Access decision to subscription. Required. Known values are: "Allowed" and "Denied".'
        denialReason:
          type: string
          description: The reason why access request got denied.
      required:
        - subscriptionId
        - decision
    AccessDecisionEnum:
      type: string
      enum:
        - Allowed
        - Denied
    CarbonEmissionDataAvailableDateRange:
      type: object
      description: Response for available date range of carbon emission data.
      properties:
        startDate:
          type: string
          description: Start date parameter, format is yyyy-MM-dd. Required.
        endDate:
          type: string
          description: End date parameter, format is yyyy-MM-dd. Required.
      required:
        - startDate
        - endDate
    OperationDisplay:
      type: object
      description: Localized display information for and operation.
      properties:
        provider:
          type: string
          description: The localized friendly form of the resource provider name, e.g. "Microsoft Monitoring Insights" or "Microsoft Compute".
        resource:
          type: string
          description: The localized friendly name of the resource type related to this operation. E.g. "Virtual Machines" or "Job Schedule Collections".
        operation:
          type: string
          description: The concise, localized friendly name for the operation; suitable for dropdowns. E.g. "Create or Update Virtual Machine", "Restart Virtual Machine".
        description:
          type: string
          description: The short, localized friendly description of the operation; suitable for tool tips and detailed views.
    Origin:
      type: string
      enum:
        - user
        - system
        - user,system
    ActionType:
      type: string
      enum:
        - Internal
    Operation:
      type: object
      description: REST API Operation.
      properties:
        name:
          type: string
          description: 'The name of the operation, as per Resource-Based Access Control (RBAC). Examples: "Microsoft.Compute/virtualMachines/write", "Microsoft.Compute/virtualMachines/capture/action".'
        isDataAction:
          type: boolean
          description: Whether the operation applies to data-plane. This is "true" for data-plane operations and "false" for Azure Resource Manager/control-plane operations.
        display:
          $ref: "#/components/schemas/OperationDisplay"
          description: Localized display information for this particular operation.
        origin:
          $ref: "#/components/schemas/Origin"
          description: 'The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit logs UX. Default value is "user,system". Known values are: "user", "system", and "user,system".'
        actionType:
          $ref: "#/components/schemas/ActionType"
          description: Extensible enum. Indicates the action type. "Internal" refers to actions that are for internal only APIs. "Internal"
    PagedOperation:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/Operation"
        nextLink:
          type: string
  x-stackQL-resources:
    carbon_service:
      id: azure.carbonoptimization.carbon_service
      name: carbon_service
      title: carbon_service
      methods:
        query_carbon_emission_reports:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.Carbon~1carbonEmissionReports?api-version=2025-04-01/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
        query_carbon_emission_data_available_date_range:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.Carbon~1queryCarbonEmissionDataAvailableDateRange?api-version=2025-04-01/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    operations:
      id: azure.carbonoptimization.operations
      name: operations
      title: operations
      methods:
        list:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.Carbon~1operations?api-version=2025-04-01/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.value
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/operations/methods/list"
        insert: []
        update: []
        delete: []
paths:
  /providers/Microsoft.Carbon/carbonEmissionReports?api-version=2025-04-01:
    post:
      operationId: CarbonService_query_carbon_emission_reports
      description: API for Carbon Emissions Reports.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reportType:
                  type: string
                  description: 'The ReportType requested for carbon emissions data. Required. Specifies how data is aggregated and displayed in the output, as explained in the ReportTypeEnum. Required. Known values are: "OverallSummaryReport", "MonthlySummaryReport", "TopItemsSummaryReport", "TopItemsMonthlySummaryReport", and "ItemDetailsReport".'
                dateRange:
                  $ref: "#/components/schemas/DateRange"
                  description: "The start and end dates for carbon emissions data. Required. For ItemDetailsReport and TopItemsSummaryReport, only one month of data is supported at a time, so start and end dates should be equal within DateRange (e.g., start: 2024-06-01 and end: 2024-06-01). Required."
                subscriptionList:
                  type: array
                  items:
                    type: string
                  description: List of subscription IDs for which carbon emissions data is requested. Required. Each subscription ID should be in lowercase format. The max length of list is 100. Required.
                resourceGroupUrlList:
                  type: array
                  items:
                    type: string
                  description: List of resource group URLs for carbon emissions data. Optional. Each URL must follow the format '/subscriptions/{subscriptionId}/resourcegroups/{resourceGroup}', and should be in all lowercase.
                resourceTypeList:
                  type: array
                  items:
                    type: string
                  description: List of resource types for carbon emissions data. Optional. Each resource type should be specified in lowercase, following the format 'microsoft.{service}/{resourceType}', e.g., 'microsoft.storage/storageaccounts'.
                locationList:
                  type: array
                  items:
                    type: string
                  description: List of locations(Azure Region Display Name) for carbon emissions data, with each location specified in lowercase (e.g., 'east us'). Optional. You can use the command 'az account list-locations -o table' to find Azure Region Display Names.
                carbonScopeList:
                  type: array
                  items:
                    $ref: "#/components/schemas/EmissionScopeEnum"
                  description: List of carbon emission scopes. Required. Accepts one or more values from EmissionScopeEnum (e.g., Scope1, Scope2, Scope3) in list form. The output will include the total emissions for the specified scopes. Required.
              required:
                - reportType
                - dateRange
                - subscriptionList
                - carbonScopeList
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CarbonEmissionDataListResult"
  /providers/Microsoft.Carbon/queryCarbonEmissionDataAvailableDateRange?api-version=2025-04-01:
    post:
      operationId: CarbonService_query_carbon_emission_data_available_date_range
      description: API for query carbon emission data available date range.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CarbonEmissionDataAvailableDateRange"
  /providers/Microsoft.Carbon/operations?api-version=2025-04-01:
    get:
      operationId: carbonoptimization_list
      description: List the operations for the provider.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedOperation"
