openapi: 3.0.0
servers:
  - url: https://{endpoint}
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme), e.g. myaccount.table.cosmos.azure.com:443 - value of the client `endpoint` parameter.
info:
  title: Email Client
  description: Azure Communication Email Service.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2025-09-01-stackql-generated
  x-serviceAlias: communication_email
  x-sdkPackage: azure-communication-email
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas: {}
  x-stackQL-resources:
    sends:
      id: azure.communication_email.sends
      name: sends
      title: sends
      methods:
        send:
          operation:
            $ref: "#/paths/~1emails:send?api-version=2025-09-01/post"
          response:
            openAPIDocKey: "204"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /emails:send?api-version=2025-09-01:
    post:
      operationId: _EmailClient_begin_send
      description: Queues an email message to be sent to one or more recipients. Queues an email message to be sent to one or more recipients.
      parameters:
        - name: Operation-Id
          in: header
          required: false
          schema:
            type: string
          description: This is the ID provided by the customer to identify the long running operation. If an ID is not provided by the customer, the service will generate one. Default value is None.
      responses:
        "204":
          description: Success (no content / accepted)
