openapi: 3.0.0
servers:
  - url: https://{endpoint}
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme).
info:
  title: Sms Client
  description: A client to interact with the AzureCommunicationService Sms gateway. This client provides operations to send an SMS via a phone number.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2021-03-07-stackql-generated
  x-serviceAlias: communication_sms
  x-sdkPackage: azure-communication-sms
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    SmsRecipient:
      type: object
      description: Recipient details for sending SMS messages. All required parameters must be populated in order to send to Azure.
      properties:
        to:
          type: string
        repeatabilityRequestId:
          type: string
        repeatabilityFirstSent:
          type: string
      required:
        - to
    SmsSendOptions:
      type: object
      description: Optional configuration for sending SMS messages. All required parameters must be populated in order to send to Azure.
      properties:
        enableDeliveryReport:
          type: boolean
        tag:
          type: string
      required:
        - enableDeliveryReport
    SmsSendResponse:
      type: object
      description: Response for a successful or multi status send Sms request. All required parameters must be populated in order to send to Azure.
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/SmsSendResponseItem"
      required:
        - value
    SmsSendResponseItem:
      type: object
      description: Response for a single recipient. All required parameters must be populated in order to send to Azure.
      properties:
        to:
          type: string
        messageId:
          type: string
        httpStatusCode:
          type: integer
        repeatabilityResult:
          type: string
        successful:
          type: boolean
        errorMessage:
          type: string
      required:
        - to
        - httpStatusCode
        - successful
  x-stackQL-resources:
    sms:
      id: azure.communication_sms.sms
      name: sms
      title: sms
      methods:
        send:
          operation:
            $ref: "#/paths/~1sms?api-version=2021-03-07/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /sms?api-version=2021-03-07:
    post:
      operationId: Sms_send
      description: Sends a SMS message from a phone number that belongs to the authenticated account. Sends a SMS message from a phone number that belongs to the authenticated account.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                smsRecipients:
                  type: array
                  items:
                    $ref: "#/components/schemas/SmsRecipient"
                message:
                  type: string
                smsSendOptions:
                  $ref: "#/components/schemas/SmsSendOptions"
              required:
                - from
                - smsRecipients
                - message
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SmsSendResponse"
