openapi: 3.0.0
servers:
  - url: https://{endpoint}
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme), e.g. myaccount.table.cosmos.azure.com:443 - value of the client `endpoint` parameter.
info:
  title: Notification Messages Client
  description: NotificationMessagesClient.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2025-01-15-preview-stackql-generated
  x-serviceAlias: communication_messages
  x-sdkPackage: azure-communication-messages
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    MessageTemplateStatus:
      type: string
      enum:
        - approved
        - rejected
        - pending
        - paused
    MessageTemplateItem:
      type: object
      description: "The message template as returned from the service. You probably want to use the sub-classes and not this class directly. Known sub-classes are: WhatsAppMessageTemplateItem Readonly variables are only populated by the server, and will be ignored when sending a request."
      properties:
        name:
          type: string
          description: The template's name. Required.
        language:
          type: string
          description: The template's language, in the ISO 639 format, consist of a two-letter language code followed by an optional two-letter country code, e.g., 'en' or 'en_US'. Required.
        status:
          $ref: "#/components/schemas/MessageTemplateStatus"
          description: 'The aggregated template status. Required. Known values are: "approved", "rejected", "pending", and "paused".'
        kind:
          type: string
          description: The type discriminator describing a template type. Required. "whatsApp"
      required:
        - language
        - status
        - kind
    PagedMessageTemplateItem:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/MessageTemplateItem"
        nextLink:
          type: string
    SendMessageResult:
      type: object
      description: Result of the send message operation.
      properties:
        receipts:
          type: array
          items:
            $ref: "#/components/schemas/MessageReceipt"
          description: Receipts of the send message operation. Required.
      required:
        - receipts
    MessageReceipt:
      type: object
      description: Receipt of the sending one message.
      properties:
        messageId:
          type: string
          description: The message id. Required.
        to:
          type: string
          description: The native external platform user identifier of the recipient. Required.
      required:
        - messageId
        - to
  x-stackQL-resources:
    templates:
      id: azure.communication_messages.templates
      name: templates
      title: templates
      methods:
        list_templates:
          operation:
            $ref: "#/paths/~1messages~1channels~1{channel_id}~1templates?api-version=2025-01-15-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.value
          request:
            nativeCasing: camel
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/templates/methods/list_templates"
        insert: []
        update: []
        delete: []
    sends:
      id: azure.communication_messages.sends
      name: sends
      title: sends
      methods:
        send:
          operation:
            $ref: "#/paths/~1messages~1notifications:send?api-version=2025-01-15-preview/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    download_medias:
      id: azure.communication_messages.download_medias
      name: download_medias
      title: download_medias
      methods:
        download_media:
          operation:
            $ref: "#/paths/~1messages~1streams~1{id}?api-version=2025-01-15-preview/get"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /messages/channels/{channel_id}/templates?api-version=2025-01-15-preview:
    get:
      operationId: MessageTemplateClient_list_templates
      description: List all templates for given Azure Communication Services channel.
      parameters:
        - name: channel_id
          in: path
          required: true
          schema:
            type: string
          description: The registration ID of the channel. Required.
        - name: maxpagesize
          in: query
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedMessageTemplateItem"
  /messages/notifications:send?api-version=2025-01-15-preview:
    post:
      operationId: NotificationMessagesClient_send
      description: Sends a notification message from Business to User.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                channelRegistrationId:
                  type: string
                  description: The Channel Registration ID for the Business Identifier. Required.
                to:
                  type: array
                  items:
                    type: string
                  description: The native external platform user identifiers of the recipient. Required.
                kind:
                  type: string
                  description: 'The type discriminator describing a notification type. Required. Known values are: "text", "image", "image_v0", "document", "video", "audio", "template", "sticker", "reaction", and "interactive".'
              required:
                - channelRegistrationId
                - to
                - kind
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SendMessageResult"
  /messages/streams/{id}?api-version=2025-01-15-preview:
    get:
      operationId: NotificationMessagesClient_download_media
      description: Download the Media payload from a User to Business message.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The stream ID. Required.
      responses:
        "200":
          description: Success
