openapi: 3.0.0
servers:
  - url: https://management.azure.com/
info:
  title: Azure Compute Recommender
  description: Spot placement and VM sizing recommendations.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2025-06-05-stackql-generated
  x-serviceAlias: compute_recommender
  x-sdkPackage: azure-mgmt-computerecommender
  x-plane: mgmt
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    OperationDisplay:
      type: object
      description: Localized display information for and operation.
      properties:
        provider:
          type: string
          description: The localized friendly form of the resource provider name, e.g. "Microsoft Monitoring Insights" or "Microsoft Compute".
        resource:
          type: string
          description: The localized friendly name of the resource type related to this operation. E.g. "Virtual Machines" or "Job Schedule Collections".
        operation:
          type: string
          description: The concise, localized friendly name for the operation; suitable for dropdowns. E.g. "Create or Update Virtual Machine", "Restart Virtual Machine".
        description:
          type: string
          description: The short, localized friendly description of the operation; suitable for tool tips and detailed views.
    Origin:
      type: string
      enum:
        - user
        - system
        - user,system
    ActionType:
      type: string
      enum:
        - Internal
    Operation:
      type: object
      description: REST API Operation.
      properties:
        name:
          type: string
          description: 'The name of the operation, as per Resource-Based Access Control (RBAC). Examples: "Microsoft.Compute/virtualMachines/write", "Microsoft.Compute/virtualMachines/capture/action".'
        isDataAction:
          type: boolean
          description: Whether the operation applies to data-plane. This is "true" for data-plane operations and "false" for Azure Resource Manager/control-plane operations.
        display:
          $ref: "#/components/schemas/OperationDisplay"
          description: Localized display information for this particular operation.
        origin:
          $ref: "#/components/schemas/Origin"
          description: 'The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit logs UX. Default value is "user,system". Known values are: "user", "system", and "user,system".'
        actionType:
          $ref: "#/components/schemas/ActionType"
          description: Extensible enum. Indicates the action type. "Internal" refers to actions that are for internal only APIs. "Internal"
    PagedOperation:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/Operation"
        nextLink:
          type: string
    SystemData:
      type: object
      description: Metadata pertaining to creation and last modification of the resource.
      properties:
        createdBy:
          type: string
          description: The identity that created the resource.
        createdByType:
          $ref: "#/components/schemas/CreatedByType"
          description: 'The type of identity that created the resource. Known values are: "User", "Application", "ManagedIdentity", and "Key".'
        createdAt:
          type: string
          format: date-time
          description: The timestamp of resource creation (UTC).
        lastModifiedBy:
          type: string
          description: The identity that last modified the resource.
        lastModifiedByType:
          $ref: "#/components/schemas/CreatedByType"
          description: 'The type of identity that last modified the resource. Known values are: "User", "Application", "ManagedIdentity", and "Key".'
        lastModifiedAt:
          type: string
          format: date-time
          description: The timestamp of resource last modification (UTC).
    CreatedByType:
      type: string
      enum:
        - User
        - Application
        - ManagedIdentity
        - Key
    DiagnosticProperties:
      type: object
      description: Contains additional properties of a diagnostic.
      properties:
        supportedResourceTypes:
          type: array
          items:
            type: string
          description: Describes what are the supported resource types for a diagnostic.
    ComputeDiagnosticBaseFlattened:
      type: object
      description: Flattened view of ComputeDiagnosticBase ('properties' hoisted to the top level).
      properties:
        id:
          type: string
          description: Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
        name:
          type: string
          description: The name of the resource.
        type:
          type: string
          description: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts".
        systemData:
          $ref: "#/components/schemas/SystemData"
          description: Azure Resource Manager metadata containing createdBy and modifiedBy information.
        supportedResourceTypes:
          type: array
          items:
            type: string
          description: Describes what are the supported resource types for a diagnostic.
    ResourceSize:
      type: object
      description: SpotPlacementRecommender API response.
      properties:
        sku:
          type: string
          description: The resource's CRP virtual machine SKU size.
    SpotPlacementScoresResponse:
      type: object
      description: SpotPlacementScores API response.
      properties:
        desiredLocations:
          type: array
          items:
            type: string
          description: The desired regions.
        desiredSizes:
          type: array
          items:
            $ref: "#/components/schemas/ResourceSize"
          description: The desired virtual machine SKU sizes.
        desiredCount:
          type: integer
          description: Desired instance count per region/zone based on the scope.
        availabilityZones:
          type: boolean
          description: Defines if the scope is zonal or regional.
        placementScores:
          type: array
          items:
            $ref: "#/components/schemas/PlacementScore"
          description: A placement score indicating the likelihood of successfully allocating the specified Spot VM(s), as well as the expected lifetimes of the Spot VM(s) after allocation.
    PlacementScore:
      type: object
      description: The spot placement score for sku/region/zone combination.
      properties:
        sku:
          type: string
          description: The resource's CRP virtual machine SKU size.
        region:
          type: string
          description: The region.
        availabilityZone:
          type: string
          description: The availability zone.
        score:
          type: string
          description: A placement score indicating the likelihood of successfully allocating the specified Spot VM(s), as well as the expected lifetimes of the Spot VM(s) after allocation.
        isQuotaAvailable:
          type: boolean
          description: Whether the desired quota is available.
  x-stackQL-resources:
    operations:
      id: azure.compute_recommender.operations
      name: operations
      title: operations
      methods:
        list:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.Compute~1operations?api-version=2025-06-05/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.value
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/operations/methods/list"
        insert: []
        update: []
        delete: []
    spot_placement_scores:
      id: azure.compute_recommender.spot_placement_scores
      name: spot_placement_scores
      title: spot_placement_scores
      methods:
        get:
          operation:
            $ref: "#/paths/~1subscriptions~1{subscription_id}~1providers~1Microsoft.Compute~1locations~1{location}~1placementScores~1spot?api-version=2025-06-05/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            overrideMediaType: application/json
            transform:
              type: golang_template_json_v0.3.0
              body: '{{ $row := . }}{ {{ $p := index $row "properties" }}{{ if eq (kindOf $p) "map" }}{{ range $k, $v := $p }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}{{ end }}{{ range $k, $v := $row }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}"_flattened": true }'
        post:
          operation:
            $ref: "#/paths/~1subscriptions~1{subscription_id}~1providers~1Microsoft.Compute~1locations~1{location}~1placementScores~1spot~1generate?api-version=2025-06-05/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/spot_placement_scores/methods/get"
        insert: []
        update: []
        delete: []
paths:
  /providers/Microsoft.Compute/operations?api-version=2025-06-05:
    get:
      operationId: computerecommender_list
      description: List the operations for the provider.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedOperation"
  /subscriptions/{subscription_id}/providers/Microsoft.Compute/locations/{location}/placementScores/spot?api-version=2025-06-05:
    get:
      operationId: SpotPlacementScores_get
      description: Gets Spot Placement Scores metadata.
      parameters:
        - name: location
          in: path
          required: true
          schema:
            type: string
          description: The name of the Azure region. Required.
        - name: subscription_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ComputeDiagnosticBaseFlattened"
  /subscriptions/{subscription_id}/providers/Microsoft.Compute/locations/{location}/placementScores/spot/generate?api-version=2025-06-05:
    post:
      operationId: SpotPlacementScores_post
      description: Generates placement scores for Spot VM skus.
      parameters:
        - name: location
          in: path
          required: true
          schema:
            type: string
          description: The name of the Azure region. Required.
        - name: subscription_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                desiredLocations:
                  type: array
                  items:
                    type: string
                  description: The desired regions.
                desiredSizes:
                  type: array
                  items:
                    $ref: "#/components/schemas/ResourceSize"
                  description: The desired virtual machine SKU sizes.
                desiredCount:
                  type: integer
                  description: Desired instance count per region/zone based on the scope.
                availabilityZones:
                  type: boolean
                  description: Defines if the scope is zonal or regional.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpotPlacementScoresResponse"
