openapi: 3.0.0
servers:
  - url: https://{certificate_endpoint}
    variables:
      certificate_endpoint:
        default: ""
        description: The service endpoint host (no scheme), e.g. myaccount.table.cosmos.azure.com:443 - value of the client `certificateEndpoint` parameter.
info:
  title: Azure Confidential Ledger - Identity Certificates (Data Plane)
  description: Retrieve ledger identity TLS certificates.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2024-12-09-preview-stackql-generated
  x-serviceAlias: confidential_ledger_certificate
  x-sdkPackage: azure-confidentialledger-certificate
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    LedgerIdentityInformation:
      type: object
      description: Contains the information about a Confidential Ledger.
      properties:
        ledgerId:
          type: string
          description: Id for the ledger.
        ledgerTlsCertificate:
          type: string
          description: PEM-encoded certificate used for TLS by the Confidential Ledger. Required.
      required:
        - ledgerTlsCertificate
  x-stackQL-resources:
    ledger_identities:
      id: azure.confidential_ledger_certificate.ledger_identities
      name: ledger_identities
      title: ledger_identities
      methods:
        get_ledger_identity:
          operation:
            $ref: "#/paths/~1ledgerIdentity~1{ledger_id}?api-version=2024-12-09-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/ledger_identities/methods/get_ledger_identity"
        insert: []
        update: []
        delete: []
paths:
  /ledgerIdentity/{ledger_id}?api-version=2024-12-09-preview:
    get:
      operationId: _ConfidentialLedgerCertificateClient_get_ledger_identity
      description: Gets identity information for a Confidential Ledger instance. Gets identity information for a Confidential Ledger instance.
      parameters:
        - name: ledger_id
          in: path
          required: true
          schema:
            type: string
          description: Id of the Confidential Ledger instance to get information for. Required.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LedgerIdentityInformation"
