openapi: 3.0.0
servers:
  - url: https://management.azure.com/
info:
  title: Azure Data Catalog
  description: The Data Catalog REST API is a REST-based API that provides programmatic access to Data Catalog resources to register, annotate, and search data assets programmatically. Azure Data Catalog is a cloud-based service that you can use to register and discover enterprise data assets. The service gives you capabilities that enable any user, from analysts to data scientists to developers, to register, discover, understand, and consume data assets.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2024-10-11-stackql-generated
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  parameters:
    SubscriptionIdParameter:
      name: subscriptionId
      in: path
      description: Gets subscription credentials which uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
      required: true
      schema:
        type: string
    ApiVersionParameter:
      name: api-version
      in: query
      description: Client Api Version.
      required: false
      schema:
        type: string
    ResourceGroupNameParameter:
      name: resourceGroupName
      in: path
      description: The name of the resource group within the user's subscription. The name is case insensitive.
      required: true
      x-ms-parameter-location: method
      schema:
        pattern: ^[-\w\._\(\)]+$
        minLength: 1
        maxLength: 90
        type: string
    CatalogNameParameter:
      name: catalogName
      in: path
      description: The name of the data catalog in the specified subscription and resource group.
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
  schemas:
    ADCCatalogsListResult:
      properties:
        value:
          type: array
          items:
            $ref: '#/components/schemas/ADCCatalog'
          description: the list of Azure Data Catalogs.
      description: The response from the List Azure Data Catalog operation.
      type: object
    Resource:
      description: The Resource model definition.
      properties:
        id:
          readOnly: true
          type: string
          description: Resource Id
        name:
          readOnly: true
          type: string
          description: Resource name
        type:
          readOnly: true
          type: string
          description: Resource type
        location:
          type: string
          description: Resource location
          x-ms-mutability:
            - create
            - read
        tags:
          type: object
          additionalProperties:
            type: string
          description: Resource tags
        etag:
          type: string
          description: Resource etag
      x-ms-azure-resource: true
      type: object
    ADCCatalog:
      description: Azure Data Catalog.
      properties:
        properties:
          x-ms-client-flatten: true
          $ref: '#/components/schemas/ADCCatalogProperties'
          description: Azure Data Catalog properties.
        id:
          readOnly: true
          type: string
          description: Resource Id
        name:
          readOnly: true
          type: string
          description: Resource name
        type:
          readOnly: true
          type: string
          description: Resource type
        location:
          type: string
          description: Resource location
          x-ms-mutability:
            - create
            - read
        tags:
          type: object
          additionalProperties:
            type: string
          description: Resource tags
        etag:
          type: string
          description: Resource etag
      type: object
    ADCCatalogProperties:
      description: Properties of the data catalog.
      properties:
        sku:
          type: string
          description: Azure data catalog SKU.
          enum:
            - Free
            - Standard
          x-ms-enum:
            name: SkuType
            modelAsString: true
        units:
          type: integer
          description: Azure data catalog units.
        admins:
          type: array
          items:
            $ref: '#/components/schemas/Principals'
          description: Azure data catalog admin list.
          x-ms-identifiers:
            - objectId
        users:
          type: array
          items:
            $ref: '#/components/schemas/Principals'
          description: Azure data catalog user list.
          x-ms-identifiers:
            - objectId
        successfullyProvisioned:
          type: boolean
          description: Azure data catalog provision status.
        enableAutomaticUnitAdjustment:
          type: boolean
          description: Automatic unit adjustment enabled or not.
      type: object
    Principals:
      description: User principals.
      properties:
        upn:
          type: string
          description: UPN of the user.
        objectId:
          type: string
          description: Object Id for the user
      type: object
    OperationEntityListResult:
      description: The list of Azure data catalog service operation response.
      type: object
      properties:
        value:
          description: The list of operations.
          type: array
          items:
            $ref: '#/components/schemas/OperationEntity'
          x-ms-identifiers:
            - name
    OperationEntity:
      description: The operation supported by Azure Data Catalog Service.
      type: object
      properties:
        name:
          description: 'Operation name: {provider}/{resource}/{operation}.'
          type: string
        display:
          $ref: '#/components/schemas/OperationDisplayInfo'
          description: The operation supported by Azure Data Catalog Service.
    OperationDisplayInfo:
      description: The operation supported by Azure Data Catalog Service.
      type: object
      properties:
        description:
          description: The description of the operation.
          type: string
        operation:
          description: The action that users can perform, based on their permission level.
          type: string
        provider:
          description: 'Service provider: Azure Data Catalog Service.'
          type: string
        resource:
          description: Resource on which the operation is performed.
          type: string
  x-stackQL-resources:
    adc_operations:
      id: azure.data_catalog.adc_operations
      name: adc_operations
      title: adc_operations
      methods:
        list:
          operation:
            $ref: '#/paths/~1providers~1Microsoft.DataCatalog~1operations?api-version=2016-03-30/get'
            operationId: ADCOperations_List
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            schemaRef: OperationEntityListResult
            objectKey: $.value
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/adc_operations/methods/list'
        insert: []
        update: []
        replace: []
        delete: []
    adc_catalogst_by_resource_groups:
      id: azure.data_catalog.adc_catalogst_by_resource_groups
      name: adc_catalogst_by_resource_groups
      title: adc_catalogst_by_resource_groups
      methods:
        list:
          operation:
            $ref: '#/paths/~1subscriptions~1{subscriptionId}~1resourceGroups~1{resourceGroupName}~1providers~1Microsoft.DataCatalog~1catalogs?api-version=2016-03-30/get'
            operationId: ADCCatalogstByResourceGroup_List
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            schemaRef: ADCCatalogsListResult
            objectKey: $.value
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/adc_catalogst_by_resource_groups/methods/list'
        insert: []
        update: []
        replace: []
        delete: []
    adc_catalogs:
      id: azure.data_catalog.adc_catalogs
      name: adc_catalogs
      title: adc_catalogs
      methods:
        create_or_update:
          operation:
            $ref: '#/paths/~1subscriptions~1{subscriptionId}~1resourceGroups~1{resourceGroupName}~1providers~1Microsoft.DataCatalog~1catalogs~1{catalogName}?api-version=2016-03-30/put'
            operationId: ADCCatalogs_CreateOrUpdate
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            schemaRef: ADCCatalog
        get:
          operation:
            $ref: '#/paths/~1subscriptions~1{subscriptionId}~1resourceGroups~1{resourceGroupName}~1providers~1Microsoft.DataCatalog~1catalogs~1{catalogName}?api-version=2016-03-30/get'
            operationId: ADCCatalogs_Get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            schemaRef: ADCCatalog
        delete:
          operation:
            $ref: '#/paths/~1subscriptions~1{subscriptionId}~1resourceGroups~1{resourceGroupName}~1providers~1Microsoft.DataCatalog~1catalogs~1{catalogName}?api-version=2016-03-30/delete'
            operationId: ADCCatalogs_Delete
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        update:
          operation:
            $ref: '#/paths/~1subscriptions~1{subscriptionId}~1resourceGroups~1{resourceGroupName}~1providers~1Microsoft.DataCatalog~1catalogs~1{catalogName}?api-version=2016-03-30/patch'
            operationId: ADCCatalogs_Update
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            schemaRef: ADCCatalog
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/adc_catalogs/methods/get'
        insert:
          - $ref: '#/components/x-stackQL-resources/adc_catalogs/methods/create_or_update'
        update:
          - $ref: '#/components/x-stackQL-resources/adc_catalogs/methods/update'
        replace: []
        delete:
          - $ref: '#/components/x-stackQL-resources/adc_catalogs/methods/delete'
    vw_adc_catalogs:
      id: azure.data_catalog.vw_adc_catalogs
      name: vw_adc_catalogs
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              id as id,
              name as name,
              location as location,
              type as type,
              tags as tags,
              etag as etag,
              JSON_EXTRACT(properties, '$.sku') as "sku",
              JSON_EXTRACT(properties, '$.units') as "units",
              JSON_EXTRACT(properties, '$.admins') as "admins",
              JSON_EXTRACT(properties, '$.users') as "users",
              JSON_EXTRACT(properties, '$.successfullyProvisioned') as "successfully_provisioned",
              JSON_EXTRACT(properties, '$.enableAutomaticUnitAdjustment') as "enable_automatic_unit_adjustment",
              subscriptionId,
              resourceGroupName,
              catalogName
              FROM azure.data_catalog.adc_catalogs
              WHERE subscriptionId = 'replace-me' AND resourceGroupName = 'replace-me' AND catalogName = 'replace-me';
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                id as id,
                name as name,
                location as location,
                type as type,
                tags as tags,
                etag as etag,
                json_extract_path_text(properties, '$.sku') as "sku",
                json_extract_path_text(properties, '$.units') as "units",
                json_extract_path_text(properties, '$.admins') as "admins",
                json_extract_path_text(properties, '$.users') as "users",
                json_extract_path_text(properties, '$.successfullyProvisioned') as "successfully_provisioned",
                json_extract_path_text(properties, '$.enableAutomaticUnitAdjustment') as "enable_automatic_unit_adjustment",
                subscriptionId,
                resourceGroupName,
                catalogName
                FROM azure.data_catalog.adc_catalogs
                WHERE subscriptionId = 'replace-me' AND resourceGroupName = 'replace-me' AND catalogName = 'replace-me';
paths:
  /providers/Microsoft.DataCatalog/operations?api-version=2016-03-30:
    get:
      tags:
        - AzureDataCatalog
      description: Lists all the available Azure Data Catalog service operations.
      operationId: ADCOperations_List
      parameters: []
      responses:
        '200':
          description: HTTP 200 (OK) if the operation was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationEntityListResult'
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataCatalog/catalogs?api-version=2016-03-30:
    get:
      tags:
        - AzureDataCatalog
      operationId: ADCCatalogstByResourceGroup_List
      summary: List catalogs in Resource Group (GET Resources)
      description: The List catalogs in Resource Group operation lists all the Azure Data Catalogs available under the given resource group.
      parameters:
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/ResourceGroupNameParameter'
      responses:
        '200':
          description: HTTP 200 (OK) if the operation was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ADCCatalogsListResult'
      x-ms-original-operationId: ADCCatalogs_ListtByResourceGroup
  /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataCatalog/catalogs/{catalogName}?api-version=2016-03-30:
    put:
      tags:
        - AzureDataCatalog
      operationId: ADCCatalogs_CreateOrUpdate
      summary: Create or Update Azure Data Catalog service (PUT Resource)
      description: The Create Azure Data Catalog service operation creates a new data catalog service with the specified parameters. If the specific service already exists, then any patchable properties will be updated and any immutable properties will remain unchanged.
      parameters:
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/ResourceGroupNameParameter'
        - $ref: '#/components/parameters/CatalogNameParameter'
      requestBody:
        description: Properties supplied to the Create or Update a data catalog.
        required: true
        x-ms-requestBody-name: properties
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ADCCatalog'
      responses:
        '200':
          description: HTTP 200 (OK) if the operation was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ADCCatalog'
        '201':
          description: HTTP 201 (Created) if the operation completed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ADCCatalog'
    get:
      tags:
        - AzureDataCatalog
      operationId: ADCCatalogs_Get
      summary: Get Azure Data Catalog service (GET Resources)
      description: The Get Azure Data Catalog Service operation retrieves a json representation of the data catalog.
      parameters:
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/ResourceGroupNameParameter'
        - $ref: '#/components/parameters/CatalogNameParameter'
      responses:
        '200':
          description: HTTP 200 (OK) if the operation was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ADCCatalog'
    delete:
      tags:
        - AzureDataCatalog
      operationId: ADCCatalogs_Delete
      summary: Delete Azure Data Catalog Service (DELETE Resource)
      x-ms-long-running-operation: true
      description: The Delete Azure Data Catalog Service operation deletes an existing data catalog.
      parameters:
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/ResourceGroupNameParameter'
        - $ref: '#/components/parameters/CatalogNameParameter'
      responses:
        '200':
          description: OK. An existing annotation was updated.
        '202':
          description: Accepted. Delete is asynchronous. In this case, the caller needs to read the Location header for an URL to poll. That URL will continue to return 202 until the operation is complete. When it stops returning 202, the response it gives back is the result of the DELETE operation.
        '204':
          description: No Content (didn't exist).
    patch:
      tags:
        - AzureDataCatalog
      operationId: ADCCatalogs_Update
      summary: Update Azure Data Catalog Service (PATCH Resource)
      description: The Update Azure Data Catalog Service operation can be used to update the existing deployment. The update call only supports the properties listed in the PATCH body.
      parameters:
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/ResourceGroupNameParameter'
        - $ref: '#/components/parameters/CatalogNameParameter'
      requestBody:
        description: Properties supplied to the Update a data catalog.
        required: true
        x-ms-requestBody-name: properties
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ADCCatalog'
      responses:
        '200':
          description: HTTP 200 (OK) if the operation was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ADCCatalog'
