openapi: 3.0.0
servers:
  - url: https://management.azure.com/
info:
  title: Azure Extended Zones
  description: Register and enumerate Azure Extended Zones for latency-sensitive workloads.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2024-04-01-preview-stackql-generated
  x-serviceAlias: edge_zones
  x-sdkPackage: azure-mgmt-edgezones
  x-plane: mgmt
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    SystemData:
      type: object
      description: Metadata pertaining to creation and last modification of the resource.
      properties:
        createdBy:
          type: string
          description: The identity that created the resource.
        createdByType:
          $ref: "#/components/schemas/CreatedByType"
          description: 'The type of identity that created the resource. Known values are: "User", "Application", "ManagedIdentity", and "Key".'
        createdAt:
          type: string
          format: date-time
          description: The timestamp of resource creation (UTC).
        lastModifiedBy:
          type: string
          description: The identity that last modified the resource.
        lastModifiedByType:
          $ref: "#/components/schemas/CreatedByType"
          description: 'The type of identity that last modified the resource. Known values are: "User", "Application", "ManagedIdentity", and "Key".'
        lastModifiedAt:
          type: string
          format: date-time
          description: The timestamp of resource last modification (UTC).
    CreatedByType:
      type: string
      enum:
        - User
        - Application
        - ManagedIdentity
        - Key
    ExtendedZoneProperties:
      type: object
      description: The properties of an Extended Zone resource.
      properties:
        provisioningState:
          $ref: "#/components/schemas/ProvisioningState"
          description: 'Status of the last operation performed by the subscription on the Edge Zone resource. Known values are: "Succeeded", "Failed", "Canceled", "Provisioning", "Updating", "Deleting", and "Accepted".'
        registrationState:
          $ref: "#/components/schemas/RegistrationState"
          description: 'Indicates the Azure Extended Zone registration’s approval status. Known values are: "NotRegistered", "PendingRegister", "Registered", and "PendingUnregister".'
        displayName:
          type: string
          description: Display name of the Azure Extended Zone. Required.
        regionalDisplayName:
          type: string
          description: Regional display name of the Azure Extended Zone. Required.
        regionType:
          type: string
          description: Type of region for the Azure Extended Zone. Required.
        regionCategory:
          type: string
          description: Category of region for the Azure Extended Zone. Required.
        geography:
          type: string
          description: Geography of the Azure Extended Zone. Required.
        geographyGroup:
          type: string
          description: The Geography Group of the Azure Extended Zone. Required.
        longitude:
          type: string
          description: The Longitude of the Azure Extended Zone. Required.
        latitude:
          type: string
          description: The Latitude of the Azure Extended Zone. Required.
        homeLocation:
          type: string
          description: The Home Location of the Azure Extended Zone. Required.
    ProvisioningState:
      type: string
      enum:
        - Succeeded
        - Failed
        - Canceled
        - Provisioning
        - Updating
        - Deleting
        - Accepted
    RegistrationState:
      type: string
      enum:
        - NotRegistered
        - PendingRegister
        - Registered
        - PendingUnregister
    ExtendedZoneFlattened:
      type: object
      description: Flattened view of ExtendedZone ('properties' hoisted to the top level).
      properties:
        id:
          type: string
          description: Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
        name:
          type: string
          description: The name of the resource.
        type:
          type: string
          description: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts".
        systemData:
          $ref: "#/components/schemas/SystemData"
          description: Azure Resource Manager metadata containing createdBy and modifiedBy information.
        provisioningState:
          $ref: "#/components/schemas/ProvisioningState"
          description: 'Status of the last operation performed by the subscription on the Edge Zone resource. Known values are: "Succeeded", "Failed", "Canceled", "Provisioning", "Updating", "Deleting", and "Accepted".'
        registrationState:
          $ref: "#/components/schemas/RegistrationState"
          description: 'Indicates the Azure Extended Zone registration’s approval status. Known values are: "NotRegistered", "PendingRegister", "Registered", and "PendingUnregister".'
        displayName:
          type: string
          description: Display name of the Azure Extended Zone. Required.
        regionalDisplayName:
          type: string
          description: Regional display name of the Azure Extended Zone. Required.
        regionType:
          type: string
          description: Type of region for the Azure Extended Zone. Required.
        regionCategory:
          type: string
          description: Category of region for the Azure Extended Zone. Required.
        geography:
          type: string
          description: Geography of the Azure Extended Zone. Required.
        geographyGroup:
          type: string
          description: The Geography Group of the Azure Extended Zone. Required.
        longitude:
          type: string
          description: The Longitude of the Azure Extended Zone. Required.
        latitude:
          type: string
          description: The Latitude of the Azure Extended Zone. Required.
        homeLocation:
          type: string
          description: The Home Location of the Azure Extended Zone. Required.
    PagedExtendedZoneFlattened:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/ExtendedZoneFlattened"
        nextLink:
          type: string
    ExtendedZone:
      type: object
      description: Resource that represents an Azure Extended Zone available to a subscription for registering and unregistering.
      properties:
        id:
          type: string
          description: Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
        name:
          type: string
          description: The name of the resource.
        type:
          type: string
          description: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts".
        systemData:
          $ref: "#/components/schemas/SystemData"
          description: Azure Resource Manager metadata containing createdBy and modifiedBy information.
        properties:
          $ref: "#/components/schemas/ExtendedZoneProperties"
          description: The resource-specific properties for this resource.
    OperationDisplay:
      type: object
      description: Localized display information for and operation.
      properties:
        provider:
          type: string
          description: The localized friendly form of the resource provider name, e.g. "Microsoft Monitoring Insights" or "Microsoft Compute".
        resource:
          type: string
          description: The localized friendly name of the resource type related to this operation. E.g. "Virtual Machines" or "Job Schedule Collections".
        operation:
          type: string
          description: The concise, localized friendly name for the operation; suitable for dropdowns. E.g. "Create or Update Virtual Machine", "Restart Virtual Machine".
        description:
          type: string
          description: The short, localized friendly description of the operation; suitable for tool tips and detailed views.
    Origin:
      type: string
      enum:
        - user
        - system
        - user,system
    ActionType:
      type: string
      enum:
        - Internal
    Operation:
      type: object
      description: Details of a REST API operation, returned from the Resource Provider Operations API.
      properties:
        name:
          type: string
          description: 'The name of the operation, as per Resource-Based Access Control (RBAC). Examples: "Microsoft.Compute/virtualMachines/write", "Microsoft.Compute/virtualMachines/capture/action".'
        isDataAction:
          type: boolean
          description: Whether the operation applies to data-plane. This is "true" for data-plane operations and "false" for Azure Resource Manager/control-plane operations.
        display:
          $ref: "#/components/schemas/OperationDisplay"
          description: Localized display information for this particular operation.
        origin:
          $ref: "#/components/schemas/Origin"
          description: 'The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit logs UX. Default value is "user,system". Known values are: "user", "system", and "user,system".'
        actionType:
          $ref: "#/components/schemas/ActionType"
          description: Extensible enum. Indicates the action type. "Internal" refers to actions that are for internal only APIs. "Internal"
    PagedOperation:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/Operation"
        nextLink:
          type: string
  x-stackQL-resources:
    extended_zones:
      id: azure.edge_zones.extended_zones
      name: extended_zones
      title: extended_zones
      methods:
        get:
          operation:
            $ref: "#/paths/~1subscriptions~1{subscription_id}~1providers~1Microsoft.EdgeZones~1extendedZones~1{extended_zone_name}?api-version=2024-04-01-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            overrideMediaType: application/json
            transform:
              type: golang_template_json_v0.3.0
              body: '{{ $row := . }}{ {{ $p := index $row "properties" }}{{ if eq (kindOf $p) "map" }}{{ range $k, $v := $p }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}{{ end }}{{ range $k, $v := $row }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}"_flattened": true }'
        list_by_subscription:
          operation:
            $ref: "#/paths/~1subscriptions~1{subscription_id}~1providers~1Microsoft.EdgeZones~1extendedZones?api-version=2024-04-01-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.value
            overrideMediaType: application/json
            transform:
              type: golang_template_json_v0.3.0
              body: |-
                {"value": [
                {{- range $i, $row := index . "value" }}{{ if $i }},{{ end }}
                  { {{ $p := index $row "properties" }}{{ if eq (kindOf $p) "map" }}{{ range $k, $v := $p }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}{{ end }}{{ range $k, $v := $row }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}"_flattened": true }
                {{- end }}
                ], "nextLink": {{ toJson (index . "nextLink") }}}
        register:
          operation:
            $ref: "#/paths/~1subscriptions~1{subscription_id}~1providers~1Microsoft.EdgeZones~1extendedZones~1{extended_zone_name}~1register?api-version=2024-04-01-preview/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        unregister:
          operation:
            $ref: "#/paths/~1subscriptions~1{subscription_id}~1providers~1Microsoft.EdgeZones~1extendedZones~1{extended_zone_name}~1unregister?api-version=2024-04-01-preview/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/extended_zones/methods/get"
          - $ref: "#/components/x-stackQL-resources/extended_zones/methods/list_by_subscription"
        insert: []
        update: []
        delete: []
    operations:
      id: azure.edge_zones.operations
      name: operations
      title: operations
      methods:
        list:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.EdgeZones~1operations?api-version=2024-04-01-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.value
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/operations/methods/list"
        insert: []
        update: []
        delete: []
paths:
  /subscriptions/{subscription_id}/providers/Microsoft.EdgeZones/extendedZones/{extended_zone_name}?api-version=2024-04-01-preview:
    get:
      operationId: ExtendedZones_get
      description: Gets an Azure Extended Zone for a subscription.
      parameters:
        - name: extended_zone_name
          in: path
          required: true
          schema:
            type: string
          description: The name of the ExtendedZone. Required.
        - name: subscription_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExtendedZoneFlattened"
  /subscriptions/{subscription_id}/providers/Microsoft.EdgeZones/extendedZones?api-version=2024-04-01-preview:
    get:
      operationId: ExtendedZones_list_by_subscription
      description: Lists the Azure Extended Zones available to a subscription.
      parameters:
        - name: subscription_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedExtendedZoneFlattened"
  /subscriptions/{subscription_id}/providers/Microsoft.EdgeZones/extendedZones/{extended_zone_name}/register?api-version=2024-04-01-preview:
    post:
      operationId: ExtendedZones_register
      description: Registers a subscription for an Extended Zone.
      parameters:
        - name: extended_zone_name
          in: path
          required: true
          schema:
            type: string
          description: The name of the ExtendedZone. Required.
        - name: subscription_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExtendedZone"
  /subscriptions/{subscription_id}/providers/Microsoft.EdgeZones/extendedZones/{extended_zone_name}/unregister?api-version=2024-04-01-preview:
    post:
      operationId: ExtendedZones_unregister
      description: Unregisters a subscription for an Extended Zone.
      parameters:
        - name: extended_zone_name
          in: path
          required: true
          schema:
            type: string
          description: The name of the ExtendedZone. Required.
        - name: subscription_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExtendedZone"
  /providers/Microsoft.EdgeZones/operations?api-version=2024-04-01-preview:
    get:
      operationId: edgezones_list
      description: List the operations for the provider.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedOperation"
