openapi: 3.0.0
servers:
  - url: https://{endpoint}
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme).
info:
  title: Device Provisioning Client
  description: API for service operations with the Azure IoT Hub Device Provisioning Service.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2021-10-01-stackql-generated
  x-serviceAlias: iot_deviceprovisioning
  x-sdkPackage: azure-iot-deviceprovisioning
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas: {}
  x-stackQL-resources:
    device_registration_state:
      id: azure.iot_deviceprovisioning.device_registration_state
      name: device_registration_state
      title: device_registration_state
      methods:
        get_raw:
          operation:
            $ref: "#/paths/~1registrations~1{id}?api-version=2021-10-01/get"
          response:
            openAPIDocKey: "200"
        delete:
          operation:
            $ref: "#/paths/~1registrations~1{id}?api-version=2021-10-01/delete"
          response:
            openAPIDocKey: "204"
        query:
          operation:
            $ref: "#/paths/~1registrations~1{id}~1query?api-version=2021-10-01/post"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete:
          - $ref: "#/components/x-stackQL-resources/device_registration_state/methods/delete"
    enrollment_group:
      id: azure.iot_deviceprovisioning.enrollment_group
      name: enrollment_group
      title: enrollment_group
      methods:
        get_raw:
          operation:
            $ref: "#/paths/~1enrollmentGroups~1{id}?api-version=2021-10-01/get"
          response:
            openAPIDocKey: "200"
        create_or_update:
          operation:
            $ref: "#/paths/~1enrollmentGroups~1{id}?api-version=2021-10-01/put"
          response:
            openAPIDocKey: "200"
        delete:
          operation:
            $ref: "#/paths/~1enrollmentGroups~1{id}?api-version=2021-10-01/delete"
          response:
            openAPIDocKey: "204"
        get_attestation_mechanism:
          operation:
            $ref: "#/paths/~1enrollmentGroups~1{id}~1attestationmechanism?api-version=2021-10-01/post"
          response:
            openAPIDocKey: "200"
        run_bulk_operation:
          operation:
            $ref: "#/paths/~1enrollmentGroups?api-version=2021-10-01/post"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert:
          - $ref: "#/components/x-stackQL-resources/enrollment_group/methods/create_or_update"
        update: []
        replace:
          - $ref: "#/components/x-stackQL-resources/enrollment_group/methods/create_or_update"
        delete:
          - $ref: "#/components/x-stackQL-resources/enrollment_group/methods/delete"
    enrollment:
      id: azure.iot_deviceprovisioning.enrollment
      name: enrollment
      title: enrollment
      methods:
        get_raw:
          operation:
            $ref: "#/paths/~1enrollments~1{id}?api-version=2021-10-01/get"
          response:
            openAPIDocKey: "200"
        create_or_update:
          operation:
            $ref: "#/paths/~1enrollments~1{id}?api-version=2021-10-01/put"
          response:
            openAPIDocKey: "200"
        delete:
          operation:
            $ref: "#/paths/~1enrollments~1{id}?api-version=2021-10-01/delete"
          response:
            openAPIDocKey: "204"
        get_attestation_mechanism:
          operation:
            $ref: "#/paths/~1enrollments~1{id}~1attestationmechanism?api-version=2021-10-01/post"
          response:
            openAPIDocKey: "200"
        run_bulk_operation:
          operation:
            $ref: "#/paths/~1enrollments?api-version=2021-10-01/post"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert:
          - $ref: "#/components/x-stackQL-resources/enrollment/methods/create_or_update"
        update: []
        replace:
          - $ref: "#/components/x-stackQL-resources/enrollment/methods/create_or_update"
        delete:
          - $ref: "#/components/x-stackQL-resources/enrollment/methods/delete"
paths:
  /registrations/{id}?api-version=2021-10-01:
    get:
      operationId: DeviceRegistrationState_get
      description: Gets the device registration state. Gets the device registration state.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Registration ID. Required.
      responses:
        "200":
          description: Success
    delete:
      operationId: DeviceRegistrationState_delete
      description: Deletes the device registration. Deletes the device registration.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Registration ID. Required.
        - name: If-Match
          in: header
          required: false
          schema:
            type: string
          description: The ETag of the registration status record. Default value is None.
      responses:
        "204":
          description: Success (no content / accepted)
  /registrations/{id}/query?api-version=2021-10-01:
    post:
      operationId: DeviceRegistrationState_query
      description: Gets the registration state of devices in this enrollmentGroup. Gets the registration state of devices in this enrollmentGroup.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Enrollment group ID. Required.
        - name: x-ms-max-item-count
          in: header
          required: false
          schema:
            type: integer
          description: pageSize. Default value is None.
        - name: x-ms-continuation
          in: header
          required: false
          schema:
            type: string
          description: continuation token. Default value is None.
      responses:
        "200":
          description: Success
  /enrollmentGroups/{id}?api-version=2021-10-01:
    get:
      operationId: EnrollmentGroup_get
      description: Get a device enrollment group. Get a device enrollment group.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Enrollment group ID. Required.
      responses:
        "200":
          description: Success
    put:
      operationId: EnrollmentGroup_create_or_update
      description: Create or update a device enrollment group. Create or update a device enrollment group.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Enrollment group ID. Required.
        - name: If-Match
          in: header
          required: false
          schema:
            type: string
          description: The ETag of the enrollment record. Default value is None.
      responses:
        "200":
          description: Success
    delete:
      operationId: EnrollmentGroup_delete
      description: Delete a device enrollment group. Delete a device enrollment group.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Enrollment group ID. Required.
        - name: If-Match
          in: header
          required: false
          schema:
            type: string
          description: The ETag of the enrollment group record. Default value is None.
      responses:
        "204":
          description: Success (no content / accepted)
  /enrollmentGroups/{id}/attestationmechanism?api-version=2021-10-01:
    post:
      operationId: EnrollmentGroup_get_attestation_mechanism
      description: Get the attestation mechanism in the device enrollment group record. Get the attestation mechanism in the device enrollment group record.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Enrollment group ID. Required.
      responses:
        "200":
          description: Success
  /enrollmentGroups?api-version=2021-10-01:
    post:
      operationId: EnrollmentGroup_run_bulk_operation
      description: Bulk device enrollment group operation with maximum of 10 groups. Bulk device enrollment group operation with maximum of 10 groups.
      parameters: []
      responses:
        "200":
          description: Success
  /enrollments/{id}?api-version=2021-10-01:
    get:
      operationId: Enrollment_get
      description: Get a device enrollment record. Get a device enrollment record.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "This id is used to uniquely identify a device registration of an enrollment. A case-insensitive string (up to 128 characters long) of alphanumeric characters plus certain special characters : . _ -. No special characters allowed at start or end. Required."
      responses:
        "200":
          description: Success
    put:
      operationId: Enrollment_create_or_update
      description: Create or update a device enrollment record. Create or update a device enrollment record.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "This id is used to uniquely identify a device registration of an enrollment. A case-insensitive string (up to 128 characters long) of alphanumeric characters plus certain special characters : . _ -. No special characters allowed at start or end. Required."
        - name: If-Match
          in: header
          required: false
          schema:
            type: string
          description: The ETag of the enrollment record. Default value is None.
      responses:
        "200":
          description: Success
    delete:
      operationId: Enrollment_delete
      description: Delete a device enrollment record. Delete a device enrollment record.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "This id is used to uniquely identify a device registration of an enrollment. A case-insensitive string (up to 128 characters long) of alphanumeric characters plus certain special characters : . _ -. No special characters allowed at start or end. Required."
        - name: If-Match
          in: header
          required: false
          schema:
            type: string
          description: The ETag of the enrollment record. Default value is None.
      responses:
        "204":
          description: Success (no content / accepted)
  /enrollments/{id}/attestationmechanism?api-version=2021-10-01:
    post:
      operationId: Enrollment_get_attestation_mechanism
      description: Get the attestation mechanism in the device enrollment record. Get the attestation mechanism in the device enrollment record.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "This id is used to uniquely identify a device registration of an enrollment. A case-insensitive string (up to 128 characters long) of alphanumeric characters plus certain special characters : . _ -. No special characters allowed at start or end. Required."
      responses:
        "200":
          description: Success
  /enrollments?api-version=2021-10-01:
    post:
      operationId: Enrollment_run_bulk_operation
      description: Bulk device enrollment operation with maximum of 10 enrollments. Bulk device enrollment operation with maximum of 10 enrollments.
      parameters: []
      responses:
        "200":
          description: Success
