openapi: 3.0.0
servers:
  - url: https://{vault_base_url}
    variables:
      vault_base_url:
        default: ""
        description: The service endpoint host (no scheme), e.g. myaccount.table.cosmos.azure.com:443 - value of the client `vaultBaseUrl` parameter.
info:
  title: Security Domain Client
  description: SecurityDomainClient.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2025-07-01-stackql-generated
  x-serviceAlias: keyvault_securitydomain
  x-sdkPackage: azure-keyvault-securitydomain
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    OperationStatus:
      type: string
      enum:
        - Success
        - InProgress
        - Failed
    SecurityDomainOperationStatus:
      type: object
      description: The Security Domain operation status.
      properties:
        status:
          $ref: "#/components/schemas/OperationStatus"
          description: 'Operation status. Known values are: "Success", "InProgress", and "Failed".'
        status_details:
          type: string
          description: Details of the operation status.
    SecurityDomainJsonWebKey:
      type: object
      description: A JSON Web Key (JWK) for use in a security domain operation.
      properties:
        kid:
          type: string
          description: Key identifier. Required.
        kty:
          type: string
          description: JsonWebKey Key Type (kty), as defined in `https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40 `_. For Security Domain this value must be RSA. Required.
        key_ops:
          type: array
          items:
            type: string
          description: Supported key operations. Required.
        "n":
          type: string
          description: RSA modulus. Required.
        e:
          type: string
          description: RSA public exponent. Required.
        x5c:
          type: array
          items:
            type: string
          description: X509 certificate chain parameter. Required.
        use:
          type: string
          description: Public Key Use Parameter. This is optional and if present must be enc.
        x5t:
          type: string
          description: X509 certificate SHA1 thumbprint. This is optional.
        x5t#S256:
          type: string
          description: X509 certificate SHA256 thumbprint. Required.
        alg:
          type: string
          description: Algorithm intended for use with the key. Required.
      required:
        - kid
        - kty
        - key_ops
        - "n"
        - e
        - x5c
        - x5t#S256
        - alg
    TransferKey:
      type: object
      description: Security Domain transfer key.
      properties:
        key_format:
          type: string
          description: Specifies the format of the transfer key.
        transfer_key:
          $ref: "#/components/schemas/SecurityDomainJsonWebKey"
          description: Specifies the transfer key in JWK format. Required.
      required:
        - transfer_key
  x-stackQL-resources:
    download_status:
      id: azure.keyvault_securitydomain.download_status
      name: download_status
      title: download_status
      methods:
        get_download_status:
          operation:
            $ref: "#/paths/~1securitydomain~1download~1pending?api-version=2025-07-01/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/download_status/methods/get_download_status"
        insert: []
        update: []
        delete: []
    upload_status:
      id: azure.keyvault_securitydomain.upload_status
      name: upload_status
      title: upload_status
      methods:
        get_upload_status:
          operation:
            $ref: "#/paths/~1securitydomain~1upload~1pending?api-version=2025-07-01/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/upload_status/methods/get_upload_status"
        insert: []
        update: []
        delete: []
    transfer_keys:
      id: azure.keyvault_securitydomain.transfer_keys
      name: transfer_keys
      title: transfer_keys
      methods:
        get_transfer_key:
          operation:
            $ref: "#/paths/~1securitydomain~1upload?api-version=2025-07-01/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/transfer_keys/methods/get_transfer_key"
        insert: []
        update: []
        delete: []
paths:
  /securitydomain/download/pending?api-version=2025-07-01:
    get:
      operationId: _SecurityDomainClient_get_download_status
      description: Retrieves the Security Domain download operation status.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SecurityDomainOperationStatus"
  /securitydomain/upload/pending?api-version=2025-07-01:
    get:
      operationId: _SecurityDomainClient_get_upload_status
      description: Get Security Domain upload operation status.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SecurityDomainOperationStatus"
  /securitydomain/upload?api-version=2025-07-01:
    get:
      operationId: _SecurityDomainClient_get_transfer_key
      description: Retrieve Security Domain transfer key.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransferKey"
