openapi: 3.0.0
servers:
  - url: https://{endpoint}
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme).
info:
  title: Geolocation Client
  description: Azure Maps Geolocation REST APIs.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 1.0-stackql-generated
  x-serviceAlias: maps_geolocation
  x-sdkPackage: azure-maps-geolocation
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    CountryRegion:
      type: object
      description: The object containing the country/region information. Variables are only populated by the server, and will be ignored when sending a request.
      properties:
        isoCode:
          type: string
          description: The IP Address's 2-character code `(ISO 3166-1) `_ of the country or region. Please note, IP address in ranges reserved for special purpose will return Null for country/region.
    IpAddressToLocationResult:
      type: object
      description: This object is returned from a successful call to IP Address to country/region API. Variables are only populated by the server, and will be ignored when sending a request.
      properties:
        countryRegion:
          $ref: "#/components/schemas/CountryRegion"
          description: The object containing the country/region information.
        ipAddress:
          type: string
          description: The IP Address of the request.
  x-stackQL-resources:
    geolocation:
      id: azure.maps_geolocation.geolocation
      name: geolocation
      title: geolocation
      methods:
        get_location:
          operation:
            $ref: "#/paths/~1geolocation~1ip~1{format}?api-version=1.0/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/geolocation/methods/get_location"
        insert: []
        update: []
        delete: []
paths:
  /geolocation/ip/{format}?api-version=1.0:
    get:
      operationId: Geolocation_get_location
      description: "**Applies to:** see pricing `tiers `_. This service will return the ISO country code for the provided IP address. Developers can use this information to block or alter certain content based on geographical locations where the application is being viewed from."
      parameters:
        - name: format
          in: path
          required: true
          schema:
            type: string
          description: Desired format of the response. Only `json` format is supported. "json" Default value is "json".
        - name: ip
          in: query
          required: true
          schema:
            type: string
          description: The IP address. Both IPv4 and IPv6 are allowed. Required.
        - name: x-ms-client-id
          in: header
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IpAddressToLocationResult"
