openapi: 3.0.0
servers:
  - url: https://{endpoint}
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme).
info:
  title: Timezone Client
  description: Azure Maps Time Zone REST APIs.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 1.0-stackql-generated
  x-serviceAlias: maps_timezone
  x-sdkPackage: azure-maps-timezone
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas: {}
  x-stackQL-resources:
    timezone:
      id: azure.maps_timezone.timezone
      name: timezone
      title: timezone
      methods:
        get_timezone_by_id:
          operation:
            $ref: "#/paths/~1timezone~1byId~1{format}?api-version=1.0/get"
          response:
            openAPIDocKey: "200"
          request:
            nativeCasing: camel
        get_timezone_by_coordinates:
          operation:
            $ref: "#/paths/~1timezone~1byCoordinates~1{format}?api-version=1.0/get"
          response:
            openAPIDocKey: "200"
          request:
            nativeCasing: camel
        get_windows_timezone_ids:
          operation:
            $ref: "#/paths/~1timezone~1enumWindows~1{format}?api-version=1.0/get"
          response:
            openAPIDocKey: "200"
        get_iana_timezone_ids:
          operation:
            $ref: "#/paths/~1timezone~1enumIana~1{format}?api-version=1.0/get"
          response:
            openAPIDocKey: "200"
        get_iana_version:
          operation:
            $ref: "#/paths/~1timezone~1ianaVersion~1{format}?api-version=1.0/get"
          response:
            openAPIDocKey: "200"
        convert_windows_timezone_to_iana:
          operation:
            $ref: "#/paths/~1timezone~1windowsToIana~1{format}?api-version=1.0/get"
          response:
            openAPIDocKey: "200"
          request:
            nativeCasing: camel
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /timezone/byId/{format}?api-version=1.0:
    get:
      operationId: Timezone_get_timezone_by_id
      description: Use to get the current, historical, and future time zone information for the specified IANA time zone ID. The `Get Timezone By ID` API is an HTTP `GET` request that returns current, historical, and future time zone information for the specified IANA time zone ID.
      parameters:
        - name: format
          in: path
          required: true
          schema:
            type: string
          description: Desired format of the response. Only `json` format is supported. "json" Default value is "json".
        - name: query
          in: query
          required: true
          schema:
            type: string
          description: The IANA time zone ID. Required.
        - name: Accept-Language
          in: header
          required: false
          schema:
            type: string
          description: Specifies the language code in which the timezone names should be returned. If no language code is provided, the response will be in "EN". Please refer to `Supported Languages `_ for details. Default value is None.
        - name: options
          in: query
          required: false
          schema:
            type: string
          description: 'Alternatively, use alias "o". Options available for types of information returned in the result. Known values are: "none", "zoneInfo", "transitions", and "all". Default value is None.'
        - name: timeStamp
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Alternatively, use alias "stamp", or "s". Reference time, if omitted, the API will use the machine time serving the request. Default value is None.
        - name: transitionsFrom
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Alternatively, use alias "tf". The start date from which daylight savings time (DST) transitions are requested, only applies when "options" = all or "options" = transitions. Default value is None.
        - name: transitionsYears
          in: query
          required: false
          schema:
            type: integer
          description: Alternatively, use alias "ty". The number of years from "transitionsFrom" for which DST transitions are requested, only applies when "options" = all or "options" = transitions. Default value is None.
        - name: x-ms-client-id
          in: header
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
  /timezone/byCoordinates/{format}?api-version=1.0:
    get:
      operationId: Timezone_get_timezone_by_coordinates
      description: Use to get the current, historical, and future time zone information for the specified latitude-longitude pair. The `Get Timezone By Coordinates` API is an HTTP `GET` request that returns current, historical, and future time zone information for a specified latitude-longitude pair. In addition, the API provides sunset and sunrise times for a given location.
      parameters:
        - name: format
          in: path
          required: true
          schema:
            type: string
          description: Desired format of the response. Only `json` format is supported. "json" Default value is "json".
        - name: query
          in: query
          required: true
          schema:
            type: array
            items:
              type: number
          description: Coordinates of the point for which time zone information is requested. This parameter is a list of coordinates, containing a pair of coordinate(lat, long). When this endpoint is called directly, coordinates are passed in as a single string containing coordinates, separated by commas. Required.
        - name: Accept-Language
          in: header
          required: false
          schema:
            type: string
          description: Specifies the language code in which the timezone names should be returned. If no language code is provided, the response will be in "EN". Please refer to `Supported Languages `_ for details. Default value is None.
        - name: options
          in: query
          required: false
          schema:
            type: string
          description: 'Alternatively, use alias "o". Options available for types of information returned in the result. Known values are: "none", "zoneInfo", "transitions", and "all". Default value is None.'
        - name: timeStamp
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Alternatively, use alias "stamp", or "s". Reference time, if omitted, the API will use the machine time serving the request. Default value is None.
        - name: transitionsFrom
          in: query
          required: false
          schema:
            type: string
            format: date-time
          description: Alternatively, use alias "tf". The start date from which daylight savings time (DST) transitions are requested, only applies when "options" = all or "options" = transitions. Default value is None.
        - name: transitionsYears
          in: query
          required: false
          schema:
            type: integer
          description: Alternatively, use alias "ty". The number of years from "transitionsFrom" for which DST transitions are requested, only applies when "options" = all or "options" = transitions. Default value is None.
        - name: x-ms-client-id
          in: header
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
  /timezone/enumWindows/{format}?api-version=1.0:
    get:
      operationId: Timezone_get_windows_timezone_ids
      description: Use to get the list of Windows Time Zone IDs. The `Get Windows Time Zones` API is an HTTP `GET` request that returns a full list of Windows Time Zone IDs.
      parameters:
        - name: format
          in: path
          required: true
          schema:
            type: string
          description: Desired format of the response. Only `json` format is supported. "json" Default value is "json".
        - name: x-ms-client-id
          in: header
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
  /timezone/enumIana/{format}?api-version=1.0:
    get:
      operationId: Timezone_get_iana_timezone_ids
      description: Use to get the list of IANA time zone IDs. The `Get IANA Time Zones` API is an HTTP `GET` request that returns a full list of Internet Assigned Numbers Authority (IANA) time zone IDs. Updates to the IANA service are reflected in the system within one day.
      parameters:
        - name: format
          in: path
          required: true
          schema:
            type: string
          description: Desired format of the response. Only `json` format is supported. "json" Default value is "json".
        - name: x-ms-client-id
          in: header
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
  /timezone/ianaVersion/{format}?api-version=1.0:
    get:
      operationId: Timezone_get_iana_version
      description: Use to get the current IANA version number. The `Get Time Zone IANA Version` API is an HTTP `GET` request that returns the current Internet Assigned Numbers Authority (IANA) version number as Metadata.
      parameters:
        - name: format
          in: path
          required: true
          schema:
            type: string
          description: Desired format of the response. Only `json` format is supported. "json" Default value is "json".
        - name: x-ms-client-id
          in: header
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
  /timezone/windowsToIana/{format}?api-version=1.0:
    get:
      operationId: Timezone_convert_windows_timezone_to_iana
      description: Use to get the IANA ID. The `Get Windows to IANA Time Zone` API is an HTTP `GET` request that returns a corresponding Internet Assigned Numbers Authority (IANA) ID, given a valid Windows Time Zone ID. Multiple IANA IDs may be returned for a single Windows ID. It is possible to narrow these results by adding an optional territory parameter.
      parameters:
        - name: format
          in: path
          required: true
          schema:
            type: string
          description: Desired format of the response. Only `json` format is supported. "json" Default value is "json".
        - name: query
          in: query
          required: true
          schema:
            type: string
          description: The Windows time zone ID. Required.
        - name: territory
          in: query
          required: false
          schema:
            type: string
          description: Windows Time Zone territory code. Default value is None.
        - name: x-ms-client-id
          in: header
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Success
