openapi: 3.0.0
servers:
  - url: https://{endpoint}/{api_version}
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme), e.g. myaccount.table.cosmos.azure.com:443 - value of the client `endpoint` parameter.
      api_version:
        default: ""
        description: The service endpoint host (no scheme), e.g. myaccount.table.cosmos.azure.com:443 - value of the client `apiVersion` parameter.
info:
  title: Monitor Query Logs Client
  description: MonitorQueryLogsClient.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: unversioned-stackql-generated
  x-serviceAlias: monitor_query
  x-sdkPackage: azure-monitor-query
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas: {}
  x-stackQL-resources:
    executes:
      id: azure.monitor_query.executes
      name: executes
      title: executes
      methods:
        execute:
          operation:
            $ref: "#/paths/~1workspaces~1{workspace_id}~1query/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    execute_with_resource_ids:
      id: azure.monitor_query.execute_with_resource_ids
      name: execute_with_resource_ids
      title: execute_with_resource_ids
      methods:
        execute_with_resource_id:
          operation:
            $ref: "#/paths/~1{resource_id}~1query/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    batches:
      id: azure.monitor_query.batches
      name: batches
      title: batches
      methods:
        batch:
          operation:
            $ref: "#/paths/~1$batch/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /workspaces/{workspace_id}/query:
    post:
      operationId: _MonitorQueryLogsClient_execute
      description: Execute an Analytics query. Executes an Analytics query for data. `Here `_ is an example for using POST with an Analytics query.
      parameters:
        - name: workspace_id
          in: path
          required: true
          schema:
            type: string
          description: Primary Workspace ID of the query. This is the Workspace ID from the Properties blade in the Azure portal. Required.
        - name: Prefer
          in: header
          required: false
          schema:
            type: string
          description: Optional. The prefer header to set server timeout, query statistics and visualization information. Default value is None.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties: {}
  /{resource_id}/query:
    post:
      operationId: _MonitorQueryLogsClient_execute_with_resource_id
      description: Execute an Analytics query using resource ID. Executes an Analytics query for data in the context of a resource. `Here `_ is an example for using POST with an Analytics query.
      parameters:
        - name: resource_id
          in: path
          required: true
          schema:
            type: string
          description: The identifier of the resource. Required.
        - name: Prefer
          in: header
          required: false
          schema:
            type: string
          description: Optional. The prefer header to set server timeout, query statistics and visualization information. Default value is None.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties: {}
  /$batch:
    post:
      operationId: _MonitorQueryLogsClient_batch
      description: Execute a batch of Analytics queries. Executes a batch of Analytics queries for data. `Here `_ is an example for using POST with an Analytics query.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties: {}
