openapi: 3.0.0
servers:
  - url: https://{endpoint}
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme), e.g. myaccount.table.cosmos.azure.com:443 - value of the client `endpoint` parameter.
info:
  title: Logs Ingestion Client
  description: Azure Monitor data collection client.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2023-01-01-stackql-generated
  x-serviceAlias: monitor_ingestion
  x-sdkPackage: azure-monitor-ingestion
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas: {}
  x-stackQL-resources:
    uploads:
      id: azure.monitor_ingestion.uploads
      name: uploads
      title: uploads
      methods:
        upload:
          operation:
            $ref: "#/paths/~1dataCollectionRules~1{rule_id}~1streams~1{stream}?api-version=2023-01-01/post"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /dataCollectionRules/{rule_id}/streams/{stream}?api-version=2023-01-01:
    post:
      operationId: _LogsIngestionClient_upload
      description: Ingestion API used to directly ingest data using Data Collection Rules. Ingestion API used to directly ingest data using Data Collection Rules.
      parameters:
        - name: rule_id
          in: path
          required: true
          schema:
            type: string
          description: The immutable ID of the Data Collection Rule resource. Required.
        - name: stream
          in: path
          required: true
          schema:
            type: string
          description: The streamDeclaration name as defined in the Data Collection Rule. Required.
        - name: Content-Encoding
          in: header
          required: false
          schema:
            type: string
          description: The content encoding of the request body which is always 'gzip'. Default value is None.
      responses:
        "200":
          description: Success
