openapi: 3.0.0
servers:
  - url: https://{endpoint}
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme).
info:
  title: Purview Account Client
  description: Creates a Microsoft.Purview data plane account client.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: unversioned-stackql-generated
  x-serviceAlias: purview_administration
  x-sdkPackage: azure-purview-administration
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas: {}
  x-stackQL-resources:
    accounts:
      id: azure.purview_administration.accounts
      name: accounts
      title: accounts
      methods:
        get_account_properties:
          operation:
            $ref: "#/paths/~1/get"
          response:
            openAPIDocKey: "200"
        get_access_keys:
          operation:
            $ref: "#/paths/~1listkeys/get"
          response:
            openAPIDocKey: "200"
        regenerate_access_key:
          operation:
            $ref: "#/paths/~1regeneratekeys/get"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    collections:
      id: azure.purview_administration.collections
      name: collections
      title: collections
      methods:
        list_collections:
          operation:
            $ref: "#/paths/~1collections/get"
          response:
            openAPIDocKey: "200"
        list_child_collection_names:
          operation:
            $ref: "#/paths/~1collections~1{collection_name}~1getChildCollectionNames/get"
          response:
            openAPIDocKey: "200"
        get_collection:
          operation:
            $ref: "#/paths/~1collections~1{collection_name}/get"
          response:
            openAPIDocKey: "200"
        get_collection_path:
          operation:
            $ref: "#/paths/~1collections~1{collection_name}~1getCollectionPath/get"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    metadata_policy:
      id: azure.purview_administration.metadata_policy
      name: metadata_policy
      title: metadata_policy
      methods:
        get_raw:
          operation:
            $ref: "#/paths/~1metadataPolicies~1{policy_id}/get"
          response:
            openAPIDocKey: "200"
        list_all:
          operation:
            $ref: "#/paths/~1metadataPolicies/get"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    metadata_roles:
      id: azure.purview_administration.metadata_roles
      name: metadata_roles
      title: metadata_roles
      methods:
        list_raw:
          operation:
            $ref: "#/paths/~1metadataRoles/get"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    resource_set_rules:
      id: azure.purview_administration.resource_set_rules
      name: resource_set_rules
      title: resource_set_rules
      methods:
        list_resource_set_rules:
          operation:
            $ref: "#/paths/~1resourceSetRuleConfigs/get"
          response:
            openAPIDocKey: "200"
        get_resource_set_rule:
          operation:
            $ref: "#/paths/~1resourceSetRuleConfigs~1defaultResourceSetRuleConfig/get"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /:
    get:
      operationId: Accounts_get_account_properties
      description: Get an account.
      parameters: []
      responses:
        "200":
          description: Success
  /listkeys:
    get:
      operationId: Accounts_get_access_keys
      description: List the authorization keys associated with this account.
      parameters: []
      responses:
        "200":
          description: Success
  /regeneratekeys:
    get:
      operationId: Accounts_regenerate_access_key
      description: Regenerate the authorization keys associated with this data catalog.
      parameters: []
      responses:
        "200":
          description: Success
  /collections:
    get:
      operationId: Collections_list_collections
      description: List the collections in the account.
      parameters: []
      responses:
        "200":
          description: Success
  /collections/{collection_name}/getChildCollectionNames:
    get:
      operationId: Collections_list_child_collection_names
      description: Lists the child collections names in the collection.
      parameters: []
      responses:
        "200":
          description: Success
  /collections/{collection_name}:
    get:
      operationId: Collections_get_collection
      description: Get a collection.
      parameters: []
      responses:
        "200":
          description: Success
  /collections/{collection_name}/getCollectionPath:
    get:
      operationId: Collections_get_collection_path
      description: Gets the parent name and parent friendly name chains that represent the collection path.
      parameters: []
      responses:
        "200":
          description: Success
  /metadataPolicies/{policy_id}:
    get:
      operationId: MetadataPolicy_get
      description: Gets a metadata policy.
      parameters: []
      responses:
        "200":
          description: Success
  /metadataPolicies:
    get:
      operationId: MetadataPolicy_list_all
      description: List or Get metadata policies.
      parameters: []
      responses:
        "200":
          description: Success
  /metadataRoles:
    get:
      operationId: MetadataRoles_list
      description: Lists roles for Purview Account.
      parameters: []
      responses:
        "200":
          description: Success
  /resourceSetRuleConfigs:
    get:
      operationId: ResourceSetRules_list_resource_set_rules
      description: Get a resource set config service model.
      parameters: []
      responses:
        "200":
          description: Success
  /resourceSetRuleConfigs/defaultResourceSetRuleConfig:
    get:
      operationId: ResourceSetRules_get_resource_set_rule
      description: Get a resource set config service model.
      parameters: []
      responses:
        "200":
          description: Success
