openapi: 3.0.0
servers:
  - url: https://management.azure.com/
info:
  title: Bicep Mgmt Client
  description: Bicep Client.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2023-11-01-stackql-generated
  x-serviceAlias: resource_bicep
  x-sdkPackage: azure-mgmt-resource-bicep
  x-plane: mgmt
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    DecompileOperationSuccessResponse:
      type: object
      description: The response of the decompileBicep operation.
      properties:
        files:
          type: array
          items:
            $ref: "#/components/schemas/FileDefinition"
          description: An array of key-value pairs containing the entryPoint string as the key for the Bicep file decompiled from the ARM json template. Required.
        entryPoint:
          type: string
          description: The file path to the main Bicep file generated from the decompiled ARM json template. Required.
      required:
        - files
        - entryPoint
    FileDefinition:
      type: object
      description: The definition of a file along with its contents.
      properties:
        path:
          type: string
          description: The file path of the Bicep file.
        contents:
          type: string
          description: The contents of the Bicep file.
  x-stackQL-resources:
    decompile_operation_group:
      id: azure.resource_bicep.decompile_operation_group
      name: decompile_operation_group
      title: decompile_operation_group
      methods:
        bicep:
          operation:
            $ref: "#/paths/~1subscriptions~1{subscription_id}~1providers~1Microsoft.Resources~1decompileBicep?api-version=2023-11-01/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /subscriptions/{subscription_id}/providers/Microsoft.Resources/decompileBicep?api-version=2023-11-01:
    post:
      operationId: DecompileOperationGroup_bicep
      description: Decompiles an ARM json template into a Bicep template.
      parameters:
        - name: subscription_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                template:
                  type: string
                  description: The ARM json template to be decompiled into a Bicep file. Required.
              required:
                - template
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DecompileOperationSuccessResponse"
