openapi: 3.0.0
servers:
  - url: https://management.azure.com/
info:
  title: Data Boundary Mgmt Client
  description: Provides APIs for data boundary operations.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2024-08-01-stackql-generated
  x-serviceAlias: resource_databoundaries
  x-sdkPackage: azure-mgmt-resource-databoundaries
  x-plane: mgmt
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    SystemData:
      type: object
      description: Metadata pertaining to creation and last modification of the resource.
      properties:
        createdBy:
          type: string
          description: The identity that created the resource.
        createdByType:
          $ref: "#/components/schemas/CreatedByType"
          description: 'The type of identity that created the resource. Known values are: "User", "Application", "ManagedIdentity", and "Key".'
        createdAt:
          type: string
          format: date-time
          description: The timestamp of resource creation (UTC).
        lastModifiedBy:
          type: string
          description: The identity that last modified the resource.
        lastModifiedByType:
          $ref: "#/components/schemas/CreatedByType"
          description: 'The type of identity that last modified the resource. Known values are: "User", "Application", "ManagedIdentity", and "Key".'
        lastModifiedAt:
          type: string
          format: date-time
          description: The timestamp of resource last modification (UTC).
    CreatedByType:
      type: string
      enum:
        - User
        - Application
        - ManagedIdentity
        - Key
    DataBoundaryProperties:
      type: object
      description: Data boundary properties.
      properties:
        dataBoundary:
          $ref: "#/components/schemas/DataBoundary"
          description: 'The data boundary definition. Known values are: "NotDefined", "Global", and "EU".'
        provisioningState:
          $ref: "#/components/schemas/ProvisioningState"
          description: 'Denotes the state of provisioning. Known values are: "Accepted", "Running", "Creating", "Canceled", "Failed", "Succeeded", and "Updating".'
    DataBoundary:
      type: string
      enum:
        - NotDefined
        - Global
        - EU
    ProvisioningState:
      type: string
      enum:
        - Accepted
        - Running
        - Creating
        - Canceled
        - Failed
        - Succeeded
        - Updating
    DataBoundaryDefinitionFlattened:
      type: object
      description: Flattened view of DataBoundaryDefinition ('properties' hoisted to the top level).
      properties:
        id:
          type: string
          description: Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
        name:
          type: string
          description: The name of the resource.
        type:
          type: string
          description: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts".
        systemData:
          $ref: "#/components/schemas/SystemData"
          description: Azure Resource Manager metadata containing createdBy and modifiedBy information.
        dataBoundary:
          $ref: "#/components/schemas/DataBoundary"
          description: 'The data boundary definition. Known values are: "NotDefined", "Global", and "EU".'
        provisioningState:
          $ref: "#/components/schemas/ProvisioningState"
          description: 'Denotes the state of provisioning. Known values are: "Accepted", "Running", "Creating", "Canceled", "Failed", "Succeeded", and "Updating".'
    DataBoundaryDefinition:
      type: object
      description: A data boundary definition.
      properties:
        id:
          type: string
          description: Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
        name:
          type: string
          description: The name of the resource.
        type:
          type: string
          description: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts".
        systemData:
          $ref: "#/components/schemas/SystemData"
          description: Azure Resource Manager metadata containing createdBy and modifiedBy information.
        properties:
          $ref: "#/components/schemas/DataBoundaryProperties"
          description: Data boundary properties.
    OperationDisplay:
      type: object
      description: Localized display information for an operation.
      properties:
        provider:
          type: string
          description: The localized friendly form of the resource provider name, e.g. "Microsoft Monitoring Insights" or "Microsoft Compute".
        resource:
          type: string
          description: The localized friendly name of the resource type related to this operation. E.g. "Virtual Machines" or "Job Schedule Collections".
        operation:
          type: string
          description: The concise, localized friendly name for the operation; suitable for dropdowns. E.g. "Create or Update Virtual Machine", "Restart Virtual Machine".
        description:
          type: string
          description: The short, localized friendly description of the operation; suitable for tool tips and detailed views.
    Origin:
      type: string
      enum:
        - user
        - system
        - user,system
    ActionType:
      type: string
      enum:
        - Internal
    Operation:
      type: object
      description: REST API Operation.
      properties:
        name:
          type: string
          description: 'The name of the operation, as per Resource-Based Access Control (RBAC). Examples: "Microsoft.Compute/virtualMachines/write", "Microsoft.Compute/virtualMachines/capture/action".'
        isDataAction:
          type: boolean
          description: Whether the operation applies to data-plane. This is "true" for data-plane operations and "false" for Azure Resource Manager/control-plane operations.
        display:
          $ref: "#/components/schemas/OperationDisplay"
          description: Localized display information for this particular operation.
        origin:
          $ref: "#/components/schemas/Origin"
          description: 'The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit logs UX. Default value is "user,system". Known values are: "user", "system", and "user,system".'
        actionType:
          $ref: "#/components/schemas/ActionType"
          description: Extensible enum. Indicates the action type. "Internal" refers to actions that are for internal only APIs. "Internal"
    PagedOperation:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/Operation"
        nextLink:
          type: string
  x-stackQL-resources:
    data_boundaries:
      id: azure.resource_databoundaries.data_boundaries
      name: data_boundaries
      title: data_boundaries
      methods:
        get_scope:
          operation:
            $ref: "#/paths/~1{scope}~1providers~1Microsoft.Resources~1dataBoundaries~1{default_name}?api-version=2024-08-01/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            overrideMediaType: application/json
            transform:
              type: golang_template_json_v0.3.0
              body: '{{ $row := . }}{ {{ $p := index $row "properties" }}{{ if eq (kindOf $p) "map" }}{{ range $k, $v := $p }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}{{ end }}{{ range $k, $v := $row }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}"_flattened": true }'
        get_tenant:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.Resources~1dataBoundaries~1{default_name}?api-version=2024-08-01/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            overrideMediaType: application/json
            transform:
              type: golang_template_json_v0.3.0
              body: '{{ $row := . }}{ {{ $p := index $row "properties" }}{{ if eq (kindOf $p) "map" }}{{ range $k, $v := $p }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}{{ end }}{{ range $k, $v := $row }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}"_flattened": true }'
        put:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.Resources~1dataBoundaries~1{default_name}?api-version=2024-08-01/put"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/data_boundaries/methods/get_scope"
          - $ref: "#/components/x-stackQL-resources/data_boundaries/methods/get_tenant"
        insert: []
        update: []
        delete: []
    operations:
      id: azure.resource_databoundaries.operations
      name: operations
      title: operations
      methods:
        list:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.Resources~1operations?api-version=2024-08-01/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.value
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/operations/methods/list"
        insert: []
        update: []
        delete: []
paths:
  /{scope}/providers/Microsoft.Resources/dataBoundaries/{default_name}?api-version=2024-08-01:
    get:
      operationId: DataBoundaries_get_scope
      description: Get data boundary at specified scope.
      parameters:
        - name: scope
          in: path
          required: true
          schema:
            type: string
          description: The fully qualified Azure Resource manager identifier of the resource. Required.
        - name: default_name
          in: path
          required: true
          schema:
            type: string
          description: Default string modeled as parameter for auto generation to work correctly. "default" Required.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataBoundaryDefinitionFlattened"
  /providers/Microsoft.Resources/dataBoundaries/{default_name}?api-version=2024-08-01:
    get:
      operationId: DataBoundaries_get_tenant
      description: Get data boundary of tenant.
      parameters:
        - name: default_name
          in: path
          required: true
          schema:
            type: string
          description: Default string modeled as parameter for auto generation to work correctly. "default" Required.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataBoundaryDefinitionFlattened"
    put:
      operationId: DataBoundaries_put
      description: Opt-in tenant to data boundary.
      parameters:
        - name: default_name
          in: path
          required: true
          schema:
            type: string
          description: Default string modeled as parameter for auto generation to work correctly. "default" Required.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                properties:
                  $ref: "#/components/schemas/DataBoundaryProperties"
                  description: Data boundary properties.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataBoundaryDefinition"
  /providers/Microsoft.Resources/operations?api-version=2024-08-01:
    get:
      operationId: resource_databoundaries_list
      description: List the operations for the provider.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedOperation"
