openapi: 3.0.0
servers:
  - url: https://{fully_qualified_namespace}
    variables:
      fully_qualified_namespace:
        default: ""
        description: The service endpoint host (no scheme), e.g. myaccount.table.cosmos.azure.com:443 - value of the client `fullyQualifiedNamespace` parameter.
info:
  title: Schema Registry Client
  description: SchemaRegistryClient is a client for registering and retrieving schemas from the Azure Schema Registry service.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2023-07-01-stackql-generated
  x-serviceAlias: schemaregistry
  x-sdkPackage: azure-schemaregistry
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas: {}
  x-stackQL-resources:
    schema_groups:
      id: azure.schemaregistry.schema_groups
      name: schema_groups
      title: schema_groups
      methods:
        list_schema_groups:
          operation:
            $ref: "#/paths/~1$schemaGroups?api-version=2023-07-01/get"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    schema_versions:
      id: azure.schemaregistry.schema_versions
      name: schema_versions
      title: schema_versions
      methods:
        list_schema_versions:
          operation:
            $ref: "#/paths/~1$schemaGroups~1{group_name}~1schemas~1{schema_name}~1versions?api-version=2023-07-01/get"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    schemas:
      id: azure.schemaregistry.schemas
      name: schemas
      title: schemas
      methods:
        get_schema_by_id:
          operation:
            $ref: "#/paths/~1$schemaGroups~1$schemas~1{id}?api-version=2023-07-01/get"
          response:
            openAPIDocKey: "200"
        get_schema_by_version:
          operation:
            $ref: "#/paths/~1$schemaGroups~1{group_name}~1schemas~1{schema_name}~1versions~1{schema_version}?api-version=2023-07-01/get"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    schema_properties:
      id: azure.schemaregistry.schema_properties
      name: schema_properties
      title: schema_properties
      methods:
        get_schema_properties_by_content:
          operation:
            $ref: "#/paths/~1$schemaGroups~1{group_name}~1schemas~1{schema_name}:get-id?api-version=2023-07-01/post"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    register_schemas:
      id: azure.schemaregistry.register_schemas
      name: register_schemas
      title: register_schemas
      methods:
        register_schema:
          operation:
            $ref: "#/paths/~1$schemaGroups~1{group_name}~1schemas~1{schema_name}?api-version=2023-07-01/put"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /$schemaGroups?api-version=2023-07-01:
    get:
      operationId: SchemaRegistryClient_list_schema_groups
      description: Get list of schema groups. Gets the list of schema groups user is authorized to access.
      parameters: []
      responses:
        "200":
          description: Success
  /$schemaGroups/{group_name}/schemas/{schema_name}/versions?api-version=2023-07-01:
    get:
      operationId: SchemaRegistryClient_list_schema_versions
      description: List schema versions. Gets the list of all versions of one schema.
      parameters:
        - name: group_name
          in: path
          required: true
          schema:
            type: string
          description: Name of schema group. Required.
        - name: schema_name
          in: path
          required: true
          schema:
            type: string
          description: Name of schema. Required.
      responses:
        "200":
          description: Success
  /$schemaGroups/$schemas/{id}?api-version=2023-07-01:
    get:
      operationId: SchemaRegistryClient_get_schema_by_id
      description: Get a registered schema by its unique ID reference. Gets a registered schema by its unique ID. Azure Schema Registry guarantees that ID is unique within a namespace. Operation response type is based on serialization of schema requested.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Schema ID that uniquely identifies a schema in the registry namespace. Required.
      responses:
        "200":
          description: Success
  /$schemaGroups/{group_name}/schemas/{schema_name}/versions/{schema_version}?api-version=2023-07-01:
    get:
      operationId: SchemaRegistryClient_get_schema_by_version
      description: Get specific schema versions. Gets one specific version of one schema.
      parameters:
        - name: group_name
          in: path
          required: true
          schema:
            type: string
          description: Name of schema group. Required.
        - name: schema_name
          in: path
          required: true
          schema:
            type: string
          description: Name of schema. Required.
        - name: schema_version
          in: path
          required: true
          schema:
            type: integer
          description: Version number of specific schema. Required.
      responses:
        "200":
          description: Success
  /$schemaGroups/{group_name}/schemas/{schema_name}:get-id?api-version=2023-07-01:
    post:
      operationId: SchemaRegistryClient_get_schema_properties_by_content
      description: Get properties for existing schema. Gets the properties referencing an existing schema within the specified schema group, as matched by schema content comparison.
      parameters:
        - name: group_name
          in: path
          required: true
          schema:
            type: string
          description: Name of schema group. Required.
        - name: schema_name
          in: path
          required: true
          schema:
            type: string
          description: Name of schema. Required.
      responses:
        "200":
          description: Success
  /$schemaGroups/{group_name}/schemas/{schema_name}?api-version=2023-07-01:
    put:
      operationId: SchemaRegistryClient_register_schema
      description: Register new schema. Register new schema. If schema of specified name does not exist in specified group, schema is created at version 1. If schema of specified name exists already in specified group, schema is created at latest version + 1.
      parameters:
        - name: group_name
          in: path
          required: true
          schema:
            type: string
          description: Name of schema group. Required.
        - name: schema_name
          in: path
          required: true
          schema:
            type: string
          description: Name of schema. Required.
      responses:
        "200":
          description: Success
