openapi: 3.0.0
servers:
  - url: https://management.azure.com/
info:
  title: Service Groups Mgmt Client
  description: The Groups RP provides Service Groups as a construct to group multiple resources, resource groups, subscriptions and other service groups into an organizational hierarchy and centrally manage access control, policies, alerting and reporting for those resources.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2024-02-01-preview-stackql-generated
  x-serviceAlias: servicegroups
  x-sdkPackage: azure-mgmt-servicegroups
  x-plane: mgmt
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    SystemData:
      type: object
      description: Metadata pertaining to creation and last modification of the resource.
      properties:
        createdBy:
          type: string
          description: The identity that created the resource.
        createdByType:
          $ref: "#/components/schemas/CreatedByType"
          description: 'The type of identity that created the resource. Known values are: "User", "Application", "ManagedIdentity", and "Key".'
        createdAt:
          type: string
          format: date-time
          description: The timestamp of resource creation (UTC).
        lastModifiedBy:
          type: string
          description: The identity that last modified the resource.
        lastModifiedByType:
          $ref: "#/components/schemas/CreatedByType"
          description: 'The type of identity that last modified the resource. Known values are: "User", "Application", "ManagedIdentity", and "Key".'
        lastModifiedAt:
          type: string
          format: date-time
          description: The timestamp of resource last modification (UTC).
    CreatedByType:
      type: string
      enum:
        - User
        - Application
        - ManagedIdentity
        - Key
    ServiceGroupProperties:
      type: object
      description: ServiceGroup creation request body parameters.
      properties:
        provisioningState:
          $ref: "#/components/schemas/ProvisioningState"
          description: 'The provisioning state of the serviceGroup. For example, Running. Known values are: "NotStarted", "Running", "Succeeded", "Failed", and "Canceled".'
        displayName:
          type: string
          description: The display name of the serviceGroup. For example, ServiceGroupTest1.
        parent:
          $ref: "#/components/schemas/ParentServiceGroupProperties"
          description: The details of the parent serviceGroup.
    ProvisioningState:
      type: string
      enum:
        - NotStarted
        - Running
        - Succeeded
        - Failed
        - Canceled
    ParentServiceGroupProperties:
      type: object
      description: The details of the parent serviceGroup.
      properties:
        resourceId:
          type: string
          description: The fully qualified ID of the parent serviceGroup. For example, '/providers/Microsoft.Management/serviceGroups/TestServiceGroup'.
    ServiceGroupFlattened:
      type: object
      description: Flattened view of ServiceGroup ('properties' hoisted to the top level).
      properties:
        id:
          type: string
          description: Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
        name:
          type: string
          description: The name of the resource.
        type:
          type: string
          description: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts".
        systemData:
          $ref: "#/components/schemas/SystemData"
          description: Azure Resource Manager metadata containing createdBy and modifiedBy information.
        kind:
          type: string
          description: The kind of the serviceGroup.
        tags:
          type: object
          properties: {}
          description: The serviceGroup tags.
        provisioningState:
          $ref: "#/components/schemas/ProvisioningState"
          description: 'The provisioning state of the serviceGroup. For example, Running. Known values are: "NotStarted", "Running", "Succeeded", "Failed", and "Canceled".'
        displayName:
          type: string
          description: The display name of the serviceGroup. For example, ServiceGroupTest1.
        parent:
          $ref: "#/components/schemas/ParentServiceGroupProperties"
          description: The details of the parent serviceGroup.
    ServiceGroupCollectionResponse:
      type: object
      description: Response holding an array of service groups and a nextLink that supports pagination.
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/ServiceGroup"
          description: The ServiceGroup items on this page. Required.
        nextLink:
          type: string
          description: The link to the next page of items.
      required:
        - value
    ServiceGroup:
      type: object
      description: The serviceGroup details.
      properties:
        id:
          type: string
          description: Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
        name:
          type: string
          description: The name of the resource.
        type:
          type: string
          description: The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts".
        systemData:
          $ref: "#/components/schemas/SystemData"
          description: Azure Resource Manager metadata containing createdBy and modifiedBy information.
        properties:
          $ref: "#/components/schemas/ServiceGroupProperties"
          description: ServiceGroup creation request body parameters.
        kind:
          type: string
          description: The kind of the serviceGroup.
        tags:
          type: object
          properties: {}
          description: The serviceGroup tags.
  x-stackQL-resources:
    service_groups:
      id: azure.servicegroups.service_groups
      name: service_groups
      title: service_groups
      methods:
        get:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.Management~1serviceGroups~1{service_group_name}?api-version=2024-02-01-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            overrideMediaType: application/json
            transform:
              type: golang_template_json_v0.3.0
              body: '{{ $row := . }}{ {{ $p := index $row "properties" }}{{ if eq (kindOf $p) "map" }}{{ range $k, $v := $p }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}{{ end }}{{ range $k, $v := $row }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}"_flattened": true }'
        create_or_update_service_group:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.Management~1serviceGroups~1{service_group_name}?api-version=2024-02-01-preview/put"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
        update_service_group:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.Management~1serviceGroups~1{service_group_name}?api-version=2024-02-01-preview/patch"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
        delete_service_group:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.Management~1serviceGroups~1{service_group_name}?api-version=2024-02-01-preview/delete"
          response:
            openAPIDocKey: "204"
        list_ancestors:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.Management~1serviceGroups~1{service_group_name}~1listAncestors?api-version=2024-02-01-preview/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/service_groups/methods/get"
        insert:
          - $ref: "#/components/x-stackQL-resources/service_groups/methods/create_or_update_service_group"
        update:
          - $ref: "#/components/x-stackQL-resources/service_groups/methods/update_service_group"
        replace:
          - $ref: "#/components/x-stackQL-resources/service_groups/methods/create_or_update_service_group"
        delete:
          - $ref: "#/components/x-stackQL-resources/service_groups/methods/delete_service_group"
paths:
  /providers/Microsoft.Management/serviceGroups/{service_group_name}?api-version=2024-02-01-preview:
    get:
      operationId: ServiceGroups_get
      description: Get the details of the serviceGroup.
      parameters:
        - name: service_group_name
          in: path
          required: true
          schema:
            type: string
          description: ServiceGroup Name. Required.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceGroupFlattened"
    put:
      operationId: _ServiceGroupsMgmtClient_begin_create_or_update_service_group
      description: Create or Update a serviceGroup.
      parameters:
        - name: service_group_name
          in: path
          required: true
          schema:
            type: string
          description: ServiceGroup Name. Required.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                properties:
                  $ref: "#/components/schemas/ServiceGroupProperties"
                  description: ServiceGroup creation request body parameters.
                kind:
                  type: string
                  description: The kind of the serviceGroup.
                tags:
                  type: object
                  properties: {}
                  description: The serviceGroup tags.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceGroup"
    patch:
      operationId: _ServiceGroupsMgmtClient_begin_update_service_group
      description: Update a serviceGroup.
      parameters:
        - name: service_group_name
          in: path
          required: true
          schema:
            type: string
          description: ServiceGroup Name. Required.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                properties:
                  $ref: "#/components/schemas/ServiceGroupProperties"
                  description: ServiceGroup creation request body parameters.
                kind:
                  type: string
                  description: The kind of the serviceGroup.
                tags:
                  type: object
                  properties: {}
                  description: The serviceGroup tags.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceGroup"
    delete:
      operationId: _ServiceGroupsMgmtClient_begin_delete_service_group
      description: Delete a ServiceGroup.
      parameters:
        - name: service_group_name
          in: path
          required: true
          schema:
            type: string
          description: ServiceGroup Name. Required.
      responses:
        "204":
          description: Success (no content / accepted)
  /providers/Microsoft.Management/serviceGroups/{service_group_name}/listAncestors?api-version=2024-02-01-preview:
    post:
      operationId: ServiceGroups_list_ancestors
      description: Get the details of the serviceGroup's ancestors.
      parameters:
        - name: service_group_name
          in: path
          required: true
          schema:
            type: string
          description: ServiceGroup Name. Required.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServiceGroupCollectionResponse"
