openapi: 3.0.0
servers:
  - url: https://{endpoint}
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme).
info:
  title: Monitoring Client
  description: MonitoringClient.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2019-11-01-preview-stackql-generated
  x-serviceAlias: synapse_monitoring
  x-sdkPackage: azure-synapse-monitoring
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    SparkJob:
      type: object
      description: SparkJob.
      properties:
        state:
          type: string
        name:
          type: string
        submitter:
          type: string
        compute:
          type: string
        sparkApplicationId:
          type: string
        livyId:
          type: string
        timing:
          type: array
          items:
            type: string
        sparkJobDefinition:
          type: string
        pipeline:
          type: array
          items:
            $ref: "#/components/schemas/SparkJob"
        jobType:
          type: string
        submitTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        queuedDuration:
          type: string
        runningDuration:
          type: string
        totalDuration:
          type: string
    SparkJobListViewResponse:
      type: object
      description: SparkJobListViewResponse.
      properties:
        nJobs:
          type: integer
        sparkJobs:
          type: array
          items:
            $ref: "#/components/schemas/SparkJob"
    SqlQueryStringDataModel:
      type: object
      description: SqlQueryStringDataModel.
      properties:
        query:
          type: string
  x-stackQL-resources:
    monitoring:
      id: azure.synapse_monitoring.monitoring
      name: monitoring
      title: monitoring
      methods:
        get_spark_job_list:
          operation:
            $ref: "#/paths/~1monitoring~1workloadTypes~1spark~1Applications?api-version=2019-11-01-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        get_sql_job_query_string:
          operation:
            $ref: "#/paths/~1monitoring~1workloadTypes~1sql~1querystring?api-version=2019-11-01-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/monitoring/methods/get_spark_job_list"
        insert: []
        update: []
        delete: []
paths:
  /monitoring/workloadTypes/spark/Applications?api-version=2019-11-01-preview:
    get:
      operationId: Monitoring_get_spark_job_list
      description: Get list of spark applications for the workspace.
      parameters:
        - name: x-ms-client-request-id
          in: header
          required: false
          schema:
            type: string
          description: Can provide a guid, which is helpful for debugging and to provide better customer support.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SparkJobListViewResponse"
  /monitoring/workloadTypes/sql/querystring?api-version=2019-11-01-preview:
    get:
      operationId: Monitoring_get_sql_job_query_string
      description: Get SQL OD/DW Query for the workspace.
      parameters:
        - name: filter
          in: query
          required: false
          schema:
            type: string
          description: ":type filter: str"
        - name: $orderby
          in: query
          required: false
          schema:
            type: string
          description: ":type orderby: str"
        - name: skip
          in: query
          required: false
          schema:
            type: string
          description: ":type skip: str"
        - name: x-ms-client-request-id
          in: header
          required: false
          schema:
            type: string
          description: Can provide a guid, which is helpful for debugging and to provide better customer support.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SqlQueryStringDataModel"
