openapi: 3.0.0
servers:
  - url: https://{endpoint}
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme).
info:
  title: Azure Synapse Analytics - Access Control (Data Plane)
  description: Workspace role assignments and definitions.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2020-12-01-stackql-generated
  x-serviceAlias: synapse_access_control
  x-sdkPackage: azure-synapse-accesscontrol
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    PagedRolesListResponse:
      type: object
      properties:
        value:
          type: array
          items:
            type: object
            properties: {}
        nextLink:
          type: string
    RoleAssignmentDetails:
      type: object
      description: Role Assignment response details.
      properties:
        id:
          type: string
        roleDefinitionId:
          type: string
        principalId:
          type: string
        scope:
          type: string
        principalType:
          type: string
    RoleAssignmentDetailsList:
      type: object
      description: Role Assignment response details.
      properties:
        count:
          type: integer
        value:
          type: array
          items:
            $ref: "#/components/schemas/RoleAssignmentDetails"
    SubjectInfo:
      type: object
      description: Subject details. All required parameters must be populated in order to send to Azure.
      properties:
        principalId:
          type: string
        groupIds:
          type: array
          items:
            type: string
      required:
        - principalId
    RequiredAction:
      type: object
      description: Action Info. All required parameters must be populated in order to send to Azure.
      properties:
        id:
          type: string
        isDataAction:
          type: boolean
      required:
        - id
        - isDataAction
    CheckAccessDecision:
      type: object
      description: Check access response details.
      properties:
        accessDecision:
          type: string
        actionId:
          type: string
        roleAssignment:
          $ref: "#/components/schemas/RoleAssignmentDetails"
    CheckPrincipalAccessResponse:
      type: object
      description: Check access response details.
      properties:
        accessDecisions:
          type: array
          items:
            $ref: "#/components/schemas/CheckAccessDecision"
    SynapseRbacPermission:
      type: object
      description: Synapse role definition details.
      properties:
        actions:
          type: array
          items:
            type: string
        notActions:
          type: array
          items:
            type: string
        dataActions:
          type: array
          items:
            type: string
        notDataActions:
          type: array
          items:
            type: string
    SynapseRoleDefinition:
      type: object
      description: Synapse role definition details.
      properties:
        id:
          type: string
        name:
          type: string
        isBuiltIn:
          type: boolean
        description:
          type: string
        permissions:
          type: array
          items:
            $ref: "#/components/schemas/SynapseRbacPermission"
        scopes:
          type: array
          items:
            type: string
        availabilityStatus:
          type: string
  x-stackQL-resources:
    role_definitions:
      id: azure.synapse_access_control.role_definitions
      name: role_definitions
      title: role_definitions
      methods:
        get_role_definitions:
          operation:
            $ref: "#/paths/~1rbac~1roles?api-version=2020-02-01-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.value
        get_role_definition_by_id:
          operation:
            $ref: "#/paths/~1rbac~1roles~1{role_id}?api-version=2020-02-01-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        list_role_definitions:
          operation:
            $ref: "#/paths/~1roleDefinitions?api-version=2020-12-01/get"
          response:
            openAPIDocKey: "200"
          request:
            nativeCasing: camel
        list_scopes:
          operation:
            $ref: "#/paths/~1rbacScopes?api-version=2020-12-01/get"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    role_assignments:
      id: azure.synapse_access_control.role_assignments
      name: role_assignments
      title: role_assignments
      methods:
        get_role_assignments:
          operation:
            $ref: "#/paths/~1rbac~1roleAssignments?api-version=2020-02-01-preview/get"
          response:
            openAPIDocKey: "200"
          request:
            nativeCasing: camel
        create_role_assignment:
          operation:
            $ref: "#/paths/~1rbac~1roleAssignments?api-version=2020-02-01-preview/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
        get_role_assignment_by_id:
          operation:
            $ref: "#/paths/~1rbac~1roleAssignments~1{role_assignment_id}?api-version=2020-02-01-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        delete_role_assignment_by_id:
          operation:
            $ref: "#/paths/~1rbac~1roleAssignments~1{role_assignment_id}?api-version=2020-02-01-preview/delete"
          response:
            openAPIDocKey: "200"
        list_role_assignments:
          operation:
            $ref: "#/paths/~1roleAssignments?api-version=2020-12-01/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.value
          request:
            nativeCasing: camel
        check_principal_access:
          operation:
            $ref: "#/paths/~1checkAccessSynapseRbac?api-version=2020-12-01/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/role_assignments/methods/check_principal_access"
          - $ref: "#/components/x-stackQL-resources/role_assignments/methods/get_role_assignment_by_id"
          - $ref: "#/components/x-stackQL-resources/role_assignments/methods/list_role_assignments"
        insert:
          - $ref: "#/components/x-stackQL-resources/role_assignments/methods/create_role_assignment"
        update: []
        delete: []
    caller_role_assignments:
      id: azure.synapse_access_control.caller_role_assignments
      name: caller_role_assignments
      title: caller_role_assignments
      methods:
        get_caller_role_assignments:
          operation:
            $ref: "#/paths/~1rbac~1getMyAssignedRoles?api-version=2020-02-01-preview/post"
          response:
            openAPIDocKey: "200"
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /rbac/roles?api-version=2020-02-01-preview:
    get:
      operationId: AccessControlClient_get_role_definitions
      description: List roles.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedRolesListResponse"
  /rbac/roles/{role_id}?api-version=2020-02-01-preview:
    get:
      operationId: AccessControlClient_get_role_definition_by_id
      description: Get role by role Id.
      parameters:
        - name: role_id
          in: path
          required: true
          schema:
            type: string
          description: Synapse Built-In Role Id.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties: {}
  /rbac/roleAssignments?api-version=2020-02-01-preview:
    get:
      operationId: AccessControlClient_get_role_assignments
      description: List role assignments.
      parameters:
        - name: roleId
          in: query
          required: false
          schema:
            type: string
          description: Synapse Built-In Role Id.
        - name: principalId
          in: query
          required: false
          schema:
            type: string
          description: Object ID of the AAD principal or security-group.
        - name: x-ms-continuation
          in: header
          required: false
          schema:
            type: string
          description: Continuation token.
      responses:
        "200":
          description: Success
    post:
      operationId: AccessControlClient_create_role_assignment
      description: Create role assignment.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoleAssignmentDetails"
  /rbac/roleAssignments/{role_assignment_id}?api-version=2020-02-01-preview:
    get:
      operationId: AccessControlClient_get_role_assignment_by_id
      description: Get role assignment by role assignment Id.
      parameters:
        - name: role_assignment_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the role assignment.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoleAssignmentDetails"
    delete:
      operationId: AccessControlClient_delete_role_assignment_by_id
      description: Delete role assignment by role assignment Id.
      parameters:
        - name: role_assignment_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the role assignment.
      responses:
        "200":
          description: Success
  /rbac/getMyAssignedRoles?api-version=2020-02-01-preview:
    post:
      operationId: AccessControlClient_get_caller_role_assignments
      description: List role assignments of the caller.
      parameters: []
      responses:
        "200":
          description: Success
  /roleAssignments?api-version=2020-12-01:
    get:
      operationId: RoleAssignments_list_role_assignments
      description: List role assignments.
      parameters:
        - name: roleId
          in: query
          required: false
          schema:
            type: string
          description: Synapse Built-In Role Id.
        - name: principalId
          in: query
          required: false
          schema:
            type: string
          description: Object ID of the AAD principal or security-group.
        - name: scope
          in: query
          required: false
          schema:
            type: string
          description: Scope of the Synapse Built-in Role.
        - name: x-ms-continuation
          in: header
          required: false
          schema:
            type: string
          description: Continuation token.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoleAssignmentDetailsList"
  /roleAssignments/{role_assignment_id}?api-version=2020-12-01:
    get:
      operationId: RoleAssignments_get_role_assignment_by_id
      description: Get role assignment by role assignment Id.
      parameters:
        - name: role_assignment_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the role assignment.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoleAssignmentDetails"
    put:
      operationId: RoleAssignments_create_role_assignment
      description: Create role assignment.
      parameters:
        - name: role_assignment_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the role assignment.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                roleId:
                  type: string
                principalId:
                  type: string
                scope:
                  type: string
                principalType:
                  type: string
              required:
                - roleId
                - principalId
                - scope
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoleAssignmentDetails"
    delete:
      operationId: RoleAssignments_delete_role_assignment_by_id
      description: Delete role assignment by role assignment Id.
      parameters:
        - name: role_assignment_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the role assignment.
        - name: scope
          in: query
          required: false
          schema:
            type: string
          description: Scope of the Synapse Built-in Role.
      responses:
        "200":
          description: Success
  /checkAccessSynapseRbac?api-version=2020-12-01:
    post:
      operationId: RoleAssignments_check_principal_access
      description: Check if the given principalId has access to perform list of actions at a given scope.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subject:
                  $ref: "#/components/schemas/SubjectInfo"
                actions:
                  type: array
                  items:
                    $ref: "#/components/schemas/RequiredAction"
                scope:
                  type: string
              required:
                - subject
                - actions
                - scope
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CheckPrincipalAccessResponse"
  /roleDefinitions?api-version=2020-12-01:
    get:
      operationId: RoleDefinitions_list_role_definitions
      description: List role definitions.
      parameters:
        - name: isBuiltIn
          in: query
          required: false
          schema:
            type: boolean
          description: Is a Synapse Built-In Role or not.
        - name: scope
          in: query
          required: false
          schema:
            type: string
          description: Scope of the Synapse Built-in Role.
      responses:
        "200":
          description: Success
  /rbacScopes?api-version=2020-12-01:
    get:
      operationId: RoleDefinitions_list_scopes
      description: List rbac scopes.
      parameters: []
      responses:
        "200":
          description: Success
  /roleDefinitions/{role_definition_id}?api-version=2020-12-01:
    get:
      operationId: RoleDefinitions_get_role_definition_by_id
      description: Get role definition by role definition Id.
      parameters:
        - name: role_definition_id
          in: path
          required: true
          schema:
            type: string
          description: Synapse Built-In Role Definition Id.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SynapseRoleDefinition"
