openapi: 3.0.0
servers:
  - url: https://{endpoint}
    variables:
      endpoint:
        default: ""
        description: The service endpoint host (no scheme).
info:
  title: _ S D K Client
  description: This is the Microsoft Azure Synapse Managed Private Endpoints Client Library.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2021-06-01-preview-stackql-generated
  x-serviceAlias: synapse_managedprivateendpoints
  x-sdkPackage: azure-synapse-managedprivateendpoints
  x-plane: data
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    ManagedPrivateEndpointProperties:
      type: object
      description: Properties of a managed private endpoint. Variables are only populated by the server, and will be ignored when sending a request.
      properties:
        name:
          type: string
        privateLinkResourceId:
          type: string
        groupId:
          type: string
        provisioningState:
          type: string
          description: The managed private endpoint provisioning state.
        connectionState:
          $ref: "#/components/schemas/ManagedPrivateEndpointConnectionState"
        isReserved:
          type: boolean
          description: Denotes whether the managed private endpoint is reserved.
        fqdns:
          type: array
          items:
            type: string
        isCompliant:
          type: boolean
    ManagedPrivateEndpointConnectionState:
      type: object
      description: The connection state of a managed private endpoint. Variables are only populated by the server, and will be ignored when sending a request.
      properties:
        status:
          type: string
          description: The approval status.
        description:
          type: string
        actionsRequired:
          type: string
    ManagedPrivateEndpointFlattened:
      type: object
      description: Flattened view of ManagedPrivateEndpoint ('properties' hoisted to the top level).
      properties:
        id:
          type: string
          description: Fully qualified resource Id for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
        name:
          type: string
          description: The name of the resource.
        type:
          type: string
          description: The type of the resource. Ex- Microsoft.Compute/virtualMachines or Microsoft.Storage/storageAccounts.
        privateLinkResourceId:
          type: string
        groupId:
          type: string
        provisioningState:
          type: string
          description: The managed private endpoint provisioning state.
        connectionState:
          $ref: "#/components/schemas/ManagedPrivateEndpointConnectionState"
        isReserved:
          type: boolean
          description: Denotes whether the managed private endpoint is reserved.
        fqdns:
          type: array
          items:
            type: string
        isCompliant:
          type: boolean
    ManagedPrivateEndpoint:
      type: object
      description: Managed private endpoint. Variables are only populated by the server, and will be ignored when sending a request.
      properties:
        id:
          type: string
          description: Fully qualified resource Id for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}.
        name:
          type: string
          description: The name of the resource.
        type:
          type: string
          description: The type of the resource. Ex- Microsoft.Compute/virtualMachines or Microsoft.Storage/storageAccounts.
        properties:
          $ref: "#/components/schemas/ManagedPrivateEndpointProperties"
    ManagedPrivateEndpointListResponse:
      type: object
      description: A list of managed private endpoints. Variables are only populated by the server, and will be ignored when sending a request.
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/ManagedPrivateEndpoint"
        nextLink:
          type: string
          description: The link to the next page of results, if any remaining results exist.
    PagedManagedPrivateEndpointListResponse:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/ManagedPrivateEndpointListResponse"
        nextLink:
          type: string
  x-stackQL-resources:
    managed_private_endpoints:
      id: azure.synapse_managedprivateendpoints.managed_private_endpoints
      name: managed_private_endpoints
      title: managed_private_endpoints
      methods:
        get:
          operation:
            $ref: "#/paths/~1managedVirtualNetworks~1{managed_virtual_network_name}~1managedPrivateEndpoints~1{managed_private_endpoint_name}?api-version=2021-06-01-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            overrideMediaType: application/json
            transform:
              type: golang_template_json_v0.3.0
              body: '{{ $row := . }}{ {{ $p := index $row "properties" }}{{ if eq (kindOf $p) "map" }}{{ range $k, $v := $p }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}{{ end }}{{ range $k, $v := $row }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}"_flattened": true }'
        create:
          operation:
            $ref: "#/paths/~1managedVirtualNetworks~1{managed_virtual_network_name}~1managedPrivateEndpoints~1{managed_private_endpoint_name}?api-version=2021-06-01-preview/put"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
        delete:
          operation:
            $ref: "#/paths/~1managedVirtualNetworks~1{managed_virtual_network_name}~1managedPrivateEndpoints~1{managed_private_endpoint_name}?api-version=2021-06-01-preview/delete"
          response:
            openAPIDocKey: "204"
        list:
          operation:
            $ref: "#/paths/~1managedVirtualNetworks~1{managed_virtual_network_name}~1managedPrivateEndpoints?api-version=2021-06-01-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.value
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/managed_private_endpoints/methods/get"
          - $ref: "#/components/x-stackQL-resources/managed_private_endpoints/methods/list"
        insert:
          - $ref: "#/components/x-stackQL-resources/managed_private_endpoints/methods/create"
        update: []
        delete:
          - $ref: "#/components/x-stackQL-resources/managed_private_endpoints/methods/delete"
paths:
  /managedVirtualNetworks/{managed_virtual_network_name}/managedPrivateEndpoints/{managed_private_endpoint_name}?api-version=2021-06-01-preview:
    get:
      operationId: ManagedPrivateEndpoints_get
      description: Get Managed Private Endpoints.
      parameters:
        - name: managed_private_endpoint_name
          in: path
          required: true
          schema:
            type: string
          description: Managed private endpoint name.
        - name: managed_virtual_network_name
          in: path
          required: true
          schema:
            type: string
          description: Managed virtual network name.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagedPrivateEndpointFlattened"
    put:
      operationId: ManagedPrivateEndpoints_create
      description: Create Managed Private Endpoints.
      parameters:
        - name: managed_private_endpoint_name
          in: path
          required: true
          schema:
            type: string
          description: Managed private endpoint name.
        - name: managed_virtual_network_name
          in: path
          required: true
          schema:
            type: string
          description: Managed virtual network name.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                properties:
                  $ref: "#/components/schemas/ManagedPrivateEndpointProperties"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagedPrivateEndpoint"
    delete:
      operationId: ManagedPrivateEndpoints_delete
      description: Delete Managed Private Endpoints.
      parameters:
        - name: managed_private_endpoint_name
          in: path
          required: true
          schema:
            type: string
          description: Managed private endpoint name.
        - name: managed_virtual_network_name
          in: path
          required: true
          schema:
            type: string
          description: Managed virtual network name.
      responses:
        "204":
          description: Success (no content / accepted)
  /managedVirtualNetworks/{managed_virtual_network_name}/managedPrivateEndpoints?api-version=2021-06-01-preview:
    get:
      operationId: ManagedPrivateEndpoints_list
      description: List Managed Private Endpoints.
      parameters:
        - name: managed_virtual_network_name
          in: path
          required: true
          schema:
            type: string
          description: Managed virtual network name.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedManagedPrivateEndpointListResponse"
