openapi: 3.0.3
servers:
  - url: 'https://api.vercel.com'
    description: Production API
info:
  contact:
    email: support@vercel.com
    name: Vercel Support
    url: 'https://vercel.com/support'
  version: 0.0.1
  title: Vercel API - billing_settings
  description: billing_settings
components:
  schemas: {}
  responses: {}
  securitySchemes:
    bearerToken:
      type: http
      description: Default authentication mechanism
      scheme: bearer
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://api.vercel.com/oauth/authorize'
          tokenUrl: 'https://api.vercel.com/oauth/access_token'
          scopes: {}
  x-stackQL-resources:
    data_cache:
      id: vercel.billing_settings.data_cache
      name: data_cache
      title: Data Cache
      methods:
        enable_excess_billing:
          operation:
            $ref: '#/paths/~1data-cache~1billing-settings/patch'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /data-cache/billing-settings:
    patch:
      description: ''
      operationId: enableExcessBilling
      security: []
      tags:
        - billing_settings
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                properties:
                  excessBillingEnabled:
                    type: boolean
                type: object
        '400':
          description: One of the provided values in the request body is invalid.
        '401':
          description: ''
        '403':
          description: You do not have permission to access this resource.
        '404':
          description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                excessBillingEnabled:
                  type: boolean
