openapi: 3.0.3
servers:
  - url: 'https://api.vercel.com'
    description: Production API
info:
  contact:
    email: support@vercel.com
    name: Vercel Support
    url: 'https://vercel.com/support'
  version: 0.0.1
  title: Vercel API - cache
  description: cache
components:
  schemas: {}
  responses: {}
  securitySchemes:
    bearerToken:
      type: http
      description: Default authentication mechanism
      scheme: bearer
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://api.vercel.com/oauth/authorize'
          tokenUrl: 'https://api.vercel.com/oauth/access_token'
          scopes: {}
  x-stackQL-resources:
    data_cache_purge_all:
      id: vercel.cache.data_cache_purge_all
      name: data_cache_purge_all
      title: Data Cache Purge All
      methods:
        purge_all:
          operation:
            $ref: '#/paths/~1data-cache~1purge-all/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /data-cache/purge-all:
    delete:
      description: ''
      operationId: purgeAll
      security: []
      tags:
        - cache
      responses:
        '200':
          description: ''
        '400':
          description: One of the provided values in the request query is invalid.
        '401':
          description: ''
        '403':
          description: You do not have permission to access this resource.
        '404':
          description: ''
      parameters:
        - name: projectIdOrName
          in: query
          required: true
          schema:
            type: string
