openapi: 3.0.3
servers:
  - url: 'https://api.vercel.com'
    description: Production API
info:
  contact:
    email: support@vercel.com
    name: Vercel Support
    url: 'https://vercel.com/support'
  version: 0.0.1
  title: Vercel API - certs
  description: certs
components:
  schemas: {}
  responses: {}
  securitySchemes:
    bearerToken:
      type: http
      description: Default authentication mechanism
      scheme: bearer
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://api.vercel.com/oauth/authorize'
          tokenUrl: 'https://api.vercel.com/oauth/access_token'
          scopes: {}
  x-stackQL-resources:
    certs:
      id: vercel.certs.certs
      name: certs
      title: Certs
      methods:
        get_cert_by_id:
          operation:
            $ref: '#/paths/~1v7~1certs~1{id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        remove_cert:
          operation:
            $ref: '#/paths/~1v7~1certs~1{id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        issue_cert:
          operation:
            $ref: '#/paths/~1v7~1certs/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        upload_cert:
          operation:
            $ref: '#/paths/~1v7~1certs/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/certs/methods/get_cert_by_id'
        insert: []
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/certs/methods/remove_cert'
paths:
  '/v7/certs/{id}':
    get:
      description: Get cert by id
      operationId: getCertById
      security:
        - bearerToken: []
      summary: Get cert by id
      tags:
        - certs
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                  createdAt:
                    type: number
                  expiresAt:
                    type: number
                  autoRenew:
                    type: boolean
                  cns:
                    items:
                      type: string
                    type: array
                required:
                  - id
                  - createdAt
                  - expiresAt
                  - autoRenew
                  - cns
                type: object
        '400':
          description: One of the provided values in the request query is invalid.
        '401':
          description: ''
        '403':
          description: You do not have permission to access this resource.
        '404':
          description: ''
      parameters:
        - name: id
          description: The cert id
          in: path
          required: true
          schema:
            description: The cert id
            type: string
        - description: The Team identifier or slug to perform the request on behalf of.
          in: query
          name: teamId
          required: true
          schema:
            type: string
    delete:
      description: Remove cert
      operationId: removeCert
      security:
        - bearerToken: []
      summary: Remove cert
      tags:
        - certs
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
        '400':
          description: One of the provided values in the request query is invalid.
        '401':
          description: ''
        '403':
          description: You do not have permission to access this resource.
        '404':
          description: ''
      parameters:
        - name: id
          description: The cert id to remove
          in: path
          required: true
          schema:
            description: The cert id to remove
            type: string
        - description: The Team identifier or slug to perform the request on behalf of.
          in: query
          name: teamId
          required: true
          schema:
            type: string
  /v7/certs:
    post:
      description: Issue a new cert
      operationId: issueCert
      security:
        - bearerToken: []
      summary: Issue a new cert
      tags:
        - certs
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                  createdAt:
                    type: number
                  expiresAt:
                    type: number
                  autoRenew:
                    type: boolean
                  cns:
                    items:
                      type: string
                    type: array
                required:
                  - id
                  - createdAt
                  - expiresAt
                  - autoRenew
                  - cns
                type: object
        '400':
          description: One of the provided values in the request body is invalid.
        '401':
          description: ''
        '402':
          description: |-
            The account was soft-blocked for an unhandled reason.
            The account is missing a payment so payment method must be updated
        '403':
          description: You do not have permission to access this resource.
        '404':
          description: ''
        '449':
          description: ''
        '500':
          description: ''
      parameters:
        - description: The Team identifier or slug to perform the request on behalf of.
          in: query
          name: teamId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cns:
                  description: The common names the cert should be issued for
                  type: array
                  items:
                    type: string
    put:
      description: Upload a cert
      operationId: uploadCert
      security:
        - bearerToken: []
      summary: Upload a cert
      tags:
        - certs
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                  createdAt:
                    type: number
                  expiresAt:
                    type: number
                  autoRenew:
                    type: boolean
                  cns:
                    items:
                      type: string
                    type: array
                required:
                  - id
                  - createdAt
                  - expiresAt
                  - autoRenew
                  - cns
                type: object
        '400':
          description: One of the provided values in the request body is invalid.
        '401':
          description: ''
        '402':
          description: This feature is only available for Enterprise customers.
        '403':
          description: You do not have permission to access this resource.
      parameters:
        - description: The Team identifier or slug to perform the request on behalf of.
          in: query
          name: teamId
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - ca
                - key
                - cert
              additionalProperties: false
              properties:
                ca:
                  type: string
                  description: The certificate authority
                key:
                  type: string
                  description: The certificate key
                cert:
                  type: string
                  description: The certificate
                skipValidation:
                  type: boolean
                  description: Skip validation of the certificate
