openapi: 3.0.3
info:
  title: certs API
  description: vercel certs API
  version: 0.0.1
paths:
  /v8/certs/{id}:
    get:
      description: Get cert by id
      operationId: getCertById
      security:
        - bearerToken: []
      summary: Get cert by id
      tags:
        - certs
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                  createdAt:
                    type: number
                  expiresAt:
                    type: number
                  autoRenew:
                    type: boolean
                    enum:
                      - false
                      - true
                  cns:
                    items:
                      type: string
                    type: array
                required:
                  - autoRenew
                  - cns
                  - createdAt
                  - expiresAt
                  - id
                type: object
        '400':
          description: One of the provided values in the request query is invalid.
        '401':
          description: The request is not authorized.
        '403':
          description: You do not have permission to access this resource.
        '404':
          description: ''
        '410':
          description: ''
      x-vercel-cli:
        supportedSubcommands: true
        supportedProduction: false
      parameters:
        - name: id
          description: The cert id
          in: path
          required: true
          schema:
            description: The cert id
            type: string
          x-vercel-cli:
            kind: argument
        - description: The Team identifier to perform the request on behalf of.
          in: query
          name: teamId
          schema:
            type: string
            example: team_1a2b3c4d5e6f7g8h9i0j1k2l
        - description: The Team slug to perform the request on behalf of.
          in: query
          name: slug
          schema:
            type: string
            example: my-team-url-slug
    delete:
      description: Remove cert
      operationId: removeCert
      security:
        - bearerToken: []
      summary: Remove cert
      tags:
        - certs
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: string
                description: (opaque JSON object)
        '400':
          description: One of the provided values in the request query is invalid.
        '401':
          description: The request is not authorized.
        '403':
          description: You do not have permission to access this resource.
        '404':
          description: ''
        '410':
          description: ''
      x-vercel-cli:
        supportedSubcommands: true
        supportedProduction: false
      parameters:
        - name: id
          description: The cert id to remove
          in: path
          required: true
          schema:
            description: The cert id to remove
            type: string
          x-vercel-cli:
            kind: argument
        - description: The Team identifier to perform the request on behalf of.
          in: query
          name: teamId
          schema:
            type: string
            example: team_1a2b3c4d5e6f7g8h9i0j1k2l
        - description: The Team slug to perform the request on behalf of.
          in: query
          name: slug
          schema:
            type: string
            example: my-team-url-slug
  /v8/certs:
    get:
      description: Get certs
      operationId: getCerts
      security:
        - bearerToken: []
      summary: Get certs
      tags:
        - certs
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                properties:
                  certs:
                    items:
                      properties:
                        id:
                          type: string
                        createdAt:
                          type: number
                        expiresAt:
                          type: number
                        autoRenew:
                          type: boolean
                          enum:
                            - false
                            - true
                        cns:
                          items:
                            type: string
                          type: array
                      required:
                        - autoRenew
                        - cns
                        - createdAt
                        - expiresAt
                        - id
                      type: object
                    type: array
                  pagination:
                    $ref: '#/components/schemas/Pagination'
                required:
                  - certs
                  - pagination
                type: object
        '400':
          description: ''
        '401':
          description: The request is not authorized.
        '403':
          description: You do not have permission to access this resource.
        '410':
          description: ''
      parameters:
        - description: The Team identifier to perform the request on behalf of.
          in: query
          name: teamId
          schema:
            type: string
            example: team_1a2b3c4d5e6f7g8h9i0j1k2l
        - description: The Team slug to perform the request on behalf of.
          in: query
          name: slug
          schema:
            type: string
            example: my-team-url-slug
    post:
      description: Issue a new cert
      operationId: issueCert
      security:
        - bearerToken: []
      summary: Issue a new cert
      tags:
        - certs
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                  createdAt:
                    type: number
                  expiresAt:
                    type: number
                  autoRenew:
                    type: boolean
                    enum:
                      - false
                      - true
                  cns:
                    items:
                      type: string
                    type: array
                required:
                  - autoRenew
                  - cns
                  - createdAt
                  - expiresAt
                  - id
                type: object
        '400':
          description: One of the provided values in the request body is invalid.
        '401':
          description: The request is not authorized.
        '402':
          description: The account is missing a payment so payment method must be updated
        '403':
          description: You do not have permission to access this resource.
        '404':
          description: ''
        '410':
          description: ''
        '449':
          description: ''
        '500':
          description: ''
      x-vercel-cli:
        supportedSubcommands: true
        supportedProduction: false
        aliases:
          - issue
        bodyArguments:
          - cns
      parameters:
        - description: The Team identifier to perform the request on behalf of.
          in: query
          name: teamId
          schema:
            type: string
            example: team_1a2b3c4d5e6f7g8h9i0j1k2l
        - description: The Team slug to perform the request on behalf of.
          in: query
          name: slug
          schema:
            type: string
            example: my-team-url-slug
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cns:
                  description: The common names the cert should be issued for
                  type: array
                  items:
                    type: string
    put:
      description: Upload a cert
      operationId: uploadCert
      security:
        - bearerToken: []
      summary: Upload a cert
      tags:
        - certs
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                  createdAt:
                    type: number
                  expiresAt:
                    type: number
                  autoRenew:
                    type: boolean
                    enum:
                      - false
                      - true
                  cns:
                    items:
                      type: string
                    type: array
                required:
                  - autoRenew
                  - cns
                  - createdAt
                  - expiresAt
                  - id
                type: object
        '400':
          description: One of the provided values in the request body is invalid.
        '401':
          description: The request is not authorized.
        '402':
          description: This feature is only available for Enterprise customers.
        '403':
          description: You do not have permission to access this resource.
        '410':
          description: ''
      x-vercel-cli:
        supportedSubcommands: true
        supportedProduction: false
        aliases:
          - add
      parameters:
        - description: The Team identifier to perform the request on behalf of.
          in: query
          name: teamId
          schema:
            type: string
            example: team_1a2b3c4d5e6f7g8h9i0j1k2l
        - description: The Team slug to perform the request on behalf of.
          in: query
          name: slug
          schema:
            type: string
            example: my-team-url-slug
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - ca
                - key
                - cert
              additionalProperties: false
              properties:
                ca:
                  type: string
                  description: The certificate authority
                key:
                  type: string
                  description: The certificate key
                cert:
                  type: string
                  description: The certificate
                skipValidation:
                  type: boolean
                  description: Skip validation of the certificate
components:
  schemas:
    Pagination:
      properties:
        count:
          type: number
          description: Amount of items in the current page.
          example: 20
        next:
          nullable: true
          type: number
          description: Timestamp that must be used to request the next page.
          example: 1540095775951
        prev:
          nullable: true
          type: number
          description: Timestamp that must be used to request the previous page.
          example: 1540095775951
      required:
        - count
        - next
        - prev
      type: object
      description: This object contains information related to the pagination of the current request, including the necessary parameters to get the next or previous page of data.
  x-stackQL-resources:
    certs:
      id: vercel.certs.certs
      name: certs
      title: Certs
      methods:
        get:
          operation:
            $ref: '#/paths/~1v8~1certs~1{id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
          request:
            nativeCasing: camel
        delete:
          operation:
            $ref: '#/paths/~1v8~1certs~1{id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
          request:
            nativeCasing: camel
        list:
          operation:
            $ref: '#/paths/~1v8~1certs/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.certs
          request:
            nativeCasing: camel
        issue:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1v8~1certs/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
          request:
            nativeCasing: camel
        upload:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1v8~1certs/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
          request:
            nativeCasing: camel
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/certs/methods/get'
          - $ref: '#/components/x-stackQL-resources/certs/methods/list'
        insert:
          - $ref: '#/components/x-stackQL-resources/certs/methods/issue'
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/certs/methods/delete'
        replace: []
servers:
  - url: https://api.vercel.com
