openapi: 3.0.3
info:
  title: edge_cache API
  description: vercel edge_cache API
  version: 0.0.1
paths:
  /v1/edge-cache/invalidate-by-tags:
    post:
      description: Marks a cache tag as stale, causing cache entries associated with that tag to be revalidated in the background on the next request.
      operationId: invalidateByTags
      security:
        - bearerToken: []
      summary: Invalidate by tag
      tags:
        - edge-cache
      responses:
        '200':
          description: ''
        '400':
          description: |-
            One of the provided values in the request body is invalid.
            One of the provided values in the request query is invalid.
        '401':
          description: The request is not authorized.
        '403':
          description: You do not have permission to access this resource.
        '404':
          description: ''
        '410':
          description: ''
      parameters:
        - name: projectIdOrName
          in: query
          required: true
          schema:
            type: string
        - description: The Team identifier to perform the request on behalf of.
          in: query
          name: teamId
          schema:
            type: string
            example: team_1a2b3c4d5e6f7g8h9i0j1k2l
        - description: The Team slug to perform the request on behalf of.
          in: query
          name: slug
          schema:
            type: string
            example: my-team-url-slug
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              type: object
              required:
                - tags
              properties:
                tags:
                  items:
                    maxLength: 256
                    type: string
                  maxItems: 16
                  minItems: 1
                  type: array
                  maxLength: 8196
                target:
                  enum:
                    - production
                    - preview
                  type: string
  /v1/edge-cache/dangerously-delete-by-tags:
    post:
      description: Marks a cache tag as deleted, causing cache entries associated with that tag to be revalidated in the foreground on the next request. Use this method with caution because one tag can be associated with many paths and deleting the cache can cause many concurrent requests to the origin leading to cache stampede problem. This method is for advanced use cases and is not recommended; prefer using `invalidateByTag` instead.
      operationId: dangerouslyDeleteByTags
      security:
        - bearerToken: []
      summary: Dangerously delete by tag
      tags:
        - edge-cache
      responses:
        '200':
          description: ''
        '400':
          description: |-
            One of the provided values in the request body is invalid.
            One of the provided values in the request query is invalid.
        '401':
          description: The request is not authorized.
        '403':
          description: You do not have permission to access this resource.
        '404':
          description: ''
        '410':
          description: ''
      parameters:
        - name: projectIdOrName
          in: query
          required: true
          schema:
            type: string
        - description: The Team identifier to perform the request on behalf of.
          in: query
          name: teamId
          schema:
            type: string
            example: team_1a2b3c4d5e6f7g8h9i0j1k2l
        - description: The Team slug to perform the request on behalf of.
          in: query
          name: slug
          schema:
            type: string
            example: my-team-url-slug
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              type: object
              required:
                - tags
              properties:
                revalidationDeadlineSeconds:
                  minimum: 0
                  maximum: 31536000
                  type: integer
                tags:
                  items:
                    maxLength: 256
                    type: string
                  maxItems: 16
                  minItems: 1
                  type: array
                  maxLength: 8196
                target:
                  enum:
                    - production
                    - preview
                  type: string
  /v1/edge-cache/invalidate-by-src-images:
    post:
      description: Marks a source image as stale, causing its corresponding transformed images to be revalidated in the background on the next request.
      operationId: invalidateBySrcImages
      security:
        - bearerToken: []
      summary: Invalidate by source image
      tags:
        - edge-cache
      responses:
        '200':
          description: ''
        '400':
          description: |-
            One of the provided values in the request body is invalid.
            One of the provided values in the request query is invalid.
        '401':
          description: The request is not authorized.
        '402':
          description: ''
        '403':
          description: You do not have permission to access this resource.
        '404':
          description: ''
        '410':
          description: ''
      parameters:
        - name: projectIdOrName
          in: query
          required: true
          schema:
            type: string
        - description: The Team identifier to perform the request on behalf of.
          in: query
          name: teamId
          schema:
            type: string
            example: team_1a2b3c4d5e6f7g8h9i0j1k2l
        - description: The Team slug to perform the request on behalf of.
          in: query
          name: slug
          schema:
            type: string
            example: my-team-url-slug
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              type: object
              required:
                - srcImages
              properties:
                srcImages:
                  items:
                    type: string
                  maxItems: 8
                  minItems: 1
                  type: array
  /v1/edge-cache/dangerously-delete-by-src-images:
    post:
      description: Marks a source image as deleted, causing cache entries associated with that source image to be revalidated in the foreground on the next request. Use this method with caution because one source image can be associated with many paths and deleting the cache can cause many concurrent requests to the origin leading to cache stampede problem. This method is for advanced use cases and is not recommended; prefer using `invalidateBySrcImage` instead.
      operationId: dangerouslyDeleteBySrcImages
      security:
        - bearerToken: []
      summary: Dangerously delete by source image
      tags:
        - edge-cache
      responses:
        '200':
          description: ''
        '400':
          description: |-
            One of the provided values in the request body is invalid.
            One of the provided values in the request query is invalid.
        '401':
          description: The request is not authorized.
        '402':
          description: ''
        '403':
          description: You do not have permission to access this resource.
        '404':
          description: ''
        '410':
          description: ''
      parameters:
        - name: projectIdOrName
          in: query
          required: true
          schema:
            type: string
        - description: The Team identifier to perform the request on behalf of.
          in: query
          name: teamId
          schema:
            type: string
            example: team_1a2b3c4d5e6f7g8h9i0j1k2l
        - description: The Team slug to perform the request on behalf of.
          in: query
          name: slug
          schema:
            type: string
            example: my-team-url-slug
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              type: object
              required:
                - srcImages
              properties:
                revalidationDeadlineSeconds:
                  minimum: 0
                  maximum: 31536000
                  type: integer
                srcImages:
                  items:
                    type: string
                  maxItems: 8
                  minItems: 1
                  type: array
components:
  x-stackQL-resources:
    cache:
      id: vercel.edge_cache.cache
      name: cache
      title: Cache
      methods:
        invalidate_by_tags:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1v1~1edge-cache~1invalidate-by-tags/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
          request:
            nativeCasing: camel
        delete_by_tags:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1v1~1edge-cache~1dangerously-delete-by-tags/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
          request:
            nativeCasing: camel
        invalidate_by_src_images:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1v1~1edge-cache~1invalidate-by-src-images/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
          request:
            nativeCasing: camel
        delete_by_src_images:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1v1~1edge-cache~1dangerously-delete-by-src-images/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
          request:
            nativeCasing: camel
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
        replace: []
servers:
  - url: https://api.vercel.com
