openapi: 3.0.3
info:
  title: project_members API
  description: vercel project_members API
  version: 0.0.1
paths:
  /v1/projects/{id_or_name}/members:
    get:
      description: Lists all members of a project.
      operationId: getProjectMembers
      security:
        - bearerToken: []
      summary: List project members
      tags:
        - projectMembers
      responses:
        '200':
          description: Paginated list of members for the project.
          content:
            application/json:
              schema:
                properties:
                  members:
                    items:
                      properties:
                        avatar:
                          type: string
                          description: ID of the file for the Avatar of this member.
                          example: 123a6c5209bc3778245d011443644c8d27dc2c50
                        email:
                          type: string
                          description: The email of this member.
                          example: jane.doe@example.com
                        role:
                          type: string
                          enum:
                            - ADMIN
                            - PROJECT_DEVELOPER
                            - PROJECT_GUEST
                            - PROJECT_VIEWER
                          description: Role of this user in the project.
                          example: ADMIN
                        computedProjectRole:
                          type: string
                          enum:
                            - ADMIN
                            - PROJECT_DEVELOPER
                            - PROJECT_GUEST
                            - PROJECT_VIEWER
                          description: Role of this user in the project.
                          example: ADMIN
                        uid:
                          type: string
                          description: The ID of this user.
                          example: zTuNVUXEAvvnNN3IaqinkyMw
                        username:
                          type: string
                          description: The unique username of this user.
                          example: jane-doe
                        name:
                          type: string
                          description: The name of this user.
                          example: Jane Doe
                        createdAt:
                          type: number
                          description: Timestamp in milliseconds when this member was added.
                          example: 1588720733602
                        teamRole:
                          type: string
                          enum:
                            - BILLING
                            - CONTRIBUTOR
                            - DEVELOPER
                            - MEMBER
                            - OWNER
                            - SECURITY
                            - VIEWER
                            - VIEWER_FOR_PLUS
                          description: The role of this user in the team.
                          example: CONTRIBUTOR
                      required:
                        - computedProjectRole
                        - createdAt
                        - email
                        - role
                        - teamRole
                        - uid
                        - username
                      type: object
                    type: array
                  pagination:
                    properties:
                      hasNext:
                        type: boolean
                        enum:
                          - false
                          - true
                      count:
                        type: number
                        description: Amount of items in the current page.
                        example: 20
                      next:
                        nullable: true
                        type: number
                        description: Timestamp that must be used to request the next page.
                        example: 1540095775951
                      prev:
                        nullable: true
                        type: number
                        description: Timestamp that must be used to request the previous page.
                        example: 1540095775951
                    required:
                      - count
                      - hasNext
                      - next
                      - prev
                    type: object
                required:
                  - members
                  - pagination
                type: object
                description: Paginated list of members for the project.
        '400':
          description: One of the provided values in the request query is invalid.
        '401':
          description: The request is not authorized.
        '403':
          description: You do not have permission to access this resource.
        '410':
          description: ''
      parameters:
        - name: id_or_name
          description: The ID or name of the Project.
          in: path
          required: true
          schema:
            type: string
            description: The ID or name of the Project.
            example: prj_pavWOn1iLObbXLRiwVvzmPrTWyTf
        - name: limit
          description: Limit how many project members should be returned
          in: query
          required: false
          schema:
            description: Limit how many project members should be returned
            example: 20
            type: integer
            minimum: 1
            maximum: 100
        - name: since
          description: Timestamp in milliseconds to only include members added since then.
          in: query
          required: false
          schema:
            description: Timestamp in milliseconds to only include members added since then.
            example: 1540095775951
            type: integer
        - name: until
          description: Timestamp in milliseconds to only include members added until then.
          in: query
          required: false
          schema:
            description: Timestamp in milliseconds to only include members added until then.
            example: 1540095775951
            type: integer
        - name: search
          description: Search project members by their name, username, and email.
          in: query
          required: false
          schema:
            description: Search project members by their name, username, and email.
            type: string
        - description: The Team identifier to perform the request on behalf of.
          in: query
          name: teamId
          schema:
            type: string
            example: team_1a2b3c4d5e6f7g8h9i0j1k2l
        - description: The Team slug to perform the request on behalf of.
          in: query
          name: slug
          schema:
            type: string
            example: my-team-url-slug
      x-speakeasy-test: false
    post:
      description: Adds a new member to the project.
      operationId: addProjectMember
      security:
        - bearerToken: []
      summary: Adds a new member to a project.
      tags:
        - projectMembers
      responses:
        '200':
          description: Responds with the project ID on success.
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                required:
                  - id
                type: object
                description: Responds with the project ID on success.
        '400':
          description: |-
            One of the provided values in the request body is invalid.
            One of the provided values in the request query is invalid.
        '401':
          description: The request is not authorized.
        '403':
          description: You do not have permission to access this resource.
        '410':
          description: ''
        '500':
          description: ''
      parameters:
        - name: id_or_name
          description: The ID or name of the Project.
          in: path
          required: true
          schema:
            type: string
            description: The ID or name of the Project.
            example: prj_pavWOn1iLObbXLRiwVvzmPrTWyTf
        - description: The Team identifier to perform the request on behalf of.
          in: query
          name: teamId
          schema:
            type: string
            example: team_1a2b3c4d5e6f7g8h9i0j1k2l
        - description: The Team slug to perform the request on behalf of.
          in: query
          name: slug
          schema:
            type: string
            example: my-team-url-slug
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - role
                - uid
                - username
                - email
              properties:
                uid:
                  type: string
                  maxLength: 256
                  example: ndlgr43fadlPyCtREAqxxdyFK
                  description: The ID of the team member that should be added to this project.
                username:
                  type: string
                  maxLength: 256
                  example: example
                  description: The username of the team member that should be added to this project.
                email:
                  type: string
                  format: email
                  example: entity@example.com
                  description: The email of the team member that should be added to this project.
                role:
                  type: string
                  example: ADMIN
                  description: The project role of the member that will be added.
                  enum:
                    - ADMIN
                    - PROJECT_VIEWER
                    - PROJECT_DEVELOPER
        required: true
  /v1/projects/{id_or_name}/members/{uid}:
    delete:
      description: Remove a member from a specific project
      operationId: removeProjectMember
      security:
        - bearerToken: []
      summary: Remove a Project Member
      tags:
        - projectMembers
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                required:
                  - id
                type: object
        '400':
          description: One of the provided values in the request query is invalid.
        '401':
          description: The request is not authorized.
        '403':
          description: You do not have permission to access this resource.
        '410':
          description: ''
      parameters:
        - name: id_or_name
          description: The ID or name of the Project.
          in: path
          required: true
          schema:
            type: string
            description: The ID or name of the Project.
            example: prj_pavWOn1iLObbXLRiwVvzmPrTWyTf
        - name: uid
          description: The user ID of the member.
          in: path
          required: true
          schema:
            type: string
            description: The user ID of the member.
            example: ndlgr43fadlPyCtREAqxxdyFK
        - description: The Team identifier to perform the request on behalf of.
          in: query
          name: teamId
          schema:
            type: string
            example: team_1a2b3c4d5e6f7g8h9i0j1k2l
        - description: The Team slug to perform the request on behalf of.
          in: query
          name: slug
          schema:
            type: string
            example: my-team-url-slug
components:
  x-stackQL-resources:
    members:
      id: vercel.project_members.members
      name: members
      title: Members
      methods:
        list:
          operation:
            $ref: '#/paths/~1v1~1projects~1{id_or_name}~1members/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.members
          request:
            nativeCasing: camel
          config:
            pagination:
              requestToken:
                key: until
                location: query
              responseToken:
                key: $.pagination.next
                location: body
            queryParamPushdown:
              top:
                paramName: limit
                maxValue: 100
        add:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1v1~1projects~1{id_or_name}~1members/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
          request:
            nativeCasing: camel
        remove:
          operation:
            $ref: '#/paths/~1v1~1projects~1{id_or_name}~1members~1{uid}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
          request:
            nativeCasing: camel
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/members/methods/list'
        insert:
          - $ref: '#/components/x-stackQL-resources/members/methods/add'
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/members/methods/remove'
        replace: []
servers:
  - url: https://api.vercel.com
