components:
  schemas:
    GroupSchema:
      properties:
        $schema:
          readOnly: true
          type: string
        _links:
          additionalProperties:
            properties: {}
            type: object
          readOnly: true
          type: object
        created:
          readOnly: true
          type: string
        definitions:
          $ref: '#/components/schemas/GroupSchemaDefinitions'
        description:
          type: string
        id:
          readOnly: true
          type: string
        lastUpdated:
          readOnly: true
          type: string
        name:
          readOnly: true
          type: string
        properties:
          $ref: '#/components/schemas/UserSchemaProperties'
        title:
          type: string
        type:
          readOnly: true
          type: string
      type: object
      x-okta-tags:
      - GroupSchema
    GroupSchemaAttribute:
      properties:
        description:
          type: string
        enum:
          items:
            type: string
          type: array
        externalName:
          type: string
        externalNamespace:
          type: string
        items:
          $ref: '#/components/schemas/UserSchemaAttributeItems'
        master:
          $ref: '#/components/schemas/UserSchemaAttributeMaster'
        maxLength:
          type: integer
        minLength:
          type: integer
        mutability:
          type: string
        oneOf:
          items:
            $ref: '#/components/schemas/UserSchemaAttributeEnum'
          type: array
        permissions:
          items:
            $ref: '#/components/schemas/UserSchemaAttributePermission'
          type: array
        required:
          type: boolean
        scope:
          $ref: '#/components/schemas/UserSchemaAttributeScope'
        title:
          type: string
        type:
          $ref: '#/components/schemas/UserSchemaAttributeType'
        union:
          $ref: '#/components/schemas/UserSchemaAttributeUnion'
        unique:
          type: string
      type: object
      x-okta-tags:
      - GroupSchema
    GroupSchemaBase:
      properties:
        id:
          readOnly: true
          type: string
        properties:
          $ref: '#/components/schemas/GroupSchemaBaseProperties'
        required:
          items:
            type: string
          type: array
        type:
          type: string
      type: object
      x-okta-tags:
      - GroupSchema
    GroupSchemaBaseProperties:
      properties:
        description:
          $ref: '#/components/schemas/GroupSchemaAttribute'
        name:
          $ref: '#/components/schemas/GroupSchemaAttribute'
      type: object
      x-okta-tags:
      - GroupSchema
    GroupSchemaCustom:
      properties:
        id:
          readOnly: true
          type: string
        properties:
          additionalProperties:
            $ref: '#/components/schemas/GroupSchemaAttribute'
          type: object
        required:
          items:
            type: string
          type: array
        type:
          type: string
      type: object
      x-okta-tags:
      - GroupSchema
    GroupSchemaDefinitions:
      properties:
        base:
          $ref: '#/components/schemas/GroupSchemaBase'
        custom:
          $ref: '#/components/schemas/GroupSchemaCustom'
      type: object
      x-okta-tags:
      - GroupSchema
    UserSchemaAttributeEnum:
      properties:
        const:
          type: string
        title:
          type: string
      type: object
      x-okta-tags:
      - UserSchema
    UserSchemaAttributeItems:
      properties:
        enum:
          items:
            type: string
          type: array
        oneOf:
          items:
            $ref: '#/components/schemas/UserSchemaAttributeEnum'
          type: array
        type:
          type: string
      type: object
      x-okta-tags:
      - UserSchema
    UserSchemaAttributeMaster:
      properties:
        priority:
          items:
            $ref: '#/components/schemas/UserSchemaAttributeMasterPriority'
          type: array
        type:
          $ref: '#/components/schemas/UserSchemaAttributeMasterType'
      type: object
      x-okta-tags:
      - UserSchema
    UserSchemaAttributeMasterPriority:
      properties:
        type:
          type: string
        value:
          type: string
      type: object
      x-okta-tags:
      - UserSchema
    UserSchemaAttributeMasterType:
      enum:
      - PROFILE_MASTER
      - OKTA
      - OVERRIDE
      type: string
      x-okta-tags:
      - UserSchema
    UserSchemaAttributePermission:
      properties:
        action:
          type: string
        principal:
          type: string
      type: object
      x-okta-tags:
      - UserSchema
    UserSchemaAttributeScope:
      enum:
      - SELF
      - NONE
      type: object
      x-okta-tags:
      - UserSchema
    UserSchemaAttributeType:
      enum:
      - string
      - boolean
      - number
      - integer
      - array
      type: string
      x-okta-tags:
      - UserSchema
    UserSchemaAttributeUnion:
      enum:
      - DISABLE
      - ENABLE
      type: object
      x-okta-tags:
      - UserSchema
    UserSchemaProperties:
      properties:
        profile:
          $ref: '#/components/schemas/UserSchemaPropertiesProfile'
      type: object
      x-okta-tags:
      - UserSchema
    UserSchemaPropertiesProfile:
      properties:
        allOf:
          items:
            $ref: '#/components/schemas/UserSchemaPropertiesProfileItem'
          type: array
      type: object
      x-okta-tags:
      - UserSchema
    UserSchemaPropertiesProfileItem:
      properties:
        $ref:
          type: string
      type: object
      x-okta-tags:
      - UserSchema
  securitySchemes:
    api_token:
      description: SSWS {API Token}
      in: header
      name: Authorization
      type: apiKey
  x-stackQL-resources:
    default:
      id: okta.groupschema.default
      methods:
        get:
          operation:
            $ref: '#/paths/~1api~1v1~1meta~1schemas~1group~1default/GET'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        update:
          operation:
            $ref: '#/paths/~1api~1v1~1meta~1schemas~1group~1default/POST'
          request:
            mediaType: application/json
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      name: default
      title: default
externalDocs:
  description: Find more info here
  url: https://developer.okta.com/docs/api/getting_started/design_principles.html
info:
  contact:
    email: devex-public@okta.com
    name: Okta Developer Team
    url: https://developer.okta.com/
  description: Allows customers to easily access the Okta API
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developer.okta.com/terms/
  title: Okta API
  version: 2.8.0
openapi: 3.0.1
paths:
  /api/v1/meta/schemas/group/default:
    get:
      description: Fetches the group schema
      operationId: getGroupSchema
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupSchema'
          description: successful operation
      security:
      - api_token: []
      summary: Fetches the group schema
      tags:
      - GroupSchema
    post:
      description: Updates, adds ore removes one or more custom Group Profile properties
        in the schema
      operationId: updateGroupSchema
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupSchema'
        required: false
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupSchema'
          description: successful operation
      security:
      - api_token: []
      summary: Updates, adds ore removes one or more custom Group Profile properties
        in the schema
      tags:
      - GroupSchema
      x-codegen-request-body-name: body
servers:
- url: https://{subdomain}.okta.com/
  variables:
    subdomain:
      default: my-domain
