id: aws
name: aws
version: v00.00.00000
providerServices:
  cloud_control:
    description: Cloud Control api
    id: cloud_control:v00.00.00000
    name: cloud_control
    preferred: true
    service:
      $ref: aws/v00.00.00000/services/cloud_control.yaml
    title: Cloud Control API
    version: v00.00.00000
  ec2:
    description: ec2
    id: ec2:v00.00.00000
    name: ec2
    preferred: true
    service:
      $ref: aws/v00.00.00000/services/ec2.yaml
    title: EC2
    version: v00.00.00000
  iam:
    description: iam
    id: iam:v00.00.00000
    name: ec2
    preferred: true
    service:
      $ref: aws/v00.00.00000/services/iam.yaml
    title: IAM
    version: v00.00.00000
  s3:
    description: s3
    id: s3:v00.00.00000
    name: s3
    preferred: true
    service:
      $ref: aws/v00.00.00000/services/s3.yaml
    title: S3
    version: v00.00.00000
openapi: 3.0.0
