openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Business Profile Performance API
  description: The Business Profile Performance API allows merchants to fetch performance reports about their business profile on Google. Note - If you have a quota of 0 after enabling the API, please request for GBP API access.
  version: v1
  x-discovery-doc-revision: '20230118'
  x-generated-date: '2023-01-19'
externalDocs:
  url: https://developers.google.com/my-business/
servers:
  - url: https://businessprofileperformance.googleapis.com
components:
  schemas:
    DatedValue:
      properties:
        value:
          description: The value of the datapoint.
          format: int64
          type: string
        date:
          $ref: '#/components/schemas/Date'
          description: The date that the datapoint corresponds to. This represents a month value if the day field is not set.
      id: DatedValue
      description: Represents a single datapoint in the timeseries, where each datapoint is a date-value pair.
      type: object
    SearchKeywordCount:
      type: object
      id: SearchKeywordCount
      properties:
        insightsValue:
          description: 'One of either: 1) The sum of the number of unique users that used the keyword in a month, aggregated for each month requested. 2) A threshold that indicates that the actual value is below this threshold.'
          $ref: '#/components/schemas/InsightsValue'
        searchKeyword:
          description: The lower-cased string that the user entered.
          type: string
      description: Represents a single search keyword and its value.
    InsightsValue:
      properties:
        value:
          type: string
          description: Represents the actual value.
          format: int64
        threshold:
          type: string
          format: int64
          description: Represents the threshold below which the actual value falls.
      type: object
      id: InsightsValue
      description: Represents an insights value.
    ListSearchKeywordImpressionsMonthlyResponse:
      description: Represents the response for ListSearchKeywordImpressionsMonthly.
      properties:
        searchKeywordsCounts:
          type: array
          description: Search terms which have been used to find a business.
          items:
            $ref: '#/components/schemas/SearchKeywordCount'
        nextPageToken:
          type: string
          description: A token indicating the last paginated result returned. This can be used by succeeding requests to get the next "page" of keywords. It will only be present when there are more results to be returned.
          format: byte
      type: object
      id: ListSearchKeywordImpressionsMonthlyResponse
    TimeSeries:
      id: TimeSeries
      properties:
        datedValues:
          items:
            $ref: '#/components/schemas/DatedValue'
          description: List of datapoints in the timeseries, where each datapoint is a date-value pair.
          type: array
      description: Represents a timeseries.
      type: object
    GetDailyMetricsTimeSeriesResponse:
      type: object
      description: Represents the response for GetDailyMetricsTimeSeries.
      properties:
        timeSeries:
          description: The daily time series.
          $ref: '#/components/schemas/TimeSeries'
      id: GetDailyMetricsTimeSeriesResponse
    Date:
      properties:
        month:
          type: integer
          format: int32
          description: Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.
        day:
          format: int32
          type: integer
          description: Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.
        year:
          format: int32
          type: integer
          description: Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.
      description: 'Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following: * A full date, with non-zero year, month, and day values. * A month and day, with a zero year (for example, an anniversary). * A year on its own, with a zero month and a zero day. * A year and month, with a zero day (for example, a credit card expiration date). Related types: * google.type.TimeOfDay * google.type.DateTime * google.protobuf.Timestamp'
      type: object
      id: Date
  parameters:
    uploadType:
      description: Legacy upload protocol for media (e.g. "media", "multipart").
      in: query
      name: uploadType
      schema:
        type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    upload_protocol:
      description: Upload protocol for media (e.g. "raw", "multipart").
      in: query
      name: upload_protocol
      schema:
        type: string
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    key:
      description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      in: query
      name: key
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    quotaUser:
      description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/books: Manage your books
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
  x-stackQL-resources:
    locations_daily_metrics_time_series:
      id: googlemybusiness.businessprofileperformance.locations_daily_metrics_time_series
      name: locations_daily_metrics_time_series
      title: Locations_daily_metrics_time_series
      methods:
        locations_getDailyMetricsTimeSeries:
          operation:
            $ref: '#/paths/~1v1~1locations~1{locationsId}:getDailyMetricsTimeSeries/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/locations_daily_metrics_time_series/methods/locations_getDailyMetricsTimeSeries'
        insert: []
        update: []
        delete: []
    monthly:
      id: googlemybusiness.businessprofileperformance.monthly
      name: monthly
      title: Monthly
      methods:
        locations_searchkeywords_impressions_monthly_list:
          operation:
            $ref: '#/paths/~1v1~1locations~1{locationsId}~1searchkeywords~1impressions~1monthly/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/monthly/methods/locations_searchkeywords_impressions_monthly_list'
        insert: []
        update: []
        delete: []
paths:
  /v1/locations/{locationsId}:getDailyMetricsTimeSeries:
    parameters: &ref_1
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/quotaUser'
    get:
      description: ' Returns the values for each date from a given time range that are associated with the specific daily metric. Example request: `GET https://businessprofileperformance.googleapis.com/v1/locations/12345:getDailyMetricsTimeSeries?dailyMetric=WEBSITE_CLICKS&daily_range.start_date.year=2022&daily_range.start_date.month=1&daily_range.start_date.day=1&daily_range.end_date.year=2022&daily_range.end_date.month=3&daily_range.end_date.day=31`'
      operationId: businessprofileperformance.locations.getDailyMetricsTimeSeries
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDailyMetricsTimeSeriesResponse'
      parameters:
        - in: path
          name: locationsId
          required: true
          schema:
            type: string
        - in: query
          name: dailyRange.startDate.month
          schema:
            type: integer
        - in: query
          name: dailyMetric
          schema:
            type: string
        - in: query
          name: dailyRange.endDate.year
          schema:
            type: integer
        - in: query
          name: dailyRange.endDate.day
          schema:
            type: integer
        - in: query
          name: dailySubEntityType.timeOfDay.nanos
          schema:
            type: integer
        - in: query
          name: dailyRange.endDate.month
          schema:
            type: integer
        - in: query
          name: dailyRange.startDate.day
          schema:
            type: integer
        - in: query
          name: dailySubEntityType.dayOfWeek
          schema:
            type: string
        - in: query
          name: dailySubEntityType.timeOfDay.seconds
          schema:
            type: integer
        - in: query
          name: dailySubEntityType.timeOfDay.hours
          schema:
            type: integer
        - in: query
          name: dailyRange.startDate.year
          schema:
            type: integer
        - in: query
          name: dailySubEntityType.timeOfDay.minutes
          schema:
            type: integer
      x-stackQL-resource: locations_daily_metrics_time_series
      x-stackQL-verb: select
  /v1/locations/{locationsId}/searchkeywords/impressions/monthly:
    parameters: *ref_1
    get:
      description: 'Returns the search keywords used to find a business in search or maps. Each search keyword is accompanied by impressions which are aggregated on a monthly basis. Example request: `GET https://businessprofileperformance.googleapis.com/v1/locations/12345/searchkeywords/impressions/monthly?monthly_range.start_month.year=2022&monthly_range.start_month.month=1&monthly_range.end_month.year=2022&monthly_range.end_month.month=3`'
      operationId: businessprofileperformance.locations.searchkeywords.impressions.monthly.list
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSearchKeywordImpressionsMonthlyResponse'
      parameters:
        - in: path
          name: locationsId
          required: true
          schema:
            type: string
        - in: query
          name: monthlyRange.endMonth.day
          schema:
            type: integer
        - in: query
          name: monthlyRange.endMonth.year
          schema:
            type: integer
        - in: query
          name: pageToken
          schema:
            type: string
        - in: query
          name: monthlyRange.startMonth.year
          schema:
            type: integer
        - in: query
          name: monthlyRange.startMonth.day
          schema:
            type: integer
        - in: query
          name: monthlyRange.endMonth.month
          schema:
            type: integer
        - in: query
          name: monthlyRange.startMonth.month
          schema:
            type: integer
        - in: query
          name: pageSize
          schema:
            type: integer
      x-stackQL-resource: monthly
      x-stackQL-verb: select
