openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: My Business Notifications API
  description: The My Business Notification Settings API enables managing notification settings for business accounts. Note - If you have a quota of 0 after enabling the API, please request for GBP API access.
  version: v1
  x-discovery-doc-revision: '20230118'
  x-generated-date: '2023-01-19'
externalDocs:
  url: https://developers.google.com/my-business/
servers:
  - url: https://mybusinessnotifications.googleapis.com
components:
  schemas:
    NotificationSetting:
      type: object
      properties:
        name:
          description: Required. The resource name this setting is for. This is of the form `accounts/{account_id}/notificationSetting`.
          type: string
        pubsubTopic:
          type: string
          description: Optional. The Google Pub/Sub topic that will receive notifications when locations managed by this account are updated. If unset, no notifications will be posted. The account mybusiness-api-pubsub@system.gserviceaccount.com must have at least Publish permissions on the Pub/Sub topic.
        notificationTypes:
          description: The types of notifications that will be sent to the Pub/Sub topic. To stop receiving notifications entirely, use NotificationSettings.UpdateNotificationSetting with an empty notification_types or set the pubsub_topic to an empty string.
          type: array
          items:
            type: string
            enum:
              - NOTIFICATION_TYPE_UNSPECIFIED
              - GOOGLE_UPDATE
              - NEW_REVIEW
              - UPDATED_REVIEW
              - NEW_CUSTOMER_MEDIA
              - NEW_QUESTION
              - UPDATED_QUESTION
              - NEW_ANSWER
              - UPDATED_ANSWER
              - DUPLICATE_LOCATION
              - LOSS_OF_VOICE_OF_MERCHANT
              - VOICE_OF_MERCHANT_UPDATED
            enumDescriptions:
              - No notification type. Will not match any notifications.
              - The location has Google updates for review. The location_name field on the notification will provide the resource name of the location with Google updates.
              - A new review has been added to the location. The review_name field on the notification will provide the resource name of the review that was added, and location_name will have the location's resource name.
              - A review on the location has been updated. The review_name field on the notification will provide the resource name of the review that was added, and location_name will have the location's resource name.
              - A new media item has been added to the location by a Google Maps user. The notification will provide the resource name of the new media item.
              - A new question is added to the location. The notification will provide the resource name of question.
              - A question of the location is updated. The notification will provide the resource name of question.
              - A new answer is added to the location. The notification will provide the resource name of question and answer.
              - An answer of the location is updated. The notification will provide the resource name of question and answer.
              - Indicates whether there is a change in location metadata's duplicate location field.
              - 'Deprecated: Migrate the existing usages of this value to the more expanded "VOICE_OF_MERCHANT_UPDATED".'
              - Indicates whether the location has an update in Voice of Merchant (VOM) status. VOM dictates whether the location is in good standing and the merchant has control over the business on Google. Any edits made to the location will propagate to Maps after passing the review phase. Call GetVoiceOfMerchantState rpc for more details.
      id: NotificationSetting
      description: A Google Pub/Sub topic where notifications can be published when a location is updated or has a new review. There will be only one notification setting resource per-account.
  parameters:
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    upload_protocol:
      description: Upload protocol for media (e.g. "raw", "multipart").
      in: query
      name: upload_protocol
      schema:
        type: string
    uploadType:
      description: Legacy upload protocol for media (e.g. "media", "multipart").
      in: query
      name: uploadType
      schema:
        type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    key:
      description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      in: query
      name: key
      schema:
        type: string
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    quotaUser:
      description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/monitoring: View and write monitoring data for all of your Google and third-party Cloud and API projects
            https://www.googleapis.com/auth/monitoring.read: View monitoring data for all of your Google Cloud and third-party projects
            https://www.googleapis.com/auth/monitoring.write: Publish metric data to your Google Cloud projects
            https://www.googleapis.com/auth/cloud-platform: See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account.
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
  x-stackQL-resources:
    accounts:
      id: googlemybusiness.mybusinessnotifications.accounts
      name: accounts
      title: Accounts
      methods:
        updateNotificationSetting:
          operation:
            $ref: '#/paths/~1v1~1accounts~1{accountsId}~1notificationSetting/patch'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    accounts_notification_setting:
      id: googlemybusiness.mybusinessnotifications.accounts_notification_setting
      name: accounts_notification_setting
      title: Accounts_notification_setting
      methods:
        accounts_getNotificationSetting:
          operation:
            $ref: '#/paths/~1v1~1accounts~1{accountsId}~1notificationSetting/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/accounts_notification_setting/methods/accounts_getNotificationSetting'
        insert: []
        update: []
        delete: []
paths:
  /v1/accounts/{accountsId}/notificationSetting:
    parameters:
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/quotaUser'
    patch:
      description: Sets the pubsub notification setting for the account informing Google which topic to send pubsub notifications for. Use the notification_types field within notification_setting to manipulate the events an account wants to subscribe to. An account will only have one notification setting resource, and only one pubsub topic can be set. To delete the setting, update with an empty notification_types
      operationId: mybusinessnotifications.accounts.updateNotificationSetting
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationSetting'
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationSetting'
      parameters:
        - in: path
          name: accountsId
          required: true
          schema:
            type: string
        - in: query
          name: updateMask
          schema:
            type: string
      x-stackQL-resource: accounts
      x-stackQL-verb: exec
    get:
      description: Returns the pubsub notification settings for the account.
      operationId: mybusinessnotifications.accounts.getNotificationSetting
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationSetting'
      parameters:
        - in: path
          name: accountsId
          required: true
          schema:
            type: string
      x-stackQL-resource: accounts_notification_setting
      x-stackQL-verb: select
