openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: My Business Business Calls API
  description: The My Business Business Calls API manages business calls information of a location on Google and collect insights like the number of missed calls to their location. Additional information about Business calls can be found at https://support.google.com/business/answer/9688285?p=call_history. If the Google Business Profile links to a Google Ads account and call history is turned on, calls that last longer than a specific time, and that can be attributed to an ad interaction, will show in the linked Google Ads account under the "Calls from Ads" conversion. If smart bidding and call conversions are used in the optimization strategy, there could be a change in ad spend. Learn more about smart bidding. To view and perform actions on a location's calls, you need to be a `OWNER`, `CO_OWNER` or `MANAGER` of the location. Note - If you have a quota of 0 after enabling the API, please request for GBP API access.
  version: v1
  x-discovery-doc-revision: '20230118'
  x-generated-date: '2023-01-19'
externalDocs:
  url: https://developers.google.com/my-business/
servers:
  - url: https://mybusinessbusinesscalls.googleapis.com
components:
  schemas:
    BusinessCallsSettings:
      description: Business calls settings for a location.
      id: BusinessCallsSettings
      properties:
        consentTime:
          type: string
          format: google-datetime
          description: Input only. Time when the end user provided consent to the API user to enable business calls.
        name:
          description: 'Required. The resource name of the calls settings. Format: locations/{location}/businesscallssettings'
          type: string
        callsState:
          enum:
            - CALLS_STATE_UNSPECIFIED
            - ENABLED
            - DISABLED
          enumDescriptions:
            - Unspecified.
            - Business calls is enabled for the location.
            - Business calls is disabled for the location.
          description: Required. The state of this location's enrollment in Business calls.
          type: string
      type: object
    AggregateMetrics:
      type: object
      properties:
        answeredCallsCount:
          description: Total count of answered calls.
          type: integer
          format: int32
        hourlyMetrics:
          type: array
          description: A list of metrics by hour of day.
          items:
            $ref: '#/components/schemas/HourlyMetrics'
        missedCallsCount:
          description: Total count of missed calls.
          type: integer
          format: int32
        startDate:
          $ref: '#/components/schemas/Date'
          description: Date for this metric. If metric is monthly, only year and month are used.
        weekdayMetrics:
          items:
            $ref: '#/components/schemas/WeekDayMetrics'
          type: array
          description: A list of metrics by day of week.
        endDate:
          $ref: '#/components/schemas/Date'
          description: End date for this metric.
      description: Metrics aggregated over the input time range.
      id: AggregateMetrics
    WeekDayMetrics:
      description: Metrics for a week day.
      properties:
        missedCallsCount:
          description: Total count of missed calls for this hour.
          format: int32
          type: integer
        day:
          enum:
            - DAY_OF_WEEK_UNSPECIFIED
            - MONDAY
            - TUESDAY
            - WEDNESDAY
            - THURSDAY
            - FRIDAY
            - SATURDAY
            - SUNDAY
          type: string
          enumDescriptions:
            - The day of the week is unspecified.
            - Monday
            - Tuesday
            - Wednesday
            - Thursday
            - Friday
            - Saturday
            - Sunday
          description: Day of the week. Allowed values are Sunday - Saturday.
      id: WeekDayMetrics
      type: object
    ListBusinessCallsInsightsResponse:
      id: ListBusinessCallsInsightsResponse
      properties:
        nextPageToken:
          type: string
          description: A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages. Some of the metric_types (e.g, AGGREGATE_COUNT) returns a single page. For these metrics, the next_page_token will be empty.
        businessCallsInsights:
          type: array
          items:
            $ref: '#/components/schemas/BusinessCallsInsights'
          description: A collection of business calls insights for the location.
      description: Response message for ListBusinessCallsInsights.
      type: object
    HourlyMetrics:
      description: Metrics for an hour.
      id: HourlyMetrics
      type: object
      properties:
        hour:
          type: integer
          format: int32
          description: Hour of the day. Allowed values are 0-23.
        missedCallsCount:
          description: Total count of missed calls for this hour.
          type: integer
          format: int32
    BusinessCallsInsights:
      description: Insights for calls made to a location.
      type: object
      id: BusinessCallsInsights
      properties:
        metricType:
          enum:
            - METRIC_TYPE_UNSPECIFIED
            - AGGREGATE_COUNT
          description: The metric for which the value applies.
          type: string
          enumDescriptions:
            - Type of metric is unspecified.
            - The metrics provided are counts aggregated over the input time_range.
        name:
          type: string
          description: 'Required. The resource name of the calls insights. Format: locations/{location}/businesscallsinsights'
        aggregateMetrics:
          $ref: '#/components/schemas/AggregateMetrics'
          description: Metric for the time range based on start_date and end_date.
    Date:
      id: Date
      description: 'Represents a whole or partial calendar date, such as a birthday. The time of day and time zone are either specified elsewhere or are insignificant. The date is relative to the Gregorian Calendar. This can represent one of the following: * A full date, with non-zero year, month, and day values. * A month and day, with a zero year (for example, an anniversary). * A year on its own, with a zero month and a zero day. * A year and month, with a zero day (for example, a credit card expiration date). Related types: * google.type.TimeOfDay * google.type.DateTime * google.protobuf.Timestamp'
      type: object
      properties:
        day:
          type: integer
          description: Day of a month. Must be from 1 to 31 and valid for the year and month, or 0 to specify a year by itself or a year and month where the day isn't significant.
          format: int32
        year:
          format: int32
          description: Year of the date. Must be from 1 to 9999, or 0 to specify a date without a year.
          type: integer
        month:
          format: int32
          description: Month of a year. Must be from 1 to 12, or 0 to specify a year without a month and day.
          type: integer
  parameters:
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    key:
      description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      in: query
      name: key
      schema:
        type: string
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    uploadType:
      description: Legacy upload protocol for media (e.g. "media", "multipart").
      in: query
      name: uploadType
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    upload_protocol:
      description: Upload protocol for media (e.g. "raw", "multipart").
      in: query
      name: upload_protocol
      schema:
        type: string
    quotaUser:
      description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/monitoring: View and write monitoring data for all of your Google and third-party Cloud and API projects
            https://www.googleapis.com/auth/monitoring.read: View monitoring data for all of your Google Cloud and third-party projects
            https://www.googleapis.com/auth/monitoring.write: Publish metric data to your Google Cloud projects
            https://www.googleapis.com/auth/cloud-platform: See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account.
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
  x-stackQL-resources:
    locations_businesscallssettings:
      id: googlemybusiness.mybusinessbusinesscalls.locations_businesscallssettings
      name: locations_businesscallssettings
      title: Locations_businesscallssettings
      methods:
        locations_getBusinesscallssettings:
          operation:
            $ref: '#/paths/~1v1~1locations~1{locationsId}~1businesscallssettings/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/locations_businesscallssettings/methods/locations_getBusinesscallssettings'
        insert: []
        update: []
        delete: []
    locations:
      id: googlemybusiness.mybusinessbusinesscalls.locations
      name: locations
      title: Locations
      methods:
        updateBusinesscallssettings:
          operation:
            $ref: '#/paths/~1v1~1locations~1{locationsId}~1businesscallssettings/patch'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    businesscallsinsights:
      id: googlemybusiness.mybusinessbusinesscalls.businesscallsinsights
      name: businesscallsinsights
      title: Businesscallsinsights
      methods:
        locations_businesscallsinsights_list:
          operation:
            $ref: '#/paths/~1v1~1locations~1{locationsId}~1businesscallsinsights/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/businesscallsinsights/methods/locations_businesscallsinsights_list'
        insert: []
        update: []
        delete: []
paths:
  /v1/locations/{locationsId}/businesscallssettings:
    parameters: &ref_1
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/quotaUser'
    get:
      description: Returns the Business calls settings resource for the given location.
      operationId: mybusinessbusinesscalls.locations.getBusinesscallssettings
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessCallsSettings'
      parameters:
        - in: path
          name: locationsId
          required: true
          schema:
            type: string
      x-stackQL-resource: locations_businesscallssettings
      x-stackQL-verb: select
    patch:
      description: Updates the Business call settings for the specified location.
      operationId: mybusinessbusinesscalls.locations.updateBusinesscallssettings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessCallsSettings'
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessCallsSettings'
      parameters:
        - in: path
          name: locationsId
          required: true
          schema:
            type: string
        - in: query
          name: updateMask
          schema:
            type: string
      x-stackQL-resource: locations
      x-stackQL-verb: exec
  /v1/locations/{locationsId}/businesscallsinsights:
    parameters: *ref_1
    get:
      description: Returns insights for Business calls for a location.
      operationId: mybusinessbusinesscalls.locations.businesscallsinsights.list
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListBusinessCallsInsightsResponse'
      parameters:
        - in: path
          name: locationsId
          required: true
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: pageToken
          schema:
            type: string
      x-stackQL-resource: businesscallsinsights
      x-stackQL-verb: select
