id: sumologic
name: sumologic
version: v0.1.0
providerServices:
  access_keys:
    description: accessKeys
    id: access_keys:v0.1.0
    name: access_keys
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/access_keys.yaml
    title: Sumo Logic API - access_keys
    version: v0.1.0
  account:
    description: account
    id: account:v0.1.0
    name: account
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/account.yaml
    title: Sumo Logic API - account
    version: v0.1.0
  apps:
    description: apps
    id: apps:v0.1.0
    name: apps
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/apps.yaml
    title: Sumo Logic API - apps
    version: v0.1.0
  archive:
    description: archive
    id: archive:v0.1.0
    name: archive
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/archive.yaml
    title: Sumo Logic API - archive
    version: v0.1.0
  collectors:
    description: collectors
    id: collectors:v0.1.0
    name: collectors
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/collectors.yaml
    title: Sumo Logic API - Collector Management API
    version: v0.1.0
  connections:
    description: connections
    id: connections:v0.1.0
    name: connections
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/connections.yaml
    title: Sumo Logic API - connections
    version: v0.1.0
  content:
    description: content
    id: content:v0.1.0
    name: content
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/content.yaml
    title: Sumo Logic API - content
    version: v0.1.0
  dashboards:
    description: dashboards
    id: dashboards:v0.1.0
    name: dashboards
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/dashboards.yaml
    title: Sumo Logic API - dashboards
    version: v0.1.0
  dynamic_parsing_rules:
    description: dynamicParsingRules
    id: dynamic_parsing_rules:v0.1.0
    name: dynamic_parsing_rules
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/dynamic_parsing_rules.yaml
    title: Sumo Logic API - dynamic_parsing_rules
    version: v0.1.0
  extraction_rules:
    description: extractionRules
    id: extraction_rules:v0.1.0
    name: extraction_rules
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/extraction_rules.yaml
    title: Sumo Logic API - extraction_rules
    version: v0.1.0
  fields:
    description: fields
    id: fields:v0.1.0
    name: fields
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/fields.yaml
    title: Sumo Logic API - fields
    version: v0.1.0
  health_events:
    description: healthEvents
    id: health_events:v0.1.0
    name: health_events
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/health_events.yaml
    title: Sumo Logic API - health_events
    version: v0.1.0
  ingest_budgets:
    description: ingestBudgets
    id: ingest_budgets:v0.1.0
    name: ingest_budgets
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/ingest_budgets.yaml
    title: Sumo Logic API - ingest_budgets
    version: v0.1.0
  log_searches:
    description: logSearches
    id: log_searches:v0.1.0
    name: log_searches
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/log_searches.yaml
    title: Sumo Logic API - log_searches
    version: v0.1.0
  logs_data_forwarding:
    description: logsDataForwarding
    id: logs_data_forwarding:v0.1.0
    name: logs_data_forwarding
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/logs_data_forwarding.yaml
    title: Sumo Logic API - logs_data_forwarding
    version: v0.1.0
  lookup_tables:
    description: lookupTables
    id: lookup_tables:v0.1.0
    name: lookup_tables
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/lookup_tables.yaml
    title: Sumo Logic API - lookup_tables
    version: v0.1.0
  metrics_queries:
    description: metricsQueries
    id: metrics_queries:v0.1.0
    name: metrics_queries
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/metrics_queries.yaml
    title: Sumo Logic API - metrics_queries
    version: v0.1.0
  metrics_searches:
    description: metricsSearches
    id: metrics_searches:v0.1.0
    name: metrics_searches
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/metrics_searches.yaml
    title: Sumo Logic API - metrics_searches
    version: v0.1.0
  monitors:
    description: monitors
    id: monitors:v0.1.0
    name: monitors
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/monitors.yaml
    title: Sumo Logic API - monitors
    version: v0.1.0
  partitions:
    description: partitions
    id: partitions:v0.1.0
    name: partitions
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/partitions.yaml
    title: Sumo Logic API - partitions
    version: v0.1.0
  password_policy:
    description: passwordPolicy
    id: password_policy:v0.1.0
    name: password_policy
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/password_policy.yaml
    title: Sumo Logic API - password_policy
    version: v0.1.0
  plan:
    description: plan
    id: plan:v0.1.0
    name: plan
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/plan.yaml
    title: Sumo Logic API - plan
    version: v0.1.0
  policies:
    description: policies
    id: policies:v0.1.0
    name: policies
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/policies.yaml
    title: Sumo Logic API - policies
    version: v0.1.0
  roles:
    description: roles
    id: roles:v0.1.0
    name: roles
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/roles.yaml
    title: Sumo Logic API - roles
    version: v0.1.0
  saml:
    description: saml
    id: saml:v0.1.0
    name: saml
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/saml.yaml
    title: Sumo Logic API - saml
    version: v0.1.0
  scheduled_views:
    description: scheduledViews
    id: scheduled_views:v0.1.0
    name: scheduled_views
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/scheduled_views.yaml
    title: Sumo Logic API - scheduled_views
    version: v0.1.0
  service_allowlist:
    description: serviceAllowlist
    id: service_allowlist:v0.1.0
    name: service_allowlist
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/service_allowlist.yaml
    title: Sumo Logic API - service_allowlist
    version: v0.1.0
  slos:
    description: slos
    id: slos:v0.1.0
    name: slos
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/slos.yaml
    title: Sumo Logic API - slos
    version: v0.1.0
  tokens:
    description: tokens
    id: tokens:v0.1.0
    name: tokens
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/tokens.yaml
    title: Sumo Logic API - tokens
    version: v0.1.0
  tracing:
    description: tracing
    id: tracing:v0.1.0
    name: tracing
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/tracing.yaml
    title: Sumo Logic API - tracing
    version: v0.1.0
  transformation_rules:
    description: transformationRules
    id: transformation_rules:v0.1.0
    name: transformation_rules
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/transformation_rules.yaml
    title: Sumo Logic API - transformation_rules
    version: v0.1.0
  users:
    description: users
    id: users:v0.1.0
    name: users
    preferred: true
    service:
      $ref: sumologic/v0.1.0/services/users.yaml
    title: Sumo Logic API - users
    version: v0.1.0
openapi: 3.0.0
