id: netlify
name: netlify
version: v00.00.00000
providerServices:
  accounts:
    id: accounts:v00.00.00000
    name: accounts
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/accounts.yaml
    title: accounts API
    version: v00.00.00000
    description: netlify accounts API
  agent_runners:
    id: agent_runners:v00.00.00000
    name: agent_runners
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/agent_runners.yaml
    title: agent_runners API
    version: v00.00.00000
    description: netlify agent_runners API
  ai_gateway:
    id: ai_gateway:v00.00.00000
    name: ai_gateway
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/ai_gateway.yaml
    title: ai_gateway API
    version: v00.00.00000
    description: netlify ai_gateway API
  builds:
    id: builds:v00.00.00000
    name: builds
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/builds.yaml
    title: builds API
    version: v00.00.00000
    description: netlify builds API
  database:
    id: database:v00.00.00000
    name: database
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/database.yaml
    title: database API
    version: v00.00.00000
    description: netlify database API
  deploys:
    id: deploys:v00.00.00000
    name: deploys
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/deploys.yaml
    title: deploys API
    version: v00.00.00000
    description: netlify deploys API
  dev_servers:
    id: dev_servers:v00.00.00000
    name: dev_servers
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/dev_servers.yaml
    title: dev_servers API
    version: v00.00.00000
    description: netlify dev_servers API
  dns:
    id: dns:v00.00.00000
    name: dns
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/dns.yaml
    title: dns API
    version: v00.00.00000
    description: netlify dns API
  env:
    id: env:v00.00.00000
    name: env
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/env.yaml
    title: env API
    version: v00.00.00000
    description: netlify env API
  forms:
    id: forms:v00.00.00000
    name: forms
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/forms.yaml
    title: forms API
    version: v00.00.00000
    description: netlify forms API
  functions:
    id: functions:v00.00.00000
    name: functions
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/functions.yaml
    title: functions API
    version: v00.00.00000
    description: netlify functions API
  hooks:
    id: hooks:v00.00.00000
    name: hooks
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/hooks.yaml
    title: hooks API
    version: v00.00.00000
    description: netlify hooks API
  oauth:
    id: oauth:v00.00.00000
    name: oauth
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/oauth.yaml
    title: oauth API
    version: v00.00.00000
    description: netlify oauth API
  services:
    id: services:v00.00.00000
    name: services
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/services.yaml
    title: services API
    version: v00.00.00000
    description: netlify services API
  sites:
    id: sites:v00.00.00000
    name: sites
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/sites.yaml
    title: sites API
    version: v00.00.00000
    description: netlify sites API
  split_tests:
    id: split_tests:v00.00.00000
    name: split_tests
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/split_tests.yaml
    title: split_tests API
    version: v00.00.00000
    description: netlify split_tests API
  users:
    id: users:v00.00.00000
    name: users
    preferred: true
    service:
      $ref: netlify/v00.00.00000/services/users.yaml
    title: users API
    version: v00.00.00000
    description: netlify users API
config:
  auth:
    type: bearer
    credentialsenvvar: NETLIFY_API_TOKEN
