openapi: 3.0.1
info:
  title: betas API
  description: linode betas API
  version: 4.208.1
paths:
  /betas:
    get:
      description: >-
        Display all active Beta Programs.


        Only unrestricted Users can access this operation.


        [Learn
        more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)
      externalDocs:
        description: See documentation for this operation in Akamai's Linode API
        url: https://techdocs.akamai.com/linode-api/reference/get-beta-programs
      operationId: get-beta-programs
      parameters:
        - description: The page of a collection to return.
          example: '{{page}}'
          in: query
          name: page
          required: false
          schema:
            default: 1
            example: 6
            minimum: 1
            type: integer
          x-akamai:
            file-path: parameters/page-offset.yaml
        - description: The number of items to return per page.
          example: '{{page_size}}'
          in: query
          name: page_size
          schema:
            default: 100
            example: 50
            maximum: 500
            minimum: 25
            type: integer
          x-akamai:
            file-path: parameters/page-size.yaml
      responses:
        '200':
          content:
            application/json:
              example:
                data:
                  - description: This is an open public beta for an example feature.
                    ended: null
                    greenlight_only: true
                    id: example_open
                    label: Example Open Beta
                    more_info: https://www.linode.com/green-light/
                    started: '2023-07-11T00:00:00'
                page: 1
                pages: 1
                results: 1
              schema:
                allOf:
                  - additionalProperties: false
                    description: >-
                      An envelope for paginated response. When accessing a
                      collection through a GET endpoint, the results are wrapped
                      in this envelope which includes metadata about those
                      results. Results are presented within a `data` array. See
                      [Pagination](https://techdocs.akamai.com/linode-api/reference/pagination)
                      for more information.
                    properties:
                      page:
                        description: >-
                          __Read-only__ The current
                          [page](https://techdocs.akamai.com/linode-api/reference/pagination).
                        example: 1
                        readOnly: true
                        type: integer
                      pages:
                        description: >-
                          __Read-only__ The total number of
                          [pages](https://techdocs.akamai.com/linode-api/reference/pagination).
                        example: 1
                        readOnly: true
                        type: integer
                      results:
                        description: __Read-only__ The total number of results.
                        example: 1
                        readOnly: true
                        type: integer
                    type: object
                    x-akamai:
                      file-path: schemas/pagination-envelope.yaml
                  - properties:
                      data:
                        items:
                          additionalProperties: false
                          description: An object representing Beta Program information.
                          properties:
                            description:
                              description: >-
                                __Read-only__ Additional details regarding the
                                Beta Program.
                              example: >-
                                This is an open public beta for an example
                                feature.
                              nullable: true
                              readOnly: true
                              type: string
                              x-linode-cli-display: 3
                            ended:
                              description: >-
                                __Filterable__, __Read-only__ The date-time that
                                the Beta Program ended.


                                `null` indicates that the Beta Program is
                                ongoing.
                              example: null
                              format: date-time
                              nullable: true
                              readOnly: true
                              type: string
                              x-akamai:
                                labels:
                                  - Filterable
                              x-linode-cli-display: 6
                              x-linode-filterable: true
                            greenlight_only:
                              description: >-
                                __Filterable__, __Read-only__ Whether the Beta
                                Program requires [Green
                                Light](https://www.linode.com/green-light/)
                                participation for enrollment.
                              example: true
                              readOnly: true
                              type: boolean
                              x-akamai:
                                labels:
                                  - Filterable
                              x-linode-cli-display: 4
                              x-linode-filterable: true
                            id:
                              description: The unique identifier of the Beta Program.
                              example: example_open
                              type: string
                              x-linode-cli-display: 1
                            label:
                              description: >-
                                __Filterable__, __Read-only__ The name of the
                                Beta Program.
                              example: Example Open Beta
                              readOnly: true
                              type: string
                              x-akamai:
                                labels:
                                  - Filterable
                              x-linode-cli-display: 2
                              x-linode-filterable: true
                            more_info:
                              description: >-
                                __Read-only__ Additional source of information
                                for the Beta Program.
                              example: https://www.linode.com/green-light/
                              nullable: true
                              readOnly: true
                              type: string
                              x-linode-cli-display: 7
                            started:
                              description: >-
                                __Filterable__, __Read-only__ The start
                                date-time of the Beta Program.
                              example: '2023-07-11T00:00:00'
                              format: date-time
                              readOnly: true
                              type: string
                              x-akamai:
                                labels:
                                  - Filterable
                              x-linode-cli-display: 5
                              x-linode-filterable: true
                          type: object
                          x-akamai:
                            file-path: schemas/beta-program.yaml
                        type: array
                    type: object
                x-akamai:
                  file-path: schemas/added-get-beta-programs-200.yaml
          description: Returns a paginated list of all available Beta Program objects.
        default:
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  errors:
                    items:
                      additionalProperties: false
                      description: >-
                        An object for describing a single error that occurred
                        during the processing of a request.
                      properties:
                        field:
                          description: >-
                            The field in the request that caused this error.
                            This may be a path, separated by periods in the case
                            of nested fields. In some cases this may come back
                            as `null` if the error is not specific to any single
                            element of the request.
                          example: fieldname
                          type: string
                        reason:
                          description: >-
                            What happened to cause this error. In most cases,
                            this can be fixed immediately by changing the data
                            you sent in the request, but in some cases you will
                            be instructed to [Open a support
                            ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket)
                            or perform some other action before you can complete
                            the request successfully.
                          example: fieldname must be a valid value
                          type: string
                      type: object
                      x-akamai:
                        file-path: schemas/error-object.yaml
                    type: array
                type: object
          description: >-
            See
            [Errors](https://techdocs.akamai.com/linode-api/reference/errors)
            for the range of possible error response codes.
      security:
        - personalAccessToken: []
        - oauth: []
      summary: List Beta programs
      tags:
        - Beta programs
      x-akamai:
        tabs:
          - syntax: linode-cli betas list
            title: CLI
            url: >-
              https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli
      x-linode-cli-action:
        - list
        - ls
      x-linode-grant: unrestricted only
    parameters: []
    x-akamai:
      file-path: paths/betas.yaml
      path-info: /{apiVersion}/betas
    x-linode-cli-command: betas
  /betas/{betaId}:
    get:
      description: >-
        Display information about a Beta Program. This operation can be used to
        access inactive as well as active Beta Programs.


        Only unrestricted Users can access this operation.


        [Learn
        more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)
      externalDocs:
        description: See documentation for this operation in Akamai's Linode API
        url: https://techdocs.akamai.com/linode-api/reference/get-beta-program
      operationId: get-beta-program
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: false
                description: An object representing Beta Program information.
                properties:
                  description:
                    description: >-
                      __Read-only__ Additional details regarding the Beta
                      Program.
                    example: This is an open public beta for an example feature.
                    nullable: true
                    readOnly: true
                    type: string
                    x-linode-cli-display: 3
                  ended:
                    description: >-
                      __Filterable__, __Read-only__ The date-time that the Beta
                      Program ended.


                      `null` indicates that the Beta Program is ongoing.
                    example: null
                    format: date-time
                    nullable: true
                    readOnly: true
                    type: string
                    x-akamai:
                      labels:
                        - Filterable
                    x-linode-cli-display: 6
                    x-linode-filterable: true
                  greenlight_only:
                    description: >-
                      __Filterable__, __Read-only__ Whether the Beta Program
                      requires [Green
                      Light](https://www.linode.com/green-light/) participation
                      for enrollment.
                    example: true
                    readOnly: true
                    type: boolean
                    x-akamai:
                      labels:
                        - Filterable
                    x-linode-cli-display: 4
                    x-linode-filterable: true
                  id:
                    description: The unique identifier of the Beta Program.
                    example: example_open
                    type: string
                    x-linode-cli-display: 1
                  label:
                    description: >-
                      __Filterable__, __Read-only__ The name of the Beta
                      Program.
                    example: Example Open Beta
                    readOnly: true
                    type: string
                    x-akamai:
                      labels:
                        - Filterable
                    x-linode-cli-display: 2
                    x-linode-filterable: true
                  more_info:
                    description: >-
                      __Read-only__ Additional source of information for the
                      Beta Program.
                    example: https://www.linode.com/green-light/
                    nullable: true
                    readOnly: true
                    type: string
                    x-linode-cli-display: 7
                  started:
                    description: >-
                      __Filterable__, __Read-only__ The start date-time of the
                      Beta Program.
                    example: '2023-07-11T00:00:00'
                    format: date-time
                    readOnly: true
                    type: string
                    x-akamai:
                      labels:
                        - Filterable
                    x-linode-cli-display: 5
                    x-linode-filterable: true
                type: object
                x-akamai:
                  file-path: schemas/beta-program.yaml
              x-example:
                x-ref: ../examples/get-beta-program-200.json
          description: Returns a paginated list of all available Beta Program objects.
        default:
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  errors:
                    items:
                      additionalProperties: false
                      description: >-
                        An object for describing a single error that occurred
                        during the processing of a request.
                      properties:
                        field:
                          description: >-
                            The field in the request that caused this error.
                            This may be a path, separated by periods in the case
                            of nested fields. In some cases this may come back
                            as `null` if the error is not specific to any single
                            element of the request.
                          example: fieldname
                          type: string
                        reason:
                          description: >-
                            What happened to cause this error. In most cases,
                            this can be fixed immediately by changing the data
                            you sent in the request, but in some cases you will
                            be instructed to [Open a support
                            ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket)
                            or perform some other action before you can complete
                            the request successfully.
                          example: fieldname must be a valid value
                          type: string
                      type: object
                      x-akamai:
                        file-path: schemas/error-object.yaml
                    type: array
                type: object
          description: >-
            See
            [Errors](https://techdocs.akamai.com/linode-api/reference/errors)
            for the range of possible error response codes.
      security:
        - personalAccessToken: []
        - oauth: []
      summary: Get a Beta program
      tags:
        - Beta programs
      x-akamai:
        tabs:
          - syntax: linode-cli betas view $betaId
            title: CLI
            url: >-
              https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli
      x-linode-cli-action: view
      x-linode-grant: unrestricted only
    parameters:
      - description: The ID of the Beta Program.
        example: '{{betaId}}'
        in: path
        name: betaId
        required: true
        schema:
          type: string
        x-akamai:
          file-path: parameters/beta-id.yaml
    x-akamai:
      file-path: paths/beta.yaml
      path-info: /{apiVersion}/betas/{betaId}
    x-linode-cli-command: betas
components:
  x-stackQL-resources:
    beta_programs:
      id: linode.betas.beta_programs
      name: beta_programs
      title: Beta Programs
      methods:
        get_beta_programs:
          operation:
            $ref: '#/paths/~1betas/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.data
        get_beta_program:
          operation:
            $ref: '#/paths/~1betas~1{betaId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/beta_programs/methods/get_beta_program
          - $ref: >-
              #/components/x-stackQL-resources/beta_programs/methods/get_beta_programs
        insert: []
        update: []
        delete: []
        replace: []
servers:
  - url: https://api.linode.com/v4
