openapi: 3.0.1
info:
  title: maintenance API
  description: linode maintenance API
  version: 4.215.0
paths:
  /maintenance/policies:
    get:
      description: >-
        __Beta__ List all available maintenance policies that can be applied to
        your Linodes.


        > 📘

        >

        > This operation is beta and only works when using the beta API. Call
        the URL with the `apiVersion` path parameter set to `v4beta`.


        [Learn
        more...](https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli)
      externalDocs:
        description: See documentation for this operation in Akamai's Linode API
        url: >-
          https://techdocs.akamai.com/linode-api/reference/get-maintenance-policies
      operationId: get-maintenance-policies
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  data:
                    items:
                      additionalProperties: false
                      description: Information about maintenance policies.
                      properties:
                        description:
                          description: >-
                            A brief explanation of the maintenance policy's
                            intended behavior.
                          example: >-
                            Migrates the Linode to a new host while it remains
                            fully operational. Recommended for maximizing
                            availability.
                          type: string
                        is_default:
                          description: >-
                            Indicates whether this policy is the default one
                            applied when creating a Linode.
                          example: true
                          type: boolean
                        label:
                          description: The display name for the maintenance policy.
                          example: Migrate
                          type: string
                        notification_period_sec:
                          description: >-
                            __Filterable__ Number of seconds before the
                            maintenance event triggers. A value of 0 means no
                            prior notification.
                          example: 10800
                          type: integer
                          x-akamai:
                            labels:
                              - Filterable
                          x-linode-filterable: true
                        slug:
                          description: >-
                            Unique identifier for the maintenance policy. System
                            policies are prefixed with `linode/`.
                          example: linode/migrate
                          type: string
                        type:
                          description: The type of policy.
                          enum:
                            - migrate
                            - power_off_on
                          example: migrate
                          type: string
                      type: object
                      x-akamai:
                        file-path: schemas/maintenance-policies.yaml
                    type: array
                  page:
                    description: >-
                      __Read-only__ The current
                      [page](https://techdocs.akamai.com/linode-api/reference/pagination).
                    example: 1
                    readOnly: true
                    type: integer
                  pages:
                    description: >-
                      __Read-only__ The total number of
                      [pages](https://techdocs.akamai.com/linode-api/reference/pagination).
                    example: 1
                    readOnly: true
                    type: integer
                  results:
                    description: __Read-only__ The total number of results.
                    example: 1
                    readOnly: true
                    type: integer
                type: object
                x-akamai:
                  file-path: schemas/get-maintenance-policies-200.yaml
              x-example:
                x-ref: ../examples/get-maintenance-policies-200.json
          description: Returns a paginated list of maintenance policy objects.
        default:
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  errors:
                    items:
                      additionalProperties: false
                      description: >-
                        An object for describing a single error that occurred
                        during the processing of a request.
                      properties:
                        field:
                          description: >-
                            The field in the request that caused this error.
                            This may be a path, separated by periods in the case
                            of nested fields. In some cases this may come back
                            as `null` if the error is not specific to any single
                            element of the request.
                          example: fieldname
                          type: string
                        reason:
                          description: >-
                            What happened to cause this error. In most cases,
                            this can be fixed immediately by changing the data
                            you sent in the request, but in some cases you will
                            be instructed to [Open a support
                            ticket](https://techdocs.akamai.com/linode-api/reference/post-ticket)
                            or perform some other action before you can complete
                            the request successfully.
                          example: fieldname must be a valid value
                          type: string
                      type: object
                      x-akamai:
                        file-path: schemas/error-object.yaml
                    type: array
                type: object
          description: >-
            See
            [Errors](https://techdocs.akamai.com/linode-api/reference/errors)
            for the range of possible error response codes.
      security:
        - personalAccessToken: []
        - oauth: []
      summary: List maintenance policies
      tags:
        - Maintenance policies
      x-akamai:
        status: BETA
        tabs:
          - syntax: linode-cli maintenance policies-list
            title: CLI
            url: >-
              https://techdocs.akamai.com/cloud-computing/docs/getting-started-with-the-linode-cli
      x-linode-cli-action: policies-list
      x-linode-grant: read_only
    parameters: []
    x-akamai:
      file-path: paths/maintenance-policies.yaml
      path-info: /{apiVersion}/maintenance/policies
    x-linode-cli-command: maintenance
components:
  x-stackQL-resources:
    policies:
      id: linode.maintenance.policies
      name: policies
      title: Policies
      methods:
        list:
          operation:
            $ref: '#/paths/~1maintenance~1policies/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.data
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/policies/methods/list'
        insert: []
        update: []
        delete: []
        replace: []
servers:
  - url: https://api.linode.com/v4
x-stackQL-config:
  pagination:
    algorithm: page_number
    requestToken:
      key: page
      location: query
    responseToken:
      key: $.page
      location: body
    responseTerminator:
      key: $.pages
      location: body
