id: googledevelopers
name: googledevelopers
version: v00.00.00000
providerServices:
  abusiveexperiencereport:
    description: Views Abusive Experience Report data, and gets a list of sites that have a significant number of abusive experiences.
    id: abusiveexperiencereport:v00.00.00000
    name: abusiveexperiencereport
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/abusiveexperiencereport.yaml
    title: Abusive Experience Report API
    version: v00.00.00000
  acceleratedmobilepageurl:
    description: 'Retrieves the list of AMP URLs (and equivalent AMP Cache URLs) for a given list of public URL(s). '
    id: acceleratedmobilepageurl:v00.00.00000
    name: acceleratedmobilepageurl
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/acceleratedmobilepageurl.yaml
    title: Accelerated Mobile Pages (AMP) URL API
    version: v00.00.00000
  androiddeviceprovisioning:
    description: Automates Android zero-touch enrollment for device resellers, customers, and EMMs.
    id: androiddeviceprovisioning:v00.00.00000
    name: androiddeviceprovisioning
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/androiddeviceprovisioning.yaml
    title: Android Device Provisioning Partner API
    version: v00.00.00000
  androidenterprise:
    description: Manages the deployment of apps to Android Enterprise devices.
    id: androidenterprise:v00.00.00000
    name: androidenterprise
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/androidenterprise.yaml
    title: Google Play EMM API
    version: v00.00.00000
  androidmanagement:
    description: The Android Management API provides remote enterprise management of Android devices and apps.
    id: androidmanagement:v00.00.00000
    name: androidmanagement
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/androidmanagement.yaml
    title: Android Management API
    version: v00.00.00000
  androidpublisher:
    description: 'Lets Android application developers access their Google Play accounts. At a high level, the expected workflow is to "insert" an Edit, make changes as necessary, and then "commit" it. '
    id: androidpublisher:v00.00.00000
    name: androidpublisher
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/androidpublisher.yaml
    title: Google Play Android Developer API
    version: v00.00.00000
  area120tables:
    description: ''
    id: area120tables:v00.00.00000
    name: area120tables
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/area120tables.yaml
    title: Area120 Tables API
    version: v00.00.00000
  authorizedbuyersmarketplace:
    description: The Authorized Buyers Marketplace API lets buyers programmatically discover inventory; propose, retrieve and negotiate deals with publishers.
    id: authorizedbuyersmarketplace:v00.00.00000
    name: authorizedbuyersmarketplace
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/authorizedbuyersmarketplace.yaml
    title: Authorized Buyers Marketplace API
    version: v00.00.00000
  blogger:
    description: The Blogger API provides access to posts, comments and pages of a Blogger blog.
    id: blogger:v00.00.00000
    name: blogger
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/blogger.yaml
    title: Blogger API
    version: v00.00.00000
  books:
    description: The Google Books API allows clients to access the Google Books repository.
    id: books:v00.00.00000
    name: books
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/books.yaml
    title: Books API
    version: v00.00.00000
  civicinfo:
    description: Provides polling places, early vote locations, contest data, election officials, and government representatives for U.S. residential addresses.
    id: civicinfo:v00.00.00000
    name: civicinfo
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/civicinfo.yaml
    title: Google Civic Information API
    version: v00.00.00000
  content:
    description: Manage your product listings and accounts for Google Shopping
    id: content:v00.00.00000
    name: content
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/content.yaml
    title: Content API for Shopping
    version: v00.00.00000
  customsearch:
    description: Searches over a website or collection of websites
    id: customsearch:v00.00.00000
    name: customsearch
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/customsearch.yaml
    title: Custom Search API
    version: v00.00.00000
  digitalassetlinks:
    description: Discovers relationships between online assets such as websites or mobile apps.
    id: digitalassetlinks:v00.00.00000
    name: digitalassetlinks
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/digitalassetlinks.yaml
    title: Digital Asset Links API
    version: v00.00.00000
  discovery:
    description: Provides information about other Google APIs, such as what APIs are available, the resource, and method details for each API.
    id: discovery:v00.00.00000
    name: discovery
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/discovery.yaml
    title: API Discovery Service
    version: v00.00.00000
  displayvideo:
    description: Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.
    id: displayvideo:v00.00.00000
    name: displayvideo
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/displayvideo.yaml
    title: Display & Video 360 API
    version: v00.00.00000
  domainsrdap:
    description: Read-only public API that lets users search for information about domain names.
    id: domainsrdap:v00.00.00000
    name: domainsrdap
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/domainsrdap.yaml
    title: Domains RDAP API
    version: v00.00.00000
  factchecktools:
    description: ''
    id: factchecktools:v00.00.00000
    name: factchecktools
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/factchecktools.yaml
    title: Fact Check Tools API
    version: v00.00.00000
  fitness:
    description: The Fitness API for managing users' fitness tracking data.
    id: fitness:v00.00.00000
    name: fitness
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/fitness.yaml
    title: Fitness API
    version: v00.00.00000
  games:
    description: The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.
    id: games:v00.00.00000
    name: games
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/games.yaml
    title: Google Play Game Services
    version: v00.00.00000
  gamesConfiguration:
    description: The Google Play Game Services Publishing API allows developers to configure their games in Game Services.
    id: gamesConfiguration:v00.00.00000
    name: gamesConfiguration
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/gamesConfiguration.yaml
    title: Google Play Game Services Publishing API
    version: v00.00.00000
  gamesManagement:
    description: The Google Play Game Management API allows developers to manage resources from the Google Play Game service.
    id: gamesManagement:v00.00.00000
    name: gamesManagement
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/gamesManagement.yaml
    title: Google Play Game Management
    version: v00.00.00000
  homegraph:
    description: ''
    id: homegraph:v00.00.00000
    name: homegraph
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/homegraph.yaml
    title: HomeGraph API
    version: v00.00.00000
  indexing:
    description: Notifies Google when your web pages change.
    id: indexing:v00.00.00000
    name: indexing
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/indexing.yaml
    title: Indexing API
    version: v00.00.00000
  kgsearch:
    description: Searches the Google Knowledge Graph for entities.
    id: kgsearch:v00.00.00000
    name: kgsearch
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/kgsearch.yaml
    title: Knowledge Graph Search API
    version: v00.00.00000
  manufacturers:
    description: Public API for managing Manufacturer Center related data.
    id: manufacturers:v00.00.00000
    name: manufacturers
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/manufacturers.yaml
    title: Manufacturer Center API
    version: v00.00.00000
  oauth2:
    description: Obtains end-user authorization grants for use with other Google APIs.
    id: oauth2:v00.00.00000
    name: oauth2
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/oauth2.yaml
    title: Google OAuth2 API
    version: v00.00.00000
  pagespeedonline:
    description: 'The PageSpeed Insights API lets you analyze the performance of your website with a simple API. It offers tailored suggestions for how you can optimize your site, and lets you easily integrate PageSpeed Insights analysis into your development tools and workflow. '
    id: pagespeedonline:v00.00.00000
    name: pagespeedonline
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/pagespeedonline.yaml
    title: PageSpeed Insights API
    version: v00.00.00000
  paymentsresellersubscription:
    description: ''
    id: paymentsresellersubscription:v00.00.00000
    name: paymentsresellersubscription
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/paymentsresellersubscription.yaml
    title: Payments Reseller Subscription API
    version: v00.00.00000
  people:
    description: Provides access to information about profiles and contacts.
    id: people:v00.00.00000
    name: people
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/people.yaml
    title: People API
    version: v00.00.00000
  playcustomapp:
    description: API to create and publish custom Android apps
    id: playcustomapp:v00.00.00000
    name: playcustomapp
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/playcustomapp.yaml
    title: Google Play Custom App Publishing API
    version: v00.00.00000
  playdeveloperreporting:
    description: ''
    id: playdeveloperreporting:v00.00.00000
    name: playdeveloperreporting
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/playdeveloperreporting.yaml
    title: Google Play Developer Reporting API
    version: v00.00.00000
  playintegrity:
    description: The Play Integrity API helps you check that you're interacting with your genuine app on a genuine Android device powered by Google Play services. The Play Integrity API has replaced SafetyNet Attestation and Android Device Verification.
    id: playintegrity:v00.00.00000
    name: playintegrity
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/playintegrity.yaml
    title: Google Play Integrity API
    version: v00.00.00000
  poly:
    description: 'The Poly API provides read access to assets hosted on poly.google.com to all, and upload access to poly.google.com for whitelisted accounts. '
    id: poly:v00.00.00000
    name: poly
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/poly.yaml
    title: Poly API
    version: v00.00.00000
  prod_tt_sasportal:
    description: ''
    id: prod_tt_sasportal:v00.00.00000
    name: prod_tt_sasportal
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/prod_tt_sasportal.yaml
    title: SAS Portal API (Testing)
    version: v00.00.00000
  safebrowsing:
    description: Enables client applications to check web resources (most commonly URLs) against Google-generated lists of unsafe web resources. The Safe Browsing APIs are for non-commercial use only. If you need to use APIs to detect malicious URLs for commercial purposes – meaning “for sale or revenue-generating purposes” – please refer to the Web Risk API.
    id: safebrowsing:v00.00.00000
    name: safebrowsing
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/safebrowsing.yaml
    title: Safe Browsing API
    version: v00.00.00000
  sasportal:
    description: ''
    id: sasportal:v00.00.00000
    name: sasportal
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/sasportal.yaml
    title: SAS Portal API
    version: v00.00.00000
  searchconsole:
    description: The Search Console API provides access to both Search Console data (verified users only) and to public information on an URL basis (anyone)
    id: searchconsole:v00.00.00000
    name: searchconsole
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/searchconsole.yaml
    title: Google Search Console API
    version: v00.00.00000
  smartdevicemanagement:
    description: Allow select enterprise partners to access, control, and manage Google and Nest devices programmatically.
    id: smartdevicemanagement:v00.00.00000
    name: smartdevicemanagement
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/smartdevicemanagement.yaml
    title: Smart Device Management API
    version: v00.00.00000
  streetviewpublish:
    description: 'Publishes 360 photos to Google Maps, along with position, orientation, and connectivity metadata. Apps can offer an interface for positioning, connecting, and uploading user-generated Street View images. '
    id: streetviewpublish:v00.00.00000
    name: streetviewpublish
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/streetviewpublish.yaml
    title: Street View Publish API
    version: v00.00.00000
  travelimpactmodel:
    description: Travel Impact Model API lets you query travel carbon emission estimates.
    id: travelimpactmodel:v00.00.00000
    name: travelimpactmodel
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/travelimpactmodel.yaml
    title: Travel Impact Model API
    version: v00.00.00000
  verifiedaccess:
    description: API for Verified Access chrome extension to provide credential verification for chrome devices connecting to an enterprise network
    id: verifiedaccess:v00.00.00000
    name: verifiedaccess
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/verifiedaccess.yaml
    title: Chrome Verified Access API
    version: v00.00.00000
  versionhistory:
    description: Version History API - Prod
    id: versionhistory:v00.00.00000
    name: versionhistory
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/versionhistory.yaml
    title: versionhistory.googleapis.com API
    version: v00.00.00000
  webfonts:
    description: The Google Web Fonts Developer API lets you retrieve information about web fonts served by Google.
    id: webfonts:v00.00.00000
    name: webfonts
    preferred: true
    service:
      $ref: googledevelopers/v00.00.00000/services/webfonts.yaml
    title: Web Fonts Developer API
    version: v00.00.00000
openapi: 3.1.0
