id: github
name: github
version: v0.1.1
providerServices:
  activity:
    description: Activity APIs provide access to notifications, subscriptions, and timelines.
    id: activity:v0.1.1
    name: activity
    preferred: true
    service:
      $ref: github/v0.1.1/services/activity.yaml
    title: GitHub v3 REST API - activity
    version: v0.1.1
  apps:
    description: Information for integrations and installations.
    id: apps:v0.1.1
    name: apps
    preferred: true
    service:
      $ref: github/v0.1.1/services/apps.yaml
    title: GitHub v3 REST API - apps
    version: v0.1.1
  billing:
    description: Monitor charges and usage from Actions and Packages.
    id: billing:v0.1.1
    name: billing
    preferred: true
    service:
      $ref: github/v0.1.1/services/billing.yaml
    title: GitHub v3 REST API - billing
    version: v0.1.1
  codes_of_conduct:
    description: codes_of_conduct
    id: codes_of_conduct:v0.1.1
    name: codes_of_conduct
    preferred: true
    service:
      $ref: github/v0.1.1/services/codes_of_conduct.yaml
    title: GitHub v3 REST API - codes_of_conduct
    version: v0.1.1
  codespaces:
    description: Endpoints to manage Codespaces using the REST API.
    id: codespaces:v0.1.1
    name: codespaces
    preferred: true
    service:
      $ref: github/v0.1.1/services/codespaces.yaml
    title: GitHub v3 REST API - codespaces
    version: v0.1.1
  emojis:
    description: List emojis available to use on GitHub.
    id: emojis:v0.1.1
    name: emojis
    preferred: true
    service:
      $ref: github/v0.1.1/services/emojis.yaml
    title: GitHub v3 REST API - emojis
    version: v0.1.1
  enterprise_actions:
    description: Endpoints to manage GitHub Actions using the REST API.
    id: enterprise_actions:v0.1.1
    name: enterprise_actions
    preferred: true
    service:
      $ref: github/v0.1.1/services/enterprise_actions.yaml
    title: GitHub v3 REST API - enterprise_actions
    version: v0.1.1
  enterprise_admin:
    description: enterprise_admin
    id: enterprise_admin:v0.1.1
    name: enterprise_admin
    preferred: true
    service:
      $ref: github/v0.1.1/services/enterprise_admin.yaml
    title: GitHub v3 REST API - enterprise_admin
    version: v0.1.1
  enterprise_secret_scanning:
    description: secret_scanning
    id: enterprise_secret_scanning:v0.1.1
    name: enterprise_secret_scanning
    preferred: true
    service:
      $ref: github/v0.1.1/services/enterprise_secret_scanning.yaml
    title: GitHub v3 REST API - enterprise_secret_scanning
    version: v0.1.1
  gists:
    description: View, modify your gists.
    id: gists:v0.1.1
    name: gists
    preferred: true
    service:
      $ref: github/v0.1.1/services/gists.yaml
    title: GitHub v3 REST API - gists
    version: v0.1.1
  gitignore:
    description: View gitignore templates
    id: gitignore:v0.1.1
    name: gitignore
    preferred: true
    service:
      $ref: github/v0.1.1/services/gitignore.yaml
    title: GitHub v3 REST API - gitignore
    version: v0.1.1
  interactions:
    description: Owner or admin management of users interactions.
    id: interactions:v0.1.1
    name: interactions
    preferred: true
    service:
      $ref: github/v0.1.1/services/interactions.yaml
    title: GitHub v3 REST API - interactions
    version: v0.1.1
  issues:
    description: Interact with GitHub Issues.
    id: issues:v0.1.1
    name: issues
    preferred: true
    service:
      $ref: github/v0.1.1/services/issues.yaml
    title: GitHub v3 REST API - issues
    version: v0.1.1
  licenses:
    description: View various OSS licenses.
    id: licenses:v0.1.1
    name: licenses
    preferred: true
    service:
      $ref: github/v0.1.1/services/licenses.yaml
    title: GitHub v3 REST API - licenses
    version: v0.1.1
  markdown:
    description: Render GitHub flavored markdown
    id: markdown:v0.1.1
    name: markdown
    preferred: true
    service:
      $ref: github/v0.1.1/services/markdown.yaml
    title: GitHub v3 REST API - markdown
    version: v0.1.1
  meta:
    description: Endpoints that give information about the API.
    id: meta:v0.1.1
    name: meta
    preferred: true
    service:
      $ref: github/v0.1.1/services/meta.yaml
    title: GitHub v3 REST API - meta
    version: v0.1.1
  migrations:
    description: Move projects to or from GitHub.
    id: migrations:v0.1.1
    name: migrations
    preferred: true
    service:
      $ref: github/v0.1.1/services/migrations.yaml
    title: GitHub v3 REST API - migrations
    version: v0.1.1
  oauth_authorizations:
    description: oauth_authorizations
    id: oauth_authorizations:v0.1.1
    name: oauth_authorizations
    preferred: true
    service:
      $ref: github/v0.1.1/services/oauth_authorizations.yaml
    title: GitHub v3 REST API - oauth_authorizations
    version: v0.1.1
  org_actions:
    description: Endpoints to manage GitHub Actions using the REST API.
    id: org_actions:v0.1.1
    name: org_actions
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_actions.yaml
    title: GitHub v3 REST API - org_actions
    version: v0.1.1
  org_activity:
    description: Activity APIs provide access to notifications, subscriptions, and timelines.
    id: org_activity:v0.1.1
    name: org_activity
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_activity.yaml
    title: GitHub v3 REST API - org_activity
    version: v0.1.1
  org_apps:
    description: Information for integrations and installations.
    id: org_apps:v0.1.1
    name: org_apps
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_apps.yaml
    title: GitHub v3 REST API - org_apps
    version: v0.1.1
  org_billing:
    description: Monitor charges and usage from Actions and Packages.
    id: org_billing:v0.1.1
    name: org_billing
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_billing.yaml
    title: GitHub v3 REST API - org_billing
    version: v0.1.1
  org_code_scanning:
    description: code_scanning
    id: org_code_scanning:v0.1.1
    name: org_code_scanning
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_code_scanning.yaml
    title: GitHub v3 REST API - org_code_scanning
    version: v0.1.1
  org_dependabot:
    description: Endpoints to manage Dependabot.
    id: org_dependabot:v0.1.1
    name: org_dependabot
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_dependabot.yaml
    title: GitHub v3 REST API - org_dependabot
    version: v0.1.1
  org_interactions:
    description: Owner or admin management of users interactions.
    id: org_interactions:v0.1.1
    name: org_interactions
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_interactions.yaml
    title: GitHub v3 REST API - org_interactions
    version: v0.1.1
  org_issues:
    description: Interact with GitHub Issues.
    id: org_issues:v0.1.1
    name: org_issues
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_issues.yaml
    title: GitHub v3 REST API - org_issues
    version: v0.1.1
  org_migrations:
    description: Move projects to or from GitHub.
    id: org_migrations:v0.1.1
    name: org_migrations
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_migrations.yaml
    title: GitHub v3 REST API - org_migrations
    version: v0.1.1
  org_packages:
    description: Manage packages for authenticated users and organizations.
    id: org_packages:v0.1.1
    name: org_packages
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_packages.yaml
    title: GitHub v3 REST API - org_packages
    version: v0.1.1
  org_projects:
    description: Interact with GitHub Projects.
    id: org_projects:v0.1.1
    name: org_projects
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_projects.yaml
    title: GitHub v3 REST API - org_projects
    version: v0.1.1
  org_reactions:
    description: Interact with reactions to various GitHub entities.
    id: org_reactions:v0.1.1
    name: org_reactions
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_reactions.yaml
    title: GitHub v3 REST API - org_reactions
    version: v0.1.1
  org_repos:
    description: Interact with GitHub Repos.
    id: org_repos:v0.1.1
    name: org_repos
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_repos.yaml
    title: GitHub v3 REST API - org_repos
    version: v0.1.1
  org_secret_scanning:
    description: secret_scanning
    id: org_secret_scanning:v0.1.1
    name: org_secret_scanning
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_secret_scanning.yaml
    title: GitHub v3 REST API - org_secret_scanning
    version: v0.1.1
  org_teams:
    description: Interact with GitHub Teams.
    id: org_teams:v0.1.1
    name: org_teams
    preferred: true
    service:
      $ref: github/v0.1.1/services/org_teams.yaml
    title: GitHub v3 REST API - org_teams
    version: v0.1.1
  orgs:
    description: Interact with GitHub Orgs.
    id: orgs:v0.1.1
    name: orgs
    preferred: true
    service:
      $ref: github/v0.1.1/services/orgs.yaml
    title: GitHub v3 REST API - orgs
    version: v0.1.1
  packages:
    description: Manage packages for authenticated users and organizations.
    id: packages:v0.1.1
    name: packages
    preferred: true
    service:
      $ref: github/v0.1.1/services/packages.yaml
    title: GitHub v3 REST API - packages
    version: v0.1.1
  projects:
    description: Interact with GitHub Projects.
    id: projects:v0.1.1
    name: projects
    preferred: true
    service:
      $ref: github/v0.1.1/services/projects.yaml
    title: GitHub v3 REST API - projects
    version: v0.1.1
  rate_limit:
    description: rate_limit
    id: rate_limit:v0.1.1
    name: rate_limit
    preferred: true
    service:
      $ref: github/v0.1.1/services/rate_limit.yaml
    title: GitHub v3 REST API - rate_limit
    version: v0.1.1
  reactions:
    description: Interact with reactions to various GitHub entities.
    id: reactions:v0.1.1
    name: reactions
    preferred: true
    service:
      $ref: github/v0.1.1/services/reactions.yaml
    title: GitHub v3 REST API - reactions
    version: v0.1.1
  repo_actions:
    description: Endpoints to manage GitHub Actions using the REST API.
    id: repo_actions:v0.1.1
    name: repo_actions
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_actions.yaml
    title: GitHub v3 REST API - repo_actions
    version: v0.1.1
  repo_activity:
    description: Activity APIs provide access to notifications, subscriptions, and timelines.
    id: repo_activity:v0.1.1
    name: repo_activity
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_activity.yaml
    title: GitHub v3 REST API - repo_activity
    version: v0.1.1
  repo_apps:
    description: Information for integrations and installations.
    id: repo_apps:v0.1.1
    name: repo_apps
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_apps.yaml
    title: GitHub v3 REST API - repo_apps
    version: v0.1.1
  repo_checks:
    description: Rich interactions with checks run by your integrations.
    id: repo_checks:v0.1.1
    name: repo_checks
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_checks.yaml
    title: GitHub v3 REST API - repo_checks
    version: v0.1.1
  repo_code_scanning:
    description: code_scanning
    id: repo_code_scanning:v0.1.1
    name: repo_code_scanning
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_code_scanning.yaml
    title: GitHub v3 REST API - repo_code_scanning
    version: v0.1.1
  repo_codespaces:
    description: Endpoints to manage Codespaces using the REST API.
    id: repo_codespaces:v0.1.1
    name: repo_codespaces
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_codespaces.yaml
    title: GitHub v3 REST API - repo_codespaces
    version: v0.1.1
  repo_dependabot:
    description: Endpoints to manage Dependabot.
    id: repo_dependabot:v0.1.1
    name: repo_dependabot
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_dependabot.yaml
    title: GitHub v3 REST API - repo_dependabot
    version: v0.1.1
  repo_git:
    description: Raw Git functionality.
    id: repo_git:v0.1.1
    name: repo_git
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_git.yaml
    title: GitHub v3 REST API - repo_git
    version: v0.1.1
  repo_interactions:
    description: Owner or admin management of users interactions.
    id: repo_interactions:v0.1.1
    name: repo_interactions
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_interactions.yaml
    title: GitHub v3 REST API - repo_interactions
    version: v0.1.1
  repo_issues:
    description: Interact with GitHub Issues.
    id: repo_issues:v0.1.1
    name: repo_issues
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_issues.yaml
    title: GitHub v3 REST API - repo_issues
    version: v0.1.1
  repo_licenses:
    description: View various OSS licenses.
    id: repo_licenses:v0.1.1
    name: repo_licenses
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_licenses.yaml
    title: GitHub v3 REST API - repo_licenses
    version: v0.1.1
  repo_migrations:
    description: Move projects to or from GitHub.
    id: repo_migrations:v0.1.1
    name: repo_migrations
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_migrations.yaml
    title: GitHub v3 REST API - repo_migrations
    version: v0.1.1
  repo_projects:
    description: Interact with GitHub Projects.
    id: repo_projects:v0.1.1
    name: repo_projects
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_projects.yaml
    title: GitHub v3 REST API - repo_projects
    version: v0.1.1
  repo_pulls:
    description: Interact with GitHub Pull Requests.
    id: repo_pulls:v0.1.1
    name: repo_pulls
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_pulls.yaml
    title: GitHub v3 REST API - repo_pulls
    version: v0.1.1
  repo_reactions:
    description: Interact with reactions to various GitHub entities.
    id: repo_reactions:v0.1.1
    name: repo_reactions
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_reactions.yaml
    title: GitHub v3 REST API - repo_reactions
    version: v0.1.1
  repo_secret_scanning:
    description: secret_scanning
    id: repo_secret_scanning:v0.1.1
    name: repo_secret_scanning
    preferred: true
    service:
      $ref: github/v0.1.1/services/repo_secret_scanning.yaml
    title: GitHub v3 REST API - repo_secret_scanning
    version: v0.1.1
  repos:
    description: Interact with GitHub Repos.
    id: repos:v0.1.1
    name: repos
    preferred: true
    service:
      $ref: github/v0.1.1/services/repos.yaml
    title: GitHub v3 REST API - repos
    version: v0.1.1
  scim:
    description: Provisioning of GitHub organization membership for SCIM-enabled providers.
    id: scim:v0.1.1
    name: scim
    preferred: true
    service:
      $ref: github/v0.1.1/services/scim.yaml
    title: GitHub v3 REST API - scim
    version: v0.1.1
  search:
    description: Look for stuff on GitHub.
    id: search:v0.1.1
    name: search
    preferred: true
    service:
      $ref: github/v0.1.1/services/search.yaml
    title: GitHub v3 REST API - search
    version: v0.1.1
  teams:
    description: Interact with GitHub Teams.
    id: teams:v0.1.1
    name: teams
    preferred: true
    service:
      $ref: github/v0.1.1/services/teams.yaml
    title: GitHub v3 REST API - teams
    version: v0.1.1
  users:
    description: Interact with and view information about users and also current user.
    id: users:v0.1.1
    name: users
    preferred: true
    service:
      $ref: github/v0.1.1/services/users.yaml
    title: GitHub v3 REST API - users
    version: v0.1.1
openapi: 3.0.3
