openapi: 3.0.0
servers:
  - url: https://management.azure.com/
info:
  title: Azure Terraform
  description: Export existing Azure resources as Terraform configuration (Microsoft.AzureTerraform).
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2023-07-01-preview-stackql-generated
  x-serviceAlias: terraform
  x-sdkPackage: azure-mgmt-terraform
  x-plane: mgmt
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    OperationDisplay:
      type: object
      description: Localized display information for and operation. Readonly variables are only populated by the server, and will be ignored when sending a request.
      properties:
        provider:
          type: string
          description: The localized friendly form of the resource provider name, e.g. "Microsoft Monitoring Insights" or "Microsoft Compute".
        resource:
          type: string
          description: The localized friendly name of the resource type related to this operation. E.g. "Virtual Machines" or "Job Schedule Collections".
        operation:
          type: string
          description: The concise, localized friendly name for the operation; suitable for dropdowns. E.g. "Create or Update Virtual Machine", "Restart Virtual Machine".
        description:
          type: string
          description: The short, localized friendly description of the operation; suitable for tool tips and detailed views.
    Origin:
      type: string
      enum:
        - user
        - system
        - user,system
    ActionType:
      type: string
      enum:
        - Internal
    Operation:
      type: object
      description: Details of a REST API operation, returned from the Resource Provider Operations API. Readonly variables are only populated by the server, and will be ignored when sending a request.
      properties:
        name:
          type: string
          description: 'The name of the operation, as per Resource-Based Access Control (RBAC). Examples: "Microsoft.Compute/virtualMachines/write", "Microsoft.Compute/virtualMachines/capture/action".'
        isDataAction:
          type: boolean
          description: Whether the operation applies to data-plane. This is "true" for data-plane operations and "false" for Azure Resource Manager/control-plane operations.
        display:
          $ref: "#/components/schemas/OperationDisplay"
          description: Localized display information for this particular operation.
        origin:
          $ref: "#/components/schemas/Origin"
          description: 'The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit logs UX. Default value is "user,system". Known values are: "user", "system", and "user,system".'
        actionType:
          $ref: "#/components/schemas/ActionType"
          description: Extensible enum. Indicates the action type. "Internal" refers to actions that are for internal only APIs. "Internal"
    PagedOperation:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/Operation"
        nextLink:
          type: string
    TargetProvider:
      type: string
      enum:
        - azurerm
        - azapi
    TerraformOperationStatus:
      type: object
      description: The status of the LRO operation. Readonly variables are only populated by the server, and will be ignored when sending a request.
      properties:
        properties:
          $ref: "#/components/schemas/ExportResult"
          description: RP-specific properties for the operationStatus resource, only appears when operation ended with Succeeded status.
        status:
          $ref: "#/components/schemas/ResourceProvisioningState"
          description: 'The operation status. Required. Known values are: "Succeeded", "Failed", and "Canceled".'
        name:
          type: string
          description: The name of the operationStatus resource.
        startTime:
          type: string
          format: date-time
          description: Operation start time.
        endTime:
          type: string
          format: date-time
          description: Operation complete time.
        percentComplete:
          type: number
          description: The progress made toward completing the operation.
        error:
          $ref: "#/components/schemas/ErrorDetail"
          description: Errors that occurred if the operation ended with Canceled or Failed status.
      required:
        - status
    ExportResult:
      type: object
      description: The Terraform export result.
      properties:
        configuration:
          type: string
          description: The Terraform configuration content.
        skippedResources:
          type: array
          items:
            type: string
          description: A list of Azure resources which are not exported to Terraform due to there is no corresponding resources in Terraform.
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ErrorDetail"
          description: A list of errors derived during exporting each resource.
    ErrorDetail:
      type: object
      description: The error detail. Readonly variables are only populated by the server, and will be ignored when sending a request.
      properties:
        code:
          type: string
          description: The error code.
        message:
          type: string
          description: The error message.
        target:
          type: string
          description: The error target.
        details:
          type: array
          items:
            $ref: "#/components/schemas/ErrorDetail"
          description: The error details.
        additionalInfo:
          type: array
          items:
            $ref: "#/components/schemas/ErrorAdditionalInfo"
          description: The error additional info.
    ErrorAdditionalInfo:
      type: object
      description: The resource management error additional info. Readonly variables are only populated by the server, and will be ignored when sending a request.
      properties:
        type:
          type: string
          description: The additional info type.
        info:
          type: object
          properties: {}
          description: The additional info.
    ResourceProvisioningState:
      type: string
      enum:
        - Succeeded
        - Failed
        - Canceled
  x-stackQL-resources:
    operations:
      id: azure_isv.terraform.operations
      name: operations
      title: operations
      methods:
        list:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.AzureTerraform~1operations?api-version=2023-07-01-preview/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.value
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/operations/methods/list"
        insert: []
        update: []
        delete: []
    terraform:
      id: azure_isv.terraform.terraform
      name: terraform
      title: terraform
      methods:
        export_terraform:
          operation:
            $ref: "#/paths/~1subscriptions~1{subscription_id}~1providers~1Microsoft.AzureTerraform~1exportTerraform?api-version=2023-07-01-preview/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: camel
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /providers/Microsoft.AzureTerraform/operations?api-version=2023-07-01-preview:
    get:
      operationId: terraform_list
      description: List the operations for the provider.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedOperation"
  /subscriptions/{subscription_id}/providers/Microsoft.AzureTerraform/exportTerraform?api-version=2023-07-01-preview:
    post:
      operationId: Terraform_begin_export_terraform
      description: Exports the Terraform configuration of the specified resource(s).
      parameters:
        - name: subscription_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  description: 'The parameter type. Required. Known values are: "ExportResource", "ExportResourceGroup", and "ExportQuery".'
                targetProvider:
                  $ref: "#/components/schemas/TargetProvider"
                  description: 'The target Azure Terraform Provider. Known values are: "azurerm" and "azapi".'
                fullProperties:
                  type: boolean
                  description: Whether to output all non-computed properties in the generated Terraform configuration? This probably needs manual modifications to make it valid.
                maskSensitive:
                  type: boolean
                  description: Mask sensitive attributes in the Terraform configuration.
              required:
                - type
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TerraformOperationStatus"
