openapi: 3.0.0
info:
  version: 2024-12-19-stackql-generated
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  title: Databricks Logging API
  description: Log Delivery
servers:
- url: https://accounts.cloud.databricks.com
paths:
  /api/2.0/accounts/{account_id}/log-delivery:
    post:
      operationId: log-delivery-create
      externalDocs:
        url: https://docs.databricks.com/api/account/logdelivery/create
      x-stackQL-resource: log_delivery
      x-stackQL-method: create
      x-stackQL-verb: insert
      x-numReqParams: 1
      parameters:
      - name: account_id
        required: true
        description: uuid
        in: path
      responses:
        '200':
          description: The log delivery configuration creation request succeeded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  log_delivery_configuration:
                    type: object
                    properties:
                      account_id:
                        type: string
                      config_id:
                        type: string
                      creation_time:
                        type: integer
                      update_time:
                        type: integer
                      log_delivery_status:
                        type: object
                        properties:
                          status:
                            type: string
                          message:
                            type: string
                          last_attempt_time:
                            type: string
                          last_successful_attempt_time:
                            type: string
                      config_name:
                        type: string
                      status:
                        type: string
                      log_type:
                        type: string
                      output_format:
                        type: string
                      credentials_id:
                        type: string
                      storage_configuration_id:
                        type: string
                      workspace_ids_filter:
                        type: array
                        items:
                          type: integer
                      delivery_path_prefix:
                        type: string
                      delivery_start_time:
                        type: string
        '400':
          description: Request is invalid or malformed.
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '404':
          description: Operation was performed on a resource that does not exist.
        '500':
          description: Internal error.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                log_delivery_configuration:
                  type: object
              example:
                log_delivery_configuration:
                  config_name: string
                  status: ENABLED
                  log_type: BILLABLE_USAGE
                  output_format: CSV
                  credentials_id: c7814269-df58-4ca3-85e9-f6672ef43d77
                  storage_configuration_id: 04aae505-1b1e-4cb9-997d-e1c49282675d
                  workspace_ids_filter:
                  - 0
                  delivery_path_prefix: string
                  delivery_start_time: string
        description: Properties of the new log delivery configuration.
      description: Creates a new Databricks log delivery configuration to enable delivery
        of the specified type of logs to your storage location. This requires that
        you already created a
    get:
      operationId: log-delivery-list
      externalDocs:
        url: https://docs.databricks.com/api/account/logdelivery/list
      x-stackQL-resource: log_delivery
      x-stackQL-method: list
      x-stackQL-verb: select
      x-numReqParams: 1
      parameters:
      - name: account_id
        required: true
        description: uuid
        in: path
      - name: status
        in: query
      - name: credentials_id
        in: query
      - name: storage_configuration_id
        in: query
      responses:
        '200':
          description: Log delivery configurations were returned successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  log_delivery_configurations:
                    type: array
                    items:
                      type: object
                      properties:
                        account_id:
                          type: string
                        config_id:
                          type: string
                        creation_time:
                          type: integer
                        update_time:
                          type: integer
                        log_delivery_status:
                          type: object
                          properties:
                            status:
                              type: string
                            message:
                              type: string
                            last_attempt_time:
                              type: string
                            last_successful_attempt_time:
                              type: string
                        config_name:
                          type: string
                        status:
                          type: string
                        log_type:
                          type: string
                        output_format:
                          type: string
                        credentials_id:
                          type: string
                        storage_configuration_id:
                          type: string
                        workspace_ids_filter:
                          type: array
                          items:
                            type: integer
                        delivery_path_prefix:
                          type: string
                        delivery_start_time:
                          type: string
        '400':
          description: Request is invalid or malformed.
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '404':
          description: Operation was performed on a resource that does not exist.
        '500':
          description: Internal error.
      x-stackQL-objectKey: $.log_delivery_configurations
      description: Gets all Databricks log delivery configurations associated with
        an account specified by ID.
  /api/2.0/accounts/{account_id}/log-delivery/{log_delivery_configuration_id}:
    get:
      operationId: log-delivery-get
      externalDocs:
        url: https://docs.databricks.com/api/account/logdelivery/get
      x-stackQL-resource: log_delivery
      x-stackQL-method: get
      x-stackQL-verb: select
      x-numReqParams: 2
      parameters:
      - name: account_id
        required: true
        description: uuid
        in: path
      - name: log_delivery_configuration_id
        required: true
        description: uuid
        in: path
      responses:
        '200':
          description: The log delivery configuration was successfully returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  log_delivery_configuration:
                    type: object
                    properties:
                      account_id:
                        type: string
                      config_id:
                        type: string
                      creation_time:
                        type: integer
                      update_time:
                        type: integer
                      log_delivery_status:
                        type: object
                        properties:
                          status:
                            type: string
                          message:
                            type: string
                          last_attempt_time:
                            type: string
                          last_successful_attempt_time:
                            type: string
                      config_name:
                        type: string
                      status:
                        type: string
                      log_type:
                        type: string
                      output_format:
                        type: string
                      credentials_id:
                        type: string
                      storage_configuration_id:
                        type: string
                      workspace_ids_filter:
                        type: array
                        items:
                          type: integer
                      delivery_path_prefix:
                        type: string
                      delivery_start_time:
                        type: string
        '400':
          description: Request is invalid or malformed.
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '404':
          description: Operation was performed on a resource that does not exist.
        '500':
          description: Internal error.
      x-stackQL-objectKey: $.log_delivery_configuration
      description: Gets a Databricks log delivery configuration object for an account,
        both specified by ID.
    patch:
      operationId: log-delivery-patchstatus
      externalDocs:
        url: https://docs.databricks.com/api/account/logdelivery/patchstatus
      x-stackQL-resource: log_delivery
      x-stackQL-method: patchstatus
      x-stackQL-verb: exec
      x-numReqParams: 2
      parameters:
      - name: account_id
        required: true
        description: uuid
        in: path
      - name: log_delivery_configuration_id
        required: true
        description: uuid
        in: path
      responses:
        '200':
          description: The log delivery configuration was successfully updated.
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '400':
          description: Request is invalid or malformed.
        '401':
          description: The request does not have valid authentication credentials
            for the operation.
        '404':
          description: Operation was performed on a resource that does not exist.
        '500':
          description: Internal error.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: required
              example:
                status: ENABLED
        description: The new status for this log delivery configuration object.
      description: Enables or disables a log delivery configuration. Deletion of delivery
        configurations is not supported, so disable log delivery configurations that
        are no longer needed. Note that you can't re-enable a delivery configuration
        if this would violate the delivery configuration limits described under
components:
  x-stackQL-resources:
    log_delivery:
      id: databricks_account.logging.log_delivery
      name: log_delivery
      title: Log_delivery
      methods:
        create:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1log-delivery/post'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
        list:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1log-delivery/get'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.log_delivery_configurations
        get:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1log-delivery~1{log_delivery_configuration_id}/get'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.log_delivery_configuration
        patchstatus:
          operation:
            $ref: '#/paths/~1api~12.0~1accounts~1{account_id}~1log-delivery~1{log_delivery_configuration_id}/patch'
          response:
            mediaType: application/json
            overrideMediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
        - $ref: '#/components/x-stackQL-resources/log_delivery/methods/get'
        - $ref: '#/components/x-stackQL-resources/log_delivery/methods/list'
        insert:
        - $ref: '#/components/x-stackQL-resources/log_delivery/methods/create'
        update: []
        replace: []
        delete: []
        exec:
        - $ref: '#/components/x-stackQL-resources/log_delivery/methods/patchstatus'
