openapi: 3.0.3
info:
  title: organization API
  description: Operations about organizations
  version: 1.0.0
paths:
  /organizations/{organizationId}:
    get:
      tags:
        - organization
      summary: Get organization details
      operationId: get_organization
      parameters:
        - name: organizationId
          in: path
          description: Organization ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '400':
          description: Invalid Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
  /organizations/{organizationId}/analytics:
    get:
      tags:
        - organization
      summary: Retrieve organization analytics
      description: >-
        This API returns analytics for the specified organization.

        The analytics are returned as time series data in 15 minute intervals,
        with

        the `time` field representing the start of the interval.
      operationId: get_organization_analytics
      parameters:
        - name: organizationId
          in: path
          description: Organization ID
          required: true
          schema:
            type: string
            format: uuid
        - name: since
          in: query
          description: |-

            Start of the time range in RFC3339 format.

            Defaults to 24 hours ago.

            Note that the maximum allowed time range is 24 hours.
                  
          required: true
          schema:
            type: string
            format: date-time
          example: '2021-08-01T00:00:00Z'
        - name: until
          in: query
          description: |-

            End of the time range in RFC3339 format.

            Defaults to the current time.

            Note that the maximum allowed time range is 24 hours.
                  
          required: true
          schema:
            type: string
            format: date-time
          example: '2021-08-02T00:00:00Z'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Analytics'
        '400':
          description: Invalid Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBody'
components:
  schemas:
    Organization:
      type: object
      required:
        - id
        - name
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      additionalProperties: false
      example:
        id: a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
        name: my-org
        createdAt: '2021-08-01T00:00:00Z'
        updatedAt: '2021-08-01T00:00:00Z'
    ErrorBody:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: The error code
        message:
          type: string
          description: The error message
    Analytics:
      type: object
      description: Project analytics data
      required:
        - fields
        - values
      properties:
        fields:
          type: array
          items:
            $ref: '#/components/schemas/AnalyticsFieldSchema'
        values:
          type: array
          items:
            type: array
            items:
              $ref: '#/components/schemas/AnalyticsDataValue'
      additionalProperties: false
      example:
        fields:
          - name: time
            type: time
          - name: requestCount
            type: number
          - name: cpuSeconds
            type: number
          - name: uptimeSeconds
            type: number
          - name: maxRssMemoryBytes
            type: number
          - name: networkIngressBytes
            type: number
          - name: networkEgressBytes
            type: number
          - name: kvReadCount
            type: number
          - name: kvWriteCount
            type: number
          - name: kvReadUnits
            type: number
          - name: kvWriteUnits
            type: number
          - name: kvStorageBytes
            type: number
        values:
          - - '2023-08-01T00:00:00Z'
            - 111
            - 111
            - 111
            - 111
            - 111
            - 111
            - 111
            - 111
            - 111
            - 111
            - 111
          - - '2023-08-01T00:15:00Z'
            - 222
            - 222
            - 222
            - 222
            - 222
            - 222
            - 222
            - 222
            - 222
            - 222
            - 222
          - - '2023-08-01T00:30:00Z'
            - 333
            - 333
            - 333
            - 333
            - 333
            - 333
            - 333
            - 333
            - 333
            - 333
            - 333
          - - '2023-08-01T00:45:00Z'
            - 444
            - 444
            - 444
            - 444
            - 444
            - 444
            - 444
            - 444
            - 444
            - 444
            - 444
          - - '2023-08-01T01:00:00Z'
            - 555
            - 555
            - 555
            - 555
            - 555
            - 555
            - 555
            - 555
            - 555
            - 555
            - 555
    AnalyticsFieldSchema:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
        type:
          $ref: '#/components/schemas/AnalyticsFieldType'
      additionalProperties: false
    AnalyticsDataValue:
      oneOf:
        - type: string
          format: date-time
        - type: number
          format: double
        - type: string
        - type: boolean
        - {}
    AnalyticsFieldType:
      type: string
      description: >-
        A data type that analytic data can be represented in.


        Inspired by Grafana's data types defined at:

        https://github.com/grafana/grafana/blob/e3288834b37b9aac10c1f43f0e621b35874c1f8a/packages/grafana-data/src/types/dataFrame.ts#L11-L23
      enum:
        - time
        - number
        - string
        - boolean
        - other
  x-stackQL-resources:
    organizations:
      id: deno.organization.organizations
      name: organizations
      title: Organizations
      methods:
        get_organization:
          operation:
            $ref: '#/paths/~1organizations~1{organizationId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/organizations/methods/get_organization
        insert: []
        update: []
        delete: []
        replace: []
    analytics:
      id: deno.organization.analytics
      name: analytics
      title: Analytics
      methods:
        get_organization_analytics:
          operation:
            $ref: '#/paths/~1organizations~1{organizationId}~1analytics/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/analytics/methods/get_organization_analytics
        insert: []
        update: []
        delete: []
        replace: []
servers:
  - url: https://api.deno.com/v1
