id: googleworkspace
name: googleworkspace
version: v00.00.00000
providerServices:
  admin:
    description: Admin SDK lets administrators of enterprise domains to view and manage resources like user, groups etc. It also provides audit and usage reports of domain.
    id: admin:v00.00.00000
    name: admin
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/admin.yaml
    title: Admin SDK API
    version: v00.00.00000
  alertcenter:
    description: 'Manages alerts on issues affecting your domain. Note: The current version of this API (v1beta1) is available to all Google Workspace customers. '
    id: alertcenter:v00.00.00000
    name: alertcenter
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/alertcenter.yaml
    title: Google Workspace Alert Center API
    version: v00.00.00000
  calendar:
    description: Manipulates events and other calendar data.
    id: calendar:v00.00.00000
    name: calendar
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/calendar.yaml
    title: Calendar API
    version: v00.00.00000
  chat:
    description: Enables apps to fetch information and perform actions in Google Chat. Authentication is a prerequisite for using the Google Chat REST API.
    id: chat:v00.00.00000
    name: chat
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/chat.yaml
    title: Google Chat API
    version: v00.00.00000
  chromemanagement:
    description: The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.
    id: chromemanagement:v00.00.00000
    name: chromemanagement
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/chromemanagement.yaml
    title: Chrome Management API
    version: v00.00.00000
  chromepolicy:
    description: The Chrome Policy API is a suite of services that allows Chrome administrators to control the policies applied to their managed Chrome OS devices and Chrome browsers.
    id: chromepolicy:v00.00.00000
    name: chromepolicy
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/chromepolicy.yaml
    title: Chrome Policy API
    version: v00.00.00000
  chromeuxreport:
    description: 'The Chrome UX Report API lets you view real user experience data for millions of websites. '
    id: chromeuxreport:v00.00.00000
    name: chromeuxreport
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/chromeuxreport.yaml
    title: Chrome UX Report API
    version: v00.00.00000
  classroom:
    description: Manages classes, rosters, and invitations in Google Classroom.
    id: classroom:v00.00.00000
    name: classroom
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/classroom.yaml
    title: Google Classroom API
    version: v00.00.00000
  docs:
    description: Reads and writes Google Docs documents.
    id: docs:v00.00.00000
    name: docs
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/docs.yaml
    title: Google Docs API
    version: v00.00.00000
  drive:
    description: Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.
    id: drive:v00.00.00000
    name: drive
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/drive.yaml
    title: Drive API
    version: v00.00.00000
  driveactivity:
    description: Provides a historical view of activity in Google Drive.
    id: driveactivity:v00.00.00000
    name: driveactivity
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/driveactivity.yaml
    title: Drive Activity API
    version: v00.00.00000
  drivelabels:
    description: An API for managing Drive Labels
    id: drivelabels:v00.00.00000
    name: drivelabels
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/drivelabels.yaml
    title: Drive Labels API
    version: v00.00.00000
  forms:
    description: Reads and writes Google Forms and responses.
    id: forms:v00.00.00000
    name: forms
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/forms.yaml
    title: Google Forms API
    version: v00.00.00000
  gmail:
    description: The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels.
    id: gmail:v00.00.00000
    name: gmail
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/gmail.yaml
    title: Gmail API
    version: v00.00.00000
  gmailpostmastertools:
    description: The Postmaster Tools API is a RESTful API that provides programmatic access to email traffic metrics (like spam reports, delivery errors etc) otherwise available through the Gmail Postmaster Tools UI currently.
    id: gmailpostmastertools:v00.00.00000
    name: gmailpostmastertools
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/gmailpostmastertools.yaml
    title: Gmail Postmaster Tools API
    version: v00.00.00000
  # groupsmigration:
  #   description: The Groups Migration API allows domain administrators to archive emails into Google groups.
  #   id: groupsmigration:v00.00.00000
  #   name: groupsmigration
  #   preferred: true
  #   service:
  #     $ref: googleworkspace/v00.00.00000/services/groupsmigration.yaml
  #   title: Groups Migration API
  #   version: v00.00.00000
  groupssettings:
    description: Manages permission levels and related settings of a group.
    id: groupssettings:v00.00.00000
    name: groupssettings
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/groupssettings.yaml
    title: Groups Settings API
    version: v00.00.00000
  keep:
    description: The Google Keep API is used in an enterprise environment to manage Google Keep content and resolve issues identified by cloud security software.
    id: keep:v00.00.00000
    name: keep
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/keep.yaml
    title: Google Keep API
    version: v00.00.00000
  licensing:
    description: The Google Enterprise License Manager API lets you manage Google Workspace and related licenses for all users of a customer that you manage.
    id: licensing:v00.00.00000
    name: licensing
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/licensing.yaml
    title: Enterprise License Manager API
    version: v00.00.00000
  reseller:
    description: Perform common functions that are available on the Channel Services console at scale, like placing orders and viewing customer information
    id: reseller:v00.00.00000
    name: reseller
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/reseller.yaml
    title: Google Workspace Reseller API
    version: v00.00.00000
  script:
    description: 'Manages and executes Google Apps Script projects. '
    id: script:v00.00.00000
    name: script
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/script.yaml
    title: Apps Script API
    version: v00.00.00000
  sheets:
    description: Reads and writes Google Sheets.
    id: sheets:v00.00.00000
    name: sheets
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/sheets.yaml
    title: Google Sheets API
    version: v00.00.00000
  siteVerification:
    description: Verifies ownership of websites or domains with Google.
    id: siteVerification:v00.00.00000
    name: siteVerification
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/siteVerification.yaml
    title: Google Site Verification API
    version: v00.00.00000
  slides:
    description: Reads and writes Google Slides presentations.
    id: slides:v00.00.00000
    name: slides
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/slides.yaml
    title: Google Slides API
    version: v00.00.00000
  tasks:
    description: The Google Tasks API lets you manage your tasks and task lists.
    id: tasks:v00.00.00000
    name: tasks
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/tasks.yaml
    title: Tasks API
    version: v00.00.00000
  vault:
    description: 'Retention and eDiscovery for Google Workspace. To work with Vault resources, the account must have the [required Vault privileges](https://support.google.com/vault/answer/2799699) and access to the matter. To access a matter, the account must have created the matter, have the matter shared with them, or have the **View All Matters** privilege. For example, to download an export, an account needs the **Manage Exports** privilege and the matter shared with them. '
    id: vault:v00.00.00000
    name: vault
    preferred: true
    service:
      $ref: googleworkspace/v00.00.00000/services/vault.yaml
    title: Google Vault API
    version: v00.00.00000
openapi: 3.1.0
