paths:
  /:
    get:
      summary: GitHub API Root
      description: Get Hypermedia links to resources accessible in GitHub's REST API
      tags:
        - meta
      operationId: meta/root
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_user_url:
                    type: string
                    format: uri-template
                  current_user_authorizations_html_url:
                    type: string
                    format: uri-template
                  authorizations_url:
                    type: string
                    format: uri-template
                  code_search_url:
                    type: string
                    format: uri-template
                  commit_search_url:
                    type: string
                    format: uri-template
                  emails_url:
                    type: string
                    format: uri-template
                  emojis_url:
                    type: string
                    format: uri-template
                  events_url:
                    type: string
                    format: uri-template
                  feeds_url:
                    type: string
                    format: uri-template
                  followers_url:
                    type: string
                    format: uri-template
                  following_url:
                    type: string
                    format: uri-template
                  gists_url:
                    type: string
                    format: uri-template
                  hub_url:
                    type: string
                    format: uri-template
                  issue_search_url:
                    type: string
                    format: uri-template
                  issues_url:
                    type: string
                    format: uri-template
                  keys_url:
                    type: string
                    format: uri-template
                  label_search_url:
                    type: string
                    format: uri-template
                  notifications_url:
                    type: string
                    format: uri-template
                  organization_url:
                    type: string
                    format: uri-template
                  organization_repositories_url:
                    type: string
                    format: uri-template
                  organization_teams_url:
                    type: string
                    format: uri-template
                  public_gists_url:
                    type: string
                    format: uri-template
                  rate_limit_url:
                    type: string
                    format: uri-template
                  repository_url:
                    type: string
                    format: uri-template
                  repository_search_url:
                    type: string
                    format: uri-template
                  current_user_repositories_url:
                    type: string
                    format: uri-template
                  starred_url:
                    type: string
                    format: uri-template
                  starred_gists_url:
                    type: string
                    format: uri-template
                  topic_search_url:
                    type: string
                    format: uri-template
                  user_url:
                    type: string
                    format: uri-template
                  user_organizations_url:
                    type: string
                    format: uri-template
                  user_repositories_url:
                    type: string
                    format: uri-template
                  user_search_url:
                    type: string
                    format: uri-template
                required:
                  - current_user_url
                  - current_user_authorizations_html_url
                  - authorizations_url
                  - code_search_url
                  - commit_search_url
                  - emails_url
                  - emojis_url
                  - events_url
                  - feeds_url
                  - followers_url
                  - following_url
                  - gists_url
                  - hub_url
                  - issue_search_url
                  - issues_url
                  - keys_url
                  - label_search_url
                  - notifications_url
                  - organization_url
                  - organization_repositories_url
                  - organization_teams_url
                  - public_gists_url
                  - rate_limit_url
                  - repository_url
                  - repository_search_url
                  - current_user_repositories_url
                  - starred_url
                  - starred_gists_url
                  - user_url
                  - user_organizations_url
                  - user_repositories_url
                  - user_search_url
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/overview/resources-in-the-rest-api#root-endpoint
  /meta:
    get:
      summary: Get GitHub meta information
      description: |-
        Returns meta information about GitHub, including a list of GitHub's IP addresses. For more information, see "[About GitHub's IP addresses](https://docs.github.com/articles/about-github-s-ip-addresses/)."

        **Note:** The IP addresses shown in the documentation's response are only example values. You must always query the API directly to get the latest list of IP addresses.
      tags:
        - meta
      operationId: meta/get
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/reference/meta#get-github-meta-information
      parameters: []
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-overview'
              examples:
                default:
                  $ref: '#/components/examples/api-overview'
        '304':
          $ref: '#/components/responses/not_modified'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
        subcategory: null
  /octocat:
    get:
      summary: Get Octocat
      description: Get the octocat as ASCII art
      tags:
        - meta
      operationId: meta/get-octocat
      parameters:
        - name: s
          in: query
          description: The words to show in Octocat's speech bubble
          schema:
            type: string
          required: false
      responses:
        '200':
          description: Response
          content:
            application/octocat-stream:
              schema:
                type: string
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/reference/meta#get-octocat
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
  /zen:
    get:
      summary: Get the Zen of GitHub
      description: Get a random sentence from the Zen of GitHub
      tags:
        - meta
      operationId: meta/get-zen
      responses:
        '200':
          description: Response
          content:
            text/plain:
              schema:
                type: string
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
components:
  schemas:
    api-overview:
      title: Api Overview
      description: Api Overview
      type: object
      properties:
        verifiable_password_authentication:
          type: boolean
          example: true
        ssh_key_fingerprints:
          type: object
          properties:
            SHA256_RSA:
              type: string
            SHA256_DSA:
              type: string
            SHA256_ECDSA:
              type: string
            SHA256_ED25519:
              type: string
        ssh_keys:
          type: array
          items:
            type: string
          example:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
        hooks:
          type: array
          items:
            type: string
          example:
            - 127.0.0.1/32
        web:
          type: array
          items:
            type: string
          example:
            - 127.0.0.1/32
        api:
          type: array
          items:
            type: string
          example:
            - 127.0.0.1/32
        git:
          type: array
          items:
            type: string
          example:
            - 127.0.0.1/32
        packages:
          type: array
          items:
            type: string
          example:
            - 13.65.0.0/16
            - 157.55.204.33/32
            - 2a01:111:f403:f90c::/62
        pages:
          type: array
          items:
            type: string
          example:
            - 192.30.252.153/32
            - 192.30.252.154/32
        importer:
          type: array
          items:
            type: string
          example:
            - 54.158.161.132
            - 54.226.70.38
        actions:
          type: array
          items:
            type: string
          example:
            - 13.64.0.0/16
            - 13.65.0.0/16
        dependabot:
          type: array
          items:
            type: string
          example:
            - 192.168.7.15/32
            - 192.168.7.16/32
      required:
        - verifiable_password_authentication
  parameters: {}
  responses:
    not_modified:
      description: Not modified
  securitySchemes: {}
  callbacks: {}
  examples:
    api-overview:
      value:
        verifiable_password_authentication: true
        ssh_key_fingerprints:
          SHA256_RSA: nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
          SHA256_DSA: br9IjFspm1vxR3iA35FWE+4VTyz1hYVLIE2t1/CeyWQ
          SHA256_ECDSA: p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM
          SHA256_ED25519: +DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU
        ssh_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
        hooks:
          - 192.30.252.0/22
        web:
          - 192.30.252.0/22
          - 185.199.108.0/22
        api:
          - 192.30.252.0/22
          - 185.199.108.0/22
        git:
          - 192.30.252.0/22
        packages:
          - 192.30.252.0/22
        pages:
          - 192.30.252.153/32
          - 192.30.252.154/32
        importer:
          - 54.158.161.132
          - 54.226.70.38
        actions:
          - 13.64.0.0/16
          - 13.65.0.0/16
        dependabot:
          - 54.158.161.132
  requestBodies: {}
  headers: {}
  links: {}
  x-stackQL-resources:
    meta:
      id: github.meta.meta
      name: meta
      title: Meta
      methods:
        root:
          operation:
            $ref: '#/paths/~1/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get:
          operation:
            $ref: '#/paths/~1meta/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get_octocat:
          operation:
            $ref: '#/paths/~1octocat/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get_zen:
          operation:
            $ref: '#/paths/~1zen/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/meta/methods/get'
        insert: []
        update: []
        delete: []
openapi: 3.0.3
servers:
  - url: https://api.github.com
tags:
  - name: actions
    description: Endpoints to manage GitHub Actions using the REST API.
  - name: activity
    description: Activity APIs provide access to notifications, subscriptions, and timelines.
  - name: apps
    description: Information for integrations and installations.
  - name: billing
    description: Monitor charges and usage from Actions and Packages.
  - name: checks
    description: Rich interactions with checks run by your integrations.
  - name: code-scanning
    description: Retrieve code scanning alerts from a repository.
  - name: codes-of-conduct
    description: Insight into codes of conduct for your communities.
  - name: codespaces
    description: Endpoints to manage Codespaces using the REST API.
  - name: emojis
    description: List emojis available to use on GitHub.
  - name: enterprise-admin
    description: Administer a GitHub enterprise.
  - name: dependabot
    description: Endpoints to manage Dependabot.
  - name: gists
    description: View, modify your gists.
  - name: git
    description: Raw Git functionality.
  - name: gitignore
    description: View gitignore templates
  - name: interactions
    description: Owner or admin management of users interactions.
  - name: issues
    description: Interact with GitHub Issues.
  - name: licenses
    description: View various OSS licenses.
  - name: markdown
    description: Render GitHub flavored markdown
  - name: meta
    description: Endpoints that give information about the API.
  - name: migrations
    description: Move projects to or from GitHub.
  - name: oauth-authorizations
    description: Manage access of OAuth applications
  - name: orgs
    description: Interact with GitHub Orgs.
  - name: packages
    description: Manage packages for authenticated users and organizations.
  - name: projects
    description: Interact with GitHub Projects.
  - name: pulls
    description: Interact with GitHub Pull Requests.
  - name: rate-limit
    description: Check your current rate limit status
  - name: reactions
    description: Interact with reactions to various GitHub entities.
  - name: repos
    description: Interact with GitHub Repos.
  - name: scim
    description: Provisioning of GitHub organization membership for SCIM-enabled providers.
  - name: search
    description: Look for stuff on GitHub.
  - name: secret-scanning
    description: Retrieve secret scanning alerts from a repository.
  - name: server-statistics
    description: GHES statistics
  - name: teams
    description: Interact with GitHub Teams.
  - name: users
    description: Interact with and view information about users and also current user.
externalDocs:
  description: GitHub v3 REST API
  url: https://docs.github.com/rest/
info:
  version: 1.1.4
  title: GitHub v3 REST API - meta
  description: Endpoints that give information about the API.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
