openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Abusive Experience Report API
  description: Views Abusive Experience Report data, and gets a list of sites that have a significant number of abusive experiences.
  version: v1
  x-discovery-doc-revision: '20230114'
  x-generated-date: '2023-01-19'
externalDocs:
  url: https://developers.google.com/abusive-experience-report/
servers:
  - url: https://abusiveexperiencereport.googleapis.com
components:
  schemas:
    SiteSummaryResponse:
      type: object
      description: Response message for GetSiteSummary.
      id: SiteSummaryResponse
      properties:
        abusiveStatus:
          enumDescriptions:
            - Not reviewed.
            - Passing.
            - Failing.
          type: string
          description: The site's Abusive Experience Report status.
          enum:
            - UNKNOWN
            - PASSING
            - FAILING
        lastChangeTime:
          description: The time at which the site's status last changed.
          type: string
          format: google-datetime
        filterStatus:
          enumDescriptions:
            - N/A.
            - Enforcement is on.
            - Enforcement is off.
            - Enforcement is paused.
            - Enforcement is pending.
          enum:
            - UNKNOWN
            - 'ON'
            - 'OFF'
            - PAUSED
            - PENDING
          description: The site's [enforcement status](https://support.google.com/webtools/answer/7538608).
          type: string
        reportUrl:
          type: string
          description: A link to the full Abusive Experience Report for the site. Not set in ViolatingSitesResponse. Note that you must complete the [Search Console verification process](https://support.google.com/webmasters/answer/9008080) for the site before you can access the full report.
        underReview:
          type: boolean
          description: Whether the site is currently under review.
        reviewedSite:
          description: The name of the reviewed site, e.g. `google.com`.
          type: string
        enforcementTime:
          description: The time at which [enforcement](https://support.google.com/webtools/answer/7538608) against the site began or will begin. Not set when the filter_status is OFF.
          type: string
          format: google-datetime
    ViolatingSitesResponse:
      type: object
      description: Response message for ListViolatingSites.
      properties:
        violatingSites:
          items:
            $ref: '#/components/schemas/SiteSummaryResponse'
          description: The list of violating sites.
          type: array
      id: ViolatingSitesResponse
  parameters:
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    quotaUser:
      description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    upload_protocol:
      description: Upload protocol for media (e.g. "raw", "multipart").
      in: query
      name: upload_protocol
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
    key:
      description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      in: query
      name: key
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    uploadType:
      description: Legacy upload protocol for media (e.g. "media", "multipart").
      in: query
      name: uploadType
      schema:
        type: string
  x-stackQL-resources:
    violating_sites:
      id: googledevelopers.abusiveexperiencereport.violating_sites
      name: violating_sites
      title: Violating_sites
      methods:
        violatingSites_list:
          operation:
            $ref: '#/paths/~1v1~1violatingSites/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/violating_sites/methods/violatingSites_list'
        insert: []
        update: []
        delete: []
    sites:
      id: googledevelopers.abusiveexperiencereport.sites
      name: sites
      title: Sites
      methods:
        get:
          operation:
            $ref: '#/paths/~1v1~1sites~1{sitesId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/sites/methods/get'
        insert: []
        update: []
        delete: []
paths:
  /v1/violatingSites:
    parameters: &ref_0
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/uploadType'
    get:
      description: Lists sites that are failing in the Abusive Experience Report.
      operationId: abusiveexperiencereport.violatingSites.list
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ViolatingSitesResponse'
      parameters: []
      x-stackQL-resource: violating_sites
      x-stackQL-verb: select
  /v1/sites/{sitesId}:
    parameters: *ref_0
    get:
      description: Gets a site's Abusive Experience Report summary.
      operationId: abusiveexperiencereport.sites.get
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SiteSummaryResponse'
      parameters:
        - in: path
          name: sitesId
          required: true
          schema:
            type: string
      x-stackQL-resource: sites
      x-stackQL-verb: select
