openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Knowledge Graph Search API
  description: Searches the Google Knowledge Graph for entities.
  version: v1
  x-discovery-doc-revision: '20221210'
  x-generated-date: '2023-01-06'
externalDocs:
  url: https://developers.google.com/knowledge-graph/
servers:
  - url: https://kgsearch.googleapis.com
components:
  schemas:
    SearchResponse:
      id: SearchResponse
      description: Response message includes the context and a list of matching results which contain the detail of associated entities.
      type: object
      properties:
        '@type':
          description: The schema type of top-level JSON-LD object, e.g. ItemList.
          type: any
        itemListElement:
          description: The item list of search results.
          type: array
          items:
            type: any
        '@context':
          description: The local context applicable for the response. See more details at http://www.w3.org/TR/json-ld/#context-definitions.
          type: any
  parameters:
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    quotaUser:
      description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
    uploadType:
      description: Legacy upload protocol for media (e.g. "media", "multipart").
      in: query
      name: uploadType
      schema:
        type: string
    key:
      description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      in: query
      name: key
      schema:
        type: string
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    upload_protocol:
      description: Upload protocol for media (e.g. "raw", "multipart").
      in: query
      name: upload_protocol
      schema:
        type: string
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/keep: See, edit, create and permanently delete all your Google Keep data
            https://www.googleapis.com/auth/keep.readonly: View all your Google Keep data
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
  x-stackQL-resources:
    entities:
      id: googledevelopers.kgsearch.entities
      name: entities
      title: Entities
      methods:
        search:
          operation:
            $ref: '#/paths/~1v1~1entities:search/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /v1/entities:search:
    parameters:
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/callback'
    get:
      description: Searches Knowledge Graph for entities that match the constraints. A list of matched entities will be returned in response, which will be in JSON-LD format and compatible with http://schema.org
      operationId: kgsearch.entities.search
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
      parameters:
        - in: query
          name: query
          schema:
            type: string
        - in: query
          name: languages
          schema:
            type: string
        - in: query
          name: indent
          schema:
            type: boolean
        - in: query
          name: prefix
          schema:
            type: boolean
        - in: query
          name: limit
          schema:
            type: integer
        - in: query
          name: ids
          schema:
            type: string
        - in: query
          name: types
          schema:
            type: string
      x-stackQL-resource: entities
      x-stackQL-verb: exec
