openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Google Play Custom App Publishing API
  description: API to create and publish custom Android apps
  version: v1
  x-discovery-doc-revision: '20230104'
  x-generated-date: '2023-01-06'
externalDocs:
  url: https://developers.google.com/android/work/play/custom-app-api/
servers:
  - url: https://playcustomapp.googleapis.com
components:
  schemas:
    Organization:
      description: Represents an organization that can access a custom app.
      type: object
      id: Organization
      properties:
        organizationName:
          type: string
          description: Optional. A human-readable name of the organization, to help recognize the organization.
        organizationId:
          description: Required. ID of the organization.
          type: string
    CustomApp:
      type: object
      properties:
        languageCode:
          type: string
          description: Default listing language in BCP 47 format.
        packageName:
          description: Output only. Package name of the created Android app. Only present in the API response.
          readOnly: true
          type: string
        organizations:
          items:
            $ref: '#/components/schemas/Organization'
          type: array
          description: Organizations to which the custom app should be made available. If the request contains any organizations, then the app will be restricted to only these organizations. To support the organization linked to the developer account, the organization ID should be provided explicitly together with other organizations. If no organizations are provided, then the app is only available to the organization linked to the developer account.
        title:
          description: Title for the Android app.
          type: string
      id: CustomApp
      description: This resource represents a custom app.
  parameters:
    upload_protocol:
      description: Upload protocol for media (e.g. "raw", "multipart").
      in: query
      name: upload_protocol
      schema:
        type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    uploadType:
      description: Legacy upload protocol for media (e.g. "media", "multipart").
      in: query
      name: uploadType
      schema:
        type: string
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    key:
      description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      in: query
      name: key
      schema:
        type: string
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    quotaUser:
      description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/androidpublisher: View and manage your Google Play Developer account
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
  x-stackQL-resources:
    custom_apps:
      id: googledevelopers.playcustomapp.custom_apps
      name: custom_apps
      title: Custom_apps
      methods:
        accounts_customApps_create:
          operation:
            $ref: '#/paths/~1playcustomapp~1v1~1accounts~1{account}~1customApps/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert:
          - $ref: '#/components/x-stackQL-resources/custom_apps/methods/accounts_customApps_create'
        update: []
        delete: []
paths:
  /playcustomapp/v1/accounts/{account}/customApps:
    parameters:
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/callback'
    post:
      description: Creates a new custom app.
      operationId: playcustomapp.accounts.customApps.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomApp'
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/androidpublisher
          Oauth2c:
            - https://www.googleapis.com/auth/androidpublisher
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomApp'
      parameters:
        - in: path
          name: account
          required: true
          schema:
            type: string
      x-stackQL-resource: custom_apps
      x-stackQL-verb: insert
