openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Google Play Integrity API
  description: The Play Integrity API helps you check that you're interacting with your genuine app on a genuine Android device powered by Google Play services. The Play Integrity API has replaced SafetyNet Attestation and Android Device Verification.
  version: v1
  x-discovery-doc-revision: '20230104'
  x-generated-date: '2023-01-06'
externalDocs:
  url: https://developer.android.com/google/play/integrity
servers:
  - url: https://playintegrity.googleapis.com
components:
  schemas:
    TokenPayloadExternal:
      id: TokenPayloadExternal
      description: Contains basic app information and integrity signals like device attestation and licensing details.
      properties:
        accountDetails:
          $ref: '#/components/schemas/AccountDetails'
          description: Required. Details about the Play Store account.
        deviceIntegrity:
          $ref: '#/components/schemas/DeviceIntegrity'
          description: Required. Details about the device integrity.
        requestDetails:
          description: Required. Details about the integrity request.
          $ref: '#/components/schemas/RequestDetails'
        testingDetails:
          description: Indicates that this payload is generated for testing purposes and contains any additional data that is linked with testing status.
          $ref: '#/components/schemas/TestingDetails'
        appIntegrity:
          description: Required. Details about the application integrity.
          $ref: '#/components/schemas/AppIntegrity'
      type: object
    DecodeIntegrityTokenResponse:
      description: Response containing the decoded integrity payload.
      properties:
        tokenPayloadExternal:
          description: Plain token payload generated from the decoded integrity token.
          $ref: '#/components/schemas/TokenPayloadExternal'
      id: DecodeIntegrityTokenResponse
      type: object
    AccountDetails:
      id: AccountDetails
      description: Contains the account information such as the licensing status for the user in the scope.
      properties:
        appLicensingVerdict:
          enum:
            - UNKNOWN
            - LICENSED
            - UNLICENSED
            - UNEVALUATED
          enumDescriptions:
            - Play does not have sufficient information to evaluate licensing details
            - The app and certificate match the versions distributed by Play.
            - The certificate or package name does not match Google Play records.
            - Licensing details were not evaluated since a necessary requirement was missed. For example DeviceIntegrity did not meet the minimum bar or the application was not a known Play version.
          type: string
          description: Required. Details about the licensing status of the user for the app in the scope.
        accountActivity:
          $ref: '#/components/schemas/AccountActivity'
          description: Details about the account activity for the user in the scope.
      type: object
    AccountActivity:
      description: Contains a signal helping apps differentiating between likely genuine users and likely non-genuine traffic (such as accounts being used for fraud, accounts used by automated traffic, or accounts used in device farms) based on the presence and volume of Play store activity.
      id: AccountActivity
      type: object
      properties:
        activityLevel:
          enumDescriptions:
            - Activity level has not been set.
            - Account activity level is not evaluated because one of the prerequisite conditions is not met (e.g., device is not trusted, the user does not have Play app license)
            - Google Play store activity is unusual for at least one of the user accounts on the device. Google Play recommends checking that this is a real user.
            - Google Play does not have sufficient activity for the user account on the device. The account may be new, or it may lack activity on Google Play.
            - Google Play store activity is typical for the user account or accounts on the device.
            - Google Play store activity is typical for the user account or accounts on the device, with harder to replicate signals.
          type: string
          enum:
            - ACTIVITY_LEVEL_UNSPECIFIED
            - UNEVALUATED
            - UNUSUAL
            - UNKNOWN
            - TYPICAL_BASIC
            - TYPICAL_STRONG
          description: Required. Indicates the activity level of the account.
    TestingDetails:
      type: object
      description: Contains additional information generated for testing responses.
      properties:
        isTestingResponse:
          type: boolean
          description: Required. Indicates that the information contained in this payload is a testing response that is statically overridden for a tester.
      id: TestingDetails
    AppIntegrity:
      type: object
      id: AppIntegrity
      properties:
        certificateSha256Digest:
          type: array
          description: The SHA256 hash of the requesting app's signing certificates (base64 web-safe encoded). Set iff app_recognition_verdict != UNEVALUATED.
          items:
            type: string
        versionCode:
          type: string
          description: Version code of the application. Set iff app_recognition_verdict != UNEVALUATED.
          format: int64
        packageName:
          description: Package name of the application under attestation. Set iff app_recognition_verdict != UNEVALUATED.
          type: string
        appRecognitionVerdict:
          description: Required. Details about the app recognition verdict
          enumDescriptions:
            - Play does not have sufficient information to evaluate app integrity
            - The app and certificate match the versions distributed by Play.
            - The certificate or package name does not match Google Play records.
            - Application integrity was not evaluated since a necessary requirement was missed. For example DeviceIntegrity did not meet the minimum bar.
          enum:
            - UNKNOWN
            - PLAY_RECOGNIZED
            - UNRECOGNIZED_VERSION
            - UNEVALUATED
          type: string
      description: Contains the application integrity information.
    DeviceIntegrity:
      id: DeviceIntegrity
      properties:
        deviceRecognitionVerdict:
          description: Details about the integrity of the device the app is running on
          type: array
          items:
            enumDescriptions:
              - Play does not have sufficient information to evaluate device integrity
              - App is running on a device that passes basic system integrity checks, but may not meet Android platform compatibility requirements and may not be approved to run Google Play services.
              - App is running on GMS Android device with Google Play services.
              - App is running on GMS Android device with Google Play services and has a strong guarantee of system integrity such as a hardware-backed keystore.
              - App is running on an Android emulator with Google Play services which meets core Android compatibility requirements.
            type: string
            enum:
              - UNKNOWN
              - MEETS_BASIC_INTEGRITY
              - MEETS_DEVICE_INTEGRITY
              - MEETS_STRONG_INTEGRITY
              - MEETS_VIRTUAL_INTEGRITY
      type: object
      description: Contains the device attestation information.
    DecodeIntegrityTokenRequest:
      description: Request to decode the integrity token.
      type: object
      id: DecodeIntegrityTokenRequest
      properties:
        integrityToken:
          description: Encoded integrity token.
          type: string
    RequestDetails:
      type: object
      description: Contains the integrity request information.
      properties:
        nonce:
          description: Required. Nonce that was provided in the request (which is base64 web-safe no-wrap).
          type: string
        timestampMillis:
          description: Required. Timestamp, in milliseconds, of the integrity application request.
          type: string
          format: int64
        requestPackageName:
          description: 'Required. Application package name this attestation was requested for. Note: This field makes no guarantees or promises on the caller integrity. For details on application integrity, check application_integrity.'
          type: string
      id: RequestDetails
  parameters:
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    uploadType:
      description: Legacy upload protocol for media (e.g. "media", "multipart").
      in: query
      name: uploadType
      schema:
        type: string
    key:
      description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      in: query
      name: key
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
    upload_protocol:
      description: Upload protocol for media (e.g. "raw", "multipart").
      in: query
      name: upload_protocol
      schema:
        type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    quotaUser:
      description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/playintegrity: 'Private Service: https://www.googleapis.com/auth/playintegrity'
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
  x-stackQL-resources:
    playintegrity:
      id: googledevelopers.playintegrity.playintegrity
      name: playintegrity
      title: Playintegrity
      methods:
        decodeIntegrityToken:
          operation:
            $ref: '#/paths/~1v1~1{v1Id}:decodeIntegrityToken/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /v1/{v1Id}:decodeIntegrityToken:
    parameters:
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/quotaUser'
    post:
      description: Decodes the integrity token and returns the token payload.
      operationId: playintegrity.decodeIntegrityToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DecodeIntegrityTokenRequest'
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/playintegrity
          Oauth2c:
            - https://www.googleapis.com/auth/playintegrity
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DecodeIntegrityTokenResponse'
      parameters:
        - in: path
          name: v1Id
          required: true
          schema:
            type: string
      x-stackQL-resource: playintegrity
      x-stackQL-verb: exec
