openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Smart Device Management API
  description: Allow select enterprise partners to access, control, and manage Google and Nest devices programmatically.
  version: v1
  x-discovery-doc-revision: '20230112'
  x-generated-date: '2023-01-19'
externalDocs:
  url: https://developers.google.com/nest/device-access
servers:
  - url: https://smartdevicemanagement.googleapis.com
components:
  schemas:
    GoogleHomeEnterpriseSdmV1ExecuteDeviceCommandResponse:
      description: Response message for SmartDeviceManagementService.ExecuteDeviceCommand
      type: object
      id: GoogleHomeEnterpriseSdmV1ExecuteDeviceCommandResponse
      properties:
        results:
          description: The results of executing the command.
          additionalProperties:
            description: Properties of the object.
            type: any
          type: object
    GoogleHomeEnterpriseSdmV1ExecuteDeviceCommandRequest:
      type: object
      id: GoogleHomeEnterpriseSdmV1ExecuteDeviceCommandRequest
      properties:
        params:
          description: The command message to execute, represented as a Struct.
          type: object
          additionalProperties:
            type: any
            description: Properties of the object.
        command:
          type: string
          description: The command name to execute, represented by the fully qualified protobuf message name.
      description: Request message for SmartDeviceManagementService.ExecuteDeviceCommand
    GoogleHomeEnterpriseSdmV1Structure:
      description: Structure resource represents an instance of enterprise managed home or hotel room.
      properties:
        traits:
          type: object
          additionalProperties:
            type: any
            description: Properties of the object.
          description: Structure traits.
        name:
          type: string
          readOnly: true
          description: 'Output only. The resource name of the structure. For example: "enterprises/XYZ/structures/ABC".'
      id: GoogleHomeEnterpriseSdmV1Structure
      type: object
    GoogleHomeEnterpriseSdmV1ListRoomsResponse:
      description: Response message for SmartDeviceManagementService.ListRooms
      type: object
      properties:
        rooms:
          description: The list of rooms.
          type: array
          items:
            $ref: '#/components/schemas/GoogleHomeEnterpriseSdmV1Room'
        nextPageToken:
          type: string
          description: The pagination token to retrieve the next page of results. If this field is omitted, there are no subsequent pages.
      id: GoogleHomeEnterpriseSdmV1ListRoomsResponse
    GoogleHomeEnterpriseSdmV1ListDevicesResponse:
      type: object
      id: GoogleHomeEnterpriseSdmV1ListDevicesResponse
      properties:
        nextPageToken:
          description: The pagination token to retrieve the next page of results.
          type: string
        devices:
          items:
            $ref: '#/components/schemas/GoogleHomeEnterpriseSdmV1Device'
          type: array
          description: The list of devices.
      description: Response message for SmartDeviceManagementService.ListDevices
    GoogleHomeEnterpriseSdmV1ListStructuresResponse:
      id: GoogleHomeEnterpriseSdmV1ListStructuresResponse
      type: object
      properties:
        structures:
          items:
            $ref: '#/components/schemas/GoogleHomeEnterpriseSdmV1Structure'
          description: The list of structures.
          type: array
        nextPageToken:
          type: string
          description: The pagination token to retrieve the next page of results. If this field is omitted, there are no subsequent pages.
      description: Response message for SmartDeviceManagementService.ListStructures
    GoogleHomeEnterpriseSdmV1Device:
      description: Device resource represents an instance of enterprise managed device in the property.
      id: GoogleHomeEnterpriseSdmV1Device
      type: object
      properties:
        traits:
          description: Output only. Device traits.
          readOnly: true
          additionalProperties:
            description: Properties of the object.
            type: any
          type: object
        type:
          description: 'Output only. Type of the device for general display purposes. For example: "THERMOSTAT". The device type should not be used to deduce or infer functionality of the actual device it is assigned to. Instead, use the returned traits for the device.'
          type: string
          readOnly: true
        name:
          description: 'Required. The resource name of the device. For example: "enterprises/XYZ/devices/123".'
          type: string
        parentRelations:
          type: array
          description: Assignee details of the device.
          items:
            $ref: '#/components/schemas/GoogleHomeEnterpriseSdmV1ParentRelation'
    GoogleHomeEnterpriseSdmV1ParentRelation:
      id: GoogleHomeEnterpriseSdmV1ParentRelation
      description: Represents device relationships, for instance, structure/room to which the device is assigned to.
      properties:
        parent:
          readOnly: true
          type: string
          description: 'Output only. The name of the relation -- e.g., structure/room where the device is assigned to. For example: "enterprises/XYZ/structures/ABC" or "enterprises/XYZ/structures/ABC/rooms/123"'
        displayName:
          description: Output only. The custom name of the relation -- e.g., structure/room where the device is assigned to.
          type: string
          readOnly: true
      type: object
    GoogleHomeEnterpriseSdmV1Room:
      description: Room resource represents an instance of sub-space within a structure such as rooms in a hotel suite or rental apartment.
      properties:
        name:
          description: 'Output only. The resource name of the room. For example: "enterprises/XYZ/structures/ABC/rooms/123".'
          readOnly: true
          type: string
        traits:
          additionalProperties:
            type: any
            description: Properties of the object.
          description: Room traits.
          type: object
      id: GoogleHomeEnterpriseSdmV1Room
      type: object
  parameters:
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    quotaUser:
      description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    upload_protocol:
      description: Upload protocol for media (e.g. "raw", "multipart").
      in: query
      name: upload_protocol
      schema:
        type: string
    key:
      description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      in: query
      name: key
      schema:
        type: string
    uploadType:
      description: Legacy upload protocol for media (e.g. "media", "multipart").
      in: query
      name: uploadType
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/sdm.service: See and/or control the devices that you selected
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
  x-stackQL-resources:
    devices:
      id: googledevelopers.smartdevicemanagement.devices
      name: devices
      title: Devices
      methods:
        enterprises_devices_list:
          operation:
            $ref: '#/paths/~1v1~1enterprises~1{enterprisesId}~1devices/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        enterprises_devices_get:
          operation:
            $ref: '#/paths/~1v1~1enterprises~1{enterprisesId}~1devices~1{devicesId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        enterprises_devices_executeCommand:
          operation:
            $ref: '#/paths/~1v1~1enterprises~1{enterprisesId}~1devices~1{devicesId}:executeCommand/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/devices/methods/enterprises_devices_get'
          - $ref: '#/components/x-stackQL-resources/devices/methods/enterprises_devices_list'
        insert: []
        update: []
        delete: []
    rooms:
      id: googledevelopers.smartdevicemanagement.rooms
      name: rooms
      title: Rooms
      methods:
        enterprises_structures_rooms_get:
          operation:
            $ref: '#/paths/~1v1~1enterprises~1{enterprisesId}~1structures~1{structuresId}~1rooms~1{roomsId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        enterprises_structures_rooms_list:
          operation:
            $ref: '#/paths/~1v1~1enterprises~1{enterprisesId}~1structures~1{structuresId}~1rooms/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/rooms/methods/enterprises_structures_rooms_get'
          - $ref: '#/components/x-stackQL-resources/rooms/methods/enterprises_structures_rooms_list'
        insert: []
        update: []
        delete: []
    structures:
      id: googledevelopers.smartdevicemanagement.structures
      name: structures
      title: Structures
      methods:
        enterprises_structures_get:
          operation:
            $ref: '#/paths/~1v1~1enterprises~1{enterprisesId}~1structures~1{structuresId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        enterprises_structures_list:
          operation:
            $ref: '#/paths/~1v1~1enterprises~1{enterprisesId}~1structures/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/structures/methods/enterprises_structures_get'
          - $ref: '#/components/x-stackQL-resources/structures/methods/enterprises_structures_list'
        insert: []
        update: []
        delete: []
paths:
  /v1/enterprises/{enterprisesId}/devices:
    parameters: &ref_1
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/access_token'
    get:
      description: Lists devices managed by the enterprise.
      operationId: smartdevicemanagement.enterprises.devices.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/sdm.service
          Oauth2c:
            - https://www.googleapis.com/auth/sdm.service
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleHomeEnterpriseSdmV1ListDevicesResponse'
      parameters:
        - in: path
          name: enterprisesId
          required: true
          schema:
            type: string
        - in: query
          name: pageToken
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: filter
          schema:
            type: string
      x-stackQL-resource: devices
      x-stackQL-verb: select
  /v1/enterprises/{enterprisesId}/devices/{devicesId}:
    parameters: *ref_1
    get:
      description: Gets a device managed by the enterprise.
      operationId: smartdevicemanagement.enterprises.devices.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/sdm.service
          Oauth2c:
            - https://www.googleapis.com/auth/sdm.service
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleHomeEnterpriseSdmV1Device'
      parameters:
        - in: path
          name: enterprisesId
          required: true
          schema:
            type: string
        - in: path
          name: devicesId
          required: true
          schema:
            type: string
      x-stackQL-resource: devices
      x-stackQL-verb: select
  /v1/enterprises/{enterprisesId}/devices/{devicesId}:executeCommand:
    parameters: *ref_1
    post:
      description: Executes a command to device managed by the enterprise.
      operationId: smartdevicemanagement.enterprises.devices.executeCommand
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GoogleHomeEnterpriseSdmV1ExecuteDeviceCommandRequest'
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/sdm.service
          Oauth2c:
            - https://www.googleapis.com/auth/sdm.service
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleHomeEnterpriseSdmV1ExecuteDeviceCommandResponse'
      parameters:
        - in: path
          name: enterprisesId
          required: true
          schema:
            type: string
        - in: path
          name: devicesId
          required: true
          schema:
            type: string
      x-stackQL-resource: devices
      x-stackQL-verb: exec
  /v1/enterprises/{enterprisesId}/structures/{structuresId}/rooms/{roomsId}:
    parameters: *ref_1
    get:
      description: Gets a room managed by the enterprise.
      operationId: smartdevicemanagement.enterprises.structures.rooms.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/sdm.service
          Oauth2c:
            - https://www.googleapis.com/auth/sdm.service
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleHomeEnterpriseSdmV1Room'
      parameters:
        - in: path
          name: enterprisesId
          required: true
          schema:
            type: string
        - in: path
          name: structuresId
          required: true
          schema:
            type: string
        - in: path
          name: roomsId
          required: true
          schema:
            type: string
      x-stackQL-resource: rooms
      x-stackQL-verb: select
  /v1/enterprises/{enterprisesId}/structures/{structuresId}/rooms:
    parameters: *ref_1
    get:
      description: Lists rooms managed by the enterprise.
      operationId: smartdevicemanagement.enterprises.structures.rooms.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/sdm.service
          Oauth2c:
            - https://www.googleapis.com/auth/sdm.service
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleHomeEnterpriseSdmV1ListRoomsResponse'
      parameters:
        - in: path
          name: enterprisesId
          required: true
          schema:
            type: string
        - in: path
          name: structuresId
          required: true
          schema:
            type: string
        - in: query
          name: pageToken
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
      x-stackQL-resource: rooms
      x-stackQL-verb: select
  /v1/enterprises/{enterprisesId}/structures/{structuresId}:
    parameters: *ref_1
    get:
      description: Gets a structure managed by the enterprise.
      operationId: smartdevicemanagement.enterprises.structures.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/sdm.service
          Oauth2c:
            - https://www.googleapis.com/auth/sdm.service
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleHomeEnterpriseSdmV1Structure'
      parameters:
        - in: path
          name: enterprisesId
          required: true
          schema:
            type: string
        - in: path
          name: structuresId
          required: true
          schema:
            type: string
      x-stackQL-resource: structures
      x-stackQL-verb: select
  /v1/enterprises/{enterprisesId}/structures:
    parameters: *ref_1
    get:
      description: Lists structures managed by the enterprise.
      operationId: smartdevicemanagement.enterprises.structures.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/sdm.service
          Oauth2c:
            - https://www.googleapis.com/auth/sdm.service
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleHomeEnterpriseSdmV1ListStructuresResponse'
      parameters:
        - in: path
          name: enterprisesId
          required: true
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: pageToken
          schema:
            type: string
      x-stackQL-resource: structures
      x-stackQL-verb: select
