openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: versionhistory.googleapis.com API
  description: Version History API - Prod
  version: v1
  x-discovery-doc-revision: '20230104'
  x-generated-date: '2023-01-06'
externalDocs:
  url: https://developers.chrome.com/versionhistory
servers:
  - url: https://versionhistory.googleapis.com
components:
  schemas:
    ListReleasesResponse:
      properties:
        releases:
          items:
            $ref: '#/components/schemas/Release'
          description: The list of releases.
          type: array
        nextPageToken:
          description: A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.
          type: string
      id: ListReleasesResponse
      type: object
      description: Response message for ListReleases.
    ListChannelsResponse:
      description: Response message for ListChannels.
      properties:
        nextPageToken:
          type: string
          description: A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.
        channels:
          type: array
          items:
            $ref: '#/components/schemas/Channel'
          description: The list of channels.
      id: ListChannelsResponse
      type: object
    ListVersionsResponse:
      description: Response message for ListVersions.
      type: object
      id: ListVersionsResponse
      properties:
        versions:
          items:
            $ref: '#/components/schemas/Version'
          description: The list of versions.
          type: array
        nextPageToken:
          description: A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.
          type: string
    Version:
      description: Each Version is owned by a Channel. A Version only displays the Version number (e.g. 84.0.4147.38). A Version owns a collection of releases.
      type: object
      properties:
        name:
          type: string
          description: Version name. Format is "{product}/platforms/{platform}/channels/{channel}/versions/{version}" e.g. "chrome/platforms/win/channels/beta/versions/84.0.4147.38"
        version:
          description: String containing just the version number. e.g. "84.0.4147.38"
          type: string
      id: Version
    Release:
      properties:
        version:
          type: string
          description: String containing just the version number. e.g. "84.0.4147.38"
        serving:
          $ref: '#/components/schemas/Interval'
          description: Timestamp interval of when the release was live. If end_time is unspecified, the release is currently live.
        fraction:
          format: double
          type: number
          description: Rollout fraction. This fraction indicates the fraction of people that should receive this version in this release. If the fraction is not specified in ReleaseManager, the API will assume fraction is 1.
        name:
          type: string
          description: Release name. Format is "{product}/platforms/{platform}/channels/{channel}/versions/{version}/releases/{release}"
        fractionGroup:
          format: int64
          type: string
          description: 'Rollout fraction group. Only fractions with the same fraction_group are statistically comparable: there may be non-fractional differences between different fraction groups.'
      id: Release
      type: object
      description: A Release is owned by a Version. A Release contains information about the release(s) of its parent version. This includes when the release began and ended, as well as what percentage it was released at. If the version is released again, or if the serving percentage changes, it will create another release under the version.
    Platform:
      description: Each Platform is owned by a Product and owns a collection of channels. Available platforms are listed in Platform enum below. Not all Channels are available for every Platform (e.g. CANARY does not exist for LINUX).
      properties:
        name:
          type: string
          description: Platform name. Format is "{product}/platforms/{platform}"
        platformType:
          enum:
            - PLATFORM_TYPE_UNSPECIFIED
            - WIN
            - WIN64
            - MAC
            - LINUX
            - ANDROID
            - WEBVIEW
            - IOS
            - ALL
            - MAC_ARM64
            - LACROS
            - LACROS_ARM32
            - CHROMEOS
            - LACROS_ARM64
            - FUCHSIA
          enumDescriptions:
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
          description: Type of platform.
          type: string
      type: object
      id: Platform
    Channel:
      description: Each Channel is owned by a Platform and owns a collection of versions. Possible Channels are listed in the Channel enum below. Not all Channels are available for every Platform (e.g. CANARY does not exist for LINUX).
      type: object
      id: Channel
      properties:
        name:
          type: string
          description: Channel name. Format is "{product}/platforms/{platform}/channels/{channel}"
        channelType:
          description: Type of channel.
          enum:
            - CHANNEL_TYPE_UNSPECIFIED
            - STABLE
            - BETA
            - DEV
            - CANARY
            - CANARY_ASAN
            - ALL
            - EXTENDED
          type: string
          enumDescriptions:
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
            - ''
    Interval:
      id: Interval
      description: Represents a time interval, encoded as a Timestamp start (inclusive) and a Timestamp end (exclusive). The start must be less than or equal to the end. When the start equals the end, the interval is empty (matches no time). When both start and end are unspecified, the interval matches any time.
      type: object
      properties:
        endTime:
          format: google-datetime
          description: Optional. Exclusive end of the interval. If specified, a Timestamp matching this interval will have to be before the end.
          type: string
        startTime:
          type: string
          description: Optional. Inclusive start of the interval. If specified, a Timestamp matching this interval will have to be the same or after the start.
          format: google-datetime
    ListPlatformsResponse:
      type: object
      description: Response message for ListPlatforms.
      id: ListPlatformsResponse
      properties:
        nextPageToken:
          description: A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.
          type: string
        platforms:
          description: The list of platforms.
          type: array
          items:
            $ref: '#/components/schemas/Platform'
  parameters:
    key:
      description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      in: query
      name: key
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    upload_protocol:
      description: Upload protocol for media (e.g. "raw", "multipart").
      in: query
      name: upload_protocol
      schema:
        type: string
    uploadType:
      description: Legacy upload protocol for media (e.g. "media", "multipart").
      in: query
      name: uploadType
      schema:
        type: string
    quotaUser:
      description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/verifiedaccess: Verify your enterprise credentials
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
  x-stackQL-resources:
    platforms:
      id: googledevelopers.versionhistory.platforms
      name: platforms
      title: Platforms
      methods:
        list:
          operation:
            $ref: '#/paths/~1v1~1{parent}~1platforms/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/platforms/methods/list'
        insert: []
        update: []
        delete: []
    versions:
      id: googledevelopers.versionhistory.versions
      name: versions
      title: Versions
      methods:
        platforms_channels_versions_list:
          operation:
            $ref: '#/paths/~1v1~1{parent}~1versions/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/versions/methods/platforms_channels_versions_list'
        insert: []
        update: []
        delete: []
    releases:
      id: googledevelopers.versionhistory.releases
      name: releases
      title: Releases
      methods:
        platforms_channels_versions_releases_list:
          operation:
            $ref: '#/paths/~1v1~1{parent}~1releases/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/releases/methods/platforms_channels_versions_releases_list'
        insert: []
        update: []
        delete: []
    channels:
      id: googledevelopers.versionhistory.channels
      name: channels
      title: Channels
      methods:
        platforms_channels_list:
          operation:
            $ref: '#/paths/~1v1~1{parent}~1channels/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/channels/methods/platforms_channels_list'
        insert: []
        update: []
        delete: []
paths:
  /v1/{parent}/platforms:
    parameters: &ref_1
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/oauth_token'
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/alt'
    get:
      description: Returns list of platforms that are available for a given product. The resource "product" has no resource name in its name.
      operationId: versionhistory.platforms.list
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPlatformsResponse'
      parameters:
        - in: path
          name: parent
          required: true
          schema:
            type: string
        - in: query
          name: pageToken
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
      x-stackQL-resource: platforms
      x-stackQL-verb: select
  /v1/{parent}/versions:
    parameters: *ref_1
    get:
      description: Returns list of version for the given platform/channel.
      operationId: versionhistory.platforms.channels.versions.list
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListVersionsResponse'
      parameters:
        - in: path
          name: parent
          required: true
          schema:
            type: string
        - in: query
          name: pageToken
          schema:
            type: string
        - in: query
          name: orderBy
          schema:
            type: string
        - in: query
          name: filter
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
      x-stackQL-resource: versions
      x-stackQL-verb: select
  /v1/{parent}/releases:
    parameters: *ref_1
    get:
      description: Returns list of releases of the given version.
      operationId: versionhistory.platforms.channels.versions.releases.list
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListReleasesResponse'
      parameters:
        - in: path
          name: parent
          required: true
          schema:
            type: string
        - in: query
          name: orderBy
          schema:
            type: string
        - in: query
          name: pageToken
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: filter
          schema:
            type: string
      x-stackQL-resource: releases
      x-stackQL-verb: select
  /v1/{parent}/channels:
    parameters: *ref_1
    get:
      description: Returns list of channels that are available for a given platform.
      operationId: versionhistory.platforms.channels.list
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListChannelsResponse'
      parameters:
        - in: path
          name: parent
          required: true
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: pageToken
          schema:
            type: string
      x-stackQL-resource: channels
      x-stackQL-verb: select
