paths:
  /deploy_keys:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/deployKey'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - deployKey
      operationId: listDeployKeys
    post:
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deployKey'
          description: Created
        default:
          $ref: '#/components/responses/error'
      tags:
        - deployKey
      operationId: createDeployKey
  /deploy_keys/{key_id}:
    delete:
      responses:
        '204':
          description: Not Content
        default:
          $ref: '#/components/responses/error'
      tags:
        - deployKey
      operationId: deleteDeployKey
      parameters: &ref_0
        - in: path
          name: key_id
          required: true
          schema:
            type: string
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deployKey'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - deployKey
      operationId: getDeployKey
      parameters: *ref_0
  /deploys/{deploy_id}:
    get:
      parameters:
        - in: path
          name: deploy_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deploy'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - deploy
      operationId: getDeploy
  /deploys/{deploy_id}/cancel:
    post:
      parameters:
        - in: path
          name: deploy_id
          required: true
          schema:
            type: string
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deploy'
          description: Cancelled
        default:
          $ref: '#/components/responses/error'
      tags:
        - deploy
      operationId: cancelSiteDeploy
  /deploys/{deploy_id}/lock:
    post:
      parameters:
        - in: path
          name: deploy_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deploy'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - deploy
      operationId: lockDeploy
  /deploys/{deploy_id}/unlock:
    post:
      parameters:
        - in: path
          name: deploy_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deploy'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - deploy
      operationId: unlockDeploy
  /sites/{site_id}/deployed-branches:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/deployedBranch'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - deployedBranch
      operationId: listSiteDeployedBranches
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
  /sites/{site_id}/deploys:
    get:
      parameters: &ref_1
        - in: path
          name: site_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/deploy'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - deploy
      operationId: listSiteDeploys
    post:
      parameters: *ref_1
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deploy'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - deploy
      operationId: createSiteDeploy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deployFiles'
        required: true
  /sites/{site_id}/deploys/{deploy_id}:
    get:
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
        - in: path
          name: deploy_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deploy'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - deploy
      operationId: getSiteDeploy
    put:
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
        - in: path
          name: deploy_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deploy'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - deploy
      operationId: updateSiteDeploy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deployFiles'
        required: true
  /sites/{site_id}/deploys/{deploy_id}/restore:
    post:
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
        - in: path
          name: deploy_id
          required: true
          schema:
            type: string
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deploy'
          description: Created
        default:
          $ref: '#/components/responses/error'
      tags:
        - deploy
      operationId: restoreSiteDeploy
  /sites/{site_id}/rollback:
    put:
      responses:
        '204':
          description: No content
        default:
          $ref: '#/components/responses/error'
      tags:
        - deploy
      operationId: rollbackSiteDeploy
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
components:
  schemas:
    deployKey:
      properties:
        created_at:
          format: dateTime
          type: string
        id:
          type: string
        public_key:
          type: string
      type: object
    error:
      properties:
        code:
          format: int64
          type: integer
        message:
          nullable: false
          type: string
      required:
        - message
      type: object
    deploy:
      properties:
        admin_url:
          type: string
        branch:
          type: string
        build_id:
          type: string
        commit_ref:
          type: string
        commit_url:
          type: string
        context:
          type: string
        created_at:
          format: dateTime
          type: string
        deploy_ssl_url:
          type: string
        deploy_url:
          type: string
        draft:
          type: boolean
        error_message:
          type: string
        framework:
          type: string
        function_schedules:
          items:
            $ref: '#/components/schemas/functionSchedule'
          type: array
        id:
          type: string
        locked:
          type: boolean
        name:
          type: string
        published_at:
          format: dateTime
          type: string
        required:
          items:
            type: string
          type: array
        required_functions:
          items:
            type: string
          type: array
        review_id:
          type: number
        review_url:
          type: string
        screenshot_url:
          type: string
        site_capabilities:
          properties:
            large_media_enabled:
              type: boolean
          type: object
        site_id:
          type: string
        skipped:
          type: boolean
        ssl_url:
          type: string
        state:
          type: string
        title:
          type: string
        updated_at:
          format: dateTime
          type: string
        url:
          type: string
        user_id:
          type: string
      type: object
    functionSchedule:
      properties:
        cron:
          type: string
        name:
          type: string
      type: object
    deployedBranch:
      properties:
        deploy_id:
          type: string
        id:
          type: string
        name:
          type: string
        slug:
          type: string
        ssl_url:
          type: string
        url:
          type: string
      type: object
    deployFiles:
      properties:
        async:
          type: boolean
        branch:
          type: string
        draft:
          type: boolean
        files:
          type: object
        framework:
          type: string
        function_schedules:
          items:
            $ref: '#/components/schemas/functionSchedule'
          type: array
        functions:
          type: object
      type: object
  parameters:
    page:
      in: query
      name: page
      required: false
      schema:
        format: int32
        type: integer
    perPage:
      in: query
      name: per_page
      required: false
      schema:
        format: int32
        type: integer
  responses:
    error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: error
  securitySchemes: {}
  callbacks: {}
  examples: {}
  requestBodies: {}
  headers: {}
  links: {}
  x-stackQL-resources:
    deployKey:
      id: netlify.deploys.deployKey
      name: deployKey
      title: deployKey
      methods:
        listDeployKeys:
          operation:
            $ref: '#/paths/~1deploy_keys/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        createDeployKey:
          operation:
            $ref: '#/paths/~1deploy_keys/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        deleteDeployKey:
          operation:
            $ref: '#/paths/~1deploy_keys~1{key_id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        getDeployKey:
          operation:
            $ref: '#/paths/~1deploy_keys~1{key_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/deployKey/methods/getDeployKey'
          - $ref: '#/components/x-stackQL-resources/deployKey/methods/listDeployKeys'
        insert:
          - $ref: '#/components/x-stackQL-resources/deployKey/methods/createDeployKey'
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/deployKey/methods/deleteDeployKey'
    deploy:
      id: netlify.deploys.deploy
      name: deploy
      title: deploy
      methods:
        getDeploy:
          operation:
            $ref: '#/paths/~1deploys~1{deploy_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        cancelSiteDeploy:
          operation:
            $ref: '#/paths/~1deploys~1{deploy_id}~1cancel/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        lockDeploy:
          operation:
            $ref: '#/paths/~1deploys~1{deploy_id}~1lock/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        unlockDeploy:
          operation:
            $ref: '#/paths/~1deploys~1{deploy_id}~1unlock/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        listSiteDeploys:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1deploys/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        createSiteDeploy:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1deploys/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        getSiteDeploy:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1deploys~1{deploy_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        updateSiteDeploy:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1deploys~1{deploy_id}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        restoreSiteDeploy:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1deploys~1{deploy_id}~1restore/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        rollbackSiteDeploy:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1rollback/put'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/deploy/methods/getSiteDeploy'
          - $ref: '#/components/x-stackQL-resources/deploy/methods/getDeploy'
          - $ref: '#/components/x-stackQL-resources/deploy/methods/listSiteDeploys'
        insert:
          - $ref: '#/components/x-stackQL-resources/deploy/methods/createSiteDeploy'
        update: []
        delete: []
    deployedBranch:
      id: netlify.deploys.deployedBranch
      name: deployedBranch
      title: deployedBranch
      methods:
        listSiteDeployedBranches:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1deployed-branches/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/deployedBranch/methods/listSiteDeployedBranches'
        insert: []
        update: []
        delete: []
openapi: 3.0.0
servers:
  - url: https://api.netlify.com/api/v1
security:
  - netlifyAuth: []
tags:
  - name: ticket
    x-displayName: Ticket
  - name: accessToken
    x-displayName: Access token
  - name: user
    x-displayName: User
  - name: accountMembership
    x-displayName: Accounts
  - name: member
    x-displayName: Member
  - name: accountType
    x-displayName: Access type
  - name: paymentMethod
    x-displayName: Payment method
  - name: auditLog
    x-displayName: Audit log
  - name: site
    x-displayName: Site
  - name: file
    x-displayName: File
  - name: metadata
    x-displayName: Metadata
  - name: snippet
    x-displayName: Snippet
  - name: dnsZone
    x-displayName: DNS zone
  - name: sniCertificate
    x-displayName: SNI certificate
  - name: deploy
    x-displayName: Deploy
  - name: deployedBranch
    x-displayName: Deployed branch
  - name: deployKey
    x-displayName: Deploy key
  - name: build
    x-displayName: Build
  - name: buildLogMsg
    x-displayName: Build log message
  - name: hook
    x-displayName: Hook
  - name: hookType
    x-displayName: Hook type
  - name: buildHook
    x-displayName: Build hook
  - name: service
    x-displayName: Service
  - name: serviceInstance
    x-displayName: Service instance
  - name: function
    x-displayName: Function
  - name: form
    x-displayName: Form
  - name: submission
    x-displayName: Form submission
  - name: splitTest
    x-displayName: Split test
  - name: asset
    x-displayName: Asset
  - name: assetPublicSignature
    x-displayName: Asset public signature
externalDocs:
  description: Online documentation
  url: https://www.netlify.com/docs/api/
info:
  description: Deploys
  termsOfService: https://www.netlify.com/legal/terms-of-use/
  title: Netlify's API documentation - deploys
  version: 2.9.0
  x-logo:
    altText: Netlify
    href: https://www.netlify.com/docs/
    url: netlify-logo.png
