paths:
  /forms/{form_id}/submissions:
    get:
      parameters:
        - in: path
          name: form_id
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/perPage'
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/submission'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - submission
      operationId: listFormSubmissions
  /sites/{site_id}/forms:
    get:
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/form'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - form
      operationId: listSiteForms
  /sites/{site_id}/forms/{form_id}:
    delete:
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
        - in: path
          name: form_id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Deleted
        default:
          $ref: '#/components/responses/error'
      tags:
        - form
      operationId: deleteSiteForm
  /sites/{site_id}/submissions:
    get:
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/perPage'
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/submission'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - submission
      operationId: listSiteSubmissions
  /submissions/{submission_id}:
    delete:
      responses:
        '204':
          description: Deleted
        default:
          $ref: '#/components/responses/error'
      tags:
        - submission
      operationId: deleteSubmission
      parameters: &ref_0
        - in: path
          name: submission_id
          required: true
          schema:
            type: string
    get:
      parameters: *ref_0
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/submission'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - submission
      operationId: listFormSubmission
components:
  schemas:
    submission:
      properties:
        body:
          type: string
        company:
          type: string
        created_at:
          format: dateTime
          type: string
        data:
          type: object
        email:
          type: string
        first_name:
          type: string
        id:
          type: string
        last_name:
          type: string
        name:
          type: string
        number:
          format: int32
          type: integer
        site_url:
          type: string
        summary:
          type: string
      type: object
    error:
      properties:
        code:
          format: int64
          type: integer
        message:
          nullable: false
          type: string
      required:
        - message
      type: object
    form:
      properties:
        paths:
          items:
            type: string
          type: array
        created_at:
          format: dateTime
          type: string
        fields:
          items:
            type: object
          type: array
        id:
          type: string
        name:
          type: string
        site_id:
          type: string
        submission_count:
          format: int32
          type: integer
      type: object
  parameters:
    page:
      in: query
      name: page
      required: false
      schema:
        format: int32
        type: integer
    perPage:
      in: query
      name: per_page
      required: false
      schema:
        format: int32
        type: integer
  responses:
    error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: error
  securitySchemes: {}
  callbacks: {}
  examples: {}
  requestBodies: {}
  headers: {}
  links: {}
  x-stackQL-resources:
    submission:
      id: netlify.forms.submission
      name: submission
      title: submission
      methods:
        listFormSubmissions:
          operation:
            $ref: '#/paths/~1forms~1{form_id}~1submissions/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        listSiteSubmissions:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1submissions/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        deleteSubmission:
          operation:
            $ref: '#/paths/~1submissions~1{submission_id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        listFormSubmission:
          operation:
            $ref: '#/paths/~1submissions~1{submission_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/submission/methods/listFormSubmissions'
          - $ref: '#/components/x-stackQL-resources/submission/methods/listSiteSubmissions'
          - $ref: '#/components/x-stackQL-resources/submission/methods/listFormSubmission'
        insert: []
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/submission/methods/deleteSubmission'
    form:
      id: netlify.forms.form
      name: form
      title: form
      methods:
        listSiteForms:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1forms/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        deleteSiteForm:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1forms~1{form_id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/form/methods/listSiteForms'
        insert: []
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/form/methods/deleteSiteForm'
openapi: 3.0.0
servers:
  - url: https://api.netlify.com/api/v1
security:
  - netlifyAuth: []
tags:
  - name: ticket
    x-displayName: Ticket
  - name: accessToken
    x-displayName: Access token
  - name: user
    x-displayName: User
  - name: accountMembership
    x-displayName: Accounts
  - name: member
    x-displayName: Member
  - name: accountType
    x-displayName: Access type
  - name: paymentMethod
    x-displayName: Payment method
  - name: auditLog
    x-displayName: Audit log
  - name: site
    x-displayName: Site
  - name: file
    x-displayName: File
  - name: metadata
    x-displayName: Metadata
  - name: snippet
    x-displayName: Snippet
  - name: dnsZone
    x-displayName: DNS zone
  - name: sniCertificate
    x-displayName: SNI certificate
  - name: deploy
    x-displayName: Deploy
  - name: deployedBranch
    x-displayName: Deployed branch
  - name: deployKey
    x-displayName: Deploy key
  - name: build
    x-displayName: Build
  - name: buildLogMsg
    x-displayName: Build log message
  - name: hook
    x-displayName: Hook
  - name: hookType
    x-displayName: Hook type
  - name: buildHook
    x-displayName: Build hook
  - name: service
    x-displayName: Service
  - name: serviceInstance
    x-displayName: Service instance
  - name: function
    x-displayName: Function
  - name: form
    x-displayName: Form
  - name: submission
    x-displayName: Form submission
  - name: splitTest
    x-displayName: Split test
  - name: asset
    x-displayName: Asset
  - name: assetPublicSignature
    x-displayName: Asset public signature
externalDocs:
  description: Online documentation
  url: https://www.netlify.com/docs/api/
info:
  description: Forms
  termsOfService: https://www.netlify.com/legal/terms-of-use/
  title: Netlify's API documentation - forms
  version: 2.9.0
  x-logo:
    altText: Netlify
    href: https://www.netlify.com/docs/
    url: netlify-logo.png
