paths:
  /hooks:
    get:
      parameters:
        - in: query
          name: site_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/hook'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - hook
      operationId: listHooksBySiteId
    post:
      parameters:
        - in: query
          name: site_id
          required: true
          schema:
            type: string
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hook'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - hook
      operationId: createHookBySiteId
      requestBody:
        $ref: '#/components/requestBodies/hook'
  /hooks/types:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/hookType'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - hookType
      operationId: listHookTypes
  /hooks/{hook_id}:
    delete:
      responses:
        '204':
          description: No content
      tags:
        - hook
      operationId: deleteHook
      parameters: &ref_0
        - in: path
          name: hook_id
          required: true
          schema:
            type: string
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hook'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - hook
      operationId: getHook
      parameters: *ref_0
    put:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hook'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - hook
      operationId: updateHook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/hook'
        required: true
      parameters: *ref_0
  /hooks/{hook_id}/enable:
    post:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hook'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - hook
      operationId: enableHook
      parameters:
        - in: path
          name: hook_id
          required: true
          schema:
            type: string
  /sites/{site_id}/build_hooks:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/buildHook'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - buildHook
      operationId: listSiteBuildHooks
      parameters: &ref_1
        - in: path
          name: site_id
          required: true
          schema:
            type: string
    post:
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/buildHook'
          description: Created
        default:
          $ref: '#/components/responses/error'
      tags:
        - buildHook
      operationId: createSiteBuildHook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/buildHookSetup'
        required: true
      parameters: *ref_1
  /sites/{site_id}/build_hooks/{id}:
    delete:
      responses:
        '204':
          description: No content
        default:
          $ref: '#/components/responses/error'
      tags:
        - buildHook
      operationId: deleteSiteBuildHook
      parameters: &ref_2
        - in: path
          name: site_id
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: string
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/buildHook'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - buildHook
      operationId: getSiteBuildHook
      parameters: *ref_2
    put:
      responses:
        '204':
          description: No content
        default:
          $ref: '#/components/responses/error'
      tags:
        - buildHook
      operationId: updateSiteBuildHook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/buildHookSetup'
        required: true
      parameters: *ref_2
components:
  schemas:
    hook:
      properties:
        created_at:
          format: dateTime
          type: string
        data:
          type: object
        disabled:
          type: boolean
        event:
          type: string
        id:
          type: string
        site_id:
          type: string
        type:
          type: string
        updated_at:
          format: dateTime
          type: string
      type: object
    error:
      properties:
        code:
          format: int64
          type: integer
        message:
          nullable: false
          type: string
      required:
        - message
      type: object
    hookType:
      properties:
        events:
          items:
            type: string
          type: array
        fields:
          items:
            type: object
          type: array
        name:
          type: string
      type: object
    buildHook:
      properties:
        branch:
          type: string
        created_at:
          format: dateTime
          type: string
        id:
          type: string
        site_id:
          type: string
        title:
          type: string
        url:
          type: string
      type: object
    buildHookSetup:
      properties:
        branch:
          type: string
        title:
          type: string
      type: object
  parameters: {}
  responses:
    error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: error
  securitySchemes: {}
  callbacks: {}
  examples: {}
  requestBodies:
    hook:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/hook'
      required: true
  headers: {}
  links: {}
  x-stackQL-resources:
    hook:
      id: netlify.notifications.hook
      name: hook
      title: hook
      methods:
        listHooksBySiteId:
          operation:
            $ref: '#/paths/~1hooks/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        createHookBySiteId:
          operation:
            $ref: '#/paths/~1hooks/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        deleteHook:
          operation:
            $ref: '#/paths/~1hooks~1{hook_id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        getHook:
          operation:
            $ref: '#/paths/~1hooks~1{hook_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        updateHook:
          operation:
            $ref: '#/paths/~1hooks~1{hook_id}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        enableHook:
          operation:
            $ref: '#/paths/~1hooks~1{hook_id}~1enable/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/hook/methods/getHook'
          - $ref: '#/components/x-stackQL-resources/hook/methods/listHooksBySiteId'
        insert:
          - $ref: '#/components/x-stackQL-resources/hook/methods/createHookBySiteId'
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/hook/methods/deleteHook'
    hookType:
      id: netlify.notifications.hookType
      name: hookType
      title: hookType
      methods:
        listHookTypes:
          operation:
            $ref: '#/paths/~1hooks~1types/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/hookType/methods/listHookTypes'
        insert: []
        update: []
        delete: []
    buildHook:
      id: netlify.notifications.buildHook
      name: buildHook
      title: buildHook
      methods:
        listSiteBuildHooks:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1build_hooks/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        createSiteBuildHook:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1build_hooks/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        deleteSiteBuildHook:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1build_hooks~1{id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        getSiteBuildHook:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1build_hooks~1{id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        updateSiteBuildHook:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1build_hooks~1{id}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/buildHook/methods/getSiteBuildHook'
          - $ref: '#/components/x-stackQL-resources/buildHook/methods/listSiteBuildHooks'
        insert:
          - $ref: '#/components/x-stackQL-resources/buildHook/methods/createSiteBuildHook'
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/buildHook/methods/deleteSiteBuildHook'
openapi: 3.0.0
servers:
  - url: https://api.netlify.com/api/v1
security:
  - netlifyAuth: []
tags:
  - name: ticket
    x-displayName: Ticket
  - name: accessToken
    x-displayName: Access token
  - name: user
    x-displayName: User
  - name: accountMembership
    x-displayName: Accounts
  - name: member
    x-displayName: Member
  - name: accountType
    x-displayName: Access type
  - name: paymentMethod
    x-displayName: Payment method
  - name: auditLog
    x-displayName: Audit log
  - name: site
    x-displayName: Site
  - name: file
    x-displayName: File
  - name: metadata
    x-displayName: Metadata
  - name: snippet
    x-displayName: Snippet
  - name: dnsZone
    x-displayName: DNS zone
  - name: sniCertificate
    x-displayName: SNI certificate
  - name: deploy
    x-displayName: Deploy
  - name: deployedBranch
    x-displayName: Deployed branch
  - name: deployKey
    x-displayName: Deploy key
  - name: build
    x-displayName: Build
  - name: buildLogMsg
    x-displayName: Build log message
  - name: hook
    x-displayName: Hook
  - name: hookType
    x-displayName: Hook type
  - name: buildHook
    x-displayName: Build hook
  - name: service
    x-displayName: Service
  - name: serviceInstance
    x-displayName: Service instance
  - name: function
    x-displayName: Function
  - name: form
    x-displayName: Form
  - name: submission
    x-displayName: Form submission
  - name: splitTest
    x-displayName: Split test
  - name: asset
    x-displayName: Asset
  - name: assetPublicSignature
    x-displayName: Asset public signature
externalDocs:
  description: Online documentation
  url: https://www.netlify.com/docs/api/
info:
  description: Webhooks and Notifications
  termsOfService: https://www.netlify.com/legal/terms-of-use/
  title: Netlify's API documentation - notifications
  version: 2.9.0
  x-logo:
    altText: Netlify
    href: https://www.netlify.com/docs/
    url: netlify-logo.png
