paths:
  /services/:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/service'
                type: array
          description: services
        default:
          $ref: '#/components/responses/error'
      tags:
        - service
      operationId: getServices
      parameters:
        - in: query
          name: search
          schema:
            type: string
  /services/{addonName}:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service'
          description: services
        default:
          $ref: '#/components/responses/error'
      tags:
        - service
      operationId: showService
      parameters:
        - in: path
          name: addonName
          required: true
          schema:
            type: string
  /services/{addonName}/manifest:
    get:
      responses:
        '201':
          content:
            application/json:
              schema:
                type: object
          description: retrieving from provider
        default:
          $ref: '#/components/responses/error'
      tags:
        - service
      operationId: showServiceManifest
      parameters:
        - in: path
          name: addonName
          required: true
          schema:
            type: string
  /sites/{site_id}/service-instances:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/serviceInstance'
                type: array
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - serviceInstance
      operationId: listServiceInstancesForSite
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
  /sites/{site_id}/services/{addon}/instances:
    post:
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serviceInstance'
          description: Created
        default:
          $ref: '#/components/responses/error'
      tags:
        - serviceInstance
      operationId: createServiceInstance
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      parameters:
        - in: path
          name: site_id
          required: true
          schema:
            type: string
        - in: path
          name: addon
          required: true
          schema:
            type: string
  /sites/{site_id}/services/{addon}/instances/{instance_id}:
    delete:
      responses:
        '204':
          description: Deleted
        default:
          $ref: '#/components/responses/error'
      tags:
        - serviceInstance
      operationId: deleteServiceInstance
      parameters: &ref_0
        - in: path
          name: site_id
          required: true
          schema:
            type: string
        - in: path
          name: addon
          required: true
          schema:
            type: string
        - in: path
          name: instance_id
          required: true
          schema:
            type: string
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serviceInstance'
          description: OK
        default:
          $ref: '#/components/responses/error'
      tags:
        - serviceInstance
      operationId: showServiceInstance
      parameters: *ref_0
    put:
      responses:
        '204':
          description: No Content
        default:
          $ref: '#/components/responses/error'
      tags:
        - serviceInstance
      operationId: updateServiceInstance
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      parameters: *ref_0
components:
  schemas:
    service:
      properties:
        tags:
          items:
            type: string
          type: array
        created_at:
          format: dateTime
          type: string
        description:
          type: string
        environments:
          items:
            type: string
          type: array
        events:
          items:
            type: object
          type: array
        icon:
          type: string
        id:
          type: string
        long_description:
          type: string
        manifest_url:
          type: string
        name:
          type: string
        service_path:
          type: string
        slug:
          type: string
        updated_at:
          format: dateTime
          type: string
      type: object
    error:
      properties:
        code:
          format: int64
          type: integer
        message:
          nullable: false
          type: string
      required:
        - message
      type: object
    serviceInstance:
      properties:
        auth_url:
          type: string
        config:
          type: object
        created_at:
          format: dateTime
          type: string
        env:
          type: object
        external_attributes:
          type: object
        id:
          type: string
        service_name:
          type: string
        service_path:
          type: string
        service_slug:
          type: string
        snippets:
          items:
            type: object
          type: array
        updated_at:
          format: dateTime
          type: string
        url:
          type: string
      type: object
  parameters: {}
  responses:
    error:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
      description: error
  securitySchemes: {}
  callbacks: {}
  examples: {}
  requestBodies: {}
  headers: {}
  links: {}
  x-stackQL-resources:
    service:
      id: netlify.services.service
      name: service
      title: service
      methods:
        getServices:
          operation:
            $ref: '#/paths/~1services~1/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        showService:
          operation:
            $ref: '#/paths/~1services~1{addonName}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        showServiceManifest:
          operation:
            $ref: '#/paths/~1services~1{addonName}~1manifest/get'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/service/methods/getServices'
        insert: []
        update: []
        delete: []
    serviceInstance:
      id: netlify.services.serviceInstance
      name: serviceInstance
      title: serviceInstance
      methods:
        listServiceInstancesForSite:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1service-instances/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        createServiceInstance:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1services~1{addon}~1instances/post'
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        deleteServiceInstance:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1services~1{addon}~1instances~1{instance_id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        showServiceInstance:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1services~1{addon}~1instances~1{instance_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        updateServiceInstance:
          operation:
            $ref: '#/paths/~1sites~1{site_id}~1services~1{addon}~1instances~1{instance_id}/put'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/serviceInstance/methods/listServiceInstancesForSite'
        insert:
          - $ref: '#/components/x-stackQL-resources/serviceInstance/methods/createServiceInstance'
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/serviceInstance/methods/deleteServiceInstance'
openapi: 3.0.0
servers:
  - url: https://api.netlify.com/api/v1
security:
  - netlifyAuth: []
tags:
  - name: ticket
    x-displayName: Ticket
  - name: accessToken
    x-displayName: Access token
  - name: user
    x-displayName: User
  - name: accountMembership
    x-displayName: Accounts
  - name: member
    x-displayName: Member
  - name: accountType
    x-displayName: Access type
  - name: paymentMethod
    x-displayName: Payment method
  - name: auditLog
    x-displayName: Audit log
  - name: site
    x-displayName: Site
  - name: file
    x-displayName: File
  - name: metadata
    x-displayName: Metadata
  - name: snippet
    x-displayName: Snippet
  - name: dnsZone
    x-displayName: DNS zone
  - name: sniCertificate
    x-displayName: SNI certificate
  - name: deploy
    x-displayName: Deploy
  - name: deployedBranch
    x-displayName: Deployed branch
  - name: deployKey
    x-displayName: Deploy key
  - name: build
    x-displayName: Build
  - name: buildLogMsg
    x-displayName: Build log message
  - name: hook
    x-displayName: Hook
  - name: hookType
    x-displayName: Hook type
  - name: buildHook
    x-displayName: Build hook
  - name: service
    x-displayName: Service
  - name: serviceInstance
    x-displayName: Service instance
  - name: function
    x-displayName: Function
  - name: form
    x-displayName: Form
  - name: submission
    x-displayName: Form submission
  - name: splitTest
    x-displayName: Split test
  - name: asset
    x-displayName: Asset
  - name: assetPublicSignature
    x-displayName: Asset public signature
externalDocs:
  description: Online documentation
  url: https://www.netlify.com/docs/api/
info:
  description: Services
  termsOfService: https://www.netlify.com/legal/terms-of-use/
  title: Netlify's API documentation - services
  version: 2.9.0
  x-logo:
    altText: Netlify
    href: https://www.netlify.com/docs/
    url: netlify-logo.png
