id: firebase
name: firebase
version: v00.00.00000
providerServices:
  fcm:
    description: FCM send API that provides a cross-platform messaging solution to reliably deliver messages at no cost.
    id: fcm:v00.00.00000
    name: fcm
    preferred: true
    service:
      $ref: firebase/v00.00.00000/services/fcm.yaml
    title: Firebase Cloud Messaging API
    version: v00.00.00000
  fcmdata:
    description: Provides additional information about Firebase Cloud Messaging (FCM) message sends and deliveries.
    id: fcmdata:v00.00.00000
    name: fcmdata
    preferred: true
    service:
      $ref: firebase/v00.00.00000/services/fcmdata.yaml
    title: Firebase Cloud Messaging Data API
    version: v00.00.00000
  firebaseappcheck:
    description: Firebase App Check works alongside other Firebase services to help protect your backend resources from abuse, such as billing fraud or phishing.
    id: firebaseappcheck:v00.00.00000
    name: firebaseappcheck
    preferred: true
    service:
      $ref: firebase/v00.00.00000/services/firebaseappcheck.yaml
    title: Firebase App Check API
    version: v00.00.00000
  firebasedatabase:
    description: The Firebase Realtime Database Management API enables programmatic provisioning and management of Realtime Database instances.
    id: firebasedatabase:v00.00.00000
    name: firebasedatabase
    preferred: true
    service:
      $ref: firebase/v00.00.00000/services/firebasedatabase.yaml
    title: Firebase Realtime Database Management API
    version: v00.00.00000
  firebasedynamiclinks:
    description: Programmatically creates and manages Firebase Dynamic Links.
    id: firebasedynamiclinks:v00.00.00000
    name: firebasedynamiclinks
    preferred: true
    service:
      $ref: firebase/v00.00.00000/services/firebasedynamiclinks.yaml
    title: Firebase Dynamic Links API
    version: v00.00.00000
  firebasehosting:
    description: The Firebase Hosting REST API enables programmatic and customizable management and deployments to your Firebase-hosted sites. Use this REST API to create and manage channels and sites as well as to deploy new or updated hosting configurations and content files.
    id: firebasehosting:v00.00.00000
    name: firebasehosting
    preferred: true
    service:
      $ref: firebase/v00.00.00000/services/firebasehosting.yaml
    title: Firebase Hosting API
    version: v00.00.00000
  firebaserules:
    description: 'Creates and manages rules that determine when a Firebase Rules-enabled service should permit a request. '
    id: firebaserules:v00.00.00000
    name: firebaserules
    preferred: true
    service:
      $ref: firebase/v00.00.00000/services/firebaserules.yaml
    title: Firebase Rules API
    version: v00.00.00000
  firebasestorage:
    description: The Cloud Storage for Firebase API enables programmatic management of Cloud Storage buckets for use in Firebase projects
    id: firebasestorage:v00.00.00000
    name: firebasestorage
    preferred: true
    service:
      $ref: firebase/v00.00.00000/services/firebasestorage.yaml
    title: Cloud Storage for Firebase API
    version: v00.00.00000
  toolresults:
    description: API to publish and access results from developer tools.
    id: toolresults:v00.00.00000
    name: toolresults
    preferred: true
    service:
      $ref: firebase/v00.00.00000/services/toolresults.yaml
    title: Cloud Tool Results API
    version: v00.00.00000
openapi: 3.1.0
