openapi: 3.0.0
servers:
  - url: https://management.azure.com/
info:
  title: Microsoft Addons
  description: The service for managing third party addons.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2024-10-18-stackql-generated
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  parameters:
    SubscriptionIdParameter:
      name: subscriptionId
      in: path
      description: Subscription credentials that uniquely identify the Microsoft Azure subscription. The subscription ID forms part of the URI for every service call.
      required: true
      schema:
        type: string
    ApiVersionParameter:
      name: api-version
      in: query
      description: Client API version.
      required: false
      schema:
        type: string
    SupportProviderName:
      name: providerName
      in: path
      description: The support plan type. For now the only valid type is "canonical".
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    CanonicalSupportPlanType:
      name: planTypeName
      in: path
      description: The Canonical support plan type.
      required: true
      x-ms-parameter-location: method
      schema:
        enum:
          - Essential
          - Standard
          - Advanced
        x-ms-enum:
          name: PlanTypeName
          modelAsString: true
        type: string
    OperationResultsIdParameter:
      name: operationResultsId
      in: path
      description: The id representing an async operation.
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
  schemas:
    CanonicalSupportPlanProperties:
      type: object
      description: The properties of the Canonical support plan.
      properties:
        provisioningState:
          type: string
          description: The provisioning state of the resource.
          enum:
            - Succeeded
            - Failed
            - Cancelled
            - Purchasing
            - Downgrading
            - Cancelling
            - Upgrading
          x-ms-enum:
            name: ProvisioningState
            modelAsString: true
    CanonicalSupportPlanResponseEnvelope:
      description: The status of the Canonical support plan.
      required:
        - properties
      x-ms-azure-resource: true
      properties:
        id:
          readOnly: true
          type: string
          description: The id of the ARM resource, e.g. "/subscriptions/{id}/providers/Microsoft.Addons/supportProvider/{supportProviderName}/supportPlanTypes/{planTypeName}".
        name:
          readOnly: true
          type: string
          description: The name of the Canonical support plan, i.e. "essential", "standard" or "advanced".
        type:
          readOnly: true
          type: string
          description: Microsoft.Addons/supportProvider
        properties:
          type: object
          $ref: '#/components/schemas/CanonicalSupportPlanProperties'
          description: Describes Canonical support plan type and status.
          x-ms-client-flatten: true
      type: object
    CanonicalSupportPlanInfo:
      type: array
      title: Canonical Support Plan Info
      description: The status of all Canonical support plans for a subscription.
      items:
        $ref: '#/components/schemas/CanonicalSupportPlanInfoDefinition'
      x-ms-identifiers: []
    CanonicalSupportPlanInfoDefinition:
      type: object
      description: Definition object with the properties of a canonical plan
      properties:
        supportPlanType:
          type: string
          description: Support plan type.
          enum:
            - essential
            - standard
            - advanced
          x-ms-enum:
            name: SupportPlanType
            modelAsString: true
        enabled:
          type: boolean
          description: Flag to indicate if this support plan type is currently enabled for the subscription.
        oneTimeCharge:
          type: string
          description: The one time charge status for the subscription.
          enum:
            - 'no'
            - onEnabled
            - onReenabled
          x-ms-enum:
            name: OneTimeCharge
            modelAsString: true
    OperationListValue:
      type: object
      description: List of supported operations.
      properties:
        value:
          $ref: '#/components/schemas/OperationList'
    OperationList:
      type: array
      description: List of supported operations.
      items:
        $ref: '#/components/schemas/OperationsDefinition'
      x-ms-identifiers:
        - name
    OperationsDefinition:
      type: object
      description: Definition object with the name and properties of an operation.
      properties:
        name:
          type: string
          description: Name of the operation.
        display:
          $ref: '#/components/schemas/OperationsDisplayDefinition'
          description: Display object with properties of the operation.
    OperationsDisplayDefinition:
      type: object
      description: Display object with properties of the operation.
      properties:
        provider:
          type: string
          description: Resource provider of the operation.
        resource:
          type: string
          description: Resource for the operation.
        operation:
          type: string
          description: Short description of the operation.
        description:
          type: string
          description: Description of the operation.
    ErrorDefinition:
      type: object
      title: Error
      description: Error description and code explaining why an operation failed.
      required:
        - message
        - code
      properties:
        message:
          type: string
          description: Description of the error.
        code:
          type: string
          description: Service specific error code which serves as the substatus for the HTTP error code.
  x-stackQL-resources:
    operations:
      id: azure_extras.addons.operations
      name: operations
      title: operations
      methods:
        list:
          operation:
            $ref: '#/paths/~1providers~1Microsoft.Addons~1operations?api-version=2018-03-01/get'
            operationId: Operations_List
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            schemaRef: OperationListValue
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/operations/methods/list'
        insert: []
        update: []
        replace: []
        delete: []
    support_plan_types:
      id: azure_extras.addons.support_plan_types
      name: support_plan_types
      title: support_plan_types
      methods:
        get:
          operation:
            $ref: '#/paths/~1subscriptions~1{subscriptionId}~1providers~1Microsoft.Addons~1supportProviders~1{providerName}~1supportPlanTypes~1{planTypeName}?api-version=2018-03-01/get'
            operationId: SupportPlanTypes_Get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            schemaRef: CanonicalSupportPlanResponseEnvelope
        create_or_update:
          operation:
            $ref: '#/paths/~1subscriptions~1{subscriptionId}~1providers~1Microsoft.Addons~1supportProviders~1{providerName}~1supportPlanTypes~1{planTypeName}?api-version=2018-03-01/put'
            operationId: SupportPlanTypes_CreateOrUpdate
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            schemaRef: CanonicalSupportPlanResponseEnvelope
        delete:
          operation:
            $ref: '#/paths/~1subscriptions~1{subscriptionId}~1providers~1Microsoft.Addons~1supportProviders~1{providerName}~1supportPlanTypes~1{planTypeName}?api-version=2018-03-01/delete'
            operationId: SupportPlanTypes_Delete
          response:
            mediaType: application/json
            openAPIDocKey: '202'
            schemaRef: CanonicalSupportPlanResponseEnvelope
        list_info:
          operation:
            $ref: '#/paths/~1subscriptions~1{subscriptionId}~1providers~1Microsoft.Addons~1supportProviders~1canonical~1listSupportPlanInfo?api-version=2018-03-01/post'
            operationId: SupportPlanTypes_ListInfo
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            schemaRef: CanonicalSupportPlanInfo
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/support_plan_types/methods/get'
          - $ref: '#/components/x-stackQL-resources/support_plan_types/methods/list_info'
        insert:
          - $ref: '#/components/x-stackQL-resources/support_plan_types/methods/create_or_update'
        update: []
        replace: []
        delete:
          - $ref: '#/components/x-stackQL-resources/support_plan_types/methods/delete'
    vw_support_plan_types:
      id: azure_extras.addons.vw_support_plan_types
      name: vw_support_plan_types
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              id as id,
              name as name,
              type as type,
              JSON_EXTRACT(properties, '$.provisioningState') as "provisioning_state",
              subscriptionId,
              providerName,
              planTypeName
              FROM azure_extras.addons.support_plan_types
              WHERE subscriptionId = 'replace-me';
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                id as id,
                name as name,
                type as type,
                json_extract_path_text(properties, '$.provisioningState') as "provisioning_state",
                subscriptionId,
                providerName,
                planTypeName
                FROM azure_extras.addons.support_plan_types
                WHERE subscriptionId = 'replace-me';
paths:
  /providers/Microsoft.Addons/operations?api-version=2018-03-01:
    get:
      tags:
        - Operations
      operationId: Operations_List
      description: Lists all of the available Addons RP operations.
      parameters: []
      responses:
        '200':
          description: List all the operations.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationListValue'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDefinition'
  /subscriptions/{subscriptionId}/providers/Microsoft.Addons/supportProviders/{providerName}/supportPlanTypes/{planTypeName}?api-version=2018-03-01:
    get:
      tags:
        - AddonDetails
      operationId: SupportPlanTypes_Get
      description: Returns whether or not the canonical support plan of type {type} is enabled for the subscription.
      parameters:
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/SupportProviderName'
        - $ref: '#/components/parameters/CanonicalSupportPlanType'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CanonicalSupportPlanResponseEnvelope'
        '404':
          description: Not Found
        default:
          description: |-
            '404' - 'Not Found'.
            '400' - 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDefinition'
    put:
      tags:
        - AddonDetails
      operationId: SupportPlanTypes_CreateOrUpdate
      description: Creates or updates the Canonical support plan of type {type} for the subscription.
      x-ms-long-running-operation: true
      parameters:
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/SupportProviderName'
        - $ref: '#/components/parameters/CanonicalSupportPlanType'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CanonicalSupportPlanResponseEnvelope'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CanonicalSupportPlanResponseEnvelope'
        '404':
          description: Not Found
        default:
          description: |-
            '404' - 'Not Found'.
            '400' - 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDefinition'
    delete:
      operationId: SupportPlanTypes_Delete
      description: Cancels the Canonical support plan of type {type} for the subscription.
      x-ms-long-running-operation: true
      parameters:
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/SupportProviderName'
        - $ref: '#/components/parameters/CanonicalSupportPlanType'
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CanonicalSupportPlanResponseEnvelope'
          headers: {}
        '204':
          description: No Content
        default:
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDefinition'
  /subscriptions/{subscriptionId}/providers/Microsoft.Addons/supportProviders/canonical/listSupportPlanInfo?api-version=2018-03-01:
    post:
      tags:
        - AddonStatus
      operationId: SupportPlanTypes_ListInfo
      description: Returns the canonical support plan information for all types for the subscription.
      parameters:
        - $ref: '#/components/parameters/SubscriptionIdParameter'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CanonicalSupportPlanInfo'
        '404':
          description: Not Found
        default:
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDefinition'
