openapi: 3.0.0
servers:
  - url: https://management.azure.com/
info:
  title: Microsoft Management Partner
  description: Partner Admin Link (PAL) associations between partners and Azure credentials.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2018-02-01-stackql-generated
  x-serviceAlias: management_partner
  x-sdkPackage: azure-mgmt-managementpartner
  x-plane: mgmt
security:
  - azure_auth:
      - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    OperationDisplay:
      type: object
      description: this is the management partner operation.
      properties:
        provider:
          type: string
          description: the is management partner provider.
        resource:
          type: string
          description: the is management partner resource.
        operation:
          type: string
          description: the is management partner operation.
        description:
          type: string
          description: the is management partner operation description.
    OperationResponse:
      type: object
      description: this is the management partner operations response.
      properties:
        name:
          type: string
          description: this is the operation response name.
        display:
          $ref: "#/components/schemas/OperationDisplay"
          description: this is the operation display.
        origin:
          type: string
          description: the is operation response origin information.
    PagedOperationResponse:
      type: object
      properties:
        value:
          type: array
          items:
            $ref: "#/components/schemas/OperationResponse"
        nextLink:
          type: string
    PartnerResponseFlattened:
      type: object
      description: Flattened view of PartnerResponse ('properties' hoisted to the top level).
      properties:
        etag:
          type: integer
          description: Type of the partner.
        id:
          type: string
          description: Identifier of the partner.
        name:
          type: string
          description: Name of the partner.
        type:
          type: string
          description: Type of resource. "Microsoft.ManagementPartner/partners".
        partnerId:
          type: string
          description: This is the partner id.
        partnerName:
          type: string
          description: This is the partner name.
        tenantId:
          type: string
          description: This is the tenant id.
        objectId:
          type: string
          description: This is the object id.
        version:
          type: integer
          description: This is the version.
        updatedTime:
          type: string
          format: date-time
          description: This is the DateTime when the partner was updated.
        createdTime:
          type: string
          format: date-time
          description: This is the DateTime when the partner was created.
        state:
          type: string
          description: 'This is the partner state. Known values are: "Active" and "Deleted".'
    PartnerResponse:
      type: object
      description: this is the management partner operations response. Variables are only populated by the server, and will be ignored when sending a request.
      properties:
        etag:
          type: integer
          description: Type of the partner.
        id:
          type: string
          description: Identifier of the partner.
        name:
          type: string
          description: Name of the partner.
        type:
          type: string
          description: Type of resource. "Microsoft.ManagementPartner/partners".
        properties:
          type: object
          properties:
            partnerId:
              type: string
              description: This is the partner id.
            partnerName:
              type: string
              description: This is the partner name.
            tenantId:
              type: string
              description: This is the tenant id.
            objectId:
              type: string
              description: This is the object id.
            version:
              type: integer
              description: This is the version.
            updatedTime:
              type: string
              format: date-time
              description: This is the DateTime when the partner was updated.
            createdTime:
              type: string
              format: date-time
              description: This is the DateTime when the partner was created.
            state:
              type: string
              description: 'This is the partner state. Known values are: "Active" and "Deleted".'
  x-stackQL-resources:
    operation:
      id: azure_extras.management_partner.operation
      name: operation
      title: operation
      methods:
        list:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.ManagementPartner~1operations?api-version=2018-02-01/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.value
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/operation/methods/list"
        insert: []
        update: []
        delete: []
    partner:
      id: azure_extras.management_partner.partner
      name: partner
      title: partner
      methods:
        get:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.ManagementPartner~1partners~1{partner_id}?api-version=2018-02-01/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            overrideMediaType: application/json
            transform:
              type: golang_template_json_v0.3.0
              body: '{{ $row := . }}{ {{ $p := index $row "properties" }}{{ if eq (kindOf $p) "map" }}{{ range $k, $v := $p }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}{{ end }}{{ range $k, $v := $row }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}"_flattened": true }'
        create:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.ManagementPartner~1partners~1{partner_id}?api-version=2018-02-01/put"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        update:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.ManagementPartner~1partners~1{partner_id}?api-version=2018-02-01/patch"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        delete:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.ManagementPartner~1partners~1{partner_id}?api-version=2018-02-01/delete"
          response:
            openAPIDocKey: "204"
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/partner/methods/get"
        insert:
          - $ref: "#/components/x-stackQL-resources/partner/methods/create"
        update:
          - $ref: "#/components/x-stackQL-resources/partner/methods/update"
        delete:
          - $ref: "#/components/x-stackQL-resources/partner/methods/delete"
    partners:
      id: azure_extras.management_partner.partners
      name: partners
      title: partners
      methods:
        get:
          operation:
            $ref: "#/paths/~1providers~1Microsoft.ManagementPartner~1partners?api-version=2018-02-01/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            overrideMediaType: application/json
            transform:
              type: golang_template_json_v0.3.0
              body: '{{ $row := . }}{ {{ $p := index $row "properties" }}{{ if eq (kindOf $p) "map" }}{{ range $k, $v := $p }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}{{ end }}{{ range $k, $v := $row }}{{ printf "%q" $k }}: {{ toJson $v }}, {{ end }}"_flattened": true }'
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/partners/methods/get"
        insert: []
        update: []
        delete: []
paths:
  /providers/Microsoft.ManagementPartner/operations?api-version=2018-02-01:
    get:
      operationId: Operation_list
      description: Get operations. List all the operations.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagedOperationResponse"
  /providers/Microsoft.ManagementPartner/partners/{partner_id}?api-version=2018-02-01:
    get:
      operationId: Partner_get
      description: Get a specific `Partner`. Get the management partner using the partnerId, objectId and tenantId.
      parameters:
        - name: partner_id
          in: path
          required: true
          schema:
            type: string
          description: Id of the Partner. Required.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartnerResponseFlattened"
    put:
      operationId: Partner_create
      description: Create a specific `Partner`. Create a management partner for the objectId and tenantId.
      parameters:
        - name: partner_id
          in: path
          required: true
          schema:
            type: string
          description: Id of the Partner. Required.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartnerResponse"
    patch:
      operationId: Partner_update
      description: Update a specific `Partner`. Update the management partner for the objectId and tenantId.
      parameters:
        - name: partner_id
          in: path
          required: true
          schema:
            type: string
          description: Id of the Partner. Required.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartnerResponse"
    delete:
      operationId: Partner_delete
      description: Delete a specific `Partner`. Delete the management partner for the objectId and tenantId.
      parameters:
        - name: partner_id
          in: path
          required: true
          schema:
            type: string
          description: Id of the Partner. Required.
      responses:
        "204":
          description: Success (no content / accepted)
  /providers/Microsoft.ManagementPartner/partners?api-version=2018-02-01:
    get:
      operationId: Partners_get
      description: Get a specific `Partner`. Get the management partner using the objectId and tenantId.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PartnerResponseFlattened"
