components:
  schemas:
    SmsTemplate:
      properties:
        created:
          format: date-time
          readOnly: true
          type: string
        id:
          readOnly: true
          type: string
        lastUpdated:
          format: date-time
          readOnly: true
          type: string
        name:
          type: string
        template:
          type: string
        translations:
          $ref: '#/components/schemas/SmsTemplateTranslations'
        type:
          $ref: '#/components/schemas/SmsTemplateType'
      type: object
      x-okta-crud:
      - alias: create
        arguments:
        - dest: smsTemplate
          self: true
        operationId: createSmsTemplate
      - alias: read
        arguments: []
        operationId: getSmsTemplate
      - alias: update
        arguments:
        - dest: templateId
          src: id
        - dest: smsTemplate
          self: true
        operationId: updateSmsTemplate
      - alias: delete
        arguments:
        - dest: templateId
          src: id
        operationId: deleteSmsTemplate
      x-okta-operations:
      - alias: partialUpdate
        arguments:
        - dest: templateId
          src: id
        - dest: smsTemplate
          self: true
        operationId: partialUpdateSmsTemplate
      x-okta-tags:
      - Template
    SmsTemplateTranslations:
      type: object
      x-okta-extensible: true
      x-okta-tags:
      - Template
    SmsTemplateType:
      enum:
      - SMS_VERIFY_CODE
      type: string
      x-okta-tags:
      - Template
  securitySchemes:
    api_token:
      description: SSWS {API Token}
      in: header
      name: Authorization
      type: apiKey
  x-stackQL-resources:
    sms:
      id: okta.template.sms
      methods:
        delete:
          operation:
            $ref: '#/paths/~1api~1v1~1templates~1sms~1{templateId}/DELETE'
          response:
            openAPIDocKey: '204'
        get:
          operation:
            $ref: '#/paths/~1api~1v1~1templates~1sms~1{templateId}/GET'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        insert:
          operation:
            $ref: '#/paths/~1api~1v1~1templates~1sms/POST'
          request:
            mediaType: application/json
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        list:
          operation:
            $ref: '#/paths/~1api~1v1~1templates~1sms/GET'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        partialUpdate:
          operation:
            $ref: '#/paths/~1api~1v1~1templates~1sms~1{templateId}/POST'
          request:
            mediaType: application/json
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        update:
          operation:
            $ref: '#/paths/~1api~1v1~1templates~1sms~1{templateId}/PUT'
          request:
            mediaType: application/json
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      name: sms
      title: sms
externalDocs:
  description: Find more info here
  url: https://developer.okta.com/docs/api/getting_started/design_principles.html
info:
  contact:
    email: devex-public@okta.com
    name: Okta Developer Team
    url: https://developer.okta.com/
  description: Allows customers to easily access the Okta API
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developer.okta.com/terms/
  title: Okta API
  version: 2.8.0
openapi: 3.0.1
paths:
  /api/v1/templates/sms:
    get:
      description: Enumerates custom SMS templates in your organization. A subset
        of templates can be returned that match a template type.
      operationId: listSmsTemplates
      parameters:
      - in: query
        name: templateType
        schema:
          type: string
          x-openapi-v3-schema-ref: '#/components/schemas/SmsTemplateType'
        x-openapi-v3-schema-ref: '#/components/schemas/SmsTemplateType'
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SmsTemplate'
                type: array
          description: Success
      security:
      - api_token: []
      summary: List SMS Templates
      tags:
      - Template
    post:
      description: Adds a new custom SMS template to your organization.
      operationId: createSmsTemplate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmsTemplate'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsTemplate'
          description: Success
      security:
      - api_token: []
      summary: Add SMS Template
      tags:
      - Template
      x-codegen-request-body-name: smsTemplate
  /api/v1/templates/sms/{templateId}:
    delete:
      description: Removes an SMS template.
      operationId: deleteSmsTemplate
      parameters:
      - in: path
        name: templateId
        required: true
        schema:
          type: string
      responses:
        '204':
          content: {}
          description: No Content
      security:
      - api_token: []
      summary: Remove SMS Template
      tags:
      - Template
    get:
      description: Fetches a specific template by `id`
      operationId: getSmsTemplate
      parameters:
      - in: path
        name: templateId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsTemplate'
          description: Success
      security:
      - api_token: []
      summary: Get SMS Template
      tags:
      - Template
    post:
      description: 'Updates only some of the SMS template properties:'
      operationId: partialUpdateSmsTemplate
      parameters:
      - in: path
        name: templateId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmsTemplate'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsTemplate'
          description: Success
      security:
      - api_token: []
      summary: Partial SMS Template Update
      tags:
      - Template
      x-codegen-request-body-name: smsTemplate
    put:
      description: Updates the SMS template.
      operationId: updateSmsTemplate
      parameters:
      - in: path
        name: templateId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SmsTemplate'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SmsTemplate'
          description: Success
      security:
      - api_token: []
      summary: Update SMS Template
      tags:
      - Template
      x-codegen-request-body-name: smsTemplate
servers:
- url: https://{subdomain}.okta.com/
  variables:
    subdomain:
      default: my-domain
