openapi: 3.1.0
info:
  contact:
    name: StackQL Studios
    url: https://github.com/stackql/google-discovery-to-openapi
    email: info@stackql.io
  title: Local Services API
  description: ''
  version: v1
  x-discovery-doc-revision: '20230104'
  x-generated-date: '2023-01-06'
externalDocs:
  url: https://ads.google.com/local-services-ads/
servers:
  - url: https://localservices.googleapis.com
components:
  schemas:
    GoogleTypeTimeZone:
      description: Represents a time zone from the [IANA Time Zone Database](https://www.iana.org/time-zones).
      id: GoogleTypeTimeZone
      properties:
        version:
          description: Optional. IANA Time Zone Database version number, e.g. "2019a".
          type: string
        id:
          type: string
          description: IANA Time Zone Database time zone, e.g. "America/New_York".
      type: object
    GoogleAdsHomeservicesLocalservicesV1AggregatorInfo:
      properties:
        aggregatorProviderId:
          type: string
          description: Provider id (listed in aggregator system) which maps to a account id in GLS system.
      type: object
      id: GoogleAdsHomeservicesLocalservicesV1AggregatorInfo
      description: Conatiner for aggregator specific information if lead is for an aggregator GLS account.
    GoogleAdsHomeservicesLocalservicesV1DetailedLeadReport:
      id: GoogleAdsHomeservicesLocalservicesV1DetailedLeadReport
      type: object
      properties:
        messageLead:
          $ref: '#/components/schemas/GoogleAdsHomeservicesLocalservicesV1MessageLead'
          description: More information associated to only message leads.
        leadPrice:
          description: Price of the lead (available only after it has been charged).
          format: double
          type: number
        accountId:
          format: int64
          type: string
          description: Identifies account that received the lead.
        timezone:
          $ref: '#/components/schemas/GoogleTypeTimeZone'
          description: Timezone of the particular provider associated to a lead.
        leadCreationTimestamp:
          description: Timestamp of when the lead was created.
          type: string
          format: google-datetime
        disputeStatus:
          description: Dispute status related to the lead.
          type: string
        phoneLead:
          $ref: '#/components/schemas/GoogleAdsHomeservicesLocalservicesV1PhoneLead'
          description: More information associated to only phone leads.
        leadId:
          description: Unique identifier of a Detailed Lead Report.
          format: int64
          type: string
        businessName:
          type: string
          description: Business name associated to the account.
        leadType:
          enumDescriptions:
            - Not specified.
            - Message lead.
            - Phone call lead.
            - Booking lead.
          description: Lead type.
          type: string
          enum:
            - LEAD_TYPE_UNSPECIFIED
            - MESSAGE
            - PHONE_CALL
            - BOOKING
        leadCategory:
          type: string
          description: Lead category (e.g. hvac, plumber)
        aggregatorInfo:
          description: Aggregator specific information related to the lead.
          $ref: '#/components/schemas/GoogleAdsHomeservicesLocalservicesV1AggregatorInfo'
        geo:
          description: Location of the associated account's home city.
          type: string
        bookingLead:
          description: More information associated to only booking leads.
          $ref: '#/components/schemas/GoogleAdsHomeservicesLocalservicesV1BookingLead'
        currencyCode:
          type: string
          description: Currency code.
        chargeStatus:
          enumDescriptions:
            - Not specified.
            - Charged.
            - Not charged.
          enum:
            - CHARGE_STATUS_UNSPECIFIED
            - CHARGED
            - NOT_CHARGED
          type: string
          description: Whether the lead has been charged.
      description: A Detailed Lead Report of a lead identified by their lead id and contains consumer, account, monetization, and lead data.
    GoogleAdsHomeservicesLocalservicesV1BookingLead:
      type: object
      properties:
        bookingAppointmentTimestamp:
          format: google-datetime
          description: Timestamp of when service is provided by advertiser.
          type: string
        consumerPhoneNumber:
          description: Consumer phone number associated with the booking lead.
          type: string
        customerName:
          description: Name of the customer who created the lead.
          type: string
        consumerEmail:
          description: Consumer email associated with the booking lead.
          type: string
        jobType:
          type: string
          description: The job type of the specified lead.
      description: Container for booking lead specific information.
      id: GoogleAdsHomeservicesLocalservicesV1BookingLead
    GoogleAdsHomeservicesLocalservicesV1PhoneLead:
      id: GoogleAdsHomeservicesLocalservicesV1PhoneLead
      description: Container for phone lead specific information.
      properties:
        chargedCallTimestamp:
          type: string
          description: Timestamp of the phone call which resulted in a charged phone lead.
          format: google-datetime
        chargedConnectedCallDurationSeconds:
          format: google-duration
          type: string
          description: Duration of the charged phone call in seconds.
        consumerPhoneNumber:
          description: Consumer phone number associated with the phone lead.
          type: string
      type: object
    GoogleAdsHomeservicesLocalservicesV1SearchAccountReportsResponse:
      description: A page of the response received from the SearchAccountReports method. A paginated response where more pages are available has `next_page_token` set. This token can be used in a subsequent request to retrieve the next request page.
      id: GoogleAdsHomeservicesLocalservicesV1SearchAccountReportsResponse
      type: object
      properties:
        nextPageToken:
          description: Pagination token to retrieve the next page of results. When `next_page_token` is not filled in, there is no next page and the list returned is the last page in the result set.
          type: string
        accountReports:
          type: array
          description: List of account reports which maps 1:1 to a particular linked GLS account.
          items:
            $ref: '#/components/schemas/GoogleAdsHomeservicesLocalservicesV1AccountReport'
    GoogleAdsHomeservicesLocalservicesV1MessageLead:
      id: GoogleAdsHomeservicesLocalservicesV1MessageLead
      properties:
        customerName:
          description: Name of the customer who created the lead.
          type: string
        consumerPhoneNumber:
          description: Consumer phone number associated with the message lead.
          type: string
        postalCode:
          description: The postal code of the customer who created the lead.
          type: string
        jobType:
          type: string
          description: The job type of the specified lead.
      description: Container for message lead specific information.
      type: object
    GoogleAdsHomeservicesLocalservicesV1SearchDetailedLeadReportsResponse:
      description: A page of the response received from the SearchDetailedLeadReports method. A paginated response where more pages are available has `next_page_token` set. This token can be used in a subsequent request to retrieve the next request page.
      id: GoogleAdsHomeservicesLocalservicesV1SearchDetailedLeadReportsResponse
      properties:
        detailedLeadReports:
          items:
            $ref: '#/components/schemas/GoogleAdsHomeservicesLocalservicesV1DetailedLeadReport'
          type: array
          description: List of detailed lead reports uniquely identified by external lead id.
        nextPageToken:
          type: string
          description: Pagination token to retrieve the next page of results. When `next_page_token` is not filled in, there is no next page and the list returned is the last page in the result set.
      type: object
    GoogleAdsHomeservicesLocalservicesV1AccountReport:
      properties:
        previousPeriodChargedLeads:
          description: Number of charged leads the account received in previous specified period.
          format: int64
          type: string
        businessName:
          description: Business name of the account.
          type: string
        totalReview:
          format: int32
          type: integer
          description: Total number of reviews the account has up to current date.
        impressionsLastTwoDays:
          description: Number of impressions that customers have had in the past 2 days.
          type: string
          format: int64
        averageWeeklyBudget:
          format: double
          description: Average weekly budget in the currency code of the account.
          type: number
        averageFiveStarRating:
          type: number
          format: double
          description: Average review rating score from 1-5 stars.
        previousPeriodConnectedPhoneCalls:
          description: Number of connected phone calls (duration over 30s) in previous specified period.
          type: string
          format: int64
        phoneLeadResponsiveness:
          type: number
          description: Phone lead responsiveness of the account for the past 90 days from current date. This is computed by taking the total number of connected calls from charged phone leads and dividing by the total number of calls received.
          format: double
        currentPeriodPhoneCalls:
          type: string
          description: Number of phone calls in current specified period, including both connected and unconnected calls.
          format: int64
        currencyCode:
          type: string
          description: Currency code of the account.
        previousPeriodPhoneCalls:
          description: Number of phone calls in previous specified period, including both connected and unconnected calls.
          type: string
          format: int64
        aggregatorInfo:
          description: Aggregator specific information related to the account.
          $ref: '#/components/schemas/GoogleAdsHomeservicesLocalservicesV1AggregatorInfo'
        accountId:
          type: string
          description: Unique identifier of the GLS account.
          format: int64
        currentPeriodConnectedPhoneCalls:
          format: int64
          description: Number of connected phone calls (duration over 30s) in current specified period.
          type: string
        currentPeriodTotalCost:
          format: double
          description: Total cost of the account in current specified period in the account's specified currency.
          type: number
        previousPeriodTotalCost:
          description: Total cost of the account in previous specified period in the account's specified currency.
          format: double
          type: number
        currentPeriodChargedLeads:
          format: int64
          type: string
          description: Number of charged leads the account received in current specified period.
      description: 'An Account Report of a GLS account identified by their account id containing aggregate data gathered from a particular date range. Next ID: 18'
      id: GoogleAdsHomeservicesLocalservicesV1AccountReport
      type: object
  parameters:
    _.xgafv:
      description: V1 error format.
      in: query
      name: _.xgafv
      schema:
        type: string
        enum:
          - '1'
          - '2'
    quotaUser:
      description: Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters.
      in: query
      name: quotaUser
      schema:
        type: string
    uploadType:
      description: Legacy upload protocol for media (e.g. "media", "multipart").
      in: query
      name: uploadType
      schema:
        type: string
    access_token:
      description: OAuth access token.
      in: query
      name: access_token
      schema:
        type: string
    prettyPrint:
      description: Returns response with indentations and line breaks.
      in: query
      name: prettyPrint
      schema:
        type: boolean
    alt:
      description: Data format for response.
      in: query
      name: alt
      schema:
        type: string
        enum:
          - json
          - media
          - proto
    fields:
      description: Selector specifying which fields to include in a partial response.
      in: query
      name: fields
      schema:
        type: string
    key:
      description: API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.
      in: query
      name: key
      schema:
        type: string
    callback:
      description: JSONP
      in: query
      name: callback
      schema:
        type: string
    upload_protocol:
      description: Upload protocol for media (e.g. "raw", "multipart").
      in: query
      name: upload_protocol
      schema:
        type: string
    oauth_token:
      description: OAuth 2.0 token for the current user.
      in: query
      name: oauth_token
      schema:
        type: string
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes: &ref_0
            https://www.googleapis.com/auth/adwords: See, edit, create, and delete your Google Ads accounts and data.
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorization code authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes: *ref_0
  x-stackQL-resources:
    account_reports:
      id: googleads.localservices.account_reports
      name: account_reports
      title: Account_reports
      methods:
        accountReports_search:
          operation:
            $ref: '#/paths/~1v1~1accountReports:search/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
    detailed_lead_reports:
      id: googleads.localservices.detailed_lead_reports
      name: detailed_lead_reports
      title: Detailed_lead_reports
      methods:
        detailedLeadReports_search:
          operation:
            $ref: '#/paths/~1v1~1detailedLeadReports:search/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
paths:
  /v1/accountReports:search:
    parameters: &ref_1
      - $ref: '#/components/parameters/_.xgafv'
      - $ref: '#/components/parameters/quotaUser'
      - $ref: '#/components/parameters/uploadType'
      - $ref: '#/components/parameters/access_token'
      - $ref: '#/components/parameters/prettyPrint'
      - $ref: '#/components/parameters/alt'
      - $ref: '#/components/parameters/fields'
      - $ref: '#/components/parameters/key'
      - $ref: '#/components/parameters/callback'
      - $ref: '#/components/parameters/upload_protocol'
      - $ref: '#/components/parameters/oauth_token'
    get:
      description: Get account reports containing aggregate account data of all linked GLS accounts. Caller needs to provide their manager customer id and the associated auth credential that allows them read permissions on their linked accounts.
      operationId: localservices.accountReports.search
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adwords
          Oauth2c:
            - https://www.googleapis.com/auth/adwords
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleAdsHomeservicesLocalservicesV1SearchAccountReportsResponse'
      parameters:
        - in: query
          name: endDate.day
          schema:
            type: integer
        - in: query
          name: endDate.month
          schema:
            type: integer
        - in: query
          name: startDate.year
          schema:
            type: integer
        - in: query
          name: startDate.day
          schema:
            type: integer
        - in: query
          name: query
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: startDate.month
          schema:
            type: integer
        - in: query
          name: endDate.year
          schema:
            type: integer
        - in: query
          name: pageToken
          schema:
            type: string
      x-stackQL-resource: account_reports
      x-stackQL-verb: exec
  /v1/detailedLeadReports:search:
    parameters: *ref_1
    get:
      description: Get detailed lead reports containing leads that have been received by all linked GLS accounts. Caller needs to provide their manager customer id and the associated auth credential that allows them read permissions on their linked accounts.
      operationId: localservices.detailedLeadReports.search
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adwords
          Oauth2c:
            - https://www.googleapis.com/auth/adwords
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleAdsHomeservicesLocalservicesV1SearchDetailedLeadReportsResponse'
      parameters:
        - in: query
          name: pageToken
          schema:
            type: string
        - in: query
          name: startDate.month
          schema:
            type: integer
        - in: query
          name: endDate.month
          schema:
            type: integer
        - in: query
          name: startDate.day
          schema:
            type: integer
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: startDate.year
          schema:
            type: integer
        - in: query
          name: query
          schema:
            type: string
        - in: query
          name: endDate.day
          schema:
            type: integer
        - in: query
          name: endDate.year
          schema:
            type: integer
      x-stackQL-resource: detailed_lead_reports
      x-stackQL-verb: exec
