id: k8s
name: k8s
version: v00.00.00000
providerServices:
  admissionregistration:
    id: admissionregistration:v00.00.00000
    name: admissionregistration
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/admissionregistration.yaml
    title: admissionregistration API
    version: v00.00.00000
    description: k8s admissionregistration API
  apiextensions:
    id: apiextensions:v00.00.00000
    name: apiextensions
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/apiextensions.yaml
    title: apiextensions API
    version: v00.00.00000
    description: k8s apiextensions API
  apiregistration:
    id: apiregistration:v00.00.00000
    name: apiregistration
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/apiregistration.yaml
    title: apiregistration API
    version: v00.00.00000
    description: k8s apiregistration API
  apps:
    id: apps:v00.00.00000
    name: apps
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/apps.yaml
    title: apps API
    version: v00.00.00000
    description: k8s apps API
  authentication:
    id: authentication:v00.00.00000
    name: authentication
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/authentication.yaml
    title: authentication API
    version: v00.00.00000
    description: k8s authentication API
  authorization:
    id: authorization:v00.00.00000
    name: authorization
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/authorization.yaml
    title: authorization API
    version: v00.00.00000
    description: k8s authorization API
  autoscaling:
    id: autoscaling:v00.00.00000
    name: autoscaling
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/autoscaling.yaml
    title: autoscaling API
    version: v00.00.00000
    description: k8s autoscaling API
  batch:
    id: batch:v00.00.00000
    name: batch
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/batch.yaml
    title: batch API
    version: v00.00.00000
    description: k8s batch API
  certificates:
    id: certificates:v00.00.00000
    name: certificates
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/certificates.yaml
    title: certificates API
    version: v00.00.00000
    description: k8s certificates API
  coordination:
    id: coordination:v00.00.00000
    name: coordination
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/coordination.yaml
    title: coordination API
    version: v00.00.00000
    description: k8s coordination API
  core:
    id: core:v00.00.00000
    name: core
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/core.yaml
    title: core API
    version: v00.00.00000
    description: k8s core API
  discovery:
    id: discovery:v00.00.00000
    name: discovery
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/discovery.yaml
    title: discovery API
    version: v00.00.00000
    description: k8s discovery API
  events:
    id: events:v00.00.00000
    name: events
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/events.yaml
    title: events API
    version: v00.00.00000
    description: k8s events API
  flowcontrol:
    id: flowcontrol:v00.00.00000
    name: flowcontrol
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/flowcontrol.yaml
    title: flowcontrol API
    version: v00.00.00000
    description: k8s flowcontrol API
  networking:
    id: networking:v00.00.00000
    name: networking
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/networking.yaml
    title: networking API
    version: v00.00.00000
    description: k8s networking API
  node:
    id: node:v00.00.00000
    name: node
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/node.yaml
    title: node API
    version: v00.00.00000
    description: k8s node API
  policy:
    id: policy:v00.00.00000
    name: policy
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/policy.yaml
    title: policy API
    version: v00.00.00000
    description: k8s policy API
  rbac:
    id: rbac:v00.00.00000
    name: rbac
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/rbac.yaml
    title: rbac API
    version: v00.00.00000
    description: k8s rbac API
  scheduling:
    id: scheduling:v00.00.00000
    name: scheduling
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/scheduling.yaml
    title: scheduling API
    version: v00.00.00000
    description: k8s scheduling API
  storage:
    id: storage:v00.00.00000
    name: storage
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/storage.yaml
    title: storage API
    version: v00.00.00000
    description: k8s storage API
config:
  auth:
    type: null_auth
  snake_case_aliases: true
