id: k8s
name: k8s
version: v00.00.00000
providerServices:
  admissionregistration:
    description: admission registration
    id: admissionregistration:v00.00.00000
    name: admissionregistration
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/admissionregistration.yaml
    title: Kubernetes - admissionregistration
    version: v00.00.00000
  admissionregistration_v1:
    description: admissionregistration_v1
    id: admissionregistration_v1:v00.00.00000
    name: admissionregistration_v1
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/admissionregistration_v1.yaml
    title: Kubernetes - admissionregistration_v1
    version: v00.00.00000
  apiextensions:
    description: apiextensions
    id: apiextensions:v00.00.00000
    name: apiextensions
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/apiextensions.yaml
    title: Kubernetes - apiextensions
    version: v00.00.00000
  core:
    description: core
    id: core:v00.00.00000
    name: core
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/core.yaml
    title: Kubernetes - core
    version: v00.00.00000
  core_v1:
    description: core_v1
    id: core_v1:v00.00.00000
    name: core_v1
    preferred: true
    service:
      $ref: k8s/v00.00.00000/services/core_v1.yaml
    title: Kubernetes - core_v1
    version: v00.00.00000
openapi: 3.0.0
