id: netlify
name: netlify
version: v0.2.0
providerServices:
  access_token:
    description: accessToken
    id: access_token:v0.2.0
    name: access_token
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/access_token.yaml
    title: Netlify's API documentation - access_token
    version: v0.2.0
  account_membership:
    description: accountMembership
    id: account_membership:v0.2.0
    name: account_membership
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/account_membership.yaml
    title: Netlify's API documentation - account_membership
    version: v0.2.0
  account_type:
    description: accountType
    id: account_type:v0.2.0
    name: account_type
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/account_type.yaml
    title: Netlify's API documentation - account_type
    version: v0.2.0
  asset:
    description: asset
    id: asset:v0.2.0
    name: asset
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/asset.yaml
    title: Netlify's API documentation - asset
    version: v0.2.0
  asset_public_signature:
    description: assetPublicSignature
    id: asset_public_signature:v0.2.0
    name: asset_public_signature
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/asset_public_signature.yaml
    title: Netlify's API documentation - asset_public_signature
    version: v0.2.0
  audit_log:
    description: auditLog
    id: audit_log:v0.2.0
    name: audit_log
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/audit_log.yaml
    title: Netlify's API documentation - audit_log
    version: v0.2.0
  build:
    description: build
    id: build:v0.2.0
    name: build
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/build.yaml
    title: Netlify's API documentation - build
    version: v0.2.0
  build_hook:
    description: buildHook
    id: build_hook:v0.2.0
    name: build_hook
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/build_hook.yaml
    title: Netlify's API documentation - build_hook
    version: v0.2.0
  build_log_msg:
    description: buildLogMsg
    id: build_log_msg:v0.2.0
    name: build_log_msg
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/build_log_msg.yaml
    title: Netlify's API documentation - build_log_msg
    version: v0.2.0
  deploy:
    description: deploy
    id: deploy:v0.2.0
    name: deploy
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/deploy.yaml
    title: Netlify's API documentation - deploy
    version: v0.2.0
  deploy_key:
    description: deployKey
    id: deploy_key:v0.2.0
    name: deploy_key
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/deploy_key.yaml
    title: Netlify's API documentation - deploy_key
    version: v0.2.0
  deployed_branch:
    description: deployedBranch
    id: deployed_branch:v0.2.0
    name: deployed_branch
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/deployed_branch.yaml
    title: Netlify's API documentation - deployed_branch
    version: v0.2.0
  dns_zone:
    description: dnsZone
    id: dns_zone:v0.2.0
    name: dns_zone
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/dns_zone.yaml
    title: Netlify's API documentation - dns_zone
    version: v0.2.0
  file:
    description: file
    id: file:v0.2.0
    name: file
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/file.yaml
    title: Netlify's API documentation - file
    version: v0.2.0
  form:
    description: form
    id: form:v0.2.0
    name: form
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/form.yaml
    title: Netlify's API documentation - form
    version: v0.2.0
  function:
    description: function
    id: function:v0.2.0
    name: function
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/function.yaml
    title: Netlify's API documentation - function
    version: v0.2.0
  hook:
    description: hook
    id: hook:v0.2.0
    name: hook
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/hook.yaml
    title: Netlify's API documentation - hook
    version: v0.2.0
  hook_type:
    description: hookType
    id: hook_type:v0.2.0
    name: hook_type
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/hook_type.yaml
    title: Netlify's API documentation - hook_type
    version: v0.2.0
  member:
    description: member
    id: member:v0.2.0
    name: member
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/member.yaml
    title: Netlify's API documentation - member
    version: v0.2.0
  metadata:
    description: metadata
    id: metadata:v0.2.0
    name: metadata
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/metadata.yaml
    title: Netlify's API documentation - metadata
    version: v0.2.0
  payment_method:
    description: paymentMethod
    id: payment_method:v0.2.0
    name: payment_method
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/payment_method.yaml
    title: Netlify's API documentation - payment_method
    version: v0.2.0
  service:
    description: service
    id: service:v0.2.0
    name: service
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/service.yaml
    title: Netlify's API documentation - service
    version: v0.2.0
  service_instance:
    description: serviceInstance
    id: service_instance:v0.2.0
    name: service_instance
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/service_instance.yaml
    title: Netlify's API documentation - service_instance
    version: v0.2.0
  site:
    description: site
    id: site:v0.2.0
    name: site
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/site.yaml
    title: Netlify's API documentation - site
    version: v0.2.0
  sni_certificate:
    description: sniCertificate
    id: sni_certificate:v0.2.0
    name: sni_certificate
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/sni_certificate.yaml
    title: Netlify's API documentation - sni_certificate
    version: v0.2.0
  snippet:
    description: snippet
    id: snippet:v0.2.0
    name: snippet
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/snippet.yaml
    title: Netlify's API documentation - snippet
    version: v0.2.0
  split_test:
    description: splitTest
    id: split_test:v0.2.0
    name: split_test
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/split_test.yaml
    title: Netlify's API documentation - split_test
    version: v0.2.0
  submission:
    description: submission
    id: submission:v0.2.0
    name: submission
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/submission.yaml
    title: Netlify's API documentation - submission
    version: v0.2.0
  ticket:
    description: ticket
    id: ticket:v0.2.0
    name: ticket
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/ticket.yaml
    title: Netlify's API documentation - ticket
    version: v0.2.0
  user:
    description: user
    id: user:v0.2.0
    name: user
    preferred: true
    service:
      $ref: netlify/v0.2.0/services/user.yaml
    title: Netlify's API documentation - user
    version: v0.2.0
openapi: 3.0.0
