openapi: 3.0.3
info:
  title: credentials API
  description: Revoke compromised or leaked GitHub credentials.
  version: 1.1.4
paths:
  /credentials/revoke:
    post:
      summary: Revoke a list of credentials
      description: >-
        Submit a list of credentials to be revoked. This endpoint is intended to
        revoke credentials the caller does not own and may have found exposed on
        GitHub.com or elsewhere. It can also be used for credentials associated
        with an old user account that you no longer have access to. Credential
        owners will be notified of the revocation.


        This endpoint currently accepts the following credential types:

        - Personal access tokens (classic) (`ghp_`)

        - Fine-grained personal access tokens (`github_pat_`)

        - OAuth app access tokens (`gho_`)

        - User-to-server tokens from GitHub Apps (`ghu_`)

        - Refresh tokens from GitHub Apps (`ghr_`)



        Revoked credentials may impact users on GitHub Free, Pro, & Team and
        GitHub Enterprise Cloud, and GitHub Enterprise Cloud with Enterprise
        Managed Users.

        GitHub cannot reactivate any credentials that have been revoked; new
        credentials will need to be generated.


        To prevent abuse, this API is limited to only 60 unauthenticated
        requests per hour and a max of 1000 tokens per API request.


        > [!NOTE]

        > Any authenticated requests will return a 403.
      tags:
        - credentials
      operationId: credentials/revoke
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/credentials/revoke#revoke-a-list-of-credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                credentials:
                  type: array
                  description: A list of credentials to be revoked, up to 1000 per request.
                  items:
                    type: string
                  minItems: 1
                  maxItems: 1000
              required:
                - credentials
            examples:
              default:
                value:
                  credentials:
                    - ghp_1234567890abcdef1234567890abcdef12345678
                    - >-
                      github_pat_0A1B2C3D4E5F6G7H8I9J0K_ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456
                    - gho_1234567890abcdef1234567890abcdef12345678
                    - ghu_1234567890abcdef1234567890abcdef12345678
                    - >-
                      ghr_1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890ab
      responses:
        '202':
          $ref: '#/components/responses/accepted'
        '422':
          $ref: '#/components/responses/validation_failed_simple'
        '500':
          $ref: '#/components/responses/internal_error'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: credentials
        subcategory: revoke
      x-stackQL-resource: revoke
components:
  schemas:
    validation-error-simple:
      title: Validation Error Simple
      description: Validation Error Simple
      type: object
      required:
        - message
        - documentation_url
      properties:
        message:
          type: string
        documentation_url:
          type: string
        errors:
          type: array
          items:
            type: string
    basic-error:
      title: Basic Error
      description: Basic Error
      type: object
      properties:
        message:
          type: string
        documentation_url:
          type: string
        url:
          type: string
        status:
          type: string
  responses:
    accepted:
      description: Accepted
      content:
        application/json:
          schema:
            type: string
            description: (opaque JSON object)
          examples:
            default:
              value: null
    validation_failed_simple:
      description: Validation failed, or the endpoint has been spammed.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/validation-error-simple'
    internal_error:
      description: Internal Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/basic-error'
  x-stackQL-resources:
    credentials:
      id: github.credentials.credentials
      name: credentials
      title: Credentials
      methods:
        revoke:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1credentials~1revoke/post'
          response:
            mediaType: application/json
            openAPIDocKey: '202'
      sqlVerbs:
        select: []
        insert: []
        update: []
        delete: []
        replace: []
servers:
  - url: https://api.github.com
