openapi: 3.0.3
info:
  title: enterprise_team_organizations API
  description: github API
  version: 1.1.4
paths:
  /enterprises/{enterprise}/teams/{enterprise_team}/organizations:
    get:
      summary: Get organization assignments
      description: Get all organizations assigned to an enterprise team
      tags:
        - enterprise-team-organizations
      operationId: enterprise-team-organizations/get-assignments
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/enterprise-teams/enterprise-team-organizations#get-organization-assignments
      parameters:
        - $ref: '#/components/parameters/enterprise'
        - $ref: '#/components/parameters/enterprise-team'
        - $ref: '#/components/parameters/per-page'
        - $ref: '#/components/parameters/page'
      responses:
        '200':
          description: An array of organizations the team is assigned to
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/organization-simple'
              examples:
                default:
                  $ref: '#/components/examples/organization-simple'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-teams
        subcategory: enterprise-team-organizations
      x-stackQL-resource: enterprise_team_organizations
  /enterprises/{enterprise}/teams/{enterprise_team}/organizations/add:
    post:
      summary: Add organization assignments
      description: Assign an enterprise team to multiple organizations.
      tags:
        - enterprise-team-organizations
      operationId: enterprise-team-organizations/bulk-add
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/enterprise-teams/enterprise-team-organizations#add-organization-assignments
      parameters:
        - $ref: '#/components/parameters/enterprise'
        - $ref: '#/components/parameters/enterprise-team'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - organization_slugs
              properties:
                organization_slugs:
                  type: array
                  description: Organization slug to assign the team to.
                  items:
                    type: string
                    description: Organization slug to assign the team to
            examples:
              default:
                value:
                  organization_slugs:
                    - github
      responses:
        '200':
          description: Successfully assigned the enterprise team to organizations.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/organization-simple'
              examples:
                default:
                  $ref: '#/components/examples/organization-simple-items'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-teams
        subcategory: enterprise-team-organizations
      x-stackQL-resource: enterprise_team_organizations
  /enterprises/{enterprise}/teams/{enterprise_team}/organizations/remove:
    post:
      summary: Remove organization assignments
      description: Unassign an enterprise team from multiple organizations.
      tags:
        - enterprise-team-organizations
      operationId: enterprise-team-organizations/bulk-remove
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/enterprise-teams/enterprise-team-organizations#remove-organization-assignments
      parameters:
        - $ref: '#/components/parameters/enterprise'
        - $ref: '#/components/parameters/enterprise-team'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - organization_slugs
              properties:
                organization_slugs:
                  type: array
                  description: Organization slug to unassign the team from.
                  items:
                    type: string
                    description: Organization slug to unassign the team from
            examples:
              default:
                value:
                  organization_slugs:
                    - github
      responses:
        '204':
          description: Successfully unassigned the enterprise team from organizations.
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-teams
        subcategory: enterprise-team-organizations
      x-stackQL-resource: enterprise_team_organizations
  /enterprises/{enterprise}/teams/{enterprise_team}/organizations/{org}:
    get:
      summary: Get organization assignment
      description: Check if an enterprise team is assigned to an organization
      tags:
        - enterprise-team-organizations
      operationId: enterprise-team-organizations/get-assignment
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/enterprise-teams/enterprise-team-organizations#get-organization-assignment
      parameters:
        - $ref: '#/components/parameters/enterprise'
        - $ref: '#/components/parameters/enterprise-team'
        - $ref: '#/components/parameters/org'
      responses:
        '200':
          description: The team is assigned to the organization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organization-simple'
              examples:
                default:
                  $ref: '#/components/examples/organization-simple'
        '404':
          description: The team is not assigned to the organization
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-teams
        subcategory: enterprise-team-organizations
      x-stackQL-resource: enterprise_team_organizations
    put:
      summary: Add an organization assignment
      description: Assign an enterprise team to an organization.
      tags:
        - enterprise-team-organizations
      operationId: enterprise-team-organizations/add
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/enterprise-teams/enterprise-team-organizations#add-an-organization-assignment
      parameters:
        - $ref: '#/components/parameters/enterprise'
        - $ref: '#/components/parameters/enterprise-team'
        - $ref: '#/components/parameters/org'
      responses:
        '201':
          description: Successfully assigned the enterprise team to the organization.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organization-simple'
              examples:
                default:
                  $ref: '#/components/examples/organization-simple'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-teams
        subcategory: enterprise-team-organizations
      x-stackQL-resource: enterprise_team_organizations
    delete:
      summary: Delete an organization assignment
      description: Unassign an enterprise team from an organization.
      tags:
        - enterprise-team-organizations
      operationId: enterprise-team-organizations/delete
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/enterprise-teams/enterprise-team-organizations#delete-an-organization-assignment
      parameters:
        - $ref: '#/components/parameters/enterprise'
        - $ref: '#/components/parameters/enterprise-team'
        - $ref: '#/components/parameters/org'
      responses:
        '204':
          description: Successfully unassigned the enterprise team from the organization.
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-teams
        subcategory: enterprise-team-organizations
      x-stackQL-resource: enterprise_team_organizations
components:
  schemas:
    organization-simple:
      title: Organization Simple
      description: A GitHub organization.
      type: object
      properties:
        login:
          type: string
          example: github
        id:
          type: integer
          example: 1
        node_id:
          type: string
          example: MDEyOk9yZ2FuaXphdGlvbjE=
        url:
          type: string
          format: uri
          example: https://api.github.com/orgs/github
        repos_url:
          type: string
          format: uri
          example: https://api.github.com/orgs/github/repos
        events_url:
          type: string
          format: uri
          example: https://api.github.com/orgs/github/events
        hooks_url:
          type: string
          example: https://api.github.com/orgs/github/hooks
        issues_url:
          type: string
          example: https://api.github.com/orgs/github/issues
        members_url:
          type: string
          example: https://api.github.com/orgs/github/members{/member}
        public_members_url:
          type: string
          example: https://api.github.com/orgs/github/public_members{/member}
        avatar_url:
          type: string
          example: https://github.com/images/error/octocat_happy.gif
        description:
          type: string
          example: A great organization
          nullable: true
      required:
        - login
        - url
        - id
        - node_id
        - repos_url
        - events_url
        - hooks_url
        - issues_url
        - members_url
        - public_members_url
        - avatar_url
        - description
  parameters:
    enterprise:
      name: enterprise
      description: The slug version of the enterprise name.
      in: path
      required: true
      schema:
        type: string
    enterprise-team:
      name: enterprise-team
      description: >-
        The slug version of the enterprise team name. You can also substitute
        this value with the enterprise team id.
      in: path
      required: true
      schema:
        type: string
    per-page:
      name: per_page
      description: >-
        The number of results per page (max 100). For more information, see
        "[Using pagination in the REST
        API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."
      in: query
      schema:
        type: integer
        default: 30
    page:
      name: page
      description: >-
        The page number of the results to fetch. For more information, see
        "[Using pagination in the REST
        API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."
      in: query
      schema:
        type: integer
        default: 1
    org:
      name: org
      description: The organization name. The name is not case sensitive.
      in: path
      required: true
      schema:
        type: string
  examples:
    organization-simple:
      value:
        login: github
        id: 1
        node_id: MDEyOk9yZ2FuaXphdGlvbjE=
        url: https://api.github.com/orgs/github
        repos_url: https://api.github.com/orgs/github/repos
        events_url: https://api.github.com/orgs/github/events
        hooks_url: https://api.github.com/orgs/github/hooks
        issues_url: https://api.github.com/orgs/github/issues
        members_url: https://api.github.com/orgs/github/members{/member}
        public_members_url: https://api.github.com/orgs/github/public_members{/member}
        avatar_url: https://github.com/images/error/octocat_happy.gif
        description: A great organization
    organization-simple-items:
      value:
        - login: github
          id: 1
          node_id: MDEyOk9yZ2FuaXphdGlvbjE=
          url: https://api.github.com/orgs/github
          repos_url: https://api.github.com/orgs/github/repos
          events_url: https://api.github.com/orgs/github/events
          hooks_url: https://api.github.com/orgs/github/hooks
          issues_url: https://api.github.com/orgs/github/issues
          members_url: https://api.github.com/orgs/github/members{/member}
          public_members_url: https://api.github.com/orgs/github/public_members{/member}
          avatar_url: https://github.com/images/error/octocat_happy.gif
          description: A great organization
  x-stackQL-resources:
    enterprise_team_organizations:
      id: github.enterprise_team_organizations.enterprise_team_organizations
      name: enterprise_team_organizations
      title: Enterprise Team Organizations
      methods:
        get_assignments:
          operation:
            $ref: >-
              #/paths/~1enterprises~1{enterprise}~1teams~1{enterprise_team}~1organizations/get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get_assignment:
          operation:
            $ref: >-
              #/paths/~1enterprises~1{enterprise}~1teams~1{enterprise_team}~1organizations~1{org}/get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        add:
          operation:
            $ref: >-
              #/paths/~1enterprises~1{enterprise}~1teams~1{enterprise_team}~1organizations~1{org}/put
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        delete:
          operation:
            $ref: >-
              #/paths/~1enterprises~1{enterprise}~1teams~1{enterprise_team}~1organizations~1{org}/delete
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/enterprise_team_organizations/methods/get_assignment
          - $ref: >-
              #/components/x-stackQL-resources/enterprise_team_organizations/methods/get_assignments
        insert: []
        update: []
        delete:
          - $ref: >-
              #/components/x-stackQL-resources/enterprise_team_organizations/methods/delete
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/enterprise_team_organizations/methods/add
    enterprise_team_organization_bulk_additions:
      id: >-
        github.enterprise_team_organizations.enterprise_team_organization_bulk_additions
      name: enterprise_team_organization_bulk_additions
      title: Enterprise Team Organization Bulk Additions
      methods:
        bulk_add:
          operation:
            $ref: >-
              #/paths/~1enterprises~1{enterprise}~1teams~1{enterprise_team}~1organizations~1add/post
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert:
          - $ref: >-
              #/components/x-stackQL-resources/enterprise_team_organization_bulk_additions/methods/bulk_add
        update: []
        delete: []
        replace: []
    enterprise_team_organization_bulk_removals:
      id: >-
        github.enterprise_team_organizations.enterprise_team_organization_bulk_removals
      name: enterprise_team_organization_bulk_removals
      title: Enterprise Team Organization Bulk Removals
      methods:
        bulk_remove:
          operation:
            $ref: >-
              #/paths/~1enterprises~1{enterprise}~1teams~1{enterprise_team}~1organizations~1remove/post
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select: []
        insert:
          - $ref: >-
              #/components/x-stackQL-resources/enterprise_team_organization_bulk_removals/methods/bulk_remove
        update: []
        delete: []
        replace: []
servers:
  - url: https://api.github.com
