openapi: 3.0.3
info:
  title: enterprise_team_memberships API
  description: github API
  version: 1.1.4
paths:
  /enterprises/{enterprise}/teams/{enterprise_team}/memberships:
    get:
      summary: List members in an enterprise team
      description: Lists all team members in an enterprise team.
      tags:
        - enterprise-team-memberships
      operationId: enterprise-team-memberships/list
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/enterprise-teams/enterprise-team-members#list-members-in-an-enterprise-team
      parameters:
        - $ref: '#/components/parameters/enterprise'
        - $ref: '#/components/parameters/enterprise-team'
        - $ref: '#/components/parameters/per-page'
        - $ref: '#/components/parameters/page'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/simple-user'
              examples:
                default:
                  $ref: '#/components/examples/simple-user-items'
          headers:
            Link:
              $ref: '#/components/headers/link'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-teams
        subcategory: enterprise-team-members
      x-stackQL-resource: enterprise_team_members
  /enterprises/{enterprise}/teams/{enterprise_team}/memberships/add:
    post:
      summary: Bulk add team members
      description: Add multiple team members to an enterprise team.
      tags:
        - enterprise-team-memberships
      operationId: enterprise-team-memberships/bulk-add
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/enterprise-teams/enterprise-team-members#bulk-add-team-members
      parameters:
        - $ref: '#/components/parameters/enterprise'
        - $ref: '#/components/parameters/enterprise-team'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - usernames
              properties:
                usernames:
                  type: array
                  description: The GitHub user handles to add to the team.
                  items:
                    type: string
                    description: The handle for the GitHub user account.
            examples:
              default:
                value:
                  usernames:
                    - monalisa
                    - octocat
      responses:
        '200':
          description: Successfully added team members.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/simple-user'
              examples:
                default:
                  $ref: '#/components/examples/simple-user-items'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-teams
        subcategory: enterprise-team-members
      x-stackQL-resource: enterprise_team_members
  /enterprises/{enterprise}/teams/{enterprise_team}/memberships/remove:
    post:
      summary: Bulk remove team members
      description: Remove multiple team members from an enterprise team.
      tags:
        - enterprise-team-memberships
      operationId: enterprise-team-memberships/bulk-remove
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/enterprise-teams/enterprise-team-members#bulk-remove-team-members
      parameters:
        - $ref: '#/components/parameters/enterprise'
        - $ref: '#/components/parameters/enterprise-team'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - usernames
              properties:
                usernames:
                  type: array
                  description: The GitHub user handles to be removed from the team.
                  items:
                    type: string
                    description: The handle for the GitHub user account.
            examples:
              default:
                value:
                  usernames:
                    - monalisa
                    - octocat
      responses:
        '200':
          description: Successfully removed team members.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/simple-user'
              examples:
                default:
                  $ref: '#/components/examples/simple-user-items'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-teams
        subcategory: enterprise-team-members
      x-stackQL-resource: enterprise_team_members
  /enterprises/{enterprise}/teams/{enterprise_team}/memberships/{username}:
    get:
      summary: Get enterprise team membership
      description: Returns whether the user is a member of the enterprise team.
      tags:
        - enterprise-team-memberships
      operationId: enterprise-team-memberships/get
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/enterprise-teams/enterprise-team-members#get-enterprise-team-membership
      parameters:
        - $ref: '#/components/parameters/enterprise'
        - $ref: '#/components/parameters/enterprise-team'
        - $ref: '#/components/parameters/username'
      responses:
        '200':
          description: User is a member of the enterprise team.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/simple-user'
              examples:
                exampleKey1:
                  $ref: '#/components/examples/simple-user'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-teams
        subcategory: enterprise-team-members
      x-stackQL-resource: enterprise_team_members
    put:
      summary: Add team member
      description: Add a team member to an enterprise team.
      tags:
        - enterprise-team-memberships
      operationId: enterprise-team-memberships/add
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/enterprise-teams/enterprise-team-members#add-team-member
      parameters:
        - $ref: '#/components/parameters/enterprise'
        - $ref: '#/components/parameters/enterprise-team'
        - $ref: '#/components/parameters/username'
      responses:
        '201':
          description: Successfully added team member
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/simple-user'
              examples:
                exampleKey1:
                  $ref: '#/components/examples/simple-user'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-teams
        subcategory: enterprise-team-members
      x-stackQL-resource: enterprise_team_members
    delete:
      summary: Remove team membership
      description: >-
        Remove membership of a specific user from a particular team in an
        enterprise.
      tags:
        - enterprise-team-memberships
      operationId: enterprise-team-memberships/remove
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/enterprise-teams/enterprise-team-members#remove-team-membership
      parameters:
        - $ref: '#/components/parameters/enterprise'
        - $ref: '#/components/parameters/enterprise-team'
        - $ref: '#/components/parameters/username'
      responses:
        '204':
          description: Response
        '403':
          $ref: '#/components/responses/forbidden'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: false
        category: enterprise-teams
        subcategory: enterprise-team-members
      x-stackQL-resource: enterprise_team_members
components:
  schemas:
    simple-user:
      title: Simple User
      description: A GitHub user.
      type: object
      properties:
        name:
          nullable: true
          type: string
        email:
          nullable: true
          type: string
        login:
          type: string
          example: octocat
        id:
          type: integer
          format: int64
          example: 1
        node_id:
          type: string
          example: MDQ6VXNlcjE=
        avatar_url:
          type: string
          format: uri
          example: https://github.com/images/error/octocat_happy.gif
        gravatar_id:
          type: string
          example: 41d064eb2195891e12d0413f63227ea7
          nullable: true
        url:
          type: string
          format: uri
          example: https://api.github.com/users/octocat
        html_url:
          type: string
          format: uri
          example: https://github.com/octocat
        followers_url:
          type: string
          format: uri
          example: https://api.github.com/users/octocat/followers
        following_url:
          type: string
          example: https://api.github.com/users/octocat/following{/other_user}
        gists_url:
          type: string
          example: https://api.github.com/users/octocat/gists{/gist_id}
        starred_url:
          type: string
          example: https://api.github.com/users/octocat/starred{/owner}{/repo}
        subscriptions_url:
          type: string
          format: uri
          example: https://api.github.com/users/octocat/subscriptions
        organizations_url:
          type: string
          format: uri
          example: https://api.github.com/users/octocat/orgs
        repos_url:
          type: string
          format: uri
          example: https://api.github.com/users/octocat/repos
        events_url:
          type: string
          example: https://api.github.com/users/octocat/events{/privacy}
        received_events_url:
          type: string
          format: uri
          example: https://api.github.com/users/octocat/received_events
        type:
          type: string
          example: User
        site_admin:
          type: boolean
        starred_at:
          type: string
          example: '"2020-07-09T00:17:55Z"'
        user_view_type:
          type: string
          example: public
      required:
        - avatar_url
        - events_url
        - followers_url
        - following_url
        - gists_url
        - gravatar_id
        - html_url
        - id
        - node_id
        - login
        - organizations_url
        - received_events_url
        - repos_url
        - site_admin
        - starred_url
        - subscriptions_url
        - type
        - url
    basic-error:
      title: Basic Error
      description: Basic Error
      type: object
      properties:
        message:
          type: string
        documentation_url:
          type: string
        url:
          type: string
        status:
          type: string
  responses:
    forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/basic-error'
  parameters:
    enterprise:
      name: enterprise
      description: The slug version of the enterprise name.
      in: path
      required: true
      schema:
        type: string
    enterprise-team:
      name: enterprise-team
      description: >-
        The slug version of the enterprise team name. You can also substitute
        this value with the enterprise team id.
      in: path
      required: true
      schema:
        type: string
    per-page:
      name: per_page
      description: >-
        The number of results per page (max 100). For more information, see
        "[Using pagination in the REST
        API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."
      in: query
      schema:
        type: integer
        default: 30
    page:
      name: page
      description: >-
        The page number of the results to fetch. For more information, see
        "[Using pagination in the REST
        API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api)."
      in: query
      schema:
        type: integer
        default: 1
    username:
      name: username
      description: The handle for the GitHub user account.
      in: path
      required: true
      schema:
        type: string
  examples:
    simple-user-items:
      value:
        - login: octocat
          id: 1
          node_id: MDQ6VXNlcjE=
          avatar_url: https://github.com/images/error/octocat_happy.gif
          gravatar_id: ''
          url: https://api.github.com/users/octocat
          html_url: https://github.com/octocat
          followers_url: https://api.github.com/users/octocat/followers
          following_url: https://api.github.com/users/octocat/following{/other_user}
          gists_url: https://api.github.com/users/octocat/gists{/gist_id}
          starred_url: https://api.github.com/users/octocat/starred{/owner}{/repo}
          subscriptions_url: https://api.github.com/users/octocat/subscriptions
          organizations_url: https://api.github.com/users/octocat/orgs
          repos_url: https://api.github.com/users/octocat/repos
          events_url: https://api.github.com/users/octocat/events{/privacy}
          received_events_url: https://api.github.com/users/octocat/received_events
          type: User
          site_admin: false
    simple-user:
      value:
        login: octocat
        id: 1
        node_id: MDQ6VXNlcjE=
        avatar_url: https://github.com/images/error/octocat_happy.gif
        gravatar_id: ''
        url: https://api.github.com/users/octocat
        html_url: https://github.com/octocat
        followers_url: https://api.github.com/users/octocat/followers
        following_url: https://api.github.com/users/octocat/following{/other_user}
        gists_url: https://api.github.com/users/octocat/gists{/gist_id}
        starred_url: https://api.github.com/users/octocat/starred{/owner}{/repo}
        subscriptions_url: https://api.github.com/users/octocat/subscriptions
        organizations_url: https://api.github.com/users/octocat/orgs
        repos_url: https://api.github.com/users/octocat/repos
        events_url: https://api.github.com/users/octocat/events{/privacy}
        received_events_url: https://api.github.com/users/octocat/received_events
        type: User
        site_admin: false
  headers:
    link:
      example: >-
        <https://api.github.com/resource?page=2>; rel="next",
        <https://api.github.com/resource?page=5>; rel="last"
      schema:
        type: string
  x-stackQL-resources:
    enterprise_team_memberships:
      id: github.enterprise_team_memberships.enterprise_team_memberships
      name: enterprise_team_memberships
      title: Enterprise Team Memberships
      methods:
        list:
          operation:
            $ref: >-
              #/paths/~1enterprises~1{enterprise}~1teams~1{enterprise_team}~1memberships/get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        get:
          operation:
            $ref: >-
              #/paths/~1enterprises~1{enterprise}~1teams~1{enterprise_team}~1memberships~1{username}/get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        add:
          operation:
            $ref: >-
              #/paths/~1enterprises~1{enterprise}~1teams~1{enterprise_team}~1memberships~1{username}/put
          response:
            mediaType: application/json
            openAPIDocKey: '201'
        remove:
          operation:
            $ref: >-
              #/paths/~1enterprises~1{enterprise}~1teams~1{enterprise_team}~1memberships~1{username}/delete
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/enterprise_team_memberships/methods/get
          - $ref: >-
              #/components/x-stackQL-resources/enterprise_team_memberships/methods/list
        insert: []
        update: []
        delete:
          - $ref: >-
              #/components/x-stackQL-resources/enterprise_team_memberships/methods/remove
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/enterprise_team_memberships/methods/add
    enterprise_team_membership_bulk_additions:
      id: >-
        github.enterprise_team_memberships.enterprise_team_membership_bulk_additions
      name: enterprise_team_membership_bulk_additions
      title: Enterprise Team Membership Bulk Additions
      methods:
        bulk_add:
          operation:
            $ref: >-
              #/paths/~1enterprises~1{enterprise}~1teams~1{enterprise_team}~1memberships~1add/post
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert:
          - $ref: >-
              #/components/x-stackQL-resources/enterprise_team_membership_bulk_additions/methods/bulk_add
        update: []
        delete: []
        replace: []
    enterprise_team_membership_bulk_removals:
      id: >-
        github.enterprise_team_memberships.enterprise_team_membership_bulk_removals
      name: enterprise_team_membership_bulk_removals
      title: Enterprise Team Membership Bulk Removals
      methods:
        bulk_remove:
          operation:
            $ref: >-
              #/paths/~1enterprises~1{enterprise}~1teams~1{enterprise_team}~1memberships~1remove/post
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert:
          - $ref: >-
              #/components/x-stackQL-resources/enterprise_team_membership_bulk_removals/methods/bulk_remove
        update: []
        delete: []
        replace: []
servers:
  - url: https://api.github.com
