openapi: 3.0.3
info:
  title: markdown API
  description: Render GitHub flavored Markdown
  version: 1.1.4
paths:
  /markdown:
    post:
      summary: Render a Markdown document
      description: >-
        Depending on what is rendered in the Markdown, you may need to provide
        additional token scopes for labels, such as `issues:read` or
        `pull_requests:read`.
      operationId: markdown/render
      tags:
        - markdown
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/markdown/markdown#render-a-markdown-document
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                text:
                  description: The Markdown text to render in HTML.
                  type: string
                mode:
                  description: The rendering mode.
                  enum:
                    - markdown
                    - gfm
                  default: markdown
                  example: markdown
                  type: string
                context:
                  description: >-
                    The repository context to use when creating references in
                    `gfm` mode.  For example, setting `context` to
                    `octo-org/octo-repo` will change the text `#42` into an HTML
                    link to issue 42 in the `octo-org/octo-repo` repository.
                  type: string
              required:
                - text
              type: object
            examples:
              default:
                summary: Rendering markdown
                value:
                  text: Hello **world**
      responses:
        '200':
          description: Response
          headers:
            Content-Type:
              $ref: '#/components/headers/content-type'
            Content-Length:
              example: '279'
              schema:
                type: string
            X-CommonMarker-Version:
              $ref: '#/components/headers/x-common-marker-version'
          content:
            text/html:
              schema:
                type: string
              examples:
                default:
                  summary: Example response
                  value: <p>Hello <strong>world</strong></p>
        '304':
          $ref: '#/components/responses/not_modified'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: markdown
        subcategory: markdown
      x-stackQL-resource: markdown
  /markdown/raw:
    post:
      summary: Render a Markdown document in raw mode
      description: >-
        You must send Markdown as plain text (using a `Content-Type` header of
        `text/plain` or `text/x-markdown`) to this endpoint, rather than using
        JSON format. In raw mode, [GitHub Flavored
        Markdown](https://github.github.com/gfm/) is not supported and Markdown
        will be rendered in plain format like a README.md file. Markdown content
        must be 400 KB or less.
      operationId: markdown/render-raw
      tags:
        - markdown
      externalDocs:
        description: API method documentation
        url: >-
          https://docs.github.com/rest/markdown/markdown#render-a-markdown-document-in-raw-mode
      parameters: []
      requestBody:
        required: false
        content:
          text/plain:
            schema:
              type: string
            examples:
              default:
                value:
                  text: Hello **world**
          text/x-markdown:
            schema:
              type: string
            examples:
              default:
                summary: Rendering markdown
                value:
                  text: Hello **world**
      responses:
        '200':
          description: Response
          headers:
            X-CommonMarker-Version:
              $ref: '#/components/headers/x-common-marker-version'
          content:
            text/html:
              schema:
                type: string
              examples:
                default:
                  summary: Example response
                  value: <p>Hello <strong>world</strong></p>
        '304':
          $ref: '#/components/responses/not_modified'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: markdown
        subcategory: markdown
      x-stackQL-resource: markdown
components:
  responses:
    not_modified:
      description: Not modified
  headers:
    content-type:
      example: text/html
      schema:
        type: string
    x-common-marker-version:
      example: 0.17.4
      schema:
        type: string
  x-stackQL-resources:
    rendered_markdown:
      id: github.markdown.rendered_markdown
      name: rendered_markdown
      title: Rendered Markdown
      methods:
        render:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1markdown/post'
          response:
            mediaType: text/html
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert:
          - $ref: '#/components/x-stackQL-resources/rendered_markdown/methods/render'
        update: []
        delete: []
        replace: []
    rendered_markdown_raw:
      id: github.markdown.rendered_markdown_raw
      name: rendered_markdown_raw
      title: Rendered Markdown Raw
      methods:
        render_raw:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1markdown~1raw/post'
          response:
            mediaType: text/html
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert:
          - $ref: >-
              #/components/x-stackQL-resources/rendered_markdown_raw/methods/render_raw
        update: []
        delete: []
        replace: []
servers:
  - url: https://api.github.com
