paths:
  /rate_limit:
    get:
      summary: Get rate limit status for the authenticated user
      description: |-
        **Note:** Accessing this endpoint does not count against your REST API rate limit.

        **Note:** The `rate` object is deprecated. If you're writing new API client code or updating existing code, you should use the `core` object instead of the `rate` object. The `core` object contains the same information that is present in the `rate` object.
      tags:
        - rate-limit
      operationId: rate-limit/get
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/rest/reference/rate-limit#get-rate-limit-status-for-the-authenticated-user
      parameters: []
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rate-limit-overview'
              examples:
                default:
                  $ref: '#/components/examples/rate-limit-overview'
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/x-rate-limit-limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/x-rate-limit-remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/x-rate-limit-reset'
        '304':
          $ref: '#/components/responses/not_modified'
        '404':
          $ref: '#/components/responses/not_found'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: rate-limit
        subcategory: null
components:
  schemas:
    rate-limit-overview:
      title: Rate Limit Overview
      description: Rate Limit Overview
      type: object
      properties:
        resources:
          type: object
          properties:
            core:
              $ref: '#/components/schemas/rate-limit'
            graphql:
              $ref: '#/components/schemas/rate-limit'
            search:
              $ref: '#/components/schemas/rate-limit'
            source_import:
              $ref: '#/components/schemas/rate-limit'
            integration_manifest:
              $ref: '#/components/schemas/rate-limit'
            code_scanning_upload:
              $ref: '#/components/schemas/rate-limit'
            actions_runner_registration:
              $ref: '#/components/schemas/rate-limit'
            scim:
              $ref: '#/components/schemas/rate-limit'
          required:
            - core
            - search
        rate:
          $ref: '#/components/schemas/rate-limit'
      required:
        - rate
        - resources
    rate-limit:
      title: Rate Limit
      type: object
      properties:
        limit:
          type: integer
        remaining:
          type: integer
        reset:
          type: integer
        used:
          type: integer
      required:
        - limit
        - remaining
        - reset
        - used
    basic-error:
      title: Basic Error
      description: Basic Error
      type: object
      properties:
        message:
          type: string
        documentation_url:
          type: string
        url:
          type: string
        status:
          type: string
  parameters: {}
  responses:
    not_modified:
      description: Not modified
    not_found:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/basic-error'
  securitySchemes: {}
  callbacks: {}
  examples:
    rate-limit-overview:
      value:
        resources:
          core:
            limit: 5000
            remaining: 4999
            reset: 1372700873
            used: 1
          search:
            limit: 30
            remaining: 18
            reset: 1372697452
            used: 12
          graphql:
            limit: 5000
            remaining: 4993
            reset: 1372700389
            used: 7
          integration_manifest:
            limit: 5000
            remaining: 4999
            reset: 1551806725
            used: 1
          code_scanning_upload:
            limit: 500
            remaining: 499
            reset: 1551806725
            used: 1
        rate:
          limit: 5000
          remaining: 4999
          reset: 1372700873
          used: 1
  requestBodies: {}
  headers:
    x-rate-limit-limit:
      example: 5000
      schema:
        type: integer
    x-rate-limit-remaining:
      example: 4999
      schema:
        type: integer
    x-rate-limit-reset:
      example: 1590701888
      schema:
        type: integer
        format: timestamp
  links: {}
  x-stackQL-resources:
    rate_limits:
      id: github.rate_limits.rate_limits
      name: rate_limits
      title: Rate Limits
      methods:
        get:
          operation:
            $ref: '#/paths/~1rate_limit/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/rate_limits/methods/get'
        insert: []
        update: []
        delete: []
openapi: 3.0.3
servers:
  - url: https://api.github.com
tags:
  - name: actions
    description: Endpoints to manage GitHub Actions using the REST API.
  - name: activity
    description: Activity APIs provide access to notifications, subscriptions, and timelines.
  - name: apps
    description: Information for integrations and installations.
  - name: billing
    description: Monitor charges and usage from Actions and Packages.
  - name: checks
    description: Rich interactions with checks run by your integrations.
  - name: code-scanning
    description: Retrieve code scanning alerts from a repository.
  - name: codes-of-conduct
    description: Insight into codes of conduct for your communities.
  - name: codespaces
    description: Endpoints to manage Codespaces using the REST API.
  - name: emojis
    description: List emojis available to use on GitHub.
  - name: enterprise-admin
    description: Administer a GitHub enterprise.
  - name: dependabot
    description: Endpoints to manage Dependabot.
  - name: gists
    description: View, modify your gists.
  - name: git
    description: Raw Git functionality.
  - name: gitignore
    description: View gitignore templates
  - name: interactions
    description: Owner or admin management of users interactions.
  - name: issues
    description: Interact with GitHub Issues.
  - name: licenses
    description: View various OSS licenses.
  - name: markdown
    description: Render GitHub flavored markdown
  - name: meta
    description: Endpoints that give information about the API.
  - name: migrations
    description: Move projects to or from GitHub.
  - name: oauth-authorizations
    description: Manage access of OAuth applications
  - name: orgs
    description: Interact with GitHub Orgs.
  - name: packages
    description: Manage packages for authenticated users and organizations.
  - name: projects
    description: Interact with GitHub Projects.
  - name: pulls
    description: Interact with GitHub Pull Requests.
  - name: rate-limit
    description: Check your current rate limit status
  - name: reactions
    description: Interact with reactions to various GitHub entities.
  - name: repos
    description: Interact with GitHub Repos.
  - name: scim
    description: Provisioning of GitHub organization membership for SCIM-enabled providers.
  - name: search
    description: Look for stuff on GitHub.
  - name: secret-scanning
    description: Retrieve secret scanning alerts from a repository.
  - name: server-statistics
    description: GHES statistics
  - name: teams
    description: Interact with GitHub Teams.
  - name: users
    description: Interact with and view information about users and also current user.
externalDocs:
  description: GitHub v3 REST API
  url: https://docs.github.com/rest/
info:
  version: 1.1.4
  title: GitHub v3 REST API - rate_limit
  description: rate_limit
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT
  termsOfService: https://docs.github.com/articles/github-terms-of-service
  contact:
    name: Support
    url: https://support.github.com/contact?tags=dotcom-rest-api
