id: aws
name: aws
version: v0.1.2
providerServices:
  ec2:
    description: ec2
    id: ec2:v0.1.2
    name: ec2
    preferred: true
    service:
      $ref: aws/v0.1.2/services/ec2.yaml
    title: EC2
    version: v0.1.2
  cloud_control:
    description: cloud_control
    id: cloud_control:v0.1.2
    name: cloud_control
    preferred: true
    service:
      $ref: aws/v0.1.2/services/cloud_control.yaml
    title: Cloud Control API
    version: v0.1.2
openapi: 3.0.0
