providerServices:
  meta:
    description: Endpoints that give information about the API.
    id: meta:v2.0.1
    name: meta
    preferred: true
    service:
      $ref: github/v2.0.1/services/meta.yaml
    title: meta
    version: v2.0.1
  apps:
    description: Information for integrations and installations.
    id: apps:v2.0.1
    name: apps
    preferred: true
    service:
      $ref: github/v2.0.1/services/apps.yaml
    title: apps
    version: v2.0.1
  oauth_authorizations:
    id: oauth_authorizations:v2.0.1
    name: oauth_authorizations
    preferred: true
    service:
      $ref: github/v2.0.1/services/oauth_authorizations.yaml
    title: oauth_authorizations
    version: v2.0.1
  codes_of_conduct:
    id: codes_of_conduct:v2.0.1
    name: codes_of_conduct
    preferred: true
    service:
      $ref: github/v2.0.1/services/codes_of_conduct.yaml
    title: codes_of_conduct
    version: v2.0.1
  emojis:
    description: List emojis available to use on GitHub.
    id: emojis:v2.0.1
    name: emojis
    preferred: true
    service:
      $ref: github/v2.0.1/services/emojis.yaml
    title: emojis
    version: v2.0.1
  actions_enterprises:
    id: actions_enterprises:v2.0.1
    name: actions_enterprises
    preferred: true
    service:
      $ref: github/v2.0.1/services/actions_enterprises.yaml
    title: actions_enterprises
    version: v2.0.1
  enterprise_admin:
    id: enterprise_admin:v2.0.1
    name: enterprise_admin
    preferred: true
    service:
      $ref: github/v2.0.1/services/enterprise_admin.yaml
    title: enterprise_admin
    version: v2.0.1
  secret_scanning_enterprises:
    id: secret_scanning_enterprises:v2.0.1
    name: secret_scanning_enterprises
    preferred: true
    service:
      $ref: github/v2.0.1/services/secret_scanning_enterprises.yaml
    title: secret_scanning_enterprises
    version: v2.0.1
  activity:
    description: Activity APIs provide access to notifications, subscriptions, and timelines.
    id: activity:v2.0.1
    name: activity
    preferred: true
    service:
      $ref: github/v2.0.1/services/activity.yaml
    title: activity
    version: v2.0.1
  gists:
    description: View, modify your gists.
    id: gists:v2.0.1
    name: gists
    preferred: true
    service:
      $ref: github/v2.0.1/services/gists.yaml
    title: gists
    version: v2.0.1
  gitignore:
    description: View gitignore templates
    id: gitignore:v2.0.1
    name: gitignore
    preferred: true
    service:
      $ref: github/v2.0.1/services/gitignore.yaml
    title: gitignore
    version: v2.0.1
  issues:
    description: Interact with GitHub Issues.
    id: issues:v2.0.1
    name: issues
    preferred: true
    service:
      $ref: github/v2.0.1/services/issues.yaml
    title: issues
    version: v2.0.1
  licenses:
    description: View various OSS licenses.
    id: licenses:v2.0.1
    name: licenses
    preferred: true
    service:
      $ref: github/v2.0.1/services/licenses.yaml
    title: licenses
    version: v2.0.1
  markdown:
    description: Render GitHub flavored markdown
    id: markdown:v2.0.1
    name: markdown
    preferred: true
    service:
      $ref: github/v2.0.1/services/markdown.yaml
    title: markdown
    version: v2.0.1
  orgs:
    description: Interact with GitHub Orgs.
    id: orgs:v2.0.1
    name: orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/orgs.yaml
    title: orgs
    version: v2.0.1
  teams:
    description: Interact with GitHub Teams.
    id: teams:v2.0.1
    name: teams
    preferred: true
    service:
      $ref: github/v2.0.1/services/teams.yaml
    title: teams
    version: v2.0.1
  actions_orgs:
    id: actions_orgs:v2.0.1
    name: actions_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/actions_orgs.yaml
    title: actions_orgs
    version: v2.0.1
  code_scanning_orgs:
    id: code_scanning_orgs:v2.0.1
    name: code_scanning_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/code_scanning_orgs.yaml
    title: code_scanning_orgs
    version: v2.0.1
  dependabot_orgs:
    id: dependabot_orgs:v2.0.1
    name: dependabot_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/dependabot_orgs.yaml
    title: dependabot_orgs
    version: v2.0.1
  activity_orgs:
    id: activity_orgs:v2.0.1
    name: activity_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/activity_orgs.yaml
    title: activity_orgs
    version: v2.0.1
  teams_orgs:
    id: teams_orgs:v2.0.1
    name: teams_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/teams_orgs.yaml
    title: teams_orgs
    version: v2.0.1
  apps_orgs:
    id: apps_orgs:v2.0.1
    name: apps_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/apps_orgs.yaml
    title: apps_orgs
    version: v2.0.1
  interactions_orgs:
    id: interactions_orgs:v2.0.1
    name: interactions_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/interactions_orgs.yaml
    title: interactions_orgs
    version: v2.0.1
  issues_orgs:
    id: issues_orgs:v2.0.1
    name: issues_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/issues_orgs.yaml
    title: issues_orgs
    version: v2.0.1
  migrations_orgs:
    id: migrations_orgs:v2.0.1
    name: migrations_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/migrations_orgs.yaml
    title: migrations_orgs
    version: v2.0.1
  packages_orgs:
    id: packages_orgs:v2.0.1
    name: packages_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/packages_orgs.yaml
    title: packages_orgs
    version: v2.0.1
  projects_orgs:
    id: projects_orgs:v2.0.1
    name: projects_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/projects_orgs.yaml
    title: projects_orgs
    version: v2.0.1
  repos_orgs:
    id: repos_orgs:v2.0.1
    name: repos_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/repos_orgs.yaml
    title: repos_orgs
    version: v2.0.1
  secret_scanning_orgs:
    id: secret_scanning_orgs:v2.0.1
    name: secret_scanning_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/secret_scanning_orgs.yaml
    title: secret_scanning_orgs
    version: v2.0.1
  billing_orgs:
    id: billing_orgs:v2.0.1
    name: billing_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/billing_orgs.yaml
    title: billing_orgs
    version: v2.0.1
  reactions_orgs:
    id: reactions_orgs:v2.0.1
    name: reactions_orgs
    preferred: true
    service:
      $ref: github/v2.0.1/services/reactions_orgs.yaml
    title: reactions_orgs
    version: v2.0.1
  projects:
    description: Interact with GitHub Projects.
    id: projects:v2.0.1
    name: projects
    preferred: true
    service:
      $ref: github/v2.0.1/services/projects.yaml
    title: projects
    version: v2.0.1
  rate_limit:
    id: rate_limit:v2.0.1
    name: rate_limit
    preferred: true
    service:
      $ref: github/v2.0.1/services/rate_limit.yaml
    title: rate_limit
    version: v2.0.1
  repos:
    description: Interact with GitHub Repos.
    id: repos:v2.0.1
    name: repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/repos.yaml
    title: repos
    version: v2.0.1
  actions_repos:
    id: actions_repos:v2.0.1
    name: actions_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/actions_repos.yaml
    title: actions_repos
    version: v2.0.1
  issues_repos:
    id: issues_repos:v2.0.1
    name: issues_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/issues_repos.yaml
    title: issues_repos
    version: v2.0.1
  checks_repos:
    id: checks_repos:v2.0.1
    name: checks_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/checks_repos.yaml
    title: checks_repos
    version: v2.0.1
  code_scanning_repos:
    id: code_scanning_repos:v2.0.1
    name: code_scanning_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/code_scanning_repos.yaml
    title: code_scanning_repos
    version: v2.0.1
  codespaces_repos:
    id: codespaces_repos:v2.0.1
    name: codespaces_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/codespaces_repos.yaml
    title: codespaces_repos
    version: v2.0.1
  reactions_repos:
    id: reactions_repos:v2.0.1
    name: reactions_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/reactions_repos.yaml
    title: reactions_repos
    version: v2.0.1
  dependabot_repos:
    id: dependabot_repos:v2.0.1
    name: dependabot_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/dependabot_repos.yaml
    title: dependabot_repos
    version: v2.0.1
  activity_repos:
    id: activity_repos:v2.0.1
    name: activity_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/activity_repos.yaml
    title: activity_repos
    version: v2.0.1
  git_repos:
    id: git_repos:v2.0.1
    name: git_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/git_repos.yaml
    title: git_repos
    version: v2.0.1
  migrations_repos:
    id: migrations_repos:v2.0.1
    name: migrations_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/migrations_repos.yaml
    title: migrations_repos
    version: v2.0.1
  apps_repos:
    id: apps_repos:v2.0.1
    name: apps_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/apps_repos.yaml
    title: apps_repos
    version: v2.0.1
  interactions_repos:
    id: interactions_repos:v2.0.1
    name: interactions_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/interactions_repos.yaml
    title: interactions_repos
    version: v2.0.1
  licenses_repos:
    id: licenses_repos:v2.0.1
    name: licenses_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/licenses_repos.yaml
    title: licenses_repos
    version: v2.0.1
  projects_repos:
    id: projects_repos:v2.0.1
    name: projects_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/projects_repos.yaml
    title: projects_repos
    version: v2.0.1
  pulls_repos:
    id: pulls_repos:v2.0.1
    name: pulls_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/pulls_repos.yaml
    title: pulls_repos
    version: v2.0.1
  secret_scanning_repos:
    id: secret_scanning_repos:v2.0.1
    name: secret_scanning_repos
    preferred: true
    service:
      $ref: github/v2.0.1/services/secret_scanning_repos.yaml
    title: secret_scanning_repos
    version: v2.0.1
  scim:
    description: Provisioning of GitHub organization membership for SCIM-enabled providers.
    id: scim:v2.0.1
    name: scim
    preferred: true
    service:
      $ref: github/v2.0.1/services/scim.yaml
    title: scim
    version: v2.0.1
  search:
    description: Look for stuff on GitHub.
    id: search:v2.0.1
    name: search
    preferred: true
    service:
      $ref: github/v2.0.1/services/search.yaml
    title: search
    version: v2.0.1
  reactions:
    description: Interact with reactions to various GitHub entities.
    id: reactions:v2.0.1
    name: reactions
    preferred: true
    service:
      $ref: github/v2.0.1/services/reactions.yaml
    title: reactions
    version: v2.0.1
  users:
    description: Interact with and view information about users and also current user.
    id: users:v2.0.1
    name: users
    preferred: true
    service:
      $ref: github/v2.0.1/services/users.yaml
    title: users
    version: v2.0.1
  codespaces:
    description: Endpoints to manage Codespaces using the REST API.
    id: codespaces:v2.0.1
    name: codespaces
    preferred: true
    service:
      $ref: github/v2.0.1/services/codespaces.yaml
    title: codespaces
    version: v2.0.1
  interactions:
    description: Owner or admin management of users interactions.
    id: interactions:v2.0.1
    name: interactions
    preferred: true
    service:
      $ref: github/v2.0.1/services/interactions.yaml
    title: interactions
    version: v2.0.1
  migrations:
    description: Move projects to or from GitHub.
    id: migrations:v2.0.1
    name: migrations
    preferred: true
    service:
      $ref: github/v2.0.1/services/migrations.yaml
    title: migrations
    version: v2.0.1
  packages:
    description: Manage packages for authenticated users and organizations.
    id: packages:v2.0.1
    name: packages
    preferred: true
    service:
      $ref: github/v2.0.1/services/packages.yaml
    title: packages
    version: v2.0.1
  billing:
    description: Monitor charges and usage from Actions and Packages.
    id: billing:v2.0.1
    name: billing
    preferred: true
    service:
      $ref: github/v2.0.1/services/billing.yaml
    title: billing
    version: v2.0.1
openapi: 3.0.3
id: github
name: github
version: v2.0.1
description: GitHub's v3 REST API.
title: GitHub v3 REST API
