openapi: 3.0.0
info:
  title: CertificateManager
  version: 1.0.0
paths: {}
components:
  schemas:
    ExpiryEventsConfiguration:
      type: object
      additionalProperties: false
      properties:
        DaysBeforeExpiry:
          type: integer
          minimum: 1
          maximum: 45
    AccountId:
      type: string
    Account:
      type: object
      properties:
        ExpiryEventsConfiguration:
          $ref: '#/components/schemas/ExpiryEventsConfiguration'
        AccountId:
          $ref: '#/components/schemas/AccountId'
      required:
        - ExpiryEventsConfiguration
      x-stackql-resource-name: account
      x-stackql-primaryIdentifier:
        - AccountId
      x-read-only-properties:
        - AccountId
      x-required-permissions:
        create:
          - acm:GetAccountConfiguration
          - acm:PutAccountConfiguration
        read:
          - acm:GetAccountConfiguration
        update:
          - acm:GetAccountConfiguration
          - acm:PutAccountConfiguration
        delete:
          - acm:GetAccountConfiguration
          - acm:PutAccountConfiguration
  x-stackQL-resources:
    account:
      name: account
      id: awscc.certificatemanager.account
      x-cfn-schema-name: Account
      x-type: get
      x-identifiers:
        - AccountId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.ExpiryEventsConfiguration') as expiry_events_configuration,
              JSON_EXTRACT(Properties, '$.AccountId') as account_id
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::CertificateManager::Account'
              AND data__Identifier = '<AccountId>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'ExpiryEventsConfiguration') as expiry_events_configuration,
                json_extract_path_text(Properties, 'AccountId') as account_id
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::CertificateManager::Account'
                AND data__Identifier = '<AccountId>'
                AND region = 'us-east-1'
