openapi: 3.0.0
info:
  title: CodePipeline
  version: 1.0.0
paths: {}
components:
  schemas:
    ConfigurationProperties:
      additionalProperties: false
      description: The configuration properties for the custom action.
      type: object
      properties:
        Description:
          description: 'The description of the action configuration property that is displayed to users. '
          type: string
        Key:
          description: Whether the configuration property is a key.
          type: boolean
        Name:
          description: The name of the action configuration property.
          type: string
        Queryable:
          description: >-
            Indicates that the property is used with PollForJobs. When creating a custom action, an action can have up to one queryable property. If it has one, that property must be both required and not secret.If you create a pipeline with a custom action type, and that custom action contains a queryable property, the value for that configuration property is subject to other restrictions. The value must be less than or equal to twenty (20) characters. The value can contain only alphanumeric
            characters, underscores, and hyphens. 
          type: boolean
        Required:
          description: Whether the configuration property is a required value.
          type: boolean
        Secret:
          description: Whether the configuration property is secret. Secrets are hidden from all calls except for GetJobDetails, GetThirdPartyJobDetails, PollForJobs, and PollForThirdPartyJobs.
          type: boolean
        Type:
          description: The type of the configuration property.
          type: string
      required:
        - Key
        - Name
        - Required
        - Secret
    ArtifactDetails:
      additionalProperties: false
      description: Returns information about the details of an artifact.
      type: object
      properties:
        MaximumCount:
          description: The maximum number of artifacts allowed for the action type.
          type: integer
        MinimumCount:
          description: The minimum number of artifacts allowed for the action type.
          type: integer
      required:
        - MaximumCount
        - MinimumCount
    Settings:
      additionalProperties: false
      description: 'Settings is a property of the AWS::CodePipeline::CustomActionType resource that provides URLs that users can access to view information about the CodePipeline custom action. '
      type: object
      properties:
        EntityUrlTemplate:
          description: 'The URL returned to the AWS CodePipeline console that provides a deep link to the resources of the external system, such as the configuration page for an AWS CodeDeploy deployment group. This link is provided as part of the action display in the pipeline. '
          type: string
        ExecutionUrlTemplate:
          description: 'The URL returned to the AWS CodePipeline console that contains a link to the top-level landing page for the external system, such as the console page for AWS CodeDeploy. This link is shown on the pipeline view page in the AWS CodePipeline console and provides a link to the execution entity of the external action. '
          type: string
        RevisionUrlTemplate:
          description: 'The URL returned to the AWS CodePipeline console that contains a link to the page where customers can update or change the configuration of the external action. '
          type: string
        ThirdPartyConfigurationUrl:
          description: The URL of a sign-up page where users can sign up for an external service and perform initial configuration of the action provided by that service.
          type: string
    Tag:
      type: object
      additionalProperties: false
      properties:
        Value:
          type: string
        Key:
          type: string
      required:
        - Value
        - Key
    CustomActionType:
      type: object
      properties:
        Category:
          description: The category of the custom action, such as a build action or a test action.
          type: string
        ConfigurationProperties:
          description: The configuration properties for the custom action.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/ConfigurationProperties'
        InputArtifactDetails:
          description: The details of the input artifact for the action, such as its commit ID.
          $ref: '#/components/schemas/ArtifactDetails'
        OutputArtifactDetails:
          description: The details of the output artifact of the action, such as its commit ID.
          $ref: '#/components/schemas/ArtifactDetails'
        Provider:
          description: The provider of the service used in the custom action, such as AWS CodeDeploy.
          type: string
        Settings:
          description: URLs that provide users information about this custom action.
          $ref: '#/components/schemas/Settings'
        Tags:
          description: Any tags assigned to the custom action.
          type: array
          uniqueItems: false
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
        Version:
          description: The version identifier of the custom action.
          type: string
        Id:
          type: string
      required:
        - Category
        - InputArtifactDetails
        - OutputArtifactDetails
        - Provider
        - Version
      x-stackql-resource-name: custom_action_type
      x-stackql-primaryIdentifier:
        - Category
        - Provider
        - Version
      x-create-only-properties:
        - Category
        - ConfigurationProperties
        - InputArtifactDetails
        - OutputArtifactDetails
        - Provider
        - Settings
        - Version
      x-read-only-properties:
        - Id
      x-required-permissions:
        create:
          - codepipeline:CreateCustomActionType
          - codepipeline:TagResource
          - codepipeline:ListActionTypes
        read:
          - codepipeline:ListActionTypes
          - codepipeline:ListTagsForResource
        update:
          - codepipeline:ListActionTypes
          - codepipeline:TagResource
          - codepipeline:UntagResource
        delete:
          - codepipeline:DeleteCustomActionType
          - codepipeline:ListActionTypes
        list:
          - codepipeline:ListActionTypes
  x-stackQL-resources:
    custom_action_types:
      name: custom_action_types
      id: awscc.codepipeline.custom_action_types
      x-cfn-schema-name: CustomActionType
      x-type: list
      x-identifiers:
        - Category
        - Provider
        - Version
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Category') as category,
              JSON_EXTRACT(Properties, '$.Provider') as provider,
              JSON_EXTRACT(Properties, '$.Version') as version
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::CodePipeline::CustomActionType'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Category') as category,
                json_extract_path_text(Properties, 'Provider') as provider,
                json_extract_path_text(Properties, 'Version') as version
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::CodePipeline::CustomActionType'
                AND region = 'us-east-1'
    custom_action_type:
      name: custom_action_type
      id: awscc.codepipeline.custom_action_type
      x-cfn-schema-name: CustomActionType
      x-type: get
      x-identifiers:
        - Category
        - Provider
        - Version
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Category') as category,
              JSON_EXTRACT(Properties, '$.ConfigurationProperties') as configuration_properties,
              JSON_EXTRACT(Properties, '$.InputArtifactDetails') as input_artifact_details,
              JSON_EXTRACT(Properties, '$.OutputArtifactDetails') as output_artifact_details,
              JSON_EXTRACT(Properties, '$.Provider') as provider,
              JSON_EXTRACT(Properties, '$.Settings') as settings,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.Version') as version,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::CodePipeline::CustomActionType'
              AND data__Identifier = '<Category>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Category') as category,
                json_extract_path_text(Properties, 'ConfigurationProperties') as configuration_properties,
                json_extract_path_text(Properties, 'InputArtifactDetails') as input_artifact_details,
                json_extract_path_text(Properties, 'OutputArtifactDetails') as output_artifact_details,
                json_extract_path_text(Properties, 'Provider') as provider,
                json_extract_path_text(Properties, 'Settings') as settings,
                json_extract_path_text(Properties, 'Tags') as tags,
                json_extract_path_text(Properties, 'Version') as version,
                json_extract_path_text(Properties, 'Id') as id
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::CodePipeline::CustomActionType'
                AND data__Identifier = '<Category>'
                AND region = 'us-east-1'
