openapi: 3.0.0
info:
  title: CodeGuruReviewer
  version: 1.0.0
paths: {}
components:
  schemas:
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      additionalProperties: false
      properties:
        Key:
          description: 'The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. The allowed characters across services are: letters, numbers, and spaces representable in UTF-8, and the following characters: + - = . _ : / @.'
          type: string
          minLength: 1
          maxLength: 128
        Value:
          description: 'The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length. The allowed characters across services are: letters, numbers, and spaces representable in UTF-8, and the following characters: + - = . _ : / @.'
          type: string
          minLength: 0
          maxLength: 256
      required:
        - Value
        - Key
    RepositoryAssociation:
      type: object
      properties:
        Name:
          description: Name of the repository to be associated.
          type: string
          minLength: 1
          maxLength: 100
          pattern: ^\S[\w.-]*$
        Type:
          description: The type of repository to be associated.
          type: string
          enum:
            - CodeCommit
            - Bitbucket
            - GitHubEnterpriseServer
            - S3Bucket
        Owner:
          description: The owner of the repository. For a Bitbucket repository, this is the username for the account that owns the repository.
          type: string
          minLength: 1
          maxLength: 100
          pattern: ^\S(.*\S)?$
        BucketName:
          description: The name of the S3 bucket associated with an associated S3 repository. It must start with `codeguru-reviewer-`.
          type: string
          minLength: 3
          maxLength: 63
          pattern: ^\S(.*\S)?$
        ConnectionArn:
          description: The Amazon Resource Name (ARN) of an AWS CodeStar Connections connection.
          type: string
          minLength: 0
          maxLength: 256
          pattern: arn:aws(-[\w]+)*:.+:.+:[0-9]{12}:.+
        AssociationArn:
          description: The Amazon Resource Name (ARN) of the repository association.
          type: string
          minLength: 0
          maxLength: 256
          pattern: arn:aws(-[\w]+)*:.+:.+:[0-9]{12}:.+
        Tags:
          description: The tags associated with a repository association.
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          maxItems: 50
          uniqueItems: false
      required:
        - Name
        - Type
      x-stackql-resource-name: repository_association
      x-stackql-primaryIdentifier:
        - AssociationArn
      x-create-only-properties:
        - Name
        - Type
        - Tags
        - BucketName
        - Owner
        - ConnectionArn
      x-read-only-properties:
        - AssociationArn
      x-required-permissions:
        create:
          - codeguru-reviewer:DescribeRepositoryAssociation
          - codeguru-reviewer:AssociateRepository
          - codeguru-reviewer:TagResource
          - iam:CreateServiceLinkedRole
          - codecommit:TagResource
          - codecommit:GitPull
          - codecommit:TagResource
          - events:PutRule
          - events:PutTargets
          - codestar-connections:ListBranches
          - codestar-connections:ListRepositories
          - codestar-connections:ListTagsForResource
          - codestar-connections:PassConnection
          - codestar-connections:TagResource
          - codestar-connections:UseConnection
          - s3:ListBucket
        read:
          - codeguru-reviewer:DescribeRepositoryAssociation
          - codeguru-reviewer:ListTagsForResource
        delete:
          - codeguru-reviewer:DescribeRepositoryAssociation
          - codeguru-reviewer:DisassociateRepository
          - codecommit:UntagResource
          - events:DeleteRule
          - events:RemoveTargets
          - codestar-connections:UntagResource
          - codestar-connections:ListTagsForResource
        list:
          - codeguru-reviewer:ListRepositoryAssociations
  x-stackQL-resources:
    repository_associations:
      name: repository_associations
      id: awscc.codegurureviewer.repository_associations
      x-cfn-schema-name: RepositoryAssociation
      x-type: list
      x-identifiers:
        - AssociationArn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.AssociationArn') as association_arn
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::CodeGuruReviewer::RepositoryAssociation'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'AssociationArn') as association_arn
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::CodeGuruReviewer::RepositoryAssociation'
                AND region = 'us-east-1'
    repository_association:
      name: repository_association
      id: awscc.codegurureviewer.repository_association
      x-cfn-schema-name: RepositoryAssociation
      x-type: get
      x-identifiers:
        - AssociationArn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Type') as type,
              JSON_EXTRACT(Properties, '$.Owner') as owner,
              JSON_EXTRACT(Properties, '$.BucketName') as bucket_name,
              JSON_EXTRACT(Properties, '$.ConnectionArn') as connection_arn,
              JSON_EXTRACT(Properties, '$.AssociationArn') as association_arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::CodeGuruReviewer::RepositoryAssociation'
              AND data__Identifier = '<AssociationArn>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'Name') as name,
                json_extract_path_text(Properties, 'Type') as type,
                json_extract_path_text(Properties, 'Owner') as owner,
                json_extract_path_text(Properties, 'BucketName') as bucket_name,
                json_extract_path_text(Properties, 'ConnectionArn') as connection_arn,
                json_extract_path_text(Properties, 'AssociationArn') as association_arn,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::CodeGuruReviewer::RepositoryAssociation'
                AND data__Identifier = '<AssociationArn>'
                AND region = 'us-east-1'
