openapi: 3.0.0
info:
  title: ConnectCampaigns
  version: 1.0.0
paths: {}
components:
  schemas:
    DialerConfig:
      type: object
      description: The possible types of dialer config parameters
      properties:
        ProgressiveDialerConfig:
          $ref: '#/components/schemas/ProgressiveDialerConfig'
        PredictiveDialerConfig:
          $ref: '#/components/schemas/PredictiveDialerConfig'
        AgentlessDialerConfig:
          $ref: '#/components/schemas/AgentlessDialerConfig'
      additionalProperties: false
      oneOf:
        - required:
            - ProgressiveDialerConfig
        - required:
            - PredictiveDialerConfig
        - required:
            - AgentlessDialerConfig
    OutboundCallConfig:
      type: object
      description: The configuration used for outbound calls.
      properties:
        ConnectContactFlowArn:
          type: string
          maxLength: 500
          description: The identifier of the contact flow for the outbound call.
          pattern: ^arn:aws[-a-z0-9]*:connect:[-a-z0-9]*:[0-9]{12}:instance/[-a-zA-Z0-9]*/contact-flow/[-a-zA-Z0-9]*$
        ConnectSourcePhoneNumber:
          type: string
          maxLength: 100
          description: The phone number associated with the Amazon Connect instance, in E.164 format. If you do not specify a source phone number, you must specify a queue.
        ConnectQueueArn:
          type: string
          maxLength: 500
          description: The queue for the call. If you specify a queue, the phone displayed for caller ID is the phone number specified in the queue. If you do not specify a queue, the queue defined in the contact flow is used. If you do not specify a queue, you must specify a source phone number.
          pattern: ^arn:aws[-a-z0-9]*:connect:[-a-z0-9]*:[0-9]{12}:instance/[-a-zA-Z0-9]*/queue/[-a-zA-Z0-9]*$
        AnswerMachineDetectionConfig:
          $ref: '#/components/schemas/AnswerMachineDetectionConfig'
      required:
        - ConnectContactFlowArn
      additionalProperties: false
    PredictiveDialerConfig:
      type: object
      description: Predictive Dialer config
      properties:
        BandwidthAllocation:
          type: number
          maximum: 1
          minimum: 0
          description: The bandwidth allocation of a queue resource.
        DialingCapacity:
          type: number
          maximum: 1
          minimum: 0.01
          description: Allocates dialing capacity for this campaign between multiple active campaigns.
      required:
        - BandwidthAllocation
      additionalProperties: false
    ProgressiveDialerConfig:
      type: object
      description: Progressive Dialer config
      properties:
        BandwidthAllocation:
          type: number
          maximum: 1
          minimum: 0
          description: The bandwidth allocation of a queue resource.
        DialingCapacity:
          type: number
          maximum: 1
          minimum: 0.01
          description: Allocates dialing capacity for this campaign between multiple active campaigns.
      required:
        - BandwidthAllocation
      additionalProperties: false
    AgentlessDialerConfig:
      type: object
      description: Agentless Dialer config
      properties:
        DialingCapacity:
          type: number
          maximum: 1
          minimum: 0.01
          description: Allocates dialing capacity for this campaign between multiple active campaigns.
      required: []
      additionalProperties: false
    AnswerMachineDetectionConfig:
      type: object
      description: The configuration used for answering machine detection during outbound calls
      properties:
        EnableAnswerMachineDetection:
          type: boolean
          description: Flag to decided whether outbound calls should have answering machine detection enabled or not
      required:
        - EnableAnswerMachineDetection
      additionalProperties: false
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      additionalProperties: false
      properties:
        Key:
          type: string
          description: 'The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          minLength: 1
          maxLength: 128
          pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
        Value:
          type: string
          description: The value for the tag. You can specify a value that's 1 to 256 characters in length.
          minLength: 1
          maxLength: 256
      required:
        - Key
        - Value
    Campaign:
      type: object
      properties:
        ConnectInstanceArn:
          type: string
          maxLength: 256
          minLength: 0
          description: Amazon Connect Instance Arn
          pattern: ^arn:aws[-a-z0-9]*:connect:[-a-z0-9]*:[0-9]{12}:instance/[-a-zA-Z0-9]*$
        DialerConfig:
          $ref: '#/components/schemas/DialerConfig'
        Arn:
          type: string
          maxLength: 256
          minLength: 0
          description: Amazon Connect Campaign Arn
          pattern: ^arn:aws[-a-z0-9]*:connect-campaigns:[-a-z0-9]*:[0-9]{12}:campaign/[-a-zA-Z0-9]*$
        Name:
          type: string
          maxLength: 127
          minLength: 1
          description: Amazon Connect Campaign Name
        OutboundCallConfig:
          $ref: '#/components/schemas/OutboundCallConfig'
        Tags:
          type: array
          maxItems: 50
          uniqueItems: true
          x-insertionOrder: false
          description: One or more tags.
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - ConnectInstanceArn
        - DialerConfig
        - Name
        - OutboundCallConfig
      x-stackql-resource-name: campaign
      x-stackql-primaryIdentifier:
        - Arn
      x-create-only-properties:
        - ConnectInstanceArn
      x-read-only-properties:
        - Arn
      x-required-permissions:
        create:
          - connect-campaigns:CreateCampaign
          - connect-campaigns:DescribeCampaign
          - connect-campaigns:TagResource
          - connect:DescribeContactFlow
          - connect:DescribeInstance
          - connect:DescribeQueue
        read:
          - connect-campaigns:DescribeCampaign
        delete:
          - connect-campaigns:DeleteCampaign
        list:
          - connect-campaigns:ListCampaigns
        update:
          - connect-campaigns:UpdateCampaignDialerConfig
          - connect-campaigns:UpdateCampaignName
          - connect-campaigns:UpdateCampaignOutboundCallConfig
          - connect-campaigns:TagResource
          - connect-campaigns:UntagResource
          - connect-campaigns:DescribeCampaign
  x-stackQL-resources:
    campaigns:
      name: campaigns
      id: awscc.connectcampaigns.campaigns
      x-cfn-schema-name: Campaign
      x-type: list
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::ConnectCampaigns::Campaign'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Arn') as arn
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::ConnectCampaigns::Campaign'
                AND region = 'us-east-1'
    campaign:
      name: campaign
      id: awscc.connectcampaigns.campaign
      x-cfn-schema-name: Campaign
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.ConnectInstanceArn') as connect_instance_arn,
              JSON_EXTRACT(Properties, '$.DialerConfig') as dialer_config,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.OutboundCallConfig') as outbound_call_config,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::ConnectCampaigns::Campaign'
              AND data__Identifier = '<Arn>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'ConnectInstanceArn') as connect_instance_arn,
                json_extract_path_text(Properties, 'DialerConfig') as dialer_config,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'Name') as name,
                json_extract_path_text(Properties, 'OutboundCallConfig') as outbound_call_config,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::ConnectCampaigns::Campaign'
                AND data__Identifier = '<Arn>'
                AND region = 'us-east-1'
