openapi: 3.0.0
info:
  title: CUR
  version: 1.0.0
paths: {}
components:
  schemas:
    ReportDefinition:
      type: object
      properties:
        ReportName:
          description: The name of the report that you want to create. The name must be unique, is case sensitive, and can't include spaces.
          type: string
          minLength: 1
          maxLength: 256
          pattern: '[0-9A-Za-z!\-_.*\''()]+'
        TimeUnit:
          description: The granularity of the line items in the report.
          type: string
          enum:
            - HOURLY
            - DAILY
            - MONTHLY
        Format:
          description: The format that AWS saves the report in.
          type: string
          enum:
            - textORcsv
            - Parquet
        Compression:
          description: The compression format that AWS uses for the report.
          type: string
          enum:
            - ZIP
            - GZIP
            - Parquet
        AdditionalSchemaElements:
          description: A list of strings that indicate additional content that Amazon Web Services includes in the report, such as individual resource IDs.
          type: array
          default: []
          items:
            description: Whether or not AWS includes resource IDs in the report.
            type: string
            enum:
              - RESOURCES
        S3Bucket:
          description: The S3 bucket where AWS delivers the report.
          type: string
          minLength: 1
          maxLength: 256
          pattern: '[A-Za-z0-9_\.\-]+'
        S3Prefix:
          description: The prefix that AWS adds to the report name when AWS delivers the report. Your prefix can't include spaces.
          type: string
          minLength: 1
          maxLength: 256
          pattern: '[0-9A-Za-z!\-_.*\''()/]*'
        S3Region:
          description: The region of the S3 bucket that AWS delivers the report into.
          type: string
        AdditionalArtifacts:
          description: A list of manifests that you want Amazon Web Services to create for this report.
          type: array
          default: []
          items:
            description: The types of manifest that you want AWS to create for this report.
            type: string
            enum:
              - REDSHIFT
              - QUICKSIGHT
              - ATHENA
        RefreshClosedReports:
          description: Whether you want Amazon Web Services to update your reports after they have been finalized if Amazon Web Services detects charges related to previous months. These charges can include refunds, credits, or support fees.
          type: boolean
        ReportVersioning:
          description: Whether you want Amazon Web Services to overwrite the previous version of each report or to deliver the report in addition to the previous versions.
          type: string
          enum:
            - CREATE_NEW_REPORT
            - OVERWRITE_REPORT
        BillingViewArn:
          description: The Amazon resource name of the billing view. You can get this value by using the billing view service public APIs.
          type: string
          default: null
          pattern: (arn:aws(-cn)?:billing::[0-9]{12}:billingview/)?[a-zA-Z0-9_\+=\.\-@].{1,30}
          minLength: 1
          maxLength: 128
      required:
        - ReportName
        - TimeUnit
        - Format
        - Compression
        - S3Bucket
        - S3Prefix
        - S3Region
        - RefreshClosedReports
        - ReportVersioning
      x-stackql-resource-name: report_definition
      x-stackql-primaryIdentifier:
        - ReportName
      x-create-only-properties:
        - ReportName
        - AdditionalSchemaElements
        - TimeUnit
        - ReportVersioning
        - BillingViewArn
      x-required-permissions:
        create:
          - cur:PutReportDefinition
        read:
          - cur:DescribeReportDefinitions
        update:
          - cur:DescribeReportDefinitions
          - cur:ModifyReportDefinition
        delete:
          - cur:DescribeReportDefinitions
          - cur:DeleteReportDefinition
        list:
          - cur:DescribeReportDefinitions
  x-stackQL-resources:
    report_definitions:
      name: report_definitions
      id: awscc.cur.report_definitions
      x-cfn-schema-name: ReportDefinition
      x-type: list
      x-identifiers:
        - ReportName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ReportName') as report_name
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::CUR::ReportDefinition'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'ReportName') as report_name
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::CUR::ReportDefinition'
                AND region = 'us-east-1'
    report_definition:
      name: report_definition
      id: awscc.cur.report_definition
      x-cfn-schema-name: ReportDefinition
      x-type: get
      x-identifiers:
        - ReportName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ReportName') as report_name,
              JSON_EXTRACT(Properties, '$.TimeUnit') as time_unit,
              JSON_EXTRACT(Properties, '$.Format') as _format,
              JSON_EXTRACT(Properties, '$.Compression') as compression,
              JSON_EXTRACT(Properties, '$.AdditionalSchemaElements') as additional_schema_elements,
              JSON_EXTRACT(Properties, '$.S3Bucket') as s3_bucket,
              JSON_EXTRACT(Properties, '$.S3Prefix') as s3_prefix,
              JSON_EXTRACT(Properties, '$.S3Region') as s3_region,
              JSON_EXTRACT(Properties, '$.AdditionalArtifacts') as additional_artifacts,
              JSON_EXTRACT(Properties, '$.RefreshClosedReports') as refresh_closed_reports,
              JSON_EXTRACT(Properties, '$.ReportVersioning') as report_versioning,
              JSON_EXTRACT(Properties, '$.BillingViewArn') as billing_view_arn
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::CUR::ReportDefinition'
              AND data__Identifier = '<ReportName>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'ReportName') as report_name,
                json_extract_path_text(Properties, 'TimeUnit') as time_unit,
                json_extract_path_text(Properties, 'Format') as _format,
                json_extract_path_text(Properties, 'Compression') as compression,
                json_extract_path_text(Properties, 'AdditionalSchemaElements') as additional_schema_elements,
                json_extract_path_text(Properties, 'S3Bucket') as s3_bucket,
                json_extract_path_text(Properties, 'S3Prefix') as s3_prefix,
                json_extract_path_text(Properties, 'S3Region') as s3_region,
                json_extract_path_text(Properties, 'AdditionalArtifacts') as additional_artifacts,
                json_extract_path_text(Properties, 'RefreshClosedReports') as refresh_closed_reports,
                json_extract_path_text(Properties, 'ReportVersioning') as report_versioning,
                json_extract_path_text(Properties, 'BillingViewArn') as billing_view_arn
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::CUR::ReportDefinition'
                AND data__Identifier = '<ReportName>'
                AND region = 'us-east-1'
