openapi: 3.0.0
info:
  title: Detective
  version: 1.0.0
paths: {}
components:
  schemas:
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      properties:
        Key:
          type: string
          description: 'The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. Valid characters are Unicode letters, digits, white space, and any of the following symbols: _ . : / = + - @ '
          minLength: 1
          maxLength: 128
        Value:
          type: string
          description: 'The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. Valid characters are Unicode letters, digits, white space, and any of the following symbols: _ . : / = + - @ '
          minLength: 0
          maxLength: 256
      additionalProperties: false
    Graph:
      type: object
      properties:
        Arn:
          type: string
          description: The Detective graph ARN
        Tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        AutoEnableMembers:
          type: boolean
          default: false
          description: Indicates whether to automatically enable new organization accounts as member accounts in the organization behavior graph.
      x-stackql-resource-name: graph
      x-stackql-primaryIdentifier:
        - Arn
      x-read-only-properties:
        - Arn
      x-required-permissions:
        create:
          - detective:CreateGraph
          - detective:UpdateOrganizationConfiguration
          - organizations:DescribeOrganization
        update:
          - detective:UntagResource
          - detective:TagResource
          - detective:ListTagsForResource
          - detective:UpdateOrganizationConfiguration
          - organizations:DescribeOrganization
        read:
          - detective:ListGraphs
          - detective:ListTagsForResource
          - detective:DescribeOrganizationConfiguration
          - organizations:DescribeOrganization
        delete:
          - detective:DeleteGraph
        list:
          - detective:ListGraphs
          - detective:ListTagsForResource
          - detective:DescribeOrganizationConfiguration
          - organizations:DescribeOrganization
    MemberInvitation:
      type: object
      properties:
        GraphArn:
          description: The ARN of the graph to which the member account will be invited
          type: string
          pattern: arn:aws(-[\w]+)*:detective:(([a-z]+-)+[0-9]+):[0-9]{12}:graph:[0-9a-f]{32}
        MemberId:
          description: The AWS account ID to be invited to join the graph as a member
          type: string
          pattern: '[0-9]{12}'
        MemberEmailAddress:
          description: The root email address for the account to be invited, for validation. Updating this field has no effect.
          type: string
          pattern: .*@.*
        DisableEmailNotification:
          description: When set to true, invitation emails are not sent to the member accounts. Member accounts must still accept the invitation before they are added to the behavior graph. Updating this field has no effect.
          type: boolean
          default: false
        Message:
          description: A message to be included in the email invitation sent to the invited account. Updating this field has no effect.
          type: string
          minLength: 1
          maxLength: 1000
      required:
        - GraphArn
        - MemberId
        - MemberEmailAddress
      x-stackql-resource-name: member_invitation
      x-stackql-primaryIdentifier:
        - GraphArn
        - MemberId
      x-create-only-properties:
        - GraphArn
        - MemberId
      x-required-permissions:
        create:
          - detective:CreateMembers
          - detective:GetMembers
        read:
          - detective:GetMembers
        update: []
        delete:
          - detective:DeleteMembers
        list:
          - detective:ListGraphs
          - detective:ListMembers
    OrganizationAdmin:
      type: object
      properties:
        AccountId:
          description: The account ID of the account that should be registered as your Organization's delegated administrator for Detective
          type: string
          pattern: '[0-9]{12}'
        GraphArn:
          type: string
          description: The Detective graph ARN
      required:
        - AccountId
      x-stackql-resource-name: organization_admin
      x-stackql-primaryIdentifier:
        - AccountId
      x-create-only-properties:
        - AccountId
      x-read-only-properties:
        - GraphArn
      x-required-permissions:
        create:
          - detective:EnableOrganizationAdminAccount
          - detective:ListOrganizationAdminAccount
          - iam:CreateServiceLinkedRole
          - organizations:RegisterDelegatedAdministrator
          - organizations:DescribeOrganization
          - organizations:EnableAWSServiceAccess
          - organizations:ListAccounts
        read:
          - detective:ListOrganizationAdminAccount
          - organizations:DescribeOrganization
        update: []
        delete:
          - detective:DisableOrganizationAdminAccount
          - detective:ListOrganizationAdminAccount
          - organizations:DescribeOrganization
        list:
          - detective:ListOrganizationAdminAccount
          - organizations:DescribeOrganization
  x-stackQL-resources:
    graphs:
      name: graphs
      id: awscc.detective.graphs
      x-cfn-schema-name: Graph
      x-type: list
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::Detective::Graph'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Arn') as arn
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::Detective::Graph'
                AND region = 'us-east-1'
    graph:
      name: graph
      id: awscc.detective.graph
      x-cfn-schema-name: Graph
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.AutoEnableMembers') as auto_enable_members
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::Detective::Graph'
              AND data__Identifier = '<Arn>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'Tags') as tags,
                json_extract_path_text(Properties, 'AutoEnableMembers') as auto_enable_members
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::Detective::Graph'
                AND data__Identifier = '<Arn>'
                AND region = 'us-east-1'
    member_invitations:
      name: member_invitations
      id: awscc.detective.member_invitations
      x-cfn-schema-name: MemberInvitation
      x-type: list
      x-identifiers:
        - GraphArn
        - MemberId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.GraphArn') as graph_arn,
              JSON_EXTRACT(Properties, '$.MemberId') as member_id
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::Detective::MemberInvitation'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'GraphArn') as graph_arn,
                json_extract_path_text(Properties, 'MemberId') as member_id
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::Detective::MemberInvitation'
                AND region = 'us-east-1'
    member_invitation:
      name: member_invitation
      id: awscc.detective.member_invitation
      x-cfn-schema-name: MemberInvitation
      x-type: get
      x-identifiers:
        - GraphArn
        - MemberId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.GraphArn') as graph_arn,
              JSON_EXTRACT(Properties, '$.MemberId') as member_id,
              JSON_EXTRACT(Properties, '$.MemberEmailAddress') as member_email_address,
              JSON_EXTRACT(Properties, '$.DisableEmailNotification') as disable_email_notification,
              JSON_EXTRACT(Properties, '$.Message') as message
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::Detective::MemberInvitation'
              AND data__Identifier = '<GraphArn>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'GraphArn') as graph_arn,
                json_extract_path_text(Properties, 'MemberId') as member_id,
                json_extract_path_text(Properties, 'MemberEmailAddress') as member_email_address,
                json_extract_path_text(Properties, 'DisableEmailNotification') as disable_email_notification,
                json_extract_path_text(Properties, 'Message') as message
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::Detective::MemberInvitation'
                AND data__Identifier = '<GraphArn>'
                AND region = 'us-east-1'
    organization_admins:
      name: organization_admins
      id: awscc.detective.organization_admins
      x-cfn-schema-name: OrganizationAdmin
      x-type: list
      x-identifiers:
        - AccountId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.AccountId') as account_id
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::Detective::OrganizationAdmin'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'AccountId') as account_id
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::Detective::OrganizationAdmin'
                AND region = 'us-east-1'
    organization_admin:
      name: organization_admin
      id: awscc.detective.organization_admin
      x-cfn-schema-name: OrganizationAdmin
      x-type: get
      x-identifiers:
        - AccountId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.AccountId') as account_id,
              JSON_EXTRACT(Properties, '$.GraphArn') as graph_arn
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::Detective::OrganizationAdmin'
              AND data__Identifier = '<AccountId>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'AccountId') as account_id,
                json_extract_path_text(Properties, 'GraphArn') as graph_arn
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::Detective::OrganizationAdmin'
                AND data__Identifier = '<AccountId>'
                AND region = 'us-east-1'
