openapi: 3.0.0
info:
  title: DirectoryService
  version: 1.0.0
paths: {}
components:
  schemas:
    VpcSettings:
      x-$comment: Contains VPC information
      type: object
      additionalProperties: false
      properties:
        SubnetIds:
          description: The identifiers of the subnets for the directory servers. The two subnets must be in different Availability Zones. AWS Directory Service specifies a directory server and a DNS server in each of these subnets.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            type: string
        VpcId:
          description: The identifier of the VPC in which to create the directory.
          type: string
      required:
        - VpcId
        - SubnetIds
    SimpleAD:
      type: object
      properties:
        DirectoryId:
          description: The unique identifier for a directory.
          type: string
        Alias:
          description: The alias for a directory.
          type: string
        DnsIpAddresses:
          description: The IP addresses of the DNS servers for the directory, such as [ "172.31.3.154", "172.31.63.203" ].
          type: array
          uniqueItems: false
          x-insertionOrder: false
          items:
            type: string
        CreateAlias:
          description: The name of the configuration set.
          type: boolean
        Description:
          description: Description for the directory.
          type: string
        EnableSso:
          description: Whether to enable single sign-on for a Simple Active Directory in AWS.
          type: boolean
        Name:
          description: The fully qualified domain name for the AWS Managed Simple AD directory.
          type: string
        Password:
          description: The password for the default administrative user named Admin.
          type: string
        ShortName:
          description: The NetBIOS name for your domain.
          type: string
        Size:
          description: The size of the directory.
          type: string
        VpcSettings:
          description: VPC settings of the Simple AD directory server in AWS.
          $ref: '#/components/schemas/VpcSettings'
      required:
        - VpcSettings
        - Size
        - Name
      x-stackql-resource-name: simple_ad
      x-stackql-primaryIdentifier:
        - DirectoryId
      x-create-only-properties:
        - Size
        - VpcSettings
        - Name
        - Password
        - ShortName
        - Description
        - CreateAlias
      x-read-only-properties:
        - Alias
        - DnsIpAddresses
        - DirectoryId
      x-required-permissions:
        create:
          - ds:CreateDirectory
          - ds:CreateAlias
          - ds:EnableSso
          - ds:DescribeDirectories
          - ec2:DescribeSubnets
          - ec2:DescribeVpcs
          - ec2:CreateSecurityGroup
          - ec2:CreateNetworkInterface
          - ec2:DescribeNetworkInterfaces
          - ec2:AuthorizeSecurityGroupIngress
          - ec2:AuthorizeSecurityGroupEgress
          - ec2:CreateTags
        read:
          - ds:DescribeDirectories
        update:
          - ds:EnableSso
          - ds:DisableSso
          - ds:DescribeDirectories
        delete:
          - ds:DeleteDirectory
          - ds:DescribeDirectories
          - ec2:DescribeNetworkInterfaces
          - ec2:DeleteSecurityGroup
          - ec2:DeleteNetworkInterface
          - ec2:RevokeSecurityGroupIngress
          - ec2:RevokeSecurityGroupEgress
          - ec2:DeleteTags
        list:
          - ds:DescribeDirectories
  x-stackQL-resources:
    simple_ads:
      name: simple_ads
      id: awscc.directoryservice.simple_ads
      x-cfn-schema-name: SimpleAD
      x-type: list
      x-identifiers:
        - DirectoryId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.DirectoryId') as directory_id
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::DirectoryService::SimpleAD'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'DirectoryId') as directory_id
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::DirectoryService::SimpleAD'
                AND region = 'us-east-1'
    simple_ad:
      name: simple_ad
      id: awscc.directoryservice.simple_ad
      x-cfn-schema-name: SimpleAD
      x-type: get
      x-identifiers:
        - DirectoryId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.DirectoryId') as directory_id,
              JSON_EXTRACT(Properties, '$.Alias') as alias,
              JSON_EXTRACT(Properties, '$.DnsIpAddresses') as dns_ip_addresses,
              JSON_EXTRACT(Properties, '$.CreateAlias') as create_alias,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.EnableSso') as enable_sso,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Password') as password,
              JSON_EXTRACT(Properties, '$.ShortName') as short_name,
              JSON_EXTRACT(Properties, '$.Size') as size,
              JSON_EXTRACT(Properties, '$.VpcSettings') as vpc_settings
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::DirectoryService::SimpleAD'
              AND data__Identifier = '<DirectoryId>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'DirectoryId') as directory_id,
                json_extract_path_text(Properties, 'Alias') as alias,
                json_extract_path_text(Properties, 'DnsIpAddresses') as dns_ip_addresses,
                json_extract_path_text(Properties, 'CreateAlias') as create_alias,
                json_extract_path_text(Properties, 'Description') as description,
                json_extract_path_text(Properties, 'EnableSso') as enable_sso,
                json_extract_path_text(Properties, 'Name') as name,
                json_extract_path_text(Properties, 'Password') as password,
                json_extract_path_text(Properties, 'ShortName') as short_name,
                json_extract_path_text(Properties, 'Size') as size,
                json_extract_path_text(Properties, 'VpcSettings') as vpc_settings
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::DirectoryService::SimpleAD'
                AND data__Identifier = '<DirectoryId>'
                AND region = 'us-east-1'
