openapi: 3.0.0
info:
  title: FSx
  version: 1.0.0
paths: {}
components:
  schemas:
    EventType:
      type: string
      enum:
        - NEW
        - CHANGED
        - DELETED
    EventTypes:
      type: array
      x-insertionOrder: false
      uniqueItems: true
      items:
        $ref: '#/components/schemas/EventType'
      maxItems: 3
    AutoImportPolicy:
      description: |-
        Describes the data repository association's automatic import policy. The AutoImportPolicy defines how Amazon FSx keeps your file metadata and directory listings up to date by importing changes to your Amazon FSx for Lustre file system as you modify objects in a linked S3 bucket.
         The ``AutoImportPolicy`` is only supported on Amazon FSx for Lustre file systems with a data repository association.
      type: object
      additionalProperties: false
      properties:
        Events:
          $ref: '#/components/schemas/EventTypes'
          description: |-
            The ``AutoImportPolicy`` can have the following event values:
              +   ``NEW`` - Amazon FSx automatically imports metadata of files added to the linked S3 bucket that do not currently exist in the FSx file system.
              +   ``CHANGED`` - Amazon FSx automatically updates file metadata and invalidates existing file content on the file system as files change in the data repository.
              +   ``DELETED`` - Amazon FSx automatically deletes files on the file system as corresponding files are deleted in the data repository.
              
             You can define any combination of event types for your ``AutoImportPolicy``.
      required:
        - Events
    AutoExportPolicy:
      description: |-
        Describes a data repository association's automatic export policy. The ``AutoExportPolicy`` defines the types of updated objects on the file system that will be automatically exported to the data repository. As you create, modify, or delete files, Amazon FSx for Lustre automatically exports the defined changes asynchronously once your application finishes modifying the file.
         The ``AutoExportPolicy`` is only supported on Amazon FSx for Lustre file systems with a data repository association.
      type: object
      additionalProperties: false
      properties:
        Events:
          $ref: '#/components/schemas/EventTypes'
          description: |-
            The ``AutoExportPolicy`` can have the following event values:
              +   ``NEW`` - New files and directories are automatically exported to the data repository as they are added to the file system.
              +   ``CHANGED`` - Changes to files and directories on the file system are automatically exported to the data repository.
              +   ``DELETED`` - Files and directories are automatically deleted on the data repository when they are deleted on the file system.
              
             You can define any combination of event types for your ``AutoExportPolicy``.
      required:
        - Events
    Tag:
      description: Specifies a key-value pair for a resource tag.
      type: object
      additionalProperties: false
      properties:
        Key:
          type: string
          description: A value that specifies the ``TagKey``, the name of the tag. Tag keys must be unique for the resource to which they are attached.
          minLength: 1
          maxLength: 128
        Value:
          type: string
          description: 'A value that specifies the ``TagValue``, the value assigned to the corresponding tag key. Tag values can be null and don''t have to be unique in a tag set. For example, you can have a key-value pair in a tag set of ``finances : April`` and also of ``payroll : April``.'
          minLength: 0
          maxLength: 256
      required:
        - Key
        - Value
    S3:
      description: The configuration for an Amazon S3 data repository linked to an Amazon FSx Lustre file system with a data repository association. The configuration defines which file events (new, changed, or deleted files or directories) are automatically imported from the linked data repository to the file system or automatically exported from the file system to the data repository.
      type: object
      additionalProperties: false
      properties:
        AutoImportPolicy:
          $ref: '#/components/schemas/AutoImportPolicy'
          description: |-
            Describes the data repository association's automatic import policy. The AutoImportPolicy defines how Amazon FSx keeps your file metadata and directory listings up to date by importing changes to your Amazon FSx for Lustre file system as you modify objects in a linked S3 bucket.
             The ``AutoImportPolicy`` is only supported on Amazon FSx for Lustre file systems with a data repository association.
        AutoExportPolicy:
          $ref: '#/components/schemas/AutoExportPolicy'
          description: |-
            Describes a data repository association's automatic export policy. The ``AutoExportPolicy`` defines the types of updated objects on the file system that will be automatically exported to the data repository. As you create, modify, or delete files, Amazon FSx for Lustre automatically exports the defined changes asynchronously once your application finishes modifying the file.
             The ``AutoExportPolicy`` is only supported on Amazon FSx for Lustre file systems with a data repository association.
    DataRepositoryAssociation:
      type: object
      properties:
        AssociationId:
          type: string
          description: ''
        ResourceARN:
          type: string
          description: ''
        FileSystemId:
          type: string
          description: The ID of the file system on which the data repository association is configured.
        FileSystemPath:
          type: string
          description: >-
            A path on the Amazon FSx for Lustre file system that points to a high-level directory (such as ``/ns1/``) or subdirectory (such as ``/ns1/subdir/``) that will be mapped 1-1 with ``DataRepositoryPath``. The leading forward slash in the name is required. Two data repository associations cannot have overlapping file system paths. For example, if a data repository is associated with file system path ``/ns1/``, then you cannot link another data repository with file system path
            ``/ns1/ns2``.
             This path specifies where in your file system files will be exported from or imported to. This file system directory can be linked to only one Amazon S3 bucket, and no other S3 bucket can be linked to the directory.
              If you specify only a forward slash (``/``) as the file system path, you can link only one data repository to the file system. You can only specify "/" as the file system path for the first data repository associated with a file system.
        DataRepositoryPath:
          type: string
          description: The path to the Amazon S3 data repository that will be linked to the file system. The path can be an S3 bucket or prefix in the format ``s3://myBucket/myPrefix/``. This path specifies where in the S3 data repository files will be imported from or exported to.
        BatchImportMetaDataOnCreate:
          type: boolean
          description: A boolean flag indicating whether an import data repository task to import metadata should run after the data repository association is created. The task runs if this flag is set to ``true``.
        ImportedFileChunkSize:
          type: integer
          description: |-
            For files imported from a data repository, this value determines the stripe count and maximum amount of data per file (in MiB) stored on a single physical disk. The maximum number of disks that a single file can be striped across is limited by the total number of disks that make up the file system or cache.
             The default chunk size is 1,024 MiB (1 GiB) and can go as high as 512,000 MiB (500 GiB). Amazon S3 objects have a maximum size of 5 TB.
        S3:
          description: The configuration for an Amazon S3 data repository linked to an Amazon FSx Lustre file system with a data repository association. The configuration defines which file events (new, changed, or deleted files or directories) are automatically imported from the linked data repository to the file system or automatically exported from the file system to the data repository.
          $ref: '#/components/schemas/S3'
        Tags:
          type: array
          x-insertionOrder: false
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
          description: |-
            An array of key-value pairs to apply to this resource.
             For more information, see [Tag](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html).
      required:
        - FileSystemId
        - FileSystemPath
        - DataRepositoryPath
      x-stackql-resource-name: data_repository_association
      x-stackql-primaryIdentifier:
        - AssociationId
      x-create-only-properties:
        - FileSystemId
        - FileSystemPath
        - DataRepositoryPath
        - BatchImportMetaDataOnCreate
      x-read-only-properties:
        - AssociationId
        - ResourceARN
      x-required-permissions:
        create:
          - fsx:CreateDataRepositoryAssociation
          - fsx:DescribeDataRepositoryAssociations
          - fsx:TagResource
          - s3:ListBucket
          - s3:GetBucketPolicy
          - s3:PutBucketPolicy
          - iam:CreateServiceLinkedRole
          - iam:PutRolePolicy
        read:
          - fsx:DescribeDataRepositoryAssociations
        update:
          - fsx:DescribeDataRepositoryAssociations
          - fsx:UpdateDataRepositoryAssociation
          - fsx:TagResource
          - fsx:UntagResource
          - s3:ListBucket
          - s3:GetBucketPolicy
          - s3:PutBucketPolicy
          - iam:CreateServiceLinkedRole
          - iam:PutRolePolicy
        delete:
          - fsx:DescribeDataRepositoryAssociations
          - fsx:DeleteDataRepositoryAssociation
        list:
          - fsx:DescribeDataRepositoryAssociations
  x-stackQL-resources:
    data_repository_associations:
      name: data_repository_associations
      id: awscc.fsx.data_repository_associations
      x-cfn-schema-name: DataRepositoryAssociation
      x-type: list
      x-identifiers:
        - AssociationId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.AssociationId') as association_id
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::FSx::DataRepositoryAssociation'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'AssociationId') as association_id
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::FSx::DataRepositoryAssociation'
                AND region = 'us-east-1'
    data_repository_association:
      name: data_repository_association
      id: awscc.fsx.data_repository_association
      x-cfn-schema-name: DataRepositoryAssociation
      x-type: get
      x-identifiers:
        - AssociationId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.AssociationId') as association_id,
              JSON_EXTRACT(Properties, '$.ResourceARN') as resource_arn,
              JSON_EXTRACT(Properties, '$.FileSystemId') as file_system_id,
              JSON_EXTRACT(Properties, '$.FileSystemPath') as file_system_path,
              JSON_EXTRACT(Properties, '$.DataRepositoryPath') as data_repository_path,
              JSON_EXTRACT(Properties, '$.BatchImportMetaDataOnCreate') as batch_import_meta_data_on_create,
              JSON_EXTRACT(Properties, '$.ImportedFileChunkSize') as imported_file_chunk_size,
              JSON_EXTRACT(Properties, '$.S3') as s3,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::FSx::DataRepositoryAssociation'
              AND data__Identifier = '<AssociationId>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'AssociationId') as association_id,
                json_extract_path_text(Properties, 'ResourceARN') as resource_arn,
                json_extract_path_text(Properties, 'FileSystemId') as file_system_id,
                json_extract_path_text(Properties, 'FileSystemPath') as file_system_path,
                json_extract_path_text(Properties, 'DataRepositoryPath') as data_repository_path,
                json_extract_path_text(Properties, 'BatchImportMetaDataOnCreate') as batch_import_meta_data_on_create,
                json_extract_path_text(Properties, 'ImportedFileChunkSize') as imported_file_chunk_size,
                json_extract_path_text(Properties, 'S3') as s3,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::FSx::DataRepositoryAssociation'
                AND data__Identifier = '<AssociationId>'
                AND region = 'us-east-1'
