openapi: 3.0.0
info:
  title: IoTCoreDeviceAdvisor
  version: 1.0.0
paths: {}
components:
  schemas:
    DeviceUnderTest:
      type: object
      properties:
        CertificateArn:
          type: string
          minLength: 20
          maxLength: 2048
        ThingArn:
          type: string
          minLength: 20
          maxLength: 2048
      additionalProperties: false
    SuiteDefinitionName:
      type: string
      description: The Name of the suite definition.
      minLength: 1
      maxLength: 256
    RootGroup:
      type: string
      description: The root group of the test suite.
      minLength: 1
      maxLength: 2048
    Devices:
      type: array
      description: The devices being tested in the test suite
      minItems: 0
      maxItems: 2
      items:
        $ref: '#/components/schemas/DeviceUnderTest'
    DevicePermissionRoleArn:
      type: string
      description: The device permission role arn of the test suite.
      minLength: 20
      maxLength: 2048
    IntendedForQualification:
      description: Whether the tests are intended for qualification in a suite.
      type: boolean
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      properties:
        Key:
          type: string
          description: 'The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          minLength: 1
          maxLength: 128
        Value:
          type: string
          description: 'The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          minLength: 0
          maxLength: 256
      required:
        - Key
        - Value
      additionalProperties: false
    SuiteDefinition:
      type: object
      properties:
        SuiteDefinitionConfiguration:
          type: object
          properties:
            DevicePermissionRoleArn:
              $ref: '#/components/schemas/DevicePermissionRoleArn'
            Devices:
              $ref: '#/components/schemas/Devices'
            IntendedForQualification:
              $ref: '#/components/schemas/IntendedForQualification'
            RootGroup:
              $ref: '#/components/schemas/RootGroup'
            SuiteDefinitionName:
              $ref: '#/components/schemas/SuiteDefinitionName'
          required:
            - DevicePermissionRoleArn
            - RootGroup
          additionalProperties: false
        SuiteDefinitionId:
          type: string
          maxLength: 36
          minLength: 12
          description: The unique identifier for the suite definition.
        SuiteDefinitionArn:
          type: string
          maxLength: 2048
          minLength: 20
          description: The Amazon Resource name for the suite definition.
        SuiteDefinitionVersion:
          type: string
          maxLength: 255
          minLength: 2
          description: The suite definition version of a test suite.
        Tags:
          description: An array of key-value pairs to apply to this resource.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - SuiteDefinitionConfiguration
      x-stackql-resource-name: suite_definition
      x-stackql-primaryIdentifier:
        - SuiteDefinitionId
      x-read-only-properties:
        - SuiteDefinitionId
        - SuiteDefinitionArn
        - SuiteDefinitionVersion
      x-required-permissions:
        create:
          - iot:DescribeCertificate
          - iot:DescribeThing
          - iot:GetPolicy
          - iot:ListAttachedPolicies
          - iot:ListCertificates
          - iot:ListPrincipalPolicies
          - iot:ListTagsForResource
          - iot:ListThingPrincipals
          - iot:ListThings
          - iotdeviceadvisor:CreateSuiteDefinition
          - iotdeviceadvisor:TagResource
          - iam:PassRole
        read:
          - iotdeviceadvisor:GetSuiteDefinition
          - iotdeviceadvisor:TagResource
        update:
          - iot:DescribeCertificate
          - iot:DescribeThing
          - iot:GetPolicy
          - iot:ListAttachedPolicies
          - iot:ListCertificates
          - iot:ListPrincipalPolicies
          - iot:ListTagsForResource
          - iot:ListThingPrincipals
          - iot:ListThings
          - iotdeviceadvisor:UpdateSuiteDefinition
          - iotdeviceadvisor:GetSuiteDefinition
          - iotdeviceadvisor:UntagResource
          - iotdeviceadvisor:TagResource
          - iam:PassRole
        delete:
          - iotdeviceadvisor:GetSuiteDefinition
          - iotdeviceadvisor:DeleteSuiteDefinition
        list:
          - iotdeviceadvisor:ListSuiteDefinitions
  x-stackQL-resources:
    suite_definitions:
      name: suite_definitions
      id: awscc.iotcoredeviceadvisor.suite_definitions
      x-cfn-schema-name: SuiteDefinition
      x-type: list
      x-identifiers:
        - SuiteDefinitionId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.SuiteDefinitionId') as suite_definition_id
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::IoTCoreDeviceAdvisor::SuiteDefinition'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'SuiteDefinitionId') as suite_definition_id
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::IoTCoreDeviceAdvisor::SuiteDefinition'
                AND region = 'us-east-1'
    suite_definition:
      name: suite_definition
      id: awscc.iotcoredeviceadvisor.suite_definition
      x-cfn-schema-name: SuiteDefinition
      x-type: get
      x-identifiers:
        - SuiteDefinitionId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.SuiteDefinitionConfiguration') as suite_definition_configuration,
              JSON_EXTRACT(Properties, '$.SuiteDefinitionId') as suite_definition_id,
              JSON_EXTRACT(Properties, '$.SuiteDefinitionArn') as suite_definition_arn,
              JSON_EXTRACT(Properties, '$.SuiteDefinitionVersion') as suite_definition_version,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::IoTCoreDeviceAdvisor::SuiteDefinition'
              AND data__Identifier = '<SuiteDefinitionId>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'SuiteDefinitionConfiguration') as suite_definition_configuration,
                json_extract_path_text(Properties, 'SuiteDefinitionId') as suite_definition_id,
                json_extract_path_text(Properties, 'SuiteDefinitionArn') as suite_definition_arn,
                json_extract_path_text(Properties, 'SuiteDefinitionVersion') as suite_definition_version,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::IoTCoreDeviceAdvisor::SuiteDefinition'
                AND data__Identifier = '<SuiteDefinitionId>'
                AND region = 'us-east-1'
