openapi: 3.0.0
info:
  title: KinesisVideo
  version: 1.0.0
paths: {}
components:
  schemas:
    Tag:
      description: A key-value pair to associated with the Kinesis Video Stream.
      type: object
      properties:
        Key:
          type: string
          description: 'The key name of the tag. Specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. The following characters can be used: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          minLength: 1
          maxLength: 128
        Value:
          type: string
          description: 'The value for the tag. Specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. The following characters can be used: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          minLength: 0
          maxLength: 256
      required:
        - Key
        - Value
      additionalProperties: false
    SignalingChannel:
      type: object
      properties:
        Arn:
          description: The Amazon Resource Name (ARN) of the Kinesis Video Signaling Channel.
          type: string
        Name:
          description: The name of the Kinesis Video Signaling Channel.
          type: string
          minLength: 1
          maxLength: 256
          pattern: '[a-zA-Z0-9_.-]+'
        Type:
          description: The type of the Kinesis Video Signaling Channel to create. Currently, SINGLE_MASTER is the only supported channel type.
          type: string
          enum:
            - SINGLE_MASTER
        MessageTtlSeconds:
          description: The period of time a signaling channel retains undelivered messages before they are discarded.
          type: integer
          minimum: 5
          maximum: 120
        Tags:
          description: An array of key-value pairs to apply to this resource.
          type: array
          uniqueItems: false
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
          minItems: 1
          maxItems: 50
      required: []
      x-stackql-resource-name: signaling_channel
      x-stackql-primaryIdentifier:
        - Name
      x-create-only-properties:
        - Name
      x-read-only-properties:
        - Arn
      x-required-permissions:
        create:
          - kinesisvideo:CreateSignalingChannel
          - kinesisvideo:DescribeSignalingChannel
        read:
          - kinesisvideo:DescribeSignalingChannel
        update:
          - kinesisvideo:UpdateSignalingChannel
          - kinesisvideo:DescribeSignalingChannel
        delete:
          - kinesisvideo:DeleteSignalingChannel
          - kinesisvideo:DescribeSignalingChannel
    Stream:
      type: object
      properties:
        Arn:
          description: The Amazon Resource Name (ARN) of the Kinesis Video stream.
          type: string
        Name:
          description: The name of the Kinesis Video stream.
          type: string
          minLength: 1
          maxLength: 256
          pattern: '[a-zA-Z0-9_.-]+'
        DataRetentionInHours:
          description: The number of hours till which Kinesis Video will retain the data in the stream
          type: integer
          minimum: 0
          maximum: 87600
        DeviceName:
          description: The name of the device that is writing to the stream.
          type: string
          minLength: 1
          maxLength: 128
          pattern: '[a-zA-Z0-9_.-]+'
        KmsKeyId:
          description: AWS KMS key ID that Kinesis Video Streams uses to encrypt stream data.
          type: string
          minLength: 1
          maxLength: 2048
          pattern: .+
        MediaType:
          description: The media type of the stream. Consumers of the stream can use this information when processing the stream.
          type: string
          minLength: 1
          maxLength: 128
          pattern: '[\w\-\.\+]+/[\w\-\.\+]+(,[\w\-\.\+]+/[\w\-\.\+]+)*'
        Tags:
          description: An array of key-value pairs associated with the Kinesis Video Stream.
          type: array
          uniqueItems: false
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
          minItems: 1
          maxItems: 50
      required: []
      x-stackql-resource-name: stream
      x-stackql-primaryIdentifier:
        - Name
      x-create-only-properties:
        - Name
      x-read-only-properties:
        - Arn
      x-required-permissions:
        create:
          - kinesisvideo:DescribeStream
          - kinesisvideo:CreateStream
        read:
          - kinesisvideo:DescribeStream
        update:
          - kinesisvideo:DescribeStream
          - kinesisvideo:UpdateStream
          - kinesisvideo:UpdateDataRetention
        delete:
          - kinesisvideo:DescribeStream
          - kinesisvideo:DeleteStream
  x-stackQL-resources:
    signaling_channel:
      name: signaling_channel
      id: awscc.kinesisvideo.signaling_channel
      x-cfn-schema-name: SignalingChannel
      x-type: get
      x-identifiers:
        - Name
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Type') as type,
              JSON_EXTRACT(Properties, '$.MessageTtlSeconds') as message_ttl_seconds,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::KinesisVideo::SignalingChannel'
              AND data__Identifier = '<Name>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'Name') as name,
                json_extract_path_text(Properties, 'Type') as type,
                json_extract_path_text(Properties, 'MessageTtlSeconds') as message_ttl_seconds,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::KinesisVideo::SignalingChannel'
                AND data__Identifier = '<Name>'
                AND region = 'us-east-1'
    kinesisvideo_stream:
      name: kinesisvideo_stream
      id: awscc.kinesisvideo.kinesisvideo_stream
      x-cfn-schema-name: Stream
      x-type: get
      x-identifiers:
        - Name
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.DataRetentionInHours') as data_retention_in_hours,
              JSON_EXTRACT(Properties, '$.DeviceName') as device_name,
              JSON_EXTRACT(Properties, '$.KmsKeyId') as kms_key_id,
              JSON_EXTRACT(Properties, '$.MediaType') as media_type,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::KinesisVideo::Stream'
              AND data__Identifier = '<Name>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'Name') as name,
                json_extract_path_text(Properties, 'DataRetentionInHours') as data_retention_in_hours,
                json_extract_path_text(Properties, 'DeviceName') as device_name,
                json_extract_path_text(Properties, 'KmsKeyId') as kms_key_id,
                json_extract_path_text(Properties, 'MediaType') as media_type,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::KinesisVideo::Stream'
                AND data__Identifier = '<Name>'
                AND region = 'us-east-1'
