openapi: 3.0.0
info:
  title: LookoutVision
  version: 1.0.0
paths: {}
components:
  schemas:
    Arn:
      type: string
      maxLength: 1000
    ProjectName:
      description: The name of the Amazon Lookout for Vision project
      type: string
      minLength: 1
      maxLength: 255
      pattern: '[a-zA-Z0-9][a-zA-Z0-9_\-]*'
    Project:
      type: object
      properties:
        Arn:
          $ref: '#/components/schemas/Arn'
        ProjectName:
          $ref: '#/components/schemas/ProjectName'
      required:
        - ProjectName
      x-stackql-resource-name: project
      x-stackql-primaryIdentifier:
        - ProjectName
      x-create-only-properties:
        - ProjectName
      x-read-only-properties:
        - Arn
      x-required-permissions:
        create:
          - lookoutvision:CreateProject
        read:
          - lookoutvision:DescribeProject
        update: []
        delete:
          - lookoutvision:DeleteProject
        list:
          - lookoutvision:ListProjects
  x-stackQL-resources:
    projects:
      name: projects
      id: awscc.lookoutvision.projects
      x-cfn-schema-name: Project
      x-type: list
      x-identifiers:
        - ProjectName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ProjectName') as project_name
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::LookoutVision::Project'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'ProjectName') as project_name
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::LookoutVision::Project'
                AND region = 'us-east-1'
    project:
      name: project
      id: awscc.lookoutvision.project
      x-cfn-schema-name: Project
      x-type: get
      x-identifiers:
        - ProjectName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.ProjectName') as project_name
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::LookoutVision::Project'
              AND data__Identifier = '<ProjectName>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'ProjectName') as project_name
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::LookoutVision::Project'
                AND data__Identifier = '<ProjectName>'
                AND region = 'us-east-1'
