openapi: 3.0.0
info:
  title: ManagedBlockchain
  version: 1.0.0
paths: {}
components:
  schemas:
    AccessorStatus:
      type: string
      enum:
        - AVAILABLE
        - PENDING_DELETION
        - DELETED
    AccessorType:
      type: string
      enum:
        - BILLING_TOKEN
    NetworkAccessorType:
      type: string
      enum:
        - ETHEREUM_GOERLI
        - ETHEREUM_MAINNET
        - ETHEREUM_MAINNET_AND_GOERLI
        - POLYGON_MAINNET
        - POLYGON_MUMBAI
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      properties:
        Key:
          type: string
          description: 'The key name of the tag. You can specify a value that is 1 to 127 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          minLength: 1
          maxLength: 127
        Value:
          type: string
          description: 'The value for the tag. You can specify a value that is 1 to 255 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          minLength: 1
          maxLength: 255
      required:
        - Key
        - Value
      additionalProperties: false
    Accessor:
      type: object
      properties:
        Arn:
          type: string
          maxLength: 1011
          minLength: 1
          pattern: ^arn:.+:.+:.+:.+:.+$
        BillingToken:
          type: string
          maxLength: 42
          minLength: 42
        CreationDate:
          type: string
        Id:
          type: string
          maxLength: 32
          minLength: 1
        Status:
          $ref: '#/components/schemas/AccessorStatus'
        AccessorType:
          $ref: '#/components/schemas/AccessorType'
        NetworkType:
          $ref: '#/components/schemas/NetworkAccessorType'
        Tags:
          type: array
          maxItems: 50
          x-insertionOrder: false
          uniqueItems: true
          description: An array of key-value pairs to apply to this resource.
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - AccessorType
      x-stackql-resource-name: accessor
      x-stackql-primaryIdentifier:
        - Id
      x-create-only-properties:
        - AccessorType
        - NetworkType
      x-read-only-properties:
        - Arn
        - Id
        - BillingToken
        - CreationDate
        - Status
      x-required-permissions:
        create:
          - managedblockchain:CreateAccessor
          - managedblockchain:TagResource
          - managedblockchain:GetAccessor
        read:
          - managedblockchain:GetAccessor
        update:
          - managedblockchain:GetAccessor
          - managedblockchain:CreateAccessor
          - managedblockchain:TagResource
          - managedblockchain:UntagResource
        delete:
          - managedblockchain:DeleteAccessor
        list:
          - managedblockchain:ListAccessors
  x-stackQL-resources:
    accessors:
      name: accessors
      id: awscc.managedblockchain.accessors
      x-cfn-schema-name: Accessor
      x-type: list
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::ManagedBlockchain::Accessor'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Id') as id
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::ManagedBlockchain::Accessor'
                AND region = 'us-east-1'
    accessor:
      name: accessor
      id: awscc.managedblockchain.accessor
      x-cfn-schema-name: Accessor
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.BillingToken') as billing_token,
              JSON_EXTRACT(Properties, '$.CreationDate') as creation_date,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Status') as status,
              JSON_EXTRACT(Properties, '$.AccessorType') as accessor_type,
              JSON_EXTRACT(Properties, '$.NetworkType') as network_type,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::ManagedBlockchain::Accessor'
              AND data__Identifier = '<Id>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'BillingToken') as billing_token,
                json_extract_path_text(Properties, 'CreationDate') as creation_date,
                json_extract_path_text(Properties, 'Id') as id,
                json_extract_path_text(Properties, 'Status') as status,
                json_extract_path_text(Properties, 'AccessorType') as accessor_type,
                json_extract_path_text(Properties, 'NetworkType') as network_type,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::ManagedBlockchain::Accessor'
                AND data__Identifier = '<Id>'
                AND region = 'us-east-1'
