openapi: 3.0.0
info:
  title: OpenSearchService
  version: 1.0.0
paths: {}
components:
  schemas:
    ZoneAwarenessConfig:
      type: object
      additionalProperties: false
      properties:
        AvailabilityZoneCount:
          type: integer
    ClusterConfig:
      type: object
      additionalProperties: false
      properties:
        InstanceCount:
          type: integer
        WarmEnabled:
          type: boolean
        WarmCount:
          type: integer
        DedicatedMasterEnabled:
          type: boolean
        ZoneAwarenessConfig:
          $ref: '#/components/schemas/ZoneAwarenessConfig'
        DedicatedMasterCount:
          type: integer
        InstanceType:
          type: string
        WarmType:
          type: string
        ZoneAwarenessEnabled:
          type: boolean
        DedicatedMasterType:
          type: string
        MultiAZWithStandbyEnabled:
          type: boolean
        ColdStorageOptions:
          $ref: '#/components/schemas/ColdStorageOptions'
    LogPublishingOption:
      type: object
      additionalProperties: false
      properties:
        CloudWatchLogsLogGroupArn:
          type: string
        Enabled:
          type: boolean
    SnapshotOptions:
      type: object
      additionalProperties: false
      properties:
        AutomatedSnapshotStartHour:
          type: integer
    VPCOptions:
      type: object
      additionalProperties: false
      properties:
        SecurityGroupIds:
          type: array
          uniqueItems: true
          items:
            type: string
        SubnetIds:
          type: array
          uniqueItems: true
          items:
            type: string
    NodeToNodeEncryptionOptions:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
    DomainEndpointOptions:
      type: object
      additionalProperties: false
      properties:
        CustomEndpointCertificateArn:
          type: string
        CustomEndpointEnabled:
          type: boolean
        EnforceHTTPS:
          type: boolean
        CustomEndpoint:
          type: string
        TLSSecurityPolicy:
          type: string
    CognitoOptions:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
        IdentityPoolId:
          type: string
        UserPoolId:
          type: string
        RoleArn:
          type: string
    MasterUserOptions:
      type: object
      additionalProperties: false
      properties:
        MasterUserPassword:
          type: string
        MasterUserName:
          type: string
        MasterUserARN:
          type: string
    Idp:
      type: object
      additionalProperties: false
      properties:
        MetadataContent:
          type: string
          maxLength: 1048576
          minLength: 1
        EntityId:
          type: string
      required:
        - MetadataContent
        - EntityId
    SAMLOptions:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
        Idp:
          $ref: '#/components/schemas/Idp'
        MasterUserName:
          type: string
        MasterBackendRole:
          type: string
        SubjectKey:
          type: string
        RolesKey:
          type: string
        SessionTimeoutMinutes:
          type: integer
    AdvancedSecurityOptionsInput:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
        MasterUserOptions:
          $ref: '#/components/schemas/MasterUserOptions'
        InternalUserDatabaseEnabled:
          type: boolean
        AnonymousAuthEnabled:
          type: boolean
        SAMLOptions:
          $ref: '#/components/schemas/SAMLOptions'
        AnonymousAuthDisableDate:
          type: string
    EBSOptions:
      type: object
      additionalProperties: false
      properties:
        EBSEnabled:
          type: boolean
        VolumeType:
          type: string
        Iops:
          type: integer
        VolumeSize:
          type: integer
        Throughput:
          type: integer
    EncryptionAtRestOptions:
      type: object
      additionalProperties: false
      properties:
        KmsKeyId:
          type: string
        Enabled:
          type: boolean
    Tag:
      type: object
      additionalProperties: false
      properties:
        Value:
          description: The key of the tag.
          type: string
          minLength: 0
          maxLength: 256
        Key:
          description: The value of the tag.
          type: string
          minLength: 0
          maxLength: 128
      required:
        - Value
        - Key
    ServiceSoftwareOptions:
      type: object
      additionalProperties: false
      properties:
        CurrentVersion:
          type: string
        NewVersion:
          type: string
        UpdateAvailable:
          type: boolean
        Cancellable:
          type: boolean
        UpdateStatus:
          type: string
        Description:
          type: string
        AutomatedUpdateDate:
          type: string
        OptionalDeployment:
          type: boolean
    WindowStartTime:
      type: object
      additionalProperties: false
      properties:
        Hours:
          type: integer
          minimum: 0
          maximum: 23
        Minutes:
          type: integer
          minimum: 0
          maximum: 59
      required:
        - Hours
        - Minutes
    OffPeakWindow:
      type: object
      additionalProperties: false
      properties:
        WindowStartTime:
          $ref: '#/components/schemas/WindowStartTime'
    OffPeakWindowOptions:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
        OffPeakWindow:
          $ref: '#/components/schemas/OffPeakWindow'
    SoftwareUpdateOptions:
      type: object
      additionalProperties: false
      properties:
        AutoSoftwareUpdateEnabled:
          type: boolean
    ColdStorageOptions:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
    Domain:
      type: object
      properties:
        ClusterConfig:
          $ref: '#/components/schemas/ClusterConfig'
        DomainName:
          type: string
        AccessPolicies:
          type: object
        IPAddressType:
          type: string
        EngineVersion:
          type: string
        AdvancedOptions:
          type: object
          additionalProperties: false
          x-patternProperties:
            '[a-zA-Z0-9]+':
              type: string
        LogPublishingOptions:
          type: object
          additionalProperties: false
          x-patternProperties:
            '[a-zA-Z0-9]+':
              $ref: '#/components/schemas/LogPublishingOption'
        SnapshotOptions:
          $ref: '#/components/schemas/SnapshotOptions'
        VPCOptions:
          $ref: '#/components/schemas/VPCOptions'
        NodeToNodeEncryptionOptions:
          $ref: '#/components/schemas/NodeToNodeEncryptionOptions'
        DomainEndpointOptions:
          $ref: '#/components/schemas/DomainEndpointOptions'
        CognitoOptions:
          $ref: '#/components/schemas/CognitoOptions'
        AdvancedSecurityOptions:
          $ref: '#/components/schemas/AdvancedSecurityOptionsInput'
        DomainEndpoint:
          type: string
        DomainEndpointV2:
          type: string
        DomainEndpoints:
          type: object
          additionalProperties: false
          x-patternProperties:
            ^.*$:
              type: string
        EBSOptions:
          $ref: '#/components/schemas/EBSOptions'
        Id:
          type: string
        Arn:
          type: string
        DomainArn:
          type: string
        EncryptionAtRestOptions:
          $ref: '#/components/schemas/EncryptionAtRestOptions'
        Tags:
          description: An arbitrary set of tags (key-value pairs) for this Domain.
          items:
            $ref: '#/components/schemas/Tag'
          type: array
          uniqueItems: true
        ServiceSoftwareOptions:
          $ref: '#/components/schemas/ServiceSoftwareOptions'
        OffPeakWindowOptions:
          $ref: '#/components/schemas/OffPeakWindowOptions'
        SoftwareUpdateOptions:
          $ref: '#/components/schemas/SoftwareUpdateOptions'
      x-stackql-resource-name: domain
      x-stackql-primaryIdentifier:
        - DomainName
      x-create-only-properties:
        - DomainName
      x-read-only-properties:
        - Id
        - Arn
        - DomainArn
        - DomainEndpoint
        - DomainEndpointV2
        - DomainEndpoints
        - ServiceSoftwareOptions
        - AdvancedSecurityOptions/AnonymousAuthDisableDate
      x-required-permissions:
        create:
          - es:CreateDomain
          - es:DescribeDomain
          - es:AddTags
          - es:ListTags
        read:
          - es:DescribeDomain
          - es:ListTags
        update:
          - es:UpdateDomain
          - es:UpgradeDomain
          - es:DescribeDomain
          - es:AddTags
          - es:RemoveTags
          - es:ListTags
          - es:DescribeDomainChangeProgress
        delete:
          - es:DeleteDomain
          - es:DescribeDomain
  x-stackQL-resources:
    domains:
      name: domains
      id: awscc.opensearchservice.domains
      x-cfn-schema-name: Domain
      x-type: list
      x-identifiers:
        - DomainName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.DomainName') as domain_name
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::OpenSearchService::Domain'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'DomainName') as domain_name
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::OpenSearchService::Domain'
                AND region = 'us-east-1'
    domain:
      name: domain
      id: awscc.opensearchservice.domain
      x-cfn-schema-name: Domain
      x-type: get
      x-identifiers:
        - DomainName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ClusterConfig') as cluster_config,
              JSON_EXTRACT(Properties, '$.DomainName') as domain_name,
              JSON_EXTRACT(Properties, '$.AccessPolicies') as access_policies,
              JSON_EXTRACT(Properties, '$.IPAddressType') as i_paddress_type,
              JSON_EXTRACT(Properties, '$.EngineVersion') as engine_version,
              JSON_EXTRACT(Properties, '$.AdvancedOptions') as advanced_options,
              JSON_EXTRACT(Properties, '$.LogPublishingOptions') as log_publishing_options,
              JSON_EXTRACT(Properties, '$.SnapshotOptions') as snapshot_options,
              JSON_EXTRACT(Properties, '$.VPCOptions') as v_pc_options,
              JSON_EXTRACT(Properties, '$.NodeToNodeEncryptionOptions') as node_to_node_encryption_options,
              JSON_EXTRACT(Properties, '$.DomainEndpointOptions') as domain_endpoint_options,
              JSON_EXTRACT(Properties, '$.CognitoOptions') as cognito_options,
              JSON_EXTRACT(Properties, '$.AdvancedSecurityOptions') as advanced_security_options,
              JSON_EXTRACT(Properties, '$.DomainEndpoint') as domain_endpoint,
              JSON_EXTRACT(Properties, '$.DomainEndpointV2') as domain_endpoint_v2,
              JSON_EXTRACT(Properties, '$.DomainEndpoints') as domain_endpoints,
              JSON_EXTRACT(Properties, '$.EBSOptions') as e_bs_options,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.DomainArn') as domain_arn,
              JSON_EXTRACT(Properties, '$.EncryptionAtRestOptions') as encryption_at_rest_options,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.ServiceSoftwareOptions') as service_software_options,
              JSON_EXTRACT(Properties, '$.OffPeakWindowOptions') as off_peak_window_options,
              JSON_EXTRACT(Properties, '$.SoftwareUpdateOptions') as software_update_options
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::OpenSearchService::Domain'
              AND data__Identifier = '<DomainName>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'ClusterConfig') as cluster_config,
                json_extract_path_text(Properties, 'DomainName') as domain_name,
                json_extract_path_text(Properties, 'AccessPolicies') as access_policies,
                json_extract_path_text(Properties, 'IPAddressType') as i_paddress_type,
                json_extract_path_text(Properties, 'EngineVersion') as engine_version,
                json_extract_path_text(Properties, 'AdvancedOptions') as advanced_options,
                json_extract_path_text(Properties, 'LogPublishingOptions') as log_publishing_options,
                json_extract_path_text(Properties, 'SnapshotOptions') as snapshot_options,
                json_extract_path_text(Properties, 'VPCOptions') as v_pc_options,
                json_extract_path_text(Properties, 'NodeToNodeEncryptionOptions') as node_to_node_encryption_options,
                json_extract_path_text(Properties, 'DomainEndpointOptions') as domain_endpoint_options,
                json_extract_path_text(Properties, 'CognitoOptions') as cognito_options,
                json_extract_path_text(Properties, 'AdvancedSecurityOptions') as advanced_security_options,
                json_extract_path_text(Properties, 'DomainEndpoint') as domain_endpoint,
                json_extract_path_text(Properties, 'DomainEndpointV2') as domain_endpoint_v2,
                json_extract_path_text(Properties, 'DomainEndpoints') as domain_endpoints,
                json_extract_path_text(Properties, 'EBSOptions') as e_bs_options,
                json_extract_path_text(Properties, 'Id') as id,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'DomainArn') as domain_arn,
                json_extract_path_text(Properties, 'EncryptionAtRestOptions') as encryption_at_rest_options,
                json_extract_path_text(Properties, 'Tags') as tags,
                json_extract_path_text(Properties, 'ServiceSoftwareOptions') as service_software_options,
                json_extract_path_text(Properties, 'OffPeakWindowOptions') as off_peak_window_options,
                json_extract_path_text(Properties, 'SoftwareUpdateOptions') as software_update_options
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::OpenSearchService::Domain'
                AND data__Identifier = '<DomainName>'
                AND region = 'us-east-1'
