openapi: 3.0.0
info:
  title: RAM
  version: 1.0.0
paths: {}
components:
  schemas:
    Tag:
      type: object
      additionalProperties: false
      properties:
        Key:
          type: string
          description: 'The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          minLength: 1
          maxLength: 128
        Value:
          type: string
          description: 'The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          minLength: 0
          maxLength: 256
      required:
        - Key
        - Value
    Permission:
      type: object
      properties:
        Arn:
          type: string
        Name:
          description: The name of the permission.
          type: string
        Version:
          description: Version of the permission.
          type: string
        IsResourceTypeDefault:
          description: Set to true to use this as the default permission.
          type: boolean
        PermissionType:
          type: string
        ResourceType:
          description: The resource type this permission can be used with.
          type: string
        PolicyTemplate:
          description: Policy template for the permission.
          type: object
        Tags:
          type: array
          uniqueItems: false
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - Name
        - ResourceType
        - PolicyTemplate
      x-stackql-resource-name: permission
      x-stackql-primaryIdentifier:
        - Arn
      x-create-only-properties:
        - Name
        - ResourceType
        - PolicyTemplate
      x-read-only-properties:
        - Arn
        - Version
        - IsResourceTypeDefault
        - PermissionType
      x-required-permissions:
        create:
          - ram:CreatePermission
          - ram:TagResource
        read:
          - ram:GetPermission
        update:
          - ram:CreatePermissionVersion
          - ram:DeletePermissionVersion
          - ram:SetDefaultPermissionVersion
          - ram:GetPermission
          - ram:ReplacePermissionAssociations
          - ram:ListReplacePermissionAssociationsWork
          - ram:ListPermissionVersions
          - ram:UntagResource
          - ram:TagResource
        delete:
          - ram:DeletePermissionVersion
          - ram:DeletePermission
        list:
          - ram:ListPermissions
          - ram:ListPermissionVersions
  x-stackQL-resources:
    permissions:
      name: permissions
      id: awscc.ram.permissions
      x-cfn-schema-name: Permission
      x-type: list
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::RAM::Permission'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Arn') as arn
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::RAM::Permission'
                AND region = 'us-east-1'
    permission:
      name: permission
      id: awscc.ram.permission
      x-cfn-schema-name: Permission
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Version') as version,
              JSON_EXTRACT(Properties, '$.IsResourceTypeDefault') as is_resource_type_default,
              JSON_EXTRACT(Properties, '$.PermissionType') as permission_type,
              JSON_EXTRACT(Properties, '$.ResourceType') as resource_type,
              JSON_EXTRACT(Properties, '$.PolicyTemplate') as policy_template,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::RAM::Permission'
              AND data__Identifier = '<Arn>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'Name') as name,
                json_extract_path_text(Properties, 'Version') as version,
                json_extract_path_text(Properties, 'IsResourceTypeDefault') as is_resource_type_default,
                json_extract_path_text(Properties, 'PermissionType') as permission_type,
                json_extract_path_text(Properties, 'ResourceType') as resource_type,
                json_extract_path_text(Properties, 'PolicyTemplate') as policy_template,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::RAM::Permission'
                AND data__Identifier = '<Arn>'
                AND region = 'us-east-1'
