openapi: 3.0.0
info:
  title: ResilienceHub
  version: 1.0.0
paths: {}
components:
  schemas:
    TagValue:
      type: string
      maxLength: 256
    TagMap:
      type: object
      x-patternProperties:
        .{1,128}:
          $ref: '#/components/schemas/TagValue'
      additionalProperties: false
    PhysicalResourceId:
      type: object
      additionalProperties: false
      properties:
        AwsAccountId:
          type: string
          pattern: ^[0-9]{12}$
        AwsRegion:
          type: string
          pattern: ^[a-z]{2}-((iso[a-z]{0,1}-)|(gov-)){0,1}[a-z]+-[0-9]$
        Identifier:
          type: string
          minLength: 1
          maxLength: 255
        Type:
          type: string
          pattern: Arn|Native
      required:
        - Identifier
        - Type
    ResourceMapping:
      description: Resource mapping is used to map logical resources from template to physical resource
      type: object
      additionalProperties: false
      properties:
        LogicalStackName:
          type: string
        MappingType:
          type: string
          pattern: CfnStack|Resource|Terraform|EKS
        ResourceName:
          type: string
          pattern: ^[A-Za-z0-9][A-Za-z0-9_\-]{1,59}$
        TerraformSourceName:
          type: string
        EksSourceName:
          type: string
        PhysicalResourceId:
          $ref: '#/components/schemas/PhysicalResourceId'
      required:
        - MappingType
        - PhysicalResourceId
    IamRoleArn:
      type: string
      pattern: arn:(aws|aws-cn|aws-iso|aws-iso-[a-z]{1}|aws-us-gov):iam::[0-9]{12}:role\/(([\u0021-\u007E]+\u002F){1,511})?[A-Za-z0-9+=,.@_/-]{1,64}$
    PermissionModel:
      description: Defines the roles and credentials that AWS Resilience Hub would use while creating the application, importing its resources, and running an assessment.
      type: object
      additionalProperties: false
      properties:
        Type:
          description: Defines how AWS Resilience Hub scans your resources. It can scan for the resources by using a pre-existing role in your AWS account, or by using the credentials of the current IAM user.
          type: string
          enum:
            - LegacyIAMUser
            - RoleBased
        InvokerRoleName:
          description: Existing AWS IAM role name in the primary AWS account that will be assumed by AWS Resilience Hub Service Principle to obtain a read-only access to your application resources while running an assessment.
          type: string
          pattern: ((\u002F[\u0021-\u007E]+\u002F){1,511})?[A-Za-z0-9+=,.@_/-]{1,64}
        CrossAccountRoleArns:
          description: Defines a list of role Amazon Resource Names (ARNs) to be used in other accounts. These ARNs are used for querying purposes while importing resources and assessing your application.
          type: array
          uniqueItems: false
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/IamRoleArn'
      required:
        - Type
    EventSubscription:
      description: Indicates an event you would like to subscribe and get notification for.
      type: object
      additionalProperties: false
      properties:
        Name:
          description: Unique name to identify an event subscription.
          type: string
          maxLength: 256
        EventType:
          description: The type of event you would like to subscribe and get notification for.
          type: string
          enum:
            - ScheduledAssessmentFailure
            - DriftDetected
        SnsTopicArn:
          description: Amazon Resource Name (ARN) of the Amazon Simple Notification Service topic.
          type: string
          pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-[a-z]{1}|aws-us-gov):[A-Za-z0-9][A-Za-z0-9_/.-]{0,62}:([a-z]{2}-((iso[a-z]{0,1}-)|(gov-)){0,1}[a-z]+-[0-9]):[0-9]{12}:[A-Za-z0-9/][A-Za-z0-9:_/+.-]{0,1023}$
      required:
        - Name
        - EventType
    App:
      type: object
      properties:
        Name:
          description: Name of the app.
          type: string
          pattern: ^[A-Za-z0-9][A-Za-z0-9_\-]{1,59}$
        Description:
          description: App description.
          type: string
          minLength: 0
          maxLength: 500
        AppArn:
          type: string
          description: Amazon Resource Name (ARN) of the App.
          pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-[a-z]{1}|aws-us-gov):[A-Za-z0-9][A-Za-z0-9_/.-]{0,62}:([a-z]{2}-((iso[a-z]{0,1}-)|(gov-)){0,1}[a-z]+-[0-9]):[0-9]{12}:[A-Za-z0-9][A-Za-z0-9:_/+=,@.-]{0,1023}$
        ResiliencyPolicyArn:
          type: string
          description: Amazon Resource Name (ARN) of the Resiliency Policy.
          pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-[a-z]{1}|aws-us-gov):[A-Za-z0-9][A-Za-z0-9_/.-]{0,62}:([a-z]{2}-((iso[a-z]{0,1}-)|(gov-)){0,1}[a-z]+-[0-9]):[0-9]{12}:[A-Za-z0-9][A-Za-z0-9:_/+=,@.-]{0,1023}$
        Tags:
          $ref: '#/components/schemas/TagMap'
        AppTemplateBody:
          description: A string containing full ResilienceHub app template body.
          type: string
          minLength: 0
          maxLength: 409600
          pattern: ^[\w\s:,-\.'\/{}\[\]:"]+$
        ResourceMappings:
          description: An array of ResourceMapping objects.
          type: array
          uniqueItems: false
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/ResourceMapping'
        AppAssessmentSchedule:
          description: Assessment execution schedule.
          type: string
          enum:
            - Disabled
            - Daily
        PermissionModel:
          $ref: '#/components/schemas/PermissionModel'
        EventSubscriptions:
          description: The list of events you would like to subscribe and get notification for.
          type: array
          uniqueItems: false
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/EventSubscription'
        DriftStatus:
          description: Indicates if compliance drifts (deviations) were detected while running an assessment for your application.
          type: string
          enum:
            - NotChecked
            - NotDetected
            - Detected
      required:
        - Name
        - AppTemplateBody
        - ResourceMappings
      x-stackql-resource-name: app
      x-stackql-primaryIdentifier:
        - AppArn
      x-create-only-properties:
        - Name
      x-read-only-properties:
        - AppArn
        - DriftStatus
      x-required-permissions:
        create:
          - cloudformation:DescribeStacks
          - cloudformation:ListStackResources
          - s3:GetBucketLocation
          - s3:GetObject
          - s3:ListAllMyBuckets
          - autoscaling:DescribeAutoScalingGroups
          - apigateway:GET
          - ec2:Describe*
          - ecs:DescribeServices
          - eks:DescribeCluster
          - elasticfilesystem:DescribeFileSystems
          - elasticloadbalancing:DescribeLoadBalancers
          - lambda:GetFunction*
          - rds:Describe*
          - dynamodb:Describe*
          - sqs:GetQueueAttributes
          - sns:GetTopicAttributes
          - route53:List*
          - iam:PassRole
          - resiliencehub:*
        read:
          - resiliencehub:DescribeApp
          - resiliencehub:DescribeAppVersionTemplate
          - resiliencehub:ListAppVersionResourceMappings
          - resiliencehub:ListTagsForResource
        update:
          - cloudformation:DescribeStacks
          - cloudformation:ListStackResources
          - s3:GetBucketLocation
          - s3:GetObject
          - s3:ListAllMyBuckets
          - autoscaling:DescribeAutoScalingGroups
          - apigateway:GET
          - ec2:Describe*
          - ecs:DescribeServices
          - eks:DescribeCluster
          - elasticfilesystem:DescribeFileSystems
          - elasticloadbalancing:DescribeLoadBalancers
          - lambda:GetFunction*
          - rds:Describe*
          - dynamodb:Describe*
          - sqs:GetQueueAttributes
          - sns:GetTopicAttributes
          - route53:List*
          - iam:PassRole
          - resiliencehub:*
        delete:
          - resiliencehub:DeleteApp
          - resiliencehub:UntagResource
          - resiliencehub:ListApps
        list:
          - resiliencehub:ListApps
    FailurePolicy:
      description: Failure Policy.
      type: object
      properties:
        RtoInSecs:
          description: RTO in seconds.
          type: integer
        RpoInSecs:
          description: RPO in seconds.
          type: integer
      required:
        - RtoInSecs
        - RpoInSecs
      additionalProperties: false
    PolicyMap:
      type: object
      x-patternProperties:
        .*{1,8}:
          $ref: '#/components/schemas/FailurePolicy'
      additionalProperties: false
    ResiliencyPolicy:
      type: object
      properties:
        PolicyName:
          description: Name of Resiliency Policy.
          type: string
          pattern: ^[A-Za-z0-9][A-Za-z0-9_\-]{1,59}$
        PolicyDescription:
          description: Description of Resiliency Policy.
          type: string
          maxLength: 500
        DataLocationConstraint:
          type: string
          description: Data Location Constraint of the Policy.
          enum:
            - AnyLocation
            - SameContinent
            - SameCountry
        Tier:
          type: string
          description: Resiliency Policy Tier.
          enum:
            - MissionCritical
            - Critical
            - Important
            - CoreServices
            - NonCritical
        Policy:
          $ref: '#/components/schemas/PolicyMap'
        PolicyArn:
          type: string
          description: Amazon Resource Name (ARN) of the Resiliency Policy.
          pattern: ^arn:(aws|aws-cn|aws-iso|aws-iso-[a-z]{1}|aws-us-gov):[A-Za-z0-9][A-Za-z0-9_/.-]{0,62}:([a-z]{2}-((iso[a-z]{0,1}-)|(gov-)){0,1}[a-z]+-[0-9]):[0-9]{12}:[A-Za-z0-9][A-Za-z0-9:_/+=,@.-]{0,1023}$
        Tags:
          $ref: '#/components/schemas/TagMap'
      required:
        - PolicyName
        - Tier
        - Policy
      x-stackql-resource-name: resiliency_policy
      x-stackql-primaryIdentifier:
        - PolicyArn
      x-read-only-properties:
        - PolicyArn
      x-required-permissions:
        create:
          - resiliencehub:CreateResiliencyPolicy
          - resiliencehub:DescribeResiliencyPolicy
          - resiliencehub:TagResource
        update:
          - resiliencehub:DescribeResiliencyPolicy
          - resiliencehub:UpdateResiliencyPolicy
          - resiliencehub:TagResource
          - resiliencehub:UntagResource
          - resiliencehub:ListTagsForResource
        read:
          - resiliencehub:DescribeResiliencyPolicy
          - resiliencehub:ListTagsForResource
        delete:
          - resiliencehub:DeleteResiliencyPolicy
          - resiliencehub:UntagResource
        list:
          - resiliencehub:ListResiliencyPolicies
  x-stackQL-resources:
    apps:
      name: apps
      id: awscc.resiliencehub.apps
      x-cfn-schema-name: App
      x-type: list
      x-identifiers:
        - AppArn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.AppArn') as app_arn
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::ResilienceHub::App'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'AppArn') as app_arn
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::ResilienceHub::App'
                AND region = 'us-east-1'
    app:
      name: app
      id: awscc.resiliencehub.app
      x-cfn-schema-name: App
      x-type: get
      x-identifiers:
        - AppArn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.AppArn') as app_arn,
              JSON_EXTRACT(Properties, '$.ResiliencyPolicyArn') as resiliency_policy_arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.AppTemplateBody') as app_template_body,
              JSON_EXTRACT(Properties, '$.ResourceMappings') as resource_mappings,
              JSON_EXTRACT(Properties, '$.AppAssessmentSchedule') as app_assessment_schedule,
              JSON_EXTRACT(Properties, '$.PermissionModel') as permission_model,
              JSON_EXTRACT(Properties, '$.EventSubscriptions') as event_subscriptions,
              JSON_EXTRACT(Properties, '$.DriftStatus') as drift_status
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::ResilienceHub::App'
              AND data__Identifier = '<AppArn>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'Name') as name,
                json_extract_path_text(Properties, 'Description') as description,
                json_extract_path_text(Properties, 'AppArn') as app_arn,
                json_extract_path_text(Properties, 'ResiliencyPolicyArn') as resiliency_policy_arn,
                json_extract_path_text(Properties, 'Tags') as tags,
                json_extract_path_text(Properties, 'AppTemplateBody') as app_template_body,
                json_extract_path_text(Properties, 'ResourceMappings') as resource_mappings,
                json_extract_path_text(Properties, 'AppAssessmentSchedule') as app_assessment_schedule,
                json_extract_path_text(Properties, 'PermissionModel') as permission_model,
                json_extract_path_text(Properties, 'EventSubscriptions') as event_subscriptions,
                json_extract_path_text(Properties, 'DriftStatus') as drift_status
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::ResilienceHub::App'
                AND data__Identifier = '<AppArn>'
                AND region = 'us-east-1'
    resiliency_policies:
      name: resiliency_policies
      id: awscc.resiliencehub.resiliency_policies
      x-cfn-schema-name: ResiliencyPolicy
      x-type: list
      x-identifiers:
        - PolicyArn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.PolicyArn') as policy_arn
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::ResilienceHub::ResiliencyPolicy'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'PolicyArn') as policy_arn
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::ResilienceHub::ResiliencyPolicy'
                AND region = 'us-east-1'
    resiliency_policy:
      name: resiliency_policy
      id: awscc.resiliencehub.resiliency_policy
      x-cfn-schema-name: ResiliencyPolicy
      x-type: get
      x-identifiers:
        - PolicyArn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.PolicyName') as policy_name,
              JSON_EXTRACT(Properties, '$.PolicyDescription') as policy_description,
              JSON_EXTRACT(Properties, '$.DataLocationConstraint') as data_location_constraint,
              JSON_EXTRACT(Properties, '$.Tier') as tier,
              JSON_EXTRACT(Properties, '$.Policy') as policy,
              JSON_EXTRACT(Properties, '$.PolicyArn') as policy_arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::ResilienceHub::ResiliencyPolicy'
              AND data__Identifier = '<PolicyArn>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'PolicyName') as policy_name,
                json_extract_path_text(Properties, 'PolicyDescription') as policy_description,
                json_extract_path_text(Properties, 'DataLocationConstraint') as data_location_constraint,
                json_extract_path_text(Properties, 'Tier') as tier,
                json_extract_path_text(Properties, 'Policy') as policy,
                json_extract_path_text(Properties, 'PolicyArn') as policy_arn,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::ResilienceHub::ResiliencyPolicy'
                AND data__Identifier = '<PolicyArn>'
                AND region = 'us-east-1'
