openapi: 3.0.0
info:
  title: SimSpaceWeaver
  version: 1.0.0
paths: {}
components:
  schemas:
    S3Location:
      type: object
      properties:
        BucketName:
          description: The Schema S3 bucket name.
          type: string
          minLength: 3
          maxLength: 63
          pattern: '[a-zA-Z0-9_\-]{3,63}$'
        ObjectKey:
          description: This is the schema S3 object key, which includes the full path of "folders" from the bucket root to the schema.
          type: string
          minLength: 3
          maxLength: 255
      required:
        - BucketName
        - ObjectKey
      additionalProperties: false
    Simulation:
      type: object
      properties:
        Name:
          description: The name of the simulation.
          type: string
          minLength: 1
          maxLength: 2048
          pattern: '[a-zA-Z0-9_\-]{1,2048}$'
        RoleArn:
          description: Role ARN.
          type: string
        SchemaS3Location:
          $ref: '#/components/schemas/S3Location'
        DescribePayload:
          description: Json object with all simulation details
          type: string
        MaximumDuration:
          description: The maximum running time of the simulation.
          type: string
          minLength: 2
          maxLength: 6
        SnapshotS3Location:
          $ref: '#/components/schemas/S3Location'
      required:
        - Name
        - RoleArn
      x-stackql-resource-name: simulation
      x-stackql-primaryIdentifier:
        - Name
      x-create-only-properties:
        - Name
        - RoleArn
        - SchemaS3Location
        - SnapshotS3Location
        - MaximumDuration
      x-read-only-properties:
        - DescribePayload
      x-required-permissions:
        create:
          - simspaceweaver:StartSimulation
          - simspaceweaver:DescribeSimulation
          - iam:GetRole
          - iam:PassRole
        read:
          - simspaceweaver:DescribeSimulation
        update:
          - simspaceweaver:StartSimulation
          - simspaceweaver:StopSimulation
          - simspaceweaver:DeleteSimulation
          - simspaceweaver:DescribeSimulation
        delete:
          - simspaceweaver:StopSimulation
          - simspaceweaver:DeleteSimulation
          - simspaceweaver:DescribeSimulation
        list:
          - simspaceweaver:ListSimulations
  x-stackQL-resources:
    simulations:
      name: simulations
      id: awscc.simspaceweaver.simulations
      x-cfn-schema-name: Simulation
      x-type: list
      x-identifiers:
        - Name
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Name') as name
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::SimSpaceWeaver::Simulation'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Name') as name
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::SimSpaceWeaver::Simulation'
                AND region = 'us-east-1'
    simulation:
      name: simulation
      id: awscc.simspaceweaver.simulation
      x-cfn-schema-name: Simulation
      x-type: get
      x-identifiers:
        - Name
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.RoleArn') as role_arn,
              JSON_EXTRACT(Properties, '$.SchemaS3Location') as schema_s3_location,
              JSON_EXTRACT(Properties, '$.DescribePayload') as describe_payload,
              JSON_EXTRACT(Properties, '$.MaximumDuration') as maximum_duration,
              JSON_EXTRACT(Properties, '$.SnapshotS3Location') as snapshot_s3_location
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::SimSpaceWeaver::Simulation'
              AND data__Identifier = '<Name>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Name') as name,
                json_extract_path_text(Properties, 'RoleArn') as role_arn,
                json_extract_path_text(Properties, 'SchemaS3Location') as schema_s3_location,
                json_extract_path_text(Properties, 'DescribePayload') as describe_payload,
                json_extract_path_text(Properties, 'MaximumDuration') as maximum_duration,
                json_extract_path_text(Properties, 'SnapshotS3Location') as snapshot_s3_location
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::SimSpaceWeaver::Simulation'
                AND data__Identifier = '<Name>'
                AND region = 'us-east-1'
