openapi: 3.0.0
info:
  title: SQS
  version: 1.0.0
paths: {}
components:
  schemas:
    Tag:
      type: object
      additionalProperties: false
      properties:
        Key:
          description: 'The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          type: string
        Value:
          description: 'The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          type: string
      required:
        - Value
        - Key
    Queue:
      type: object
      properties:
        QueueUrl:
          type: string
          description: URL of the source queue.
        Arn:
          type: string
          description: Amazon Resource Name (ARN) of the queue.
        ContentBasedDeduplication:
          type: boolean
          description: For first-in-first-out (FIFO) queues, specifies whether to enable content-based deduplication. During the deduplication interval, Amazon SQS treats messages that are sent with identical content as duplicates and delivers only one copy of the message.
        DeduplicationScope:
          description: Specifies whether message deduplication occurs at the message group or queue level. Valid values are messageGroup and queue.
          type: string
        DelaySeconds:
          type: integer
          description: The time in seconds for which the delivery of all messages in the queue is delayed. You can specify an integer value of 0 to 900 (15 minutes). The default value is 0.
        FifoQueue:
          type: boolean
          description: If set to true, creates a FIFO queue. If you don't specify this property, Amazon SQS creates a standard queue.
        FifoThroughputLimit:
          description: Specifies whether the FIFO queue throughput quota applies to the entire queue or per message group. Valid values are perQueue and perMessageGroupId. The perMessageGroupId value is allowed only when the value for DeduplicationScope is messageGroup.
          type: string
        KmsDataKeyReusePeriodSeconds:
          type: integer
          description: The length of time in seconds for which Amazon SQS can reuse a data key to encrypt or decrypt messages before calling AWS KMS again. The value must be an integer between 60 (1 minute) and 86,400 (24 hours). The default is 300 (5 minutes).
        KmsMasterKeyId:
          type: string
          description: The ID of an AWS managed customer master key (CMK) for Amazon SQS or a custom CMK. To use the AWS managed CMK for Amazon SQS, specify the (default) alias alias/aws/sqs.
        SqsManagedSseEnabled:
          type: boolean
          description: Enables server-side queue encryption using SQS owned encryption keys. Only one server-side encryption option is supported per queue (e.g. SSE-KMS or SSE-SQS ).
        MaximumMessageSize:
          type: integer
          description: The limit of how many bytes that a message can contain before Amazon SQS rejects it. You can specify an integer value from 1,024 bytes (1 KiB) to 262,144 bytes (256 KiB). The default value is 262,144 (256 KiB).
        MessageRetentionPeriod:
          type: integer
          description: The number of seconds that Amazon SQS retains a message. You can specify an integer value from 60 seconds (1 minute) to 1,209,600 seconds (14 days). The default value is 345,600 seconds (4 days).
        QueueName:
          type: string
          description: A name for the queue. To create a FIFO queue, the name of your FIFO queue must end with the .fifo suffix.
        ReceiveMessageWaitTimeSeconds:
          type: integer
          description: Specifies the duration, in seconds, that the ReceiveMessage action call waits until a message is in the queue in order to include it in the response, rather than returning an empty response if a message isn't yet available. You can specify an integer from 1 to 20. Short polling is used as the default or when you specify 0 for this property.
        RedriveAllowPolicy:
          type: object
          description: The string that includes the parameters for the permissions for the dead-letter queue redrive permission and which source queues can specify dead-letter queues as a JSON object.
        RedrivePolicy:
          type: object
          description: A string that includes the parameters for the dead-letter queue functionality (redrive policy) of the source queue.
        Tags:
          type: array
          description: The tags that you attach to this queue.
          uniqueItems: false
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
        VisibilityTimeout:
          type: integer
          description: The length of time during which a message will be unavailable after a message is delivered from the queue. This blocks other components from receiving the same message and gives the initial component time to process and delete the message from the queue. Values must be from 0 to 43,200 seconds (12 hours). If you don't specify a value, AWS CloudFormation uses the default value of 30 seconds.
      x-stackql-resource-name: queue
      x-stackql-primaryIdentifier:
        - QueueUrl
      x-create-only-properties:
        - FifoQueue
        - QueueName
      x-read-only-properties:
        - QueueUrl
        - Arn
      x-required-permissions:
        create:
          - sqs:CreateQueue
          - sqs:GetQueueUrl
          - sqs:GetQueueAttributes
          - sqs:ListQueueTags
          - sqs:TagQueue
        read:
          - sqs:GetQueueAttributes
          - sqs:ListQueueTags
        update:
          - sqs:SetQueueAttributes
          - sqs:GetQueueAttributes
          - sqs:ListQueueTags
          - sqs:TagQueue
          - sqs:UntagQueue
        delete:
          - sqs:DeleteQueue
          - sqs:GetQueueAttributes
        list:
          - sqs:ListQueues
    QueueInlinePolicy:
      type: object
      properties:
        PolicyDocument:
          description: A policy document that contains permissions to add to the specified SQS queue
          type: object
        Queue:
          description: The URL of the SQS queue.
          type: string
      required:
        - PolicyDocument
        - Queue
      x-stackql-resource-name: queue_inline_policy
      x-stackql-primaryIdentifier:
        - Queue
      x-create-only-properties:
        - Queue
      x-required-permissions:
        create:
          - sqs:SetQueueAttributes
          - sqs:GetQueueAttributes
          - sqs:GetQueueUrl
        read:
          - sqs:GetQueueAttributes
          - sqs:GetQueueUrl
        delete:
          - sqs:SetQueueAttributes
          - sqs:GetQueueAttributes
        update:
          - sqs:SetQueueAttributes
          - sqs:GetQueueAttributes
          - sqs:GetQueueUrl
    QueuePolicy:
      type: object
      properties:
        Id:
          type: string
          description: ''
        PolicyDocument:
          type: object
          description: A policy document that contains the permissions for the specified SQS queues. For more information about SQS policies, see [Using custom policies with the access policy language](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-creating-custom-policies.html) in the *Developer Guide*.
        Queues:
          type: array
          description: The URLs of the queues to which you want to add the policy. You can use the ``Ref`` function to specify an ``AWS::SQS::Queue`` resource.
          uniqueItems: false
          x-insertionOrder: false
          items:
            type: string
      required:
        - PolicyDocument
        - Queues
      x-stackql-resource-name: queue_policy
      x-stackql-primaryIdentifier:
        - Id
      x-read-only-properties:
        - Id
      x-required-permissions:
        create:
          - sqs:SetQueueAttributes
        update:
          - sqs:SetQueueAttributes
        delete:
          - sqs:SetQueueAttributes
  x-stackQL-resources:
    queues:
      name: queues
      id: awscc.sqs.queues
      x-cfn-schema-name: Queue
      x-type: list
      x-identifiers:
        - QueueUrl
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.QueueUrl') as queue_url
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::SQS::Queue'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'QueueUrl') as queue_url
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::SQS::Queue'
                AND region = 'us-east-1'
    queue:
      name: queue
      id: awscc.sqs.queue
      x-cfn-schema-name: Queue
      x-type: get
      x-identifiers:
        - QueueUrl
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.QueueUrl') as queue_url,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.ContentBasedDeduplication') as content_based_deduplication,
              JSON_EXTRACT(Properties, '$.DeduplicationScope') as deduplication_scope,
              JSON_EXTRACT(Properties, '$.DelaySeconds') as delay_seconds,
              JSON_EXTRACT(Properties, '$.FifoQueue') as fifo_queue,
              JSON_EXTRACT(Properties, '$.FifoThroughputLimit') as fifo_throughput_limit,
              JSON_EXTRACT(Properties, '$.KmsDataKeyReusePeriodSeconds') as kms_data_key_reuse_period_seconds,
              JSON_EXTRACT(Properties, '$.KmsMasterKeyId') as kms_master_key_id,
              JSON_EXTRACT(Properties, '$.SqsManagedSseEnabled') as sqs_managed_sse_enabled,
              JSON_EXTRACT(Properties, '$.MaximumMessageSize') as maximum_message_size,
              JSON_EXTRACT(Properties, '$.MessageRetentionPeriod') as message_retention_period,
              JSON_EXTRACT(Properties, '$.QueueName') as queue_name,
              JSON_EXTRACT(Properties, '$.ReceiveMessageWaitTimeSeconds') as receive_message_wait_time_seconds,
              JSON_EXTRACT(Properties, '$.RedriveAllowPolicy') as redrive_allow_policy,
              JSON_EXTRACT(Properties, '$.RedrivePolicy') as redrive_policy,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.VisibilityTimeout') as visibility_timeout
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::SQS::Queue'
              AND data__Identifier = '<QueueUrl>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'QueueUrl') as queue_url,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'ContentBasedDeduplication') as content_based_deduplication,
                json_extract_path_text(Properties, 'DeduplicationScope') as deduplication_scope,
                json_extract_path_text(Properties, 'DelaySeconds') as delay_seconds,
                json_extract_path_text(Properties, 'FifoQueue') as fifo_queue,
                json_extract_path_text(Properties, 'FifoThroughputLimit') as fifo_throughput_limit,
                json_extract_path_text(Properties, 'KmsDataKeyReusePeriodSeconds') as kms_data_key_reuse_period_seconds,
                json_extract_path_text(Properties, 'KmsMasterKeyId') as kms_master_key_id,
                json_extract_path_text(Properties, 'SqsManagedSseEnabled') as sqs_managed_sse_enabled,
                json_extract_path_text(Properties, 'MaximumMessageSize') as maximum_message_size,
                json_extract_path_text(Properties, 'MessageRetentionPeriod') as message_retention_period,
                json_extract_path_text(Properties, 'QueueName') as queue_name,
                json_extract_path_text(Properties, 'ReceiveMessageWaitTimeSeconds') as receive_message_wait_time_seconds,
                json_extract_path_text(Properties, 'RedriveAllowPolicy') as redrive_allow_policy,
                json_extract_path_text(Properties, 'RedrivePolicy') as redrive_policy,
                json_extract_path_text(Properties, 'Tags') as tags,
                json_extract_path_text(Properties, 'VisibilityTimeout') as visibility_timeout
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::SQS::Queue'
                AND data__Identifier = '<QueueUrl>'
                AND region = 'us-east-1'
    queue_inline_policies:
      name: queue_inline_policies
      id: awscc.sqs.queue_inline_policies
      x-cfn-schema-name: QueueInlinePolicy
      x-type: list
      x-identifiers:
        - Queue
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Queue') as queue
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::SQS::QueueInlinePolicy'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Queue') as queue
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::SQS::QueueInlinePolicy'
                AND region = 'us-east-1'
    queue_inline_policy:
      name: queue_inline_policy
      id: awscc.sqs.queue_inline_policy
      x-cfn-schema-name: QueueInlinePolicy
      x-type: get
      x-identifiers:
        - Queue
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.PolicyDocument') as policy_document,
              JSON_EXTRACT(Properties, '$.Queue') as queue
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::SQS::QueueInlinePolicy'
              AND data__Identifier = '<Queue>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'PolicyDocument') as policy_document,
                json_extract_path_text(Properties, 'Queue') as queue
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::SQS::QueueInlinePolicy'
                AND data__Identifier = '<Queue>'
                AND region = 'us-east-1'
    queue_policies:
      name: queue_policies
      id: awscc.sqs.queue_policies
      x-cfn-schema-name: QueuePolicy
      x-type: list
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::SQS::QueuePolicy'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Id') as id
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::SQS::QueuePolicy'
                AND region = 'us-east-1'
    queue_policy:
      name: queue_policy
      id: awscc.sqs.queue_policy
      x-cfn-schema-name: QueuePolicy
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.PolicyDocument') as policy_document,
              JSON_EXTRACT(Properties, '$.Queues') as queues
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::SQS::QueuePolicy'
              AND data__Identifier = '<Id>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Id') as id,
                json_extract_path_text(Properties, 'PolicyDocument') as policy_document,
                json_extract_path_text(Properties, 'Queues') as queues
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::SQS::QueuePolicy'
                AND data__Identifier = '<Id>'
                AND region = 'us-east-1'
