openapi: 3.0.0
info:
  title: SystemsManagerSAP
  version: 1.0.0
paths: {}
components:
  schemas:
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      properties:
        Key:
          description: 'The key name of the tag. You can specify a value that is 1 to 127 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          type: string
          minLength: 1
          maxLength: 128
        Value:
          description: 'The value for the tag. You can specify a value that is 1 to 255 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          type: string
          minLength: 0
          maxLength: 256
      required:
        - Key
        - Value
      additionalProperties: false
    Credential:
      type: object
      properties:
        DatabaseName:
          type: string
          pattern: ^(?=.{1,100}$).*
        CredentialType:
          type: string
          enum:
            - ADMIN
        SecretId:
          type: string
          pattern: ^(?=.{1,100}$).*
      additionalProperties: false
    Instance:
      type: string
      pattern: ^i-[\w\d]{8}$|^i-[\w\d]{17}$
    Application:
      type: object
      properties:
        ApplicationId:
          type: string
          pattern: '[\w\d]{1,50}'
        ApplicationType:
          type: string
          enum:
            - HANA
        Arn:
          description: The ARN of the Helix application
          type: string
          pattern: ^arn:(.+:){2,4}.+$|^arn:(.+:){1,3}.+\/.+$
        Credentials:
          type: array
          items:
            $ref: '#/components/schemas/Credential'
          minItems: 1
          x-insertionOrder: true
        Instances:
          type: array
          items:
            $ref: '#/components/schemas/Instance'
          minItems: 1
          x-insertionOrder: true
        SapInstanceNumber:
          type: string
          pattern: '[0-9]{2}'
        Sid:
          type: string
          pattern: '[A-Z][A-Z0-9]{2}'
        Tags:
          description: The tags of a SystemsManagerSAP application.
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          x-insertionOrder: true
      required:
        - ApplicationId
        - ApplicationType
      x-stackql-resource-name: application
      x-stackql-primaryIdentifier:
        - Arn
      x-create-only-properties:
        - Credentials
        - Instances
        - SapInstanceNumber
        - Sid
      x-read-only-properties:
        - Arn
      x-required-permissions:
        create:
          - ssm-sap:RegisterApplication
          - ssm-sap:GetApplication
          - ssm-sap:TagResource
          - ssm-sap:ListTagsForResource
        read:
          - ssm-sap:GetApplication
          - ssm-sap:ListTagsForResource
        update:
          - ssm-sap:TagResource
          - ssm-sap:UntagResource
          - ssm-sap:ListTagsForResource
          - ssm-sap:GetApplication
        delete:
          - ssm-sap:DeregisterApplication
          - ssm-sap:GetApplication
        list:
          - ssm-sap:ListApplications
  x-stackQL-resources:
    applications:
      name: applications
      id: awscc.systemsmanagersap.applications
      x-cfn-schema-name: Application
      x-type: list
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::SystemsManagerSAP::Application'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Arn') as arn
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::SystemsManagerSAP::Application'
                AND region = 'us-east-1'
    application:
      name: application
      id: awscc.systemsmanagersap.application
      x-cfn-schema-name: Application
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ApplicationId') as application_id,
              JSON_EXTRACT(Properties, '$.ApplicationType') as application_type,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Credentials') as credentials,
              JSON_EXTRACT(Properties, '$.Instances') as instances,
              JSON_EXTRACT(Properties, '$.SapInstanceNumber') as sap_instance_number,
              JSON_EXTRACT(Properties, '$.Sid') as sid,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::SystemsManagerSAP::Application'
              AND data__Identifier = '<Arn>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'ApplicationId') as application_id,
                json_extract_path_text(Properties, 'ApplicationType') as application_type,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'Credentials') as credentials,
                json_extract_path_text(Properties, 'Instances') as instances,
                json_extract_path_text(Properties, 'SapInstanceNumber') as sap_instance_number,
                json_extract_path_text(Properties, 'Sid') as sid,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::SystemsManagerSAP::Application'
                AND data__Identifier = '<Arn>'
                AND region = 'us-east-1'
