openapi: 3.0.0
info:
  title: Wisdom
  version: 1.0.0
paths: {}
components:
  schemas:
    AssistantType:
      type: string
      enum:
        - AGENT
    ServerSideEncryptionConfiguration:
      type: object
      properties:
        KmsKeyId:
          type: string
          maxLength: 4096
          minLength: 1
      additionalProperties: false
    Tag:
      additionalProperties: false
      properties:
        Key:
          maxLength: 128
          minLength: 1
          pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
          type: string
        Value:
          maxLength: 256
          minLength: 1
          type: string
      required:
        - Key
        - Value
      type: object
    Assistant:
      type: object
      properties:
        Type:
          $ref: '#/components/schemas/AssistantType'
        Description:
          type: string
          maxLength: 255
          minLength: 1
        AssistantArn:
          type: string
          pattern: ^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})?$
        AssistantId:
          type: string
          pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
        ServerSideEncryptionConfiguration:
          $ref: '#/components/schemas/ServerSideEncryptionConfiguration'
        Tags:
          x-insertionOrder: false
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Tag'
          type: array
        Name:
          type: string
          maxLength: 255
          minLength: 1
      required:
        - Name
        - Type
      x-stackql-resource-name: assistant
      x-stackql-primaryIdentifier:
        - AssistantId
      x-create-only-properties:
        - Description
        - Name
        - ServerSideEncryptionConfiguration
        - Tags
        - Type
      x-read-only-properties:
        - AssistantId
        - AssistantArn
      x-required-permissions:
        create:
          - kms:CreateGrant
          - kms:DescribeKey
          - wisdom:CreateAssistant
          - wisdom:TagResource
        update:
          - wisdom:GetAssistant
        read:
          - wisdom:GetAssistant
        list:
          - wisdom:ListAssistants
        delete:
          - wisdom:DeleteAssistant
    AssociationData:
      type: object
      properties:
        KnowledgeBaseId:
          type: string
          pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
      required:
        - KnowledgeBaseId
      additionalProperties: false
    AssociationType:
      type: string
      enum:
        - KNOWLEDGE_BASE
    AssistantAssociation:
      type: object
      properties:
        AssistantAssociationArn:
          type: string
          pattern: ^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})?$
        AssistantArn:
          type: string
          pattern: ^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})?$
        AssistantAssociationId:
          type: string
          pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
        AssistantId:
          type: string
          pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
        Association:
          $ref: '#/components/schemas/AssociationData'
        AssociationType:
          $ref: '#/components/schemas/AssociationType'
        Tags:
          x-insertionOrder: false
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Tag'
          type: array
      required:
        - Association
        - AssociationType
        - AssistantId
      x-stackql-resource-name: assistant_association
      x-stackql-primaryIdentifier:
        - AssistantAssociationId
        - AssistantId
      x-create-only-properties:
        - Association
        - AssociationType
        - AssistantId
        - Tags
      x-read-only-properties:
        - AssistantAssociationId
        - AssistantAssociationArn
        - AssistantArn
      x-required-permissions:
        create:
          - wisdom:CreateAssistantAssociation
          - wisdom:TagResource
        update:
          - wisdom:GetAssistantAssociation
        read:
          - wisdom:GetAssistantAssociation
        list:
          - wisdom:ListAssistantAssociations
        delete:
          - wisdom:DeleteAssistantAssociation
    AppIntegrationsConfiguration:
      type: object
      properties:
        ObjectFields:
          type: array
          items:
            type: string
            maxLength: 4096
            minLength: 1
          x-insertionOrder: false
          maxItems: 100
          minItems: 1
        AppIntegrationArn:
          type: string
          maxLength: 2048
          minLength: 1
          pattern: ^arn:[a-z-]+?:[a-z-]+?:[a-z0-9-]*?:([0-9]{12})?:[a-zA-Z0-9-:/]+$
      required:
        - AppIntegrationArn
      additionalProperties: false
    KnowledgeBaseType:
      type: string
      enum:
        - EXTERNAL
        - CUSTOM
    RenderingConfiguration:
      type: object
      properties:
        TemplateUri:
          type: string
          maxLength: 4096
          minLength: 1
      additionalProperties: false
    SourceConfiguration:
      type: object
      properties:
        AppIntegrations:
          $ref: '#/components/schemas/AppIntegrationsConfiguration'
      oneOf:
        - required:
            - AppIntegrations
      additionalProperties: false
    KnowledgeBase:
      type: object
      properties:
        Description:
          type: string
          maxLength: 255
          minLength: 1
        KnowledgeBaseArn:
          type: string
          pattern: ^arn:[a-z-]*?:wisdom:[a-z0-9-]*?:[0-9]{12}:[a-z-]*?/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}(?:/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})?$
        KnowledgeBaseId:
          type: string
          pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
        KnowledgeBaseType:
          $ref: '#/components/schemas/KnowledgeBaseType'
        Name:
          type: string
          maxLength: 255
          minLength: 1
        RenderingConfiguration:
          $ref: '#/components/schemas/RenderingConfiguration'
        ServerSideEncryptionConfiguration:
          $ref: '#/components/schemas/ServerSideEncryptionConfiguration'
        SourceConfiguration:
          $ref: '#/components/schemas/SourceConfiguration'
        Tags:
          x-insertionOrder: false
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Tag'
          type: array
      required:
        - KnowledgeBaseType
        - Name
      x-stackql-resource-name: knowledge_base
      x-stackql-primaryIdentifier:
        - KnowledgeBaseId
      x-create-only-properties:
        - Description
        - KnowledgeBaseType
        - Name
        - ServerSideEncryptionConfiguration
        - SourceConfiguration
        - Tags
      x-read-only-properties:
        - KnowledgeBaseId
        - KnowledgeBaseArn
      x-required-permissions:
        create:
          - appflow:CreateFlow
          - appflow:DeleteFlow
          - appflow:StartFlow
          - appflow:TagResource
          - appflow:UseConnectorProfile
          - app-integrations:CreateDataIntegrationAssociation
          - app-integrations:GetDataIntegration
          - kms:DescribeKey
          - kms:CreateGrant
          - kms:ListGrants
          - wisdom:CreateKnowledgeBase
          - wisdom:TagResource
        update:
          - wisdom:GetKnowledgeBase
        delete:
          - appflow:DeleteFlow
          - appflow:StopFlow
          - app-integrations:DeleteDataIntegrationAssociation
          - wisdom:DeleteKnowledgeBase
        list:
          - wisdom:ListKnowledgeBases
        read:
          - wisdom:GetKnowledgeBase
  x-stackQL-resources:
    assistants:
      name: assistants
      id: awscc.wisdom.assistants
      x-cfn-schema-name: Assistant
      x-type: list
      x-identifiers:
        - AssistantId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.AssistantId') as assistant_id
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::Wisdom::Assistant'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'AssistantId') as assistant_id
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::Wisdom::Assistant'
                AND region = 'us-east-1'
    assistant:
      name: assistant
      id: awscc.wisdom.assistant
      x-cfn-schema-name: Assistant
      x-type: get
      x-identifiers:
        - AssistantId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.Type') as type,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.AssistantArn') as assistant_arn,
              JSON_EXTRACT(Properties, '$.AssistantId') as assistant_id,
              JSON_EXTRACT(Properties, '$.ServerSideEncryptionConfiguration') as server_side_encryption_configuration,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.Name') as name
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::Wisdom::Assistant'
              AND data__Identifier = '<AssistantId>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'Type') as type,
                json_extract_path_text(Properties, 'Description') as description,
                json_extract_path_text(Properties, 'AssistantArn') as assistant_arn,
                json_extract_path_text(Properties, 'AssistantId') as assistant_id,
                json_extract_path_text(Properties, 'ServerSideEncryptionConfiguration') as server_side_encryption_configuration,
                json_extract_path_text(Properties, 'Tags') as tags,
                json_extract_path_text(Properties, 'Name') as name
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::Wisdom::Assistant'
                AND data__Identifier = '<AssistantId>'
                AND region = 'us-east-1'
    assistant_associations:
      name: assistant_associations
      id: awscc.wisdom.assistant_associations
      x-cfn-schema-name: AssistantAssociation
      x-type: list
      x-identifiers:
        - AssistantAssociationId
        - AssistantId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.AssistantAssociationId') as assistant_association_id,
              JSON_EXTRACT(Properties, '$.AssistantId') as assistant_id
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::Wisdom::AssistantAssociation'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'AssistantAssociationId') as assistant_association_id,
                json_extract_path_text(Properties, 'AssistantId') as assistant_id
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::Wisdom::AssistantAssociation'
                AND region = 'us-east-1'
    assistant_association:
      name: assistant_association
      id: awscc.wisdom.assistant_association
      x-cfn-schema-name: AssistantAssociation
      x-type: get
      x-identifiers:
        - AssistantAssociationId
        - AssistantId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.AssistantAssociationArn') as assistant_association_arn,
              JSON_EXTRACT(Properties, '$.AssistantArn') as assistant_arn,
              JSON_EXTRACT(Properties, '$.AssistantAssociationId') as assistant_association_id,
              JSON_EXTRACT(Properties, '$.AssistantId') as assistant_id,
              JSON_EXTRACT(Properties, '$.Association') as association,
              JSON_EXTRACT(Properties, '$.AssociationType') as association_type,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::Wisdom::AssistantAssociation'
              AND data__Identifier = '<AssistantAssociationId>|<AssistantId>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'AssistantAssociationArn') as assistant_association_arn,
                json_extract_path_text(Properties, 'AssistantArn') as assistant_arn,
                json_extract_path_text(Properties, 'AssistantAssociationId') as assistant_association_id,
                json_extract_path_text(Properties, 'AssistantId') as assistant_id,
                json_extract_path_text(Properties, 'Association') as association,
                json_extract_path_text(Properties, 'AssociationType') as association_type,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::Wisdom::AssistantAssociation'
                AND data__Identifier = '<AssistantAssociationId>|<AssistantId>'
                AND region = 'us-east-1'
    knowledge_bases:
      name: knowledge_bases
      id: awscc.wisdom.knowledge_bases
      x-cfn-schema-name: KnowledgeBase
      x-type: list
      x-identifiers:
        - KnowledgeBaseId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.KnowledgeBaseId') as knowledge_base_id
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::Wisdom::KnowledgeBase'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'KnowledgeBaseId') as knowledge_base_id
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::Wisdom::KnowledgeBase'
                AND region = 'us-east-1'
    knowledge_base:
      name: knowledge_base
      id: awscc.wisdom.knowledge_base
      x-cfn-schema-name: KnowledgeBase
      x-type: get
      x-identifiers:
        - KnowledgeBaseId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.KnowledgeBaseArn') as knowledge_base_arn,
              JSON_EXTRACT(Properties, '$.KnowledgeBaseId') as knowledge_base_id,
              JSON_EXTRACT(Properties, '$.KnowledgeBaseType') as knowledge_base_type,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.RenderingConfiguration') as rendering_configuration,
              JSON_EXTRACT(Properties, '$.ServerSideEncryptionConfiguration') as server_side_encryption_configuration,
              JSON_EXTRACT(Properties, '$.SourceConfiguration') as source_configuration,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::Wisdom::KnowledgeBase'
              AND data__Identifier = '<KnowledgeBaseId>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'Description') as description,
                json_extract_path_text(Properties, 'KnowledgeBaseArn') as knowledge_base_arn,
                json_extract_path_text(Properties, 'KnowledgeBaseId') as knowledge_base_id,
                json_extract_path_text(Properties, 'KnowledgeBaseType') as knowledge_base_type,
                json_extract_path_text(Properties, 'Name') as name,
                json_extract_path_text(Properties, 'RenderingConfiguration') as rendering_configuration,
                json_extract_path_text(Properties, 'ServerSideEncryptionConfiguration') as server_side_encryption_configuration,
                json_extract_path_text(Properties, 'SourceConfiguration') as source_configuration,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::Wisdom::KnowledgeBase'
                AND data__Identifier = '<KnowledgeBaseId>'
                AND region = 'us-east-1'
