openapi: 3.0.0
info:
  title: WorkSpaces
  version: 1.0.0
paths: {}
components:
  schemas:
    ConnectionAliasAssociation:
      type: object
      additionalProperties: false
      properties:
        AssociationStatus:
          type: string
          enum:
            - NOT_ASSOCIATED
            - PENDING_ASSOCIATION
            - ASSOCIATED_WITH_OWNER_ACCOUNT
            - ASSOCIATED_WITH_SHARED_ACCOUNT
            - PENDING_DISASSOCIATION
        AssociatedAccountId:
          type: string
        ResourceId:
          type: string
          pattern: .+
          minLength: 1
          maxLength: 1000
        ConnectionIdentifier:
          type: string
          maxLength: 20
          minLength: 1
          pattern: ^[a-zA-Z0-9]+$
    Tag:
      type: object
      additionalProperties: false
      properties:
        Key:
          type: string
        Value:
          type: string
      required:
        - Value
        - Key
    ConnectionAlias:
      type: object
      properties:
        Associations:
          type: array
          maxLength: 25
          minLength: 1
          items:
            $ref: '#/components/schemas/ConnectionAliasAssociation'
        AliasId:
          type: string
          pattern: ^wsca-[0-9a-z]{8,63}$
          maxLength: 68
          minLength: 13
        ConnectionString:
          type: string
          pattern: ^[.0-9a-zA-Z\-]{1,255}$
          minLength: 1
          maxLength: 255
        ConnectionAliasState:
          type: string
          enum:
            - CREATING
            - CREATED
            - DELETING
        Tags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - ConnectionString
      x-stackql-resource-name: connection_alias
      x-stackql-primaryIdentifier:
        - AliasId
      x-create-only-properties:
        - ConnectionString
        - Tags
      x-read-only-properties:
        - ConnectionAliasState
        - AliasId
        - Associations
      x-required-permissions:
        create:
          - workspaces:CreateConnectionAlias
        read:
          - workspaces:DescribeConnectionAliases
        delete:
          - workspaces:DeleteConnectionAlias
  x-stackQL-resources:
    connection_alias:
      name: connection_alias
      id: awscc.workspaces.connection_alias
      x-cfn-schema-name: ConnectionAlias
      x-type: get
      x-identifiers:
        - AliasId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.Associations') as associations,
              JSON_EXTRACT(Properties, '$.AliasId') as alias_id,
              JSON_EXTRACT(Properties, '$.ConnectionString') as connection_string,
              JSON_EXTRACT(Properties, '$.ConnectionAliasState') as connection_alias_state,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::WorkSpaces::ConnectionAlias'
              AND data__Identifier = '<AliasId>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'Associations') as associations,
                json_extract_path_text(Properties, 'AliasId') as alias_id,
                json_extract_path_text(Properties, 'ConnectionString') as connection_string,
                json_extract_path_text(Properties, 'ConnectionAliasState') as connection_alias_state,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::WorkSpaces::ConnectionAlias'
                AND data__Identifier = '<AliasId>'
                AND region = 'us-east-1'
