openapi: 3.0.0
info:
  title: XRay
  version: 1.0.0
paths: {}
components:
  schemas:
    InsightsConfiguration:
      type: object
      additionalProperties: false
      properties:
        InsightsEnabled:
          description: Set the InsightsEnabled value to true to enable insights or false to disable insights.
          type: boolean
        NotificationsEnabled:
          description: Set the NotificationsEnabled value to true to enable insights notifications. Notifications can only be enabled on a group with InsightsEnabled set to true.
          type: boolean
    Tag:
      type: object
      properties:
        Key:
          type: string
          description: The key name of the tag.
        Value:
          type: string
          description: The value for the tag.
      required:
        - Key
        - Value
      additionalProperties: false
    Tags:
      type: array
      x-insertionOrder: false
      description: An array of key-value pairs to apply to this resource.
      items:
        $ref: '#/components/schemas/Tag'
    Group:
      type: object
      properties:
        FilterExpression:
          description: The filter expression defining criteria by which to group traces.
          type: string
        GroupName:
          description: The case-sensitive name of the new group. Names must be unique.
          type: string
          minLength: 1
          maxLength: 32
        GroupARN:
          description: The ARN of the group that was generated on creation.
          type: string
          minLength: 1
          maxLength: 400
        InsightsConfiguration:
          $ref: '#/components/schemas/InsightsConfiguration'
        Tags:
          $ref: '#/components/schemas/Tags'
      required:
        - GroupName
      x-stackql-resource-name: group
      x-stackql-primaryIdentifier:
        - GroupARN
      x-read-only-properties:
        - GroupARN
      x-required-permissions:
        create:
          - xray:CreateGroup
          - xray:TagResource
        read:
          - xray:GetGroup
          - xray:ListTagsForResource
        update:
          - xray:UpdateGroup
          - xray:TagResource
          - xray:UntagResource
          - xray:ListTagsForResource
        delete:
          - xray:DeleteGroup
        list:
          - xray:GetGroups
          - xray:ListTagsForResource
    ResourcePolicy:
      type: object
      properties:
        PolicyName:
          description: The name of the resource policy. Must be unique within a specific AWS account.
          type: string
          pattern: '[\w+=,.@-]+'
          minLength: 1
          maxLength: 128
        PolicyDocument:
          description: The resource policy document, which can be up to 5kb in size.
          type: string
          minLength: 1
          maxLength: 5120
        BypassPolicyLockoutCheck:
          description: A flag to indicate whether to bypass the resource policy lockout safety check
          type: boolean
      required:
        - PolicyName
        - PolicyDocument
      x-stackql-resource-name: resource_policy
      x-stackql-primaryIdentifier:
        - PolicyName
      x-create-only-properties:
        - PolicyName
      x-required-permissions:
        create:
          - xray:PutResourcePolicy
          - xray:ListResourcePolicies
        read:
          - xray:ListResourcePolicies
        update:
          - xray:PutResourcePolicy
          - xray:ListResourcePolicies
        delete:
          - xray:DeleteResourcePolicy
        list:
          - xray:ListResourcePolicies
    SamplingRule:
      type: object
      properties:
        SamplingRule:
          $ref: '#/components/schemas/SamplingRule'
        SamplingRuleRecord:
          $ref: '#/components/schemas/SamplingRuleRecord'
        SamplingRuleUpdate:
          $ref: '#/components/schemas/SamplingRuleUpdate'
        RuleARN:
          $ref: '#/components/schemas/RuleARN'
        RuleName:
          $ref: '#/components/schemas/RuleName'
        Tags:
          $ref: '#/components/schemas/Tags'
      x-stackql-resource-name: sampling_rule
      x-stackql-primaryIdentifier:
        - RuleARN
      x-create-only-properties:
        - SamplingRule/Version
      x-read-only-properties:
        - RuleARN
      x-required-permissions:
        create:
          - xray:CreateSamplingRule
          - xray:TagResource
        read:
          - xray:GetSamplingRules
          - xray:ListTagsForResource
        update:
          - xray:UpdateSamplingRule
          - xray:TagResource
          - xray:UntagResource
          - xray:ListTagsForResource
        delete:
          - xray:DeleteSamplingRule
        list:
          - xray:GetSamplingRules
          - xray:ListTagsForResource
    SamplingRuleRecord:
      type: object
      additionalProperties: false
      properties:
        CreatedAt:
          description: When the rule was created, in Unix time seconds.
          type: string
        ModifiedAt:
          description: When the rule was modified, in Unix time seconds.
          type: string
        SamplingRule:
          $ref: '#/components/schemas/SamplingRule'
    SamplingRuleUpdate:
      type: object
      additionalProperties: false
      properties:
        Attributes:
          x-$comment: String to string map
          description: Matches attributes derived from the request.
          type: object
          x-patternProperties:
            .{1,}:
              type: string
          additionalProperties: false
        FixedRate:
          description: The percentage of matching requests to instrument, after the reservoir is exhausted.
          type: number
          minimum: 0
          maximum: 1
        Host:
          description: Matches the hostname from a request URL.
          type: string
          maxLength: 64
        HTTPMethod:
          description: Matches the HTTP method from a request URL.
          type: string
          maxLength: 10
        Priority:
          description: The priority of the sampling rule.
          type: integer
          minimum: 1
          maximum: 9999
        ReservoirSize:
          description: A fixed number of matching requests to instrument per second, prior to applying the fixed rate. The reservoir is not used directly by services, but applies to all services using the rule collectively.
          type: integer
          minimum: 0
        ResourceARN:
          description: Matches the ARN of the AWS resource on which the service runs.
          type: string
          maxLength: 500
        RuleARN:
          $ref: '#/components/schemas/RuleARN'
        RuleName:
          $ref: '#/components/schemas/RuleName'
        ServiceName:
          description: Matches the name that the service uses to identify itself in segments.
          type: string
          maxLength: 64
        ServiceType:
          description: Matches the origin that the service uses to identify its type in segments.
          type: string
          maxLength: 64
        URLPath:
          description: Matches the path from a request URL.
          type: string
          maxLength: 128
    RuleName:
      description: The ARN of the sampling rule. Specify a rule by either name or ARN, but not both.
      type: string
      minLength: 1
      maxLength: 32
    RuleARN:
      description: The ARN of the sampling rule. Specify a rule by either name or ARN, but not both.
      type: string
  x-stackQL-resources:
    groups:
      name: groups
      id: awscc.xray.groups
      x-cfn-schema-name: Group
      x-type: list
      x-identifiers:
        - GroupARN
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.GroupARN') as group_arn
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::XRay::Group'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'GroupARN') as group_arn
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::XRay::Group'
                AND region = 'us-east-1'
    group:
      name: group
      id: awscc.xray.group
      x-cfn-schema-name: Group
      x-type: get
      x-identifiers:
        - GroupARN
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.FilterExpression') as filter_expression,
              JSON_EXTRACT(Properties, '$.GroupName') as group_name,
              JSON_EXTRACT(Properties, '$.GroupARN') as group_arn,
              JSON_EXTRACT(Properties, '$.InsightsConfiguration') as insights_configuration,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::XRay::Group'
              AND data__Identifier = '<GroupARN>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'FilterExpression') as filter_expression,
                json_extract_path_text(Properties, 'GroupName') as group_name,
                json_extract_path_text(Properties, 'GroupARN') as group_arn,
                json_extract_path_text(Properties, 'InsightsConfiguration') as insights_configuration,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::XRay::Group'
                AND data__Identifier = '<GroupARN>'
                AND region = 'us-east-1'
    resource_policies:
      name: resource_policies
      id: awscc.xray.resource_policies
      x-cfn-schema-name: ResourcePolicy
      x-type: list
      x-identifiers:
        - PolicyName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.PolicyName') as policy_name
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::XRay::ResourcePolicy'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'PolicyName') as policy_name
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::XRay::ResourcePolicy'
                AND region = 'us-east-1'
    resource_policy:
      name: resource_policy
      id: awscc.xray.resource_policy
      x-cfn-schema-name: ResourcePolicy
      x-type: get
      x-identifiers:
        - PolicyName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.PolicyName') as policy_name,
              JSON_EXTRACT(Properties, '$.PolicyDocument') as policy_document,
              JSON_EXTRACT(Properties, '$.BypassPolicyLockoutCheck') as bypass_policy_lockout_check
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::XRay::ResourcePolicy'
              AND data__Identifier = '<PolicyName>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'PolicyName') as policy_name,
                json_extract_path_text(Properties, 'PolicyDocument') as policy_document,
                json_extract_path_text(Properties, 'BypassPolicyLockoutCheck') as bypass_policy_lockout_check
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::XRay::ResourcePolicy'
                AND data__Identifier = '<PolicyName>'
                AND region = 'us-east-1'
    sampling_rules:
      name: sampling_rules
      id: awscc.xray.sampling_rules
      x-cfn-schema-name: SamplingRule
      x-type: list
      x-identifiers:
        - RuleARN
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.RuleARN') as rule_arn
              FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::XRay::SamplingRule'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'RuleARN') as rule_arn
                FROM awscc.cloud_control.resources WHERE data__TypeName = 'AWS::XRay::SamplingRule'
                AND region = 'us-east-1'
    sampling_rule:
      name: sampling_rule
      id: awscc.xray.sampling_rule
      x-cfn-schema-name: SamplingRule
      x-type: get
      x-identifiers:
        - RuleARN
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.SamplingRule') as sampling_rule,
              JSON_EXTRACT(Properties, '$.SamplingRuleRecord') as sampling_rule_record,
              JSON_EXTRACT(Properties, '$.SamplingRuleUpdate') as sampling_rule_update,
              JSON_EXTRACT(Properties, '$.RuleARN') as rule_arn,
              JSON_EXTRACT(Properties, '$.RuleName') as rule_name,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::XRay::SamplingRule'
              AND data__Identifier = '<RuleARN>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'SamplingRule') as sampling_rule,
                json_extract_path_text(Properties, 'SamplingRuleRecord') as sampling_rule_record,
                json_extract_path_text(Properties, 'SamplingRuleUpdate') as sampling_rule_update,
                json_extract_path_text(Properties, 'RuleARN') as rule_arn,
                json_extract_path_text(Properties, 'RuleName') as rule_name,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM awscc.cloud_control.resource WHERE data__TypeName = 'AWS::XRay::SamplingRule'
                AND data__Identifier = '<RuleARN>'
                AND region = 'us-east-1'
