openapi: 3.0.2
info:
  title: PagerDuty API - Session Configurations
  description: Account session configuration.
  version: 2.0.0
paths:
  /session_configurations:
    get:
      operationId: getSessionConfigurations
      x-pd-requires-scope: session_configurations.read
      summary: Get an account's session configurations
      description: |
        Retrieves session configurations for a PagerDuty account. Returns an array containing
        the requested configurations. If a specific type is requested, the array contains one item.
        If no type is specified, the array contains all available configurations (mobile and web).
        If no configurations exist, a 404 Not Found error will be returned.

        A Session Configuration needs to be created before it can be retrieved and used.

        Scoped OAuth requires: `session_configurations.read`
      tags:
        - Session Configurations
      parameters:
        - $ref: '#/components/parameters/optional_session_configuration_type'
      responses:
        '200':
          description: Session Configurations retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_configurations:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum:
                            - mobile
                            - web
                          description: The session configuration type (mobile or web)
                          example: web
                        absolute_session_ttl:
                          type: integer
                          description: Absolute session time to live in seconds
                          example: 3600
                          minimum: 600
                          maximum: 18144000
                        idle_session_ttl:
                          type: integer
                          description: Idle session time to live in seconds
                          example: 1800
                          minimum: 60
                          maximum: 86400
                      required:
                        - type
                        - absolute_session_ttl
                        - idle_session_ttl
                required:
                  - session_configurations
              examples:
                response:
                  summary: Session Configurations Example
                  value:
                    session_configurations:
                      - type: web
                        absolute_session_ttl: 3600
                        idle_session_ttl: 600
                      - type: mobile
                        absolute_session_ttl: 7200
                        idle_session_ttl: 1200
        '400':
          $ref: '#/components/responses/ArgumentError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
    put:
      summary: Configure an account's session configurations
      operationId: updateSessionConfigurations
      x-pd-requires-scope: session_configurations.write
      description: |
        Creates or updates session configurations for a PagerDuty Account. The configurations will take effect immediately for new sessions, while existing sessions for the specified `types` are immediately revoked.

        Scoped OAuth requires: `session_configurations.write`
      tags:
        - Session Configurations
      parameters:
        - $ref: '#/components/parameters/session_configuration_type'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_configuration:
                  type: object
                  properties:
                    absolute_session_ttl:
                      type: integer
                      description: Absolute session time to live in seconds
                      example: 3600
                      minimum: 600
                      maximum: 18144000
                    idle_session_ttl:
                      type: integer
                      description: Idle session time to live in seconds
                      example: 600
                      minimum: 60
                      maximum: 15552000
                  required:
                    - absolute_session_ttl
                    - idle_session_ttl
              required:
                - session_configuration
      responses:
        '200':
          description: Session Configurations updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_configurations:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum:
                            - mobile
                            - web
                          description: The session configuration type (mobile or web)
                          example: web
                        absolute_session_ttl:
                          type: integer
                          description: Absolute session time to live in seconds
                          example: 3600
                          minimum: 600
                          maximum: 18144000
                        idle_session_ttl:
                          type: integer
                          description: Idle session time to live in seconds
                          example: 1800
                          minimum: 60
                          maximum: 86400
                      required:
                        - type
                        - absolute_session_ttl
                        - idle_session_ttl
                required:
                  - session_configurations
              examples:
                response:
                  summary: Put Session Configurations Example
                  value:
                    session_configurations:
                      - type: web
                        absolute_session_ttl: 3600
                        idle_session_ttl: 600
                      - type: mobile
                        absolute_session_ttl: 7200
                        idle_session_ttl: 1200
        '400':
          $ref: '#/components/responses/ArgumentError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          $ref: '#/components/responses/TooManyRequests'
    delete:
      summary: Delete an account's session configurations.
      operationId: deleteSessionConfigurations
      x-pd-requires-scope: session_configurations.write
      description: |
        Deletes the session configurations for a PagerDuty account that was previously set.
        The type parameter is required and specifies which configurations to delete.
        A single type ('mobile' or 'web') or comma-separated list may be passed in.

        Scoped OAuth requires: `session_configurations.write`
      tags:
        - Session Configurations
      parameters:
        - $ref: '#/components/parameters/session_configuration_type'
      responses:
        '204':
          description: Session Configurations deleted successfully
        '400':
          $ref: '#/components/responses/ArgumentError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
components:
  responses:
    ArgumentError:
      description: Caller provided invalid arguments. Please review the response for error details. Retrying with the same arguments will *not* work.
      content:
        application/json:
          schema:
            description: Generic error response from the PagerDuty API
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: integer
                    readOnly: true
                  message:
                    type: string
                    readOnly: true
                    description: Error message string
                  errors:
                    type: array
                    readOnly: true
                    items:
                      type: string
                      readOnly: true
                      description: Human-readable error details
                example:
                  message: Not Found
                  code: 2100
    Unauthorized:
      description: |
        Caller did not supply credentials or did not provide the correct credentials.
        If you are using an API key, it may be invalid or your Authorization header may be malformed.
      content:
        application/json:
          schema:
            description: Generic error response from the PagerDuty API
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: integer
                    readOnly: true
                  message:
                    type: string
                    readOnly: true
                    description: Error message string
                  errors:
                    type: array
                    readOnly: true
                    items:
                      type: string
                      readOnly: true
                      description: Human-readable error details
                example:
                  message: Not Found
                  code: 2100
    Forbidden:
      description: |
        Caller is not authorized to view the requested resource.
        While your authentication is valid, the authenticated user or token does not have permission to perform this action.
      content:
        application/json:
          schema:
            description: Generic error response from the PagerDuty API
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: integer
                    readOnly: true
                  message:
                    type: string
                    readOnly: true
                    description: Error message string
                  errors:
                    type: array
                    readOnly: true
                    items:
                      type: string
                      readOnly: true
                      description: Human-readable error details
                example:
                  message: Not Found
                  code: 2100
    NotFound:
      description: The requested resource was not found.
      content:
        application/json:
          schema:
            description: Generic error response from the PagerDuty API
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: integer
                    readOnly: true
                  message:
                    type: string
                    readOnly: true
                    description: Error message string
                  errors:
                    type: array
                    readOnly: true
                    items:
                      type: string
                      readOnly: true
                      description: Human-readable error details
                example:
                  message: Not Found
                  code: 2100
    TooManyRequests:
      description: Too many requests have been made, the rate limit has been reached.
      content:
        application/json:
          schema:
            description: Generic error response from the PagerDuty API
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: integer
                    readOnly: true
                  message:
                    type: string
                    readOnly: true
                    description: Error message string
                  errors:
                    type: array
                    readOnly: true
                    items:
                      type: string
                      readOnly: true
                      description: Human-readable error details
                example:
                  message: Not Found
                  code: 2100
    Conflict:
      description: The request conflicts with the current state of the server.
      content:
        application/json:
          schema:
            description: Generic error response from the PagerDuty API
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: integer
                    readOnly: true
                  message:
                    type: string
                    readOnly: true
                    description: Error message string
                  errors:
                    type: array
                    readOnly: true
                    items:
                      type: string
                      readOnly: true
                      description: Human-readable error details
                example:
                  message: Not Found
                  code: 2100
  parameters:
    optional_session_configuration_type:
      name: type
      in: query
      required: false
      schema:
        type: string
        enum:
          - mobile
          - web
      description: Session configuration type. If omitted, returns both mobile and web configurations.
    session_configuration_type:
      name: type
      in: query
      required: true
      schema:
        type: string
        enum:
          - mobile
          - web
      description: Session configuration type. This can be either 'mobile' or 'web', or a comma-separated list of both.
  x-stackQL-resources:
    session_configurations:
      id: pagerduty.session_configurations.session_configurations
      name: session_configurations
      title: Session Configurations
      methods:
        list:
          operation:
            $ref: '#/paths/~1session_configurations/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.session_configurations
        update:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1session_configurations/put'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete:
          operation:
            $ref: '#/paths/~1session_configurations/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/session_configurations/methods/list'
        insert: []
        update:
          - $ref: '#/components/x-stackQL-resources/session_configurations/methods/update'
        delete:
          - $ref: '#/components/x-stackQL-resources/session_configurations/methods/delete'
        replace: []
servers:
  - url: https://api.pagerduty.com
    description: PagerDuty REST API v2 (US service region). The EU service region (https://api.eu.pagerduty.com) is documented in NOTES.md - a server variable cannot carry it without becoming a required parameter on every query.
