openapi: 3.0.1
info:
  title: Fivetran Connector Metadata API
  description: Connector types and their configuration metadata.
  version: v1
paths:
  /public/connector-types:
    get:
      tags:
        - Public Endpoints
      summary: Retrieve Source Metadata Public Endpoint
      description: Returns all available source types. This endpoint provides metadata including the proper source name (‘Facebook Ads’ instead of facebook_ads), the source icon, feature tables, information about the Hybrid deployment support, information about the Authorization via API support, and links to Fivetran resources. As we update source names and icons, that metadata will automatically update within this endpoint.
      operationId: metadata_public_connectors
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                required:
                  - code
                  - data
                properties:
                  code:
                    type: string
                    description: Response status code
                    example: Success
                  message:
                    type: string
                    description: Response status text
                    example: Connector metadata retrieved successfully
                  data:
                    type: array
                    description: The connector types
                    items:
                      $ref: '#/components/schemas/MetadataResponse'
                type: object
      security: []
  /v1/metadata/connector-types:
    get:
      tags:
        - Connector Metadata
      summary: Retrieve Source Metadata
      description: Returns all available source types within your Fivetran account. This endpoint makes it easier to display Fivetran connectors within your application because it provides metadata including the proper source name ('Facebook Ads' instead of 'facebook_ads'), the source icon, information about the Hybrid deployment support, and links to Fivetran resources. As we update source names and icons, that metadata will automatically update within this endpoint
      operationId: metadata_connectors
      parameters:
        - name: cursor
          in: query
          description: Paging cursor, [read more about pagination](https://fivetran.com/docs/rest-api/pagination)
          required: false
          schema:
            type: string
            example: cursor_value
          example: cursor_value
        - name: limit
          in: query
          description: Number of records to fetch per page. Accepts a number in the range 1..1000; the default value is 100.
          required: false
          schema:
            type: integer
            format: int32
            example: 100
          example: 100
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                required:
                  - code
                  - data
                properties:
                  code:
                    type: string
                    description: Response status code
                    example: Success
                  message:
                    type: string
                    description: Response status text
                    example: Connectors list retrieved successfully
                  data:
                    required:
                      - items
                    properties:
                      items:
                        type: array
                        description: The collection of returned items
                        items:
                          $ref: '#/components/schemas/MetadataResponseShort'
                      next_cursor:
                        type: string
                        description: The value of the cursor parameter for the next page
                        example: cursor_value
                    type: object
                type: object
  /v1/metadata/connector-types/{service}:
    get:
      tags:
        - Connector Metadata
      summary: Retrieve Connector Configuration Metadata
      description: Returns metadata of configuration parameters and authorization parameters for a specified connector type.
      operationId: metadata_connector_config
      parameters:
        - name: service
          in: path
          description: '[The connector type](https://fivetran.com/docs/rest-api/getting-started#commonterms) identifier within the Fivetran system'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                required:
                  - code
                  - data
                properties:
                  code:
                    type: string
                    description: Response status code
                    example: Success
                  message:
                    type: string
                    description: Response status text
                    example: Connector configuration retrieved successfully
                  data:
                    $ref: '#/components/schemas/MetadataResponse'
                type: object
components:
  schemas:
    MetadataResponse:
      required:
        - id
        - name
        - type
      type: object
      properties:
        id:
          type: string
          description: The connector type identifier within the Fivetran system
          example: google_ads
        name:
          type: string
          description: The connector service name within the Fivetran system
          example: Google Ads
        type:
          type: string
          description: The connector service type
          example: Marketing
          enum:
            - API
            - Dbt
            - Marketing
            - HumanResources
            - Finance
            - Productivity
            - Engineering
            - Support
            - Sales
            - Security
            - SuperConnectorTest
            - Free
            - File
            - Database
            - Events
            - Function
            - BITool
            - Warehouse
            - Log
            - Hvr
        description:
          type: string
          description: The description characterizing the purpose of the connector
          example: Google Ads is an online advertising platform
        icons:
          type: array
          description: The set of additional icon resource URLs in different formats (.svg, .png). Updating this list is not a breaking change. The set of icon URLs or the icons themselves may be changed
          items:
            type: string
        config:
          type: string
          description: Metadata for configuration fields (opaque JSON object)
        auth:
          type: string
          description: Metadata for authorization fields (optional) (opaque JSON object)
        icon_url:
          type: string
          description: The icon resource URL
          example: https://fivetran.com/integrations/google_ads/resources/google-ads.png
        link_to_docs:
          type: string
          description: The link to the connector documentation
          example: https://fivetran.com/docs/connectors/applications/google-ads
        connector_class:
          type: string
          enum:
            - standard
            - lite
        supported_features:
          type: array
          items:
            $ref: '#/components/schemas/Feature'
        link_to_erd:
          type: string
          description: The link to the connector ERD (entity–relationship diagram)
          example: https://docs.google.com/presentation/d/1f16zOPxwT1AXoOcNkvwT82ApKqU1yhtJ04f-73M91nw/embed
        service_status:
          type: string
          description: The current availability status of the connector
          example: general_availability
          enum:
            - general_availability
            - beta
            - private_preview
            - sunset
            - development
        service_status_updated_at:
          type: string
          description: The date (yyyy-MM-dd) the connector status was updated to the current availability status
          format: date-time
        external_secrets_keys_config:
          type: string
          description: (opaque JSON object)
    MetadataResponseShort:
      required:
        - id
        - name
        - type
      type: object
      properties:
        id:
          type: string
          description: The connector type identifier within the Fivetran system
          example: google_ads
        name:
          type: string
          description: The connector service name within the Fivetran system
          example: Google Ads
        type:
          type: string
          description: The connector service type
          example: Marketing
          enum:
            - API
            - Dbt
            - Marketing
            - HumanResources
            - Finance
            - Productivity
            - Engineering
            - Support
            - Sales
            - Security
            - SuperConnectorTest
            - Free
            - File
            - Database
            - Events
            - Function
            - BITool
            - Warehouse
            - Log
            - Hvr
        description:
          type: string
          description: The description characterizing the purpose of the connector
          example: Google Ads is an online advertising platform
        icons:
          type: array
          description: The set of additional icon resource URLs in different formats (.svg, .png). Updating this list is not a breaking change. The set of icon URLs or the icons themselves may be changed
          items:
            type: string
        icon_url:
          type: string
          description: The icon resource URL
          example: https://fivetran.com/integrations/google_ads/resources/google-ads.png
        link_to_docs:
          type: string
          description: The link to the connector documentation
          example: https://fivetran.com/docs/connectors/applications/google-ads
        connector_class:
          type: string
          enum:
            - standard
            - lite
        supported_features:
          type: array
          items:
            $ref: '#/components/schemas/Feature'
        link_to_erd:
          type: string
          description: The link to the connector ERD (entity–relationship diagram)
          example: https://docs.google.com/presentation/d/1f16zOPxwT1AXoOcNkvwT82ApKqU1yhtJ04f-73M91nw/embed
        service_status:
          type: string
          description: The current availability status of the connector
          example: general_availability
          enum:
            - general_availability
            - beta
            - private_preview
            - sunset
            - development
        service_status_updated_at:
          type: string
          description: The date (yyyy-MM-dd) the connector status was updated to the current availability status
          format: date-time
    Feature:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of a feature supported by the connector
          example: API_CONFIGURABLE
          enum:
            - CUSTOM_DATA
            - CAPTURE_DELETES
            - DATA_BLOCKING
            - COLUMN_HASHING
            - RE_SYNC
            - HISTORY
            - API_CONFIGURABLE
            - PRIORITY_FIRST_SYNC
            - FIVETRAN_DATA_MODELS
            - PRIVATE_NETWORKING
            - AUTHORIZATION_VIA_API
            - ROW_FILTERING
        notes:
          type: string
          description: Additional information about the feature support of a specific connector
          example: ...
  x-stackQL-resources:
    public_connector_types:
      id: fivetran.metadata.public_connector_types
      name: public_connector_types
      title: Public Connector Types
      methods:
        list:
          operation:
            $ref: '#/paths/~1public~1connector-types/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.data
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/public_connector_types/methods/list'
        insert: []
        update: []
        delete: []
        replace: []
    connector_types:
      id: fivetran.metadata.connector_types
      name: connector_types
      title: Connector Types
      methods:
        list:
          operation:
            $ref: '#/paths/~1v1~1metadata~1connector-types/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.data.items
        get:
          operation:
            $ref: '#/paths/~1v1~1metadata~1connector-types~1{service}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.data
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/connector_types/methods/get'
          - $ref: '#/components/x-stackQL-resources/connector_types/methods/list'
        insert: []
        update: []
        delete: []
        replace: []
servers:
  - url: https://api.fivetran.com
x-stackQL-config:
  pagination:
    requestToken:
      key: cursor
      location: query
    responseToken:
      key: $.data.next_cursor
      location: body
