openapi: 3.0.1
servers:
  - url: 'https://api.fivetran.com'
    variables: {}
info:
  title: OpenAPI Definition - webhooks
  description: Webhook Management
  version: v1
security:
  - basicAuth: []
components:
  schemas:
    WebhookRequest:
      type: object
      properties:
        url:
          type: string
          description: Your webhooks URL endpoint for your application
        events:
          type: array
          description: The array of event types
          items:
            type: string
        active:
          type: boolean
          description: 'Boolean, if set to true, webhooks are immediately sent in response to events'
        secret:
          type: string
          description: The secret string used for payload signing. Optional.
    WebhookResponse:
      type: object
      properties:
        id:
          type: string
          description: The webhook ID
        type:
          type: string
          description: The webhook type
          enum:
            - group
            - account
        url:
          type: string
          description: Your webhooks URL endpoint for your application
        events:
          type: array
          description: The array of event types
          items:
            type: string
        active:
          type: boolean
          description: 'Boolean, if set to true, webhooks are immediately sent in response to events'
        secret:
          type: string
          description: The secret string used for payload signing. Optional.
        created_at:
          type: string
          description: The webhook creation timestamp
          format: date-time
        created_by:
          type: string
          description: The ID of the user who created the webhook
        group_id:
          type: string
          description: The group ID
    WebhookTestRequest:
      type: object
      properties:
        event:
          type: string
          description: Events
    WebhookTestResponse:
      type: object
      properties:
        succeed:
          type: boolean
          description: Test result
        status:
          type: integer
          description: Test status
          format: int32
        message:
          type: string
          description: Test message
  responses: {}
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  x-stackQL-resources:
    group:
      id: fivetran.webhooks.group
      name: group
      title: Group
      methods:
        create_group_webhook:
          operation:
            $ref: '#/paths/~1v1~1webhooks~1group~1{groupId}/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert:
          - $ref: '#/components/x-stackQL-resources/group/methods/create_group_webhook'
        update: []
        delete: []
    account:
      id: fivetran.webhooks.account
      name: account
      title: Account
      methods:
        create_account_webhook:
          operation:
            $ref: '#/paths/~1v1~1webhooks~1account/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select: []
        insert:
          - $ref: '#/components/x-stackQL-resources/account/methods/create_account_webhook'
        update: []
        delete: []
    webhooks:
      id: fivetran.webhooks.webhooks
      name: webhooks
      title: Webhooks
      methods:
        webhook_details:
          operation:
            $ref: '#/paths/~1v1~1webhooks~1{webhookId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.data
        _webhook_details:
          operation:
            $ref: '#/paths/~1v1~1webhooks~1{webhookId}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        delete_webhook:
          operation:
            $ref: '#/paths/~1v1~1webhooks~1{webhookId}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '204'
        modify_webhook:
          operation:
            $ref: '#/paths/~1v1~1webhooks~1{webhookId}/patch'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        list_all_webhooks:
          operation:
            $ref: '#/paths/~1v1~1webhooks/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.data.items
        _list_all_webhooks:
          operation:
            $ref: '#/paths/~1v1~1webhooks/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        test_webhook:
          operation:
            $ref: '#/paths/~1v1~1webhooks~1{webhookId}~1test/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/webhooks/methods/webhook_details'
          - $ref: '#/components/x-stackQL-resources/webhooks/methods/list_all_webhooks'
        insert: []
        update: []
        delete:
          - $ref: '#/components/x-stackQL-resources/webhooks/methods/delete_webhook'
paths:
  '/v1/webhooks/group/{groupId}':
    post:
      tags:
        - Webhook Management
      summary: Create group webhook
      description: This endpoint allows you to create a new webhook for a given group
      operationId: create_group_webhook
      parameters:
        - name: groupId
          in: path
          description: The group ID
          required: true
          schema:
            type: string
        - name: Accept
          in: header
          schema:
            type: string
            example: application/json
            default: application/json
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: string
                    description: Response status code
                  message:
                    type: string
                    description: Response status text
                  data:
                    $ref: '#/components/schemas/WebhookResponse'
                type: object
  /v1/webhooks/account:
    post:
      tags:
        - Webhook Management
      summary: Create account webhook
      description: This endpoint allows you to create a new webhook for the current account.
      operationId: create_account_webhook
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
            example: application/json
            default: application/json
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: string
                    description: Response status code
                  message:
                    type: string
                    description: Response status text
                  data:
                    $ref: '#/components/schemas/WebhookResponse'
                type: object
  '/v1/webhooks/{webhookId}':
    get:
      tags:
        - Webhook Management
      summary: Retrieve webhook details
      description: This endpoint allows you to retrieve details of the existing webhook for a given identifier
      operationId: webhook_details
      parameters:
        - name: webhookId
          in: path
          description: The webhook ID
          required: true
          schema:
            type: string
        - name: Accept
          in: header
          schema:
            type: string
            example: application/json
            default: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: string
                    description: Response status code
                  message:
                    type: string
                    description: Response status text
                  data:
                    $ref: '#/components/schemas/WebhookResponse'
                type: object
    delete:
      tags:
        - Webhook Management
      summary: Delete webhook
      description: This endpoint allows you to delete an existing webhook with a given identifier
      operationId: delete_webhook
      parameters:
        - name: webhookId
          in: path
          description: The webhook ID
          required: true
          schema:
            type: string
        - name: Accept
          in: header
          schema:
            type: string
            example: application/json
            default: application/json
      responses:
        '204':
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: string
                    description: Response status code
                  message:
                    type: string
                    description: Response status text
                type: object
    patch:
      tags:
        - Webhook Management
      summary: Update webhook
      description: The endpoint allows you to update the existing webhook with a given identifier
      operationId: modify_webhook
      parameters:
        - name: webhookId
          in: path
          description: The webhook ID
          required: true
          schema:
            type: string
        - name: Accept
          in: header
          schema:
            type: string
            example: application/json
            default: application/json
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: string
                    description: Response status code
                  message:
                    type: string
                    description: Response status text
                  data:
                    $ref: '#/components/schemas/WebhookResponse'
                type: object
  /v1/webhooks:
    get:
      tags:
        - Webhook Management
      summary: Retrieve the list of webhooks
      description: The endpoint allows you to retrieve the list of existing webhooks available for the current account
      operationId: list_all_webhooks
      parameters:
        - name: cursor
          in: query
          description: 'Paging cursor, [read more about pagination](https://fivetran.com/docs/rest-api/pagination)'
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Number of records to fetch per page. Accepts a number in the range 1..1000; the default value is 100.
          required: false
          schema:
            type: integer
            format: int32
        - name: Accept
          in: header
          schema:
            type: string
            example: application/json
            default: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: string
                    description: Response status code
                  message:
                    type: string
                    description: Response status text
                  data:
                    properties:
                      items:
                        type: array
                        description: The collection of return items
                        items:
                          $ref: '#/components/schemas/WebhookResponse'
                      nextCursor:
                        type: string
                        description: The value of the cursor parameter for the next page
                    type: object
                type: object
  '/v1/webhooks/{webhookId}/test':
    post:
      tags:
        - Webhook Management
      summary: Test webhook
      description: The endpoint allows you to test an existing webhook. It sends a webhook with a given identifier for a dummy connector with identifier _connector_1
      operationId: test_webhook
      parameters:
        - name: webhookId
          in: path
          description: The webhook ID
          required: true
          schema:
            type: string
        - name: Accept
          in: header
          schema:
            type: string
            example: application/json
            default: application/json
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookTestRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: string
                    description: Response status code
                  message:
                    type: string
                    description: Response status text
                  data:
                    $ref: '#/components/schemas/WebhookTestResponse'
                type: object
