openapi: 3.0.1
info:
  title: Fivetran Webhooks API
  description: Account and group webhooks.
  version: v1
paths:
  /v1/webhooks:
    get:
      tags:
        - Webhook Management
      summary: List all Webhooks
      description: The endpoint allows you to retrieve the list of existing webhooks available for the current account
      operationId: list_all_webhooks
      parameters:
        - name: cursor
          in: query
          description: Paging cursor, [read more about pagination](https://fivetran.com/docs/rest-api/pagination)
          required: false
          schema:
            type: string
            example: cursor_value
          example: cursor_value
        - name: limit
          in: query
          description: Number of records to fetch per page. Accepts a number in the range 1..1000; the default value is 100.
          required: false
          schema:
            type: integer
            format: int32
            example: 100
          example: 100
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                required:
                  - code
                  - data
                properties:
                  code:
                    type: string
                    description: Response status code
                    example: Success
                  message:
                    type: string
                    description: Response status text
                    example: Webhooks retrieved successfully
                  data:
                    required:
                      - items
                    properties:
                      items:
                        type: array
                        description: The collection of returned items
                        items:
                          $ref: '#/components/schemas/WebhookResponse'
                      next_cursor:
                        type: string
                        description: The value of the cursor parameter for the next page
                        example: cursor_value
                    type: object
                type: object
  /v1/webhooks/account:
    post:
      tags:
        - Webhook Management
      summary: Create an Account Webhook
      description: This endpoint allows you to create a new webhook for the current account.
      operationId: create_account_webhook
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                required:
                  - code
                  - data
                properties:
                  code:
                    type: string
                    description: Response status code
                    example: Success
                  message:
                    type: string
                    description: Response status text
                    example: Account webhook has been created
                  data:
                    $ref: '#/components/schemas/WebhookResponse'
                type: object
  /v1/webhooks/group/{group_id}:
    post:
      tags:
        - Webhook Management
      summary: Create a Group Webhook
      description: This endpoint allows you to create a new webhook for a given group
      operationId: create_group_webhook
      parameters:
        - name: group_id
          in: path
          description: The unique identifier for the group within the Fivetran system.
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequest_create_group_webhook'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                required:
                  - code
                  - data
                properties:
                  code:
                    type: string
                    description: Response status code
                    example: Success
                  message:
                    type: string
                    description: Response status text
                    example: Group webhook has been created
                  data:
                    $ref: '#/components/schemas/WebhookResponse'
                type: object
        '404':
          description: Group not found
  /v1/webhooks/{webhook_id}:
    get:
      tags:
        - Webhook Management
      summary: Retrieve Webhook Details
      description: This endpoint allows you to retrieve details of the existing webhook for a given identifier
      operationId: webhook_details
      parameters:
        - name: webhook_id
          in: path
          description: The webhook ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                required:
                  - code
                  - data
                properties:
                  code:
                    type: string
                    description: Response status code
                    example: Success
                  message:
                    type: string
                    description: Response status text
                    example: Webhook details retrieved successfully
                  data:
                    $ref: '#/components/schemas/WebhookResponse'
                type: object
        '404':
          description: Webhook not found
    delete:
      tags:
        - Webhook Management
      summary: Delete a Webhook
      description: This endpoint allows you to delete an existing webhook with a given identifier
      operationId: delete_webhook
      parameters:
        - name: webhook_id
          in: path
          description: The webhook ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                required:
                  - code
                  - message
                properties:
                  code:
                    type: string
                    description: Response status code
                    example: Success
                  message:
                    type: string
                    description: Response status text
                    example: Webhook with id 'string' has been deleted
                type: object
        '404':
          description: Webhook not found
    patch:
      tags:
        - Webhook Management
      summary: Update a Webhook
      description: The endpoint allows you to update the existing webhook with a given identifier
      operationId: modify_webhook
      parameters:
        - name: webhook_id
          in: path
          description: The webhook ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequest_modify_webhook'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                required:
                  - code
                  - data
                properties:
                  code:
                    type: string
                    description: Response status code
                    example: Success
                  message:
                    type: string
                    description: Response status text
                    example: Webhook has been updated
                  data:
                    $ref: '#/components/schemas/WebhookResponse'
                type: object
        '404':
          description: Webhook not found
  /v1/webhooks/{webhook_id}/test:
    post:
      tags:
        - Webhook Management
      summary: Test a Webhook
      description: The endpoint allows you to test an existing webhook. It sends a webhook with a given identifier for a dummy connection with identifier _connection_1
      operationId: test_webhook
      parameters:
        - name: webhook_id
          in: path
          description: The webhook ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookTestRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                required:
                  - code
                  - data
                properties:
                  code:
                    type: string
                    description: Response status code
                    example: Success
                  message:
                    type: string
                    description: Response status text
                    example: Webhook test completed successfully
                  data:
                    $ref: '#/components/schemas/WebhookTestResponse'
                type: object
        '404':
          description: Webhook not found
components:
  schemas:
    WebhookResponse:
      required:
        - active
        - created_at
        - created_by
        - events
        - id
        - type
        - url
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the webhook.
          example: webhook_id
        type:
          type: string
          description: The type of the webhook. Specifies whether the webhook is associated with a group or an account.
          example: group
          enum:
            - group
            - account
        url:
          type: string
          description: The endpoint URL where webhook events will be delivered.
          example: https://your-host.your-domain/webhook
        events:
          type: array
          description: List of event types that trigger the webhook.
          example:
            - sync_start
            - sync_end
          items:
            type: string
        active:
          type: boolean
          description: Indicates if the webhook is enabled to send events immediately upon occurrence.
          example: true
        secret:
          type: string
          description: A secret string used to sign webhook payloads for verification.
          example: '******'
        group_id:
          type: string
          description: Unique identifier for the group associated with the webhook.
          example: group_id
        created_at:
          type: string
          description: Timestamp indicating when the webhook was created.
          format: date-time
          example: '2024-01-01T00:00:00Z'
        created_by:
          type: string
          description: Identifier of the user who created the webhook setting.
          example: user_id
    WebhookRequest:
      required:
        - events
        - url
      type: object
      properties:
        url:
          type: string
          description: The endpoint URL where webhook events will be delivered.
          example: https://your-host.your-domain/webhook
        events:
          type: array
          description: List of event types that trigger the webhook.
          example:
            - sync_start
            - sync_end
          items:
            type: string
        active:
          type: boolean
          description: Indicates if the webhook is enabled to send events immediately upon occurrence.
          example: true
        secret:
          type: string
          description: A secret string used to sign webhook payloads for verification.
          example: your_webhook_secret
    WebhookRequest_create_group_webhook:
      required:
        - events
        - url
      type: object
      properties:
        url:
          type: string
          description: The endpoint URL where webhook events will be delivered.
          example: https://your-host.your-domain/webhook
        events:
          type: array
          description: List of event types that trigger the webhook.
          example:
            - sync_start
            - sync_end
          items:
            type: string
        active:
          type: boolean
          description: Indicates if the webhook is enabled to send events immediately upon occurrence.
          example: true
        secret:
          type: string
          description: A secret string used to sign webhook payloads for verification.
          example: your_webhook_secret
    WebhookRequest_modify_webhook:
      type: object
      properties:
        url:
          type: string
          description: The endpoint URL where webhook events will be delivered.
          example: https://your-host.your-domain/webhook
        events:
          type: array
          description: List of event types that trigger the webhook.
          example:
            - sync_start
            - sync_end
          items:
            type: string
        active:
          type: boolean
          description: Indicates if the webhook is enabled to send events immediately upon occurrence.
          example: true
        secret:
          type: string
          description: A secret string used to sign webhook payloads for verification.
          example: your_webhook_secret
    WebhookTestRequest:
      required:
        - event
      type: object
      properties:
        event:
          type: string
          description: Type of event to be sent during webhook testing.
          example: sync_end
    WebhookTestResponse:
      required:
        - status
        - succeed
      type: object
      properties:
        succeed:
          type: boolean
          description: Indicates whether the webhook test was successful.
          example: true
        status:
          type: integer
          description: HTTP status code returned by the webhook test.
          format: int32
          example: 200
        message:
          type: string
          description: Additional information or result message from the webhook test.
          example: Success
  x-stackQL-resources:
    webhooks:
      id: fivetran.webhooks.webhooks
      name: webhooks
      title: Webhooks
      methods:
        list:
          operation:
            $ref: '#/paths/~1v1~1webhooks/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.data.items
        create_account_webhook:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1v1~1webhooks~1account/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.data
        create_group_webhook:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1v1~1webhooks~1group~1{group_id}/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.data
        get:
          operation:
            $ref: '#/paths/~1v1~1webhooks~1{webhook_id}/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.data
        delete:
          operation:
            $ref: '#/paths/~1v1~1webhooks~1{webhook_id}/delete'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        update:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1v1~1webhooks~1{webhook_id}/patch'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.data
        test:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: '#/paths/~1v1~1webhooks~1{webhook_id}~1test/post'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.data
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/webhooks/methods/get'
          - $ref: '#/components/x-stackQL-resources/webhooks/methods/list'
        insert:
          - $ref: '#/components/x-stackQL-resources/webhooks/methods/create_group_webhook'
          - $ref: '#/components/x-stackQL-resources/webhooks/methods/create_account_webhook'
        update:
          - $ref: '#/components/x-stackQL-resources/webhooks/methods/update'
        delete:
          - $ref: '#/components/x-stackQL-resources/webhooks/methods/delete'
        replace: []
servers:
  - url: https://api.fivetran.com
x-stackQL-config:
  pagination:
    requestToken:
      key: cursor
      location: query
    responseToken:
      key: $.data.next_cursor
      location: body
