openapi: 3.0.0
info:
  title: AccessAnalyzer
  version: 1.0.0
paths: {}
components:
  schemas:
    ArchiveRule:
      description: An Access Analyzer archive rule. Archive rules automatically archive new findings that meet the criteria you define when you create the rule.
      type: object
      properties:
        Filter:
          type: array
          x-insertionOrder: false
          minItems: 1
          items:
            $ref: '#/components/schemas/Filter'
        RuleName:
          type: string
          description: The archive rule name
      required:
        - Filter
        - RuleName
      additionalProperties: false
    Filter:
      type: object
      properties:
        Contains:
          type: array
          x-insertionOrder: false
          items:
            type: string
        Eq:
          type: array
          x-insertionOrder: false
          items:
            type: string
        Exists:
          type: boolean
        Property:
          type: string
        Neq:
          type: array
          x-insertionOrder: false
          items:
            type: string
      required:
        - Property
      additionalProperties: false
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      properties:
        Key:
          type: string
          description: 'The key name of the tag. You can specify a value that is 1 to 127 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          minLength: 1
          maxLength: 127
        Value:
          type: string
          description: 'The value for the tag. You can specify a value that is 1 to 255 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          minLength: 1
          maxLength: 255
      required:
        - Key
        - Value
      additionalProperties: false
    Analyzer:
      type: object
      properties:
        AnalyzerName:
          description: Analyzer name
          type: string
          minLength: 1
          maxLength: 1024
        ArchiveRules:
          type: array
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/ArchiveRule'
        Arn:
          description: Amazon Resource Name (ARN) of the analyzer
          type: string
          minLength: 1
          maxLength: 1600
        Tags:
          type: array
          maxItems: 50
          x-insertionOrder: false
          uniqueItems: true
          description: An array of key-value pairs to apply to this resource.
          items:
            $ref: '#/components/schemas/Tag'
        Type:
          description: The type of the analyzer, must be ACCOUNT or ORGANIZATION
          type: string
          minLength: 0
          maxLength: 1024
      required:
        - Type
      x-stackql-resource-name: analyzer
      x-stackql-primaryIdentifier:
        - Arn
  x-stackQL-resources:
    analyzers:
      name: analyzers
      id: aws.accessanalyzer.analyzers
      x-cfn-schema-name: Analyzer
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::AccessAnalyzer::Analyzer'
    analyzer:
      name: analyzer
      id: aws.accessanalyzer.analyzer
      x-cfn-schema-name: Analyzer
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.AnalyzerName') as analyzer_name,
              JSON_EXTRACT(Properties, '$.ArchiveRules') as archive_rules,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.Type') as type
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::AccessAnalyzer::Analyzer'
