openapi: 3.0.0
info:
  version: "2018-11-29"
  title: AmazonApiGatewayManagementApi
  description: AmazonApiGatewayManagementApi
  x-serviceName: execute-api
  x-serviceAlias: apigatewaymanagementapi
  x-protocol: rest-json
  x-apiVersion: "2018-11-29"
  x-endpointPrefix: execute-api
  x-jsonVersion: "1.1"
servers:
  - url: https://execute-api.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for apigatewaymanagementapi
paths:
  /@connections/{connection_id}:
    delete:
      operationId: DeleteConnection
      description: Delete the connection with the provided id.
      parameters:
        - name: connection_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/__string"
      responses:
        "204":
          description: Success
    get:
      operationId: GetConnection
      description: Get information about the connection with the provided id.
      parameters:
        - name: connection_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/__string"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetConnectionResponse"
    post:
      operationId: PostToConnection
      description: Sends the provided data to the specified connection.
      parameters:
        - name: connection_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/__string"
          description: The identifier of the connection that a specific client is using.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Data:
                  $ref: "#/components/schemas/Data"
              required:
                - Data
      responses:
        "200":
          description: Success
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    __string:
      type: string
    GetConnectionResponse:
      type: object
      properties:
        ConnectedAt:
          $ref: "#/components/schemas/__timestampIso8601"
          description: The time in ISO 8601 format for when the connection was established.
        Identity:
          $ref: "#/components/schemas/Identity"
        LastActiveAt:
          $ref: "#/components/schemas/__timestampIso8601"
          description: The time in ISO 8601 format for when the connection was last active.
    __timestampIso8601:
      type: string
      format: date-time
    Identity:
      type: object
      properties:
        SourceIp:
          $ref: "#/components/schemas/__string"
          description: The source IP address of the TCP connection making the request to API Gateway.
        UserAgent:
          $ref: "#/components/schemas/__string"
          description: The User Agent of the API caller.
      required:
        - SourceIp
        - UserAgent
    Data:
      description: The data to be sent to the client specified by its connection id.
      type: string
      format: byte
      maxLength: 131072
  x-stackQL-resources:
    connections:
      id: aws.apigatewaymanagementapi.connections
      name: connections
      title: connections
      methods:
        delete_connection:
          operation:
            $ref: "#/paths/~1@connections~1{connection_id}/delete"
          response:
            openAPIDocKey: "204"
        get_connection:
          operation:
            $ref: "#/paths/~1@connections~1{connection_id}/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        post_to_connection:
          operation:
            $ref: "#/paths/~1@connections~1{connection_id}/post"
          response:
            openAPIDocKey: "200"
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/connections/methods/get_connection"
        insert: []
        update: []
        delete:
          - $ref: "#/components/x-stackQL-resources/connections/methods/delete_connection"
