openapi: 3.0.0
info:
  version: "2021-11-11"
  title: AWS AppConfig Data
  description: AWS AppConfig Data
  x-serviceName: appconfig
  x-serviceAlias: appconfigdata
  x-protocol: rest-json
  x-apiVersion: "2021-11-11"
  x-endpointPrefix: appconfigdata
  x-jsonVersion: "1.0"
servers:
  - url: https://appconfigdata.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for appconfigdata
paths:
  /configuration:
    get:
      operationId: GetLatestConfiguration
      description: Retrieves the latest deployed configuration. This API may return empty configuration data if the client already has the latest version. For more information about this API action and to view example CLI commands that show how to use it with the StartConfigurationSession API action, see Retrieving the configuration in the AppConfig User Guide. Note the following important information. Each configuration token is only valid for one call to GetLatestConfiguration. The GetLatestConfiguration response includes a NextPollConfigurationToken that should always replace the token used for the just-completed call in preparation for the next one. GetLatestConfiguration is a priced call. For more information, see Pricing.
      parameters:
        - name: configuration_token
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/Token"
          description: Token describing the current state of the configuration session. To obtain a token, first call the StartConfigurationSession API. Note that every call to GetLatestConfiguration will return a new ConfigurationToken (NextPollConfigurationToken in the response) and must be provided to subsequent GetLatestConfiguration API calls. This token should only be used once. To support long poll use cases, the token is valid for up to 24 hours. If a GetLatestConfiguration call uses an expired token, the system returns BadRequestException.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetLatestConfigurationResponse"
  /configurationsessions:
    post:
      operationId: StartConfigurationSession
      description: Starts a configuration session used to retrieve a deployed configuration. For more information about this API action and to view example CLI commands that show how to use it with the GetLatestConfiguration API action, see Retrieving the configuration in the AppConfig User Guide.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ApplicationIdentifier:
                  $ref: "#/components/schemas/Identifier"
                EnvironmentIdentifier:
                  $ref: "#/components/schemas/Identifier"
                ConfigurationProfileIdentifier:
                  $ref: "#/components/schemas/Identifier"
                RequiredMinimumPollIntervalInSeconds:
                  $ref: "#/components/schemas/OptionalPollSeconds"
              required:
                - ApplicationIdentifier
                - EnvironmentIdentifier
                - ConfigurationProfileIdentifier
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StartConfigurationSessionResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    Token:
      type: string
      pattern: \S{1,8192}
    GetLatestConfigurationResponse:
      type: object
      properties:
        NextPollConfigurationToken:
          $ref: "#/components/schemas/Token"
          description: The latest token describing the current state of the configuration session. This must be provided to the next call to GetLatestConfiguration. This token should only be used once. To support long poll use cases, the token is valid for up to 24 hours. If a GetLatestConfiguration call uses an expired token, the system returns BadRequestException.
        NextPollIntervalInSeconds:
          $ref: "#/components/schemas/Integer"
          description: The amount of time the client should wait before polling for configuration updates again. Use RequiredMinimumPollIntervalInSeconds to set the desired poll interval.
        ContentType:
          $ref: "#/components/schemas/String"
          description: A standard MIME type describing the format of the configuration content.
        Configuration:
          $ref: "#/components/schemas/SensitiveBlob"
          description: The data of the configuration. This may be empty if the client already has the latest version of configuration.
        VersionLabel:
          $ref: "#/components/schemas/String"
          description: The user-defined label for the AppConfig hosted configuration version. This attribute doesn't apply if the configuration is not from an AppConfig hosted configuration version. If the client already has the latest version of the configuration data, this value is empty.
    Integer:
      type: integer
    String:
      type: string
    SensitiveBlob:
      type: string
      format: byte
    Identifier:
      type: string
      minLength: 1
      maxLength: 128
    OptionalPollSeconds:
      type: integer
      minimum: 15
      maximum: 86400
    StartConfigurationSessionResponse:
      type: object
      properties:
        InitialConfigurationToken:
          $ref: "#/components/schemas/Token"
          description: Token encapsulating state about the configuration session. Provide this token to the GetLatestConfiguration API to retrieve configuration data. This token should only be used once in your first call to GetLatestConfiguration. You must use the new token in the GetLatestConfiguration response (NextPollConfigurationToken) in each subsequent call to GetLatestConfiguration. The InitialConfigurationToken and NextPollConfigurationToken should only be used once. To support long poll use cases, the tokens are valid for up to 24 hours. If a GetLatestConfiguration call uses an expired token, the system returns BadRequestException.
  x-stackQL-resources:
    latest_configurations:
      id: aws.appconfigdata.latest_configurations
      name: latest_configurations
      title: latest_configurations
      methods:
        get_latest_configuration:
          operation:
            $ref: "#/paths/~1configuration/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/latest_configurations/methods/get_latest_configuration"
        insert: []
        update: []
        delete: []
