openapi: 3.0.0
info:
  title: AuditManager
  version: 1.0.0
paths: {}
components:
  schemas:
    FrameworkId:
      description: The identifier for the specified framework.
      type: string
      maxLength: 36
      minLength: 32
      pattern: ^([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}|.*\S.*)$
    UUID:
      type: string
      maxLength: 36
      minLength: 36
      pattern: ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$
    AccountId:
      description: The identifier for the specified AWS account.
      type: string
      maxLength: 12
      minLength: 12
      pattern: ^[0-9]{12}$
    EmailAddress:
      description: The unique identifier for the email account.
      type: string
      maxLength: 320
      minLength: 1
      pattern: ^.*@.*$
    AccountName:
      description: The name of the specified AWS account.
      type: string
      maxLength: 50
      minLength: 1
      pattern: ^[\u0020-\u007E]+$
    AWSAccount:
      description: The AWS account associated with the assessment.
      type: object
      additionalProperties: false
      properties:
        Id:
          $ref: '#/components/schemas/AccountId'
        EmailAddress:
          $ref: '#/components/schemas/EmailAddress'
        Name:
          $ref: '#/components/schemas/AccountName'
    AssessmentArn:
      description: The Amazon Resource Name (ARN) of the assessment.
      type: string
      maxLength: 2048
      minLength: 20
      pattern: ^arn:.*:auditmanager:.*
    Timestamp:
      description: The sequence of characters that identifies when the event occurred.
      type: number
    ControlSetId:
      description: The identifier for the specified control set.
      type: string
      maxLength: 300
      minLength: 1
      pattern: ^[\w\W\s\S]*$
    CreatedBy:
      description: The IAM user or role that performed the action.
      type: string
      maxLength: 2048
      minLength: 20
      pattern: ^arn:.*:*:.*
    IamArn:
      description: The Amazon Resource Name (ARN) of the IAM user or role.
      type: string
      maxLength: 2048
      minLength: 20
      pattern: ^arn:.*:iam:.*
    AssessmentName:
      description: The name of the related assessment.
      type: string
      maxLength: 127
      minLength: 1
      pattern: ^[a-zA-Z0-9-_\.]+$
    DelegationComment:
      description: The comment related to the delegation.
      type: string
      maxLength: 350
      pattern: ^[\w\W\s\S]*$
    RoleType:
      description: ' The IAM role type.'
      type: string
      enum:
        - PROCESS_OWNER
        - RESOURCE_OWNER
    DelegationStatus:
      description: The status of the delegation.
      type: string
      enum:
        - IN_PROGRESS
        - UNDER_REVIEW
        - COMPLETE
    Delegation:
      description: The assignment of a control set to a delegate for review.
      type: object
      additionalProperties: false
      properties:
        LastUpdated:
          $ref: '#/components/schemas/Timestamp'
        ControlSetId:
          $ref: '#/components/schemas/ControlSetId'
        CreationTime:
          $ref: '#/components/schemas/Timestamp'
        CreatedBy:
          $ref: '#/components/schemas/CreatedBy'
        RoleArn:
          $ref: '#/components/schemas/IamArn'
        AssessmentName:
          $ref: '#/components/schemas/AssessmentName'
        Comment:
          $ref: '#/components/schemas/DelegationComment'
        Id:
          $ref: '#/components/schemas/UUID'
        RoleType:
          $ref: '#/components/schemas/RoleType'
        AssessmentId:
          $ref: '#/components/schemas/UUID'
        Status:
          $ref: '#/components/schemas/DelegationStatus'
    Role:
      description: The wrapper that contains AWS Audit Manager role information, such as the role type and IAM ARN.
      type: object
      additionalProperties: false
      properties:
        RoleArn:
          $ref: '#/components/schemas/IamArn'
        RoleType:
          $ref: '#/components/schemas/RoleType'
    AWSServiceName:
      description: The name of the AWS service.
      type: string
    AWSService:
      description: An AWS service such as Amazon S3, AWS CloudTrail, and so on.
      type: object
      additionalProperties: false
      properties:
        ServiceName:
          $ref: '#/components/schemas/AWSServiceName'
    Scope:
      description: The wrapper that contains the AWS accounts and AWS services in scope for the assessment.
      type: object
      additionalProperties: false
      properties:
        AwsAccounts:
          description: The AWS accounts included in scope.
          type: array
          items:
            $ref: '#/components/schemas/AWSAccount'
        AwsServices:
          description: The AWS services included in scope.
          type: array
          items:
            $ref: '#/components/schemas/AWSService'
    S3Url:
      description: The URL of the specified Amazon S3 bucket.
      type: string
    AssessmentReportDestinationType:
      description: The destination type, such as Amazon S3.
      type: string
      enum:
        - S3
    AssessmentReportsDestination:
      description: The destination in which evidence reports are stored for the specified assessment.
      type: object
      additionalProperties: false
      properties:
        Destination:
          $ref: '#/components/schemas/S3Url'
        DestinationType:
          $ref: '#/components/schemas/AssessmentReportDestinationType'
    AssessmentStatus:
      description: 'The status of the specified assessment. '
      type: string
      enum:
        - ACTIVE
        - INACTIVE
    AssessmentDescription:
      description: The description of the specified assessment.
      type: string
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      additionalProperties: false
      properties:
        Key:
          type: string
          description: 'The key name of the tag. You can specify a value that is 1 to 127 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          minLength: 1
          maxLength: 128
        Value:
          type: string
          description: 'The value for the tag. You can specify a value that is 1 to 255 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          minLength: 0
          maxLength: 256
      required:
        - Key
        - Value
    Assessment:
      type: object
      properties:
        FrameworkId:
          $ref: '#/components/schemas/FrameworkId'
        AssessmentId:
          $ref: '#/components/schemas/UUID'
        AwsAccount:
          $ref: '#/components/schemas/AWSAccount'
        Arn:
          $ref: '#/components/schemas/AssessmentArn'
        Tags:
          description: The tags associated with the assessment.
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        Delegations:
          description: The list of delegations.
          type: array
          items:
            $ref: '#/components/schemas/Delegation'
        Roles:
          description: The list of roles for the specified assessment.
          type: array
          items:
            $ref: '#/components/schemas/Role'
        Scope:
          $ref: '#/components/schemas/Scope'
        AssessmentReportsDestination:
          $ref: '#/components/schemas/AssessmentReportsDestination'
        Status:
          $ref: '#/components/schemas/AssessmentStatus'
        CreationTime:
          $ref: '#/components/schemas/Timestamp'
        Name:
          $ref: '#/components/schemas/AssessmentName'
        Description:
          $ref: '#/components/schemas/AssessmentDescription'
      required: []
      x-stackql-resource-name: assessment
      description: An entity that defines the scope of audit evidence collected by AWS Audit Manager.
      x-type-name: AWS::AuditManager::Assessment
      x-stackql-primary-identifier:
        - AssessmentId
      x-create-only-properties:
        - FrameworkId
        - AwsAccount
      x-write-only-properties:
        - Name
        - Description
      x-read-only-properties:
        - AssessmentId
        - Arn
        - CreationTime
      x-required-properties: []
      x-required-permissions:
        create:
          - auditmanager:CreateAssessment
          - auditmanager:TagResource
          - auditmanager:ListTagsForResource
          - auditmanager:BatchCreateDelegationByAssessment
          - iam:PassRole
        read:
          - auditmanager:GetAssessment
        update:
          - auditmanager:UpdateAssessment
          - auditmanager:UpdateAssessmentStatus
          - auditmanager:BatchCreateDelegationByAssessment
          - auditmanager:BatchDeleteDelegationByAssessment
        delete:
          - auditmanager:DeleteAssessment
        list:
          - auditmanager:ListAssessments
  x-stackQL-resources:
    assessments:
      name: assessments
      id: aws.auditmanager.assessments
      x-cfn-schema-name: Assessment
      x-type: list
      x-identifiers:
        - AssessmentId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.AssessmentId') as assessment_id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::AuditManager::Assessment'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'AssessmentId') as assessment_id
                FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::AuditManager::Assessment'
                AND region = 'us-east-1'
    assessment:
      name: assessment
      id: aws.auditmanager.assessment
      x-cfn-schema-name: Assessment
      x-type: get
      x-identifiers:
        - AssessmentId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.FrameworkId') as framework_id,
              JSON_EXTRACT(Properties, '$.AssessmentId') as assessment_id,
              JSON_EXTRACT(Properties, '$.AwsAccount') as aws_account,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.Delegations') as delegations,
              JSON_EXTRACT(Properties, '$.Roles') as roles,
              JSON_EXTRACT(Properties, '$.Scope') as scope,
              JSON_EXTRACT(Properties, '$.AssessmentReportsDestination') as assessment_reports_destination,
              JSON_EXTRACT(Properties, '$.Status') as status,
              JSON_EXTRACT(Properties, '$.CreationTime') as creation_time,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Description') as description
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::AuditManager::Assessment'
              AND data__Identifier = '<AssessmentId>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'FrameworkId') as framework_id,
                json_extract_path_text(Properties, 'AssessmentId') as assessment_id,
                json_extract_path_text(Properties, 'AwsAccount') as aws_account,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'Tags') as tags,
                json_extract_path_text(Properties, 'Delegations') as delegations,
                json_extract_path_text(Properties, 'Roles') as roles,
                json_extract_path_text(Properties, 'Scope') as scope,
                json_extract_path_text(Properties, 'AssessmentReportsDestination') as assessment_reports_destination,
                json_extract_path_text(Properties, 'Status') as status,
                json_extract_path_text(Properties, 'CreationTime') as creation_time,
                json_extract_path_text(Properties, 'Name') as name,
                json_extract_path_text(Properties, 'Description') as description
                FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::AuditManager::Assessment'
                AND data__Identifier = '<AssessmentId>'
                AND region = 'us-east-1'
