openapi: 3.0.0
info:
  title: AutoScalingPlans
  version: 1.0.0
paths: {}
components:
  schemas:
    ScalingInstruction:
      type: object
      additionalProperties: false
      properties:
        DisableDynamicScaling:
          type: boolean
        ServiceNamespace:
          type: string
        PredictiveScalingMaxCapacityBehavior:
          type: string
        ScalableDimension:
          type: string
        ScalingPolicyUpdateBehavior:
          type: string
        MinCapacity:
          type: integer
        TargetTrackingConfigurations:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/TargetTrackingConfiguration'
        PredictiveScalingMaxCapacityBuffer:
          type: integer
        CustomizedLoadMetricSpecification:
          $ref: '#/components/schemas/CustomizedLoadMetricSpecification'
        PredefinedLoadMetricSpecification:
          $ref: '#/components/schemas/PredefinedLoadMetricSpecification'
        ResourceId:
          type: string
        ScheduledActionBufferTime:
          type: integer
        MaxCapacity:
          type: integer
        PredictiveScalingMode:
          type: string
      required:
        - ResourceId
        - ServiceNamespace
        - ScalableDimension
        - MinCapacity
        - TargetTrackingConfigurations
        - MaxCapacity
    ApplicationSource:
      type: object
      additionalProperties: false
      properties:
        CloudFormationStackARN:
          type: string
        TagFilters:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/TagFilter'
    TargetTrackingConfiguration:
      type: object
      additionalProperties: false
      properties:
        ScaleOutCooldown:
          type: integer
        TargetValue:
          type: number
        PredefinedScalingMetricSpecification:
          $ref: '#/components/schemas/PredefinedScalingMetricSpecification'
        DisableScaleIn:
          type: boolean
        ScaleInCooldown:
          type: integer
        EstimatedInstanceWarmup:
          type: integer
        CustomizedScalingMetricSpecification:
          $ref: '#/components/schemas/CustomizedScalingMetricSpecification'
      required:
        - TargetValue
    CustomizedLoadMetricSpecification:
      type: object
      additionalProperties: false
      properties:
        MetricName:
          type: string
        Statistic:
          type: string
        Dimensions:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/MetricDimension'
        Unit:
          type: string
        Namespace:
          type: string
      required:
        - MetricName
        - Statistic
        - Namespace
    PredefinedLoadMetricSpecification:
      type: object
      additionalProperties: false
      properties:
        PredefinedLoadMetricType:
          type: string
        ResourceLabel:
          type: string
      required:
        - PredefinedLoadMetricType
    TagFilter:
      type: object
      additionalProperties: false
      properties:
        Values:
          type: array
          uniqueItems: false
          items:
            type: string
        Key:
          type: string
      required:
        - Key
    PredefinedScalingMetricSpecification:
      type: object
      additionalProperties: false
      properties:
        ResourceLabel:
          type: string
        PredefinedScalingMetricType:
          type: string
      required:
        - PredefinedScalingMetricType
    CustomizedScalingMetricSpecification:
      type: object
      additionalProperties: false
      properties:
        MetricName:
          type: string
        Statistic:
          type: string
        Dimensions:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/MetricDimension'
        Unit:
          type: string
        Namespace:
          type: string
      required:
        - MetricName
        - Statistic
        - Namespace
    MetricDimension:
      type: object
      additionalProperties: false
      properties:
        Value:
          type: string
        Name:
          type: string
      required:
        - Value
        - Name
    ScalingPlan:
      type: object
      properties:
        Id:
          type: string
        ScalingPlanName:
          type: string
        ScalingPlanVersion:
          type: string
        ApplicationSource:
          $ref: '#/components/schemas/ApplicationSource'
        ScalingInstructions:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/ScalingInstruction'
      required:
        - ScalingInstructions
        - ApplicationSource
      x-stackql-resource-name: scaling_plan
      x-stackql-primaryIdentifier:
        - Id
  x-stackQL-resources:
    scaling_plans:
      name: scaling_plans
      id: aws.autoscalingplans.scaling_plans
      x-cfn-schema-name: ScalingPlan
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::AutoScalingPlans::ScalingPlan'
    scaling_plan:
      name: scaling_plan
      id: aws.autoscalingplans.scaling_plan
      x-cfn-schema-name: ScalingPlan
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.ScalingPlanName') as scaling_plan_name,
              JSON_EXTRACT(Properties, '$.ScalingPlanVersion') as scaling_plan_version,
              JSON_EXTRACT(Properties, '$.ApplicationSource.CloudFormationStackARN') as application_source_cloud_formation_stack_ar_n,
              JSON_EXTRACT(Properties, '$.ApplicationSource.TagFilters') as application_source_tag_filters,
              JSON_EXTRACT(Properties, '$.ScalingInstructions') as scaling_instructions
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::AutoScalingPlans::ScalingPlan'
