openapi: 3.0.0
info:
  title: BillingConductor
  version: 1.0.0
paths: {}
components:
  schemas:
    BillingGroupStatus:
      type: string
      enum:
        - ACTIVE
        - PRIMARY_ACCOUNT_MISSING
    ComputationPreference:
      type: object
      additionalProperties: false
      properties:
        PricingPlanArn:
          description: ARN of the attached pricing plan
          type: string
          pattern: arn:aws(-cn)?:billingconductor::[0-9]{12}:pricingplan/[a-zA-Z0-9]{10}
      required:
        - PricingPlanArn
    AccountGrouping:
      type: object
      additionalProperties: false
      properties:
        LinkedAccountIds:
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            type: string
            pattern: '[0-9]{12}'
          minItems: 1
      required:
        - LinkedAccountIds
    Tag:
      type: object
      properties:
        Key:
          type: string
          minLength: 1
          maxLength: 128
        Value:
          type: string
          minLength: 1
          maxLength: 256
      additionalProperties: false
      required:
        - Key
        - Value
    BillingGroup:
      type: object
      properties:
        Arn:
          description: Billing Group ARN
          type: string
          pattern: arn:aws(-cn)?:billingconductor::[0-9]{12}:billinggroup/?[0-9]{12}
        Name:
          type: string
          minLength: 1
          maxLength: 128
          pattern: '[a-zA-Z0-9_\+=\.\-@]+'
        Description:
          type: string
          maxLength: 1024
        PrimaryAccountId:
          description: This account will act as a virtual payer account of the billing group
          type: string
          pattern: '[0-9]{12}'
        ComputationPreference:
          $ref: '#/components/schemas/ComputationPreference'
        AccountGrouping:
          $ref: '#/components/schemas/AccountGrouping'
        Size:
          description: Number of accounts in the billing group
          type: integer
        Status:
          $ref: '#/components/schemas/BillingGroupStatus'
        StatusReason:
          type: string
        CreationTime:
          description: Creation timestamp in UNIX epoch time format
          type: integer
        LastModifiedTime:
          description: Latest modified timestamp in UNIX epoch time format
          type: integer
        Tags:
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - Name
        - AccountGrouping
        - PrimaryAccountId
        - ComputationPreference
      x-stackql-resource-name: billing_group
      x-stackql-primaryIdentifier:
        - Arn
    Type:
      type: string
      enum:
        - FEE
        - CREDIT
    CustomLineItemPercentageChargeDetails:
      type: object
      additionalProperties: false
      properties:
        ChildAssociatedResources:
          type: array
          x-insertionOrder: false
          uniqueItems: true
          items:
            type: string
            pattern: (arn:aws(-cn)?:billingconductor::[0-9]{12}:(customlineitem|billinggroup)/)?[a-zA-Z0-9]{10,12}
        PercentageValue:
          type: number
          minimum: 0
          maximum: 10000
      required:
        - PercentageValue
    CustomLineItemFlatChargeDetails:
      type: object
      additionalProperties: false
      properties:
        ChargeValue:
          type: number
          minimum: 0
          maximum: 1000000
      required:
        - ChargeValue
    CustomLineItemChargeDetails:
      type: object
      additionalProperties: false
      properties:
        Flat:
          $ref: '#/components/schemas/CustomLineItemFlatChargeDetails'
        Percentage:
          $ref: '#/components/schemas/CustomLineItemPercentageChargeDetails'
        Type:
          $ref: '#/components/schemas/Type'
      required:
        - Type
    InclusiveStartBillingPeriod:
      type: string
      pattern: \d{4}-(0?[1-9]|1[012])
    ExclusiveEndBillingPeriod:
      type: string
      pattern: \d{4}-(0?[1-9]|1[012])
    BillingPeriodRange:
      type: object
      additionalProperties: false
      properties:
        InclusiveStartBillingPeriod:
          $ref: '#/components/schemas/InclusiveStartBillingPeriod'
        ExclusiveEndBillingPeriod:
          $ref: '#/components/schemas/ExclusiveEndBillingPeriod'
    CustomLineItem:
      type: object
      properties:
        Name:
          type: string
          minLength: 1
          maxLength: 128
          pattern: '[a-zA-Z0-9_\+=\.\-@]+'
        Description:
          type: string
          maxLength: 255
        CustomLineItemChargeDetails:
          $ref: '#/components/schemas/CustomLineItemChargeDetails'
        BillingGroupArn:
          description: Billing Group ARN
          type: string
          pattern: arn:aws(-cn)?:billingconductor::[0-9]{12}:billinggroup/?[0-9]{12}
        BillingPeriodRange:
          $ref: '#/components/schemas/BillingPeriodRange'
        Arn:
          description: ARN
          type: string
          pattern: (arn:aws(-cn)?:billingconductor::[0-9]{12}:customlineitem/)?[a-zA-Z0-9]{10}
        CreationTime:
          description: Creation timestamp in UNIX epoch time format
          type: integer
        LastModifiedTime:
          description: Latest modified timestamp in UNIX epoch time format
          type: integer
        AssociationSize:
          description: Number of source values associated to this custom line item
          type: integer
        ProductCode:
          type: string
          minLength: 1
          maxLength: 29
        CurrencyCode:
          type: string
          enum:
            - USD
            - CNY
        Tags:
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - Name
        - BillingGroupArn
      x-stackql-resource-name: custom_line_item
      x-stackql-primaryIdentifier:
        - Arn
    PricingRuleArn:
      description: Pricing Rule ARN
      type: string
      pattern: arn:aws(-cn)?:billingconductor::[0-9]{12}:pricingrule/[a-zA-Z0-9]{10}
    PricingPlan:
      type: object
      properties:
        Arn:
          description: Pricing Plan ARN
          type: string
          pattern: arn:aws(-cn)?:billingconductor::[0-9]{12}:pricingplan/[a-zA-Z0-9]{10}
        Name:
          type: string
          minLength: 1
          maxLength: 128
          pattern: '[a-zA-Z0-9_\+=\.\-@]+'
        PricingRuleArns:
          type: array
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/PricingRuleArn'
        Size:
          type: integer
          description: Number of associated pricing rules
        Description:
          type: string
          maxLength: 1024
        CreationTime:
          description: Creation timestamp in UNIX epoch time format
          type: integer
        LastModifiedTime:
          description: Latest modified timestamp in UNIX epoch time format
          type: integer
        Tags:
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - Name
      x-stackql-resource-name: pricing_plan
      x-stackql-primaryIdentifier:
        - Arn
    FreeTier:
      description: The possible customizable free tier configurations.
      type: object
      additionalProperties: false
      properties:
        Activated:
          type: boolean
      required:
        - Activated
    PricingRule:
      type: object
      properties:
        Arn:
          description: Pricing rule ARN
          type: string
          pattern: arn:aws(-cn)?:billingconductor::[0-9]{12}:pricingrule/[a-zA-Z0-9]{10}
        Name:
          description: Pricing rule name
          type: string
          minLength: 1
          maxLength: 128
          pattern: '[a-zA-Z0-9_\+=\.\-@]+'
        Description:
          description: Pricing rule description
          type: string
          maxLength: 1024
        Scope:
          description: A term used to categorize the granularity of a Pricing Rule.
          type: string
          enum:
            - GLOBAL
            - SERVICE
            - BILLING_ENTITY
            - SKU
        Type:
          description: One of MARKUP, DISCOUNT or TIERING that describes the behaviour of the pricing rule.
          type: string
          enum:
            - MARKUP
            - DISCOUNT
            - TIERING
        ModifierPercentage:
          description: Pricing rule modifier percentage
          type: number
          minimum: 0
        Service:
          description: The service which a pricing rule is applied on
          type: string
          minLength: 1
          maxLength: 128
          pattern: '[a-zA-Z0-9\.\-]+'
        BillingEntity:
          description: The seller of services provided by AWS, their affiliates, or third-party providers selling services via AWS Marketplaces. Supported billing entities are AWS, AWS Marketplace, and AISPL.
          type: string
          enum:
            - AWS
            - AWS Marketplace
            - AISPL
        Tiering:
          description: The set of tiering configurations for the pricing rule.
          type: object
          additionalProperties: false
          properties:
            FreeTier:
              $ref: '#/components/schemas/FreeTier'
        UsageType:
          description: The UsageType which a SKU pricing rule is modifying
          type: string
          minLength: 1
          maxLength: 256
          pattern: ^\S+$
        Operation:
          description: The Operation which a SKU pricing rule is modifying
          type: string
          minLength: 1
          maxLength: 256
          pattern: ^\S+$
        AssociatedPricingPlanCount:
          description: The number of pricing plans associated with pricing rule
          type: integer
          minimum: 0
        CreationTime:
          description: Creation timestamp in UNIX epoch time format
          type: integer
        LastModifiedTime:
          description: Latest modified timestamp in UNIX epoch time format
          type: integer
        Tags:
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - Name
        - Scope
        - Type
      x-stackql-resource-name: pricing_rule
      x-stackql-primaryIdentifier:
        - Arn
  x-stackQL-resources:
    billing_groups:
      name: billing_groups
      id: aws.billingconductor.billing_groups
      x-cfn-schema-name: BillingGroup
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::BillingConductor::BillingGroup'
    billing_group:
      name: billing_group
      id: aws.billingconductor.billing_group
      x-cfn-schema-name: BillingGroup
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.PrimaryAccountId') as primary_account_id,
              JSON_EXTRACT(Properties, '$.ComputationPreference.PricingPlanArn') as computation_preference_pricing_plan_arn,
              JSON_EXTRACT(Properties, '$.AccountGrouping.LinkedAccountIds') as account_grouping_linked_account_ids,
              JSON_EXTRACT(Properties, '$.Size') as size,
              JSON_EXTRACT(Properties, '$.StatusReason') as status_reason,
              JSON_EXTRACT(Properties, '$.CreationTime') as creation_time,
              JSON_EXTRACT(Properties, '$.LastModifiedTime') as last_modified_time,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::BillingConductor::BillingGroup'
    custom_line_items:
      name: custom_line_items
      id: aws.billingconductor.custom_line_items
      x-cfn-schema-name: CustomLineItem
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::BillingConductor::CustomLineItem'
    custom_line_item:
      name: custom_line_item
      id: aws.billingconductor.custom_line_item
      x-cfn-schema-name: CustomLineItem
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.CustomLineItemChargeDetails.Flat') as custom_line_item_charge_details_flat,
              JSON_EXTRACT(Properties, '$.CustomLineItemChargeDetails.Percentage') as custom_line_item_charge_details_percentage,
              JSON_EXTRACT(Properties, '$.CustomLineItemChargeDetails.Type') as custom_line_item_charge_details_type,
              JSON_EXTRACT(Properties, '$.BillingGroupArn') as billing_group_arn,
              JSON_EXTRACT(Properties, '$.BillingPeriodRange.InclusiveStartBillingPeriod') as billing_period_range_inclusive_start_billing_period,
              JSON_EXTRACT(Properties, '$.BillingPeriodRange.ExclusiveEndBillingPeriod') as billing_period_range_exclusive_end_billing_period,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.CreationTime') as creation_time,
              JSON_EXTRACT(Properties, '$.LastModifiedTime') as last_modified_time,
              JSON_EXTRACT(Properties, '$.AssociationSize') as association_size,
              JSON_EXTRACT(Properties, '$.ProductCode') as product_code,
              JSON_EXTRACT(Properties, '$.CurrencyCode') as currency_code,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::BillingConductor::CustomLineItem'
    pricing_plans:
      name: pricing_plans
      id: aws.billingconductor.pricing_plans
      x-cfn-schema-name: PricingPlan
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::BillingConductor::PricingPlan'
    pricing_plan:
      name: pricing_plan
      id: aws.billingconductor.pricing_plan
      x-cfn-schema-name: PricingPlan
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.PricingRuleArns') as pricing_rule_arns,
              JSON_EXTRACT(Properties, '$.Size') as size,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.CreationTime') as creation_time,
              JSON_EXTRACT(Properties, '$.LastModifiedTime') as last_modified_time,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::BillingConductor::PricingPlan'
    pricing_rules:
      name: pricing_rules
      id: aws.billingconductor.pricing_rules
      x-cfn-schema-name: PricingRule
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::BillingConductor::PricingRule'
    pricing_rule:
      name: pricing_rule
      id: aws.billingconductor.pricing_rule
      x-cfn-schema-name: PricingRule
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.Scope') as scope,
              JSON_EXTRACT(Properties, '$.Type') as type,
              JSON_EXTRACT(Properties, '$.ModifierPercentage') as modifier_percentage,
              JSON_EXTRACT(Properties, '$.Service') as service,
              JSON_EXTRACT(Properties, '$.BillingEntity') as billing_entity,
              JSON_EXTRACT(Properties, '$.Tiering') as tiering,
              JSON_EXTRACT(Properties, '$.UsageType') as usage_type,
              JSON_EXTRACT(Properties, '$.Operation') as operation,
              JSON_EXTRACT(Properties, '$.AssociatedPricingPlanCount') as associated_pricing_plan_count,
              JSON_EXTRACT(Properties, '$.CreationTime') as creation_time,
              JSON_EXTRACT(Properties, '$.LastModifiedTime') as last_modified_time,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::BillingConductor::PricingRule'
