openapi: 3.0.0
info:
  title: Cloud9
  version: 1.0.0
paths: {}
components:
  schemas:
    Repository:
      type: object
      additionalProperties: false
      properties:
        RepositoryUrl:
          type: string
        PathComponent:
          type: string
      required:
        - PathComponent
        - RepositoryUrl
    Tag:
      type: object
      additionalProperties: false
      properties:
        Value:
          type: string
        Key:
          type: string
      required:
        - Value
        - Key
    EnvironmentEC2:
      type: object
      properties:
        Repositories:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Repository'
        OwnerArn:
          type: string
        Description:
          type: string
        ConnectionType:
          type: string
        AutomaticStopTimeMinutes:
          type: integer
        ImageId:
          type: string
        SubnetId:
          type: string
        Id:
          type: string
        Arn:
          type: string
        InstanceType:
          type: string
        Tags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
        Name:
          type: string
      required:
        - InstanceType
      x-stackql-resource-name: environment_ec2
      x-stackql-primaryIdentifier:
        - Id
  x-stackQL-resources:
    environment_ec2s:
      name: environment_ec2s
      id: aws.cloud9.environment_ec2s
      x-cfn-schema-name: EnvironmentEC2
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Cloud9::EnvironmentEC2'
    environment_ec2:
      name: environment_ec2
      id: aws.cloud9.environment_ec2
      x-cfn-schema-name: EnvironmentEC2
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Repositories') as repositories,
              JSON_EXTRACT(Properties, '$.OwnerArn') as owner_arn,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.ConnectionType') as connection_type,
              JSON_EXTRACT(Properties, '$.AutomaticStopTimeMinutes') as automatic_stop_time_minutes,
              JSON_EXTRACT(Properties, '$.ImageId') as image_id,
              JSON_EXTRACT(Properties, '$.SubnetId') as subnet_id,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.InstanceType') as instance_type,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.Name') as name
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Cloud9::EnvironmentEC2'
