openapi: 3.0.0
info:
  version: "2021-08-11"
  title: AWS CloudTrail Data Service
  description: AWS CloudTrail Data Service
  x-serviceName: cloudtrail-data
  x-serviceAlias: cloudtrail_data
  x-protocol: rest-json
  x-apiVersion: "2021-08-11"
  x-endpointPrefix: cloudtrail-data
  x-jsonVersion: "1.1"
servers:
  - url: https://cloudtrail-data.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for cloudtrail-data
paths:
  /PutAuditEvents:
    post:
      operationId: PutAuditEvents
      description: Ingests your application events into CloudTrail Lake. A required parameter, auditEvents, accepts the JSON records (also called payload) of events that you want CloudTrail to ingest. You can add up to 100 of these events (or up to 1 MB) per PutAuditEvents request.
      parameters:
        - name: channelArn
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/ChannelArn"
          description: The ARN or ID (the ARN suffix) of a channel.
        - name: externalId
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/ExternalId"
          description: A unique identifier that is conditionally required when the channel's resource policy includes an external ID. This value can be any string, such as a passphrase or account number.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                auditEvents:
                  $ref: "#/components/schemas/AuditEvents"
              required:
                - auditEvents
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PutAuditEventsResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    ChannelArn:
      type: string
      pattern: ^arn:.*$
    ExternalId:
      type: string
      minLength: 2
      maxLength: 1224
      pattern: ^[\w+=,.@:\/-]*$
    AuditEvents:
      type: array
      items:
        $ref: "#/components/schemas/AuditEvent"
    AuditEvent:
      description: An event from a source outside of Amazon Web Services that you want CloudTrail to log.
      type: object
      properties:
        eventData:
          $ref: "#/components/schemas/String"
          description: The content of an audit event that comes from the event, such as userIdentity, userAgent, and eventSource.
        eventDataChecksum:
          $ref: "#/components/schemas/String"
          description: "A checksum is a base64-SHA256 algorithm that helps you verify that CloudTrail receives the event that matches with the checksum. Calculate the checksum by running a command like the following: printf %s $eventdata | openssl dgst -binary -sha256 | base64"
        id:
          $ref: "#/components/schemas/Uuid"
          description: The original event ID from the source event.
      required:
        - eventData
        - id
    String:
      type: string
    Uuid:
      type: string
      minLength: 1
      maxLength: 128
      pattern: ^[-_A-Za-z0-9]+$
    PutAuditEventsResponse:
      type: object
      properties:
        failed:
          $ref: "#/components/schemas/ResultErrorEntries"
          description: Lists events in the provided event payload that could not be ingested into CloudTrail, and includes the error code and error message returned for events that could not be ingested.
        successful:
          $ref: "#/components/schemas/AuditEventResultEntries"
          description: Lists events in the provided event payload that were successfully ingested into CloudTrail.
      required:
        - failed
        - successful
    ResultErrorEntries:
      type: array
      items:
        $ref: "#/components/schemas/ResultErrorEntry"
    ResultErrorEntry:
      description: Includes the error code and error message for events that could not be ingested by CloudTrail.
      type: object
      properties:
        errorCode:
          $ref: "#/components/schemas/ErrorCode"
          description: "The error code for events that could not be ingested by CloudTrail. Possible error codes include: FieldTooLong, FieldNotFound, InvalidChecksum, InvalidData, InvalidRecipient, InvalidEventSource, AccountNotSubscribed, Throttling, and InternalFailure."
        errorMessage:
          $ref: "#/components/schemas/ErrorMessage"
          description: The message that describes the error for events that could not be ingested by CloudTrail.
        id:
          $ref: "#/components/schemas/Uuid"
          description: The original event ID from the source event that could not be ingested by CloudTrail.
      required:
        - errorCode
        - errorMessage
        - id
    ErrorCode:
      type: string
      minLength: 1
      maxLength: 128
    ErrorMessage:
      type: string
      minLength: 1
      maxLength: 1024
    AuditEventResultEntries:
      type: array
      items:
        $ref: "#/components/schemas/AuditEventResultEntry"
    AuditEventResultEntry:
      description: A response that includes successful and failed event results.
      type: object
      properties:
        eventID:
          $ref: "#/components/schemas/Uuid"
          description: The event ID assigned by CloudTrail.
        id:
          $ref: "#/components/schemas/Uuid"
          description: The original event ID from the source event.
      required:
        - eventID
        - id
  x-stackQL-resources:
    audit_events:
      id: aws.cloudtrail_data.audit_events
      name: audit_events
      title: audit_events
      methods:
        put_audit_events:
          operation:
            $ref: "#/paths/~1PutAuditEvents/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        replace:
          - $ref: "#/components/x-stackQL-resources/audit_events/methods/put_audit_events"
        delete: []
