openapi: 3.0.0
info:
  version: "2022-07-26"
  title: Amazon CloudFront KeyValueStore
  description: Amazon CloudFront KeyValueStore
  x-serviceName: cloudfront-keyvaluestore
  x-serviceAlias: cloudfront_keyvaluestore
  x-protocol: rest-json
  x-apiVersion: "2022-07-26"
  x-endpointPrefix: cloudfront-keyvaluestore
  x-jsonVersion: "1.1"
servers:
  - url: https://cloudfront-keyvaluestore.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for cloudfront-keyvaluestore
paths:
  /key-value-stores/{kvs_arn}/keys/{key}:
    delete:
      operationId: DeleteKey
      description: Deletes the key value pair specified by the key.
      parameters:
        - name: kvs_arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/KvsARN"
          description: The Amazon Resource Name (ARN) of the Key Value Store.
        - name: key
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Key"
          description: The key to delete.
        - name: If-Match
          in: header
          required: true
          schema:
            $ref: "#/components/schemas/Etag"
          description: The current version (ETag) of the Key Value Store that you are deleting keys from, which you can get using DescribeKeyValueStore.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteKeyResponse"
    get:
      operationId: GetKey
      description: Returns a key value pair.
      parameters:
        - name: kvs_arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/KvsARN"
          description: The Amazon Resource Name (ARN) of the Key Value Store.
        - name: key
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Key"
          description: The key to get.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetKeyResponse"
    put:
      operationId: PutKey
      description: Creates a new key value pair or replaces the value of an existing key.
      parameters:
        - name: key
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Key"
          description: The key to put.
        - name: kvs_arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/KvsARN"
          description: The Amazon Resource Name (ARN) of the Key Value Store.
        - name: If-Match
          in: header
          required: true
          schema:
            $ref: "#/components/schemas/Etag"
          description: The current version (ETag) of the Key Value Store that you are putting keys into, which you can get using DescribeKeyValueStore.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Value:
                  $ref: "#/components/schemas/Value"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PutKeyResponse"
  /key-value-stores/{kvs_arn}:
    get:
      operationId: DescribeKeyValueStore
      description: Returns metadata information about Key Value Store.
      parameters:
        - name: kvs_arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/KvsARN"
          description: The Amazon Resource Name (ARN) of the Key Value Store.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DescribeKeyValueStoreResponse"
  /key-value-stores/{kvs_arn}/keys:
    get:
      operationId: ListKeys
      description: Returns a list of key value pairs.
      parameters:
        - name: kvs_arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/KvsARN"
          description: The Amazon Resource Name (ARN) of the Key Value Store.
        - name: NextToken
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/String"
          description: If nextToken is returned in the response, there are more results available. Make the next call using the returned token to retrieve the next page.
        - name: MaxResults
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/ListKeysRequestMaxResultsInteger"
          description: Maximum number of results that are returned per call. The default is 10 and maximum allowed page is 50.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListKeysResponse"
    post:
      operationId: UpdateKeys
      description: Puts or Deletes multiple key value pairs in a single, all-or-nothing operation.
      parameters:
        - name: kvs_arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/KvsARN"
          description: The Amazon Resource Name (ARN) of the Key Value Store.
        - name: If-Match
          in: header
          required: true
          schema:
            $ref: "#/components/schemas/Etag"
          description: The current version (ETag) of the Key Value Store that you are updating keys of, which you can get using DescribeKeyValueStore.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                Puts:
                  $ref: "#/components/schemas/PutKeyRequestsList"
                Deletes:
                  $ref: "#/components/schemas/DeleteKeyRequestsList"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateKeysResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    KvsARN:
      type: string
      minLength: 1
      maxLength: 2048
    Key:
      type: string
      minLength: 1
      maxLength: 1024
    Etag:
      type: string
    DeleteKeyResponse:
      description: Metadata information about a Key Value Store.
      type: object
      properties:
        ItemCount:
          $ref: "#/components/schemas/Integer"
          description: Number of key value pairs in the Key Value Store after the successful delete.
        TotalSizeInBytes:
          $ref: "#/components/schemas/Long"
          description: Total size of the Key Value Store after the successful delete, in bytes.
        ETag:
          $ref: "#/components/schemas/Etag"
          description: The current version identifier of the Key Value Store after the successful delete.
      required:
        - ItemCount
        - TotalSizeInBytes
        - ETag
    Integer:
      type: integer
    Long:
      type: integer
      format: int64
    DescribeKeyValueStoreResponse:
      description: Metadata information about a Key Value Store.
      type: object
      properties:
        ItemCount:
          $ref: "#/components/schemas/Integer"
          description: Number of key value pairs in the Key Value Store.
        TotalSizeInBytes:
          $ref: "#/components/schemas/Long"
          description: Total size of the Key Value Store in bytes.
        KvsARN:
          $ref: "#/components/schemas/KvsARN"
          description: The Amazon Resource Name (ARN) of the Key Value Store.
        Created:
          $ref: "#/components/schemas/Timestamp"
          description: Date and time when the Key Value Store was created.
        ETag:
          $ref: "#/components/schemas/Etag"
          description: The version identifier for the current version of the Key Value Store.
        LastModified:
          $ref: "#/components/schemas/Timestamp"
          description: Date and time when the key value pairs in the Key Value Store was last modified.
        Status:
          $ref: "#/components/schemas/String"
          description: The current status of the Key Value Store.
        FailureReason:
          $ref: "#/components/schemas/String"
          description: The reason for Key Value Store creation failure.
      required:
        - ItemCount
        - TotalSizeInBytes
        - KvsARN
        - Created
        - ETag
    Timestamp:
      type: string
      format: date-time
    String:
      type: string
    GetKeyResponse:
      description: A key value pair.
      type: object
      properties:
        Key:
          $ref: "#/components/schemas/Key"
          description: The key of the key value pair.
        Value:
          $ref: "#/components/schemas/Value"
          description: The value of the key value pair.
        ItemCount:
          $ref: "#/components/schemas/Integer"
          description: Number of key value pairs in the Key Value Store.
        TotalSizeInBytes:
          $ref: "#/components/schemas/Long"
          description: Total size of the Key Value Store in bytes.
      required:
        - Key
        - Value
        - ItemCount
        - TotalSizeInBytes
    Value:
      type: string
    ListKeysRequestMaxResultsInteger:
      type: integer
      minimum: 1
      maximum: 50
    ListKeysResponse:
      type: object
      properties:
        NextToken:
          $ref: "#/components/schemas/String"
          description: If nextToken is returned in the response, there are more results available. Make the next call using the returned token to retrieve the next page.
        Items:
          $ref: "#/components/schemas/ListKeysResponseList"
          description: Key value pairs
    ListKeysResponseList:
      type: array
      items:
        $ref: "#/components/schemas/ListKeysResponseListItem"
    ListKeysResponseListItem:
      description: A key value pair.
      type: object
      properties:
        Key:
          $ref: "#/components/schemas/Key"
          description: The key of the key value pair.
        Value:
          $ref: "#/components/schemas/Value"
          description: The value of the key value pair.
      required:
        - Key
        - Value
    PutKeyResponse:
      description: Metadata information about a Key Value Store.
      type: object
      properties:
        ItemCount:
          $ref: "#/components/schemas/Integer"
          description: Number of key value pairs in the Key Value Store after the successful put.
        TotalSizeInBytes:
          $ref: "#/components/schemas/Long"
          description: Total size of the Key Value Store after the successful put, in bytes.
        ETag:
          $ref: "#/components/schemas/Etag"
          description: The current version identifier of the Key Value Store after the successful put.
      required:
        - ItemCount
        - TotalSizeInBytes
        - ETag
    PutKeyRequestsList:
      type: array
      items:
        $ref: "#/components/schemas/PutKeyRequestListItem"
    PutKeyRequestListItem:
      description: List item for key value pair to put.
      type: object
      properties:
        Key:
          $ref: "#/components/schemas/Key"
          description: The key of the key value pair list item to put.
        Value:
          $ref: "#/components/schemas/Value"
          description: The value for the key value pair to put.
      required:
        - Key
        - Value
    DeleteKeyRequestsList:
      type: array
      items:
        $ref: "#/components/schemas/DeleteKeyRequestListItem"
    DeleteKeyRequestListItem:
      description: List item for keys to delete.
      type: object
      properties:
        Key:
          $ref: "#/components/schemas/Key"
          description: The key of the key value pair to be deleted.
      required:
        - Key
    UpdateKeysResponse:
      description: Metadata information about a Key Value Store.
      type: object
      properties:
        ItemCount:
          $ref: "#/components/schemas/Integer"
          description: Number of key value pairs in the Key Value Store after the successful update.
        TotalSizeInBytes:
          $ref: "#/components/schemas/Long"
          description: Total size of the Key Value Store after the successful update, in bytes.
        ETag:
          $ref: "#/components/schemas/Etag"
          description: The current version identifier of the Key Value Store after the successful update.
      required:
        - ItemCount
        - TotalSizeInBytes
        - ETag
  x-stackQL-resources:
    keys:
      id: aws.cloudfront_keyvaluestore.keys
      name: keys
      title: keys
      methods:
        delete_key:
          operation:
            $ref: "#/paths/~1key-value-stores~1{kvs_arn}~1keys~1{key}/delete"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        get_key:
          operation:
            $ref: "#/paths/~1key-value-stores~1{kvs_arn}~1keys~1{key}/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        put_key:
          operation:
            $ref: "#/paths/~1key-value-stores~1{kvs_arn}~1keys~1{key}/put"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
        list_keys:
          operation:
            $ref: "#/paths/~1key-value-stores~1{kvs_arn}~1keys/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.Items
          request:
            nativeCasing: pascal
          config:
            pagination:
              requestToken:
                key: NextToken
                location: query
              responseToken:
                key: $.NextToken
                location: body
        update_keys:
          operation:
            $ref: "#/paths/~1key-value-stores~1{kvs_arn}~1keys/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/keys/methods/get_key"
          - $ref: "#/components/x-stackQL-resources/keys/methods/list_keys"
        insert: []
        update:
          - $ref: "#/components/x-stackQL-resources/keys/methods/update_keys"
        replace:
          - $ref: "#/components/x-stackQL-resources/keys/methods/put_key"
        delete:
          - $ref: "#/components/x-stackQL-resources/keys/methods/delete_key"
    key_value_stores:
      id: aws.cloudfront_keyvaluestore.key_value_stores
      name: key_value_stores
      title: key_value_stores
      methods:
        describe_key_value_store:
          operation:
            $ref: "#/paths/~1key-value-stores~1{kvs_arn}/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/key_value_stores/methods/describe_key_value_store"
        insert: []
        update: []
        delete: []
