openapi: 3.0.0
info:
  title: CodeStarNotifications
  version: 1.0.0
paths: {}
components:
  schemas:
    Target:
      type: object
      additionalProperties: false
      properties:
        TargetType:
          type: string
        TargetAddress:
          type: string
      required:
        - TargetType
        - TargetAddress
    NotificationRule:
      type: object
      properties:
        EventTypeId:
          type: string
          minLength: 1
          maxLength: 2048
        CreatedBy:
          type: string
          minLength: 1
          maxLength: 2048
        TargetAddress:
          type: string
          minLength: 1
          maxLength: 2048
        EventTypeIds:
          type: array
          uniqueItems: false
          items:
            type: string
            minLength: 1
            maxLength: 200
        Status:
          type: string
          enum:
            - ENABLED
            - DISABLED
        DetailType:
          type: string
          enum:
            - BASIC
            - FULL
        Resource:
          type: string
          pattern: ^arn:aws[^:\s]*:[^:\s]*:[^:\s]*:[0-9]{12}:[^\s]+$
        Targets:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Target'
          maxItems: 10
        Tags:
          type: object
          additionalProperties: false
          x-patternProperties:
            .*:
              type: string
        Name:
          type: string
          pattern: '[A-Za-z0-9\-_ ]+$'
          minLength: 1
          maxLength: 64
        Arn:
          type: string
          pattern: ^arn:aws[^:\s]*:codestar-notifications:[^:\s]+:\d{12}:notificationrule\/(.*\S)?$
      required:
        - EventTypeIds
        - Resource
        - DetailType
        - Targets
        - Name
      x-stackql-resource-name: notification_rule
      description: Resource Type definition for AWS::CodeStarNotifications::NotificationRule
      x-type-name: AWS::CodeStarNotifications::NotificationRule
      x-stackql-primary-identifier:
        - Arn
      x-create-only-properties:
        - Resource
      x-write-only-properties:
        - EventTypeId
        - TargetAddress
      x-read-only-properties:
        - Arn
      x-required-properties:
        - EventTypeIds
        - Resource
        - DetailType
        - Targets
        - Name
      x-required-permissions:
        create:
          - codestar-notifications:createNotificationRule
        list:
          - codestar-notifications:listNotificationRules
        read:
          - codestar-notifications:describeNotificationRule
        delete:
          - codestar-notifications:deleteNotificationRule
          - codestar-notifications:describeNotificationRule
        update:
          - codestar-notifications:updateNotificationRule
          - codestar-notifications:TagResource
          - codestar-notifications:UntagResource
  x-stackQL-resources:
    notification_rules:
      name: notification_rules
      id: aws.codestarnotifications.notification_rules
      x-cfn-schema-name: NotificationRule
      x-type: list
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::CodeStarNotifications::NotificationRule'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Arn') as arn
                FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::CodeStarNotifications::NotificationRule'
                AND region = 'us-east-1'
    notification_rule:
      name: notification_rule
      id: aws.codestarnotifications.notification_rule
      x-cfn-schema-name: NotificationRule
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.EventTypeId') as event_type_id,
              JSON_EXTRACT(Properties, '$.CreatedBy') as created_by,
              JSON_EXTRACT(Properties, '$.TargetAddress') as target_address,
              JSON_EXTRACT(Properties, '$.EventTypeIds') as event_type_ids,
              JSON_EXTRACT(Properties, '$.Status') as status,
              JSON_EXTRACT(Properties, '$.DetailType') as detail_type,
              JSON_EXTRACT(Properties, '$.Resource') as resource,
              JSON_EXTRACT(Properties, '$.Targets') as targets,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::CodeStarNotifications::NotificationRule'
              AND data__Identifier = '<Arn>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'EventTypeId') as event_type_id,
                json_extract_path_text(Properties, 'CreatedBy') as created_by,
                json_extract_path_text(Properties, 'TargetAddress') as target_address,
                json_extract_path_text(Properties, 'EventTypeIds') as event_type_ids,
                json_extract_path_text(Properties, 'Status') as status,
                json_extract_path_text(Properties, 'DetailType') as detail_type,
                json_extract_path_text(Properties, 'Resource') as resource,
                json_extract_path_text(Properties, 'Targets') as targets,
                json_extract_path_text(Properties, 'Tags') as tags,
                json_extract_path_text(Properties, 'Name') as name,
                json_extract_path_text(Properties, 'Arn') as arn
                FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::CodeStarNotifications::NotificationRule'
                AND data__Identifier = '<Arn>'
                AND region = 'us-east-1'
