openapi: 3.0.0
info:
  title: CodeCommit
  version: 1.0.0
paths: {}
components:
  schemas:
    S3:
      type: object
      additionalProperties: false
      properties:
        ObjectVersion:
          type: string
        Bucket:
          type: string
        Key:
          type: string
      required:
        - Bucket
        - Key
    Tag:
      type: object
      additionalProperties: false
      properties:
        Value:
          type: string
        Key:
          type: string
      required:
        - Value
        - Key
    RepositoryTrigger:
      type: object
      additionalProperties: false
      properties:
        CustomData:
          type: string
        Events:
          type: array
          uniqueItems: false
          items:
            type: string
        Branches:
          type: array
          uniqueItems: false
          items:
            type: string
        DestinationArn:
          type: string
        Name:
          type: string
      required:
        - Events
        - DestinationArn
        - Name
    Code:
      type: object
      additionalProperties: false
      properties:
        S3:
          $ref: '#/components/schemas/S3'
        BranchName:
          type: string
      required:
        - S3
    Repository:
      type: object
      properties:
        CloneUrlHttp:
          type: string
        CloneUrlSsh:
          type: string
        RepositoryName:
          type: string
        Triggers:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/RepositoryTrigger'
        Id:
          type: string
        Arn:
          type: string
        Code:
          $ref: '#/components/schemas/Code'
        RepositoryDescription:
          type: string
        Tags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
        Name:
          type: string
      required:
        - RepositoryName
      x-stackql-resource-name: repository
      x-stackql-primaryIdentifier:
        - Id
  x-stackQL-resources:
    repositories:
      name: repositories
      id: aws.codecommit.repositories
      x-cfn-schema-name: Repository
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::CodeCommit::Repository'
    repository:
      name: repository
      id: aws.codecommit.repository
      x-cfn-schema-name: Repository
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.CloneUrlHttp') as clone_url_http,
              JSON_EXTRACT(Properties, '$.CloneUrlSsh') as clone_url_ssh,
              JSON_EXTRACT(Properties, '$.RepositoryName') as repository_name,
              JSON_EXTRACT(Properties, '$.Triggers') as triggers,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Code.S3') as code_s3,
              JSON_EXTRACT(Properties, '$.Code.BranchName') as code_branch_name,
              JSON_EXTRACT(Properties, '$.RepositoryDescription') as repository_description,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.Name') as name
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::CodeCommit::Repository'
