openapi: 3.0.0
info:
  title: CodeArtifact
  version: 1.0.0
paths: {}
components:
  schemas:
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      properties:
        Key:
          type: string
          description: 'The key name of the tag. You can specify a value that is 1 to 127 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          minLength: 1
          maxLength: 128
        Value:
          type: string
          description: 'The value for the tag. You can specify a value that is 1 to 255 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          minLength: 0
          maxLength: 256
      required:
        - Value
        - Key
      additionalProperties: false
    Domain:
      type: object
      properties:
        DomainName:
          description: The name of the domain.
          type: string
          pattern: ^([a-z][a-z0-9\-]{0,48}[a-z0-9])$
          minLength: 2
          maxLength: 50
        Name:
          description: The name of the domain. This field is used for GetAtt
          type: string
          pattern: ^([a-z][a-z0-9\-]{0,48}[a-z0-9])$
          minLength: 2
          maxLength: 50
        Owner:
          description: The 12-digit account ID of the AWS account that owns the domain. This field is used for GetAtt
          pattern: '[0-9]{12}'
          type: string
        EncryptionKey:
          description: The ARN of an AWS Key Management Service (AWS KMS) key associated with a domain.
          type: string
        PermissionsPolicyDocument:
          description: The access control resource policy on the provided domain.
          type: object
          minLength: 2
          maxLength: 5120
        Tags:
          type: array
          description: An array of key-value pairs to apply to this resource.
          items:
            $ref: '#/components/schemas/Tag'
        Arn:
          description: The ARN of the domain.
          type: string
          minLength: 1
          maxLength: 2048
      required:
        - DomainName
      x-stackql-resource-name: domain
      x-stackql-primaryIdentifier:
        - Arn
    Repository:
      type: object
      properties:
        RepositoryName:
          description: The name of the repository.
          type: string
          pattern: ^([A-Za-z0-9][A-Za-z0-9._\-]{1,99})$
          minLength: 2
          maxLength: 100
        Name:
          description: The name of the repository. This is used for GetAtt
          type: string
          pattern: ^([A-Za-z0-9][A-Za-z0-9._\-]{1,99})$
          minLength: 2
          maxLength: 100
        DomainName:
          description: The name of the domain that contains the repository.
          type: string
          pattern: ^([a-z][a-z0-9\-]{0,48}[a-z0-9])$
          minLength: 2
          maxLength: 50
        DomainOwner:
          description: The 12-digit account ID of the AWS account that owns the domain.
          pattern: '[0-9]{12}'
          type: string
        Description:
          description: A text description of the repository.
          type: string
          maxLength: 1000
        Arn:
          description: The ARN of the repository.
          type: string
          minLength: 1
          maxLength: 2048
        ExternalConnections:
          description: A list of external connections associated with the repository.
          type: array
          items:
            type: string
        Upstreams:
          description: A list of upstream repositories associated with the repository.
          type: array
          items:
            type: string
        PermissionsPolicyDocument:
          description: The access control resource policy on the provided repository.
          type: object
          minLength: 2
          maxLength: 5120
        Tags:
          type: array
          description: An array of key-value pairs to apply to this resource.
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - RepositoryName
        - DomainName
      x-stackql-resource-name: repository
      x-stackql-primaryIdentifier:
        - Arn
  x-stackQL-resources:
    domains:
      name: domains
      id: aws.codeartifact.domains
      x-cfn-schema-name: Domain
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::CodeArtifact::Domain'
    domain:
      name: domain
      id: aws.codeartifact.domain
      x-cfn-schema-name: Domain
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.DomainName') as domain_name,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Owner') as owner,
              JSON_EXTRACT(Properties, '$.EncryptionKey') as encryption_key,
              JSON_EXTRACT(Properties, '$.PermissionsPolicyDocument') as permissions_policy_document,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::CodeArtifact::Domain'
    repositories:
      name: repositories
      id: aws.codeartifact.repositories
      x-cfn-schema-name: Repository
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::CodeArtifact::Repository'
    repository:
      name: repository
      id: aws.codeartifact.repository
      x-cfn-schema-name: Repository
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.RepositoryName') as repository_name,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.DomainName') as domain_name,
              JSON_EXTRACT(Properties, '$.DomainOwner') as domain_owner,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.ExternalConnections') as external_connections,
              JSON_EXTRACT(Properties, '$.Upstreams') as upstreams,
              JSON_EXTRACT(Properties, '$.PermissionsPolicyDocument') as permissions_policy_document,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::CodeArtifact::Repository'
