openapi: 3.0.0
info:
  title: CodeStar
  version: 1.0.0
paths: {}
components:
  schemas:
    S3:
      type: object
      additionalProperties: false
      properties:
        ObjectVersion:
          type: string
        Bucket:
          type: string
        Key:
          type: string
      required:
        - Bucket
        - Key
    Code:
      type: object
      additionalProperties: false
      properties:
        S3:
          $ref: '#/components/schemas/S3'
      required:
        - S3
    GitHubRepository:
      type: object
      properties:
        EnableIssues:
          type: boolean
        ConnectionArn:
          type: string
        RepositoryName:
          type: string
        RepositoryAccessToken:
          type: string
        Id:
          type: string
        RepositoryOwner:
          type: string
        IsPrivate:
          type: boolean
        Code:
          $ref: '#/components/schemas/Code'
        RepositoryDescription:
          type: string
      required:
        - RepositoryName
        - RepositoryOwner
      x-stackql-resource-name: git_hub_repository
      x-stackql-primaryIdentifier:
        - Id
  x-stackQL-resources:
    git_hub_repositories:
      name: git_hub_repositories
      id: aws.codestar.git_hub_repositories
      x-cfn-schema-name: GitHubRepository
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::CodeStar::GitHubRepository'
    git_hub_repository:
      name: git_hub_repository
      id: aws.codestar.git_hub_repository
      x-cfn-schema-name: GitHubRepository
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.EnableIssues') as enable_issues,
              JSON_EXTRACT(Properties, '$.ConnectionArn') as connection_arn,
              JSON_EXTRACT(Properties, '$.RepositoryName') as repository_name,
              JSON_EXTRACT(Properties, '$.RepositoryAccessToken') as repository_access_token,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.RepositoryOwner') as repository_owner,
              JSON_EXTRACT(Properties, '$.IsPrivate') as is_private,
              JSON_EXTRACT(Properties, '$.Code.S3') as code_s3,
              JSON_EXTRACT(Properties, '$.RepositoryDescription') as repository_description
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::CodeStar::GitHubRepository'
