openapi: 3.0.0
info:
  version: "2020-08-21"
  title: Amazon Connect Contact Lens
  description: Amazon Connect Contact Lens
  x-serviceName: connect
  x-serviceAlias: connect_contact_lens
  x-protocol: rest-json
  x-apiVersion: "2020-08-21"
  x-endpointPrefix: contact-lens
  x-jsonVersion: "1.1"
servers:
  - url: https://contact-lens.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for connect-contact-lens
paths:
  /realtime-contact-analysis/analysis-segments:
    post:
      operationId: ListRealtimeContactAnalysisSegments
      description: Provides a list of analysis segments for a real-time analysis session.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                InstanceId:
                  $ref: "#/components/schemas/InstanceId"
                ContactId:
                  $ref: "#/components/schemas/ContactId"
                MaxResults:
                  $ref: "#/components/schemas/MaxResults"
                NextToken:
                  $ref: "#/components/schemas/NextToken"
              required:
                - InstanceId
                - ContactId
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListRealtimeContactAnalysisSegmentsResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    InstanceId:
      type: string
      minLength: 1
      maxLength: 256
      pattern: .*\S.*
    ContactId:
      type: string
      minLength: 1
      maxLength: 256
      pattern: .*\S.*
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    NextToken:
      type: string
      minLength: 1
      maxLength: 131070
      pattern: .*\S.*
    ListRealtimeContactAnalysisSegmentsResponse:
      type: object
      properties:
        Segments:
          $ref: "#/components/schemas/RealtimeContactAnalysisSegments"
          description: An analyzed transcript or category.
        NextToken:
          $ref: "#/components/schemas/NextToken"
          description: "If there are additional results, this is the token for the next set of results. If response includes nextToken there are two possible scenarios: There are more segments so another call is required to get them. There are no more segments at this time, but more may be available later (real-time analysis is in progress) so the client should call the operation again to get new segments. If response does not include nextToken, the analysis is completed (successfully or failed) and there are no more segments to retrieve."
      required:
        - Segments
    RealtimeContactAnalysisSegments:
      type: array
      items:
        $ref: "#/components/schemas/RealtimeContactAnalysisSegment"
    RealtimeContactAnalysisSegment:
      description: An analyzed segment for a real-time analysis session.
      type: object
      properties:
        Transcript:
          $ref: "#/components/schemas/Transcript"
          description: The analyzed transcript.
        Categories:
          $ref: "#/components/schemas/Categories"
          description: The matched category rules.
        PostContactSummary:
          $ref: "#/components/schemas/PostContactSummary"
          description: Information about the post-contact summary.
    Transcript:
      description: A list of messages in the session.
      type: object
      properties:
        Id:
          $ref: "#/components/schemas/TranscriptId"
          description: The identifier of the transcript.
        ParticipantId:
          $ref: "#/components/schemas/ParticipantId"
          description: The identifier of the participant. Valid values are CUSTOMER or AGENT.
        ParticipantRole:
          $ref: "#/components/schemas/ParticipantRole"
          description: The role of participant. For example, is it a customer, agent, or system.
        Content:
          $ref: "#/components/schemas/TranscriptContent"
          description: The content of the transcript.
        BeginOffsetMillis:
          $ref: "#/components/schemas/OffsetMillis"
          description: The beginning offset in the contact for this transcript.
        EndOffsetMillis:
          $ref: "#/components/schemas/OffsetMillis"
          description: The end offset in the contact for this transcript.
        Sentiment:
          $ref: "#/components/schemas/SentimentValue"
          description: The sentiment detected for this piece of transcript.
        IssuesDetected:
          $ref: "#/components/schemas/IssuesDetected"
          description: List of positions where issues were detected on the transcript.
      required:
        - Id
        - ParticipantId
        - ParticipantRole
        - Content
        - BeginOffsetMillis
        - EndOffsetMillis
    TranscriptId:
      type: string
      minLength: 1
      maxLength: 256
      pattern: .*\S.*
    ParticipantId:
      type: string
      minLength: 1
      maxLength: 256
      pattern: .*\S.*
    ParticipantRole:
      type: string
      minLength: 1
      maxLength: 256
      pattern: .*\S.*
    TranscriptContent:
      type: string
      minLength: 1
      pattern: .*\S.*
    OffsetMillis:
      type: integer
      minimum: 0
    SentimentValue:
      type: string
      enum:
        - POSITIVE
        - NEUTRAL
        - NEGATIVE
    IssuesDetected:
      type: array
      items:
        $ref: "#/components/schemas/IssueDetected"
    IssueDetected:
      description: Potential issues that are detected based on an artificial intelligence analysis of each turn in the conversation.
      type: object
      properties:
        CharacterOffsets:
          $ref: "#/components/schemas/CharacterOffsets"
          description: The offset for when the issue was detected in the segment.
      required:
        - CharacterOffsets
    CharacterOffsets:
      description: For characters that were detected as issues, where they occur in the transcript.
      type: object
      properties:
        BeginOffsetChar:
          $ref: "#/components/schemas/CharacterOffset"
          description: The beginning of the issue.
        EndOffsetChar:
          $ref: "#/components/schemas/CharacterOffset"
          description: The end of the issue.
      required:
        - BeginOffsetChar
        - EndOffsetChar
    CharacterOffset:
      type: integer
      minimum: 0
    Categories:
      description: Provides the category rules that are used to automatically categorize contacts based on uttered keywords and phrases.
      type: object
      properties:
        MatchedCategories:
          $ref: "#/components/schemas/MatchedCategories"
          description: The category rules that have been matched in the analyzed segment.
        MatchedDetails:
          type: object
          properties: {}
          description: The category rule that was matched and when it occurred in the transcript.
      required:
        - MatchedCategories
        - MatchedDetails
    MatchedCategories:
      type: array
      items:
        $ref: "#/components/schemas/CategoryName"
    CategoryName:
      type: string
      minLength: 1
      maxLength: 256
      pattern: .*\S.*
    PostContactSummary:
      description: Information about the post-contact summary.
      type: object
      properties:
        Content:
          $ref: "#/components/schemas/PostContactSummaryContent"
          description: The content of the summary.
        Status:
          $ref: "#/components/schemas/PostContactSummaryStatus"
          description: Whether the summary was successfully COMPLETED or FAILED to be generated.
        FailureCode:
          $ref: "#/components/schemas/PostContactSummaryFailureCode"
          description: "If the summary failed to be generated, one of the following failure codes occurs: QUOTA_EXCEEDED: The number of concurrent analytics jobs reached your service quota. INSUFFICIENT_CONVERSATION_CONTENT: The conversation needs to have at least one turn from both the participants in order to generate the summary. FAILED_SAFETY_GUIDELINES: The generated summary cannot be provided because it failed to meet system safety guidelines. INVALID_ANALYSIS_CONFIGURATION: This code occurs when, for example, you're using a language that isn't supported by generative AI-powered post-contact summaries. INTERNAL_ERROR: Internal system error."
      required:
        - Status
    PostContactSummaryContent:
      type: string
      minLength: 1
      maxLength: 1762
    PostContactSummaryStatus:
      type: string
      enum:
        - FAILED
        - COMPLETED
    PostContactSummaryFailureCode:
      type: string
      enum:
        - QUOTA_EXCEEDED
        - INSUFFICIENT_CONVERSATION_CONTENT
        - FAILED_SAFETY_GUIDELINES
        - INVALID_ANALYSIS_CONFIGURATION
        - INTERNAL_ERROR
  x-stackQL-resources:
    realtime_contact_analysis_segments:
      id: aws.connect_contact_lens.realtime_contact_analysis_segments
      name: realtime_contact_analysis_segments
      title: realtime_contact_analysis_segments
      methods:
        list_realtime_contact_analysis_segments:
          operation:
            $ref: "#/paths/~1realtime-contact-analysis~1analysis-segments/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/realtime_contact_analysis_segments/methods/list_realtime_contact_analysis_segments"
        insert: []
        update: []
        delete: []
