openapi: 3.0.0
info:
  title: DataPipeline
  version: 1.0.0
paths: {}
components:
  schemas:
    ParameterObject:
      type: object
      properties:
        Attributes:
          description: The attributes of the parameter object.
          uniqueItems: false
          x-insertionOrder: false
          type: array
          items:
            $ref: '#/components/schemas/ParameterAttribute'
        Id:
          description: The ID of the parameter object.
          type: string
      required:
        - Attributes
        - Id
      additionalProperties: false
    ParameterAttribute:
      type: object
      properties:
        Key:
          description: The field identifier.
          type: string
        StringValue:
          description: The field value, expressed as a String.
          type: string
      required:
        - Key
        - StringValue
      additionalProperties: false
    ParameterValue:
      type: object
      properties:
        Id:
          description: The ID of the parameter value.
          type: string
        StringValue:
          description: The field value, expressed as a String.
          type: string
      required:
        - Id
        - StringValue
      additionalProperties: false
    Field:
      type: object
      additionalProperties: false
      properties:
        Key:
          description: Specifies the name of a field for a particular object. To view valid values for a particular field, see Pipeline Object Reference in the AWS Data Pipeline Developer Guide.
          type: string
        RefValue:
          description: A field value that you specify as an identifier of another object in the same pipeline definition.
          type: string
        StringValue:
          description: A field value that you specify as a string. To view valid values for a particular field, see Pipeline Object Reference in the AWS Data Pipeline Developer Guide.
          type: string
      required:
        - Key
    PipelineObject:
      type: object
      additionalProperties: false
      properties:
        Fields:
          description: Key-value pairs that define the properties of the object.
          type: array
          uniqueItems: false
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Field'
        Id:
          description: The ID of the object.
          type: string
        Name:
          description: The name of the object.
          type: string
      required:
        - Fields
        - Id
        - Name
    PipelineTag:
      type: object
      additionalProperties: false
      properties:
        Key:
          description: The key name of a tag.
          type: string
        Value:
          description: The value to associate with the key name.
          type: string
      required:
        - Key
        - Value
    Pipeline:
      type: object
      properties:
        Activate:
          description: Indicates whether to validate and start the pipeline or stop an active pipeline. By default, the value is set to true.
          type: boolean
        Description:
          description: A description of the pipeline.
          type: string
        Name:
          description: The name of the pipeline.
          type: string
        ParameterObjects:
          description: The parameter objects used with the pipeline.
          uniqueItems: false
          x-insertionOrder: false
          type: array
          items:
            $ref: '#/components/schemas/ParameterObject'
        ParameterValues:
          description: The parameter values used with the pipeline.
          uniqueItems: false
          x-insertionOrder: false
          type: array
          items:
            $ref: '#/components/schemas/ParameterValue'
        PipelineObjects:
          description: The objects that define the pipeline. These objects overwrite the existing pipeline definition. Not all objects, fields, and values can be updated. For information about restrictions, see Editing Your Pipeline in the AWS Data Pipeline Developer Guide.
          uniqueItems: false
          x-insertionOrder: false
          type: array
          items:
            $ref: '#/components/schemas/PipelineObject'
        PipelineTags:
          description: A list of arbitrary tags (key-value pairs) to associate with the pipeline, which you can use to control permissions. For more information, see Controlling Access to Pipelines and Resources in the AWS Data Pipeline Developer Guide.
          uniqueItems: false
          x-insertionOrder: false
          type: array
          items:
            $ref: '#/components/schemas/PipelineTag'
        PipelineId:
          type: string
      required:
        - Name
      x-stackql-resource-name: pipeline
      x-stackql-primaryIdentifier:
        - PipelineId
  x-stackQL-resources:
    pipelines:
      name: pipelines
      id: aws.datapipeline.pipelines
      x-cfn-schema-name: Pipeline
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.PipelineId') as pipeline_id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::DataPipeline::Pipeline'
    pipeline:
      name: pipeline
      id: aws.datapipeline.pipeline
      x-cfn-schema-name: Pipeline
      x-type: get
      x-identifiers:
        - PipelineId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Activate') as activate,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.ParameterObjects') as parameter_objects,
              JSON_EXTRACT(Properties, '$.ParameterValues') as parameter_values,
              JSON_EXTRACT(Properties, '$.PipelineObjects') as pipeline_objects,
              JSON_EXTRACT(Properties, '$.PipelineTags') as pipeline_tags,
              JSON_EXTRACT(Properties, '$.PipelineId') as pipeline_id
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::DataPipeline::Pipeline'
