openapi: 3.0.0
info:
  title: Detective
  version: 1.0.0
paths: {}
components:
  schemas:
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      properties:
        Key:
          type: string
          description: 'The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. Valid characters are Unicode letters, digits, white space, and any of the following symbols: _ . : / = + - @ '
          minLength: 1
          maxLength: 128
        Value:
          type: string
          description: 'The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. Valid characters are Unicode letters, digits, white space, and any of the following symbols: _ . : / = + - @ '
          minLength: 0
          maxLength: 256
      additionalProperties: false
    Graph:
      type: object
      properties:
        Arn:
          type: string
          description: The Detective graph ARN
        Tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
      x-stackql-resource-name: graph
      x-stackql-primaryIdentifier:
        - Arn
    MemberInvitation:
      type: object
      properties:
        GraphArn:
          description: The ARN of the graph to which the member account will be invited
          type: string
          pattern: arn:aws(-[\w]+)*:detective:(([a-z]+-)+[0-9]+):[0-9]{12}:graph:[0-9a-f]{32}
        MemberId:
          description: The AWS account ID to be invited to join the graph as a member
          type: string
          pattern: '[0-9]{12}'
        MemberEmailAddress:
          description: The root email address for the account to be invited, for validation. Updating this field has no effect.
          type: string
          pattern: .*@.*
        DisableEmailNotification:
          description: When set to true, invitation emails are not sent to the member accounts. Member accounts must still accept the invitation before they are added to the behavior graph. Updating this field has no effect.
          type: boolean
          default: false
        Message:
          description: A message to be included in the email invitation sent to the invited account. Updating this field has no effect.
          type: string
          minLength: 1
          maxLength: 1000
      required:
        - GraphArn
        - MemberId
        - MemberEmailAddress
      x-stackql-resource-name: member_invitation
      x-stackql-primaryIdentifier:
        - GraphArn
        - MemberId
  x-stackQL-resources:
    graphs:
      name: graphs
      id: aws.detective.graphs
      x-cfn-schema-name: Graph
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Detective::Graph'
    graph:
      name: graph
      id: aws.detective.graph
      x-cfn-schema-name: Graph
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Detective::Graph'
    member_invitations:
      name: member_invitations
      id: aws.detective.member_invitations
      x-cfn-schema-name: MemberInvitation
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.GraphArn') as graph_arn,
              JSON_EXTRACT(Properties, '$.MemberId') as member_id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Detective::MemberInvitation'
    member_invitation:
      name: member_invitation
      id: aws.detective.member_invitation
      x-cfn-schema-name: MemberInvitation
      x-type: get
      x-identifiers:
        - GraphArn
        - MemberId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.GraphArn') as graph_arn,
              JSON_EXTRACT(Properties, '$.MemberId') as member_id,
              JSON_EXTRACT(Properties, '$.MemberEmailAddress') as member_email_address,
              JSON_EXTRACT(Properties, '$.DisableEmailNotification') as disable_email_notification,
              JSON_EXTRACT(Properties, '$.Message') as message
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Detective::MemberInvitation'
