openapi: 3.0.0
info:
  title: DirectoryService
  version: 1.0.0
paths: {}
components:
  schemas:
    VpcSettings:
      x-$comment: Contains VPC information
      type: object
      additionalProperties: false
      properties:
        SubnetIds:
          description: The identifiers of the subnets for the directory servers. The two subnets must be in different Availability Zones. AWS Directory Service specifies a directory server and a DNS server in each of these subnets.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            type: string
        VpcId:
          description: The identifier of the VPC in which to create the directory.
          type: string
      required:
        - VpcId
        - SubnetIds
    MicrosoftAD:
      type: object
      properties:
        Id:
          type: string
        Alias:
          type: string
        DnsIpAddresses:
          type: array
          uniqueItems: false
          items:
            type: string
        CreateAlias:
          type: boolean
        Edition:
          type: string
        EnableSso:
          type: boolean
        Name:
          type: string
        Password:
          type: string
        ShortName:
          type: string
        VpcSettings:
          $ref: '#/components/schemas/VpcSettings'
      required:
        - VpcSettings
        - Name
        - Password
      x-stackql-resource-name: microsoft_ad
      x-stackql-primaryIdentifier:
        - Id
    SimpleAD:
      type: object
      properties:
        DirectoryId:
          description: The unique identifier for a directory.
          type: string
        Alias:
          description: The alias for a directory.
          type: string
        DnsIpAddresses:
          description: The IP addresses of the DNS servers for the directory, such as [ "172.31.3.154", "172.31.63.203" ].
          type: array
          uniqueItems: false
          x-insertionOrder: false
          items:
            type: string
        CreateAlias:
          description: The name of the configuration set.
          type: boolean
        Description:
          description: Description for the directory.
          type: string
        EnableSso:
          description: Whether to enable single sign-on for a Simple Active Directory in AWS.
          type: boolean
        Name:
          description: The fully qualified domain name for the AWS Managed Simple AD directory.
          type: string
        Password:
          description: The password for the default administrative user named Admin.
          type: string
        ShortName:
          description: The NetBIOS name for your domain.
          type: string
        Size:
          description: The size of the directory.
          type: string
        VpcSettings:
          description: VPC settings of the Simple AD directory server in AWS.
          $ref: '#/components/schemas/VpcSettings'
      required:
        - VpcSettings
        - Size
        - Name
      x-stackql-resource-name: simple_ad
      x-stackql-primaryIdentifier:
        - DirectoryId
  x-stackQL-resources:
    microsoft_ads:
      name: microsoft_ads
      id: aws.directoryservice.microsoft_ads
      x-cfn-schema-name: MicrosoftAD
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::DirectoryService::MicrosoftAD'
    microsoft_ad:
      name: microsoft_ad
      id: aws.directoryservice.microsoft_ad
      x-cfn-schema-name: MicrosoftAD
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Alias') as alias,
              JSON_EXTRACT(Properties, '$.DnsIpAddresses') as dns_ip_addresses,
              JSON_EXTRACT(Properties, '$.CreateAlias') as create_alias,
              JSON_EXTRACT(Properties, '$.Edition') as edition,
              JSON_EXTRACT(Properties, '$.EnableSso') as enable_sso,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Password') as password,
              JSON_EXTRACT(Properties, '$.ShortName') as short_name,
              JSON_EXTRACT(Properties, '$.VpcSettings.SubnetIds') as vpc_settings_subnet_ids,
              JSON_EXTRACT(Properties, '$.VpcSettings.VpcId') as vpc_settings_vpc_id
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::DirectoryService::MicrosoftAD'
    simple_ads:
      name: simple_ads
      id: aws.directoryservice.simple_ads
      x-cfn-schema-name: SimpleAD
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.DirectoryId') as directory_id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::DirectoryService::SimpleAD'
    simple_ad:
      name: simple_ad
      id: aws.directoryservice.simple_ad
      x-cfn-schema-name: SimpleAD
      x-type: get
      x-identifiers:
        - DirectoryId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.DirectoryId') as directory_id,
              JSON_EXTRACT(Properties, '$.Alias') as alias,
              JSON_EXTRACT(Properties, '$.DnsIpAddresses') as dns_ip_addresses,
              JSON_EXTRACT(Properties, '$.CreateAlias') as create_alias,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.EnableSso') as enable_sso,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Password') as password,
              JSON_EXTRACT(Properties, '$.ShortName') as short_name,
              JSON_EXTRACT(Properties, '$.Size') as size,
              JSON_EXTRACT(Properties, '$.VpcSettings.SubnetIds') as vpc_settings_subnet_ids,
              JSON_EXTRACT(Properties, '$.VpcSettings.VpcId') as vpc_settings_vpc_id
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::DirectoryService::SimpleAD'
