openapi: 3.0.0
info:
  title: DLM
  version: 1.0.0
paths: {}
components:
  schemas:
    Action:
      type: object
      additionalProperties: false
      properties:
        CrossRegionCopy:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/CrossRegionCopyAction'
        Name:
          type: string
      required:
        - CrossRegionCopy
        - Name
    Parameters:
      type: object
      additionalProperties: false
      properties:
        ExcludeBootVolume:
          type: boolean
        NoReboot:
          type: boolean
        ExcludeDataVolumeTags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
    CrossRegionCopyRule:
      type: object
      additionalProperties: false
      properties:
        TargetRegion:
          type: string
        Target:
          type: string
        DeprecateRule:
          $ref: '#/components/schemas/CrossRegionCopyDeprecateRule'
        Encrypted:
          type: boolean
        CmkArn:
          type: string
        RetainRule:
          $ref: '#/components/schemas/CrossRegionCopyRetainRule'
        CopyTags:
          type: boolean
      required:
        - Encrypted
    EncryptionConfiguration:
      type: object
      additionalProperties: false
      properties:
        Encrypted:
          type: boolean
        CmkArn:
          type: string
      required:
        - Encrypted
    CrossRegionCopyRetainRule:
      type: object
      additionalProperties: false
      properties:
        IntervalUnit:
          type: string
        Interval:
          type: integer
      required:
        - IntervalUnit
        - Interval
    ArchiveRule:
      type: object
      additionalProperties: false
      properties:
        RetainRule:
          $ref: '#/components/schemas/ArchiveRetainRule'
      required:
        - RetainRule
    EventParameters:
      type: object
      additionalProperties: false
      properties:
        DescriptionRegex:
          type: string
        EventType:
          type: string
        SnapshotOwner:
          type: array
          uniqueItems: false
          items:
            type: string
      required:
        - EventType
        - SnapshotOwner
    RetainRule:
      type: object
      additionalProperties: false
      properties:
        IntervalUnit:
          type: string
        Count:
          type: integer
        Interval:
          type: integer
    CrossRegionCopyAction:
      type: object
      additionalProperties: false
      properties:
        Target:
          type: string
        EncryptionConfiguration:
          $ref: '#/components/schemas/EncryptionConfiguration'
        RetainRule:
          $ref: '#/components/schemas/CrossRegionCopyRetainRule'
      required:
        - Target
        - EncryptionConfiguration
    EventSource:
      type: object
      additionalProperties: false
      properties:
        Type:
          type: string
        Parameters:
          $ref: '#/components/schemas/EventParameters'
      required:
        - Type
    DeprecateRule:
      type: object
      additionalProperties: false
      properties:
        IntervalUnit:
          type: string
        Count:
          type: integer
        Interval:
          type: integer
    CrossRegionCopyDeprecateRule:
      type: object
      additionalProperties: false
      properties:
        IntervalUnit:
          type: string
        Interval:
          type: integer
      required:
        - IntervalUnit
        - Interval
    ArchiveRetainRule:
      type: object
      additionalProperties: false
      properties:
        RetentionArchiveTier:
          $ref: '#/components/schemas/RetentionArchiveTier'
      required:
        - RetentionArchiveTier
    CreateRule:
      type: object
      additionalProperties: false
      properties:
        IntervalUnit:
          type: string
        CronExpression:
          type: string
        Times:
          type: array
          uniqueItems: false
          items:
            type: string
        Interval:
          type: integer
        Location:
          type: string
    Schedule:
      type: object
      additionalProperties: false
      properties:
        ShareRules:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/ShareRule'
        DeprecateRule:
          $ref: '#/components/schemas/DeprecateRule'
        TagsToAdd:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
        CreateRule:
          $ref: '#/components/schemas/CreateRule'
        VariableTags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
        FastRestoreRule:
          $ref: '#/components/schemas/FastRestoreRule'
        ArchiveRule:
          $ref: '#/components/schemas/ArchiveRule'
        RetainRule:
          $ref: '#/components/schemas/RetainRule'
        CrossRegionCopyRules:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/CrossRegionCopyRule'
        Name:
          type: string
        CopyTags:
          type: boolean
    FastRestoreRule:
      type: object
      additionalProperties: false
      properties:
        IntervalUnit:
          type: string
        Count:
          type: integer
        AvailabilityZones:
          type: array
          uniqueItems: false
          items:
            type: string
        Interval:
          type: integer
    PolicyDetails:
      type: object
      additionalProperties: false
      properties:
        ResourceTypes:
          type: array
          uniqueItems: false
          items:
            type: string
        Schedules:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Schedule'
        PolicyType:
          type: string
        EventSource:
          $ref: '#/components/schemas/EventSource'
        Parameters:
          $ref: '#/components/schemas/Parameters'
        Actions:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Action'
        TargetTags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
        ResourceLocations:
          type: array
          uniqueItems: false
          items:
            type: string
    RetentionArchiveTier:
      type: object
      additionalProperties: false
      properties:
        IntervalUnit:
          type: string
        Count:
          type: integer
        Interval:
          type: integer
    Tag:
      type: object
      additionalProperties: false
      properties:
        Value:
          type: string
        Key:
          type: string
      required:
        - Value
        - Key
    ShareRule:
      type: object
      additionalProperties: false
      properties:
        TargetAccounts:
          type: array
          uniqueItems: false
          items:
            type: string
        UnshareIntervalUnit:
          type: string
        UnshareInterval:
          type: integer
    LifecyclePolicy:
      type: object
      properties:
        ExecutionRoleArn:
          type: string
        Description:
          type: string
        State:
          type: string
        PolicyDetails:
          $ref: '#/components/schemas/PolicyDetails'
        Id:
          type: string
        Arn:
          type: string
        Tags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
      x-stackql-resource-name: lifecycle_policy
      x-stackql-primaryIdentifier:
        - Id
  x-stackQL-resources:
    lifecycle_policies:
      name: lifecycle_policies
      id: aws.dlm.lifecycle_policies
      x-cfn-schema-name: LifecyclePolicy
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::DLM::LifecyclePolicy'
    lifecycle_policy:
      name: lifecycle_policy
      id: aws.dlm.lifecycle_policy
      x-cfn-schema-name: LifecyclePolicy
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ExecutionRoleArn') as execution_role_arn,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.State') as state,
              JSON_EXTRACT(Properties, '$.PolicyDetails.ResourceTypes') as policy_details_resource_types,
              JSON_EXTRACT(Properties, '$.PolicyDetails.Schedules') as policy_details_schedules,
              JSON_EXTRACT(Properties, '$.PolicyDetails.PolicyType') as policy_details_policy_type,
              JSON_EXTRACT(Properties, '$.PolicyDetails.EventSource') as policy_details_event_source,
              JSON_EXTRACT(Properties, '$.PolicyDetails.Parameters') as policy_details_parameters,
              JSON_EXTRACT(Properties, '$.PolicyDetails.Actions') as policy_details_actions,
              JSON_EXTRACT(Properties, '$.PolicyDetails.TargetTags') as policy_details_target_tags,
              JSON_EXTRACT(Properties, '$.PolicyDetails.ResourceLocations') as policy_details_resource_locations,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::DLM::LifecyclePolicy'
