openapi: 3.0.0
info:
  title: DynamoDB
  version: 1.0.0
paths: {}
components:
  schemas:
    StreamSpecification:
      type: object
      additionalProperties: false
      properties:
        StreamViewType:
          type: string
      required:
        - StreamViewType
    KinesisStreamSpecification:
      type: object
      additionalProperties: false
      properties:
        StreamArn:
          type: string
      required:
        - StreamArn
    KeySchema:
      type: object
      additionalProperties: false
      properties:
        AttributeName:
          type: string
        KeyType:
          type: string
      required:
        - KeyType
        - AttributeName
    PointInTimeRecoverySpecification:
      type: object
      additionalProperties: false
      properties:
        PointInTimeRecoveryEnabled:
          type: boolean
    ReplicaSpecification:
      type: object
      additionalProperties: false
      properties:
        Region:
          type: string
        GlobalSecondaryIndexes:
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/ReplicaGlobalSecondaryIndexSpecification'
        ContributorInsightsSpecification:
          $ref: '#/components/schemas/ContributorInsightsSpecification'
        PointInTimeRecoverySpecification:
          $ref: '#/components/schemas/PointInTimeRecoverySpecification'
        TableClass:
          type: string
        DeletionProtectionEnabled:
          type: boolean
        SSESpecification:
          $ref: '#/components/schemas/ReplicaSSESpecification'
        Tags:
          type: array
          x-insertionOrder: false
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Tag'
        ReadProvisionedThroughputSettings:
          $ref: '#/components/schemas/ReadProvisionedThroughputSettings'
        KinesisStreamSpecification:
          $ref: '#/components/schemas/KinesisStreamSpecification'
      required:
        - Region
    TimeToLiveSpecification:
      type: object
      additionalProperties: false
      properties:
        AttributeName:
          type: string
        Enabled:
          type: boolean
      required:
        - Enabled
        - AttributeName
    LocalSecondaryIndex:
      type: object
      additionalProperties: false
      properties:
        IndexName:
          type: string
        KeySchema:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/KeySchema'
        Projection:
          $ref: '#/components/schemas/Projection'
      required:
        - IndexName
        - Projection
        - KeySchema
    GlobalSecondaryIndex:
      type: object
      additionalProperties: false
      properties:
        IndexName:
          type: string
        KeySchema:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/KeySchema'
        Projection:
          $ref: '#/components/schemas/Projection'
        ProvisionedThroughput:
          $ref: '#/components/schemas/ProvisionedThroughput'
        ContributorInsightsSpecification:
          $ref: '#/components/schemas/ContributorInsightsSpecification'
      required:
        - IndexName
        - Projection
        - KeySchema
    SSESpecification:
      type: object
      additionalProperties: false
      properties:
        KMSMasterKeyId:
          type: string
        SSEEnabled:
          type: boolean
        SSEType:
          type: string
      required:
        - SSEEnabled
    ReplicaSSESpecification:
      type: object
      additionalProperties: false
      properties:
        KMSMasterKeyId:
          type: string
      required:
        - KMSMasterKeyId
    AttributeDefinition:
      type: object
      additionalProperties: false
      properties:
        AttributeName:
          type: string
        AttributeType:
          type: string
      required:
        - AttributeName
        - AttributeType
    Tag:
      type: object
      additionalProperties: false
      properties:
        Key:
          type: string
        Value:
          type: string
      required:
        - Value
        - Key
    Projection:
      type: object
      additionalProperties: false
      properties:
        NonKeyAttributes:
          type: array
          uniqueItems: false
          items:
            type: string
        ProjectionType:
          type: string
    ReplicaGlobalSecondaryIndexSpecification:
      type: object
      additionalProperties: false
      properties:
        IndexName:
          type: string
          minLength: 3
          maxLength: 255
        ContributorInsightsSpecification:
          $ref: '#/components/schemas/ContributorInsightsSpecification'
        ReadProvisionedThroughputSettings:
          $ref: '#/components/schemas/ReadProvisionedThroughputSettings'
      required:
        - IndexName
    ContributorInsightsSpecification:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
      required:
        - Enabled
    ReadProvisionedThroughputSettings:
      type: object
      additionalProperties: false
      properties:
        ReadCapacityUnits:
          type: integer
          minimum: 1
        ReadCapacityAutoScalingSettings:
          $ref: '#/components/schemas/CapacityAutoScalingSettings'
    WriteProvisionedThroughputSettings:
      type: object
      additionalProperties: false
      properties:
        WriteCapacityAutoScalingSettings:
          $ref: '#/components/schemas/CapacityAutoScalingSettings'
    CapacityAutoScalingSettings:
      type: object
      additionalProperties: false
      properties:
        MinCapacity:
          type: integer
          minimum: 1
        MaxCapacity:
          type: integer
          minimum: 1
        SeedCapacity:
          type: integer
          minimum: 1
        TargetTrackingScalingPolicyConfiguration:
          $ref: '#/components/schemas/TargetTrackingScalingPolicyConfiguration'
      required:
        - MinCapacity
        - MaxCapacity
        - TargetTrackingScalingPolicyConfiguration
    TargetTrackingScalingPolicyConfiguration:
      type: object
      additionalProperties: false
      properties:
        DisableScaleIn:
          type: boolean
        ScaleInCooldown:
          type: integer
          minimum: 0
        ScaleOutCooldown:
          type: integer
          minimum: 0
        TargetValue:
          type: number
          format: double
      required:
        - TargetValue
    GlobalTable:
      type: object
      properties:
        Arn:
          type: string
        StreamArn:
          type: string
        AttributeDefinitions:
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/AttributeDefinition'
          minItems: 1
        BillingMode:
          type: string
        GlobalSecondaryIndexes:
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/GlobalSecondaryIndex'
        KeySchema:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/KeySchema'
          minItems: 1
          maxItems: 2
        LocalSecondaryIndexes:
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/LocalSecondaryIndex'
        WriteProvisionedThroughputSettings:
          $ref: '#/components/schemas/WriteProvisionedThroughputSettings'
        Replicas:
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/ReplicaSpecification'
          minItems: 1
        SSESpecification:
          $ref: '#/components/schemas/SSESpecification'
        StreamSpecification:
          $ref: '#/components/schemas/StreamSpecification'
        TableName:
          type: string
        TableId:
          type: string
        TimeToLiveSpecification:
          $ref: '#/components/schemas/TimeToLiveSpecification'
      required:
        - KeySchema
        - AttributeDefinitions
        - Replicas
      x-stackql-resource-name: global_table
      x-stackql-primaryIdentifier:
        - TableName
    DeprecatedKeySchema:
      type: object
      additionalProperties: false
      properties:
        HashKeyElement:
          $ref: '#/components/schemas/DeprecatedHashKeyElement'
      required:
        - HashKeyElement
    DeprecatedHashKeyElement:
      type: object
      additionalProperties: false
      properties:
        AttributeType:
          type: string
        AttributeName:
          type: string
      required:
        - AttributeType
        - AttributeName
    ProvisionedThroughput:
      type: object
      additionalProperties: false
      properties:
        ReadCapacityUnits:
          type: integer
        WriteCapacityUnits:
          type: integer
      required:
        - WriteCapacityUnits
        - ReadCapacityUnits
    ImportSourceSpecification:
      type: object
      additionalProperties: false
      properties:
        S3BucketSource:
          $ref: '#/components/schemas/S3BucketSource'
        InputFormat:
          type: string
        InputFormatOptions:
          $ref: '#/components/schemas/InputFormatOptions'
        InputCompressionType:
          type: string
      required:
        - S3BucketSource
        - InputFormat
    S3BucketSource:
      type: object
      additionalProperties: false
      properties:
        S3BucketOwner:
          type: string
        S3Bucket:
          type: string
        S3KeyPrefix:
          type: string
      required:
        - S3Bucket
    InputFormatOptions:
      type: object
      additionalProperties: false
      properties:
        Csv:
          $ref: '#/components/schemas/Csv'
    Csv:
      type: object
      additionalProperties: false
      properties:
        HeaderList:
          type: array
          uniqueItems: true
          items:
            type: string
        Delimiter:
          type: string
    Table:
      type: object
      properties:
        Arn:
          type: string
        StreamArn:
          type: string
        AttributeDefinitions:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/AttributeDefinition'
        BillingMode:
          type: string
        DeletionProtectionEnabled:
          type: boolean
        GlobalSecondaryIndexes:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/GlobalSecondaryIndex'
        KeySchema:
          oneOf:
            - type: array
              uniqueItems: true
              items:
                $ref: '#/components/schemas/KeySchema'
            - type: object
        LocalSecondaryIndexes:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/LocalSecondaryIndex'
        PointInTimeRecoverySpecification:
          $ref: '#/components/schemas/PointInTimeRecoverySpecification'
        TableClass:
          type: string
        ProvisionedThroughput:
          $ref: '#/components/schemas/ProvisionedThroughput'
        SSESpecification:
          $ref: '#/components/schemas/SSESpecification'
        StreamSpecification:
          $ref: '#/components/schemas/StreamSpecification'
        TableName:
          type: string
        Tags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
        TimeToLiveSpecification:
          $ref: '#/components/schemas/TimeToLiveSpecification'
        ContributorInsightsSpecification:
          $ref: '#/components/schemas/ContributorInsightsSpecification'
        KinesisStreamSpecification:
          $ref: '#/components/schemas/KinesisStreamSpecification'
        ImportSourceSpecification:
          $ref: '#/components/schemas/ImportSourceSpecification'
      required:
        - KeySchema
      x-stackql-resource-name: table
      x-stackql-primaryIdentifier:
        - TableName
  x-stackQL-resources:
    global_tables:
      name: global_tables
      id: aws.dynamodb.global_tables
      x-cfn-schema-name: GlobalTable
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.TableName') as table_name
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::DynamoDB::GlobalTable'
    global_table:
      name: global_table
      id: aws.dynamodb.global_table
      x-cfn-schema-name: GlobalTable
      x-type: get
      x-identifiers:
        - TableName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.StreamArn') as stream_arn,
              JSON_EXTRACT(Properties, '$.AttributeDefinitions') as attribute_definitions,
              JSON_EXTRACT(Properties, '$.BillingMode') as billing_mode,
              JSON_EXTRACT(Properties, '$.GlobalSecondaryIndexes') as global_secondary_indexes,
              JSON_EXTRACT(Properties, '$.KeySchema') as key_schema,
              JSON_EXTRACT(Properties, '$.LocalSecondaryIndexes') as local_secondary_indexes,
              JSON_EXTRACT(Properties, '$.WriteProvisionedThroughputSettings.WriteCapacityAutoScalingSettings') as write_provisioned_throughput_settings_write_capacity_auto_scaling_settings,
              JSON_EXTRACT(Properties, '$.Replicas') as replicas,
              JSON_EXTRACT(Properties, '$.SSESpecification.KMSMasterKeyId') as s_se_specification_km_smaster_key_id,
              JSON_EXTRACT(Properties, '$.SSESpecification.SSEEnabled') as s_se_specification_ss_eenabled,
              JSON_EXTRACT(Properties, '$.SSESpecification.SSEType') as s_se_specification_ss_etype,
              JSON_EXTRACT(Properties, '$.StreamSpecification.StreamViewType') as stream_specification_stream_view_type,
              JSON_EXTRACT(Properties, '$.TableName') as table_name,
              JSON_EXTRACT(Properties, '$.TableId') as table_id,
              JSON_EXTRACT(Properties, '$.TimeToLiveSpecification.AttributeName') as time_to_live_specification_attribute_name,
              JSON_EXTRACT(Properties, '$.TimeToLiveSpecification.Enabled') as time_to_live_specification_enabled
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::DynamoDB::GlobalTable'
    tables:
      name: tables
      id: aws.dynamodb.tables
      x-cfn-schema-name: Table
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.TableName') as table_name
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::DynamoDB::Table'
    table:
      name: table
      id: aws.dynamodb.table
      x-cfn-schema-name: Table
      x-type: get
      x-identifiers:
        - TableName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.StreamArn') as stream_arn,
              JSON_EXTRACT(Properties, '$.AttributeDefinitions') as attribute_definitions,
              JSON_EXTRACT(Properties, '$.BillingMode') as billing_mode,
              JSON_EXTRACT(Properties, '$.DeletionProtectionEnabled') as deletion_protection_enabled,
              JSON_EXTRACT(Properties, '$.GlobalSecondaryIndexes') as global_secondary_indexes,
              JSON_EXTRACT(Properties, '$.KeySchema') as key_schema,
              JSON_EXTRACT(Properties, '$.LocalSecondaryIndexes') as local_secondary_indexes,
              JSON_EXTRACT(Properties, '$.PointInTimeRecoverySpecification.PointInTimeRecoveryEnabled') as point_in_time_recovery_specification_point_in_time_recovery_enabled,
              JSON_EXTRACT(Properties, '$.TableClass') as table_class,
              JSON_EXTRACT(Properties, '$.ProvisionedThroughput.ReadCapacityUnits') as provisioned_throughput_read_capacity_units,
              JSON_EXTRACT(Properties, '$.ProvisionedThroughput.WriteCapacityUnits') as provisioned_throughput_write_capacity_units,
              JSON_EXTRACT(Properties, '$.SSESpecification.KMSMasterKeyId') as s_se_specification_km_smaster_key_id,
              JSON_EXTRACT(Properties, '$.SSESpecification.SSEEnabled') as s_se_specification_ss_eenabled,
              JSON_EXTRACT(Properties, '$.SSESpecification.SSEType') as s_se_specification_ss_etype,
              JSON_EXTRACT(Properties, '$.StreamSpecification.StreamViewType') as stream_specification_stream_view_type,
              JSON_EXTRACT(Properties, '$.TableName') as table_name,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.TimeToLiveSpecification.AttributeName') as time_to_live_specification_attribute_name,
              JSON_EXTRACT(Properties, '$.TimeToLiveSpecification.Enabled') as time_to_live_specification_enabled,
              JSON_EXTRACT(Properties, '$.ContributorInsightsSpecification.Enabled') as contributor_insights_specification_enabled,
              JSON_EXTRACT(Properties, '$.KinesisStreamSpecification.StreamArn') as kinesis_stream_specification_stream_arn,
              JSON_EXTRACT(Properties, '$.ImportSourceSpecification.S3BucketSource') as import_source_specification_s3_bucket_source,
              JSON_EXTRACT(Properties, '$.ImportSourceSpecification.InputFormat') as import_source_specification_input_format,
              JSON_EXTRACT(Properties, '$.ImportSourceSpecification.InputFormatOptions') as import_source_specification_input_format_options,
              JSON_EXTRACT(Properties, '$.ImportSourceSpecification.InputCompressionType') as import_source_specification_input_compression_type
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::DynamoDB::Table'
