openapi: 3.0.0
info:
  title: EMRContainers
  version: 1.0.0
paths: {}
components:
  schemas:
    ContainerProvider:
      type: object
      additionalProperties: false
      properties:
        Type:
          description: The type of the container provider
          type: string
        Id:
          description: The ID of the container cluster
          type: string
          minLength: 1
          maxLength: 100
          pattern: ^[0-9A-Za-z][A-Za-z0-9\-_]*
        Info:
          $ref: '#/components/schemas/ContainerInfo'
      required:
        - Type
        - Id
        - Info
    ContainerInfo:
      type: object
      additionalProperties: false
      properties:
        EksInfo:
          $ref: '#/components/schemas/EksInfo'
      required:
        - EksInfo
    EksInfo:
      type: object
      additionalProperties: false
      properties:
        Namespace:
          type: string
          minLength: 1
          maxLength: 63
          pattern: '[a-z0-9]([-a-z0-9]*[a-z0-9])?'
      required:
        - Namespace
    Tag:
      description: An arbitrary set of tags (key-value pairs) for this virtual cluster.
      type: object
      additionalProperties: false
      properties:
        Key:
          description: 'The key name of the tag. You can specify a value that is 1 to 127 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          type: string
        Value:
          description: 'The value for the tag. You can specify a value that is 1 to 255 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          type: string
      required:
        - Value
        - Key
    VirtualCluster:
      type: object
      properties:
        Arn:
          type: string
        ContainerProvider:
          description: Container provider of the virtual cluster.
          $ref: '#/components/schemas/ContainerProvider'
        Id:
          description: Id of the virtual cluster.
          type: string
          minLength: 1
          maxLength: 64
        Name:
          description: Name of the virtual cluster.
          type: string
          minLength: 1
          maxLength: 64
          pattern: '[\.\-_/#A-Za-z0-9]+'
        Tags:
          description: An array of key-value pairs to apply to this virtual cluster.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - Name
        - ContainerProvider
      x-stackql-resource-name: virtual_cluster
      x-stackql-primaryIdentifier:
        - Id
  x-stackQL-resources:
    virtual_clusters:
      name: virtual_clusters
      id: aws.emrcontainers.virtual_clusters
      x-cfn-schema-name: VirtualCluster
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::EMRContainers::VirtualCluster'
    virtual_cluster:
      name: virtual_cluster
      id: aws.emrcontainers.virtual_cluster
      x-cfn-schema-name: VirtualCluster
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.ContainerProvider.Type') as container_provider_type,
              JSON_EXTRACT(Properties, '$.ContainerProvider.Id') as container_provider_id,
              JSON_EXTRACT(Properties, '$.ContainerProvider.Info') as container_provider_info,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::EMRContainers::VirtualCluster'
