openapi: 3.0.0
info:
  title: FIS
  version: 1.0.0
paths: {}
components:
  schemas:
    ExperimentTemplateId:
      type: string
    ExperimentTemplateDescription:
      type: string
      description: A description for the experiment template.
      maxLength: 512
    StopConditionSource:
      type: string
      maxLength: 64
    StopConditionValue:
      type: string
      minLength: 20
      maxLength: 2048
    ExperimentTemplateStopCondition:
      type: object
      additionalProperties: false
      properties:
        Source:
          $ref: '#/components/schemas/StopConditionSource'
        Value:
          $ref: '#/components/schemas/StopConditionValue'
      required:
        - Source
    ExperimentTemplateStopConditionList:
      type: array
      description: One or more stop conditions.
      items:
        $ref: '#/components/schemas/ExperimentTemplateStopCondition'
    ResourceType:
      type: string
      description: The AWS resource type. The resource type must be supported for the specified action.
      maxLength: 64
    ResourceArn:
      type: string
      minLength: 20
      maxLength: 2048
    ResourceArnList:
      type: array
      description: The Amazon Resource Names (ARNs) of the target resources.
      items:
        $ref: '#/components/schemas/ResourceArn'
    ExperimentTemplateTargetSelectionMode:
      type: string
      description: Scopes the identified resources to a specific number of the resources at random, or a percentage of the resources.
      maxLength: 64
    ExperimentTemplateTargetFilterPath:
      type: string
      description: The attribute path for the filter.
      maxLength: 256
    ExperimentTemplateTargetFilterValue:
      type: string
      maxLength: 128
    ExperimentTemplateTargetFilterValues:
      type: array
      description: The attribute values for the filter.
      items:
        $ref: '#/components/schemas/ExperimentTemplateTargetFilterValue'
    ExperimentTemplateTargetFilter:
      type: object
      description: Describes a filter used for the target resource input in an experiment template.
      additionalProperties: false
      properties:
        Path:
          $ref: '#/components/schemas/ExperimentTemplateTargetFilterPath'
        Values:
          $ref: '#/components/schemas/ExperimentTemplateTargetFilterValues'
      required:
        - Path
        - Values
    ExperimentTemplateTargetFilterList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentTemplateTargetFilter'
    ExperimentTemplateTarget:
      type: object
      description: Specifies a target for an experiment.
      additionalProperties: false
      properties:
        ResourceType:
          $ref: '#/components/schemas/ResourceType'
        ResourceArns:
          $ref: '#/components/schemas/ResourceArnList'
        ResourceTags:
          type: object
          x-patternProperties:
            .{1,128}:
              type: string
              maxLength: 256
          additionalProperties: false
        Parameters:
          type: object
          x-patternProperties:
            .{1,64}:
              type: string
              maxLength: 1024
          additionalProperties: false
        Filters:
          $ref: '#/components/schemas/ExperimentTemplateTargetFilterList'
        SelectionMode:
          $ref: '#/components/schemas/ExperimentTemplateTargetSelectionMode'
      required:
        - ResourceType
        - SelectionMode
    ExperimentTemplateTargetMap:
      type: object
      description: The targets for the experiment.
      x-patternProperties:
        .{1,64}:
          $ref: '#/components/schemas/ExperimentTemplateTarget'
      additionalProperties: false
    ActionId:
      type: string
      description: The ID of the action.
      maxLength: 64
    ExperimentTemplateActionItemDescription:
      type: string
      description: A description for the action.
      maxLength: 512
    ExperimentTemplateActionItemParameter:
      type: string
      maxLength: 1024
    ExperimentTemplateActionItemTarget:
      type: string
      maxLength: 64
    ExperimentTemplateActionItemStartAfter:
      type: string
      maxLength: 64
    ExperimentTemplateActionItemStartAfterList:
      type: array
      description: The names of the actions that must be completed before the current action starts.
      items:
        $ref: '#/components/schemas/ExperimentTemplateActionItemStartAfter'
    ExperimentTemplateAction:
      type: object
      description: Specifies an action for the experiment template.
      additionalProperties: false
      properties:
        ActionId:
          $ref: '#/components/schemas/ActionId'
        Description:
          $ref: '#/components/schemas/ExperimentTemplateActionItemDescription'
        Parameters:
          type: object
          description: The parameters for the action, if applicable.
          x-patternProperties:
            .{1,64}:
              $ref: '#/components/schemas/ExperimentTemplateActionItemParameter'
          additionalProperties: false
        Targets:
          type: object
          description: One or more targets for the action.
          x-patternProperties:
            .{1,64}:
              $ref: '#/components/schemas/ExperimentTemplateActionItemTarget'
          additionalProperties: false
        StartAfter:
          $ref: '#/components/schemas/ExperimentTemplateActionItemStartAfterList'
      required:
        - ActionId
    ExperimentTemplateActionMap:
      type: object
      description: The actions for the experiment.
      x-patternProperties:
        '[\S]{1,64}':
          $ref: '#/components/schemas/ExperimentTemplateAction'
      additionalProperties: false
    ExperimentTemplateLogConfiguration:
      type: object
      additionalProperties: false
      properties:
        CloudWatchLogsConfiguration:
          type: object
          additionalProperties: false
          properties:
            LogGroupArn:
              type: string
              minLength: 20
              maxLength: 2048
          required:
            - LogGroupArn
        S3Configuration:
          type: object
          additionalProperties: false
          properties:
            BucketName:
              type: string
              minLength: 3
              maxLength: 63
            Prefix:
              type: string
              minLength: 1
              maxLength: 1024
          required:
            - BucketName
        LogSchemaVersion:
          type: integer
          minimum: 1
      required:
        - LogSchemaVersion
    RoleArn:
      type: string
      description: The Amazon Resource Name (ARN) of an IAM role that grants the AWS FIS service permission to perform service actions on your behalf.
      maxLength: 1224
    ExperimentTemplate:
      type: object
      properties:
        Id:
          $ref: '#/components/schemas/ExperimentTemplateId'
        Description:
          $ref: '#/components/schemas/ExperimentTemplateDescription'
        Targets:
          $ref: '#/components/schemas/ExperimentTemplateTargetMap'
        Actions:
          $ref: '#/components/schemas/ExperimentTemplateActionMap'
        StopConditions:
          $ref: '#/components/schemas/ExperimentTemplateStopConditionList'
        LogConfiguration:
          $ref: '#/components/schemas/ExperimentTemplateLogConfiguration'
        RoleArn:
          $ref: '#/components/schemas/RoleArn'
        Tags:
          type: object
          x-patternProperties:
            .{1,128}:
              type: string
              maxLength: 256
          additionalProperties: false
      required:
        - Description
        - StopConditions
        - Targets
        - RoleArn
        - Tags
      x-stackql-resource-name: experiment_template
      x-stackql-primaryIdentifier:
        - Id
  x-stackQL-resources:
    experiment_templates:
      name: experiment_templates
      id: aws.fis.experiment_templates
      x-cfn-schema-name: ExperimentTemplate
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::FIS::ExperimentTemplate'
    experiment_template:
      name: experiment_template
      id: aws.fis.experiment_template
      x-cfn-schema-name: ExperimentTemplate
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.LogConfiguration.CloudWatchLogsConfiguration') as log_configuration_cloud_watch_logs_configuration,
              JSON_EXTRACT(Properties, '$.LogConfiguration.S3Configuration') as log_configuration_s3_configuration,
              JSON_EXTRACT(Properties, '$.LogConfiguration.LogSchemaVersion') as log_configuration_log_schema_version,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::FIS::ExperimentTemplate'
