openapi: 3.0.0
info:
  title: Forecast
  version: 1.0.0
paths: {}
components:
  schemas:
    Attributes:
      type: array
      x-insertionOrder: true
      items:
        type: object
        additionalProperties: false
        properties:
          AttributeName:
            description: Name of the dataset field
            type: string
            pattern: ^[a-zA-Z][a-zA-Z0-9_]*
          AttributeType:
            description: Data type of the field
            type: string
            enum:
              - string
              - integer
              - float
              - timestamp
              - geolocation
      minItems: 1
      maxItems: 100
    KmsKeyArn:
      description: KMS key used to encrypt the Dataset data
      type: string
      maxLength: 256
      pattern: arn:aws[-a-z]*:kms:.*:key/.*
    RoleArn:
      description: The ARN of the IAM role that Amazon Forecast can assume to access the AWS KMS key.
      type: string
      maxLength: 256
      pattern: ^[a-zA-Z0-9\-\_\.\/\:]+$
    Key:
      type: string
      description: 'The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
      minLength: 1
      maxLength: 128
    Value:
      type: string
      description: 'The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
      minLength: 0
      maxLength: 256
    Dataset:
      type: object
      properties:
        Arn:
          type: string
          maxLength: 256
          pattern: ^[a-zA-Z0-9\-\_\.\/\:]+$
        DatasetName:
          description: A name for the dataset
          type: string
          minLength: 1
          maxLength: 63
          pattern: ^[a-zA-Z][a-zA-Z0-9_]*
        DatasetType:
          description: The dataset type
          type: string
          enum:
            - TARGET_TIME_SERIES
            - RELATED_TIME_SERIES
            - ITEM_METADATA
        DataFrequency:
          description: Frequency of data collection. This parameter is required for RELATED_TIME_SERIES
          type: string
          pattern: ^Y|M|W|D|H|30min|15min|10min|5min|1min$
        Domain:
          description: The domain associated with the dataset
          type: string
          enum:
            - RETAIL
            - CUSTOM
            - INVENTORY_PLANNING
            - EC2_CAPACITY
            - WORK_FORCE
            - WEB_TRAFFIC
            - METRICS
        EncryptionConfig:
          type: object
          additionalProperties: false
          properties:
            KmsKeyArn:
              $ref: '#/components/schemas/KmsKeyArn'
            RoleArn:
              $ref: '#/components/schemas/RoleArn'
        Schema:
          type: object
          additionalProperties: false
          properties:
            Attributes:
              $ref: '#/components/schemas/Attributes'
        Tags:
          type: array
          x-insertionOrder: true
          items:
            description: A key-value pair to associate with a resource.
            type: object
            properties:
              Key:
                $ref: '#/components/schemas/Key'
              Value:
                $ref: '#/components/schemas/Value'
            required:
              - Key
              - Value
            additionalProperties: false
          minItems: 0
          maxItems: 200
      required:
        - DatasetName
        - DatasetType
        - Domain
        - Schema
      x-stackql-resource-name: dataset
      description: Resource Type Definition for AWS::Forecast::Dataset
      x-type-name: AWS::Forecast::Dataset
      x-stackql-primary-identifier:
        - Arn
      x-create-only-properties:
        - DatasetName
      x-read-only-properties:
        - Arn
      x-required-properties:
        - DatasetName
        - DatasetType
        - Domain
        - Schema
      x-required-permissions:
        create:
          - forecast:CreateDataset
        read:
          - forecast:DescribeDataset
        delete:
          - forecast:DeleteDataset
        list:
          - forecast:ListDatasets
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      properties:
        Key:
          type: string
          description: 'The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          minLength: 1
          maxLength: 128
        Value:
          type: string
          description: 'The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          minLength: 0
          maxLength: 256
      required:
        - Key
        - Value
      additionalProperties: false
    Arn:
      type: string
      maxLength: 256
      pattern: ^[a-zA-Z0-9\-\_\.\/\:]+$
    MaxResults:
      description: The number of items to return in the response.
      type: integer
      minimum: 1
      maximum: 100
    NextToken:
      description: If the result of the previous request was truncated, the response includes a NextToken. To retrieve the next set of results, use the token in the next request. Tokens expire after 24 hours.
      type: string
      minLength: 1
      maxLength: 3000
    DatasetGroup:
      type: object
      properties:
        DatasetArns:
          description: An array of Amazon Resource Names (ARNs) of the datasets that you want to include in the dataset group.
          type: array
          items:
            $ref: '#/components/schemas/Arn'
          x-insertionOrder: true
        DatasetGroupName:
          description: A name for the dataset group.
          type: string
          pattern: ^[a-zA-Z][a-zA-Z0-9_]*
          minLength: 1
          maxLength: 63
        Domain:
          description: The domain associated with the dataset group. When you add a dataset to a dataset group, this value and the value specified for the Domain parameter of the CreateDataset operation must match.
          type: string
          enum:
            - RETAIL
            - CUSTOM
            - INVENTORY_PLANNING
            - EC2_CAPACITY
            - WORK_FORCE
            - WEB_TRAFFIC
            - METRICS
        Tags:
          description: The tags of Application Insights application.
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          minItems: 0
          maxItems: 200
          x-insertionOrder: true
        DatasetGroupArn:
          description: The Amazon Resource Name (ARN) of the dataset group to delete.
          type: string
          maxLength: 256
          pattern: ^[a-zA-Z0-9\-\_\.\/\:]+$
      required:
        - DatasetGroupName
        - Domain
      x-stackql-resource-name: dataset_group
      description: Represents a dataset group that holds a collection of related datasets
      x-type-name: AWS::Forecast::DatasetGroup
      x-stackql-primary-identifier:
        - DatasetGroupArn
      x-create-only-properties:
        - DatasetGroupName
      x-read-only-properties:
        - DatasetGroupArn
      x-required-properties:
        - DatasetGroupName
        - Domain
      x-taggable: true
      x-required-permissions:
        create:
          - forecast:CreateDatasetGroup
        read:
          - forecast:DescribeDatasetGroup
        update:
          - forecast:UpdateDatasetGroup
        delete:
          - forecast:DeleteDatasetGroup
        list:
          - forecast:ListDatasetGroups
  x-stackQL-resources:
    datasets:
      name: datasets
      id: aws.forecast.datasets
      x-cfn-schema-name: Dataset
      x-type: list
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Forecast::Dataset'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Arn') as arn
                FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Forecast::Dataset'
                AND region = 'us-east-1'
    dataset:
      name: dataset
      id: aws.forecast.dataset
      x-cfn-schema-name: Dataset
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.DatasetName') as dataset_name,
              JSON_EXTRACT(Properties, '$.DatasetType') as dataset_type,
              JSON_EXTRACT(Properties, '$.DataFrequency') as data_frequency,
              JSON_EXTRACT(Properties, '$.Domain') as domain,
              JSON_EXTRACT(Properties, '$.EncryptionConfig') as encryption_config,
              JSON_EXTRACT(Properties, '$.Schema') as _schema,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Forecast::Dataset'
              AND data__Identifier = '<Arn>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'DatasetName') as dataset_name,
                json_extract_path_text(Properties, 'DatasetType') as dataset_type,
                json_extract_path_text(Properties, 'DataFrequency') as data_frequency,
                json_extract_path_text(Properties, 'Domain') as domain,
                json_extract_path_text(Properties, 'EncryptionConfig') as encryption_config,
                json_extract_path_text(Properties, 'Schema') as _schema,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Forecast::Dataset'
                AND data__Identifier = '<Arn>'
                AND region = 'us-east-1'
    dataset_groups:
      name: dataset_groups
      id: aws.forecast.dataset_groups
      x-cfn-schema-name: DatasetGroup
      x-type: list
      x-identifiers:
        - DatasetGroupArn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.DatasetGroupArn') as dataset_group_arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Forecast::DatasetGroup'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'DatasetGroupArn') as dataset_group_arn
                FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Forecast::DatasetGroup'
                AND region = 'us-east-1'
    dataset_group:
      name: dataset_group
      id: aws.forecast.dataset_group
      x-cfn-schema-name: DatasetGroup
      x-type: get
      x-identifiers:
        - DatasetGroupArn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.DatasetArns') as dataset_arns,
              JSON_EXTRACT(Properties, '$.DatasetGroupName') as dataset_group_name,
              JSON_EXTRACT(Properties, '$.Domain') as domain,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.DatasetGroupArn') as dataset_group_arn
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Forecast::DatasetGroup'
              AND data__Identifier = '<DatasetGroupArn>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'DatasetArns') as dataset_arns,
                json_extract_path_text(Properties, 'DatasetGroupName') as dataset_group_name,
                json_extract_path_text(Properties, 'Domain') as domain,
                json_extract_path_text(Properties, 'Tags') as tags,
                json_extract_path_text(Properties, 'DatasetGroupArn') as dataset_group_arn
                FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Forecast::DatasetGroup'
                AND data__Identifier = '<DatasetGroupArn>'
                AND region = 'us-east-1'
