openapi: 3.0.0
info:
  version: "2017-09-29"
  title: AWS IoT Jobs Data Plane
  description: AWS IoT Jobs Data Plane
  x-serviceName: iot-jobs-data
  x-serviceAlias: iot_jobs_data
  x-protocol: rest-json
  x-apiVersion: "2017-09-29"
  x-endpointPrefix: data.jobs.iot
servers:
  - url: https://data.jobs.iot.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for iot-jobs-data
paths:
  /things/{thing_name}/jobs/{job_id}:
    get:
      operationId: DescribeJobExecution
      description: Gets details of a job execution. Requires permission to access the DescribeJobExecution action.
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/DescribeJobExecutionJobId"
          description: The unique identifier assigned to this job when it was created.
        - name: thing_name
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/ThingName"
          description: The thing name associated with the device the job execution is running on.
        - name: includeJobDocument
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/IncludeJobDocument"
          description: Optional. Unless set to false, the response contains the job document. The default is true.
        - name: executionNumber
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/ExecutionNumber"
          description: Optional. A number that identifies a particular job execution on a particular device. If not specified, the latest job execution is returned.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DescribeJobExecutionResponse"
    post:
      operationId: UpdateJobExecution
      description: Updates the status of a job execution. Requires permission to access the UpdateJobExecution action.
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/JobId"
          description: The unique identifier assigned to this job when it was created.
        - name: thing_name
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/ThingName"
          description: The name of the thing associated with the device.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  $ref: "#/components/schemas/JobExecutionStatus"
                statusDetails:
                  $ref: "#/components/schemas/DetailsMap"
                stepTimeoutInMinutes:
                  $ref: "#/components/schemas/StepTimeoutInMinutes"
                expectedVersion:
                  $ref: "#/components/schemas/ExpectedVersion"
                includeJobExecutionState:
                  $ref: "#/components/schemas/IncludeExecutionState"
                includeJobDocument:
                  $ref: "#/components/schemas/IncludeJobDocument"
                executionNumber:
                  $ref: "#/components/schemas/ExecutionNumber"
              required:
                - status
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateJobExecutionResponse"
  /things/{thing_name}/jobs:
    get:
      operationId: GetPendingJobExecutions
      description: Gets the list of all jobs for a thing that are not in a terminal status. Requires permission to access the GetPendingJobExecutions action.
      parameters:
        - name: thing_name
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/ThingName"
          description: The name of the thing that is executing the job.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPendingJobExecutionsResponse"
  /command-executions:
    post:
      operationId: StartCommandExecution
      description: Using the command created with the CreateCommand API, start a command execution on a specific device.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                targetArn:
                  $ref: "#/components/schemas/TargetArn"
                commandArn:
                  $ref: "#/components/schemas/CommandArn"
                parameters:
                  $ref: "#/components/schemas/CommandExecutionParameterMap"
                executionTimeoutSeconds:
                  $ref: "#/components/schemas/CommandExecutionTimeoutInSeconds"
                clientToken:
                  $ref: "#/components/schemas/ClientRequestTokenV2"
              required:
                - targetArn
                - commandArn
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StartCommandExecutionResponse"
  /things/{thing_name}/jobs/$next:
    put:
      operationId: StartNextPendingJobExecution
      description: Gets and starts the next pending (status IN_PROGRESS or QUEUED) job execution for a thing. Requires permission to access the StartNextPendingJobExecution action.
      parameters:
        - name: thing_name
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/ThingName"
          description: The name of the thing associated with the device.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                statusDetails:
                  $ref: "#/components/schemas/DetailsMap"
                stepTimeoutInMinutes:
                  $ref: "#/components/schemas/StepTimeoutInMinutes"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StartNextPendingJobExecutionResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    DescribeJobExecutionJobId:
      type: string
      pattern: "[a-zA-Z0-9_-]+|^\\$next"
    ThingName:
      type: string
      minLength: 1
      maxLength: 128
      pattern: "[a-zA-Z0-9:_-]+"
    IncludeJobDocument:
      type: boolean
    ExecutionNumber:
      type: integer
      format: int64
    DescribeJobExecutionResponse:
      type: object
      properties:
        execution:
          $ref: "#/components/schemas/JobExecution"
          description: Contains data about a job execution.
    JobExecution:
      description: Contains data about a job execution.
      type: object
      properties:
        jobId:
          $ref: "#/components/schemas/JobId"
          description: The unique identifier you assigned to this job when it was created.
        thingName:
          $ref: "#/components/schemas/ThingName"
          description: The name of the thing that is executing the job.
        status:
          $ref: "#/components/schemas/JobExecutionStatus"
          description: 'The status of the job execution. Can be one of: "QUEUED", "IN_PROGRESS", "FAILED", "SUCCESS", "CANCELED", "TIMED_OUT", "REJECTED", or "REMOVED".'
        statusDetails:
          type: object
          properties: {}
          description: A collection of name/value pairs that describe the status of the job execution. The maximum length of the value in the name/value pair is 1,024 characters.
        queuedAt:
          $ref: "#/components/schemas/QueuedAt"
          description: The time, in seconds since the epoch, when the job execution was enqueued.
        startedAt:
          $ref: "#/components/schemas/StartedAt"
          description: The time, in seconds since the epoch, when the job execution was started.
        lastUpdatedAt:
          $ref: "#/components/schemas/LastUpdatedAt"
          description: The time, in seconds since the epoch, when the job execution was last updated.
        approximateSecondsBeforeTimedOut:
          $ref: "#/components/schemas/ApproximateSecondsBeforeTimedOut"
          description: The estimated number of seconds that remain before the job execution status will be changed to TIMED_OUT. The actual job execution timeout can occur up to 60 seconds later than the estimated duration.
        versionNumber:
          $ref: "#/components/schemas/VersionNumber"
          description: The version of the job execution. Job execution versions are incremented each time they are updated by a device.
        executionNumber:
          $ref: "#/components/schemas/ExecutionNumber"
          description: A number that identifies a particular job execution on a particular device. It can be used later in commands that return or update job execution information.
        jobDocument:
          $ref: "#/components/schemas/JobDocument"
          description: The content of the job document.
    JobId:
      type: string
      minLength: 1
      maxLength: 64
      pattern: "[a-zA-Z0-9_-]+"
    JobExecutionStatus:
      type: string
      enum:
        - QUEUED
        - IN_PROGRESS
        - SUCCEEDED
        - FAILED
        - TIMED_OUT
        - REJECTED
        - REMOVED
        - CANCELED
    QueuedAt:
      type: integer
      format: int64
    StartedAt:
      type: integer
      format: int64
    LastUpdatedAt:
      type: integer
      format: int64
    ApproximateSecondsBeforeTimedOut:
      type: integer
      format: int64
    VersionNumber:
      type: integer
      format: int64
    JobDocument:
      type: string
      maxLength: 32768
    GetPendingJobExecutionsResponse:
      type: object
      properties:
        inProgressJobs:
          $ref: "#/components/schemas/JobExecutionSummaryList"
          description: A list of JobExecutionSummary objects with status IN_PROGRESS.
        queuedJobs:
          $ref: "#/components/schemas/JobExecutionSummaryList"
          description: A list of JobExecutionSummary objects with status QUEUED.
    JobExecutionSummaryList:
      type: array
      items:
        $ref: "#/components/schemas/JobExecutionSummary"
    JobExecutionSummary:
      description: Contains a subset of information about a job execution.
      type: object
      properties:
        jobId:
          $ref: "#/components/schemas/JobId"
          description: The unique identifier you assigned to this job when it was created.
        queuedAt:
          $ref: "#/components/schemas/QueuedAt"
          description: The time, in seconds since the epoch, when the job execution was enqueued.
        startedAt:
          $ref: "#/components/schemas/StartedAt"
          description: The time, in seconds since the epoch, when the job execution started.
        lastUpdatedAt:
          $ref: "#/components/schemas/LastUpdatedAt"
          description: The time, in seconds since the epoch, when the job execution was last updated.
        versionNumber:
          $ref: "#/components/schemas/VersionNumber"
          description: The version of the job execution. Job execution versions are incremented each time IoT Jobs receives an update from a device.
        executionNumber:
          $ref: "#/components/schemas/ExecutionNumber"
          description: A number that identifies a particular job execution on a particular device.
    TargetArn:
      type: string
      maxLength: 2048
    CommandArn:
      type: string
    CommandExecutionParameterMap:
      type: object
      properties: {}
    CommandExecutionTimeoutInSeconds:
      type: integer
      format: int64
      minimum: 1
    ClientRequestTokenV2:
      type: string
      minLength: 1
      maxLength: 64
      pattern: ^[\x21-\x7E]+$
    StartCommandExecutionResponse:
      type: object
      properties:
        executionId:
          $ref: "#/components/schemas/CommandExecutionId"
          description: A unique identifier for the command execution.
    CommandExecutionId:
      type: string
      minLength: 1
      maxLength: 64
      pattern: "[a-zA-Z0-9_-]+"
    DetailsMap:
      type: object
      properties: {}
    StepTimeoutInMinutes:
      type: integer
      format: int64
    StartNextPendingJobExecutionResponse:
      type: object
      properties:
        execution:
          $ref: "#/components/schemas/JobExecution"
          description: A JobExecution object.
    ExpectedVersion:
      type: integer
      format: int64
    IncludeExecutionState:
      type: boolean
    UpdateJobExecutionResponse:
      type: object
      properties:
        executionState:
          $ref: "#/components/schemas/JobExecutionState"
          description: A JobExecutionState object.
        jobDocument:
          $ref: "#/components/schemas/JobDocument"
          description: The contents of the Job Documents.
    JobExecutionState:
      description: Contains data about the state of a job execution.
      type: object
      properties:
        status:
          $ref: "#/components/schemas/JobExecutionStatus"
          description: 'The status of the job execution. Can be one of: "QUEUED", "IN_PROGRESS", "FAILED", "SUCCESS", "CANCELED", "TIMED_OUT", "REJECTED", or "REMOVED".'
        statusDetails:
          type: object
          properties: {}
          description: A collection of name/value pairs that describe the status of the job execution. The maximum length of the value in the name/value pair is 1,024 characters.
        versionNumber:
          $ref: "#/components/schemas/VersionNumber"
          description: The version of the job execution. Job execution versions are incremented each time they are updated by a device.
  x-stackQL-resources:
    job_executions:
      id: aws.iot_jobs_data.job_executions
      name: job_executions
      title: job_executions
      methods:
        describe_job_execution:
          operation:
            $ref: "#/paths/~1things~1{thing_name}~1jobs~1{job_id}/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.execution
          request:
            nativeCasing: pascal
        update_job_execution:
          operation:
            $ref: "#/paths/~1things~1{thing_name}~1jobs~1{job_id}/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/job_executions/methods/describe_job_execution"
        insert: []
        update:
          - $ref: "#/components/x-stackQL-resources/job_executions/methods/update_job_execution"
        delete: []
    pending_job_executions:
      id: aws.iot_jobs_data.pending_job_executions
      name: pending_job_executions
      title: pending_job_executions
      methods:
        get_pending_job_executions:
          operation:
            $ref: "#/paths/~1things~1{thing_name}~1jobs/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/pending_job_executions/methods/get_pending_job_executions"
        insert: []
        update: []
        delete: []
