openapi: 3.0.0
info:
  title: IVSChat
  version: 1.0.0
paths: {}
components:
  schemas:
    DestinationConfiguration:
      description: Destination configuration for IVS Chat logging.
      type: object
      additionalProperties: false
      properties:
        CloudWatchLogs:
          $ref: '#/components/schemas/CloudWatchLogsDestinationConfiguration'
        Firehose:
          $ref: '#/components/schemas/FirehoseDestinationConfiguration'
        S3:
          $ref: '#/components/schemas/S3DestinationConfiguration'
      required: []
    CloudWatchLogsDestinationConfiguration:
      description: CloudWatch destination configuration for IVS Chat logging.
      type: object
      additionalProperties: false
      properties:
        LogGroupName:
          description: Name of the Amazon CloudWatch Logs log group where chat activity will be logged.
          type: string
          pattern: ^[\.\-_/#A-Za-z0-9]+$
          minLength: 1
          maxLength: 512
      required:
        - LogGroupName
    FirehoseDestinationConfiguration:
      description: Kinesis Firehose destination configuration for IVS Chat logging.
      type: object
      additionalProperties: false
      properties:
        DeliveryStreamName:
          description: Name of the Amazon Kinesis Firehose delivery stream where chat activity will be logged.
          type: string
          pattern: ^[a-zA-Z0-9_.-]+$
          minLength: 1
          maxLength: 64
      required:
        - DeliveryStreamName
    S3DestinationConfiguration:
      description: S3 destination configuration for IVS Chat logging.
      type: object
      additionalProperties: false
      properties:
        BucketName:
          description: Name of the Amazon S3 bucket where chat activity will be logged.
          type: string
          pattern: ^[a-z0-9-.]+$
          minLength: 3
          maxLength: 63
      required:
        - BucketName
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      additionalProperties: false
      properties:
        Key:
          type: string
          description: 'The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          minLength: 1
          maxLength: 128
        Value:
          type: string
          description: 'The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
          minLength: 1
          maxLength: 256
      required:
        - Value
        - Key
    LoggingConfiguration:
      type: object
      properties:
        Arn:
          description: LoggingConfiguration ARN is automatically generated on creation and assigned as the unique identifier.
          type: string
          pattern: ^arn:aws:ivschat:[a-z0-9-]+:[0-9]+:logging-configuration/[a-zA-Z0-9-]+$
          minLength: 1
          maxLength: 128
        Id:
          description: The system-generated ID of the logging configuration.
          type: string
          pattern: ^[a-zA-Z0-9]+$
          minLength: 12
          maxLength: 12
        DestinationConfiguration:
          $ref: '#/components/schemas/DestinationConfiguration'
        Name:
          description: The name of the logging configuration. The value does not need to be unique.
          type: string
          pattern: ^[a-zA-Z0-9-_]*$
          minLength: 0
          maxLength: 128
        State:
          description: The state of the logging configuration. When the state is ACTIVE, the configuration is ready to log chat content.
          type: string
          enum:
            - CREATING
            - CREATE_FAILED
            - DELETING
            - DELETE_FAILED
            - UPDATING
            - UPDATING_FAILED
            - ACTIVE
        Tags:
          description: An array of key-value pairs to apply to this resource.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - DestinationConfiguration
      x-stackql-resource-name: logging_configuration
      x-stackql-primaryIdentifier:
        - Arn
    MessageReviewHandler:
      description: Configuration information for optional review of messages.
      type: object
      additionalProperties: false
      properties:
        FallbackResult:
          description: Specifies the fallback behavior if the handler does not return a valid response, encounters an error, or times out.
          type: string
          enum:
            - ALLOW
            - DENY
          default: ALLOW
        Uri:
          description: Identifier of the message review handler.
          type: string
          pattern: ^$|^arn:aws:lambda:[a-z0-9-]+:[0-9]{12}:function:.+
          minLength: 0
          maxLength: 170
      required: []
    Room:
      type: object
      properties:
        Arn:
          description: Room ARN is automatically generated on creation and assigned as the unique identifier.
          type: string
          pattern: ^arn:aws:ivschat:[a-z0-9-]+:[0-9]+:room/[a-zA-Z0-9-]+$
          minLength: 1
          maxLength: 128
        Id:
          description: The system-generated ID of the room.
          type: string
          pattern: ^[a-zA-Z0-9]+$
          minLength: 12
          maxLength: 12
        Name:
          description: The name of the room. The value does not need to be unique.
          type: string
          pattern: ^[a-zA-Z0-9-_]*$
          minLength: 0
          maxLength: 128
        LoggingConfigurationIdentifiers:
          description: Array of logging configuration identifiers attached to the room.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          minItems: 0
          maxItems: 50
          items:
            type: string
            pattern: ^arn:aws:ivschat:[a-z0-9-]+:[0-9]+:logging-configuration/[a-zA-Z0-9-]+$
            minLength: 1
            maxLength: 128
        MaximumMessageLength:
          description: The maximum number of characters in a single message.
          type: integer
          minimum: 1
          maximum: 500
          default: 500
        MaximumMessageRatePerSecond:
          description: The maximum number of messages per second that can be sent to the room.
          type: integer
          minimum: 1
          maximum: 10
          default: 10
        MessageReviewHandler:
          $ref: '#/components/schemas/MessageReviewHandler'
        Tags:
          description: An array of key-value pairs to apply to this resource.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
      required: []
      x-stackql-resource-name: room
      x-stackql-primaryIdentifier:
        - Arn
  x-stackQL-resources:
    logging_configurations:
      name: logging_configurations
      id: aws.ivschat.logging_configurations
      x-cfn-schema-name: LoggingConfiguration
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::IVSChat::LoggingConfiguration'
    logging_configuration:
      name: logging_configuration
      id: aws.ivschat.logging_configuration
      x-cfn-schema-name: LoggingConfiguration
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.DestinationConfiguration.CloudWatchLogs') as destination_configuration_cloud_watch_logs,
              JSON_EXTRACT(Properties, '$.DestinationConfiguration.Firehose') as destination_configuration_firehose,
              JSON_EXTRACT(Properties, '$.DestinationConfiguration.S3') as destination_configuration_s3,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.State') as state,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::IVSChat::LoggingConfiguration'
    rooms:
      name: rooms
      id: aws.ivschat.rooms
      x-cfn-schema-name: Room
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::IVSChat::Room'
    room:
      name: room
      id: aws.ivschat.room
      x-cfn-schema-name: Room
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.LoggingConfigurationIdentifiers') as logging_configuration_identifiers,
              JSON_EXTRACT(Properties, '$.MaximumMessageLength') as maximum_message_length,
              JSON_EXTRACT(Properties, '$.MaximumMessageRatePerSecond') as maximum_message_rate_per_second,
              JSON_EXTRACT(Properties, '$.MessageReviewHandler.FallbackResult') as message_review_handler_fallback_result,
              JSON_EXTRACT(Properties, '$.MessageReviewHandler.Uri') as message_review_handler_uri,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::IVSChat::Room'
