openapi: 3.0.0
info:
  title: KafkaConnect
  version: 1.0.0
paths: {}
components:
  schemas:
    ApacheKafkaCluster:
      description: Details of how to connect to an Apache Kafka cluster.
      type: object
      additionalProperties: false
      properties:
        BootstrapServers:
          description: The bootstrap servers string of the Apache Kafka cluster.
          type: string
        Vpc:
          $ref: '#/components/schemas/Vpc'
      required:
        - BootstrapServers
        - Vpc
    AutoScaling:
      description: 'Details about auto scaling of a connector. '
      type: object
      additionalProperties: false
      properties:
        MaxWorkerCount:
          description: The maximum number of workers for a connector.
          type: integer
        MinWorkerCount:
          description: The minimum number of workers for a connector.
          type: integer
        ScaleInPolicy:
          $ref: '#/components/schemas/ScaleInPolicy'
        ScaleOutPolicy:
          $ref: '#/components/schemas/ScaleOutPolicy'
        McuCount:
          description: Specifies how many MSK Connect Units (MCU) as the minimum scaling unit.
          type: integer
          enum:
            - 1
            - 2
            - 4
            - 8
      required:
        - MaxWorkerCount
        - MinWorkerCount
        - ScaleInPolicy
        - ScaleOutPolicy
        - McuCount
    Capacity:
      description: Information about the capacity allocated to the connector.
      type: object
      additionalProperties: false
      properties:
        AutoScaling:
          $ref: '#/components/schemas/AutoScaling'
        ProvisionedCapacity:
          $ref: '#/components/schemas/ProvisionedCapacity'
      oneOf:
        - required:
            - AutoScaling
        - required:
            - ProvisionedCapacity
    CloudWatchLogsLogDelivery:
      description: Details about delivering logs to Amazon CloudWatch Logs.
      type: object
      additionalProperties: false
      properties:
        Enabled:
          description: Specifies whether the logs get sent to the specified CloudWatch Logs destination.
          type: boolean
        LogGroup:
          description: The CloudWatch log group that is the destination for log delivery.
          type: string
      required:
        - Enabled
    CustomPlugin:
      description: Details about a custom plugin.
      type: object
      additionalProperties: false
      properties:
        CustomPluginArn:
          description: The Amazon Resource Name (ARN) of the custom plugin to use.
          type: string
          pattern: arn:(aws|aws-us-gov|aws-cn):kafkaconnect:.*
        Revision:
          description: The revision of the custom plugin to use.
          type: integer
          format: int64
          minimum: 1
      required:
        - CustomPluginArn
        - Revision
    FirehoseLogDelivery:
      description: Details about delivering logs to Amazon Kinesis Data Firehose.
      type: object
      additionalProperties: false
      properties:
        DeliveryStream:
          description: The Kinesis Data Firehose delivery stream that is the destination for log delivery.
          type: string
        Enabled:
          description: Specifies whether the logs get sent to the specified Kinesis Data Firehose delivery stream.
          type: boolean
      required:
        - Enabled
    KafkaCluster:
      description: Details of how to connect to the Kafka cluster.
      type: object
      additionalProperties: false
      properties:
        ApacheKafkaCluster:
          $ref: '#/components/schemas/ApacheKafkaCluster'
      required:
        - ApacheKafkaCluster
    KafkaClusterClientAuthentication:
      description: Details of the client authentication used by the Kafka cluster.
      type: object
      additionalProperties: false
      properties:
        AuthenticationType:
          $ref: '#/components/schemas/KafkaClusterClientAuthenticationType'
      required:
        - AuthenticationType
    KafkaClusterClientAuthenticationType:
      description: The type of client authentication used to connect to the Kafka cluster. Value NONE means that no client authentication is used.
      type: string
      enum:
        - NONE
        - IAM
    KafkaClusterEncryptionInTransit:
      description: Details of encryption in transit to the Kafka cluster.
      type: object
      additionalProperties: false
      properties:
        EncryptionType:
          $ref: '#/components/schemas/KafkaClusterEncryptionInTransitType'
      required:
        - EncryptionType
    KafkaClusterEncryptionInTransitType:
      description: The type of encryption in transit to the Kafka cluster.
      type: string
      enum:
        - PLAINTEXT
        - TLS
    LogDelivery:
      description: Details of what logs are delivered and where they are delivered.
      type: object
      additionalProperties: false
      properties:
        WorkerLogDelivery:
          $ref: '#/components/schemas/WorkerLogDelivery'
      required:
        - WorkerLogDelivery
    Plugin:
      description: Details about a Kafka Connect plugin which will be used with the connector.
      type: object
      additionalProperties: false
      properties:
        CustomPlugin:
          $ref: '#/components/schemas/CustomPlugin'
      required:
        - CustomPlugin
    ProvisionedCapacity:
      description: Details about a fixed capacity allocated to a connector.
      type: object
      additionalProperties: false
      properties:
        McuCount:
          description: Specifies how many MSK Connect Units (MCU) are allocated to the connector.
          type: integer
          enum:
            - 1
            - 2
            - 4
            - 8
        WorkerCount:
          description: Number of workers for a connector.
          type: integer
      required:
        - WorkerCount
    S3LogDelivery:
      description: Details about delivering logs to Amazon S3.
      type: object
      additionalProperties: false
      properties:
        Bucket:
          description: The name of the S3 bucket that is the destination for log delivery.
          type: string
        Enabled:
          description: Specifies whether the logs get sent to the specified Amazon S3 destination.
          type: boolean
        Prefix:
          description: The S3 prefix that is the destination for log delivery.
          type: string
      required:
        - Enabled
    ScaleInPolicy:
      description: Information about the scale in policy of the connector.
      type: object
      additionalProperties: false
      properties:
        CpuUtilizationPercentage:
          description: Specifies the CPU utilization percentage threshold at which connector scale in should trigger.
          type: integer
          minimum: 1
          maximum: 100
      required:
        - CpuUtilizationPercentage
    ScaleOutPolicy:
      description: Information about the scale out policy of the connector.
      type: object
      additionalProperties: false
      properties:
        CpuUtilizationPercentage:
          description: Specifies the CPU utilization percentage threshold at which connector scale out should trigger.
          type: integer
          minimum: 1
          maximum: 100
      required:
        - CpuUtilizationPercentage
    Vpc:
      description: Information about a VPC used with the connector.
      type: object
      additionalProperties: false
      properties:
        SecurityGroups:
          description: The AWS security groups to associate with the elastic network interfaces in order to specify what the connector has access to.
          type: array
          uniqueItems: true
          items:
            type: string
          x-insertionOrder: false
        Subnets:
          description: The list of subnets to connect to in the virtual private cloud (VPC). AWS creates elastic network interfaces inside these subnets.
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: string
          x-insertionOrder: false
      required:
        - SecurityGroups
        - Subnets
    WorkerConfiguration:
      description: Specifies the worker configuration to use with the connector.
      type: object
      additionalProperties: false
      properties:
        Revision:
          description: The revision of the worker configuration to use.
          type: integer
          minimum: 1
          format: int64
        WorkerConfigurationArn:
          description: The Amazon Resource Name (ARN) of the worker configuration to use.
          type: string
          pattern: arn:(aws|aws-us-gov|aws-cn):kafkaconnect:.*
      required:
        - Revision
        - WorkerConfigurationArn
    WorkerLogDelivery:
      description: Specifies where worker logs are delivered.
      type: object
      additionalProperties: false
      properties:
        CloudWatchLogs:
          $ref: '#/components/schemas/CloudWatchLogsLogDelivery'
        Firehose:
          $ref: '#/components/schemas/FirehoseLogDelivery'
        S3:
          $ref: '#/components/schemas/S3LogDelivery'
    Connector:
      type: object
      properties:
        Capacity:
          $ref: '#/components/schemas/Capacity'
        ConnectorArn:
          description: Amazon Resource Name for the created Connector.
          type: string
          pattern: arn:(aws|aws-us-gov|aws-cn):kafkaconnect:.*
        ConnectorConfiguration:
          description: The configuration for the connector.
          type: object
          additionalProperties: false
          x-patternProperties:
            .*:
              type: string
        ConnectorDescription:
          description: A summary description of the connector.
          type: string
          maxLength: 1024
        ConnectorName:
          description: The name of the connector.
          type: string
          minLength: 1
          maxLength: 128
        KafkaCluster:
          $ref: '#/components/schemas/KafkaCluster'
        KafkaClusterClientAuthentication:
          $ref: '#/components/schemas/KafkaClusterClientAuthentication'
        KafkaClusterEncryptionInTransit:
          $ref: '#/components/schemas/KafkaClusterEncryptionInTransit'
        KafkaConnectVersion:
          description: The version of Kafka Connect. It has to be compatible with both the Kafka cluster's version and the plugins.
          type: string
        LogDelivery:
          $ref: '#/components/schemas/LogDelivery'
        Plugins:
          description: List of plugins to use with the connector.
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: '#/components/schemas/Plugin'
          x-insertionOrder: false
        ServiceExecutionRoleArn:
          description: The Amazon Resource Name (ARN) of the IAM role used by the connector to access Amazon S3 objects and other external resources.
          type: string
          pattern: arn:(aws|aws-us-gov|aws-cn):iam:.*
        WorkerConfiguration:
          $ref: '#/components/schemas/WorkerConfiguration'
      required:
        - Capacity
        - ConnectorConfiguration
        - ConnectorName
        - KafkaConnectVersion
        - KafkaCluster
        - KafkaClusterClientAuthentication
        - KafkaClusterEncryptionInTransit
        - Plugins
        - ServiceExecutionRoleArn
      x-stackql-resource-name: connector
      x-stackql-primaryIdentifier:
        - ConnectorArn
  x-stackQL-resources:
    connectors:
      name: connectors
      id: aws.kafkaconnect.connectors
      x-cfn-schema-name: Connector
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ConnectorArn') as connector_arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::KafkaConnect::Connector'
    connector:
      name: connector
      id: aws.kafkaconnect.connector
      x-cfn-schema-name: Connector
      x-type: get
      x-identifiers:
        - ConnectorArn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Capacity.AutoScaling') as capacity_auto_scaling,
              JSON_EXTRACT(Properties, '$.Capacity.ProvisionedCapacity') as capacity_provisioned_capacity,
              JSON_EXTRACT(Properties, '$.ConnectorArn') as connector_arn,
              JSON_EXTRACT(Properties, '$.ConnectorConfiguration') as connector_configuration,
              JSON_EXTRACT(Properties, '$.ConnectorDescription') as connector_description,
              JSON_EXTRACT(Properties, '$.ConnectorName') as connector_name,
              JSON_EXTRACT(Properties, '$.KafkaCluster.ApacheKafkaCluster') as kafka_cluster_apache_kafka_cluster,
              JSON_EXTRACT(Properties, '$.KafkaClusterClientAuthentication.AuthenticationType') as kafka_cluster_client_authentication_authentication_type,
              JSON_EXTRACT(Properties, '$.KafkaClusterEncryptionInTransit.EncryptionType') as kafka_cluster_encryption_in_transit_encryption_type,
              JSON_EXTRACT(Properties, '$.KafkaConnectVersion') as kafka_connect_version,
              JSON_EXTRACT(Properties, '$.LogDelivery.WorkerLogDelivery') as log_delivery_worker_log_delivery,
              JSON_EXTRACT(Properties, '$.Plugins') as plugins,
              JSON_EXTRACT(Properties, '$.ServiceExecutionRoleArn') as service_execution_role_arn,
              JSON_EXTRACT(Properties, '$.WorkerConfiguration.Revision') as worker_configuration_revision,
              JSON_EXTRACT(Properties, '$.WorkerConfiguration.WorkerConfigurationArn') as worker_configuration_worker_configuration_arn
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::KafkaConnect::Connector'
