openapi: 3.0.0
info:
  title: KendraRanking
  version: 1.0.0
paths: {}
components:
  schemas:
    Description:
      type: string
      maxLength: 1000
    Tag:
      description: A label for tagging KendraRanking resources
      type: object
      properties:
        Key:
          description: A string used to identify this tag
          type: string
          minLength: 1
          maxLength: 128
        Value:
          description: A string containing the value for the tag
          type: string
          minLength: 0
          maxLength: 256
      required:
        - Key
        - Value
      additionalProperties: false
    Tags:
      description: List of tags
      type: array
      x-insertionOrder: false
      maxItems: 200
      items:
        $ref: '#/components/schemas/Tag'
    RescoreCapacityUnits:
      type: integer
      minimum: 0
    CapacityUnitsConfiguration:
      type: object
      properties:
        RescoreCapacityUnits:
          $ref: '#/components/schemas/RescoreCapacityUnits'
      additionalProperties: false
      required:
        - RescoreCapacityUnits
    Name:
      description: Name of kendra ranking rescore execution plan
      type: string
      minLength: 1
      maxLength: 1000
    Id:
      description: Unique ID of rescore execution plan
      type: string
      minLength: 36
      maxLength: 36
    Arn:
      type: string
      maxLength: 1000
    ExecutionPlan:
      type: object
      properties:
        Id:
          $ref: '#/components/schemas/Id'
        Arn:
          $ref: '#/components/schemas/Arn'
        Description:
          description: A description for the execution plan
          $ref: '#/components/schemas/Description'
        Tags:
          description: Tags for labeling the execution plan
          $ref: '#/components/schemas/Tags'
        Name:
          $ref: '#/components/schemas/Name'
        CapacityUnits:
          description: Capacity units
          $ref: '#/components/schemas/CapacityUnitsConfiguration'
      required:
        - Name
      x-stackql-resource-name: execution_plan
      x-stackql-primaryIdentifier:
        - Id
  x-stackQL-resources:
    execution_plans:
      name: execution_plans
      id: aws.kendraranking.execution_plans
      x-cfn-schema-name: ExecutionPlan
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::KendraRanking::ExecutionPlan'
    execution_plan:
      name: execution_plan
      id: aws.kendraranking.execution_plan
      x-cfn-schema-name: ExecutionPlan
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.CapacityUnits.RescoreCapacityUnits') as capacity_units_rescore_capacity_units
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::KendraRanking::ExecutionPlan'
