openapi: 3.0.0
info:
  version: "2019-12-04"
  title: Amazon Kinesis Video Signaling Channels
  description: Amazon Kinesis Video Signaling Channels
  x-serviceName: kinesisvideo
  x-serviceAlias: kinesis_video_signaling
  x-protocol: rest-json
  x-apiVersion: "2019-12-04"
  x-endpointPrefix: kinesisvideo
servers:
  - url: https://kinesisvideo.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for kinesis-video-signaling
paths:
  /v1/get-ice-server-config:
    post:
      operationId: GetIceServerConfig
      description: Gets the Interactive Connectivity Establishment (ICE) server configuration information, including URIs, username, and password which can be used to configure the WebRTC connection. The ICE component uses this configuration information to setup the WebRTC connection, including authenticating with the Traversal Using Relays around NAT (TURN) relay server. TURN is a protocol that is used to improve the connectivity of peer-to-peer applications. By providing a cloud-based relay service, TURN ensures that a connection can be established even when one or more peers are incapable of a direct peer-to-peer connection. For more information, see A REST API For Access To TURN Services. You can invoke this API to establish a fallback mechanism in case either of the peers is unable to establish a direct peer-to-peer connection over a signaling channel. You must specify either a signaling channel ARN or the client ID in order to invoke this API.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ChannelARN:
                  $ref: "#/components/schemas/ResourceARN"
                ClientId:
                  $ref: "#/components/schemas/ClientId"
                Service:
                  $ref: "#/components/schemas/Service"
                Username:
                  $ref: "#/components/schemas/Username"
              required:
                - ChannelARN
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetIceServerConfigResponse"
  /v1/send-alexa-offer-to-master:
    post:
      operationId: SendAlexaOfferToMaster
      description: This API allows you to connect WebRTC-enabled devices with Alexa display devices. When invoked, it sends the Alexa Session Description Protocol (SDP) offer to the master peer. The offer is delivered as soon as the master is connected to the specified signaling channel. This API returns the SDP answer from the connected master. If the master is not connected to the signaling channel, redelivery requests are made until the message expires.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ChannelARN:
                  $ref: "#/components/schemas/ResourceARN"
                SenderClientId:
                  $ref: "#/components/schemas/ClientId"
                MessagePayload:
                  $ref: "#/components/schemas/MessagePayload"
              required:
                - ChannelARN
                - SenderClientId
                - MessagePayload
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SendAlexaOfferToMasterResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    ResourceARN:
      type: string
      minLength: 1
      maxLength: 1024
      pattern: arn:aws:kinesisvideo:[a-z0-9-]+:[0-9]+:[a-z]+/[a-zA-Z0-9_.-]+/[0-9]+
    ClientId:
      type: string
      minLength: 1
      maxLength: 256
      pattern: "[a-zA-Z0-9_.-]+"
    Service:
      type: string
      enum:
        - TURN
    Username:
      type: string
      minLength: 1
      maxLength: 256
      pattern: "[a-zA-Z0-9_.-]+"
    GetIceServerConfigResponse:
      type: object
      properties:
        IceServerList:
          $ref: "#/components/schemas/IceServerList"
          description: The list of ICE server information objects.
    IceServerList:
      type: array
      items:
        $ref: "#/components/schemas/IceServer"
    IceServer:
      description: A structure for the ICE server connection data.
      type: object
      properties:
        Uris:
          $ref: "#/components/schemas/Uris"
          description: An array of URIs, in the form specified in the I-D.petithuguenin-behave-turn-uris spec. These URIs provide the different addresses and/or protocols that can be used to reach the TURN server.
        Username:
          $ref: "#/components/schemas/Username"
          description: A username to login to the ICE server.
        Password:
          $ref: "#/components/schemas/Password"
          description: A password to login to the ICE server.
        Ttl:
          $ref: "#/components/schemas/Ttl"
          description: The period of time, in seconds, during which the username and password are valid.
    Uris:
      type: array
      items:
        $ref: "#/components/schemas/Uri"
    Uri:
      type: string
      minLength: 1
      maxLength: 256
    Password:
      type: string
      minLength: 1
      maxLength: 256
      pattern: "[a-zA-Z0-9_.-]+"
    Ttl:
      type: integer
      minimum: 30
      maximum: 86400
    MessagePayload:
      type: string
      minLength: 1
      maxLength: 10000
      pattern: "[a-zA-Z0-9+/=]+"
    SendAlexaOfferToMasterResponse:
      type: object
      properties:
        Answer:
          $ref: "#/components/schemas/Answer"
          description: The base64-encoded SDP answer content.
    Answer:
      type: string
      minLength: 1
      maxLength: 10000
  x-stackQL-resources:
    ice_server_configs:
      id: aws.kinesis_video_signaling.ice_server_configs
      name: ice_server_configs
      title: ice_server_configs
      methods:
        get_ice_server_config:
          operation:
            $ref: "#/paths/~1v1~1get-ice-server-config/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/ice_server_configs/methods/get_ice_server_config"
        insert: []
        update: []
        delete: []
