openapi: 3.0.0
info:
  version: "2017-09-30"
  title: Amazon Kinesis Video Streams Media
  description: Amazon Kinesis Video Streams Media
  x-serviceName: kinesisvideo
  x-serviceAlias: kinesis_video_media
  x-protocol: rest-json
  x-apiVersion: "2017-09-30"
  x-endpointPrefix: kinesisvideo
servers:
  - url: https://kinesisvideo.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for kinesis-video-media
paths:
  /getMedia:
    post:
      operationId: GetMedia
      description: 'Use this API to retrieve media content from a Kinesis video stream. In the request, you identify the stream name or stream Amazon Resource Name (ARN), and the starting chunk. Kinesis Video Streams then returns a stream of chunks in order by fragment number. You must first call the GetDataEndpoint API to get an endpoint. Then send the GetMedia requests to this endpoint using the --endpoint-url parameter. When you put media data (fragments) on a stream, Kinesis Video Streams stores each incoming fragment and related metadata in what is called a "chunk." For more information, see PutMedia. The GetMedia API returns a stream of these chunks starting from the chunk that you specify in the request. The following limits apply when using the GetMedia API: A client can call GetMedia up to five times per second per stream. Kinesis Video Streams sends media data at a rate of up to 25 megabytes per second (or 200 megabits per second) during a GetMedia session. If an error is thrown after invoking a Kinesis Video Streams media API, in addition to the HTTP status code and the response body, it includes the following pieces of information: x-amz-ErrorType HTTP header – contains a more specific error type in addition to what the HTTP status code provides. x-amz-RequestId HTTP header – if you want to report an issue to AWS, the support team can better diagnose the problem if given the Request Id. Both the HTTP status code and the ErrorType header can be utilized to make programmatic decisions about whether errors are retry-able and under what conditions, as well as provide information on what actions the client programmer might need to take in order to successfully try again. For more information, see the Errors section at the bottom of this topic, as well as Common Errors.'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                StreamName:
                  $ref: "#/components/schemas/StreamName"
                StreamARN:
                  $ref: "#/components/schemas/ResourceARN"
                StartSelector:
                  $ref: "#/components/schemas/StartSelector"
              required:
                - StartSelector
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetMediaOutput"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    StreamName:
      type: string
      minLength: 1
      maxLength: 256
      pattern: "[a-zA-Z0-9_.-]+"
    ResourceARN:
      type: string
      minLength: 1
      maxLength: 1024
      pattern: arn:aws:kinesisvideo:[a-z0-9-]+:[0-9]+:[a-z]+/[a-zA-Z0-9_.-]+/[0-9]+
    StartSelector:
      description: "Identifies the chunk on the Kinesis video stream where you want the GetMedia API to start returning media data. You have the following options to identify the starting chunk: Choose the latest (or oldest) chunk. Identify a specific chunk. You can identify a specific chunk either by providing a fragment number or timestamp (server or producer). Each chunk's metadata includes a continuation token as a Matroska (MKV) tag (AWS_KINESISVIDEO_CONTINUATION_TOKEN). If your previous GetMedia request terminated, you can use this tag value in your next GetMedia request. The API then starts returning chunks starting where the last API ended."
      type: object
      properties:
        StartSelectorType:
          $ref: "#/components/schemas/StartSelectorType"
          description: Identifies the fragment on the Kinesis video stream where you want to start getting the data from. NOW - Start with the latest chunk on the stream. EARLIEST - Start with earliest available chunk on the stream. FRAGMENT_NUMBER - Start with the chunk after a specific fragment. You must also specify the AfterFragmentNumber parameter. PRODUCER_TIMESTAMP or SERVER_TIMESTAMP - Start with the chunk containing a fragment with the specified producer or server timestamp. You specify the timestamp by adding StartTimestamp. CONTINUATION_TOKEN - Read using the specified continuation token. If you choose the NOW, EARLIEST, or CONTINUATION_TOKEN as the startSelectorType, you don't provide any additional information in the startSelector.
        AfterFragmentNumber:
          $ref: "#/components/schemas/FragmentNumberString"
          description: Specifies the fragment number from where you want the GetMedia API to start returning the fragments.
        StartTimestamp:
          $ref: "#/components/schemas/Timestamp"
          description: A timestamp value. This value is required if you choose the PRODUCER_TIMESTAMP or the SERVER_TIMESTAMP as the startSelectorType. The GetMedia API then starts with the chunk containing the fragment that has the specified timestamp.
        ContinuationToken:
          $ref: "#/components/schemas/ContinuationToken"
          description: Continuation token that Kinesis Video Streams returned in the previous GetMedia response. The GetMedia API then starts with the chunk identified by the continuation token.
      required:
        - StartSelectorType
    StartSelectorType:
      type: string
      enum:
        - FRAGMENT_NUMBER
        - SERVER_TIMESTAMP
        - PRODUCER_TIMESTAMP
        - NOW
        - EARLIEST
        - CONTINUATION_TOKEN
    FragmentNumberString:
      type: string
      minLength: 1
      maxLength: 128
      pattern: ^[0-9]+$
    Timestamp:
      type: string
      format: date-time
    ContinuationToken:
      type: string
      minLength: 1
      maxLength: 128
      pattern: ^[a-zA-Z0-9_\.\-]+$
    GetMediaOutput:
      type: object
      properties:
        ContentType:
          $ref: "#/components/schemas/ContentType"
          description: The content type of the requested media.
        Payload:
          $ref: "#/components/schemas/Payload"
          description: "The payload Kinesis Video Streams returns is a sequence of chunks from the specified stream. For information about the chunks, see . The chunks that Kinesis Video Streams returns in the GetMedia call also include the following additional Matroska (MKV) tags: AWS_KINESISVIDEO_CONTINUATION_TOKEN (UTF-8 string) - In the event your GetMedia call terminates, you can use this continuation token in your next request to get the next chunk where the last request terminated. AWS_KINESISVIDEO_MILLIS_BEHIND_NOW (UTF-8 string) - Client applications can use this tag value to determine how far behind the chunk returned in the response is from the latest chunk on the stream. AWS_KINESISVIDEO_FRAGMENT_NUMBER - Fragment number returned in the chunk. AWS_KINESISVIDEO_SERVER_TIMESTAMP - Server timestamp of the fragment. AWS_KINESISVIDEO_PRODUCER_TIMESTAMP - Producer timestamp of the fragment. The following tags will be present if an error occurs: AWS_KINESISVIDEO_ERROR_CODE - String description of an error that caused GetMedia to stop. AWS_KINESISVIDEO_ERROR_ID: Integer code of the error. The error codes are as follows: 3002 - Error writing to the stream 4000 - Requested fragment is not found 4500 - Access denied for the stream's KMS key 4501 - Stream's KMS key is disabled 4502 - Validation error on the stream's KMS key 4503 - KMS key specified in the stream is unavailable 4504 - Invalid usage of the KMS key specified in the stream 4505 - Invalid state of the KMS key specified in the stream 4506 - Unable to find the KMS key specified in the stream 5000 - Internal error"
    ContentType:
      type: string
      minLength: 1
      maxLength: 128
      pattern: ^[a-zA-Z0-9_\.\-]+$
    Payload:
      type: string
      format: byte
  x-stackQL-resources:
    medias:
      id: aws.kinesis_video_media.medias
      name: medias
      title: medias
      methods:
        get_media:
          operation:
            $ref: "#/paths/~1getMedia/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/medias/methods/get_media"
        insert: []
        update: []
        delete: []
