openapi: 3.0.0
info:
  title: LookoutEquipment
  version: 1.0.0
paths: {}
components:
  schemas:
    Bucket:
      type: string
      pattern: ^[a-z0-9][\.\-a-z0-9]{1,61}[a-z0-9]$
      minLength: 3
      maxLength: 63
    Prefix:
      type: string
      minLength: 0
      maxLength: 1024
    S3InputConfiguration:
      description: Specifies configuration information for the input data for the inference, including input data S3 location.
      type: object
      properties:
        Bucket:
          $ref: '#/components/schemas/Bucket'
        Prefix:
          $ref: '#/components/schemas/Prefix'
      required:
        - Bucket
      additionalProperties: false
    S3OutputConfiguration:
      description: Specifies configuration information for the output results from the inference, including output S3 location.
      type: object
      properties:
        Bucket:
          $ref: '#/components/schemas/Bucket'
        Prefix:
          $ref: '#/components/schemas/Prefix'
      required:
        - Bucket
      additionalProperties: false
    InputNameConfiguration:
      description: Specifies configuration information for the input data for the inference, including timestamp format and delimiter.
      type: object
      properties:
        ComponentTimestampDelimiter:
          description: Indicates the delimiter character used between items in the data.
          type: string
          pattern: ^(\-|\_|\s)?$
          minLength: 0
          maxLength: 1
        TimestampFormat:
          description: The format of the timestamp, whether Epoch time, or standard, with or without hyphens (-).
          type: string
          pattern: ^EPOCH|yyyy-MM-dd-HH-mm-ss|yyyyMMddHHmmss$
      additionalProperties: false
    Tag:
      description: A tag is a key-value pair that can be added to a resource as metadata.
      type: object
      properties:
        Key:
          description: The key for the specified tag.
          type: string
          pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
          minLength: 1
          maxLength: 128
        Value:
          description: The value for the specified tag.
          type: string
          pattern: '[\s\w+-=\.:/@]*'
          minLength: 0
          maxLength: 256
      required:
        - Key
        - Value
      additionalProperties: false
    InferenceScheduler:
      type: object
      properties:
        DataDelayOffsetInMinutes:
          description: A period of time (in minutes) by which inference on the data is delayed after the data starts.
          type: integer
          minimum: 0
          maximum: 60
        DataInputConfiguration:
          description: Specifies configuration information for the input data for the inference scheduler, including delimiter, format, and dataset location.
          type: object
          properties:
            InputTimeZoneOffset:
              description: Indicates the difference between your time zone and Greenwich Mean Time (GMT).
              type: string
              pattern: ^(\+|\-)[0-9]{2}\:[0-9]{2}$
            InferenceInputNameConfiguration:
              $ref: '#/components/schemas/InputNameConfiguration'
            S3InputConfiguration:
              $ref: '#/components/schemas/S3InputConfiguration'
          required:
            - S3InputConfiguration
          additionalProperties: false
        DataOutputConfiguration:
          description: Specifies configuration information for the output results for the inference scheduler, including the S3 location for the output.
          type: object
          properties:
            KmsKeyId:
              description: The ID number for the AWS KMS key used to encrypt the inference output.
              type: string
              pattern: ^[A-Za-z0-9][A-Za-z0-9:_/+=,@.-]{0,2048}$
              minLength: 1
              maxLength: 2048
            S3OutputConfiguration:
              $ref: '#/components/schemas/S3OutputConfiguration'
          required:
            - S3OutputConfiguration
          additionalProperties: false
        DataUploadFrequency:
          description: How often data is uploaded to the source S3 bucket for the input data.
          type: string
          enum:
            - PT5M
            - PT10M
            - PT15M
            - PT30M
            - PT1H
        InferenceSchedulerName:
          description: The name of the inference scheduler being created.
          type: string
          pattern: ^[0-9a-zA-Z_-]{1,200}$
          minLength: 1
          maxLength: 200
        ModelName:
          description: The name of the previously trained ML model being used to create the inference scheduler.
          type: string
          pattern: ^[0-9a-zA-Z_-]{1,200}$
          minLength: 1
          maxLength: 200
        RoleArn:
          description: The Amazon Resource Name (ARN) of a role with permission to access the data source being used for the inference.
          type: string
          pattern: arn:aws(-[^:]+)?:iam::[0-9]{12}:role/.+
          minLength: 20
          maxLength: 2048
        ServerSideKmsKeyId:
          description: Provides the identifier of the AWS KMS customer master key (CMK) used to encrypt inference scheduler data by Amazon Lookout for Equipment.
          type: string
          pattern: ^[A-Za-z0-9][A-Za-z0-9:_/+=,@.-]{0,2048}$
          minLength: 1
          maxLength: 2048
        Tags:
          description: Any tags associated with the inference scheduler.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          maxItems: 200
          items:
            $ref: '#/components/schemas/Tag'
        InferenceSchedulerArn:
          description: The Amazon Resource Name (ARN) of the inference scheduler being created.
          type: string
          pattern: arn:aws(-[^:]+)?:lookoutequipment:[a-zA-Z0-9\-]*:[0-9]{12}:inference-scheduler\/.+
          minLength: 1
          maxLength: 200
      required:
        - DataInputConfiguration
        - DataOutputConfiguration
        - DataUploadFrequency
        - ModelName
        - RoleArn
      x-stackql-resource-name: inference_scheduler
      x-stackql-primaryIdentifier:
        - InferenceSchedulerName
  x-stackQL-resources:
    inference_schedulers:
      name: inference_schedulers
      id: aws.lookoutequipment.inference_schedulers
      x-cfn-schema-name: InferenceScheduler
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.InferenceSchedulerName') as inference_scheduler_name
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::LookoutEquipment::InferenceScheduler'
    inference_scheduler:
      name: inference_scheduler
      id: aws.lookoutequipment.inference_scheduler
      x-cfn-schema-name: InferenceScheduler
      x-type: get
      x-identifiers:
        - InferenceSchedulerName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.DataDelayOffsetInMinutes') as data_delay_offset_in_minutes,
              JSON_EXTRACT(Properties, '$.DataInputConfiguration') as data_input_configuration,
              JSON_EXTRACT(Properties, '$.DataOutputConfiguration') as data_output_configuration,
              JSON_EXTRACT(Properties, '$.DataUploadFrequency') as data_upload_frequency,
              JSON_EXTRACT(Properties, '$.InferenceSchedulerName') as inference_scheduler_name,
              JSON_EXTRACT(Properties, '$.ModelName') as model_name,
              JSON_EXTRACT(Properties, '$.RoleArn') as role_arn,
              JSON_EXTRACT(Properties, '$.ServerSideKmsKeyId') as server_side_kms_key_id,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.InferenceSchedulerArn') as inference_scheduler_arn
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::LookoutEquipment::InferenceScheduler'
