openapi: 3.0.0
info:
  title: Macie
  version: 1.0.0
paths: {}
components:
  schemas:
    Regex:
      type: string
    S3WordsList:
      type: object
      properties:
        BucketName:
          type: string
        ObjectKey:
          type: string
      required:
        - BucketName
        - ObjectKey
      additionalProperties: false
    Criteria:
      description: The regex or s3 object to use for the AllowList.
      type: object
      oneOf:
        - additionalProperties: false
          properties:
            Regex:
              type: string
              description: The S3 object key for the AllowList.
          required:
            - Regex
        - additionalProperties: false
          properties:
            S3WordsList:
              $ref: '#/components/schemas/S3WordsList'
              description: The S3 location for the AllowList.
          required:
            - S3WordsList
    Status:
      description: The status for the AllowList
      type: string
      enum:
        - OK
        - S3_OBJECT_NOT_FOUND
        - S3_USER_ACCESS_DENIED
        - S3_OBJECT_ACCESS_DENIED
        - S3_THROTTLED
        - S3_OBJECT_OVERSIZE
        - S3_OBJECT_EMPTY
        - UNKNOWN_ERROR
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      properties:
        Key:
          type: string
          description: The tag's key.
        Value:
          type: string
          description: The tag's value.
      required:
        - Value
        - Key
      additionalProperties: false
    AllowList:
      type: object
      properties:
        Name:
          description: Name of AllowList.
          type: string
        Description:
          description: Description of AllowList.
          type: string
        Criteria:
          description: AllowList criteria.
          $ref: '#/components/schemas/Criteria'
        Id:
          description: AllowList ID.
          type: string
        Arn:
          description: AllowList ARN.
          type: string
        Status:
          description: AllowList status.
          $ref: '#/components/schemas/Status'
        Tags:
          description: A collection of tags associated with a resource
          type: array
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - Name
        - Criteria
      x-stackql-resource-name: allow_list
      x-stackql-primaryIdentifier:
        - Id
    CustomDataIdentifier:
      type: object
      properties:
        Name:
          description: Name of custom data identifier.
          type: string
        Description:
          description: Description of custom data identifier.
          type: string
        Regex:
          description: Regular expression for custom data identifier.
          type: string
        MaximumMatchDistance:
          description: Maximum match distance.
          type: integer
        Keywords:
          description: Keywords to be matched against.
          type: array
          items:
            type: string
        IgnoreWords:
          description: Words to be ignored.
          type: array
          items:
            type: string
        Id:
          description: Custom data identifier ID.
          type: string
        Arn:
          description: Custom data identifier ARN.
          type: string
      required:
        - Name
        - Regex
      x-stackql-resource-name: custom_data_identifier
      x-stackql-primaryIdentifier:
        - Id
    CriterionAdditionalProperties:
      type: object
      properties:
        gt:
          type: integer
          format: int64
        gte:
          type: integer
          format: int64
        lt:
          type: integer
          format: int64
        lte:
          type: integer
          format: int64
        eq:
          type: array
          items:
            type: string
        neq:
          type: array
          items:
            type: string
      additionalProperties: false
    Criterion:
      description: Map of filter criteria.
      type: object
      x-patternProperties:
        \w:
          $ref: '#/components/schemas/CriterionAdditionalProperties'
      additionalProperties: false
    FindingCriteria:
      type: object
      properties:
        Criterion:
          $ref: '#/components/schemas/Criterion'
      additionalProperties: false
    FindingFilterAction:
      type: string
      enum:
        - ARCHIVE
        - NOOP
    FindingsFilterListItem:
      description: Returned by ListHandler representing filter name and ID.
      type: object
      properties:
        Id:
          type: string
        Name:
          type: string
    FindingsFilter:
      type: object
      properties:
        Name:
          description: Findings filter name
          type: string
        Description:
          description: Findings filter description
          type: string
        FindingCriteria:
          description: Findings filter criteria.
          $ref: '#/components/schemas/FindingCriteria'
        Action:
          description: Findings filter action.
          $ref: '#/components/schemas/FindingFilterAction'
        Position:
          description: Findings filter position.
          type: integer
        Id:
          description: Findings filter ID.
          type: string
        Arn:
          description: Findings filter ARN.
          type: string
      required:
        - Name
        - FindingCriteria
      x-stackql-resource-name: findings_filter
      x-stackql-primaryIdentifier:
        - Id
    Session:
      type: object
      properties:
        AwsAccountId:
          description: AWS account ID of customer
          type: string
        Status:
          description: A enumeration value that specifies the status of the Macie Session.
          type: string
          enum:
            - ENABLED
            - PAUSED
          default: ENABLED
        FindingPublishingFrequency:
          description: A enumeration value that specifies how frequently finding updates are published.
          type: string
          enum:
            - FIFTEEN_MINUTES
            - ONE_HOUR
            - SIX_HOURS
          default: SIX_HOURS
        ServiceRole:
          description: Service role used by Macie
          type: string
      x-stackql-resource-name: session
      x-stackql-primaryIdentifier:
        - AwsAccountId
  x-stackQL-resources:
    allow_lists:
      name: allow_lists
      id: aws.macie.allow_lists
      x-cfn-schema-name: AllowList
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Macie::AllowList'
    allow_list:
      name: allow_list
      id: aws.macie.allow_list
      x-cfn-schema-name: AllowList
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Macie::AllowList'
    custom_data_identifiers:
      name: custom_data_identifiers
      id: aws.macie.custom_data_identifiers
      x-cfn-schema-name: CustomDataIdentifier
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Macie::CustomDataIdentifier'
    custom_data_identifier:
      name: custom_data_identifier
      id: aws.macie.custom_data_identifier
      x-cfn-schema-name: CustomDataIdentifier
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.Regex') as regex,
              JSON_EXTRACT(Properties, '$.MaximumMatchDistance') as maximum_match_distance,
              JSON_EXTRACT(Properties, '$.Keywords') as keywords,
              JSON_EXTRACT(Properties, '$.IgnoreWords') as ignore_words,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Macie::CustomDataIdentifier'
    findings_filters:
      name: findings_filters
      id: aws.macie.findings_filters
      x-cfn-schema-name: FindingsFilter
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Macie::FindingsFilter'
    findings_filter:
      name: findings_filter
      id: aws.macie.findings_filter
      x-cfn-schema-name: FindingsFilter
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.FindingCriteria.Criterion') as finding_criteria_criterion,
              JSON_EXTRACT(Properties, '$.Position') as position,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Macie::FindingsFilter'
    sessions:
      name: sessions
      id: aws.macie.sessions
      x-cfn-schema-name: Session
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.AwsAccountId') as aws_account_id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Macie::Session'
    session:
      name: session
      id: aws.macie.session
      x-cfn-schema-name: Session
      x-type: get
      x-identifiers:
        - AwsAccountId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.AwsAccountId') as aws_account_id,
              JSON_EXTRACT(Properties, '$.Status') as status,
              JSON_EXTRACT(Properties, '$.FindingPublishingFrequency') as finding_publishing_frequency,
              JSON_EXTRACT(Properties, '$.ServiceRole') as service_role
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Macie::Session'
