openapi: 3.0.0
info:
  version: "2018-05-10"
  title: AWS Marketplace Reporting Service
  description: AWS Marketplace Reporting Service
  x-serviceName: aws-marketplace
  x-serviceAlias: marketplace_reporting
  x-protocol: rest-json
  x-apiVersion: "2018-05-10"
  x-endpointPrefix: reporting-marketplace
servers:
  - url: https://reporting-marketplace.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for marketplace-reporting
paths:
  /getBuyerDashboard:
    post:
      operationId: GetBuyerDashboard
      description: "Generates an embedding URL for an Amazon QuickSight dashboard for an anonymous user. This API is available only to Amazon Web Services Organization management accounts or delegated administrators registered for the procurement insights (procurement-insights.marketplace.amazonaws.com) feature. The following rules apply to a generated URL: It contains a temporary bearer token, valid for 5 minutes after it is generated. Once redeemed within that period, it cannot be re-used again. It has a session lifetime of one hour. The 5-minute validity period runs separately from the session lifetime."
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dashboardIdentifier:
                  $ref: "#/components/schemas/DashboardIdentifier"
                embeddingDomains:
                  $ref: "#/components/schemas/EmbeddingDomains"
              required:
                - dashboardIdentifier
                - embeddingDomains
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBuyerDashboardOutput"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    DashboardIdentifier:
      type: string
      minLength: 1
      maxLength: 1023
      pattern: arn:aws:aws-marketplace::[0-9]{12}:AWSMarketplace/ReportingData/(Agreement_V1/Dashboard/AgreementSummary_V1|BillingEvent_V1/Dashboard/CostAnalysis_V1)
    EmbeddingDomains:
      type: array
      items:
        $ref: "#/components/schemas/EmbeddingDomain"
    EmbeddingDomain:
      type: string
      minLength: 1
      maxLength: 2000
      pattern: (https://[a-zA-Z\.\*0-9\-_]+[\.]{1}[a-zA-Z]{1,}[a-zA-Z0-9&?/-_=]*[a-zA-Z\*0-9/]+|http[s]*://localhost(:[0-9]{1,5})?)
    GetBuyerDashboardOutput:
      type: object
      properties:
        embedUrl:
          $ref: "#/components/schemas/String"
          description: The dashboard's embedding URL.
        dashboardIdentifier:
          $ref: "#/components/schemas/DashboardIdentifier"
          description: The ARN of the returned dashboard.
        embeddingDomains:
          $ref: "#/components/schemas/EmbeddingDomains"
          description: The fully qualified domains specified in the request. The domains enable access to the generated URL that is then embedded. You can list up to two domains or subdomains in each API call. To include all subdomains under a specific domain, use *. For example, https://*.amazon.com includes all subdomains under https://aws.amazon.com.
      required:
        - embedUrl
        - dashboardIdentifier
        - embeddingDomains
    String:
      type: string
  x-stackQL-resources:
    buyer_dashboards:
      id: aws.marketplace_reporting.buyer_dashboards
      name: buyer_dashboards
      title: buyer_dashboards
      methods:
        get_buyer_dashboard:
          operation:
            $ref: "#/paths/~1getBuyerDashboard/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/buyer_dashboards/methods/get_buyer_dashboard"
        insert: []
        update: []
        delete: []
