openapi: 3.0.0
info:
  version: "2023-01-25"
  title: AWS Marketplace Deployment Service
  description: AWS Marketplace Deployment Service
  x-serviceName: aws-marketplace
  x-serviceAlias: marketplace_deployment
  x-protocol: rest-json
  x-apiVersion: "2023-01-25"
  x-endpointPrefix: deployment-marketplace
  x-jsonVersion: "1.1"
servers:
  - url: https://deployment-marketplace.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for marketplace-deployment
paths:
  /tags/{resource_arn}:
    get:
      operationId: ListTagsForResource
      description: Lists all tags that have been added to a deployment parameter resource.
      parameters:
        - name: resource_arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/String"
          description: The Amazon Resource Name (ARN) associated with the deployment parameter resource you want to list tags on.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListTagsForResourceResponse"
    post:
      operationId: TagResource
      description: Tags a resource.
      parameters:
        - name: resource_arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/String"
          description: The Amazon Resource Name (ARN) associated with the resource you want to tag.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                tags:
                  $ref: "#/components/schemas/Tags"
      responses:
        "204":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagResourceResponse"
    delete:
      operationId: UntagResource
      description: Removes a tag or list of tags from a resource.
      parameters:
        - name: resource_arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/String"
          description: The Amazon Resource Name (ARN) associated with the resource you want to remove the tag from.
        - name: tagKeys
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/StringList"
          description: A list of key names of tags to be removed.
      responses:
        "204":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UntagResourceResponse"
  /catalogs/{catalog}/products/{product_id}/deployment-parameters:
    post:
      operationId: PutDeploymentParameter
      description: Creates or updates a deployment parameter and is targeted by catalog and agreementId.
      parameters:
        - name: catalog
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Catalog"
          description: "The catalog related to the request. Fixed value: AWSMarketplace"
        - name: product_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/ResourceId"
          description: The product for which AWS Marketplace will save secrets for the buyer’s account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                agreementId:
                  $ref: "#/components/schemas/ResourceId"
                clientToken:
                  $ref: "#/components/schemas/ClientToken"
                deploymentParameter:
                  $ref: "#/components/schemas/DeploymentParameterInput"
                expirationDate:
                  $ref: "#/components/schemas/SyntheticTimestamp_date_time"
                tags:
                  $ref: "#/components/schemas/TagsMap"
              required:
                - agreementId
                - deploymentParameter
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PutDeploymentParameterResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    String:
      type: string
    ListTagsForResourceResponse:
      type: object
      properties:
        tags:
          type: object
          properties: {}
          description: A map of key-value pairs, where each pair represents a tag present on the resource.
    Catalog:
      type: string
      minLength: 1
      maxLength: 64
      pattern: ^[a-zA-Z_-]+$
    ResourceId:
      type: string
      minLength: 1
      maxLength: 64
      pattern: ^[A-Za-z0-9_/-]+$
    ClientToken:
      type: string
      minLength: 32
      maxLength: 64
      pattern: ^[a-zA-Z0-9/_+=.:@-]+$
    DeploymentParameterInput:
      description: The shape containing the requested deployment parameter name and secretString. To support AWS CloudFormation dynamic references to this resource using Quick Launch, this value must match a parameter defined in the CloudFormation templated provided to buyers.
      type: object
      properties:
        name:
          $ref: "#/components/schemas/DeploymentParameterName"
          description: The desired name of the deployment parameter. This is the identifier on which deployment parameters are keyed for a given buyer and product. If this name matches an existing deployment parameter, this request will update the existing resource.
        secretString:
          $ref: "#/components/schemas/SecretString"
          description: The text to encrypt and store in the secret.
      required:
        - name
        - secretString
    DeploymentParameterName:
      type: string
      minLength: 1
      maxLength: 400
      pattern: ^[a-zA-Z0-9/_+=.@-]+$
    SecretString:
      type: string
      minLength: 1
      maxLength: 15000
    SyntheticTimestamp_date_time:
      type: string
      format: date-time
    TagsMap:
      type: object
      properties: {}
    PutDeploymentParameterResponse:
      type: object
      properties:
        agreementId:
          $ref: "#/components/schemas/ResourceId"
          description: The unique identifier of the agreement.
        deploymentParameterId:
          $ref: "#/components/schemas/DeploymentParameterResourceIdentifier"
          description: The unique identifier of the deployment parameter.
        resourceArn:
          $ref: "#/components/schemas/ResourceArn"
          description: The Amazon Resource Name (ARN) associated with the deployment parameter resource you want to create or update.
        tags:
          type: object
          properties: {}
          description: A map of key-value pairs, where each pair represents a tag saved to the resource. Tags will only be applied for create operations, and they'll be ignored if the resource already exists.
      required:
        - agreementId
        - deploymentParameterId
        - resourceArn
    DeploymentParameterResourceIdentifier:
      type: string
      minLength: 1
      maxLength: 32
      pattern: ^dp-[a-zA-Z0-9]+$
    ResourceArn:
      type: string
      minLength: 1
      maxLength: 2048
      pattern: ^[a-zA-Z0-9:*/-]+$
    Tags:
      type: object
      properties: {}
    TagResourceResponse:
      type: object
    StringList:
      type: array
      items:
        $ref: "#/components/schemas/String"
    UntagResourceResponse:
      type: object
  x-stackQL-resources:
    tags:
      id: aws.marketplace_deployment.tags
      name: tags
      title: tags
      methods:
        list_tags_for_resource:
          operation:
            $ref: "#/paths/~1tags~1{resource_arn}/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        tag_resource:
          operation:
            $ref: "#/paths/~1tags~1{resource_arn}/post"
          response:
            openAPIDocKey: "204"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
        untag_resource:
          operation:
            $ref: "#/paths/~1tags~1{resource_arn}/delete"
          response:
            openAPIDocKey: "204"
            mediaType: application/json
          request:
            nativeCasing: pascal
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/tags/methods/list_tags_for_resource"
        insert: []
        update:
          - $ref: "#/components/x-stackQL-resources/tags/methods/untag_resource"
          - $ref: "#/components/x-stackQL-resources/tags/methods/tag_resource"
        delete: []
    deployment_parameters:
      id: aws.marketplace_deployment.deployment_parameters
      name: deployment_parameters
      title: deployment_parameters
      methods:
        put_deployment_parameter:
          operation:
            $ref: "#/paths/~1catalogs~1{catalog}~1products~1{product_id}~1deployment-parameters/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        replace:
          - $ref: "#/components/x-stackQL-resources/deployment_parameters/methods/put_deployment_parameter"
        delete: []
