openapi: 3.0.0
info:
  version: "2017-01-11"
  title: AWS Marketplace Entitlement Service
  description: AWS Marketplace Entitlement Service
  x-serviceName: aws-marketplace
  x-serviceAlias: marketplace_entitlement
  x-protocol: json
  x-apiVersion: "2017-01-11"
  x-endpointPrefix: entitlement.marketplace
  x-targetPrefix: AWSMPEntitlementService
  x-jsonVersion: "1.1"
servers:
  - url: https://entitlement.marketplace.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for marketplace-entitlement
paths:
  /GetEntitlements:
    post:
      operationId: GetEntitlements
      description: GetEntitlements retrieves entitlement values for a given product. The results can be filtered based on customer identifier, AWS account ID, license ARN, or product dimensions.
      parameters:
        - name: X-Amz-Target
          in: header
          description: Action Header
          required: false
          schema:
            type: string
            enum:
              - AWSMPEntitlementService.GetEntitlements
            default: AWSMPEntitlementService.GetEntitlements
      requestBody:
        required: true
        content:
          application/x-amz-json-1.1:
            schema:
              type: object
              properties:
                ProductCode:
                  $ref: "#/components/schemas/ProductCode"
                  description: Product code is used to uniquely identify a product in AWS Marketplace. The product code will be provided by AWS Marketplace when the product listing is created.
                Filter:
                  $ref: "#/components/schemas/GetEntitlementFilters"
                  description: Filter is used to return entitlements for a specific customer or for a specific dimension. Filters are described as keys mapped to a lists of values. Filtered requests are unioned for each value in the value list, and then intersected for each filter key. CustomerIdentifier and CustomerAWSAccountId are mutually exclusive parameters. You must use one or the other, but not both in the same request. If you're migrating an existing integration, use Account Feeds to map CustomerIdentifier to CustomerAWSAccountId, and Agreements Feeds to map CustomerAWSAccountId and LicenseArn.
                NextToken:
                  $ref: "#/components/schemas/NonEmptyString"
                  description: For paginated calls to GetEntitlements, pass the NextToken from the previous GetEntitlementsResult.
                MaxResults:
                  $ref: "#/components/schemas/PageSizeInteger"
                  description: The maximum number of items to retrieve from the GetEntitlements operation. For pagination, use the NextToken field in subsequent calls to GetEntitlements.
              required:
                - ProductCode
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetEntitlementsResult"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    ProductCode:
      type: string
      minLength: 1
      maxLength: 255
    GetEntitlementFilters:
      type: object
      properties: {}
    NonEmptyString:
      type: string
      pattern: \S+
    PageSizeInteger:
      type: integer
      minimum: 1
      maximum: 25
    GetEntitlementsResult:
      description: The GetEntitlementsRequest contains results from the GetEntitlements operation.
      type: object
      properties:
        Entitlements:
          $ref: "#/components/schemas/EntitlementList"
          description: The set of entitlements found through the GetEntitlements operation. If the result contains an empty set of entitlements, NextToken might still be present and should be used.
        NextToken:
          $ref: "#/components/schemas/NonEmptyString"
          description: For paginated results, use NextToken in subsequent calls to GetEntitlements. If the result contains an empty set of entitlements, NextToken might still be present and should be used.
    EntitlementList:
      type: array
      items:
        $ref: "#/components/schemas/Entitlement"
    Entitlement:
      description: An entitlement represents capacity in a product owned by the customer. For example, a customer might own some number of users or seats in an SaaS application or some amount of data capacity in a multi-tenant database.
      type: object
      properties:
        ProductCode:
          $ref: "#/components/schemas/ProductCode"
          description: The product code for which the given entitlement applies. Product codes are provided by AWS Marketplace when the product listing is created.
        Dimension:
          $ref: "#/components/schemas/NonEmptyString"
          description: The dimension for which the given entitlement applies. Dimensions represent categories of capacity in a product and are specified when the product is listed in AWS Marketplace.
        CustomerIdentifier:
          $ref: "#/components/schemas/NonEmptyString"
          description: The customer identifier is a handle to each unique customer in an application. Customer identifiers are obtained through the ResolveCustomer operation in AWS Marketplace Metering Service.
        CustomerAWSAccountId:
          $ref: "#/components/schemas/NonEmptyString"
          description: The CustomerAWSAccountId parameter specifies the AWS account ID of the buyer.
        Value:
          $ref: "#/components/schemas/EntitlementValue"
          description: The EntitlementValue represents the amount of capacity that the customer is entitled to for the product.
        ExpirationDate:
          $ref: "#/components/schemas/Timestamp"
          description: The expiration date represents the minimum date through which this entitlement is expected to remain valid. For contractual products listed on AWS Marketplace, the expiration date is the date at which the customer will renew or cancel their contract. Customers who are opting to renew their contract will still have entitlements with an expiration date.
        LicenseArn:
          $ref: "#/components/schemas/String"
          description: The LicenseArn is a unique identifier for a specific granted license. These are used for software purchased through AWS Marketplace.
    EntitlementValue:
      description: The EntitlementValue represents the amount of capacity that the customer is entitled to for the product.
      type: object
      properties:
        IntegerValue:
          $ref: "#/components/schemas/Integer"
          description: The IntegerValue field will be populated with an integer value when the entitlement is an integer type. Otherwise, the field will not be set.
        DoubleValue:
          $ref: "#/components/schemas/Double"
          description: The DoubleValue field will be populated with a double value when the entitlement is a double type. Otherwise, the field will not be set.
        BooleanValue:
          $ref: "#/components/schemas/Boolean"
          description: The BooleanValue field will be populated with a boolean value when the entitlement is a boolean type. Otherwise, the field will not be set.
        StringValue:
          $ref: "#/components/schemas/String"
          description: The StringValue field will be populated with a string value when the entitlement is a string type. Otherwise, the field will not be set.
    Integer:
      type: integer
    Double:
      type: number
      format: double
    Boolean:
      type: boolean
    String:
      type: string
    Timestamp:
      type: string
      format: date-time
  x-stackQL-resources:
    entitlements:
      id: aws.marketplace_entitlement.entitlements
      name: entitlements
      title: entitlements
      methods:
        get_entitlements:
          operation:
            $ref: "#/paths/~1GetEntitlements/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.Entitlements
          request:
            nativeCasing: pascal
            mediaType: application/x-amz-json-1.1
            base: "{}"
          config:
            pagination:
              requestToken:
                key: NextToken
                location: body
              responseToken:
                key: $.NextToken
                location: body
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/entitlements/methods/get_entitlements"
        insert: []
        update: []
        delete: []
