openapi: 3.0.0
info:
  version: "2017-09-01"
  title: AWS Elemental MediaStore Data Plane
  description: AWS Elemental MediaStore Data Plane
  x-serviceName: mediastore
  x-serviceAlias: mediastore_data
  x-protocol: rest-json
  x-apiVersion: "2017-09-01"
  x-endpointPrefix: data.mediastore
servers:
  - url: https://data.mediastore.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for mediastore-data
paths:
  /{path}:
    delete:
      operationId: DeleteObject
      description: Deletes an object at the specified path.
      parameters:
        - name: path
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/PathNaming"
          description: "The path (including the file name) where the object is stored in the container. Format: <folder name>/<folder name>/<file name>"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteObjectResponse"
    head:
      operationId: DescribeObject
      description: Gets the headers for an object at the specified path.
      parameters:
        - name: path
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/PathNaming"
          description: "The path (including the file name) where the object is stored in the container. Format: <folder name>/<folder name>/<file name>"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DescribeObjectResponse"
    get:
      operationId: GetObject
      description: Downloads the object at the specified path. If the object’s upload availability is set to streaming, AWS Elemental MediaStore downloads the object even if it’s still uploading the object.
      parameters:
        - name: path
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/PathNaming"
          description: "The path (including the file name) where the object is stored in the container. Format: <folder name>/<folder name>/<file name> For example, to upload the file mlaw.avi to the folder path premium\\canada in the container movies, enter the path premium/canada/mlaw.avi. Do not include the container name in this path. If the path includes any folders that don't exist yet, the service creates them. For example, suppose you have an existing premium/usa subfolder. If you specify premium/canada, the service creates a canada subfolder in the premium folder. You then have two subfolders, usa and canada, in the premium folder. There is no correlation between the path to the source and the path (folders) in the container in AWS Elemental MediaStore. For more information about folders and how they exist in a container, see the AWS Elemental MediaStore User Guide. The file name is the name that is assigned to the file that you upload. The file can have the same name inside and outside of AWS Elemental MediaStore, or it can have the same name. The file name can include or omit an extension."
        - name: Range
          in: header
          required: false
          schema:
            $ref: "#/components/schemas/RangePattern"
          description: The range bytes of an object to retrieve. For more information about the Range header, see http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35. AWS Elemental MediaStore ignores this header for partially uploaded objects that have streaming upload availability.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetObjectResponse"
    put:
      operationId: PutObject
      description: Uploads an object to the specified path. Object sizes are limited to 25 MB for standard upload availability and 10 MB for streaming upload availability.
      parameters:
        - name: path
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/PathNaming"
          description: "The path (including the file name) where the object is stored in the container. Format: <folder name>/<folder name>/<file name> For example, to upload the file mlaw.avi to the folder path premium\\canada in the container movies, enter the path premium/canada/mlaw.avi. Do not include the container name in this path. If the path includes any folders that don't exist yet, the service creates them. For example, suppose you have an existing premium/usa subfolder. If you specify premium/canada, the service creates a canada subfolder in the premium folder. You then have two subfolders, usa and canada, in the premium folder. There is no correlation between the path to the source and the path (folders) in the container in AWS Elemental MediaStore. For more information about folders and how they exist in a container, see the AWS Elemental MediaStore User Guide. The file name is the name that is assigned to the file that you upload. The file can have the same name inside and outside of AWS Elemental MediaStore, or it can have the same name. The file name can include or omit an extension."
        - name: Content-Type
          in: header
          required: false
          schema:
            $ref: "#/components/schemas/ContentType"
          description: The content type of the object.
        - name: Cache-Control
          in: header
          required: false
          schema:
            $ref: "#/components/schemas/StringPrimitive"
          description: An optional CacheControl header that allows the caller to control the object's cache behavior. Headers can be passed in as specified in the HTTP at https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9. Headers with a custom user-defined value are also accepted.
        - name: x-amz-storage-class
          in: header
          required: false
          schema:
            $ref: "#/components/schemas/StorageClass"
          description: Indicates the storage class of a Put request. Defaults to high-performance temporal storage class, and objects are persisted into durable storage shortly after being received.
        - name: x-amz-upload-availability
          in: header
          required: false
          schema:
            $ref: "#/components/schemas/UploadAvailability"
          description: Indicates the availability of an object while it is still uploading. If the value is set to streaming, the object is available for downloading after some initial buffering but before the object is uploaded completely. If the value is set to standard, the object is available for downloading only when it is uploaded completely. The default value for this header is standard. To use this header, you must also set the HTTP Transfer-Encoding header to chunked.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Body:
                  $ref: "#/components/schemas/PayloadBlob"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PutObjectResponse"
  /:
    get:
      operationId: ListItems
      description: Provides a list of metadata entries about folders and objects in the specified folder.
      parameters:
        - name: Path
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/ListPathNaming"
          description: "The path in the container from which to retrieve items. Format: <folder name>/<folder name>/<file name>"
        - name: MaxResults
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/ListLimit"
          description: The maximum number of results to return per API request. For example, you submit a ListItems request with MaxResults set at 500. Although 2,000 items match your request, the service returns no more than the first 500 items. (The service also returns a NextToken value that you can use to fetch the next batch of results.) The service might return fewer results than the MaxResults value. If MaxResults is not included in the request, the service defaults to pagination with a maximum of 1,000 results per page.
        - name: NextToken
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/PaginationToken"
          description: The token that identifies which batch of results that you want to see. For example, you submit a ListItems request with MaxResults set at 500. The service returns the first batch of results (up to 500) and a NextToken value. To see the next batch of results, you can submit the ListItems request a second time and specify the NextToken value. Tokens expire after 15 minutes.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListItemsResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    PathNaming:
      type: string
      minLength: 1
      maxLength: 900
      pattern: (?:[A-Za-z0-9_\.\-\~]+/){0,10}[A-Za-z0-9_\.\-\~]+
    DeleteObjectResponse:
      type: object
    DescribeObjectResponse:
      type: object
      properties:
        ETag:
          $ref: "#/components/schemas/ETag"
          description: The ETag that represents a unique instance of the object.
        ContentType:
          $ref: "#/components/schemas/ContentType"
          description: The content type of the object.
        ContentLength:
          $ref: "#/components/schemas/NonNegativeLong"
          description: The length of the object in bytes.
        CacheControl:
          $ref: "#/components/schemas/StringPrimitive"
          description: An optional CacheControl header that allows the caller to control the object's cache behavior. Headers can be passed in as specified in the HTTP at https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9. Headers with a custom user-defined value are also accepted.
        LastModified:
          $ref: "#/components/schemas/TimeStamp"
          description: The date and time that the object was last modified.
    ETag:
      type: string
      minLength: 1
      maxLength: 64
      pattern: "[0-9A-Fa-f]+"
    ContentType:
      type: string
      pattern: ^[\w\-\/\.\+]{1,255}$
    NonNegativeLong:
      type: integer
      format: int64
      minimum: 0
    StringPrimitive:
      type: string
    TimeStamp:
      type: string
      format: date-time
    RangePattern:
      type: string
      pattern: ^bytes=(?:\d+\-\d*|\d*\-\d+)$
    GetObjectResponse:
      type: object
      properties:
        Body:
          $ref: "#/components/schemas/PayloadBlob"
          description: The bytes of the object.
        CacheControl:
          $ref: "#/components/schemas/StringPrimitive"
          description: An optional CacheControl header that allows the caller to control the object's cache behavior. Headers can be passed in as specified in the HTTP spec at https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9. Headers with a custom user-defined value are also accepted.
        ContentRange:
          $ref: "#/components/schemas/ContentRangePattern"
          description: The range of bytes to retrieve.
        ContentLength:
          $ref: "#/components/schemas/NonNegativeLong"
          description: The length of the object in bytes.
        ContentType:
          $ref: "#/components/schemas/ContentType"
          description: The content type of the object.
        ETag:
          $ref: "#/components/schemas/ETag"
          description: The ETag that represents a unique instance of the object.
        LastModified:
          $ref: "#/components/schemas/TimeStamp"
          description: The date and time that the object was last modified.
        StatusCode:
          $ref: "#/components/schemas/statusCode"
          description: The HTML status code of the request. Status codes ranging from 200 to 299 indicate success. All other status codes indicate the type of error that occurred.
      required:
        - StatusCode
    PayloadBlob:
      type: string
      format: byte
    ContentRangePattern:
      type: string
      pattern: ^bytes=\d+\-\d+/\d+$
    statusCode:
      type: integer
    ListPathNaming:
      type: string
      minLength: 0
      maxLength: 900
      pattern: /?(?:[A-Za-z0-9_\.\-\~]+/){0,10}(?:[A-Za-z0-9_\.\-\~]+)?/?
    ListLimit:
      type: integer
      minimum: 1
      maximum: 1000
    PaginationToken:
      type: string
    ListItemsResponse:
      type: object
      properties:
        Items:
          $ref: "#/components/schemas/ItemList"
          description: The metadata entries for the folders and objects at the requested path.
        NextToken:
          $ref: "#/components/schemas/PaginationToken"
          description: The token that can be used in a request to view the next set of results. For example, you submit a ListItems request that matches 2,000 items with MaxResults set at 500. The service returns the first batch of results (up to 500) and a NextToken value that can be used to fetch the next batch of results.
    ItemList:
      type: array
      items:
        $ref: "#/components/schemas/Item"
    Item:
      description: A metadata entry for a folder or object.
      type: object
      properties:
        Name:
          $ref: "#/components/schemas/ItemName"
          description: The name of the item.
        Type:
          $ref: "#/components/schemas/ItemType"
          description: The item type (folder or object).
        ETag:
          $ref: "#/components/schemas/ETag"
          description: The ETag that represents a unique instance of the item.
        LastModified:
          $ref: "#/components/schemas/TimeStamp"
          description: The date and time that the item was last modified.
        ContentType:
          $ref: "#/components/schemas/ContentType"
          description: The content type of the item.
        ContentLength:
          $ref: "#/components/schemas/NonNegativeLong"
          description: The length of the item in bytes.
    ItemName:
      type: string
      pattern: "[A-Za-z0-9_\\.\\-\\~]+"
    ItemType:
      type: string
      enum:
        - OBJECT
        - FOLDER
    StorageClass:
      type: string
      enum:
        - TEMPORAL
      minLength: 1
      maxLength: 16
    UploadAvailability:
      type: string
      enum:
        - STANDARD
        - STREAMING
      minLength: 1
      maxLength: 16
    PutObjectResponse:
      type: object
      properties:
        ContentSHA256:
          $ref: "#/components/schemas/SHA256Hash"
          description: The SHA256 digest of the object that is persisted.
        ETag:
          $ref: "#/components/schemas/ETag"
          description: Unique identifier of the object in the container.
        StorageClass:
          $ref: "#/components/schemas/StorageClass"
          description: The storage class where the object was persisted. The class should be “Temporal”.
    SHA256Hash:
      type: string
      minLength: 64
      maxLength: 64
      pattern: "[0-9A-Fa-f]{64}"
  x-stackQL-resources:
    objects:
      id: aws.mediastore_data.objects
      name: objects
      title: objects
      methods:
        delete_object:
          operation:
            $ref: "#/paths/~1{path}/delete"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        describe_object:
          operation:
            $ref: "#/paths/~1{path}/head"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        get_object:
          operation:
            $ref: "#/paths/~1{path}/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        put_object:
          operation:
            $ref: "#/paths/~1{path}/put"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/objects/methods/describe_object"
        insert: []
        update: []
        replace:
          - $ref: "#/components/x-stackQL-resources/objects/methods/put_object"
        delete:
          - $ref: "#/components/x-stackQL-resources/objects/methods/delete_object"
    items:
      id: aws.mediastore_data.items
      name: items
      title: items
      methods:
        list_items:
          operation:
            $ref: "#/paths/~1/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.Items
          request:
            nativeCasing: pascal
          config:
            pagination:
              requestToken:
                key: NextToken
                location: query
              responseToken:
                key: $.NextToken
                location: body
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/items/methods/list_items"
        insert: []
        update: []
        delete: []
