openapi: 3.0.0
info:
  version: "2019-06-30"
  title: AWS Migration Hub Config
  description: AWS Migration Hub Config
  x-serviceName: mgh
  x-serviceAlias: migrationhub_config
  x-protocol: json
  x-apiVersion: "2019-06-30"
  x-endpointPrefix: migrationhub-config
  x-targetPrefix: AWSMigrationHubMultiAccountService
  x-jsonVersion: "1.1"
servers:
  - url: https://migrationhub-config.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for migrationhub-config
paths:
  /CreateHomeRegionControl:
    post:
      operationId: CreateHomeRegionControl
      description: This API sets up the home region for the calling account only.
      parameters:
        - name: X-Amz-Target
          in: header
          description: Action Header
          required: false
          schema:
            type: string
            enum:
              - AWSMigrationHubMultiAccountService.CreateHomeRegionControl
            default: AWSMigrationHubMultiAccountService.CreateHomeRegionControl
      requestBody:
        required: true
        content:
          application/x-amz-json-1.1:
            schema:
              type: object
              properties:
                HomeRegion:
                  $ref: "#/components/schemas/HomeRegion"
                  description: The name of the home region of the calling account.
                Target:
                  $ref: "#/components/schemas/Target"
                  description: The account for which this command sets up a home region control. The Target is always of type ACCOUNT.
                DryRun:
                  $ref: "#/components/schemas/DryRun"
                  description: Optional Boolean flag to indicate whether any effect should take place. It tests whether the caller has permission to make the call.
              required:
                - HomeRegion
                - Target
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateHomeRegionControlResult"
  /DeleteHomeRegionControl:
    post:
      operationId: DeleteHomeRegionControl
      description: This operation deletes the home region configuration for the calling account. The operation does not delete discovery or migration tracking data in the home region.
      parameters:
        - name: X-Amz-Target
          in: header
          description: Action Header
          required: false
          schema:
            type: string
            enum:
              - AWSMigrationHubMultiAccountService.DeleteHomeRegionControl
            default: AWSMigrationHubMultiAccountService.DeleteHomeRegionControl
      requestBody:
        required: true
        content:
          application/x-amz-json-1.1:
            schema:
              type: object
              properties:
                ControlId:
                  $ref: "#/components/schemas/ControlId"
                  description: A unique identifier that's generated for each home region control. It's always a string that begins with "hrc-" followed by 12 lowercase letters and numbers.
              required:
                - ControlId
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteHomeRegionControlResult"
  /DescribeHomeRegionControls:
    post:
      operationId: DescribeHomeRegionControls
      description: This API permits filtering on the ControlId and HomeRegion fields.
      parameters:
        - name: X-Amz-Target
          in: header
          description: Action Header
          required: false
          schema:
            type: string
            enum:
              - AWSMigrationHubMultiAccountService.DescribeHomeRegionControls
            default: AWSMigrationHubMultiAccountService.DescribeHomeRegionControls
      requestBody:
        required: true
        content:
          application/x-amz-json-1.1:
            schema:
              type: object
              properties:
                ControlId:
                  $ref: "#/components/schemas/ControlId"
                  description: The ControlID is a unique identifier string of your HomeRegionControl object.
                HomeRegion:
                  $ref: "#/components/schemas/HomeRegion"
                  description: The name of the home region you'd like to view.
                Target:
                  $ref: "#/components/schemas/Target"
                  description: The target parameter specifies the identifier to which the home region is applied, which is always of type ACCOUNT. It applies the home region to the current ACCOUNT.
                MaxResults:
                  $ref: "#/components/schemas/DescribeHomeRegionControlsMaxResults"
                  description: The maximum number of filtering results to display per page.
                NextToken:
                  $ref: "#/components/schemas/Token"
                  description: If a NextToken was returned by a previous call, more results are available. To retrieve the next page of results, make the call again using the returned token in NextToken.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DescribeHomeRegionControlsResult"
  /GetHomeRegion:
    post:
      operationId: GetHomeRegion
      description: Returns the calling account’s home region, if configured. This API is used by other AWS services to determine the regional endpoint for calling AWS Application Discovery Service and Migration Hub. You must call GetHomeRegion at least once before you call any other AWS Application Discovery Service and AWS Migration Hub APIs, to obtain the account's Migration Hub home region.
      parameters:
        - name: X-Amz-Target
          in: header
          description: Action Header
          required: false
          schema:
            type: string
            enum:
              - AWSMigrationHubMultiAccountService.GetHomeRegion
            default: AWSMigrationHubMultiAccountService.GetHomeRegion
      requestBody:
        required: true
        content:
          application/x-amz-json-1.1:
            schema:
              type: object
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetHomeRegionResult"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    HomeRegion:
      type: string
      minLength: 1
      maxLength: 50
      pattern: ^([a-z]+)-([a-z]+)-([0-9]+)$
    Target:
      description: The target parameter specifies the identifier to which the home region is applied, which is always an ACCOUNT. It applies the home region to the current ACCOUNT.
      type: object
      properties:
        Type:
          $ref: "#/components/schemas/TargetType"
          description: The target type is always an ACCOUNT.
        Id:
          $ref: "#/components/schemas/TargetId"
          description: The TargetID is a 12-character identifier of the ACCOUNT for which the control was created. (This must be the current account.)
      required:
        - Type
    TargetType:
      type: string
      enum:
        - ACCOUNT
    TargetId:
      type: string
      minLength: 12
      maxLength: 12
      pattern: ^\d{12}$
    DryRun:
      type: boolean
    CreateHomeRegionControlResult:
      type: object
      properties:
        HomeRegionControl:
          $ref: "#/components/schemas/HomeRegionControl"
          description: This object is the HomeRegionControl object that's returned by a successful call to CreateHomeRegionControl.
    HomeRegionControl:
      description: A home region control is an object that specifies the home region for an account, with some additional information. It contains a target (always of type ACCOUNT), an ID, and a time at which the home region was set.
      type: object
      properties:
        ControlId:
          $ref: "#/components/schemas/ControlId"
          description: A unique identifier that's generated for each home region control. It's always a string that begins with "hrc-" followed by 12 lowercase letters and numbers.
        HomeRegion:
          $ref: "#/components/schemas/HomeRegion"
          description: The AWS Region that's been set as home region. For example, "us-west-2" or "eu-central-1" are valid home regions.
        Target:
          $ref: "#/components/schemas/Target"
          description: The target parameter specifies the identifier to which the home region is applied, which is always an ACCOUNT. It applies the home region to the current ACCOUNT.
        RequestedTime:
          $ref: "#/components/schemas/RequestedTime"
          description: A timestamp representing the time when the customer called CreateHomeregionControl and set the home region for the account.
    ControlId:
      type: string
      minLength: 1
      maxLength: 50
      pattern: ^hrc-[a-z0-9]{12}$
    RequestedTime:
      type: string
      format: date-time
    DeleteHomeRegionControlResult:
      type: object
    DescribeHomeRegionControlsMaxResults:
      type: integer
      minimum: 1
      maximum: 100
    Token:
      type: string
      minLength: 0
      maxLength: 2048
      pattern: ^[a-zA-Z0-9\/\+\=]{0,2048}$
    DescribeHomeRegionControlsResult:
      type: object
      properties:
        HomeRegionControls:
          $ref: "#/components/schemas/HomeRegionControls"
          description: An array that contains your HomeRegionControl objects.
        NextToken:
          $ref: "#/components/schemas/Token"
          description: If a NextToken was returned by a previous call, more results are available. To retrieve the next page of results, make the call again using the returned token in NextToken.
    HomeRegionControls:
      type: array
      items:
        $ref: "#/components/schemas/HomeRegionControl"
    GetHomeRegionResult:
      type: object
      properties:
        HomeRegion:
          $ref: "#/components/schemas/HomeRegion"
          description: The name of the home region of the calling account.
  x-stackQL-resources:
    home_region_controls:
      id: aws.migrationhub_config.home_region_controls
      name: home_region_controls
      title: home_region_controls
      methods:
        create_home_region_control:
          operation:
            $ref: "#/paths/~1CreateHomeRegionControl/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
            mediaType: application/x-amz-json-1.1
            base: "{}"
          config:
            requestBodyTranslate:
              algorithm: naive
        delete_home_region_control:
          operation:
            $ref: "#/paths/~1DeleteHomeRegionControl/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
            mediaType: application/x-amz-json-1.1
            base: "{}"
          config:
            requestBodyTranslate:
              algorithm: naive
        describe_home_region_controls:
          operation:
            $ref: "#/paths/~1DescribeHomeRegionControls/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
            mediaType: application/x-amz-json-1.1
            base: "{}"
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/home_region_controls/methods/describe_home_region_controls"
        insert:
          - $ref: "#/components/x-stackQL-resources/home_region_controls/methods/create_home_region_control"
        update: []
        delete:
          - $ref: "#/components/x-stackQL-resources/home_region_controls/methods/delete_home_region_control"
    home_regions:
      id: aws.migrationhub_config.home_regions
      name: home_regions
      title: home_regions
      methods:
        get_home_region:
          operation:
            $ref: "#/paths/~1GetHomeRegion/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
            mediaType: application/x-amz-json-1.1
            base: "{}"
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/home_regions/methods/get_home_region"
        insert: []
        update: []
        delete: []
