openapi: 3.0.0
info:
  version: "2018-05-10"
  title: AWS User Notifications Contacts
  description: AWS User Notifications Contacts
  x-serviceName: notifications-contacts
  x-serviceAlias: notificationscontacts
  x-protocol: rest-json
  x-apiVersion: "2018-05-10"
  x-endpointPrefix: notifications-contacts
servers:
  - url: https://notifications-contacts.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for notificationscontacts
paths:
  /emailcontacts/{arn}/activate/{code}:
    put:
      operationId: ActivateEmailContact
      description: Activates an email contact using an activation code. This code is in the activation email sent to the email address associated with this email contact.
      parameters:
        - name: arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/EmailContactArn"
          description: The Amazon Resource Name (ARN) of the resource.
        - name: code
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Token"
          description: The activation code for this email contact. An email contact has a maximum of five activation attempts. Activation codes expire after 12 hours and are generated by the SendActivationCode API action.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ActivateEmailContactResponse"
  /2022-09-19/emailcontacts:
    post:
      operationId: CreateEmailContact
      description: Creates an email contact for the provided email address.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/EmailContactName"
                emailAddress:
                  $ref: "#/components/schemas/EmailContactAddress"
                tags:
                  $ref: "#/components/schemas/TagMap"
              required:
                - name
                - emailAddress
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateEmailContactResponse"
  /emailcontacts/{arn}:
    delete:
      operationId: DeleteEmailContact
      description: Deletes an email contact. Deleting an email contact removes it from all associated notification configurations.
      parameters:
        - name: arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/EmailContactArn"
          description: The Amazon Resource Name (ARN) of the resource.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteEmailContactResponse"
    get:
      operationId: GetEmailContact
      description: Returns an email contact.
      parameters:
        - name: arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/EmailContactArn"
          description: The Amazon Resource Name (ARN) of the email contact to get.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetEmailContactResponse"
  /emailcontacts:
    get:
      operationId: ListEmailContacts
      description: Lists all email contacts created under the Account.
      parameters:
        - name: maxResults
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/ListEmailContactsRequestMaxResultsInteger"
          description: The maximum number of results to include in the response. If more results exist than the specified MaxResults value, a token is included in the response so that the remaining results can be retrieved.
        - name: nextToken
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/String"
          description: An optional token returned from a prior request. Use this token for pagination of results from this action. If this parameter is specified, the response includes only results beyond the token, up to the value specified by MaxResults.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListEmailContactsResponse"
  /tags/{arn}:
    get:
      operationId: ListTagsForResource
      description: Lists all of the tags associated with the Amazon Resource Name (ARN) that you specify. The resource can be a user, server, or role.
      parameters:
        - name: arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/EmailContactArn"
          description: The ARN you specified to list the tags of.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListTagsForResourceResponse"
    post:
      operationId: TagResource
      description: Attaches a key-value pair to a resource, as identified by its Amazon Resource Name (ARN). Taggable resources in AWS User Notifications Contacts include email contacts.
      parameters:
        - name: arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/EmailContactArn"
          description: The ARN of the configuration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tags:
                  $ref: "#/components/schemas/TagMap"
              required:
                - tags
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TagResourceResponse"
    delete:
      operationId: UntagResource
      description: Detaches a key-value pair from a resource, as identified by its Amazon Resource Name (ARN). Taggable resources in AWS User Notifications Contacts include email contacts..
      parameters:
        - name: arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/EmailContactArn"
          description: The value of the resource that will have the tag removed. An Amazon Resource Name (ARN) is an identifier for a specific AWS resource, such as a server, user, or role.
        - name: tagKeys
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/TagKeys"
          description: Specifies a list of tag keys that you want to remove from the specified resources.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UntagResourceResponse"
  /2022-10-31/emailcontacts/{arn}/activate/send:
    post:
      operationId: SendActivationCode
      description: Sends an activation email to the email address associated with the specified email contact. It might take a few minutes for the activation email to arrive. If it doesn't arrive, check in your spam folder or try sending another activation email.
      parameters:
        - name: arn
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/EmailContactArn"
          description: The Amazon Resource Name (ARN) of the resource.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SendActivationCodeResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    EmailContactArn:
      type: string
      pattern: arn:aws:notifications-contacts::[0-9]{12}:emailcontact/[a-z0-9]{27}
    Token:
      type: string
      minLength: 7
      maxLength: 7
      pattern: "[a-z0-9]{7}"
    ActivateEmailContactResponse:
      type: object
    EmailContactName:
      type: string
      minLength: 1
      maxLength: 64
      pattern: .*[\w-.~]+.*
    EmailContactAddress:
      type: string
      minLength: 6
      maxLength: 254
      pattern: (.+)@(.+)
    TagMap:
      description: Map of tags assigned to a resource
      type: object
      properties: {}
    CreateEmailContactResponse:
      type: object
      properties:
        arn:
          $ref: "#/components/schemas/EmailContactArn"
          description: The Amazon Resource Name (ARN) of the resource.
      required:
        - arn
    DeleteEmailContactResponse:
      type: object
    GetEmailContactResponse:
      type: object
      properties:
        emailContact:
          $ref: "#/components/schemas/EmailContact"
          description: The email contact for the provided email address.
      required:
        - emailContact
    EmailContact:
      description: An email contact.
      type: object
      properties:
        arn:
          $ref: "#/components/schemas/EmailContactArn"
          description: The Amazon Resource Name (ARN) of the email contact.
        name:
          $ref: "#/components/schemas/EmailContactName"
          description: The name of the email contact.
        address:
          $ref: "#/components/schemas/SensitiveEmailContactAddress"
          description: The email address this email contact points to. The activation email and any subscribed emails are sent here.
        status:
          $ref: "#/components/schemas/EmailContactStatus"
          description: The status of the email contact. Only activated email contacts receive emails.
        creationTime:
          $ref: "#/components/schemas/CreationTime"
          description: The creation time of the resource.
        updateTime:
          $ref: "#/components/schemas/UpdateTime"
          description: The time the resource was last updated.
      required:
        - arn
        - name
        - address
        - status
        - creationTime
        - updateTime
    SensitiveEmailContactAddress:
      type: string
      minLength: 6
      maxLength: 254
      pattern: (.+)@(.+)
    EmailContactStatus:
      type: string
      enum:
        - inactive
        - active
    CreationTime:
      type: string
      format: date-time
    UpdateTime:
      type: string
      format: date-time
    ListEmailContactsRequestMaxResultsInteger:
      type: integer
      minimum: 1
      maximum: 100
    String:
      type: string
    ListEmailContactsResponse:
      type: object
      properties:
        nextToken:
          $ref: "#/components/schemas/String"
          description: An optional token returned from a prior request. Use this token for pagination of results from this action. If this parameter is specified, the response includes only results beyond the token, up to the value specified by MaxResults.
        emailContacts:
          $ref: "#/components/schemas/EmailContacts"
          description: A list of email contacts.
      required:
        - emailContacts
    EmailContacts:
      type: array
      items:
        $ref: "#/components/schemas/EmailContact"
    ListTagsForResourceResponse:
      type: object
      properties:
        tags:
          type: object
          properties: {}
          description: Key-value pairs that are assigned to a resource, usually for the purpose of grouping and searching for items. Tags are metadata that you define.
    SendActivationCodeResponse:
      type: object
    TagResourceResponse:
      type: object
    TagKeys:
      type: array
      items:
        $ref: "#/components/schemas/TagKey"
    TagKey:
      type: string
      pattern: (?!aws:).{1,128}
    UntagResourceResponse:
      type: object
  x-stackQL-resources:
    email_contacts:
      id: aws.notificationscontacts.email_contacts
      name: email_contacts
      title: email_contacts
      methods:
        create_email_contact:
          operation:
            $ref: "#/paths/~12022-09-19~1emailcontacts/post"
          response:
            openAPIDocKey: "201"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
        delete_email_contact:
          operation:
            $ref: "#/paths/~1emailcontacts~1{arn}/delete"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        get_email_contact:
          operation:
            $ref: "#/paths/~1emailcontacts~1{arn}/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.emailContact
        list_email_contacts:
          operation:
            $ref: "#/paths/~1emailcontacts/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.emailContacts
          request:
            nativeCasing: pascal
          config:
            pagination:
              requestToken:
                key: nextToken
                location: query
              responseToken:
                key: $.nextToken
                location: body
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/email_contacts/methods/get_email_contact"
          - $ref: "#/components/x-stackQL-resources/email_contacts/methods/list_email_contacts"
        insert:
          - $ref: "#/components/x-stackQL-resources/email_contacts/methods/create_email_contact"
        update: []
        delete:
          - $ref: "#/components/x-stackQL-resources/email_contacts/methods/delete_email_contact"
    tags:
      id: aws.notificationscontacts.tags
      name: tags
      title: tags
      methods:
        list_tags_for_resource:
          operation:
            $ref: "#/paths/~1tags~1{arn}/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        tag_resource:
          operation:
            $ref: "#/paths/~1tags~1{arn}/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
        untag_resource:
          operation:
            $ref: "#/paths/~1tags~1{arn}/delete"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/tags/methods/list_tags_for_resource"
        insert: []
        update:
          - $ref: "#/components/x-stackQL-resources/tags/methods/tag_resource"
          - $ref: "#/components/x-stackQL-resources/tags/methods/untag_resource"
        delete: []
