openapi: 3.0.0
info:
  title: Oam
  version: 1.0.0
paths: {}
components:
  schemas:
    ResourceType:
      type: string
      enum:
        - AWS::CloudWatch::Metric
        - AWS::Logs::LogGroup
        - AWS::XRay::Trace
    Link:
      type: object
      properties:
        Arn:
          type: string
          maxLength: 2048
        Label:
          type: string
        LabelTemplate:
          type: string
          maxLength: 64
          minLength: 1
        ResourceTypes:
          type: array
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/ResourceType'
          maxItems: 50
          minItems: 1
          uniqueItems: true
        SinkIdentifier:
          type: string
          maxLength: 2048
          minLength: 1
        Tags:
          description: Tags to apply to the link
          type: object
          additionalProperties: false
          x-patternProperties:
            ^(?!aws:.*)[a-zA-Z0-9\s\_\.\/\=\+\-]{1,128}$:
              type: string
              description: 'The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
              pattern: ^(?!aws:.*)[a-zA-Z0-9\s\_\.\/\=\+\-]{0,256}$
              minLength: 0
              maxLength: 256
      required:
        - ResourceTypes
        - SinkIdentifier
      x-stackql-resource-name: link
      x-stackql-primaryIdentifier:
        - Arn
    Sink:
      type: object
      properties:
        Arn:
          description: The Amazon resource name (ARN) of the ObservabilityAccessManager Sink
          type: string
          maxLength: 2048
        Name:
          description: The name of the ObservabilityAccessManager Sink.
          type: string
          minLength: 1
          maxLength: 255
          pattern: ^[a-zA-Z0-9_.-]+$
        Policy:
          description: The policy of this ObservabilityAccessManager Sink.
          type: object
        Tags:
          description: Tags to apply to the sink
          type: object
          additionalProperties: false
          x-patternProperties:
            ^(?!aws:.*)[a-zA-Z0-9\s\_\.\/\=\+\-]{1,128}$:
              type: string
              description: 'The value for the tag. You can specify a value that is 0 to 256 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -.'
              pattern: ^(?!aws:.*)[a-zA-Z0-9\s\_\.\/\=\+\-]{0,256}$
              minLength: 0
              maxLength: 256
      required:
        - Name
      x-stackql-resource-name: sink
      x-stackql-primaryIdentifier:
        - Arn
  x-stackQL-resources:
    links:
      name: links
      id: aws.oam.links
      x-cfn-schema-name: Link
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Oam::Link'
    link:
      name: link
      id: aws.oam.link
      x-cfn-schema-name: Link
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Label') as label,
              JSON_EXTRACT(Properties, '$.LabelTemplate') as label_template,
              JSON_EXTRACT(Properties, '$.ResourceTypes') as resource_types,
              JSON_EXTRACT(Properties, '$.SinkIdentifier') as sink_identifier,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Oam::Link'
    sinks:
      name: sinks
      id: aws.oam.sinks
      x-cfn-schema-name: Sink
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Oam::Sink'
    sink:
      name: sink
      id: aws.oam.sink
      x-cfn-schema-name: Sink
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Policy') as policy,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Oam::Sink'
