openapi: 3.0.0
info:
  title: OpenSearchService
  version: 1.0.0
paths: {}
components:
  schemas:
    ZoneAwarenessConfig:
      type: object
      additionalProperties: false
      properties:
        AvailabilityZoneCount:
          type: integer
    ClusterConfig:
      type: object
      additionalProperties: false
      properties:
        InstanceCount:
          type: integer
        WarmEnabled:
          type: boolean
        WarmCount:
          type: integer
        DedicatedMasterEnabled:
          type: boolean
        ZoneAwarenessConfig:
          $ref: '#/components/schemas/ZoneAwarenessConfig'
        DedicatedMasterCount:
          type: integer
        InstanceType:
          type: string
        WarmType:
          type: string
        ZoneAwarenessEnabled:
          type: boolean
        DedicatedMasterType:
          type: string
    LogPublishingOption:
      type: object
      additionalProperties: false
      properties:
        CloudWatchLogsLogGroupArn:
          type: string
        Enabled:
          type: boolean
    SnapshotOptions:
      type: object
      additionalProperties: false
      properties:
        AutomatedSnapshotStartHour:
          type: integer
    VPCOptions:
      type: object
      additionalProperties: false
      properties:
        SecurityGroupIds:
          type: array
          uniqueItems: true
          items:
            type: string
        SubnetIds:
          type: array
          uniqueItems: true
          items:
            type: string
    NodeToNodeEncryptionOptions:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
    DomainEndpointOptions:
      type: object
      additionalProperties: false
      properties:
        CustomEndpointCertificateArn:
          type: string
        CustomEndpointEnabled:
          type: boolean
        EnforceHTTPS:
          type: boolean
        CustomEndpoint:
          type: string
        TLSSecurityPolicy:
          type: string
    CognitoOptions:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
        IdentityPoolId:
          type: string
        UserPoolId:
          type: string
        RoleArn:
          type: string
    MasterUserOptions:
      type: object
      additionalProperties: false
      properties:
        MasterUserPassword:
          type: string
        MasterUserName:
          type: string
        MasterUserARN:
          type: string
    Idp:
      type: object
      additionalProperties: false
      properties:
        MetadataContent:
          type: string
          maxLength: 20480
          minLength: 1
        EntityId:
          type: string
      required:
        - MetadataContent
        - EntityId
    SAMLOptions:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
        Idp:
          $ref: '#/components/schemas/Idp'
        MasterUserName:
          type: string
        MasterBackendRole:
          type: string
        SubjectKey:
          type: string
        RolesKey:
          type: string
        SessionTimeoutMinutes:
          type: integer
    AdvancedSecurityOptionsInput:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
        MasterUserOptions:
          $ref: '#/components/schemas/MasterUserOptions'
        InternalUserDatabaseEnabled:
          type: boolean
        AnonymousAuthEnabled:
          type: boolean
        SAMLOptions:
          $ref: '#/components/schemas/SAMLOptions'
        AnonymousAuthDisableDate:
          type: string
    EBSOptions:
      type: object
      additionalProperties: false
      properties:
        EBSEnabled:
          type: boolean
        VolumeType:
          type: string
        Iops:
          type: integer
        VolumeSize:
          type: integer
        Throughput:
          type: integer
    EncryptionAtRestOptions:
      type: object
      additionalProperties: false
      properties:
        KmsKeyId:
          type: string
        Enabled:
          type: boolean
    Tag:
      type: object
      additionalProperties: false
      properties:
        Value:
          description: The key of the tag.
          type: string
          minLength: 0
          maxLength: 256
        Key:
          description: The value of the tag.
          type: string
          minLength: 0
          maxLength: 128
      required:
        - Value
        - Key
    ServiceSoftwareOptions:
      type: object
      additionalProperties: false
      properties:
        CurrentVersion:
          type: string
        NewVersion:
          type: string
        UpdateAvailable:
          type: boolean
        Cancellable:
          type: boolean
        UpdateStatus:
          type: string
        Description:
          type: string
        AutomatedUpdateDate:
          type: string
        OptionalDeployment:
          type: boolean
    WindowStartTime:
      type: object
      additionalProperties: false
      properties:
        Hours:
          type: integer
          minimum: 0
          maximum: 23
        Minutes:
          type: integer
          minimum: 0
          maximum: 59
      required:
        - Hours
        - Minutes
    OffPeakWindow:
      type: object
      additionalProperties: false
      properties:
        WindowStartTime:
          $ref: '#/components/schemas/WindowStartTime'
    OffPeakWindowOptions:
      type: object
      additionalProperties: false
      properties:
        Enabled:
          type: boolean
        OffPeakWindow:
          $ref: '#/components/schemas/OffPeakWindow'
    SoftwareUpdateOptions:
      type: object
      additionalProperties: false
      properties:
        AutoSoftwareUpdateEnabled:
          type: boolean
    Domain:
      type: object
      properties:
        ClusterConfig:
          $ref: '#/components/schemas/ClusterConfig'
        DomainName:
          type: string
        AccessPolicies:
          type: object
        EngineVersion:
          type: string
        AdvancedOptions:
          type: object
          additionalProperties: false
          x-patternProperties:
            '[a-zA-Z0-9]+':
              type: string
        LogPublishingOptions:
          type: object
          additionalProperties: false
          x-patternProperties:
            '[a-zA-Z0-9]+':
              $ref: '#/components/schemas/LogPublishingOption'
        SnapshotOptions:
          $ref: '#/components/schemas/SnapshotOptions'
        VPCOptions:
          $ref: '#/components/schemas/VPCOptions'
        NodeToNodeEncryptionOptions:
          $ref: '#/components/schemas/NodeToNodeEncryptionOptions'
        DomainEndpointOptions:
          $ref: '#/components/schemas/DomainEndpointOptions'
        CognitoOptions:
          $ref: '#/components/schemas/CognitoOptions'
        AdvancedSecurityOptions:
          $ref: '#/components/schemas/AdvancedSecurityOptionsInput'
        DomainEndpoint:
          type: string
        DomainEndpoints:
          type: object
          additionalProperties: false
          x-patternProperties:
            ^.*$:
              type: string
        EBSOptions:
          $ref: '#/components/schemas/EBSOptions'
        Id:
          type: string
        Arn:
          type: string
        DomainArn:
          type: string
        EncryptionAtRestOptions:
          $ref: '#/components/schemas/EncryptionAtRestOptions'
        Tags:
          description: An arbitrary set of tags (key-value pairs) for this Domain.
          items:
            $ref: '#/components/schemas/Tag'
          type: array
          uniqueItems: true
        ServiceSoftwareOptions:
          $ref: '#/components/schemas/ServiceSoftwareOptions'
        OffPeakWindowOptions:
          $ref: '#/components/schemas/OffPeakWindowOptions'
        SoftwareUpdateOptions:
          $ref: '#/components/schemas/SoftwareUpdateOptions'
      x-stackql-resource-name: domain
      x-stackql-primaryIdentifier:
        - DomainName
  x-stackQL-resources:
    domains:
      name: domains
      id: aws.opensearchservice.domains
      x-cfn-schema-name: Domain
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.DomainName') as domain_name
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::OpenSearchService::Domain'
    domain:
      name: domain
      id: aws.opensearchservice.domain
      x-cfn-schema-name: Domain
      x-type: get
      x-identifiers:
        - DomainName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ClusterConfig.InstanceCount') as cluster_config_instance_count,
              JSON_EXTRACT(Properties, '$.ClusterConfig.WarmEnabled') as cluster_config_warm_enabled,
              JSON_EXTRACT(Properties, '$.ClusterConfig.WarmCount') as cluster_config_warm_count,
              JSON_EXTRACT(Properties, '$.ClusterConfig.DedicatedMasterEnabled') as cluster_config_dedicated_master_enabled,
              JSON_EXTRACT(Properties, '$.ClusterConfig.ZoneAwarenessConfig') as cluster_config_zone_awareness_config,
              JSON_EXTRACT(Properties, '$.ClusterConfig.DedicatedMasterCount') as cluster_config_dedicated_master_count,
              JSON_EXTRACT(Properties, '$.ClusterConfig.InstanceType') as cluster_config_instance_type,
              JSON_EXTRACT(Properties, '$.ClusterConfig.WarmType') as cluster_config_warm_type,
              JSON_EXTRACT(Properties, '$.ClusterConfig.ZoneAwarenessEnabled') as cluster_config_zone_awareness_enabled,
              JSON_EXTRACT(Properties, '$.ClusterConfig.DedicatedMasterType') as cluster_config_dedicated_master_type,
              JSON_EXTRACT(Properties, '$.DomainName') as domain_name,
              JSON_EXTRACT(Properties, '$.AccessPolicies') as access_policies,
              JSON_EXTRACT(Properties, '$.EngineVersion') as engine_version,
              JSON_EXTRACT(Properties, '$.AdvancedOptions') as advanced_options,
              JSON_EXTRACT(Properties, '$.LogPublishingOptions') as log_publishing_options,
              JSON_EXTRACT(Properties, '$.SnapshotOptions.AutomatedSnapshotStartHour') as snapshot_options_automated_snapshot_start_hour,
              JSON_EXTRACT(Properties, '$.VPCOptions.SecurityGroupIds') as v_pc_options_security_group_ids,
              JSON_EXTRACT(Properties, '$.VPCOptions.SubnetIds') as v_pc_options_subnet_ids,
              JSON_EXTRACT(Properties, '$.NodeToNodeEncryptionOptions.Enabled') as node_to_node_encryption_options_enabled,
              JSON_EXTRACT(Properties, '$.DomainEndpointOptions.CustomEndpointCertificateArn') as domain_endpoint_options_custom_endpoint_certificate_arn,
              JSON_EXTRACT(Properties, '$.DomainEndpointOptions.CustomEndpointEnabled') as domain_endpoint_options_custom_endpoint_enabled,
              JSON_EXTRACT(Properties, '$.DomainEndpointOptions.EnforceHTTPS') as domain_endpoint_options_enforce_ht_tp_s,
              JSON_EXTRACT(Properties, '$.DomainEndpointOptions.CustomEndpoint') as domain_endpoint_options_custom_endpoint,
              JSON_EXTRACT(Properties, '$.DomainEndpointOptions.TLSSecurityPolicy') as domain_endpoint_options_tl_ssecurity_policy,
              JSON_EXTRACT(Properties, '$.CognitoOptions.Enabled') as cognito_options_enabled,
              JSON_EXTRACT(Properties, '$.CognitoOptions.IdentityPoolId') as cognito_options_identity_pool_id,
              JSON_EXTRACT(Properties, '$.CognitoOptions.UserPoolId') as cognito_options_user_pool_id,
              JSON_EXTRACT(Properties, '$.CognitoOptions.RoleArn') as cognito_options_role_arn,
              JSON_EXTRACT(Properties, '$.AdvancedSecurityOptions.Enabled') as advanced_security_options_enabled,
              JSON_EXTRACT(Properties, '$.AdvancedSecurityOptions.MasterUserOptions') as advanced_security_options_master_user_options,
              JSON_EXTRACT(Properties, '$.AdvancedSecurityOptions.InternalUserDatabaseEnabled') as advanced_security_options_internal_user_database_enabled,
              JSON_EXTRACT(Properties, '$.AdvancedSecurityOptions.AnonymousAuthEnabled') as advanced_security_options_anonymous_auth_enabled,
              JSON_EXTRACT(Properties, '$.AdvancedSecurityOptions.SAMLOptions') as advanced_security_options_sa_ml_options,
              JSON_EXTRACT(Properties, '$.AdvancedSecurityOptions.AnonymousAuthDisableDate') as advanced_security_options_anonymous_auth_disable_date,
              JSON_EXTRACT(Properties, '$.DomainEndpoint') as domain_endpoint,
              JSON_EXTRACT(Properties, '$.DomainEndpoints') as domain_endpoints,
              JSON_EXTRACT(Properties, '$.EBSOptions.EBSEnabled') as e_bs_options_eb_senabled,
              JSON_EXTRACT(Properties, '$.EBSOptions.VolumeType') as e_bs_options_volume_type,
              JSON_EXTRACT(Properties, '$.EBSOptions.Iops') as e_bs_options_iops,
              JSON_EXTRACT(Properties, '$.EBSOptions.VolumeSize') as e_bs_options_volume_size,
              JSON_EXTRACT(Properties, '$.EBSOptions.Throughput') as e_bs_options_throughput,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.DomainArn') as domain_arn,
              JSON_EXTRACT(Properties, '$.EncryptionAtRestOptions.KmsKeyId') as encryption_at_rest_options_kms_key_id,
              JSON_EXTRACT(Properties, '$.EncryptionAtRestOptions.Enabled') as encryption_at_rest_options_enabled,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.ServiceSoftwareOptions.CurrentVersion') as service_software_options_current_version,
              JSON_EXTRACT(Properties, '$.ServiceSoftwareOptions.NewVersion') as service_software_options_new_version,
              JSON_EXTRACT(Properties, '$.ServiceSoftwareOptions.UpdateAvailable') as service_software_options_update_available,
              JSON_EXTRACT(Properties, '$.ServiceSoftwareOptions.Cancellable') as service_software_options_cancellable,
              JSON_EXTRACT(Properties, '$.ServiceSoftwareOptions.UpdateStatus') as service_software_options_update_status,
              JSON_EXTRACT(Properties, '$.ServiceSoftwareOptions.Description') as service_software_options_description,
              JSON_EXTRACT(Properties, '$.ServiceSoftwareOptions.AutomatedUpdateDate') as service_software_options_automated_update_date,
              JSON_EXTRACT(Properties, '$.ServiceSoftwareOptions.OptionalDeployment') as service_software_options_optional_deployment,
              JSON_EXTRACT(Properties, '$.OffPeakWindowOptions.Enabled') as off_peak_window_options_enabled,
              JSON_EXTRACT(Properties, '$.OffPeakWindowOptions.OffPeakWindow') as off_peak_window_options_off_peak_window,
              JSON_EXTRACT(Properties, '$.SoftwareUpdateOptions.AutoSoftwareUpdateEnabled') as software_update_options_auto_software_update_enabled
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::OpenSearchService::Domain'
