openapi: 3.0.0
info:
  title: Panorama
  version: 1.0.0
paths: {}
components:
  schemas:
    Name:
      type: string
      minLength: 1
      maxLength: 255
      pattern: ^[a-zA-Z0-9\-\_]+$
    Description:
      type: string
      minLength: 0
      maxLength: 255
      pattern: ^.*$
    ManifestPayloadData:
      type: string
      minLength: 1
      maxLength: 51200
      pattern: ^.+$
    ManifestPayload:
      type: object
      properties:
        PayloadData:
          $ref: '#/components/schemas/ManifestPayloadData'
      additionalProperties: false
    ManifestOverridesPayloadData:
      type: string
      minLength: 0
      maxLength: 51200
      pattern: ^.+$
    ManifestOverridesPayload:
      type: object
      properties:
        PayloadData:
          $ref: '#/components/schemas/ManifestOverridesPayloadData'
      additionalProperties: false
    RuntimeRoleArn:
      type: string
      minLength: 1
      maxLength: 255
      pattern: ^arn:[a-z0-9][-.a-z0-9]{0,62}:iam::[0-9]{12}:role/.+$
    DefaultRuntimeContextDevice:
      type: string
      minLength: 1
      maxLength: 255
      pattern: ^[a-zA-Z0-9\-\_]+$
    DeviceName:
      type: string
      minLength: 1
      maxLength: 255
      pattern: ^[a-zA-Z0-9\-\_]+$
    ApplicationInstanceId:
      type: string
      minLength: 1
      maxLength: 255
      pattern: ^[a-zA-Z0-9\-\_]+$
    ApplicationInstanceArn:
      type: string
      minLength: 1
      maxLength: 255
    ApplicationInstanceStatusDescription:
      type: string
      minLength: 1
      maxLength: 255
    Timestamp:
      type: integer
    DeviceId:
      type: string
      minLength: 1
      maxLength: 255
      pattern: ^[a-zA-Z0-9\-\_]+$
    ApplicationInstanceStatus:
      type: string
      enum:
        - DEPLOYMENT_PENDING
        - DEPLOYMENT_REQUESTED
        - DEPLOYMENT_IN_PROGRESS
        - DEPLOYMENT_ERROR
        - DEPLOYMENT_SUCCEEDED
        - REMOVAL_PENDING
        - REMOVAL_REQUESTED
        - REMOVAL_IN_PROGRESS
        - REMOVAL_FAILED
        - REMOVAL_SUCCEEDED
    ApplicationInstanceHealthStatus:
      type: string
      enum:
        - RUNNING
        - ERROR
        - NOT_AVAILABLE
    StatusFilter:
      type: string
      enum:
        - DEPLOYMENT_SUCCEEDED
        - DEPLOYMENT_ERROR
        - REMOVAL_SUCCEEDED
        - REMOVAL_FAILED
        - PROCESSING_DEPLOYMENT
        - PROCESSING_REMOVAL
    Tag:
      type: object
      properties:
        Key:
          type: string
          minLength: 1
          maxLength: 128
          pattern: ^.+$
        Value:
          type: string
          minLength: 0
          maxLength: 256
          pattern: ^.+$
      required:
        - Key
        - Value
      additionalProperties: false
    TagList:
      type: array
      uniqueItems: true
      x-insertionOrder: false
      items:
        $ref: '#/components/schemas/Tag'
    ApplicationInstance:
      type: object
      properties:
        Name:
          $ref: '#/components/schemas/Name'
        Description:
          $ref: '#/components/schemas/Description'
        ManifestPayload:
          $ref: '#/components/schemas/ManifestPayload'
        ManifestOverridesPayload:
          $ref: '#/components/schemas/ManifestOverridesPayload'
        RuntimeRoleArn:
          $ref: '#/components/schemas/RuntimeRoleArn'
        DefaultRuntimeContextDevice:
          $ref: '#/components/schemas/DefaultRuntimeContextDevice'
        DefaultRuntimeContextDeviceName:
          $ref: '#/components/schemas/DeviceName'
        ApplicationInstanceId:
          $ref: '#/components/schemas/ApplicationInstanceId'
        ApplicationInstanceIdToReplace:
          $ref: '#/components/schemas/ApplicationInstanceId'
        DeviceId:
          $ref: '#/components/schemas/DeviceId'
        StatusFilter:
          $ref: '#/components/schemas/StatusFilter'
        Status:
          $ref: '#/components/schemas/ApplicationInstanceStatus'
        HealthStatus:
          $ref: '#/components/schemas/ApplicationInstanceHealthStatus'
        StatusDescription:
          $ref: '#/components/schemas/ApplicationInstanceStatusDescription'
        CreatedTime:
          $ref: '#/components/schemas/Timestamp'
        LastUpdatedTime:
          $ref: '#/components/schemas/Timestamp'
        Arn:
          $ref: '#/components/schemas/ApplicationInstanceArn'
        Tags:
          $ref: '#/components/schemas/TagList'
      required:
        - ManifestPayload
        - DefaultRuntimeContextDevice
      x-stackql-resource-name: application_instance
      x-stackql-primaryIdentifier:
        - ApplicationInstanceId
    NodePackageName:
      type: string
      minLength: 1
      maxLength: 128
      pattern: ^[a-zA-Z0-9\-\_]+$
    NodePackageId:
      type: string
      minLength: 1
      maxLength: 255
      pattern: ^[a-zA-Z0-9\-\_\/]+$
    NodePackageArn:
      type: string
      minLength: 1
      maxLength: 255
    StorageLocation:
      type: object
      properties:
        Bucket:
          type: string
        RepoPrefixLocation:
          type: string
        GeneratedPrefixLocation:
          type: string
        BinaryPrefixLocation:
          type: string
        ManifestPrefixLocation:
          type: string
      additionalProperties: false
    Package:
      type: object
      properties:
        PackageName:
          $ref: '#/components/schemas/NodePackageName'
        PackageId:
          $ref: '#/components/schemas/NodePackageId'
        Arn:
          $ref: '#/components/schemas/NodePackageArn'
        StorageLocation:
          $ref: '#/components/schemas/StorageLocation'
        CreatedTime:
          $ref: '#/components/schemas/Timestamp'
        Tags:
          $ref: '#/components/schemas/TagList'
      required:
        - PackageName
      x-stackql-resource-name: package
      x-stackql-primaryIdentifier:
        - PackageId
    PackageOwnerAccount:
      type: string
      minLength: 1
      maxLength: 12
      pattern: ^[0-9a-z\_]+$
    NodePackageVersion:
      type: string
      minLength: 1
      maxLength: 255
      pattern: ^([0-9]+)\.([0-9]+)$
    NodePackagePatchVersion:
      type: string
      minLength: 1
      maxLength: 255
      pattern: ^[a-z0-9]+$
    PackageVersionStatus:
      type: string
      enum:
        - REGISTER_PENDING
        - REGISTER_COMPLETED
        - FAILED
        - DELETING
    PackageVersionStatusDescription:
      type: string
      minLength: 1
      maxLength: 255
    TimeStamp:
      type: integer
    PackageVersion:
      type: object
      properties:
        OwnerAccount:
          $ref: '#/components/schemas/PackageOwnerAccount'
        PackageId:
          $ref: '#/components/schemas/NodePackageId'
        PackageArn:
          $ref: '#/components/schemas/NodePackageArn'
        PackageVersion:
          $ref: '#/components/schemas/NodePackageVersion'
        PatchVersion:
          $ref: '#/components/schemas/NodePackagePatchVersion'
        MarkLatest:
          type: boolean
        IsLatestPatch:
          type: boolean
        PackageName:
          $ref: '#/components/schemas/NodePackageName'
        Status:
          $ref: '#/components/schemas/PackageVersionStatus'
        StatusDescription:
          $ref: '#/components/schemas/PackageVersionStatusDescription'
        RegisteredTime:
          $ref: '#/components/schemas/TimeStamp'
        UpdatedLatestPatchVersion:
          $ref: '#/components/schemas/NodePackagePatchVersion'
      required:
        - PackageId
        - PackageVersion
        - PatchVersion
      x-stackql-resource-name: package_version
      x-stackql-primaryIdentifier:
        - PackageId
        - PackageVersion
        - PatchVersion
  x-stackQL-resources:
    application_instances:
      name: application_instances
      id: aws.panorama.application_instances
      x-cfn-schema-name: ApplicationInstance
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ApplicationInstanceId') as application_instance_id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Panorama::ApplicationInstance'
    application_instance:
      name: application_instance
      id: aws.panorama.application_instance
      x-cfn-schema-name: ApplicationInstance
      x-type: get
      x-identifiers:
        - ApplicationInstanceId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ManifestPayload.PayloadData') as manifest_payload_payload_data,
              JSON_EXTRACT(Properties, '$.ManifestOverridesPayload.PayloadData') as manifest_overrides_payload_payload_data
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Panorama::ApplicationInstance'
    packages:
      name: packages
      id: aws.panorama.packages
      x-cfn-schema-name: Package
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.PackageId') as package_id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Panorama::Package'
    package:
      name: package
      id: aws.panorama.package
      x-cfn-schema-name: Package
      x-type: get
      x-identifiers:
        - PackageId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.StorageLocation.Bucket') as storage_location_bucket,
              JSON_EXTRACT(Properties, '$.StorageLocation.RepoPrefixLocation') as storage_location_repo_prefix_location,
              JSON_EXTRACT(Properties, '$.StorageLocation.GeneratedPrefixLocation') as storage_location_generated_prefix_location,
              JSON_EXTRACT(Properties, '$.StorageLocation.BinaryPrefixLocation') as storage_location_binary_prefix_location,
              JSON_EXTRACT(Properties, '$.StorageLocation.ManifestPrefixLocation') as storage_location_manifest_prefix_location
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Panorama::Package'
    package_versions:
      name: package_versions
      id: aws.panorama.package_versions
      x-cfn-schema-name: PackageVersion
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.PackageId') as package_id,
              JSON_EXTRACT(Properties, '$.PackageVersion') as package_version,
              JSON_EXTRACT(Properties, '$.PatchVersion') as patch_version
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Panorama::PackageVersion'
    package_version:
      name: package_version
      id: aws.panorama.package_version
      x-cfn-schema-name: PackageVersion
      x-type: get
      x-identifiers:
        - PackageId
        - PackageVersion
        - PatchVersion
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.MarkLatest') as mark_latest,
              JSON_EXTRACT(Properties, '$.IsLatestPatch') as is_latest_patch
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Panorama::PackageVersion'
