openapi: 3.0.0
info:
  version: "2018-03-22"
  title: Amazon Personalize Events
  description: Amazon Personalize Events
  x-serviceName: personalize
  x-serviceAlias: personalize_events
  x-protocol: rest-json
  x-apiVersion: "2018-03-22"
  x-endpointPrefix: personalize-events
  x-jsonVersion: "1.1"
servers:
  - url: https://personalize-events.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for personalize-events
paths:
  /action-interactions:
    post:
      operationId: PutActionInteractions
      description: Records action interaction event data. An action interaction event is an interaction between a user and an action. For example, a user taking an action, such a enrolling in a membership program or downloading your app. For more information about recording action interactions, see Recording action interaction events. For more information about actions in an Actions dataset, see Actions dataset.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trackingId:
                  $ref: "#/components/schemas/StringType"
                actionInteractions:
                  $ref: "#/components/schemas/ActionInteractionsList"
              required:
                - trackingId
                - actionInteractions
      responses:
        "200":
          description: Success
  /actions:
    post:
      operationId: PutActions
      description: Adds one or more actions to an Actions dataset. For more information see Importing actions individually.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                datasetArn:
                  $ref: "#/components/schemas/Arn"
                actions:
                  $ref: "#/components/schemas/ActionList"
              required:
                - datasetArn
                - actions
      responses:
        "200":
          description: Success
  /events:
    post:
      operationId: PutEvents
      description: Records item interaction event data. For more information see Recording item interaction events.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trackingId:
                  $ref: "#/components/schemas/StringType"
                userId:
                  $ref: "#/components/schemas/UserId"
                sessionId:
                  $ref: "#/components/schemas/StringType"
                eventList:
                  $ref: "#/components/schemas/EventList"
              required:
                - trackingId
                - sessionId
                - eventList
      responses:
        "200":
          description: Success
  /items:
    post:
      operationId: PutItems
      description: Adds one or more items to an Items dataset. For more information see Importing items individually.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                datasetArn:
                  $ref: "#/components/schemas/Arn"
                items:
                  $ref: "#/components/schemas/ItemList"
              required:
                - datasetArn
                - items
      responses:
        "200":
          description: Success
  /users:
    post:
      operationId: PutUsers
      description: Adds one or more users to a Users dataset. For more information see Importing users individually.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                datasetArn:
                  $ref: "#/components/schemas/Arn"
                users:
                  $ref: "#/components/schemas/UserList"
              required:
                - datasetArn
                - users
      responses:
        "200":
          description: Success
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    StringType:
      type: string
      minLength: 1
      maxLength: 256
    ActionInteractionsList:
      type: array
      items:
        $ref: "#/components/schemas/ActionInteraction"
    ActionInteraction:
      description: Represents an action interaction event sent using the PutActionInteractions API.
      type: object
      properties:
        actionId:
          $ref: "#/components/schemas/ActionId"
          description: The ID of the action the user interacted with. This corresponds to the ACTION_ID field of the Action interaction schema.
        userId:
          $ref: "#/components/schemas/UserId"
          description: The ID of the user who interacted with the action. This corresponds to the USER_ID field of the Action interaction schema.
        sessionId:
          $ref: "#/components/schemas/StringType"
          description: The ID associated with the user's visit. Your application generates a unique sessionId when a user first visits your website or uses your application.
        timestamp:
          $ref: "#/components/schemas/Date"
          description: The timestamp for when the action interaction event occurred. Timestamps must be in Unix epoch time format, in seconds.
        eventType:
          $ref: "#/components/schemas/StringType"
          description: The type of action interaction event. You can specify Viewed, Taken, and Not Taken event types. For more information about action interaction event type data, see Event type data.
        eventId:
          $ref: "#/components/schemas/StringType"
          description: An ID associated with the event. If an event ID is not provided, Amazon Personalize generates a unique ID for the event. An event ID is not used as an input to the model. Amazon Personalize uses the event ID to distinguish unique events. Any subsequent events after the first with the same event ID are not used in model training.
        recommendationId:
          $ref: "#/components/schemas/RecommendationId"
          description: The ID of the list of recommendations that contains the action the user interacted with.
        impression:
          $ref: "#/components/schemas/ActionImpression"
          description: A list of action IDs that represents the sequence of actions you have shown the user. For example, ["actionId1", "actionId2", "actionId3"]. Amazon Personalize doesn't use impressions data from action interaction events. Instead, record multiple events for each action and use the Viewed event type.
        properties_:
          $ref: "#/components/schemas/ActionInteractionProperties"
          description: "A string map of event-specific data that you might choose to record. For example, if a user takes an action, other than the action ID, you might also send the number of actions taken by the user. Each item in the map consists of a key-value pair. For example, {\"numberOfActions\": \"12\"} The keys use camel case names that match the fields in the Action interactions schema. In the above example, the numberOfActions would match the 'NUMBER_OF_ACTIONS' field defined in the Action interactions schema. The following can't be included as a keyword for properties (case insensitive). userId sessionId eventType timestamp recommendationId impression"
      required:
        - actionId
        - sessionId
        - timestamp
        - eventType
    ActionId:
      type: string
      minLength: 1
      maxLength: 256
    UserId:
      type: string
      minLength: 1
      maxLength: 256
    Date:
      type: string
      format: date-time
    RecommendationId:
      type: string
      minLength: 1
      maxLength: 40
    ActionImpression:
      type: array
      items:
        $ref: "#/components/schemas/ActionId"
    ActionInteractionProperties:
      type: string
      minLength: 1
      maxLength: 1024
    Arn:
      type: string
      maxLength: 256
      pattern: arn:([a-z\d-]+):personalize:.*:.*:.+
    ActionList:
      type: array
      items:
        $ref: "#/components/schemas/Action"
    Action:
      description: Represents action metadata added to an Action dataset using the PutActions API. For more information see Importing actions individually.
      type: object
      properties:
        actionId:
          $ref: "#/components/schemas/StringType"
          description: The ID associated with the action.
        properties_:
          $ref: "#/components/schemas/ActionProperties"
          description: "A string map of action-specific metadata. Each element in the map consists of a key-value pair. For example, {\"value\": \"100\"}. The keys use camel case names that match the fields in the schema for the Actions dataset. In the previous example, the value matches the 'VALUE' field defined in the Actions schema. For categorical string data, to include multiple categories for a single action, separate each category with a pipe separator (|). For example, \\\"Deluxe|Premium\\\"."
      required:
        - actionId
    ActionProperties:
      type: string
      minLength: 1
      maxLength: 32000
    EventList:
      type: array
      items:
        $ref: "#/components/schemas/Event"
    Event:
      description: Represents item interaction event information sent using the PutEvents API.
      type: object
      properties:
        eventId:
          $ref: "#/components/schemas/StringType"
          description: An ID associated with the event. If an event ID is not provided, Amazon Personalize generates a unique ID for the event. An event ID is not used as an input to the model. Amazon Personalize uses the event ID to distinguish unique events. Any subsequent events after the first with the same event ID are not used in model training.
        eventType:
          $ref: "#/components/schemas/StringType"
          description: The type of event, such as click or download. This property corresponds to the EVENT_TYPE field of your Item interactions dataset's schema and depends on the types of events you are tracking.
        eventValue:
          $ref: "#/components/schemas/FloatType"
          description: The event value that corresponds to the EVENT_VALUE field of the Item interactions schema.
        itemId:
          $ref: "#/components/schemas/ItemId"
          description: The item ID key that corresponds to the ITEM_ID field of the Item interactions dataset's schema.
        properties_:
          $ref: "#/components/schemas/EventPropertiesJSON"
          description: "A string map of event-specific data that you might choose to record. For example, if a user rates a movie on your site, other than movie ID (itemId) and rating (eventValue) , you might also send the number of movie ratings made by the user. Each item in the map consists of a key-value pair. For example, {\"numberOfRatings\": \"12\"} The keys use camel case names that match the fields in the Item interactions dataset's schema. In the above example, the numberOfRatings would match the 'NUMBER_OF_RATINGS' field defined in the Item interactions dataset's schema. The following can't be included as a keyword for properties (case insensitive). userId sessionId eventType timestamp recommendationId impression"
        sentAt:
          $ref: "#/components/schemas/Date"
          description: The timestamp (in Unix time) on the client side when the event occurred.
        recommendationId:
          $ref: "#/components/schemas/RecommendationId"
          description: The ID of the list of recommendations that contains the item the user interacted with. Provide a recommendationId to have Amazon Personalize implicitly record the recommendations you show your user as impressions data. Or provide a recommendationId if you use a metric attribution to measure the impact of recommendations. For more information on recording impressions data, see Recording impressions data. For more information on creating a metric attribution see Measuring impact of recommendations.
        impression:
          $ref: "#/components/schemas/Impression"
          description: A list of item IDs that represents the sequence of items you have shown the user. For example, ["itemId1", "itemId2", "itemId3"]. Provide a list of items to manually record impressions data for an event. For more information on recording impressions data, see Recording impressions data.
        metricAttribution:
          $ref: "#/components/schemas/MetricAttribution"
          description: Contains information about the metric attribution associated with an event. For more information about metric attributions, see Measuring impact of recommendations.
      required:
        - eventType
        - sentAt
    FloatType:
      type: number
      format: float
    ItemId:
      type: string
      minLength: 1
      maxLength: 256
    EventPropertiesJSON:
      type: string
      minLength: 1
      maxLength: 1024
    Impression:
      type: array
      items:
        $ref: "#/components/schemas/ItemId"
    MetricAttribution:
      description: Contains information about a metric attribution associated with an event. For more information about metric attributions, see Measuring impact of recommendations.
      type: object
      properties:
        eventAttributionSource:
          $ref: "#/components/schemas/EventAttributionSource"
          description: The source of the event, such as a third party.
      required:
        - eventAttributionSource
    EventAttributionSource:
      type: string
      maxLength: 1024
      pattern: ^[\x20-\x7E]*[\x21-\x7E]+[\x20-\x7E]*$
    ItemList:
      type: array
      items:
        $ref: "#/components/schemas/Item"
    Item:
      description: Represents item metadata added to an Items dataset using the PutItems API. For more information see Importing items individually.
      type: object
      properties:
        itemId:
          $ref: "#/components/schemas/StringType"
          description: The ID associated with the item.
        properties_:
          $ref: "#/components/schemas/ItemProperties"
          description: "A string map of item-specific metadata. Each element in the map consists of a key-value pair. For example, {\"numberOfRatings\": \"12\"}. The keys use camel case names that match the fields in the schema for the Items dataset. In the previous example, the numberOfRatings matches the 'NUMBER_OF_RATINGS' field defined in the Items schema. For categorical string data, to include multiple categories for a single item, separate each category with a pipe separator (|). For example, \\\"Horror|Action\\\"."
      required:
        - itemId
    ItemProperties:
      type: string
      minLength: 1
      maxLength: 32000
    UserList:
      type: array
      items:
        $ref: "#/components/schemas/User"
    User:
      description: Represents user metadata added to a Users dataset using the PutUsers API. For more information see Importing users individually.
      type: object
      properties:
        userId:
          $ref: "#/components/schemas/StringType"
          description: The ID associated with the user.
        properties_:
          $ref: "#/components/schemas/UserProperties"
          description: "A string map of user-specific metadata. Each element in the map consists of a key-value pair. For example, {\"numberOfVideosWatched\": \"45\"}. The keys use camel case names that match the fields in the schema for the Users dataset. In the previous example, the numberOfVideosWatched matches the 'NUMBER_OF_VIDEOS_WATCHED' field defined in the Users schema. For categorical string data, to include multiple categories for a single user, separate each category with a pipe separator (|). For example, \\\"Member|Frequent shopper\\\"."
      required:
        - userId
    UserProperties:
      type: string
      minLength: 1
      maxLength: 24000
  x-stackQL-resources:
    action_interactions:
      id: aws.personalize_events.action_interactions
      name: action_interactions
      title: action_interactions
      methods:
        put_action_interactions:
          operation:
            $ref: "#/paths/~1action-interactions/post"
          response:
            openAPIDocKey: "200"
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        replace:
          - $ref: "#/components/x-stackQL-resources/action_interactions/methods/put_action_interactions"
        delete: []
    actions:
      id: aws.personalize_events.actions
      name: actions
      title: actions
      methods:
        put_actions:
          operation:
            $ref: "#/paths/~1actions/post"
          response:
            openAPIDocKey: "200"
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        replace:
          - $ref: "#/components/x-stackQL-resources/actions/methods/put_actions"
        delete: []
    events:
      id: aws.personalize_events.events
      name: events
      title: events
      methods:
        put_events:
          operation:
            $ref: "#/paths/~1events/post"
          response:
            openAPIDocKey: "200"
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        replace:
          - $ref: "#/components/x-stackQL-resources/events/methods/put_events"
        delete: []
    items:
      id: aws.personalize_events.items
      name: items
      title: items
      methods:
        put_items:
          operation:
            $ref: "#/paths/~1items/post"
          response:
            openAPIDocKey: "200"
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        replace:
          - $ref: "#/components/x-stackQL-resources/items/methods/put_items"
        delete: []
    users:
      id: aws.personalize_events.users
      name: users
      title: users
      methods:
        put_users:
          operation:
            $ref: "#/paths/~1users/post"
          response:
            openAPIDocKey: "200"
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert: []
        update: []
        replace:
          - $ref: "#/components/x-stackQL-resources/users/methods/put_users"
        delete: []
