openapi: 3.0.0
info:
  version: "2018-05-22"
  title: Amazon Personalize Runtime
  description: Amazon Personalize Runtime
  x-serviceName: personalize
  x-serviceAlias: personalize_runtime
  x-protocol: rest-json
  x-apiVersion: "2018-05-22"
  x-endpointPrefix: personalize-runtime
  x-jsonVersion: "1.1"
servers:
  - url: https://personalize-runtime.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for personalize-runtime
paths:
  /action-recommendations:
    post:
      operationId: GetActionRecommendations
      description: Returns a list of recommended actions in sorted in descending order by prediction score. Use the GetActionRecommendations API if you have a custom campaign that deploys a solution version trained with a PERSONALIZED_ACTIONS recipe. For more information about PERSONALIZED_ACTIONS recipes, see PERSONALIZED_ACTIONS recipes. For more information about getting action recommendations, see Getting action recommendations.
      parameters: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                campaignArn:
                  $ref: "#/components/schemas/Arn"
                userId:
                  $ref: "#/components/schemas/UserID"
                numResults:
                  $ref: "#/components/schemas/NumResults"
                filterArn:
                  $ref: "#/components/schemas/Arn"
                filterValues:
                  $ref: "#/components/schemas/FilterValues"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetActionRecommendationsResponse"
  /personalize-ranking:
    post:
      operationId: GetPersonalizedRanking
      description: Re-ranks a list of recommended items for the given user. The first item in the list is deemed the most likely item to be of interest to the user. The solution backing the campaign must have been created using a recipe of type PERSONALIZED_RANKING.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                campaignArn:
                  $ref: "#/components/schemas/Arn"
                inputList:
                  $ref: "#/components/schemas/InputList"
                userId:
                  $ref: "#/components/schemas/UserID"
                context:
                  $ref: "#/components/schemas/Context"
                filterArn:
                  $ref: "#/components/schemas/Arn"
                filterValues:
                  $ref: "#/components/schemas/FilterValues"
                metadataColumns:
                  $ref: "#/components/schemas/MetadataColumns"
              required:
                - campaignArn
                - inputList
                - userId
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPersonalizedRankingResponse"
  /recommendations:
    post:
      operationId: GetRecommendations
      description: "Returns a list of recommended items. For campaigns, the campaign's Amazon Resource Name (ARN) is required and the required user and item input depends on the recipe type used to create the solution backing the campaign as follows: USER_PERSONALIZATION - userId required, itemId not used RELATED_ITEMS - itemId required, userId not used Campaigns that are backed by a solution created using a recipe of type PERSONALIZED_RANKING use the API. For recommenders, the recommender's ARN is required and the required item and user input depends on the use case (domain-based recipe) backing the recommender. For information on use case requirements see Choosing recommender use cases."
      parameters: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                campaignArn:
                  $ref: "#/components/schemas/Arn"
                itemId:
                  $ref: "#/components/schemas/ItemID"
                userId:
                  $ref: "#/components/schemas/UserID"
                numResults:
                  $ref: "#/components/schemas/NumResults"
                context:
                  $ref: "#/components/schemas/Context"
                filterArn:
                  $ref: "#/components/schemas/Arn"
                filterValues:
                  $ref: "#/components/schemas/FilterValues"
                recommenderArn:
                  $ref: "#/components/schemas/Arn"
                promotions:
                  $ref: "#/components/schemas/PromotionList"
                metadataColumns:
                  $ref: "#/components/schemas/MetadataColumns"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetRecommendationsResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    Arn:
      type: string
      maxLength: 256
      pattern: arn:([a-z\d-]+):personalize:.*:.*:.+
    UserID:
      type: string
      maxLength: 256
    NumResults:
      type: integer
      minimum: 0
    FilterValues:
      type: object
      properties: {}
    GetActionRecommendationsResponse:
      type: object
      properties:
        actionList:
          $ref: "#/components/schemas/ActionList"
          description: A list of action recommendations sorted in descending order by prediction score. There can be a maximum of 100 actions in the list. For information about action scores, see How action recommendation scoring works.
        recommendationId:
          $ref: "#/components/schemas/RecommendationID"
          description: The ID of the recommendation.
    ActionList:
      type: array
      items:
        $ref: "#/components/schemas/PredictedAction"
    PredictedAction:
      description: An object that identifies an action. The API returns a list of PredictedActions.
      type: object
      properties:
        actionId:
          $ref: "#/components/schemas/ActionID"
          description: The ID of the recommended action.
        score:
          $ref: "#/components/schemas/Score"
          description: The score of the recommended action. For information about action scores, see How action recommendation scoring works.
    ActionID:
      type: string
      maxLength: 256
    Score:
      type: number
      format: double
    RecommendationID:
      type: string
    InputList:
      type: array
      items:
        $ref: "#/components/schemas/ItemID"
    ItemID:
      type: string
      maxLength: 256
    Context:
      type: object
      properties: {}
    MetadataColumns:
      type: object
      properties: {}
    GetPersonalizedRankingResponse:
      type: object
      properties:
        personalizedRanking:
          $ref: "#/components/schemas/ItemList"
          description: A list of items in order of most likely interest to the user. The maximum is 500.
        recommendationId:
          $ref: "#/components/schemas/RecommendationID"
          description: The ID of the recommendation.
    ItemList:
      type: array
      items:
        $ref: "#/components/schemas/PredictedItem"
    PredictedItem:
      description: An object that identifies an item. The and APIs return a list of PredictedItems.
      type: object
      properties:
        itemId:
          $ref: "#/components/schemas/ItemID"
          description: The recommended item ID.
        score:
          $ref: "#/components/schemas/Score"
          description: A numeric representation of the model's certainty that the item will be the next user selection. For more information on scoring logic, see how-scores-work.
        promotionName:
          $ref: "#/components/schemas/Name"
          description: The name of the promotion that included the predicted item.
        metadata:
          type: object
          properties: {}
          description: Metadata about the item from your Items dataset.
        reason:
          $ref: "#/components/schemas/ReasonList"
          description: "If you use User-Personalization-v2, a list of reasons for why the item was included in recommendations. Possible reasons include the following: Promoted item - Indicates the item was included as part of a promotion that you applied in your recommendation request. Exploration - Indicates the item was included with exploration. With exploration, recommendations include items with less interactions data or relevance for the user. For more information about exploration, see Exploration. Popular item - Indicates the item was included as a placeholder popular item. If you use a filter, depending on how many recommendations the filter removes, Amazon Personalize might add placeholder items to meet the numResults for your recommendation request. These items are popular items, based on interactions data, that satisfy your filter criteria. They don't have a relevance score for the user."
    Name:
      type: string
      minLength: 1
      maxLength: 63
      pattern: ^[a-zA-Z0-9][a-zA-Z0-9\-_]*
    ReasonList:
      type: array
      items:
        $ref: "#/components/schemas/Reason"
    Reason:
      type: string
      maxLength: 256
    PromotionList:
      type: array
      items:
        $ref: "#/components/schemas/Promotion"
    Promotion:
      description: Contains information on a promotion. A promotion defines additional business rules that apply to a configurable subset of recommended items.
      type: object
      properties:
        name:
          $ref: "#/components/schemas/Name"
          description: The name of the promotion.
        percentPromotedItems:
          $ref: "#/components/schemas/PercentPromotedItems"
          description: The percentage of recommended items to apply the promotion to.
        filterArn:
          $ref: "#/components/schemas/Arn"
          description: The Amazon Resource Name (ARN) of the filter used by the promotion. This filter defines the criteria for promoted items. For more information, see Promotion filters.
        filterValues:
          type: object
          properties: {}
          description: The values to use when promoting items. For each placeholder parameter in your promotion's filter expression, provide the parameter name (in matching case) as a key and the filter value(s) as the corresponding value. Separate multiple values for one parameter with a comma. For filter expressions that use an INCLUDE element to include items, you must provide values for all parameters that are defined in the expression. For filters with expressions that use an EXCLUDE element to exclude items, you can omit the filter-values. In this case, Amazon Personalize doesn't use that portion of the expression to filter recommendations. For more information on creating filters, see Filtering recommendations and user segments.
    PercentPromotedItems:
      type: integer
      minimum: 1
      maximum: 100
    GetRecommendationsResponse:
      type: object
      properties:
        itemList:
          $ref: "#/components/schemas/ItemList"
          description: A list of recommendations sorted in descending order by prediction score. There can be a maximum of 500 items in the list.
        recommendationId:
          $ref: "#/components/schemas/RecommendationID"
          description: The ID of the recommendation.
  x-stackQL-resources:
    action_recommendations:
      id: aws.personalize_runtime.action_recommendations
      name: action_recommendations
      title: action_recommendations
      methods:
        get_action_recommendations:
          operation:
            $ref: "#/paths/~1action-recommendations/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/action_recommendations/methods/get_action_recommendations"
        insert: []
        update: []
        delete: []
    personalized_rankings:
      id: aws.personalize_runtime.personalized_rankings
      name: personalized_rankings
      title: personalized_rankings
      methods:
        get_personalized_ranking:
          operation:
            $ref: "#/paths/~1personalize-ranking/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/personalized_rankings/methods/get_personalized_ranking"
        insert: []
        update: []
        delete: []
    recommendations:
      id: aws.personalize_runtime.recommendations
      name: recommendations
      title: recommendations
      methods:
        get_recommendations:
          operation:
            $ref: "#/paths/~1recommendations/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/recommendations/methods/get_recommendations"
        insert: []
        update: []
        delete: []
