openapi: 3.0.0
info:
  title: Pinpoint
  version: 1.0.0
paths: {}
components:
  schemas:
    Alignment:
      enum:
        - LEFT
        - CENTER
        - RIGHT
      type: string
    BodyConfig:
      additionalProperties: false
      properties:
        Alignment:
          $ref: '#/components/schemas/Alignment'
        Body:
          type: string
        TextColor:
          type: string
      type: object
    ButtonAction:
      enum:
        - LINK
        - DEEP_LINK
        - CLOSE
      type: string
    ButtonConfig:
      additionalProperties: false
      properties:
        Android:
          $ref: '#/components/schemas/OverrideButtonConfiguration'
        DefaultConfig:
          $ref: '#/components/schemas/DefaultButtonConfiguration'
        IOS:
          $ref: '#/components/schemas/OverrideButtonConfiguration'
        Web:
          $ref: '#/components/schemas/OverrideButtonConfiguration'
      type: object
    DefaultButtonConfiguration:
      additionalProperties: false
      properties:
        BackgroundColor:
          type: string
        BorderRadius:
          type: integer
        ButtonAction:
          $ref: '#/components/schemas/ButtonAction'
        Link:
          type: string
        Text:
          type: string
        TextColor:
          type: string
      type: object
    HeaderConfig:
      additionalProperties: false
      properties:
        Alignment:
          $ref: '#/components/schemas/Alignment'
        Header:
          type: string
        TextColor:
          type: string
      type: object
    InAppMessageContent:
      additionalProperties: false
      properties:
        BackgroundColor:
          type: string
        BodyConfig:
          $ref: '#/components/schemas/BodyConfig'
        HeaderConfig:
          $ref: '#/components/schemas/HeaderConfig'
        ImageUrl:
          type: string
        PrimaryBtn:
          $ref: '#/components/schemas/ButtonConfig'
        SecondaryBtn:
          $ref: '#/components/schemas/ButtonConfig'
      type: object
    OverrideButtonConfiguration:
      additionalProperties: false
      properties:
        ButtonAction:
          $ref: '#/components/schemas/ButtonAction'
        Link:
          type: string
      type: object
    InAppTemplate:
      type: object
      properties:
        Arn:
          type: string
        Content:
          x-insertionOrder: true
          items:
            $ref: '#/components/schemas/InAppMessageContent'
          type: array
        CustomConfig:
          type: object
        Layout:
          enum:
            - BOTTOM_BANNER
            - TOP_BANNER
            - OVERLAYS
            - MOBILE_FEED
            - MIDDLE_BANNER
            - CAROUSEL
          type: string
        Tags:
          type: object
        TemplateDescription:
          type: string
        TemplateName:
          type: string
      required:
        - TemplateName
      x-stackql-resource-name: in_app_template
      description: Resource Type definition for AWS::Pinpoint::InAppTemplate
      x-type-name: AWS::Pinpoint::InAppTemplate
      x-stackql-primary-identifier:
        - TemplateName
      x-create-only-properties:
        - TemplateName
      x-read-only-properties:
        - Arn
      x-required-properties:
        - TemplateName
      x-taggable: true
      x-required-permissions:
        create:
          - mobiletargeting:CreateInAppTemplate
          - mobiletargeting:GetInAppTemplate
          - mobiletargeting:TagResource
        delete:
          - mobiletargeting:DeleteInAppTemplate
          - mobiletargeting:GetInAppTemplate
        list:
          - mobiletargeting:GetInAppTemplate
          - mobiletargeting:ListTemplates
        read:
          - mobiletargeting:GetInAppTemplate
          - mobiletargeting:ListTemplates
        update:
          - mobiletargeting:UpdateInAppTemplate
          - mobiletargeting:GetInAppTemplate
  x-stackQL-resources:
    in_app_templates:
      name: in_app_templates
      id: aws.pinpoint.in_app_templates
      x-cfn-schema-name: InAppTemplate
      x-type: list
      x-identifiers:
        - TemplateName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.TemplateName') as template_name
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Pinpoint::InAppTemplate'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'TemplateName') as template_name
                FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Pinpoint::InAppTemplate'
                AND region = 'us-east-1'
    in_app_template:
      name: in_app_template
      id: aws.pinpoint.in_app_template
      x-cfn-schema-name: InAppTemplate
      x-type: get
      x-identifiers:
        - TemplateName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Content') as content,
              JSON_EXTRACT(Properties, '$.CustomConfig') as custom_config,
              JSON_EXTRACT(Properties, '$.Layout') as layout,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.TemplateDescription') as template_description,
              JSON_EXTRACT(Properties, '$.TemplateName') as template_name
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Pinpoint::InAppTemplate'
              AND data__Identifier = '<TemplateName>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'Content') as content,
                json_extract_path_text(Properties, 'CustomConfig') as custom_config,
                json_extract_path_text(Properties, 'Layout') as layout,
                json_extract_path_text(Properties, 'Tags') as tags,
                json_extract_path_text(Properties, 'TemplateDescription') as template_description,
                json_extract_path_text(Properties, 'TemplateName') as template_name
                FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Pinpoint::InAppTemplate'
                AND data__Identifier = '<TemplateName>'
                AND region = 'us-east-1'
