openapi: 3.0.0
info:
  title: QLDB
  version: 1.0.0
paths: {}
components:
  schemas:
    Tag:
      description: A key-value pair to associate with a resource.
      type: object
      properties:
        Key:
          type: string
          description: 'The key name of the tag. You can specify a value that is 1 to 127 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          minLength: 1
          maxLength: 127
        Value:
          type: string
          description: 'The value for the tag. You can specify a value that is 1 to 255 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          minLength: 1
          maxLength: 255
      required:
        - Key
        - Value
      additionalProperties: false
    Ledger:
      type: object
      properties:
        PermissionsMode:
          type: string
        DeletionProtection:
          type: boolean
        Id:
          type: string
        KmsKey:
          type: string
        Tags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
        Name:
          type: string
      required:
        - PermissionsMode
      x-stackql-resource-name: ledger
      x-stackql-primaryIdentifier:
        - Id
    Arn:
      type: string
      pattern: arn:[\w+=/,.@-]+:[\w+=/,.@-]+:[\w+=/,.@-]*:[0-9]*:[\w+=,.@-]+(/[\w+=,.@-]+)*
    KinesisConfiguration:
      type: object
      properties:
        StreamArn:
          type: object
          $ref: '#/components/schemas/Arn'
        AggregationEnabled:
          type: boolean
      additionalProperties: false
    Stream:
      type: object
      properties:
        LedgerName:
          type: string
        StreamName:
          type: string
        RoleArn:
          $ref: '#/components/schemas/Arn'
        InclusiveStartTime:
          type: string
        ExclusiveEndTime:
          type: string
        KinesisConfiguration:
          $ref: '#/components/schemas/KinesisConfiguration'
        Tags:
          type: array
          maxItems: 50
          x-insertionOrder: false
          uniqueItems: true
          description: An array of key-value pairs to apply to this resource.
          items:
            $ref: '#/components/schemas/Tag'
        Arn:
          $ref: '#/components/schemas/Arn'
        Id:
          type: string
      required:
        - LedgerName
        - StreamName
        - RoleArn
        - KinesisConfiguration
        - InclusiveStartTime
      x-stackql-resource-name: stream
      x-stackql-primaryIdentifier:
        - LedgerName
        - Id
  x-stackQL-resources:
    ledgers:
      name: ledgers
      id: aws.qldb.ledgers
      x-cfn-schema-name: Ledger
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::QLDB::Ledger'
    ledger:
      name: ledger
      id: aws.qldb.ledger
      x-cfn-schema-name: Ledger
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.PermissionsMode') as permissions_mode,
              JSON_EXTRACT(Properties, '$.DeletionProtection') as deletion_protection,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.KmsKey') as kms_key,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.Name') as name
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::QLDB::Ledger'
    streams:
      name: streams
      id: aws.qldb.streams
      x-cfn-schema-name: Stream
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.LedgerName') as ledger_name,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::QLDB::Stream'
    stream:
      name: stream
      id: aws.qldb.stream
      x-cfn-schema-name: Stream
      x-type: get
      x-identifiers:
        - LedgerName
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.LedgerName') as ledger_name,
              JSON_EXTRACT(Properties, '$.StreamName') as stream_name,
              JSON_EXTRACT(Properties, '$.InclusiveStartTime') as inclusive_start_time,
              JSON_EXTRACT(Properties, '$.ExclusiveEndTime') as exclusive_end_time,
              JSON_EXTRACT(Properties, '$.KinesisConfiguration.StreamArn') as kinesis_configuration_stream_arn,
              JSON_EXTRACT(Properties, '$.KinesisConfiguration.AggregationEnabled') as kinesis_configuration_aggregation_enabled,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::QLDB::Stream'
