openapi: 3.0.0
info:
  title: RAM
  version: 1.0.0
paths: {}
components:
  schemas:
    Tag:
      type: object
      additionalProperties: false
      properties:
        Value:
          type: string
        Key:
          type: string
      required:
        - Value
        - Key
    ResourceShare:
      type: object
      properties:
        PermissionArns:
          type: array
          uniqueItems: false
          items:
            type: string
        Principals:
          type: array
          uniqueItems: false
          items:
            type: string
        AllowExternalPrincipals:
          type: boolean
        Id:
          type: string
        Arn:
          type: string
        ResourceArns:
          type: array
          uniqueItems: false
          items:
            type: string
        Tags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
        Name:
          type: string
      required:
        - Name
      x-stackql-resource-name: resource_share
      x-stackql-primaryIdentifier:
        - Id
  x-stackQL-resources:
    resource_shares:
      name: resource_shares
      id: aws.ram.resource_shares
      x-cfn-schema-name: ResourceShare
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::RAM::ResourceShare'
    resource_share:
      name: resource_share
      id: aws.ram.resource_share
      x-cfn-schema-name: ResourceShare
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.PermissionArns') as permission_arns,
              JSON_EXTRACT(Properties, '$.Principals') as principals,
              JSON_EXTRACT(Properties, '$.AllowExternalPrincipals') as allow_external_principals,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.ResourceArns') as resource_arns,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.Name') as name
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::RAM::ResourceShare'
