openapi: 3.0.0
info:
  title: ResourceExplorer2
  version: 1.0.0
paths: {}
components:
  schemas:
    DefaultViewAssociation:
      type: object
      properties:
        ViewArn:
          type: string
        AssociatedAwsPrincipal:
          description: The AWS principal that the default view is associated with, used as the unique identifier for this resource.
          type: string
          pattern: ^[0-9]{12}$
      required:
        - ViewArn
      x-stackql-resource-name: default_view_association
      x-stackql-primaryIdentifier:
        - AssociatedAwsPrincipal
    IndexType:
      type: string
      enum:
        - LOCAL
        - AGGREGATOR
    TagMap:
      type: object
      x-patternProperties:
        .+:
          type: string
      additionalProperties: false
    IndexState:
      type: string
      enum:
        - ACTIVE
        - CREATING
        - DELETING
        - DELETED
        - UPDATING
    Index:
      type: object
      properties:
        Arn:
          type: string
        Tags:
          $ref: '#/components/schemas/TagMap'
        Type:
          $ref: '#/components/schemas/IndexType'
        IndexState:
          $ref: '#/components/schemas/IndexState'
      required:
        - Type
      x-stackql-resource-name: index
      x-stackql-primaryIdentifier:
        - Arn
    IncludedProperty:
      type: object
      properties:
        Name:
          type: string
      required:
        - Name
      additionalProperties: false
    Filters:
      type: object
      properties:
        FilterString:
          type: string
      required:
        - FilterString
      additionalProperties: false
    View:
      type: object
      properties:
        IncludedProperties:
          type: array
          items:
            $ref: '#/components/schemas/IncludedProperty'
          x-insertionOrder: false
        Filters:
          $ref: '#/components/schemas/Filters'
        Tags:
          $ref: '#/components/schemas/TagMap'
        ViewArn:
          type: string
        ViewName:
          type: string
          pattern: ^[a-zA-Z0-9\-]{1,64}$
      required:
        - ViewName
      x-stackql-resource-name: view
      x-stackql-primaryIdentifier:
        - ViewArn
  x-stackQL-resources:
    default_view_associations:
      name: default_view_associations
      id: aws.resourceexplorer2.default_view_associations
      x-cfn-schema-name: DefaultViewAssociation
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.AssociatedAwsPrincipal') as associated_aws_principal
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::ResourceExplorer2::DefaultViewAssociation'
    default_view_association:
      name: default_view_association
      id: aws.resourceexplorer2.default_view_association
      x-cfn-schema-name: DefaultViewAssociation
      x-type: get
      x-identifiers:
        - AssociatedAwsPrincipal
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ViewArn') as view_arn,
              JSON_EXTRACT(Properties, '$.AssociatedAwsPrincipal') as associated_aws_principal
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::ResourceExplorer2::DefaultViewAssociation'
    indices:
      name: indices
      id: aws.resourceexplorer2.indices
      x-cfn-schema-name: Index
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::ResourceExplorer2::Index'
    index:
      name: index
      id: aws.resourceexplorer2.index
      x-cfn-schema-name: Index
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::ResourceExplorer2::Index'
    views:
      name: views
      id: aws.resourceexplorer2.views
      x-cfn-schema-name: View
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ViewArn') as view_arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::ResourceExplorer2::View'
    view:
      name: view
      id: aws.resourceexplorer2.view
      x-cfn-schema-name: View
      x-type: get
      x-identifiers:
        - ViewArn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.IncludedProperties') as included_properties,
              JSON_EXTRACT(Properties, '$.Filters.FilterString') as filters_filter_string,
              JSON_EXTRACT(Properties, '$.ViewArn') as view_arn,
              JSON_EXTRACT(Properties, '$.ViewName') as view_name
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::ResourceExplorer2::View'
