openapi: 3.0.0
info:
  title: Route53RecoveryReadiness
  version: 1.0.0
paths: {}
components:
  schemas:
    Tag:
      type: object
      additionalProperties: false
      properties:
        Key:
          type: string
        Value:
          type: string
      required:
        - Value
        - Key
    Cell:
      type: object
      properties:
        CellName:
          description: The name of the cell to create.
          type: string
          pattern: '[a-zA-Z0-9_]+'
          maxLength: 64
        CellArn:
          description: The Amazon Resource Name (ARN) of the cell.
          type: string
          maxLength: 256
        Cells:
          description: A list of cell Amazon Resource Names (ARNs) contained within this cell, for use in nested cells. For example, Availability Zones within specific Regions.
          type: array
          items:
            type: string
          maxItems: 5
          x-insertionOrder: false
        ParentReadinessScopes:
          description: The readiness scope for the cell, which can be a cell Amazon Resource Name (ARN) or a recovery group ARN. This is a list but currently can have only one element.
          type: array
          items:
            type: string
          maxItems: 5
          x-insertionOrder: false
        Tags:
          description: A collection of tags associated with a resource
          type: array
          items:
            $ref: '#/components/schemas/Tag'
            maxItems: 20
          x-insertionOrder: false
      x-stackql-resource-name: cell
      x-stackql-primaryIdentifier:
        - CellName
    ReadinessCheck:
      type: object
      properties:
        ResourceSetName:
          description: The name of the resource set to check.
          type: string
          pattern: '[a-zA-Z0-9_]+'
          minLength: 1
          maxLength: 64
        ReadinessCheckName:
          description: Name of the ReadinessCheck to create.
          type: string
          pattern: '[a-zA-Z0-9_]+'
          minLength: 1
          maxLength: 64
        ReadinessCheckArn:
          description: The Amazon Resource Name (ARN) of the readiness check.
          type: string
          maxLength: 256
        Tags:
          description: A collection of tags associated with a resource.
          type: array
          items:
            $ref: '#/components/schemas/Tag'
            maxItems: 20
          x-insertionOrder: false
      x-stackql-resource-name: readiness_check
      x-stackql-primaryIdentifier:
        - ReadinessCheckName
    RecoveryGroup:
      type: object
      properties:
        RecoveryGroupName:
          description: The name of the recovery group to create.
          type: string
          pattern: '[a-zA-Z0-9_]+'
          minLength: 1
          maxLength: 64
        Cells:
          description: A list of the cell Amazon Resource Names (ARNs) in the recovery group.
          type: array
          items:
            type: string
            minLength: 1
            maxLength: 256
          maxItems: 5
          x-insertionOrder: false
        RecoveryGroupArn:
          description: A collection of tags associated with a resource.
          type: string
          maxLength: 256
        Tags:
          description: A collection of tags associated with a resource.
          type: array
          items:
            $ref: '#/components/schemas/Tag'
            maxItems: 20
          x-insertionOrder: false
      x-stackql-resource-name: recovery_group
      x-stackql-primaryIdentifier:
        - RecoveryGroupName
    NLBResource:
      description: The Network Load Balancer resource that a DNS target resource points to.
      type: object
      properties:
        Arn:
          description: A Network Load Balancer resource Amazon Resource Name (ARN).
          type: string
      additionalProperties: false
    R53ResourceRecord:
      description: The Route 53 resource that a DNS target resource record points to.
      type: object
      properties:
        DomainName:
          description: The DNS target domain name.
          type: string
        RecordSetId:
          description: The Resource Record set id.
          type: string
      additionalProperties: false
    TargetResource:
      description: The target resource that the Route 53 record points to.
      type: object
      properties:
        NLBResource:
          $ref: '#/components/schemas/NLBResource'
        R53Resource:
          $ref: '#/components/schemas/R53ResourceRecord'
      oneOf:
        - required:
            - NLBResource
        - required:
            - R53Resource
      additionalProperties: false
    DNSTargetResource:
      description: A component for DNS/routing control readiness checks.
      type: object
      properties:
        DomainName:
          description: The domain name that acts as an ingress point to a portion of the customer application.
          type: string
        RecordSetId:
          description: The Route 53 record set ID that will uniquely identify a DNS record, given a name and a type.
          type: string
        HostedZoneArn:
          description: The hosted zone Amazon Resource Name (ARN) that contains the DNS record with the provided name of the target resource.
          type: string
        RecordType:
          description: The type of DNS record of the target resource.
          type: string
        TargetResource:
          $ref: '#/components/schemas/TargetResource'
      additionalProperties: false
    Resource:
      description: The resource element of a ResourceSet
      type: object
      properties:
        ResourceArn:
          description: The Amazon Resource Name (ARN) of the AWS resource.
          type: string
        ComponentId:
          description: The component identifier of the resource, generated when DNS target resource is used.
          type: string
        DnsTargetResource:
          $ref: '#/components/schemas/DNSTargetResource'
        ReadinessScopes:
          description: A list of recovery group Amazon Resource Names (ARNs) and cell ARNs that this resource is contained within.
          type: array
          items:
            type: string
            maxItems: 5
          x-insertionOrder: false
      additionalProperties: false
    ResourceSet:
      type: object
      properties:
        ResourceSetName:
          description: The name of the resource set to create.
          type: string
        Resources:
          description: A list of resource objects in the resource set.
          type: array
          items:
            $ref: '#/components/schemas/Resource'
          minItems: 1
          maxItems: 6
          x-insertionOrder: false
        ResourceSetArn:
          description: The Amazon Resource Name (ARN) of the resource set.
          type: string
          minLength: 1
          maxLength: 256
        ResourceSetType:
          description: |-
            The resource type of the resources in the resource set. Enter one of the following values for resource type: 

            AWS: :AutoScaling: :AutoScalingGroup, AWS: :CloudWatch: :Alarm, AWS: :EC2: :CustomerGateway, AWS: :DynamoDB: :Table, AWS: :EC2: :Volume, AWS: :ElasticLoadBalancing: :LoadBalancer, AWS: :ElasticLoadBalancingV2: :LoadBalancer, AWS: :MSK: :Cluster, AWS: :RDS: :DBCluster, AWS: :Route53: :HealthCheck, AWS: :SQS: :Queue, AWS: :SNS: :Topic, AWS: :SNS: :Subscription, AWS: :EC2: :VPC, AWS: :EC2: :VPNConnection, AWS: :EC2: :VPNGateway, AWS::Route53RecoveryReadiness::DNSTargetResource
          type: string
        Tags:
          description: A tag to associate with the parameters for a resource set.
          type: array
          items:
            $ref: '#/components/schemas/Tag'
            maxItems: 20
          x-insertionOrder: false
      required:
        - ResourceSetType
        - Resources
      x-stackql-resource-name: resource_set
      x-stackql-primaryIdentifier:
        - ResourceSetName
  x-stackQL-resources:
    cells:
      name: cells
      id: aws.route53recoveryreadiness.cells
      x-cfn-schema-name: Cell
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.CellName') as cell_name
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Route53RecoveryReadiness::Cell'
    cell:
      name: cell
      id: aws.route53recoveryreadiness.cell
      x-cfn-schema-name: Cell
      x-type: get
      x-identifiers:
        - CellName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.CellName') as cell_name,
              JSON_EXTRACT(Properties, '$.CellArn') as cell_arn,
              JSON_EXTRACT(Properties, '$.Cells') as cells,
              JSON_EXTRACT(Properties, '$.ParentReadinessScopes') as parent_readiness_scopes,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Route53RecoveryReadiness::Cell'
    readiness_checks:
      name: readiness_checks
      id: aws.route53recoveryreadiness.readiness_checks
      x-cfn-schema-name: ReadinessCheck
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ReadinessCheckName') as readiness_check_name
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Route53RecoveryReadiness::ReadinessCheck'
    readiness_check:
      name: readiness_check
      id: aws.route53recoveryreadiness.readiness_check
      x-cfn-schema-name: ReadinessCheck
      x-type: get
      x-identifiers:
        - ReadinessCheckName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ResourceSetName') as resource_set_name,
              JSON_EXTRACT(Properties, '$.ReadinessCheckName') as readiness_check_name,
              JSON_EXTRACT(Properties, '$.ReadinessCheckArn') as readiness_check_arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Route53RecoveryReadiness::ReadinessCheck'
    recovery_groups:
      name: recovery_groups
      id: aws.route53recoveryreadiness.recovery_groups
      x-cfn-schema-name: RecoveryGroup
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.RecoveryGroupName') as recovery_group_name
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Route53RecoveryReadiness::RecoveryGroup'
    recovery_group:
      name: recovery_group
      id: aws.route53recoveryreadiness.recovery_group
      x-cfn-schema-name: RecoveryGroup
      x-type: get
      x-identifiers:
        - RecoveryGroupName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.RecoveryGroupName') as recovery_group_name,
              JSON_EXTRACT(Properties, '$.Cells') as cells,
              JSON_EXTRACT(Properties, '$.RecoveryGroupArn') as recovery_group_arn,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Route53RecoveryReadiness::RecoveryGroup'
    resource_sets:
      name: resource_sets
      id: aws.route53recoveryreadiness.resource_sets
      x-cfn-schema-name: ResourceSet
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ResourceSetName') as resource_set_name
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Route53RecoveryReadiness::ResourceSet'
    resource_set:
      name: resource_set
      id: aws.route53recoveryreadiness.resource_set
      x-cfn-schema-name: ResourceSet
      x-type: get
      x-identifiers:
        - ResourceSetName
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.ResourceSetName') as resource_set_name,
              JSON_EXTRACT(Properties, '$.Resources') as resources,
              JSON_EXTRACT(Properties, '$.ResourceSetArn') as resource_set_arn,
              JSON_EXTRACT(Properties, '$.ResourceSetType') as resource_set_type,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Route53RecoveryReadiness::ResourceSet'
