openapi: 3.0.0
info:
  version: "2019-12-02"
  title: Route53 Recovery Cluster
  description: Route53 Recovery Cluster
  x-serviceName: route53-recovery-cluster
  x-serviceAlias: route53_recovery_cluster
  x-protocol: json
  x-apiVersion: "2019-12-02"
  x-endpointPrefix: route53-recovery-cluster
  x-targetPrefix: ToggleCustomerAPI
  x-jsonVersion: "1.0"
servers:
  - url: https://route53-recovery-cluster.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for route53-recovery-cluster
paths:
  /GetRoutingControlState:
    post:
      operationId: GetRoutingControlState
      description: "Get the state for a routing control. A routing control is a simple on/off switch that you can use to route traffic to cells. When a routing control state is set to ON, traffic flows to a cell. When the state is set to OFF, traffic does not flow. Before you can create a routing control, you must first create a cluster, and then host the control in a control panel on the cluster. For more information, see Create routing control structures in the Amazon Route 53 Application Recovery Controller Developer Guide. You access one of the endpoints for the cluster to get or update the routing control state to redirect traffic for your application. You must specify Regional endpoints when you work with API cluster operations to get or update routing control states in Route 53 ARC. To see a code example for getting a routing control state, including accessing Regional cluster endpoints in sequence, see API examples in the Amazon Route 53 Application Recovery Controller Developer Guide. Learn more about working with routing controls in the following topics in the Amazon Route 53 Application Recovery Controller Developer Guide: Viewing and updating routing control states Working with routing controls in Route 53 ARC"
      parameters:
        - name: X-Amz-Target
          in: header
          description: Action Header
          required: false
          schema:
            type: string
            enum:
              - ToggleCustomerAPI.GetRoutingControlState
            default: ToggleCustomerAPI.GetRoutingControlState
      requestBody:
        required: true
        content:
          application/x-amz-json-1.0:
            schema:
              type: object
              properties:
                RoutingControlArn:
                  $ref: "#/components/schemas/Arn"
                  description: The Amazon Resource Name (ARN) for the routing control that you want to get the state for.
              required:
                - RoutingControlArn
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetRoutingControlStateResponse"
  /ListRoutingControls:
    post:
      operationId: ListRoutingControls
      description: "List routing control names and Amazon Resource Names (ARNs), as well as the routing control state for each routing control, along with the control panel name and control panel ARN for the routing controls. If you specify a control panel ARN, this call lists the routing controls in the control panel. Otherwise, it lists all the routing controls in the cluster. A routing control is a simple on/off switch in Route 53 ARC that you can use to route traffic to cells. When a routing control state is set to ON, traffic flows to a cell. When the state is set to OFF, traffic does not flow. Before you can create a routing control, you must first create a cluster, and then host the control in a control panel on the cluster. For more information, see Create routing control structures in the Amazon Route 53 Application Recovery Controller Developer Guide. You access one of the endpoints for the cluster to get or update the routing control state to redirect traffic for your application. You must specify Regional endpoints when you work with API cluster operations to use this API operation to list routing controls in Route 53 ARC. Learn more about working with routing controls in the following topics in the Amazon Route 53 Application Recovery Controller Developer Guide: Viewing and updating routing control states Working with routing controls in Route 53 ARC"
      parameters:
        - name: X-Amz-Target
          in: header
          description: Action Header
          required: false
          schema:
            type: string
            enum:
              - ToggleCustomerAPI.ListRoutingControls
            default: ToggleCustomerAPI.ListRoutingControls
      requestBody:
        required: true
        content:
          application/x-amz-json-1.0:
            schema:
              type: object
              properties:
                ControlPanelArn:
                  $ref: "#/components/schemas/Arn"
                  description: The Amazon Resource Name (ARN) of the control panel of the routing controls to list.
                NextToken:
                  $ref: "#/components/schemas/PageToken"
                  description: The token for the next set of results. You receive this token from a previous call.
                MaxResults:
                  $ref: "#/components/schemas/MaxResults"
                  description: The number of routing controls objects that you want to return with this call. The default value is 500.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListRoutingControlsResponse"
  /UpdateRoutingControlState:
    post:
      operationId: UpdateRoutingControlState
      description: Set the state of the routing control to reroute traffic. You can set the value to ON or OFF. When the state is ON, traffic flows to a cell. When the state is OFF, traffic does not flow. With Route 53 ARC, you can add safety rules for routing controls, which are safeguards for routing control state updates that help prevent unexpected outcomes, like fail open traffic routing. However, there are scenarios when you might want to bypass the routing control safeguards that are enforced with safety rules that you've configured. For example, you might want to fail over quickly for disaster recovery, and one or more safety rules might be unexpectedly preventing you from updating a routing control state to reroute traffic. In a "break glass" scenario like this, you can override one or more safety rules to change a routing control state and fail over your application. The SafetyRulesToOverride property enables you override one or more safety rules and update routing control states. For more information, see Override safety rules to reroute traffic in the Amazon Route 53 Application Recovery Controller Developer Guide. You must specify Regional endpoints when you work with API cluster operations to get or update routing control states in Route 53 ARC. To see a code example for getting a routing control state, including accessing Regional cluster endpoints in sequence, see API examples in the Amazon Route 53 Application Recovery Controller Developer Guide. Viewing and updating routing control states Working with routing controls overall
      parameters:
        - name: X-Amz-Target
          in: header
          description: Action Header
          required: false
          schema:
            type: string
            enum:
              - ToggleCustomerAPI.UpdateRoutingControlState
            default: ToggleCustomerAPI.UpdateRoutingControlState
      requestBody:
        required: true
        content:
          application/x-amz-json-1.0:
            schema:
              type: object
              properties:
                RoutingControlArn:
                  $ref: "#/components/schemas/Arn"
                  description: The Amazon Resource Name (ARN) for the routing control that you want to update the state for.
                RoutingControlState:
                  $ref: "#/components/schemas/RoutingControlState"
                  description: The state of the routing control. You can set the value to ON or OFF.
                SafetyRulesToOverride:
                  $ref: "#/components/schemas/Arns"
                  description: The Amazon Resource Names (ARNs) for the safety rules that you want to override when you're updating the state of a routing control. You can override one safety rule or multiple safety rules by including one or more ARNs, separated by commas. For more information, see Override safety rules to reroute traffic in the Amazon Route 53 Application Recovery Controller Developer Guide.
              required:
                - RoutingControlArn
                - RoutingControlState
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateRoutingControlStateResponse"
  /UpdateRoutingControlStates:
    post:
      operationId: UpdateRoutingControlStates
      description: Set multiple routing control states. You can set the value for each state to be ON or OFF. When the state is ON, traffic flows to a cell. When it's OFF, traffic does not flow. With Route 53 ARC, you can add safety rules for routing controls, which are safeguards for routing control state updates that help prevent unexpected outcomes, like fail open traffic routing. However, there are scenarios when you might want to bypass the routing control safeguards that are enforced with safety rules that you've configured. For example, you might want to fail over quickly for disaster recovery, and one or more safety rules might be unexpectedly preventing you from updating a routing control state to reroute traffic. In a "break glass" scenario like this, you can override one or more safety rules to change a routing control state and fail over your application. The SafetyRulesToOverride property enables you override one or more safety rules and update routing control states. For more information, see Override safety rules to reroute traffic in the Amazon Route 53 Application Recovery Controller Developer Guide. You must specify Regional endpoints when you work with API cluster operations to get or update routing control states in Route 53 ARC. To see a code example for getting a routing control state, including accessing Regional cluster endpoints in sequence, see API examples in the Amazon Route 53 Application Recovery Controller Developer Guide. Viewing and updating routing control states Working with routing controls overall
      parameters:
        - name: X-Amz-Target
          in: header
          description: Action Header
          required: false
          schema:
            type: string
            enum:
              - ToggleCustomerAPI.UpdateRoutingControlStates
            default: ToggleCustomerAPI.UpdateRoutingControlStates
      requestBody:
        required: true
        content:
          application/x-amz-json-1.0:
            schema:
              type: object
              properties:
                UpdateRoutingControlStateEntries:
                  $ref: "#/components/schemas/UpdateRoutingControlStateEntries"
                  description: A set of routing control entries that you want to update.
                SafetyRulesToOverride:
                  $ref: "#/components/schemas/Arns"
                  description: The Amazon Resource Names (ARNs) for the safety rules that you want to override when you're updating routing control states. You can override one safety rule or multiple safety rules by including one or more ARNs, separated by commas. For more information, see Override safety rules to reroute traffic in the Amazon Route 53 Application Recovery Controller Developer Guide.
              required:
                - UpdateRoutingControlStateEntries
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateRoutingControlStatesResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    Arn:
      type: string
      minLength: 1
      maxLength: 255
      pattern: ^[A-Za-z0-9:.\/_-]*$
    GetRoutingControlStateResponse:
      type: object
      properties:
        RoutingControlArn:
          $ref: "#/components/schemas/Arn"
          description: The Amazon Resource Name (ARN) of the response.
        RoutingControlState:
          $ref: "#/components/schemas/RoutingControlState"
          description: The state of the routing control.
        RoutingControlName:
          $ref: "#/components/schemas/RoutingControlName"
          description: The routing control name.
      required:
        - RoutingControlArn
        - RoutingControlState
    RoutingControlState:
      type: string
      enum:
        - "On"
        - "Off"
    RoutingControlName:
      type: string
      minLength: 1
      maxLength: 64
      pattern: ^\S+$
    PageToken:
      type: string
      minLength: 1
      maxLength: 8096
      pattern: "[\\S]*"
    MaxResults:
      type: integer
      minimum: 1
    ListRoutingControlsResponse:
      type: object
      properties:
        RoutingControls:
          $ref: "#/components/schemas/RoutingControls"
          description: The list of routing controls.
        NextToken:
          $ref: "#/components/schemas/PageToken"
          description: The token for the next set of results. You receive this token from a previous call.
      required:
        - RoutingControls
    RoutingControls:
      type: array
      items:
        $ref: "#/components/schemas/RoutingControl"
    RoutingControl:
      description: A routing control, which is a simple on/off switch that you can use to route traffic to cells. When a routing control state is set to ON, traffic flows to a cell. When the state is set to OFF, traffic does not flow.
      type: object
      properties:
        ControlPanelArn:
          $ref: "#/components/schemas/Arn"
          description: The Amazon Resource Name (ARN) of the control panel where the routing control is located.
        ControlPanelName:
          $ref: "#/components/schemas/ControlPanelName"
          description: The name of the control panel where the routing control is located. Only ASCII characters are supported for control panel names.
        RoutingControlArn:
          $ref: "#/components/schemas/Arn"
          description: The Amazon Resource Name (ARN) of the routing control.
        RoutingControlName:
          $ref: "#/components/schemas/RoutingControlName"
          description: The name of the routing control.
        RoutingControlState:
          $ref: "#/components/schemas/RoutingControlState"
          description: The current state of the routing control. When a routing control state is set to ON, traffic flows to a cell. When the state is set to OFF, traffic does not flow.
        Owner:
          $ref: "#/components/schemas/Owner"
          description: The Amazon Web Services account ID of the routing control owner.
    ControlPanelName:
      type: string
      minLength: 1
      maxLength: 64
      pattern: ^\S+$
    Owner:
      type: string
      minLength: 12
      maxLength: 1024
      pattern: ^\S+$
    Arns:
      type: array
      items:
        $ref: "#/components/schemas/Arn"
    UpdateRoutingControlStateResponse:
      type: object
    UpdateRoutingControlStateEntries:
      type: array
      items:
        $ref: "#/components/schemas/UpdateRoutingControlStateEntry"
    UpdateRoutingControlStateEntry:
      description: A routing control state entry.
      type: object
      properties:
        RoutingControlArn:
          $ref: "#/components/schemas/Arn"
          description: The Amazon Resource Name (ARN) for a routing control state entry.
        RoutingControlState:
          $ref: "#/components/schemas/RoutingControlState"
          description: The routing control state in a set of routing control state entries.
      required:
        - RoutingControlArn
        - RoutingControlState
    UpdateRoutingControlStatesResponse:
      type: object
  x-stackQL-resources:
    routing_control_states:
      id: aws.route53_recovery_cluster.routing_control_states
      name: routing_control_states
      title: routing_control_states
      methods:
        get_routing_control_state:
          operation:
            $ref: "#/paths/~1GetRoutingControlState/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
            mediaType: application/x-amz-json-1.0
            base: "{}"
          config:
            requestBodyTranslate:
              algorithm: naive
        update_routing_control_state:
          operation:
            $ref: "#/paths/~1UpdateRoutingControlState/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
            mediaType: application/x-amz-json-1.0
            base: "{}"
          config:
            requestBodyTranslate:
              algorithm: naive
        update_routing_control_states:
          operation:
            $ref: "#/paths/~1UpdateRoutingControlStates/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
            mediaType: application/x-amz-json-1.0
            base: "{}"
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/routing_control_states/methods/get_routing_control_state"
        insert: []
        update:
          - $ref: "#/components/x-stackQL-resources/routing_control_states/methods/update_routing_control_state"
          - $ref: "#/components/x-stackQL-resources/routing_control_states/methods/update_routing_control_states"
        delete: []
    routing_controls:
      id: aws.route53_recovery_cluster.routing_controls
      name: routing_controls
      title: routing_controls
      methods:
        list_routing_controls:
          operation:
            $ref: "#/paths/~1ListRoutingControls/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.RoutingControls
          request:
            nativeCasing: pascal
            mediaType: application/x-amz-json-1.0
            base: "{}"
          config:
            pagination:
              requestToken:
                key: NextToken
                location: body
              responseToken:
                key: $.NextToken
                location: body
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/routing_controls/methods/list_routing_controls"
        insert: []
        update: []
        delete: []
