openapi: 3.0.0
info:
  version: "2017-07-25"
  title: Amazon S3 on Outposts
  description: Amazon S3 on Outposts
  x-serviceName: s3-outposts
  x-serviceAlias: s3outposts
  x-protocol: rest-json
  x-apiVersion: "2017-07-25"
  x-endpointPrefix: s3-outposts
  x-jsonVersion: "1.1"
servers:
  - url: https://s3-outposts.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for s3outposts
paths:
  /S3Outposts/CreateEndpoint:
    post:
      operationId: CreateEndpoint
      description: "Creates an endpoint and associates it with the specified Outpost. It can take up to 5 minutes for this action to finish. Related actions include: DeleteEndpoint ListEndpoints"
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                OutpostId:
                  $ref: "#/components/schemas/OutpostId"
                SubnetId:
                  $ref: "#/components/schemas/SubnetId"
                SecurityGroupId:
                  $ref: "#/components/schemas/SecurityGroupId"
                AccessType:
                  $ref: "#/components/schemas/EndpointAccessType"
                CustomerOwnedIpv4Pool:
                  $ref: "#/components/schemas/CustomerOwnedIpv4Pool"
              required:
                - OutpostId
                - SubnetId
                - SecurityGroupId
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateEndpointResult"
  /S3Outposts/DeleteEndpoint:
    delete:
      operationId: DeleteEndpoint
      description: "Deletes an endpoint. It can take up to 5 minutes for this action to finish. Related actions include: CreateEndpoint ListEndpoints"
      parameters:
        - name: endpointId
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/EndpointId"
          description: The ID of the endpoint.
        - name: outpostId
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/OutpostId"
          description: The ID of the Outposts.
      responses:
        "200":
          description: Success
  /S3Outposts/ListEndpoints:
    get:
      operationId: ListEndpoints
      description: "Lists endpoints associated with the specified Outpost. Related actions include: CreateEndpoint DeleteEndpoint"
      parameters:
        - name: nextToken
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/NextToken"
          description: If a previous response from this operation included a NextToken value, provide that value here to retrieve the next page of results.
        - name: maxResults
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/MaxResults"
          description: The maximum number of endpoints that will be returned in the response.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListEndpointsResult"
  /S3Outposts/ListOutpostsWithS3:
    get:
      operationId: ListOutpostsWithS3
      description: Lists the Outposts with S3 on Outposts capacity for your Amazon Web Services account. Includes S3 on Outposts that you have access to as the Outposts owner, or as a shared user from Resource Access Manager (RAM).
      parameters:
        - name: nextToken
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/NextToken"
          description: When you can get additional results from the ListOutpostsWithS3 call, a NextToken parameter is returned in the output. You can then pass in a subsequent command to the NextToken parameter to continue listing additional Outposts.
        - name: maxResults
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/MaxResults"
          description: The maximum number of Outposts to return. The limit is 100.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListOutpostsWithS3Result"
  /S3Outposts/ListSharedEndpoints:
    get:
      operationId: ListSharedEndpoints
      description: "Lists all endpoints associated with an Outpost that has been shared by Amazon Web Services Resource Access Manager (RAM). Related actions include: CreateEndpoint DeleteEndpoint"
      parameters:
        - name: nextToken
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/NextToken"
          description: If a previous response from this operation included a NextToken value, you can provide that value here to retrieve the next page of results.
        - name: maxResults
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/MaxResults"
          description: The maximum number of endpoints that will be returned in the response.
        - name: outpostId
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/OutpostId"
          description: The ID of the Amazon Web Services Outpost.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListSharedEndpointsResult"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    OutpostId:
      type: string
      pattern: ^(op-[a-f0-9]{17}|\d{12}|ec2)$
    SubnetId:
      type: string
      pattern: ^subnet-([0-9a-f]{8}|[0-9a-f]{17})$
    SecurityGroupId:
      type: string
      pattern: ^sg-([0-9a-f]{8}|[0-9a-f]{17})$
    EndpointAccessType:
      type: string
      enum:
        - Private
        - CustomerOwnedIp
    CustomerOwnedIpv4Pool:
      type: string
      pattern: ^ipv4pool-coip-([0-9a-f]{17})$
    CreateEndpointResult:
      type: object
      properties:
        EndpointArn:
          $ref: "#/components/schemas/EndpointArn"
          description: The Amazon Resource Name (ARN) of the endpoint.
    EndpointArn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-us-gov|aws-iso|aws-iso-b):s3-outposts:[a-z\-0-9]*:[0-9]{12}:outpost/(op-[a-f0-9]{17}|ec2)/endpoint/[a-zA-Z0-9]{19}$
    EndpointId:
      type: string
      pattern: ^[a-zA-Z0-9]{19}$
    NextToken:
      type: string
      minLength: 1
      maxLength: 1024
      pattern: ^[A-Za-z0-9\+\:\/\=\?\#-_]+$
    MaxResults:
      type: integer
      minimum: 0
      maximum: 100
    ListEndpointsResult:
      type: object
      properties:
        Endpoints:
          $ref: "#/components/schemas/Endpoints"
          description: The list of endpoints associated with the specified Outpost.
        NextToken:
          $ref: "#/components/schemas/NextToken"
          description: If the number of endpoints associated with the specified Outpost exceeds MaxResults, you can include this value in subsequent calls to this operation to retrieve more results.
    Endpoints:
      type: array
      items:
        $ref: "#/components/schemas/Endpoint"
    Endpoint:
      description: Amazon S3 on Outposts Access Points simplify managing data access at scale for shared datasets in S3 on Outposts. S3 on Outposts uses endpoints to connect to Outposts buckets so that you can perform actions within your virtual private cloud (VPC). For more information, see Accessing S3 on Outposts using VPC-only access points in the Amazon Simple Storage Service User Guide.
      type: object
      properties:
        EndpointArn:
          $ref: "#/components/schemas/EndpointArn"
          description: The Amazon Resource Name (ARN) of the endpoint.
        OutpostsId:
          $ref: "#/components/schemas/OutpostId"
          description: The ID of the Outposts.
        CidrBlock:
          $ref: "#/components/schemas/CidrBlock"
          description: The VPC CIDR committed by this endpoint.
        Status:
          $ref: "#/components/schemas/EndpointStatus"
          description: The status of the endpoint.
        CreationTime:
          $ref: "#/components/schemas/CreationTime"
          description: The time the endpoint was created.
        NetworkInterfaces:
          $ref: "#/components/schemas/NetworkInterfaces"
          description: The network interface of the endpoint.
        VpcId:
          $ref: "#/components/schemas/VpcId"
          description: The ID of the VPC used for the endpoint.
        SubnetId:
          $ref: "#/components/schemas/SubnetId"
          description: The ID of the subnet used for the endpoint.
        SecurityGroupId:
          $ref: "#/components/schemas/SecurityGroupId"
          description: The ID of the security group used for the endpoint.
        AccessType:
          $ref: "#/components/schemas/EndpointAccessType"
          description: The type of connectivity used to access the Amazon S3 on Outposts endpoint.
        CustomerOwnedIpv4Pool:
          $ref: "#/components/schemas/CustomerOwnedIpv4Pool"
          description: The ID of the customer-owned IPv4 address pool used for the endpoint.
        FailedReason:
          $ref: "#/components/schemas/FailedReason"
          description: The failure reason, if any, for a create or delete endpoint operation.
    CidrBlock:
      type: string
    EndpointStatus:
      type: string
      enum:
        - Pending
        - Available
        - Deleting
        - Create_Failed
        - Delete_Failed
    CreationTime:
      type: string
      format: date-time
    NetworkInterfaces:
      type: array
      items:
        $ref: "#/components/schemas/NetworkInterface"
    NetworkInterface:
      description: The container for the network interface.
      type: object
      properties:
        NetworkInterfaceId:
          $ref: "#/components/schemas/NetworkInterfaceId"
          description: The ID for the network interface.
    NetworkInterfaceId:
      type: string
    VpcId:
      type: string
    FailedReason:
      description: The failure reason, if any, for a create or delete endpoint operation.
      type: object
      properties:
        ErrorCode:
          $ref: "#/components/schemas/ErrorCode"
          description: The failure code, if any, for a create or delete endpoint operation.
        Message:
          $ref: "#/components/schemas/Message"
          description: Additional error details describing the endpoint failure and recommended action.
    ErrorCode:
      type: string
    Message:
      type: string
    ListOutpostsWithS3Result:
      type: object
      properties:
        Outposts:
          $ref: "#/components/schemas/Outposts"
          description: "Returns the list of Outposts that have the following characteristics: outposts that have S3 provisioned outposts that are Active (not pending any provisioning nor decommissioned) outposts to which the the calling Amazon Web Services account has access"
        NextToken:
          $ref: "#/components/schemas/NextToken"
          description: Returns a token that you can use to call ListOutpostsWithS3 again and receive additional results, if there are any.
    Outposts:
      type: array
      items:
        $ref: "#/components/schemas/Outpost"
    Outpost:
      description: Contains the details for the Outpost object.
      type: object
      properties:
        OutpostArn:
          $ref: "#/components/schemas/OutpostArn"
          description: Specifies the unique Amazon Resource Name (ARN) for the outpost.
        S3OutpostArn:
          $ref: "#/components/schemas/S3OutpostArn"
          description: Specifies the unique S3 on Outposts ARN for use with Resource Access Manager (RAM).
        OutpostId:
          $ref: "#/components/schemas/OutpostId"
          description: Specifies the unique identifier for the outpost.
        OwnerId:
          $ref: "#/components/schemas/AwsAccountId"
          description: Returns the Amazon Web Services account ID of the outpost owner. Useful for comparing owned versus shared outposts.
        CapacityInBytes:
          $ref: "#/components/schemas/CapacityInBytes"
          description: The Amazon S3 capacity of the outpost in bytes.
    OutpostArn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-us-gov|aws-iso|aws-iso-b):outposts:[a-z\-0-9]*:[0-9]{12}:outpost/(op-[a-f0-9]{17}|ec2)$
    S3OutpostArn:
      type: string
      pattern: ^arn:(aws|aws-cn|aws-us-gov|aws-iso|aws-iso-b):s3-outposts:[a-z\-0-9]*:[0-9]{12}:outpost/(op-[a-f0-9]{17}|\d{12})/s3$
    AwsAccountId:
      type: string
      pattern: ^\d{12}$
    CapacityInBytes:
      type: integer
      format: int64
    ListSharedEndpointsResult:
      type: object
      properties:
        Endpoints:
          $ref: "#/components/schemas/Endpoints"
          description: The list of endpoints associated with the specified Outpost that have been shared by Amazon Web Services Resource Access Manager (RAM).
        NextToken:
          $ref: "#/components/schemas/NextToken"
          description: If the number of endpoints associated with the specified Outpost exceeds MaxResults, you can include this value in subsequent calls to this operation to retrieve more results.
  x-stackQL-resources:
    endpoints:
      id: aws.s3outposts.endpoints
      name: endpoints
      title: endpoints
      methods:
        create_endpoint:
          operation:
            $ref: "#/paths/~1S3Outposts~1CreateEndpoint/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
        delete_endpoint:
          operation:
            $ref: "#/paths/~1S3Outposts~1DeleteEndpoint/delete"
          response:
            openAPIDocKey: "200"
          request:
            nativeCasing: pascal
        list_endpoints:
          operation:
            $ref: "#/paths/~1S3Outposts~1ListEndpoints/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.Endpoints
          request:
            nativeCasing: pascal
          config:
            pagination:
              requestToken:
                key: nextToken
                location: query
              responseToken:
                key: $.NextToken
                location: body
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/endpoints/methods/list_endpoints"
        insert:
          - $ref: "#/components/x-stackQL-resources/endpoints/methods/create_endpoint"
        update: []
        delete:
          - $ref: "#/components/x-stackQL-resources/endpoints/methods/delete_endpoint"
    outposts_with_s3s:
      id: aws.s3outposts.outposts_with_s3s
      name: outposts_with_s3s
      title: outposts_with_s3s
      methods:
        list_outposts_with_s3:
          operation:
            $ref: "#/paths/~1S3Outposts~1ListOutpostsWithS3/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.Outposts
          request:
            nativeCasing: pascal
          config:
            pagination:
              requestToken:
                key: nextToken
                location: query
              responseToken:
                key: $.NextToken
                location: body
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/outposts_with_s3s/methods/list_outposts_with_s3"
        insert: []
        update: []
        delete: []
    shared_endpoints:
      id: aws.s3outposts.shared_endpoints
      name: shared_endpoints
      title: shared_endpoints
      methods:
        list_shared_endpoints:
          operation:
            $ref: "#/paths/~1S3Outposts~1ListSharedEndpoints/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.Endpoints
          request:
            nativeCasing: pascal
          config:
            pagination:
              requestToken:
                key: nextToken
                location: query
              responseToken:
                key: $.NextToken
                location: body
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/shared_endpoints/methods/list_shared_endpoints"
        insert: []
        update: []
        delete: []
