openapi: 3.0.0
info:
  version: "2022-09-30"
  title: Amazon SageMaker Metrics Service
  description: Amazon SageMaker Metrics Service
  x-serviceName: sagemaker
  x-serviceAlias: sagemaker_metrics
  x-protocol: rest-json
  x-apiVersion: "2022-09-30"
  x-endpointPrefix: metrics.sagemaker
servers:
  - url: https://metrics.sagemaker.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for sagemaker-metrics
paths:
  /BatchGetMetrics:
    post:
      operationId: BatchGetMetrics
      description: Used to retrieve training metrics from SageMaker.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                MetricQueries:
                  $ref: "#/components/schemas/MetricQueryList"
              required:
                - MetricQueries
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchGetMetricsResponse"
  /BatchPutMetrics:
    put:
      operationId: BatchPutMetrics
      description: Used to ingest training metrics into SageMaker. These metrics can be visualized in SageMaker Studio.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                TrialComponentName:
                  $ref: "#/components/schemas/ExperimentEntityName"
                MetricData:
                  $ref: "#/components/schemas/RawMetricDataList"
              required:
                - TrialComponentName
                - MetricData
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchPutMetricsResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    MetricQueryList:
      type: array
      items:
        $ref: "#/components/schemas/MetricQuery"
    MetricQuery:
      description: Specifies a query to retrieve training metrics from SageMaker.
      type: object
      properties:
        MetricName:
          $ref: "#/components/schemas/MetricName"
          description: The name of the metric to retrieve.
        ResourceArn:
          $ref: "#/components/schemas/SageMakerResourceArn"
          description: The ARN of the SageMaker resource to retrieve metrics for.
        MetricStat:
          $ref: "#/components/schemas/MetricStatistic"
          description: The metrics stat type of metrics to retrieve.
        Period:
          $ref: "#/components/schemas/Period"
          description: The time period of metrics to retrieve.
        XAxisType:
          $ref: "#/components/schemas/XAxisType"
          description: The x-axis type of metrics to retrieve.
        Start:
          $ref: "#/components/schemas/Long"
          description: The start time of metrics to retrieve.
        End:
          $ref: "#/components/schemas/Long"
          description: The end time of metrics to retrieve.
      required:
        - MetricName
        - ResourceArn
        - MetricStat
        - Period
        - XAxisType
    MetricName:
      type: string
      minLength: 1
      maxLength: 255
      pattern: .+
    SageMakerResourceArn:
      type: string
      maxLength: 2048
      pattern: arn:aws[a-z\-]*:sagemaker:[a-z0-9\-]*:[0-9]{12}:[a-z\-].*/.*
    MetricStatistic:
      type: string
      enum:
        - Min
        - Max
        - Avg
        - Count
        - StdDev
        - Last
    Period:
      type: string
      enum:
        - OneMinute
        - FiveMinute
        - OneHour
        - IterationNumber
    XAxisType:
      type: string
      enum:
        - IterationNumber
        - Timestamp
    Long:
      type: integer
      format: int64
    BatchGetMetricsResponse:
      type: object
      properties:
        MetricQueryResults:
          $ref: "#/components/schemas/MetricQueryResultList"
          description: The results of a query to retrieve training metrics from SageMaker.
    MetricQueryResultList:
      type: array
      items:
        $ref: "#/components/schemas/MetricQueryResult"
    MetricQueryResult:
      description: The result of a query to retrieve training metrics from SageMaker.
      type: object
      properties:
        Status:
          $ref: "#/components/schemas/MetricQueryResultStatus"
          description: The status of the metric query.
        Message:
          $ref: "#/components/schemas/Message"
          description: A message describing the status of the metric query.
        XAxisValues:
          $ref: "#/components/schemas/XAxisValues"
          description: The values for the x-axis of the metrics.
        MetricValues:
          $ref: "#/components/schemas/MetricValues"
          description: The metric values retrieved by the query.
      required:
        - Status
        - XAxisValues
        - MetricValues
    MetricQueryResultStatus:
      type: string
      enum:
        - Complete
        - Truncated
        - InternalError
        - ValidationError
    Message:
      type: string
      maxLength: 2048
      pattern: .*
    XAxisValues:
      type: array
      items:
        $ref: "#/components/schemas/Long"
    MetricValues:
      type: array
      items:
        $ref: "#/components/schemas/Double"
    Double:
      type: number
      format: double
    ExperimentEntityName:
      type: string
      minLength: 1
      maxLength: 120
      pattern: ^[a-z0-9](-*[a-z0-9]){0,119}
    RawMetricDataList:
      type: array
      items:
        $ref: "#/components/schemas/RawMetricData"
    RawMetricData:
      description: The raw metric data to associate with the resource.
      type: object
      properties:
        MetricName:
          $ref: "#/components/schemas/MetricName"
          description: The name of the metric.
        Timestamp:
          $ref: "#/components/schemas/Timestamp"
          description: The time that the metric was recorded.
        Step:
          $ref: "#/components/schemas/Step"
          description: The metric step (epoch).
        Value:
          $ref: "#/components/schemas/Double"
          description: The metric value.
      required:
        - MetricName
        - Timestamp
        - Value
    Timestamp:
      type: string
      format: date-time
    Step:
      type: integer
      minimum: 0
    BatchPutMetricsResponse:
      type: object
      properties:
        Errors:
          $ref: "#/components/schemas/BatchPutMetricsErrorList"
          description: Lists any errors that occur when inserting metric data.
    BatchPutMetricsErrorList:
      type: array
      items:
        $ref: "#/components/schemas/BatchPutMetricsError"
    BatchPutMetricsError:
      description: An error that occured when putting the metric data.
      type: object
      properties:
        Code:
          $ref: "#/components/schemas/PutMetricsErrorCode"
          description: "The error code of an error that occured when attempting to put metrics. METRIC_LIMIT_EXCEEDED: The maximum amount of metrics per resource is exceeded. INTERNAL_ERROR: An internal error occured. VALIDATION_ERROR: The metric data failed validation. CONFLICT_ERROR: Multiple requests attempted to modify the same data simultaneously."
        MetricIndex:
          $ref: "#/components/schemas/Integer"
          description: An index that corresponds to the metric in the request.
    PutMetricsErrorCode:
      type: string
      enum:
        - METRIC_LIMIT_EXCEEDED
        - INTERNAL_ERROR
        - VALIDATION_ERROR
        - CONFLICT_ERROR
    Integer:
      type: integer
  x-stackQL-resources:
    metrics:
      id: aws.sagemaker_metrics.metrics
      name: metrics
      title: metrics
      methods:
        batch_get_metrics:
          operation:
            $ref: "#/paths/~1BatchGetMetrics/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
        batch_put_metrics:
          operation:
            $ref: "#/paths/~1BatchPutMetrics/put"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/metrics/methods/batch_get_metrics"
        insert: []
        update: []
        delete: []
