openapi: 3.0.0
info:
  version: "2020-09-23"
  title: Amazon Sagemaker Edge Manager
  description: Amazon Sagemaker Edge Manager
  x-serviceName: sagemaker
  x-serviceAlias: sagemaker_edge
  x-protocol: rest-json
  x-apiVersion: "2020-09-23"
  x-endpointPrefix: edge.sagemaker
  x-jsonVersion: "1.1"
servers:
  - url: https://edge.sagemaker.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for sagemaker-edge
paths:
  /GetDeployments:
    post:
      operationId: GetDeployments
      description: Use to get the active deployments from a device.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                DeviceName:
                  $ref: "#/components/schemas/DeviceName"
                DeviceFleetName:
                  $ref: "#/components/schemas/DeviceFleetName"
              required:
                - DeviceName
                - DeviceFleetName
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetDeploymentsResult"
  /GetDeviceRegistration:
    post:
      operationId: GetDeviceRegistration
      description: Use to check if a device is registered with SageMaker Edge Manager.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                DeviceName:
                  $ref: "#/components/schemas/DeviceName"
                DeviceFleetName:
                  $ref: "#/components/schemas/DeviceFleetName"
              required:
                - DeviceName
                - DeviceFleetName
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetDeviceRegistrationResult"
  /SendHeartbeat:
    post:
      operationId: SendHeartbeat
      description: Use to get the current status of devices registered on SageMaker Edge Manager.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                AgentMetrics:
                  $ref: "#/components/schemas/EdgeMetrics"
                Models:
                  $ref: "#/components/schemas/Models"
                AgentVersion:
                  $ref: "#/components/schemas/Version"
                DeviceName:
                  $ref: "#/components/schemas/DeviceName"
                DeviceFleetName:
                  $ref: "#/components/schemas/DeviceFleetName"
                DeploymentResult:
                  $ref: "#/components/schemas/DeploymentResult"
              required:
                - AgentVersion
                - DeviceName
                - DeviceFleetName
      responses:
        "200":
          description: Success
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    DeviceName:
      type: string
      minLength: 1
      maxLength: 63
      pattern: ^[a-zA-Z0-9](-*_*[a-zA-Z0-9])*$
    DeviceFleetName:
      type: string
      minLength: 1
      maxLength: 63
      pattern: ^[a-zA-Z0-9](-*_*[a-zA-Z0-9])*$
    GetDeploymentsResult:
      type: object
      properties:
        Deployments:
          $ref: "#/components/schemas/EdgeDeployments"
          description: Returns a list of the configurations of the active deployments on the device.
    EdgeDeployments:
      type: array
      items:
        $ref: "#/components/schemas/EdgeDeployment"
    EdgeDeployment:
      description: Information about a deployment on an edge device that is registered with SageMaker Edge Manager.
      type: object
      properties:
        DeploymentName:
          $ref: "#/components/schemas/EntityName"
          description: The name and unique ID of the deployment.
        Type:
          $ref: "#/components/schemas/DeploymentType"
          description: The type of the deployment.
        FailureHandlingPolicy:
          $ref: "#/components/schemas/FailureHandlingPolicy"
          description: Determines whether to rollback to previous configuration if deployment fails.
        Definitions:
          $ref: "#/components/schemas/Definitions"
          description: Returns a list of Definition objects.
    EntityName:
      type: string
      minLength: 1
      maxLength: 63
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*$
    DeploymentType:
      type: string
      enum:
        - Model
    FailureHandlingPolicy:
      type: string
      enum:
        - ROLLBACK_ON_FAILURE
        - DO_NOTHING
    Definitions:
      type: array
      items:
        $ref: "#/components/schemas/Definition"
    Definition:
      type: object
      properties:
        ModelHandle:
          $ref: "#/components/schemas/EntityName"
          description: The unique model handle.
        S3Url:
          $ref: "#/components/schemas/S3Uri"
          description: The absolute S3 location of the model.
        Checksum:
          $ref: "#/components/schemas/Checksum"
          description: The checksum information of the model.
        State:
          $ref: "#/components/schemas/ModelState"
          description: The desired state of the model.
    S3Uri:
      type: string
      maxLength: 1024
      pattern: ^s3://([^/]+)/?(.*)$
    Checksum:
      description: Information about the checksum of a model deployed on a device.
      type: object
      properties:
        Type:
          $ref: "#/components/schemas/ChecksumType"
          description: The type of the checksum.
        Sum:
          $ref: "#/components/schemas/ChecksumString"
          description: The checksum of the model.
    ChecksumType:
      type: string
      enum:
        - SHA1
    ChecksumString:
      type: string
      minLength: 1
      maxLength: 63
      pattern: ^[a-z0-9](-*[a-z0-9])*$
    ModelState:
      type: string
      enum:
        - DEPLOY
        - UNDEPLOY
    GetDeviceRegistrationResult:
      type: object
      properties:
        DeviceRegistration:
          $ref: "#/components/schemas/DeviceRegistration"
          description: Describes if the device is currently registered with SageMaker Edge Manager.
        CacheTTL:
          $ref: "#/components/schemas/CacheTTLSeconds"
          description: The amount of time, in seconds, that the registration status is stored on the device’s cache before it is refreshed.
    DeviceRegistration:
      type: string
      minLength: 1
      maxLength: 1000
    CacheTTLSeconds:
      type: string
      minLength: 1
      maxLength: 1000
    EdgeMetrics:
      type: array
      items:
        $ref: "#/components/schemas/EdgeMetric"
    EdgeMetric:
      description: Information required for edge device metrics.
      type: object
      properties:
        Dimension:
          $ref: "#/components/schemas/Dimension"
          description: The dimension of metrics published.
        MetricName:
          $ref: "#/components/schemas/Metric"
          description: Returns the name of the metric.
        Value:
          $ref: "#/components/schemas/Value"
          description: Returns the value of the metric.
        Timestamp:
          $ref: "#/components/schemas/Timestamp"
          description: Timestamp of when the metric was requested.
    Dimension:
      type: string
      minLength: 1
      maxLength: 1000
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9\/])*$
    Metric:
      type: string
      minLength: 4
      maxLength: 100
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*$
    Value:
      type: number
      format: double
    Timestamp:
      type: string
      format: date-time
    Models:
      type: array
      items:
        $ref: "#/components/schemas/Model"
    Model:
      description: Information about a model deployed on an edge device that is registered with SageMaker Edge Manager.
      type: object
      properties:
        ModelName:
          $ref: "#/components/schemas/ModelName"
          description: The name of the model.
        ModelVersion:
          $ref: "#/components/schemas/Version"
          description: The version of the model.
        LatestSampleTime:
          $ref: "#/components/schemas/Timestamp"
          description: The timestamp of the last data sample taken.
        LatestInference:
          $ref: "#/components/schemas/Timestamp"
          description: The timestamp of the last inference that was made.
        ModelMetrics:
          $ref: "#/components/schemas/EdgeMetrics"
          description: Information required for model metrics.
    ModelName:
      type: string
      minLength: 4
      maxLength: 255
      pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*$
    Version:
      type: string
      minLength: 1
      maxLength: 64
      pattern: "[a-zA-Z0-9\\ \\_\\.]+"
    DeploymentResult:
      description: Information about the result of a deployment on an edge device that is registered with SageMaker Edge Manager.
      type: object
      properties:
        DeploymentName:
          $ref: "#/components/schemas/EntityName"
          description: The name and unique ID of the deployment.
        DeploymentStatus:
          $ref: "#/components/schemas/EntityName"
          description: Returns the bucket error code.
        DeploymentStatusMessage:
          $ref: "#/components/schemas/String"
          description: Returns the detailed error message.
        DeploymentStartTime:
          $ref: "#/components/schemas/Timestamp"
          description: The timestamp of when the deployment was started on the agent.
        DeploymentEndTime:
          $ref: "#/components/schemas/Timestamp"
          description: The timestamp of when the deployment was ended, and the agent got the deployment results.
        DeploymentModels:
          $ref: "#/components/schemas/DeploymentModels"
          description: Returns a list of models deployed on the agent.
    String:
      type: string
    DeploymentModels:
      type: array
      items:
        $ref: "#/components/schemas/DeploymentModel"
    DeploymentModel:
      type: object
      properties:
        ModelHandle:
          $ref: "#/components/schemas/EntityName"
          description: The unique handle of the model.
        ModelName:
          $ref: "#/components/schemas/ModelName"
          description: The name of the model.
        ModelVersion:
          $ref: "#/components/schemas/Version"
          description: The version of the model.
        DesiredState:
          $ref: "#/components/schemas/ModelState"
          description: The desired state of the model.
        State:
          $ref: "#/components/schemas/ModelState"
          description: Returns the current state of the model.
        Status:
          $ref: "#/components/schemas/DeploymentStatus"
          description: Returns the deployment status of the model.
        StatusReason:
          $ref: "#/components/schemas/String"
          description: Returns the error message for the deployment status result.
        RollbackFailureReason:
          $ref: "#/components/schemas/String"
          description: Returns the error message if there is a rollback.
    DeploymentStatus:
      type: string
      enum:
        - SUCCESS
        - FAIL
  x-stackQL-resources:
    deployments:
      id: aws.sagemaker_edge.deployments
      name: deployments
      title: deployments
      methods:
        get_deployments:
          operation:
            $ref: "#/paths/~1GetDeployments/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/deployments/methods/get_deployments"
        insert: []
        update: []
        delete: []
    device_registrations:
      id: aws.sagemaker_edge.device_registrations
      name: device_registrations
      title: device_registrations
      methods:
        get_device_registration:
          operation:
            $ref: "#/paths/~1GetDeviceRegistration/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/device_registrations/methods/get_device_registration"
        insert: []
        update: []
        delete: []
