openapi: 3.0.0
info:
  version: "2019-11-07"
  title: Amazon Augmented AI Runtime
  description: Amazon Augmented AI Runtime
  x-serviceName: sagemaker
  x-serviceAlias: sagemaker_a2i_runtime
  x-protocol: rest-json
  x-apiVersion: "2019-11-07"
  x-endpointPrefix: a2i-runtime.sagemaker
servers:
  - url: https://a2i-runtime.sagemaker.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for sagemaker-a2i-runtime
paths:
  /human-loops/{human_loop_name}:
    delete:
      operationId: DeleteHumanLoop
      description: Deletes the specified human loop for a flow definition. If the human loop was deleted, this operation will return a ResourceNotFoundException.
      parameters:
        - name: human_loop_name
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/HumanLoopName"
          description: The name of the human loop that you want to delete.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteHumanLoopResponse"
    get:
      operationId: DescribeHumanLoop
      description: Returns information about the specified human loop. If the human loop was deleted, this operation will return a ResourceNotFoundException error.
      parameters:
        - name: human_loop_name
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/HumanLoopName"
          description: The name of the human loop that you want information about.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DescribeHumanLoopResponse"
  /human-loops:
    get:
      operationId: ListHumanLoops
      description: Returns information about human loops, given the specified parameters. If a human loop was deleted, it will not be included.
      parameters:
        - name: CreationTimeAfter
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/Timestamp"
          description: (Optional) The timestamp of the date when you want the human loops to begin in ISO 8601 format. For example, 2020-02-24.
        - name: CreationTimeBefore
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/Timestamp"
          description: (Optional) The timestamp of the date before which you want the human loops to begin in ISO 8601 format. For example, 2020-02-24.
        - name: FlowDefinitionArn
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/FlowDefinitionArn"
          description: The Amazon Resource Name (ARN) of a flow definition.
        - name: SortOrder
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/SortOrder"
          description: "Optional. The order for displaying results. Valid values: Ascending and Descending."
        - name: NextToken
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/NextToken"
          description: A token to display the next page of results.
        - name: MaxResults
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/MaxResults"
          description: The total number of items to return. If the total number of available items is more than the value specified in MaxResults, then a NextToken is returned in the output. You can use this token to display the next page of results.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListHumanLoopsResponse"
    post:
      operationId: StartHumanLoop
      description: Starts a human loop, provided that at least one activation condition is met.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                HumanLoopName:
                  $ref: "#/components/schemas/HumanLoopName"
                FlowDefinitionArn:
                  $ref: "#/components/schemas/FlowDefinitionArn"
                HumanLoopInput:
                  $ref: "#/components/schemas/HumanLoopInput"
                DataAttributes:
                  $ref: "#/components/schemas/HumanLoopDataAttributes"
              required:
                - HumanLoopName
                - FlowDefinitionArn
                - HumanLoopInput
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StartHumanLoopResponse"
  /human-loops/stop:
    post:
      operationId: StopHumanLoop
      description: Stops the specified human loop.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                HumanLoopName:
                  $ref: "#/components/schemas/HumanLoopName"
              required:
                - HumanLoopName
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StopHumanLoopResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    HumanLoopName:
      type: string
      minLength: 1
      maxLength: 63
      pattern: ^[a-z0-9](-*[a-z0-9])*$
    DeleteHumanLoopResponse:
      type: object
    DescribeHumanLoopResponse:
      type: object
      properties:
        CreationTime:
          $ref: "#/components/schemas/Timestamp"
          description: The creation time when Amazon Augmented AI created the human loop.
        FailureReason:
          $ref: "#/components/schemas/String"
          description: The reason why a human loop failed. The failure reason is returned when the status of the human loop is Failed.
        FailureCode:
          $ref: "#/components/schemas/String"
          description: "A failure code that identifies the type of failure. Possible values: ValidationError, Expired, InternalError"
        HumanLoopStatus:
          $ref: "#/components/schemas/HumanLoopStatus"
          description: The status of the human loop.
        HumanLoopName:
          $ref: "#/components/schemas/HumanLoopName"
          description: "The name of the human loop. The name must be lowercase, unique within the Region in your account, and can have up to 63 characters. Valid characters: a-z, 0-9, and - (hyphen)."
        HumanLoopArn:
          $ref: "#/components/schemas/HumanLoopArn"
          description: The Amazon Resource Name (ARN) of the human loop.
        FlowDefinitionArn:
          $ref: "#/components/schemas/FlowDefinitionArn"
          description: The Amazon Resource Name (ARN) of the flow definition.
        HumanLoopOutput:
          $ref: "#/components/schemas/HumanLoopOutput"
          description: An object that contains information about the output of the human loop.
      required:
        - CreationTime
        - HumanLoopStatus
        - HumanLoopName
        - HumanLoopArn
        - FlowDefinitionArn
    Timestamp:
      type: string
      format: date-time
    String:
      type: string
    HumanLoopStatus:
      type: string
      enum:
        - InProgress
        - Failed
        - Completed
        - Stopped
        - Stopping
    HumanLoopArn:
      type: string
      maxLength: 1024
      pattern: arn:aws[a-z\-]*:sagemaker:[a-z0-9\-]*:[0-9]{12}:human-loop/.*
    FlowDefinitionArn:
      type: string
      maxLength: 1024
      pattern: arn:aws[a-z\-]*:sagemaker:[a-z0-9\-]*:[0-9]{12}:flow-definition/.*
    HumanLoopOutput:
      description: Information about where the human output will be stored.
      type: object
      properties:
        OutputS3Uri:
          $ref: "#/components/schemas/String"
          description: The location of the Amazon S3 object where Amazon Augmented AI stores your human loop output.
      required:
        - OutputS3Uri
    SortOrder:
      type: string
      enum:
        - Ascending
        - Descending
    NextToken:
      type: string
      maxLength: 8192
      pattern: .*
    MaxResults:
      type: integer
      minimum: 1
      maximum: 100
    ListHumanLoopsResponse:
      type: object
      properties:
        HumanLoopSummaries:
          $ref: "#/components/schemas/HumanLoopSummaries"
          description: An array of objects that contain information about the human loops.
        NextToken:
          $ref: "#/components/schemas/NextToken"
          description: A token to display the next page of results.
      required:
        - HumanLoopSummaries
    HumanLoopSummaries:
      type: array
      items:
        $ref: "#/components/schemas/HumanLoopSummary"
    HumanLoopSummary:
      description: Summary information about the human loop.
      type: object
      properties:
        HumanLoopName:
          $ref: "#/components/schemas/HumanLoopName"
          description: The name of the human loop.
        HumanLoopStatus:
          $ref: "#/components/schemas/HumanLoopStatus"
          description: The status of the human loop.
        CreationTime:
          $ref: "#/components/schemas/Timestamp"
          description: When Amazon Augmented AI created the human loop.
        FailureReason:
          $ref: "#/components/schemas/FailureReason"
          description: The reason why the human loop failed. A failure reason is returned when the status of the human loop is Failed.
        FlowDefinitionArn:
          $ref: "#/components/schemas/FlowDefinitionArn"
          description: The Amazon Resource Name (ARN) of the flow definition used to configure the human loop.
    FailureReason:
      type: string
      maxLength: 1024
    HumanLoopInput:
      description: An object containing the human loop input in JSON format.
      type: object
      properties:
        InputContent:
          $ref: "#/components/schemas/InputContent"
          description: Serialized input from the human loop. The input must be a string representation of a file in JSON format.
      required:
        - InputContent
    InputContent:
      type: string
      maxLength: 3145728
    HumanLoopDataAttributes:
      description: Attributes of the data specified by the customer. Use these to describe the data to be labeled.
      type: object
      properties:
        ContentClassifiers:
          $ref: "#/components/schemas/ContentClassifiers"
          description: Declares that your content is free of personally identifiable information or adult content. Amazon SageMaker can restrict the Amazon Mechanical Turk workers who can view your task based on this information.
      required:
        - ContentClassifiers
    ContentClassifiers:
      type: array
      items:
        $ref: "#/components/schemas/ContentClassifier"
    ContentClassifier:
      type: string
      enum:
        - FreeOfPersonallyIdentifiableInformation
        - FreeOfAdultContent
    StartHumanLoopResponse:
      type: object
      properties:
        HumanLoopArn:
          $ref: "#/components/schemas/HumanLoopArn"
          description: The Amazon Resource Name (ARN) of the human loop.
    StopHumanLoopResponse:
      type: object
  x-stackQL-resources:
    human_loops:
      id: aws.sagemaker_a2i_runtime.human_loops
      name: human_loops
      title: human_loops
      methods:
        delete_human_loop:
          operation:
            $ref: "#/paths/~1human-loops~1{human_loop_name}/delete"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        describe_human_loop:
          operation:
            $ref: "#/paths/~1human-loops~1{human_loop_name}/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        list_human_loops:
          operation:
            $ref: "#/paths/~1human-loops/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.HumanLoopSummaries
          request:
            nativeCasing: pascal
          config:
            pagination:
              requestToken:
                key: NextToken
                location: query
              responseToken:
                key: $.NextToken
                location: body
        start_human_loop:
          operation:
            $ref: "#/paths/~1human-loops/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
        stop_human_loop:
          operation:
            $ref: "#/paths/~1human-loops~1stop/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/human_loops/methods/describe_human_loop"
          - $ref: "#/components/x-stackQL-resources/human_loops/methods/list_human_loops"
        insert: []
        update: []
        delete:
          - $ref: "#/components/x-stackQL-resources/human_loops/methods/delete_human_loop"
