openapi: 3.0.0
info:
  title: SecretsManager
  version: 1.0.0
paths: {}
components:
  schemas:
    GenerateSecretString:
      type: object
      additionalProperties: false
      properties:
        ExcludeUppercase:
          type: boolean
          description: Specifies whether to exclude uppercase letters from the password. If you don't include this switch, the password can contain uppercase letters.
        RequireEachIncludedType:
          type: boolean
          description: Specifies whether to include at least one upper and lowercase letter, one number, and one punctuation. If you don't include this switch, the password contains at least one of every character type.
        IncludeSpace:
          type: boolean
          description: Specifies whether to include the space character. If you include this switch, the password can contain space characters.
        ExcludeCharacters:
          type: string
          description: A string of the characters that you don't want in the password.
        GenerateStringKey:
          type: string
          description: The JSON key name for the key/value pair, where the value is the generated password. This pair is added to the JSON structure specified by the ``SecretStringTemplate`` parameter. If you specify this parameter, then you must also specify ``SecretStringTemplate``.
        PasswordLength:
          type: integer
          description: The length of the password. If you don't include this parameter, the default length is 32 characters.
        ExcludePunctuation:
          type: boolean
          description: 'Specifies whether to exclude the following punctuation characters from the password: ``! " # $ % & '' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~``. If you don''t include this switch, the password can contain punctuation.'
        ExcludeLowercase:
          type: boolean
          description: Specifies whether to exclude lowercase letters from the password. If you don't include this switch, the password can contain lowercase letters.
        SecretStringTemplate:
          type: string
          description: A template that the generated string must match. When you make a change to this property, a new secret version is created.
        ExcludeNumbers:
          type: boolean
          description: Specifies whether to exclude numbers from the password. If you don't include this switch, the password can contain numbers.
      description: |-
        Generates a random password. We recommend that you specify the maximum length and include every character type that the system you are generating a password for can support.
          *Required permissions:* ``secretsmanager:GetRandomPassword``. For more information, see [IAM policy actions for Secrets Manager](https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssecretsmanager.html#awssecretsmanager-actions-as-permissions) and [Authentication and access control in Secrets Manager](https://docs.aws.amazon.com/secretsmanager/latest/userguide/auth-and-access.html).
    ReplicaRegion:
      type: object
      description: Specifies a ``Region`` and the ``KmsKeyId`` for a replica secret.
      additionalProperties: false
      properties:
        KmsKeyId:
          type: string
          description: The ARN, key ID, or alias of the KMS key to encrypt the secret. If you don't include this field, Secrets Manager uses ``aws/secretsmanager``.
        Region:
          type: string
          description: A string that represents a ``Region``, for example "us-east-1".
      required:
        - Region
    Tag:
      type: object
      description: A structure that contains information about a tag.
      additionalProperties: false
      properties:
        Value:
          type: string
          description: The string value associated with the key of the tag.
        Key:
          type: string
          description: The key identifier, or name, of the tag.
      required:
        - Value
        - Key
    Secret:
      type: object
      properties:
        Description:
          type: string
          description: The description of the secret.
        KmsKeyId:
          type: string
          description: |-
            The ARN, key ID, or alias of the KMS key that Secrets Manager uses to encrypt the secret value in the secret. An alias is always prefixed by ``alias/``, for example ``alias/aws/secretsmanager``. For more information, see [About aliases](https://docs.aws.amazon.com/kms/latest/developerguide/alias-about.html).
             To use a KMS key in a different account, use the key ARN or the alias ARN.
             If you don't specify this value, then Secrets Manager uses the key ``aws/secretsmanager``. If that key doesn't yet exist, then Secrets Manager creates it for you automatically the first time it encrypts the secret value.
             If the secret is in a different AWS account from the credentials calling the API, then you can't use ``aws/secretsmanager`` to encrypt the secret, and you must create and use a customer managed KMS key.
        SecretString:
          type: string
          description: The text to encrypt and store in the secret. We recommend you use a JSON structure of key/value pairs for your secret value. To generate a random password, use ``GenerateSecretString`` instead. If you omit both ``GenerateSecretString`` and ``SecretString``, you create an empty secret. When you make a change to this property, a new secret version is created.
        GenerateSecretString:
          $ref: '#/components/schemas/GenerateSecretString'
          description: |-
            A structure that specifies how to generate a password to encrypt and store in the secret. To include a specific string in the secret, use ``SecretString`` instead. If you omit both ``GenerateSecretString`` and ``SecretString``, you create an empty secret. When you make a change to this property, a new secret version is created.
             We recommend that you specify the maximum length and include every character type that the system you are generating a password for can support.
        ReplicaRegions:
          type: array
          description: A custom type that specifies a ``Region`` and the ``KmsKeyId`` for a replica secret.
          uniqueItems: false
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/ReplicaRegion'
        Id:
          type: string
          description: ''
        Tags:
          type: array
          description: |-
            A list of tags to attach to the secret. Each tag is a key and value pair of strings in a JSON text string, for example:
              ``[{"Key":"CostCenter","Value":"12345"},{"Key":"environment","Value":"production"}]`` 
             Secrets Manager tag key names are case sensitive. A tag with the key "ABC" is a different tag from one with key "abc".
             Stack-level tags, tags you apply to the CloudFormation stack, are also attached to the secret. 
             If you check tags in permissions policies as part of your security strategy, then adding or removing a tag can change permissions. If the completion of this operation would result in you losing your permissions for this secret, then Secrets Manager blocks the operation and returns an ``Access Denied`` error. For more information, see [Control access to secrets using tags](https://docs.aws.amazon.com/secretsmanager/latest/userguide/auth-and-access_examples.html#tag-secrets-abac) and [Limit access to identities with tags that match secrets' tags](https://docs.aws.amazon.com/secretsmanager/latest/userguide/auth-and-access_examples.html#auth-and-access_tags2).
             For information about how to format a JSON parameter for the various command line tool environments, see [Using JSON for Parameters](https://docs.aws.amazon.com/cli/latest/userguide/cli-using-param.html#cli-using-param-json). If your command-line tool or SDK requires quotation marks around the parameter, you should use single quotes to avoid confusion with the double quotes required in the JSON text.
             The following restrictions apply to tags:
              +  Maximum number of tags per secret: 50
              +  Maximum key length: 127 Unicode characters in UTF-8
              +  Maximum value length: 255 Unicode characters in UTF-8
              +  Tag keys and values are case sensitive.
              +  Do not use the ``aws:`` prefix in your tag names or values because AWS reserves it for AWS use. You can't edit or delete tag names or values with this prefix. Tags with this prefix do not count against your tags per secret limit.
              +  If you use your tagging schema across multiple services and resources, other services might have restrictions on allowed characters. Generally allowed characters: letters, spaces, and numbers representable in UTF-8, plus the following special characters: + - = . _ : / @.
          uniqueItems: false
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
        Name:
          type: string
          description: |-
            The name of the new secret.
             The secret name can contain ASCII letters, numbers, and the following characters: /_+=.@-
             Do not end your secret name with a hyphen followed by six characters. If you do so, you risk confusion and unexpected results when searching for a secret by partial ARN. Secrets Manager automatically adds a hyphen and six random characters after the secret name at the end of the ARN.
      x-stackql-resource-name: secret
      description: |-
        Creates a new secret. A *secret* can be a password, a set of credentials such as a user name and password, an OAuth token, or other secret information that you store in an encrypted form in Secrets Manager.
         For RDS master user credentials, see [AWS::RDS::DBCluster MasterUserSecret](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbcluster-masterusersecret.html).
         To retrieve a secret in a CFNshort template, use a *dynamic reference*. For more information, see [Retrieve a secret in an resource](https://docs.aws.amazon.com/secretsmanager/latest/userguide/cfn-example_reference-secret.html).
         A common scenario is to first create a secret with ``GenerateSecretString``, which generates a password, and then use a dynamic reference to retrieve the username and password from the secret to use as credentials for a new database. See the example *Creating a Redshift cluster and a secret for the admin credentials*.
         For information about creating a secret in the console, see [Create a secret](https://docs.aws.amazon.com/secretsmanager/latest/userguide/manage_create-basic-secret.html). For information about creating a secret using the CLI or SDK, see [CreateSecret](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_CreateSecret.html).
         For information about retrieving a secret in code, see [Retrieve secrets from Secrets Manager](https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets.html).
      x-type-name: AWS::SecretsManager::Secret
      x-stackql-primary-identifier:
        - Id
      x-create-only-properties:
        - Name
      x-write-only-properties:
        - SecretString
        - GenerateSecretString
      x-read-only-properties:
        - Id
      x-tagging:
        taggable: true
        tagOnCreate: true
        tagUpdatable: true
        cloudFormationSystemTags: true
        tagProperty: /properties/Tags
      x-required-permissions:
        create:
          - secretsmanager:DescribeSecret
          - secretsmanager:GetRandomPassword
          - secretsmanager:CreateSecret
          - secretsmanager:TagResource
        delete:
          - secretsmanager:DeleteSecret
          - secretsmanager:DescribeSecret
          - secretsmanager:RemoveRegionsFromReplication
        list:
          - secretsmanager:ListSecrets
        read:
          - secretsmanager:DescribeSecret
          - secretsmanager:GetSecretValue
        update:
          - secretsmanager:UpdateSecret
          - secretsmanager:TagResource
          - secretsmanager:UntagResource
          - secretsmanager:GetRandomPassword
          - secretsmanager:GetSecretValue
          - secretsmanager:ReplicateSecretToRegions
          - secretsmanager:RemoveRegionsFromReplication
  x-stackQL-resources:
    secrets:
      name: secrets
      id: aws.secretsmanager.secrets
      x-cfn-schema-name: Secret
      x-type: list
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::SecretsManager::Secret'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Id') as id
                FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::SecretsManager::Secret'
                AND region = 'us-east-1'
    secret:
      name: secret
      id: aws.secretsmanager.secret
      x-cfn-schema-name: Secret
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.KmsKeyId') as kms_key_id,
              JSON_EXTRACT(Properties, '$.SecretString') as secret_string,
              JSON_EXTRACT(Properties, '$.GenerateSecretString') as generate_secret_string,
              JSON_EXTRACT(Properties, '$.ReplicaRegions') as replica_regions,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.Name') as name
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::SecretsManager::Secret'
              AND data__Identifier = '<Id>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'Description') as description,
                json_extract_path_text(Properties, 'KmsKeyId') as kms_key_id,
                json_extract_path_text(Properties, 'SecretString') as secret_string,
                json_extract_path_text(Properties, 'GenerateSecretString') as generate_secret_string,
                json_extract_path_text(Properties, 'ReplicaRegions') as replica_regions,
                json_extract_path_text(Properties, 'Id') as id,
                json_extract_path_text(Properties, 'Tags') as tags,
                json_extract_path_text(Properties, 'Name') as name
                FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::SecretsManager::Secret'
                AND data__Identifier = '<Id>'
                AND region = 'us-east-1'
