openapi: 3.0.0
info:
  title: ServiceCatalogAppRegistry
  version: 1.0.0
paths: {}
components:
  schemas:
    Tags:
      type: object
      x-patternProperties:
        ^[a-zA-Z+-=._:/]+$:
          type: string
          maxLength: 256
      maxProperties: 50
      additionalProperties: false
    Application:
      type: object
      properties:
        Id:
          type: string
          pattern: '[a-z0-9]{26}'
        Arn:
          type: string
          pattern: arn:aws[-a-z]*:servicecatalog:[a-z]{2}(-gov)?-[a-z]+-\d:\d{12}:/applications/[a-z0-9]+
        Name:
          type: string
          description: 'The name of the application. '
          minLength: 1
          maxLength: 256
          pattern: \w+
        Description:
          type: string
          description: 'The description of the application. '
          maxLength: 1024
        Tags:
          $ref: '#/components/schemas/Tags'
      required:
        - Name
      x-stackql-resource-name: application
      x-stackql-primaryIdentifier:
        - Id
    AttributeGroup:
      type: object
      properties:
        Id:
          type: string
          pattern: '[a-z0-9]{12}'
        Arn:
          type: string
          pattern: arn:aws[-a-z]*:servicecatalog:[a-z]{2}(-gov)?-[a-z]+-\d:\d{12}:/attribute-groups/[a-z0-9]+
        Name:
          type: string
          description: 'The name of the attribute group. '
          minLength: 1
          maxLength: 256
          pattern: \w+
        Description:
          type: string
          description: 'The description of the attribute group. '
          maxLength: 1024
        Attributes:
          type: object
        Tags:
          $ref: '#/components/schemas/Tags'
      required:
        - Name
        - Attributes
      x-stackql-resource-name: attribute_group
      x-stackql-primaryIdentifier:
        - Id
    AttributeGroupAssociation:
      type: object
      properties:
        Application:
          type: string
          description: The name or the Id of the Application.
          minLength: 1
          maxLength: 256
          pattern: \w+|[a-z0-9]{12}
        AttributeGroup:
          type: string
          description: The name or the Id of the AttributeGroup.
          minLength: 1
          maxLength: 256
          pattern: \w+|[a-z0-9]{12}
        ApplicationArn:
          type: string
          pattern: arn:aws[-a-z]*:servicecatalog:[a-z]{2}(-gov)?-[a-z]+-\d:\d{12}:/applications/[a-z0-9]+
        AttributeGroupArn:
          type: string
          pattern: arn:aws[-a-z]*:servicecatalog:[a-z]{2}(-gov)?-[a-z]+-\d:\d{12}:/attribute-groups/[a-z0-9]+
        Id:
          type: string
      required:
        - Application
        - AttributeGroup
      x-stackql-resource-name: attribute_group_association
      x-stackql-primaryIdentifier:
        - Id
    ResourceAssociation:
      type: object
      properties:
        Application:
          type: string
          description: The name or the Id of the Application.
          minLength: 1
          maxLength: 256
          pattern: \w+|[a-z0-9]{12}
        Resource:
          type: string
          description: The name or the Id of the Resource.
          pattern: \w+|arn:aws[-a-z]*:cloudformation:[a-z]{2}(-gov)?-[a-z]+-\d:\d{12}:stack/[a-zA-Z][-A-Za-z0-9]{0,127}/[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}
        ResourceType:
          type: string
          description: The type of the CFN Resource for now it's enum CFN_STACK.
          enum:
            - CFN_STACK
        ApplicationArn:
          type: string
          pattern: arn:aws[-a-z]*:servicecatalog:[a-z]{2}(-gov)?-[a-z]+-\d:\d{12}:/applications/[a-z0-9]+
        ResourceArn:
          type: string
          pattern: arn:aws[-a-z]*:cloudformation:[a-z]{2}(-gov)?-[a-z]+-\d:\d{12}:stack/[a-zA-Z][-A-Za-z0-9]{0,127}/[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}
        Id:
          type: string
      required:
        - Application
        - Resource
        - ResourceType
      x-stackql-resource-name: resource_association
      x-stackql-primaryIdentifier:
        - Id
  x-stackQL-resources:
    applications:
      name: applications
      id: aws.servicecatalogappregistry.applications
      x-cfn-schema-name: Application
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::ServiceCatalogAppRegistry::Application'
    application:
      name: application
      id: aws.servicecatalogappregistry.application
      x-cfn-schema-name: Application
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Description') as description
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::ServiceCatalogAppRegistry::Application'
    attribute_groups:
      name: attribute_groups
      id: aws.servicecatalogappregistry.attribute_groups
      x-cfn-schema-name: AttributeGroup
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::ServiceCatalogAppRegistry::AttributeGroup'
    attribute_group:
      name: attribute_group
      id: aws.servicecatalogappregistry.attribute_group
      x-cfn-schema-name: AttributeGroup
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.Attributes') as attributes
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::ServiceCatalogAppRegistry::AttributeGroup'
    attribute_group_associations:
      name: attribute_group_associations
      id: aws.servicecatalogappregistry.attribute_group_associations
      x-cfn-schema-name: AttributeGroupAssociation
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::ServiceCatalogAppRegistry::AttributeGroupAssociation'
    attribute_group_association:
      name: attribute_group_association
      id: aws.servicecatalogappregistry.attribute_group_association
      x-cfn-schema-name: AttributeGroupAssociation
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Application') as application,
              JSON_EXTRACT(Properties, '$.AttributeGroup') as attribute_group,
              JSON_EXTRACT(Properties, '$.ApplicationArn') as application_arn,
              JSON_EXTRACT(Properties, '$.AttributeGroupArn') as attribute_group_arn,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::ServiceCatalogAppRegistry::AttributeGroupAssociation'
    resource_associations:
      name: resource_associations
      id: aws.servicecatalogappregistry.resource_associations
      x-cfn-schema-name: ResourceAssociation
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::ServiceCatalogAppRegistry::ResourceAssociation'
    resource_association:
      name: resource_association
      id: aws.servicecatalogappregistry.resource_association
      x-cfn-schema-name: ResourceAssociation
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Application') as application,
              JSON_EXTRACT(Properties, '$.Resource') as resource,
              JSON_EXTRACT(Properties, '$.ResourceType') as resource_type,
              JSON_EXTRACT(Properties, '$.ApplicationArn') as application_arn,
              JSON_EXTRACT(Properties, '$.ResourceArn') as resource_arn,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::ServiceCatalogAppRegistry::ResourceAssociation'
