openapi: 3.0.0
info:
  version: "2025-09-26"
  title: Amazon SimpleDB v2
  description: Amazon SimpleDB v2
  x-serviceName: sdb
  x-serviceAlias: simpledbv2
  x-protocol: rest-json
  x-apiVersion: "2025-09-26"
  x-endpointPrefix: sdb
servers:
  - url: https://sdb.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for simpledbv2
paths:
  /v2/GetExport:
    post:
      operationId: GetExport
      description: Returns information for an existing domain export.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                exportArn:
                  $ref: "#/components/schemas/ExportArn"
              required:
                - exportArn
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetExportResponse"
  /v2/ListExports:
    post:
      operationId: ListExports
      description: Lists all exports that were created. The results are paginated and can be filtered by domain name.
      parameters: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                domainName:
                  $ref: "#/components/schemas/DomainName"
                maxResults:
                  $ref: "#/components/schemas/MaxResults"
                nextToken:
                  $ref: "#/components/schemas/NextToken"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListExportsResponse"
  /v2/StartDomainExport:
    post:
      operationId: StartDomainExport
      description: Initiates the export of a SimpleDB domain to an S3 bucket.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clientToken:
                  $ref: "#/components/schemas/IdempotencyToken"
                domainName:
                  $ref: "#/components/schemas/DomainName"
                s3Bucket:
                  $ref: "#/components/schemas/S3BucketName"
                s3KeyPrefix:
                  $ref: "#/components/schemas/S3KeyPrefix"
                s3SseAlgorithm:
                  $ref: "#/components/schemas/S3SseAlgorithm"
                s3SseKmsKeyId:
                  $ref: "#/components/schemas/S3SseKmsKeyId"
                s3BucketOwner:
                  $ref: "#/components/schemas/AwsAccountId"
              required:
                - domainName
                - s3Bucket
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StartDomainExportResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    ExportArn:
      description: A unique ARN identifier for the export.
      type: string
      minLength: 20
      maxLength: 2048
    GetExportResponse:
      type: object
      properties:
        exportArn:
          $ref: "#/components/schemas/ExportArn"
          description: Unique ARN identifier of the export.
        clientToken:
          $ref: "#/components/schemas/IdempotencyToken"
          description: The client token provided for this export.
        exportStatus:
          $ref: "#/components/schemas/ExportStatus"
          description: "The current state of the export. Current possible values include : PENDING - export request received, IN_PROGRESS - export is being processed, SUCCEEDED - export completed successfully, and FAILED - export encountered an error."
        domainName:
          $ref: "#/components/schemas/DomainName"
          description: The name of the domain that was exported.
        requestedAt:
          $ref: "#/components/schemas/RequestedAt"
          description: Timestamp when the export request was received by the service.
        s3Bucket:
          $ref: "#/components/schemas/S3BucketName"
          description: The name of the S3 bucket for this export.
        s3KeyPrefix:
          $ref: "#/components/schemas/S3KeyPrefix"
          description: The S3 key prefix provided in the corresponding StartDomainExport request.
        s3SseAlgorithm:
          $ref: "#/components/schemas/S3SseAlgorithm"
          description: The S3 SSE encryption algorithm for this export.
        s3SseKmsKeyId:
          $ref: "#/components/schemas/S3SseKmsKeyId"
          description: The KMS key ID for this export.
        s3BucketOwner:
          $ref: "#/components/schemas/AwsAccountId"
          description: The S3 bucket owner account ID for this export.
        failureCode:
          $ref: "#/components/schemas/FailureCode"
          description: Failure code for the result of the failed export.
        failureMessage:
          $ref: "#/components/schemas/FailureMessage"
          description: Export failure reason description.
        exportManifest:
          $ref: "#/components/schemas/ExportManifestSummary"
          description: The name of the manifest summary file for the export.
        itemsCount:
          $ref: "#/components/schemas/ItemsCount"
          description: Total number of exported items.
        exportDataCutoffTime:
          $ref: "#/components/schemas/ExportDataCutoffTime"
          description: The timestamp indicating the cutoff point for data inclusion in the export. All data inserted or modified before this time will be present in the exported data. Data insertions or modifications after this timestamp may or may not be present in the export.
      required:
        - exportArn
        - clientToken
        - exportStatus
        - domainName
        - requestedAt
        - s3Bucket
    IdempotencyToken:
      type: string
      minLength: 1
    ExportStatus:
      description: "The current state of the export. Current possible values include : PENDING - export request received, IN_PROGRESS - export is being processed, SUCCEEDED - export completed successfully, and FAILED - export encountered an error."
      type: string
      enum:
        - PENDING
        - IN_PROGRESS
        - SUCCEEDED
        - FAILED
    DomainName:
      description: The domain name that uniquely identifies a SimpleDB domain within your account.
      type: string
      minLength: 1
    RequestedAt:
      description: Timestamp when the export (or any other operation) was requested.
      type: string
      format: date-time
    S3BucketName:
      type: string
      minLength: 3
      maxLength: 255
      pattern: "[a-z0-9A-Z]+[\\.\\-\\w]*[a-z0-9A-Z]+"
    S3KeyPrefix:
      type: string
      minLength: 1
      maxLength: 850
    S3SseAlgorithm:
      type: string
      enum:
        - AES256
        - KMS
    S3SseKmsKeyId:
      type: string
      minLength: 1
      maxLength: 2048
    AwsAccountId:
      type: string
      pattern: "[0-9]{12}"
    FailureCode:
      type: string
      minLength: 1
      pattern: "[a-zA-Z0-9]+"
    FailureMessage:
      type: string
      minLength: 1
    ExportManifestSummary:
      type: string
      minLength: 1
    ItemsCount:
      type: integer
      format: int64
      minimum: 0
    ExportDataCutoffTime:
      type: string
      format: date-time
    MaxResults:
      description: "The maximum number of results to return in a single response. Note: The actual number of results returned might be less than the specified maxResults."
      type: integer
      minimum: 1
    NextToken:
      description: A pagination token used for retrieving subsequent pages of results.
      type: string
      minLength: 1
      maxLength: 2048
    ListExportsResponse:
      type: object
      properties:
        exportSummaries:
          $ref: "#/components/schemas/ExportSummaries"
          description: List of export summaries containing export ARN, status, request timestamp, and associated domain name.
        nextToken:
          $ref: "#/components/schemas/NextToken"
          description: A pagination token indicating that more results are available. To retrieve the next page of results, provide this token in a subsequent ListExports request. If null or empty, there are no more results to retrieve.
      required:
        - exportSummaries
    ExportSummaries:
      description: List of export summaries containing export ARN, status, creation timestamp, and associated domain name.
      type: array
      items:
        $ref: "#/components/schemas/ExportSummary"
    ExportSummary:
      description: Summary information about an export, including its unique identifier, current status, creation time, and the domain being exported.
      type: object
      properties:
        exportArn:
          $ref: "#/components/schemas/ExportArn"
          description: Unique ARN identifier of the export.
        exportStatus:
          $ref: "#/components/schemas/ExportStatus"
          description: "The current state of the export. Current possible values include : PENDING - export request received, IN_PROGRESS - export is being processed, SUCCEEDED - export completed successfully, and FAILED - export encountered an error."
        requestedAt:
          $ref: "#/components/schemas/RequestedAt"
          description: Timestamp when the export request was received by the service
        domainName:
          $ref: "#/components/schemas/DomainName"
          description: The name of the domain for which the export was created.
      required:
        - exportArn
        - exportStatus
        - requestedAt
        - domainName
    StartDomainExportResponse:
      type: object
      properties:
        clientToken:
          $ref: "#/components/schemas/IdempotencyToken"
          description: The client token that was provided in the request.
        exportArn:
          $ref: "#/components/schemas/ExportArn"
          description: Unique ARN identifier of the export.
        requestedAt:
          $ref: "#/components/schemas/RequestedAt"
          description: Timestamp when the export request was received by the service.
      required:
        - clientToken
        - exportArn
        - requestedAt
  x-stackQL-resources:
    exports:
      id: aws.simpledbv2.exports
      name: exports
      title: exports
      methods:
        get_export:
          operation:
            $ref: "#/paths/~1v2~1GetExport/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
        list_exports:
          operation:
            $ref: "#/paths/~1v2~1ListExports/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.exportSummaries
          request:
            nativeCasing: pascal
          config:
            pagination:
              requestToken:
                key: nextToken
                location: body
              responseToken:
                key: $.nextToken
                location: body
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/exports/methods/get_export"
          - $ref: "#/components/x-stackQL-resources/exports/methods/list_exports"
        insert: []
        update: []
        delete: []
