openapi: 3.0.0
info:
  title: SimSpaceWeaver
  version: 1.0.0
paths: {}
components:
  schemas:
    S3Location:
      type: object
      properties:
        BucketName:
          description: The Schema S3 bucket name.
          type: string
          minLength: 3
          maxLength: 255
          pattern: '[a-zA-Z0-9_\-]{3,255}$'
        ObjectKey:
          description: This is the schema S3 object key, which includes the full path of "folders" from the bucket root to the schema.
          type: string
          minLength: 3
          maxLength: 255
          pattern: ([\-a-zA-Z0-9_-]+\/)*[a-zA-Z0-9_-]+\.(json|yaml)$
      required:
        - BucketName
        - ObjectKey
      additionalProperties: false
    Simulation:
      type: object
      properties:
        Name:
          description: The name of the simulation.
          type: string
          minLength: 1
          maxLength: 2048
          pattern: '[a-zA-Z0-9_\-]{1,2048}$'
        RoleArn:
          description: Role ARN.
          type: string
        SchemaS3Location:
          $ref: '#/components/schemas/S3Location'
        DescribePayload:
          description: Json object with all simulation details
          type: string
      x-stackql-resource-name: simulation
      x-stackql-primaryIdentifier:
        - Name
  x-stackQL-resources:
    simulations:
      name: simulations
      id: aws.simspaceweaver.simulations
      x-cfn-schema-name: Simulation
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Name') as name
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::SimSpaceWeaver::Simulation'
    simulation:
      name: simulation
      id: aws.simspaceweaver.simulation
      x-cfn-schema-name: Simulation
      x-type: get
      x-identifiers:
        - Name
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.RoleArn') as role_arn,
              JSON_EXTRACT(Properties, '$.SchemaS3Location.BucketName') as schema_s3_location_bucket_name,
              JSON_EXTRACT(Properties, '$.SchemaS3Location.ObjectKey') as schema_s3_location_object_key,
              JSON_EXTRACT(Properties, '$.DescribePayload') as describe_payload
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::SimSpaceWeaver::Simulation'
