openapi: 3.0.0
info:
  version: "2021-05-01"
  title: AWS SSM-GUIConnect
  description: AWS SSM-GUIConnect
  x-serviceName: ssm-guiconnect
  x-serviceAlias: ssm_guiconnect
  x-protocol: rest-json
  x-apiVersion: "2021-05-01"
  x-endpointPrefix: ssm-guiconnect
  x-jsonVersion: "1.1"
servers:
  - url: https://ssm-guiconnect.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for ssm-guiconnect
paths:
  /DeleteConnectionRecordingPreferences:
    post:
      operationId: DeleteConnectionRecordingPreferences
      description: Deletes the preferences for recording RDP connections.
      parameters: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                ClientToken:
                  $ref: "#/components/schemas/ClientToken"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeleteConnectionRecordingPreferencesResponse"
  /GetConnectionRecordingPreferences:
    post:
      operationId: GetConnectionRecordingPreferences
      description: Returns the preferences specified for recording RDP connections in the requesting Amazon Web Services account and Amazon Web Services Region.
      parameters: []
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetConnectionRecordingPreferencesResponse"
  /UpdateConnectionRecordingPreferences:
    post:
      operationId: UpdateConnectionRecordingPreferences
      description: Updates the preferences for recording RDP connections.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ClientToken:
                  $ref: "#/components/schemas/ClientToken"
                ConnectionRecordingPreferences:
                  $ref: "#/components/schemas/ConnectionRecordingPreferences"
              required:
                - ConnectionRecordingPreferences
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateConnectionRecordingPreferencesResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    ClientToken:
      type: string
      minLength: 1
      maxLength: 64
    DeleteConnectionRecordingPreferencesResponse:
      type: object
      properties:
        ClientToken:
          $ref: "#/components/schemas/ClientToken"
          description: Service-provided idempotency token.
    GetConnectionRecordingPreferencesResponse:
      type: object
      properties:
        ClientToken:
          $ref: "#/components/schemas/ClientToken"
          description: Service-provided idempotency token.
        ConnectionRecordingPreferences:
          $ref: "#/components/schemas/ConnectionRecordingPreferences"
          description: The set of preferences used for recording RDP connections in the requesting Amazon Web Services account and Amazon Web Services Region. This includes details such as which S3 bucket recordings are stored in.
    ConnectionRecordingPreferences:
      description: The set of preferences used for recording RDP connections in the requesting Amazon Web Services account and Amazon Web Services Region. This includes details such as which S3 bucket recordings are stored in.
      type: object
      properties:
        KMSKeyArn:
          $ref: "#/components/schemas/ConnectionRecordingPreferencesKMSKeyArnString"
          description: The ARN of a KMS key that is used to encrypt data while it is being processed by the service. This key must exist in the same Amazon Web Services Region as the node you start an RDP connection to.
        RecordingDestinations:
          $ref: "#/components/schemas/RecordingDestinations"
          description: Determines where recordings of RDP connections are stored.
      required:
        - KMSKeyArn
        - RecordingDestinations
    ConnectionRecordingPreferencesKMSKeyArnString:
      type: string
      minLength: 1
      maxLength: 2048
    RecordingDestinations:
      description: Determines where recordings of RDP connections are stored.
      type: object
      properties:
        S3Buckets:
          $ref: "#/components/schemas/S3Buckets"
          description: The S3 bucket where RDP connection recordings are stored.
      required:
        - S3Buckets
    S3Buckets:
      type: array
      items:
        $ref: "#/components/schemas/S3Bucket"
    S3Bucket:
      description: The S3 bucket where RDP connection recordings are stored.
      type: object
      properties:
        BucketName:
          $ref: "#/components/schemas/BucketName"
          description: The name of the S3 bucket where RDP connection recordings are stored.
        BucketOwner:
          $ref: "#/components/schemas/AccountId"
          description: The Amazon Web Services account number that owns the S3 bucket.
      required:
        - BucketName
        - BucketOwner
    BucketName:
      type: string
      pattern: (?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)
    AccountId:
      type: string
      pattern: ^[0-9]{12}$
    UpdateConnectionRecordingPreferencesResponse:
      type: object
      properties:
        ClientToken:
          $ref: "#/components/schemas/ClientToken"
          description: Service-provided idempotency token.
        ConnectionRecordingPreferences:
          $ref: "#/components/schemas/ConnectionRecordingPreferences"
          description: The set of preferences used for recording RDP connections in the requesting Amazon Web Services account and Amazon Web Services Region. This includes details such as which S3 bucket recordings are stored in.
  x-stackQL-resources:
    connection_recording_preferences:
      id: aws.ssm_guiconnect.connection_recording_preferences
      name: connection_recording_preferences
      title: connection_recording_preferences
      methods:
        delete_connection_recording_preferences:
          operation:
            $ref: "#/paths/~1DeleteConnectionRecordingPreferences/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
        get_connection_recording_preferences:
          operation:
            $ref: "#/paths/~1GetConnectionRecordingPreferences/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        update_connection_recording_preferences:
          operation:
            $ref: "#/paths/~1UpdateConnectionRecordingPreferences/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/connection_recording_preferences/methods/get_connection_recording_preferences"
        insert: []
        update:
          - $ref: "#/components/x-stackQL-resources/connection_recording_preferences/methods/update_connection_recording_preferences"
        delete:
          - $ref: "#/components/x-stackQL-resources/connection_recording_preferences/methods/delete_connection_recording_preferences"
