openapi: 3.0.0
info:
  title: SSMIncidents
  version: 1.0.0
paths: {}
components:
  schemas:
    Arn:
      description: The ARN of the ReplicationSet.
      type: string
      pattern: ^arn:aws(-(cn|us-gov|iso(-b)?))?:[a-z-]+:(([a-z]+-)+[0-9])?:([0-9]{12})?:[^.]+$
      maxLength: 1000
    RegionName:
      description: The AWS region name.
      type: string
      maxLength: 20
    ReplicationRegion:
      description: The ReplicationSet regional configuration.
      type: object
      additionalProperties: false
      properties:
        RegionName:
          $ref: '#/components/schemas/RegionName'
        RegionConfiguration:
          $ref: '#/components/schemas/RegionConfiguration'
    RegionConfiguration:
      description: The ReplicationSet regional configuration.
      type: object
      additionalProperties: false
      properties:
        SseKmsKeyId:
          $ref: '#/components/schemas/Arn'
      required:
        - SseKmsKeyId
    DeletionProtected:
      description: Configures the ReplicationSet deletion protection.
      type: boolean
    RegionList:
      type: array
      minItems: 1
      maxItems: 3
      items:
        $ref: '#/components/schemas/ReplicationRegion'
      x-insertionOrder: false
      uniqueItems: true
    Tag:
      description: A key-value pair to tag a resource.
      additionalProperties: false
      type: object
      properties:
        Key:
          type: string
          pattern: ^(?!aws:)[a-zA-Z+-=._:/]+$
          minLength: 1
          maxLength: 128
        Value:
          type: string
          minLength: 1
          maxLength: 256
      required:
        - Value
        - Key
    ReplicationSet:
      type: object
      properties:
        Arn:
          description: The ARN of the ReplicationSet.
          $ref: '#/components/schemas/Arn'
          additionalProperties: false
        Regions:
          description: The ReplicationSet configuration.
          $ref: '#/components/schemas/RegionList'
        DeletionProtected:
          $ref: '#/components/schemas/DeletionProtected'
          default: false
        Tags:
          description: The tags to apply to the replication set.
          type: array
          default: []
          uniqueItems: true
          x-insertionOrder: false
          maxItems: 50
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - Regions
      x-stackql-resource-name: replication_set
      description: Resource type definition for AWS::SSMIncidents::ReplicationSet
      x-type-name: AWS::SSMIncidents::ReplicationSet
      x-stackql-primary-identifier:
        - Arn
      x-read-only-properties:
        - Arn
      x-required-properties:
        - Regions
      x-taggable: true
      x-required-permissions:
        create:
          - ssm-incidents:CreateReplicationSet
          - ssm-incidents:ListReplicationSets
          - ssm-incidents:UpdateDeletionProtection
          - ssm-incidents:GetReplicationSet
          - ssm-incidents:TagResource
          - ssm-incidents:ListTagsForResource
          - iam:CreateServiceLinkedRole
        read:
          - ssm-incidents:ListReplicationSets
          - ssm-incidents:GetReplicationSet
          - ssm-incidents:ListTagsForResource
        update:
          - ssm-incidents:UpdateReplicationSet
          - ssm-incidents:UpdateDeletionProtection
          - ssm-incidents:GetReplicationSet
          - ssm-incidents:TagResource
          - ssm-incidents:UntagResource
          - ssm-incidents:ListTagsForResource
        delete:
          - ssm-incidents:DeleteReplicationSet
          - ssm-incidents:GetReplicationSet
        list:
          - ssm-incidents:ListReplicationSets
    SSMContact:
      description: The ARN of the contact.
      type: string
      pattern: ^arn:aws(-(cn|us-gov))?:ssm-contacts:(([a-z]+-)+[0-9])?:([0-9]{12})?:[^.]+$
      maxLength: 1000
    SnsArn:
      description: The ARN of the Chatbot SNS topic.
      type: string
      pattern: ^arn:aws(-(cn|us-gov))?:sns:(([a-z]+-)+[0-9])?:([0-9]{12})?:[^.]+$
      maxLength: 1000
    NotificationTargetItem:
      description: A notification target.
      type: object
      additionalProperties: false
      properties:
        SnsTopicArn:
          $ref: '#/components/schemas/SnsArn'
    Action:
      description: The automation configuration to launch.
      additionalProperties: false
      type: object
      properties:
        SsmAutomation:
          $ref: '#/components/schemas/SsmAutomation'
    SsmAutomation:
      description: The configuration to use when starting the SSM automation document.
      type: object
      additionalProperties: false
      required:
        - RoleArn
        - DocumentName
      properties:
        RoleArn:
          description: The role ARN to use when starting the SSM automation document.
          type: string
          pattern: ^arn:aws(-(cn|us-gov))?:[a-z-]+:(([a-z]+-)+[0-9])?:([0-9]{12})?:[^.]+$
          maxLength: 1000
        DocumentName:
          description: The document name to use when starting the SSM automation document.
          type: string
          maxLength: 128
        DocumentVersion:
          description: The version of the document to use when starting the SSM automation document.
          type: string
          maxLength: 128
        TargetAccount:
          description: The account type to use when starting the SSM automation document.
          type: string
          enum:
            - IMPACTED_ACCOUNT
            - RESPONSE_PLAN_OWNER_ACCOUNT
        Parameters:
          description: The parameters to set when starting the SSM automation document.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/SsmParameter'
          minItems: 1
          maxItems: 200
          default: []
        DynamicParameters:
          description: The parameters with dynamic values to set when starting the SSM automation document.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/DynamicSsmParameter'
          maxItems: 200
          default: []
    SsmParameter:
      description: A parameter to set when starting the SSM automation document.
      type: object
      properties:
        Key:
          type: string
          minLength: 1
          maxLength: 50
        Values:
          type: array
          uniqueItems: true
          x-insertionOrder: true
          maxItems: 10
          items:
            $ref: '#/components/schemas/SsmParameterValue'
      required:
        - Values
        - Key
      additionalProperties: false
    SsmParameterValue:
      description: A value of the parameter to set when starting the SSM automation document.
      type: string
      maxLength: 10000
    DynamicSsmParameter:
      description: A parameter with a dynamic value to set when starting the SSM automation document.
      type: object
      properties:
        Key:
          type: string
          minLength: 1
          maxLength: 50
        Value:
          $ref: '#/components/schemas/DynamicSsmParameterValue'
      required:
        - Value
        - Key
      additionalProperties: false
    DynamicSsmParameterValue:
      description: Value of the dynamic parameter to set when starting the SSM automation document.
      additionalProperties: false
      type: object
      properties:
        Variable:
          $ref: '#/components/schemas/VariableType'
    VariableType:
      description: The variable types used as dynamic parameter value when starting the SSM automation document.
      type: string
      enum:
        - INCIDENT_RECORD_ARN
        - INVOLVED_RESOURCES
    Integration:
      type: object
      additionalProperties: false
      properties:
        PagerDutyConfiguration:
          $ref: '#/components/schemas/PagerDutyConfiguration'
      oneOf:
        - required:
            - PagerDutyConfiguration
    PagerDutyConfiguration:
      description: The pagerDuty configuration to use when starting the incident.
      type: object
      additionalProperties: false
      required:
        - Name
        - SecretId
        - PagerDutyIncidentConfiguration
      properties:
        Name:
          description: The name of the pagerDuty configuration.
          type: string
          minLength: 1
          maxLength: 200
        SecretId:
          description: The AWS secrets manager secretId storing the pagerDuty token.
          type: string
          minLength: 1
          maxLength: 512
        PagerDutyIncidentConfiguration:
          $ref: '#/components/schemas/PagerDutyIncidentConfiguration'
    PagerDutyIncidentConfiguration:
      description: The pagerDuty incident configuration.
      additionalProperties: false
      type: object
      properties:
        ServiceId:
          description: The pagerDuty serviceId.
          type: string
          minLength: 1
          maxLength: 200
      required:
        - ServiceId
    IncidentTemplate:
      description: The incident template configuration.
      additionalProperties: false
      type: object
      required:
        - Title
        - Impact
      properties:
        DedupeString:
          description: The deduplication string.
          type: string
          maxLength: 1000
          minLength: 1
        Impact:
          description: The impact value.
          type: integer
          minimum: 1
          maximum: 5
        NotificationTargets:
          description: The list of notification targets.
          type: array
          default: []
          maxItems: 10
          items:
            $ref: '#/components/schemas/NotificationTargetItem'
          x-insertionOrder: false
        Summary:
          description: The summary string.
          type: string
          maxLength: 4000
          minLength: 1
        Title:
          description: The title string.
          type: string
          maxLength: 200
        IncidentTags:
          description: Tags that get applied to incidents created by the StartIncident API action.
          type: array
          uniqueItems: true
          x-insertionOrder: false
          default: []
          maxItems: 50
          items:
            $ref: '#/components/schemas/Tag'
    ChatbotSns:
      type: array
      uniqueItems: true
      x-insertionOrder: true
      default: []
      items:
        $ref: '#/components/schemas/SnsArn'
    ChatChannel:
      description: The chat channel configuration.
      additionalProperties: false
      type: object
      properties:
        ChatbotSns:
          $ref: '#/components/schemas/ChatbotSns'
    ResponsePlan:
      type: object
      properties:
        Arn:
          description: The ARN of the response plan.
          type: string
          pattern: ^arn:aws(-(cn|us-gov))?:[a-z-]+:(([a-z]+-)+[0-9])?:([0-9]{12})?:[^.]+$
          maxLength: 1000
        Name:
          description: The name of the response plan.
          type: string
          pattern: ^[a-zA-Z0-9_-]*$
          maxLength: 200
          minLength: 1
        DisplayName:
          description: The display name of the response plan.
          type: string
          maxLength: 200
          minLength: 1
        ChatChannel:
          $ref: '#/components/schemas/ChatChannel'
        Engagements:
          description: The list of engagements to use.
          type: array
          default: []
          maxItems: 5
          uniqueItems: true
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/SSMContact'
        Actions:
          description: The list of actions.
          type: array
          default: []
          uniqueItems: true
          x-insertionOrder: true
          maxItems: 1
          items:
            $ref: '#/components/schemas/Action'
        Integrations:
          description: The list of integrations.
          type: array
          default: []
          uniqueItems: true
          x-insertionOrder: true
          maxItems: 1
          items:
            $ref: '#/components/schemas/Integration'
        Tags:
          description: The tags to apply to the response plan.
          type: array
          default: []
          uniqueItems: true
          x-insertionOrder: false
          maxItems: 50
          items:
            $ref: '#/components/schemas/Tag'
        IncidentTemplate:
          $ref: '#/components/schemas/IncidentTemplate'
      required:
        - Name
        - IncidentTemplate
      x-stackql-resource-name: response_plan
      description: Resource type definition for AWS::SSMIncidents::ResponsePlan
      x-type-name: AWS::SSMIncidents::ResponsePlan
      x-stackql-primary-identifier:
        - Arn
      x-create-only-properties:
        - Name
      x-read-only-properties:
        - Arn
      x-required-properties:
        - Name
        - IncidentTemplate
      x-taggable: true
      x-required-permissions:
        create:
          - ssm-incidents:CreateResponsePlan
          - ssm-incidents:GetResponsePlan
          - ssm-incidents:TagResource
          - ssm-incidents:ListTagsForResource
          - iam:PassRole
          - secretsmanager:GetSecretValue
          - kms:Decrypt
          - kms:GenerateDataKey*
        read:
          - ssm-incidents:GetResponsePlan
          - ssm-incidents:ListTagsForResource
        update:
          - ssm-incidents:UpdateResponsePlan
          - ssm-incidents:GetResponsePlan
          - ssm-incidents:TagResource
          - ssm-incidents:UntagResource
          - ssm-incidents:ListTagsForResource
          - iam:PassRole
          - secretsmanager:GetSecretValue
          - kms:Decrypt
          - kms:GenerateDataKey*
        delete:
          - ssm-incidents:DeleteResponsePlan
          - ssm-incidents:GetResponsePlan
        list:
          - ssm-incidents:ListResponsePlans
  x-stackQL-resources:
    replication_sets:
      name: replication_sets
      id: aws.ssmincidents.replication_sets
      x-cfn-schema-name: ReplicationSet
      x-type: list
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::SSMIncidents::ReplicationSet'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Arn') as arn
                FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::SSMIncidents::ReplicationSet'
                AND region = 'us-east-1'
    replication_set:
      name: replication_set
      id: aws.ssmincidents.replication_set
      x-cfn-schema-name: ReplicationSet
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Regions') as regions,
              JSON_EXTRACT(Properties, '$.DeletionProtected') as deletion_protected,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::SSMIncidents::ReplicationSet'
              AND data__Identifier = '<Arn>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'Regions') as regions,
                json_extract_path_text(Properties, 'DeletionProtected') as deletion_protected,
                json_extract_path_text(Properties, 'Tags') as tags
                FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::SSMIncidents::ReplicationSet'
                AND data__Identifier = '<Arn>'
                AND region = 'us-east-1'
    response_plans:
      name: response_plans
      id: aws.ssmincidents.response_plans
      x-cfn-schema-name: ResponsePlan
      x-type: list
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Arn') as arn
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::SSMIncidents::ResponsePlan'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                json_extract_path_text(Properties, 'Arn') as arn
                FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::SSMIncidents::ResponsePlan'
                AND region = 'us-east-1'
    response_plan:
      name: response_plan
      id: aws.ssmincidents.response_plan
      x-cfn-schema-name: ResponsePlan
      x-type: get
      x-identifiers:
        - Arn
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              data__Identifier,
              JSON_EXTRACT(Properties, '$.Arn') as arn,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.DisplayName') as display_name,
              JSON_EXTRACT(Properties, '$.ChatChannel') as chat_channel,
              JSON_EXTRACT(Properties, '$.Engagements') as engagements,
              JSON_EXTRACT(Properties, '$.Actions') as actions,
              JSON_EXTRACT(Properties, '$.Integrations') as integrations,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.IncidentTemplate') as incident_template
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::SSMIncidents::ResponsePlan'
              AND data__Identifier = '<Arn>'
              AND region = 'us-east-1'
            fallback:
              predicate: sqlDialect == "postgres"
              ddl: |-
                SELECT
                region,
                data__Identifier,
                json_extract_path_text(Properties, 'Arn') as arn,
                json_extract_path_text(Properties, 'Name') as name,
                json_extract_path_text(Properties, 'DisplayName') as display_name,
                json_extract_path_text(Properties, 'ChatChannel') as chat_channel,
                json_extract_path_text(Properties, 'Engagements') as engagements,
                json_extract_path_text(Properties, 'Actions') as actions,
                json_extract_path_text(Properties, 'Integrations') as integrations,
                json_extract_path_text(Properties, 'Tags') as tags,
                json_extract_path_text(Properties, 'IncidentTemplate') as incident_template
                FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::SSMIncidents::ResponsePlan'
                AND data__Identifier = '<Arn>'
                AND region = 'us-east-1'
