openapi: 3.0.0
info:
  version: "2019-06-10"
  title: AWS Single Sign-On
  description: AWS Single Sign-On
  x-serviceName: awsssoportal
  x-serviceAlias: sso
  x-protocol: rest-json
  x-apiVersion: "2019-06-10"
  x-endpointPrefix: portal.sso
  x-jsonVersion: "1.1"
servers:
  - url: https://portal.sso.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for sso
paths:
  /federation/credentials:
    get:
      operationId: GetRoleCredentials
      description: Returns the STS short-term credentials for a given role name that is assigned to the user.
      parameters:
        - name: role_name
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/RoleNameType"
          description: The friendly name of the role that is assigned to the user.
        - name: account_id
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/AccountIdType"
          description: The identifier for the AWS account that is assigned to the user.
        - name: x-amz-sso_bearer_token
          in: header
          required: true
          schema:
            $ref: "#/components/schemas/AccessTokenType"
          description: The token issued by the CreateToken API call. For more information, see CreateToken in the IAM Identity Center OIDC API Reference Guide.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetRoleCredentialsResponse"
  /assignment/roles:
    get:
      operationId: ListAccountRoles
      description: Lists all roles that are assigned to the user for a given AWS account.
      parameters:
        - name: next_token
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/NextTokenType"
          description: The page token from the previous response output when you request subsequent pages.
        - name: max_result
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/MaxResultType"
          description: The number of items that clients can request per page.
        - name: x-amz-sso_bearer_token
          in: header
          required: true
          schema:
            $ref: "#/components/schemas/AccessTokenType"
          description: The token issued by the CreateToken API call. For more information, see CreateToken in the IAM Identity Center OIDC API Reference Guide.
        - name: account_id
          in: query
          required: true
          schema:
            $ref: "#/components/schemas/AccountIdType"
          description: The identifier for the AWS account that is assigned to the user.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListAccountRolesResponse"
  /assignment/accounts:
    get:
      operationId: ListAccounts
      description: Lists all AWS accounts assigned to the user. These AWS accounts are assigned by the administrator of the account. For more information, see Assign User Access in the IAM Identity Center User Guide. This operation returns a paginated response.
      parameters:
        - name: next_token
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/NextTokenType"
          description: (Optional) When requesting subsequent pages, this is the page token from the previous response output.
        - name: max_result
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/MaxResultType"
          description: This is the number of items clients can request per page.
        - name: x-amz-sso_bearer_token
          in: header
          required: true
          schema:
            $ref: "#/components/schemas/AccessTokenType"
          description: The token issued by the CreateToken API call. For more information, see CreateToken in the IAM Identity Center OIDC API Reference Guide.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListAccountsResponse"
  /logout:
    post:
      operationId: Logout
      description: Removes the locally stored SSO tokens from the client-side cache and sends an API call to the IAM Identity Center service to invalidate the corresponding server-side IAM Identity Center sign in session. If a user uses IAM Identity Center to access the AWS CLI, the user’s IAM Identity Center sign in session is used to obtain an IAM session, as specified in the corresponding IAM Identity Center permission set. More specifically, IAM Identity Center assumes an IAM role in the target account on behalf of the user, and the corresponding temporary AWS credentials are returned to the client. After user logout, any existing IAM role sessions that were created by using IAM Identity Center permission sets continue based on the duration configured in the permission set. For more information, see User authentications in the IAM Identity Center User Guide.
      parameters:
        - name: x-amz-sso_bearer_token
          in: header
          required: true
          schema:
            $ref: "#/components/schemas/AccessTokenType"
          description: The token issued by the CreateToken API call. For more information, see CreateToken in the IAM Identity Center OIDC API Reference Guide.
      responses:
        "200":
          description: Success
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    RoleNameType:
      type: string
    AccountIdType:
      type: string
    AccessTokenType:
      type: string
    GetRoleCredentialsResponse:
      type: object
      properties:
        roleCredentials:
          $ref: "#/components/schemas/RoleCredentials"
          description: The credentials for the role that is assigned to the user.
    RoleCredentials:
      description: Provides information about the role credentials that are assigned to the user.
      type: object
      properties:
        accessKeyId:
          $ref: "#/components/schemas/AccessKeyType"
          description: The identifier used for the temporary security credentials. For more information, see Using Temporary Security Credentials to Request Access to AWS Resources in the AWS IAM User Guide.
        secretAccessKey:
          $ref: "#/components/schemas/SecretAccessKeyType"
          description: The key that is used to sign the request. For more information, see Using Temporary Security Credentials to Request Access to AWS Resources in the AWS IAM User Guide.
        sessionToken:
          $ref: "#/components/schemas/SessionTokenType"
          description: The token used for temporary credentials. For more information, see Using Temporary Security Credentials to Request Access to AWS Resources in the AWS IAM User Guide.
        expiration:
          $ref: "#/components/schemas/ExpirationTimestampType"
          description: The date on which temporary security credentials expire.
    AccessKeyType:
      type: string
    SecretAccessKeyType:
      type: string
    SessionTokenType:
      type: string
    ExpirationTimestampType:
      type: integer
      format: int64
    NextTokenType:
      type: string
    MaxResultType:
      type: integer
      minimum: 1
      maximum: 100
    ListAccountRolesResponse:
      type: object
      properties:
        nextToken:
          $ref: "#/components/schemas/NextTokenType"
          description: The page token client that is used to retrieve the list of accounts.
        roleList:
          $ref: "#/components/schemas/RoleListType"
          description: A paginated response with the list of roles and the next token if more results are available.
    RoleListType:
      type: array
      items:
        $ref: "#/components/schemas/RoleInfo"
    RoleInfo:
      description: Provides information about the role that is assigned to the user.
      type: object
      properties:
        roleName:
          $ref: "#/components/schemas/RoleNameType"
          description: The friendly name of the role that is assigned to the user.
        accountId:
          $ref: "#/components/schemas/AccountIdType"
          description: The identifier of the AWS account assigned to the user.
    ListAccountsResponse:
      type: object
      properties:
        nextToken:
          $ref: "#/components/schemas/NextTokenType"
          description: The page token client that is used to retrieve the list of accounts.
        accountList:
          $ref: "#/components/schemas/AccountListType"
          description: A paginated response with the list of account information and the next token if more results are available.
    AccountListType:
      type: array
      items:
        $ref: "#/components/schemas/AccountInfo"
    AccountInfo:
      description: Provides information about your AWS account.
      type: object
      properties:
        accountId:
          $ref: "#/components/schemas/AccountIdType"
          description: The identifier of the AWS account that is assigned to the user.
        accountName:
          $ref: "#/components/schemas/AccountNameType"
          description: The display name of the AWS account that is assigned to the user.
        emailAddress:
          $ref: "#/components/schemas/EmailAddressType"
          description: The email address of the AWS account that is assigned to the user.
    AccountNameType:
      type: string
    EmailAddressType:
      type: string
      minLength: 1
      maxLength: 254
  x-stackQL-resources:
    role_credentials:
      id: aws.sso.role_credentials
      name: role_credentials
      title: role_credentials
      methods:
        get_role_credentials:
          operation:
            $ref: "#/paths/~1federation~1credentials/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.roleCredentials
          request:
            nativeCasing: pascal
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/role_credentials/methods/get_role_credentials"
        insert: []
        update: []
        delete: []
    account_roles:
      id: aws.sso.account_roles
      name: account_roles
      title: account_roles
      methods:
        list_account_roles:
          operation:
            $ref: "#/paths/~1assignment~1roles/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.roleList
          request:
            nativeCasing: pascal
          config:
            pagination:
              requestToken:
                key: next_token
                location: query
              responseToken:
                key: $.nextToken
                location: body
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/account_roles/methods/list_account_roles"
        insert: []
        update: []
        delete: []
    accounts:
      id: aws.sso.accounts
      name: accounts
      title: accounts
      methods:
        list_accounts:
          operation:
            $ref: "#/paths/~1assignment~1accounts/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
            objectKey: $.accountList
          request:
            nativeCasing: pascal
          config:
            pagination:
              requestToken:
                key: next_token
                location: query
              responseToken:
                key: $.nextToken
                location: body
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/accounts/methods/list_accounts"
        insert: []
        update: []
        delete: []
