openapi: 3.0.0
info:
  version: "2019-06-10"
  title: AWS SSO OIDC
  description: AWS SSO OIDC
  x-serviceName: sso-oauth
  x-serviceAlias: sso_oidc
  x-protocol: rest-json
  x-apiVersion: "2019-06-10"
  x-endpointPrefix: oidc
  x-jsonVersion: "1.1"
servers:
  - url: https://oidc.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for sso-oidc
paths:
  /token:
    post:
      operationId: CreateToken
      description: Creates and returns access and refresh tokens for clients that are authenticated using client secrets. The access token can be used to fetch short-lived credentials for the assigned AWS accounts or to access application APIs using bearer authentication.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clientId:
                  $ref: "#/components/schemas/ClientId"
                clientSecret:
                  $ref: "#/components/schemas/ClientSecret"
                grantType:
                  $ref: "#/components/schemas/GrantType"
                deviceCode:
                  $ref: "#/components/schemas/DeviceCode"
                code:
                  $ref: "#/components/schemas/AuthCode"
                refreshToken:
                  $ref: "#/components/schemas/RefreshToken"
                scope:
                  $ref: "#/components/schemas/Scopes"
                redirectUri:
                  $ref: "#/components/schemas/URI"
                codeVerifier:
                  $ref: "#/components/schemas/CodeVerifier"
              required:
                - clientId
                - clientSecret
                - grantType
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateTokenResponse"
  /token?aws_iam=t:
    post:
      operationId: CreateTokenWithIAM
      description: Creates and returns access and refresh tokens for authorized client applications that are authenticated using any IAM entity, such as a service role or user. These tokens might contain defined scopes that specify permissions such as read:profile or write:data. Through downscoping, you can use the scopes parameter to request tokens with reduced permissions compared to the original client application's permissions or, if applicable, the refresh token's scopes. The access token can be used to fetch short-lived credentials for the assigned Amazon Web Services accounts or to access application APIs using bearer authentication. This API is used with Signature Version 4. For more information, see Amazon Web Services Signature Version 4 for API Requests.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clientId:
                  $ref: "#/components/schemas/ClientId"
                grantType:
                  $ref: "#/components/schemas/GrantType"
                code:
                  $ref: "#/components/schemas/AuthCode"
                refreshToken:
                  $ref: "#/components/schemas/RefreshToken"
                assertion:
                  $ref: "#/components/schemas/Assertion"
                scope:
                  $ref: "#/components/schemas/Scopes"
                redirectUri:
                  $ref: "#/components/schemas/URI"
                subjectToken:
                  $ref: "#/components/schemas/SubjectToken"
                subjectTokenType:
                  $ref: "#/components/schemas/TokenTypeURI"
                requestedTokenType:
                  $ref: "#/components/schemas/TokenTypeURI"
                codeVerifier:
                  $ref: "#/components/schemas/CodeVerifier"
              required:
                - clientId
                - grantType
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateTokenWithIAMResponse"
  /client/register:
    post:
      operationId: RegisterClient
      description: Registers a public client with IAM Identity Center. This allows clients to perform authorization using the authorization code grant with Proof Key for Code Exchange (PKCE) or the device code grant.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clientName:
                  $ref: "#/components/schemas/ClientName"
                clientType:
                  $ref: "#/components/schemas/ClientType"
                scopes:
                  $ref: "#/components/schemas/Scopes"
                redirectUris:
                  $ref: "#/components/schemas/RedirectUris"
                grantTypes:
                  $ref: "#/components/schemas/GrantTypes"
                issuerUrl:
                  $ref: "#/components/schemas/URI"
                entitledApplicationArn:
                  $ref: "#/components/schemas/ArnType"
              required:
                - clientName
                - clientType
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterClientResponse"
  /device_authorization:
    post:
      operationId: StartDeviceAuthorization
      description: Initiates device authorization by requesting a pair of verification codes from the authorization service.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clientId:
                  $ref: "#/components/schemas/ClientId"
                clientSecret:
                  $ref: "#/components/schemas/ClientSecret"
                startUrl:
                  $ref: "#/components/schemas/URI"
              required:
                - clientId
                - clientSecret
                - startUrl
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StartDeviceAuthorizationResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    ClientId:
      type: string
    ClientSecret:
      type: string
    GrantType:
      type: string
    DeviceCode:
      type: string
    AuthCode:
      type: string
    RefreshToken:
      type: string
    Scopes:
      type: array
      items:
        $ref: "#/components/schemas/Scope"
    Scope:
      type: string
    URI:
      type: string
    CodeVerifier:
      type: string
    CreateTokenResponse:
      type: object
      properties:
        accessToken:
          $ref: "#/components/schemas/AccessToken"
          description: A bearer token to access Amazon Web Services accounts and applications assigned to a user.
        tokenType:
          $ref: "#/components/schemas/TokenType"
          description: Used to notify the client that the returned token is an access token. The supported token type is Bearer.
        expiresIn:
          $ref: "#/components/schemas/ExpirationInSeconds"
          description: Indicates the time in seconds when an access token will expire.
        refreshToken:
          $ref: "#/components/schemas/RefreshToken"
          description: A token that, if present, can be used to refresh a previously issued access token that might have expired. For more information about the features and limitations of the current IAM Identity Center OIDC implementation, see Considerations for Using this Guide in the IAM Identity Center OIDC API Reference.
        idToken:
          $ref: "#/components/schemas/IdToken"
          description: The idToken is not implemented or supported. For more information about the features and limitations of the current IAM Identity Center OIDC implementation, see Considerations for Using this Guide in the IAM Identity Center OIDC API Reference. A JSON Web Token (JWT) that identifies who is associated with the issued access token.
    AccessToken:
      type: string
    TokenType:
      type: string
    ExpirationInSeconds:
      type: integer
    IdToken:
      type: string
    Assertion:
      type: string
    SubjectToken:
      type: string
    TokenTypeURI:
      type: string
    CreateTokenWithIAMResponse:
      type: object
      properties:
        accessToken:
          $ref: "#/components/schemas/AccessToken"
          description: A bearer token to access Amazon Web Services accounts and applications assigned to a user.
        tokenType:
          $ref: "#/components/schemas/TokenType"
          description: Used to notify the requester that the returned token is an access token. The supported token type is Bearer.
        expiresIn:
          $ref: "#/components/schemas/ExpirationInSeconds"
          description: Indicates the time in seconds when an access token will expire.
        refreshToken:
          $ref: "#/components/schemas/RefreshToken"
          description: A token that, if present, can be used to refresh a previously issued access token that might have expired. For more information about the features and limitations of the current IAM Identity Center OIDC implementation, see Considerations for Using this Guide in the IAM Identity Center OIDC API Reference.
        idToken:
          $ref: "#/components/schemas/IdToken"
          description: A JSON Web Token (JWT) that identifies the user associated with the issued access token.
        issuedTokenType:
          $ref: "#/components/schemas/TokenTypeURI"
          description: "Indicates the type of tokens that are issued by IAM Identity Center. The following values are supported: * Access Token - urn:ietf:params:oauth:token-type:access_token * Refresh Token - urn:ietf:params:oauth:token-type:refresh_token"
        scope:
          $ref: "#/components/schemas/Scopes"
          description: The list of scopes for which authorization is granted. The access token that is issued is limited to the scopes that are granted.
        awsAdditionalDetails:
          $ref: "#/components/schemas/AwsAdditionalDetails"
          description: A structure containing information from IAM Identity Center managed user and group information.
    AwsAdditionalDetails:
      description: This structure contains Amazon Web Services-specific parameter extensions and the identity context.
      type: object
      properties:
        identityContext:
          $ref: "#/components/schemas/IdentityContext"
          description: The trusted context assertion is signed and encrypted by STS. It provides access to sts:identity_context claim in the idToken without JWT parsing Identity context comprises information that Amazon Web Services services use to make authorization decisions when they receive requests.
    IdentityContext:
      type: string
    ClientName:
      type: string
    ClientType:
      type: string
    RedirectUris:
      type: array
      items:
        $ref: "#/components/schemas/URI"
    GrantTypes:
      type: array
      items:
        $ref: "#/components/schemas/GrantType"
    ArnType:
      type: string
    RegisterClientResponse:
      type: object
      properties:
        clientId:
          $ref: "#/components/schemas/ClientId"
          description: The unique identifier string for each client. This client uses this identifier to get authenticated by the service in subsequent calls.
        clientSecret:
          $ref: "#/components/schemas/ClientSecret"
          description: A secret string generated for the client. The client will use this string to get authenticated by the service in subsequent calls.
        clientIdIssuedAt:
          $ref: "#/components/schemas/LongTimeStampType"
          description: Indicates the time at which the clientId and clientSecret were issued.
        clientSecretExpiresAt:
          $ref: "#/components/schemas/LongTimeStampType"
          description: Indicates the time at which the clientId and clientSecret will become invalid.
        authorizationEndpoint:
          $ref: "#/components/schemas/URI"
          description: An endpoint that the client can use to request authorization.
        tokenEndpoint:
          $ref: "#/components/schemas/URI"
          description: An endpoint that the client can use to create tokens.
    LongTimeStampType:
      type: integer
      format: int64
    StartDeviceAuthorizationResponse:
      type: object
      properties:
        deviceCode:
          $ref: "#/components/schemas/DeviceCode"
          description: The short-lived code that is used by the device when polling for a session token.
        userCode:
          $ref: "#/components/schemas/UserCode"
          description: A one-time user verification code. This is needed to authorize an in-use device.
        verificationUri:
          $ref: "#/components/schemas/URI"
          description: The URI of the verification page that takes the userCode to authorize the device.
        verificationUriComplete:
          $ref: "#/components/schemas/URI"
          description: An alternate URL that the client can use to automatically launch a browser. This process skips the manual step in which the user visits the verification page and enters their code.
        expiresIn:
          $ref: "#/components/schemas/ExpirationInSeconds"
          description: Indicates the number of seconds in which the verification code will become invalid.
        interval:
          $ref: "#/components/schemas/IntervalInSeconds"
          description: Indicates the number of seconds the client must wait between attempts when polling for a session.
    UserCode:
      type: string
    IntervalInSeconds:
      type: integer
  x-stackQL-resources:
    tokens:
      id: aws.sso_oidc.tokens
      name: tokens
      title: tokens
      methods:
        create_token:
          operation:
            $ref: "#/paths/~1token/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert:
          - $ref: "#/components/x-stackQL-resources/tokens/methods/create_token"
        update: []
        delete: []
    token_with_iams:
      id: aws.sso_oidc.token_with_iams
      name: token_with_iams
      title: token_with_iams
      methods:
        create_token_with_iam:
          operation:
            $ref: "#/paths/~1token?aws_iam=t/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert:
          - $ref: "#/components/x-stackQL-resources/token_with_iams/methods/create_token_with_iam"
        update: []
        delete: []
    clients:
      id: aws.sso_oidc.clients
      name: clients
      title: clients
      methods:
        register_client:
          operation:
            $ref: "#/paths/~1client~1register/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select: []
        insert:
          - $ref: "#/components/x-stackQL-resources/clients/methods/register_client"
        update: []
        delete: []
