openapi: 3.0.0
info:
  title: Synthetics
  version: 1.0.0
paths: {}
components:
  schemas:
    Schedule:
      type: object
      additionalProperties: false
      properties:
        Expression:
          type: string
        DurationInSeconds:
          type: string
      required:
        - Expression
    Code:
      type: object
      additionalProperties: false
      properties:
        S3Bucket:
          type: string
        S3Key:
          type: string
        S3ObjectVersion:
          type: string
        Script:
          type: string
        Handler:
          type: string
      required:
        - Handler
      oneOf:
        - required:
            - S3Bucket
            - S3Key
        - required:
            - Script
    Tag:
      description: A key-value pair to associate with a resource.
      additionalProperties: false
      type: object
      properties:
        Key:
          type: string
          description: 'The key name of the tag. You can specify a value that is 1 to 127 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          minLength: 1
          maxLength: 128
          pattern: ^(?!aws:)([a-zA-Z\d\s_.:/=+\-@]+)$
        Value:
          type: string
          description: 'The value for the tag. You can specify a value that is 1 to 255 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, _, ., /, =, +, and -. '
          minLength: 0
          maxLength: 256
          pattern: ^([a-zA-Z\d\s_.:/=+\-@]*)$
      required:
        - Value
        - Key
    VPCConfig:
      type: object
      additionalProperties: false
      properties:
        VpcId:
          type: string
        SubnetIds:
          type: array
          items:
            type: string
        SecurityGroupIds:
          type: array
          items:
            type: string
      required:
        - SubnetIds
        - SecurityGroupIds
    RunConfig:
      type: object
      additionalProperties: false
      properties:
        TimeoutInSeconds:
          description: Provide maximum canary timeout per run in seconds
          type: integer
        MemoryInMB:
          description: Provide maximum memory available for canary in MB
          type: integer
        ActiveTracing:
          description: Enable active tracing if set to true
          type: boolean
        EnvironmentVariables:
          type: object
          additionalProperties: false
          description: Environment variable key-value pairs.
          x-patternProperties:
            '[a-zA-Z][a-zA-Z0-9_]+':
              type: string
    VisualReference:
      type: object
      additionalProperties: false
      properties:
        BaseCanaryRunId:
          type: string
          description: Canary run id to be used as base reference for visual testing
        BaseScreenshots:
          type: array
          description: List of screenshots used as base reference for visual testing
          items:
            $ref: '#/components/schemas/BaseScreenshot'
      required:
        - BaseCanaryRunId
    BaseScreenshot:
      type: object
      properties:
        ScreenshotName:
          type: string
          description: Name of the screenshot to be used as base reference for visual testing
        IgnoreCoordinates:
          type: array
          description: List of coordinates of rectangles to be ignored during visual testing
          items:
            type: string
            description: Coordinates of a rectangle to be ignored during visual testing
      required:
        - ScreenshotName
    ArtifactConfig:
      type: object
      additionalProperties: false
      properties:
        S3Encryption:
          $ref: '#/components/schemas/S3Encryption'
          description: Encryption configuration for uploading artifacts to S3
    S3Encryption:
      type: object
      additionalProperties: false
      properties:
        EncryptionMode:
          type: string
          description: 'Encryption mode for encrypting artifacts when uploading to S3. Valid values: SSE_S3 and SSE_KMS.'
        KmsKeyArn:
          type: string
          description: KMS key Arn for encrypting artifacts when uploading to S3. You must specify KMS key Arn for SSE_KMS encryption mode only.
    Canary:
      type: object
      properties:
        Name:
          description: Name of the canary.
          type: string
          pattern: ^[0-9a-z_\-]{1,21}$
        Id:
          description: Id of the canary
          type: string
        State:
          description: State of the canary
          type: string
        Code:
          description: Provide the canary script source
          $ref: '#/components/schemas/Code'
        ArtifactS3Location:
          description: Provide the s3 bucket output location for test results
          type: string
          pattern: ^(s3|S3)://
        ArtifactConfig:
          description: Provide artifact configuration
          $ref: '#/components/schemas/ArtifactConfig'
        Schedule:
          description: Frequency to run your canaries
          $ref: '#/components/schemas/Schedule'
        ExecutionRoleArn:
          description: Lambda Execution role used to run your canaries
          type: string
        RuntimeVersion:
          description: Runtime version of Synthetics Library
          type: string
        SuccessRetentionPeriod:
          description: Retention period of successful canary runs represented in number of days
          type: integer
        FailureRetentionPeriod:
          description: Retention period of failed canary runs represented in number of days
          type: integer
        Tags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
        VPCConfig:
          description: Provide VPC Configuration if enabled.
          $ref: '#/components/schemas/VPCConfig'
        RunConfig:
          description: Provide canary run configuration
          $ref: '#/components/schemas/RunConfig'
        StartCanaryAfterCreation:
          description: Runs canary if set to True. Default is False
          type: boolean
        VisualReference:
          description: Visual reference configuration for visual testing
          $ref: '#/components/schemas/VisualReference'
        DeleteLambdaResourcesOnCanaryDeletion:
          description: Deletes associated lambda resources created by Synthetics if set to True. Default is False
          type: boolean
      required:
        - Name
        - Code
        - ArtifactS3Location
        - ExecutionRoleArn
        - Schedule
        - RuntimeVersion
        - StartCanaryAfterCreation
      x-stackql-resource-name: canary
      x-stackql-primaryIdentifier:
        - Name
    ResourceArn:
      type: string
      description: Provide Canary Arn associated with the group.
      pattern: arn:(aws[a-zA-Z-]*)?:synthetics:[a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:\d{12}:canary:[0-9a-z_\-]
    Group:
      type: object
      properties:
        Name:
          description: Name of the group.
          type: string
          pattern: ^[0-9a-z_\-]{1,64}$
        Id:
          description: Id of the group.
          type: string
        Tags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
          minItems: 0
        ResourceArns:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/ResourceArn'
          maxItems: 10
      required:
        - Name
      x-stackql-resource-name: group
      x-stackql-primaryIdentifier:
        - Name
  x-stackQL-resources:
    canaries:
      name: canaries
      id: aws.synthetics.canaries
      x-cfn-schema-name: Canary
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Name') as name
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Synthetics::Canary'
    canary:
      name: canary
      id: aws.synthetics.canary
      x-cfn-schema-name: Canary
      x-type: get
      x-identifiers:
        - Name
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.State') as state,
              JSON_EXTRACT(Properties, '$.Code.S3Bucket') as code_s3_bucket,
              JSON_EXTRACT(Properties, '$.Code.S3Key') as code_s3_key,
              JSON_EXTRACT(Properties, '$.Code.S3ObjectVersion') as code_s3_object_version,
              JSON_EXTRACT(Properties, '$.Code.Script') as code_script,
              JSON_EXTRACT(Properties, '$.Code.Handler') as code_handler,
              JSON_EXTRACT(Properties, '$.ArtifactS3Location') as artifact_s3_location,
              JSON_EXTRACT(Properties, '$.ArtifactConfig.S3Encryption') as artifact_config_s3_encryption,
              JSON_EXTRACT(Properties, '$.Schedule.Expression') as schedule_expression,
              JSON_EXTRACT(Properties, '$.Schedule.DurationInSeconds') as schedule_duration_in_seconds,
              JSON_EXTRACT(Properties, '$.ExecutionRoleArn') as execution_role_arn,
              JSON_EXTRACT(Properties, '$.RuntimeVersion') as runtime_version,
              JSON_EXTRACT(Properties, '$.SuccessRetentionPeriod') as success_retention_period,
              JSON_EXTRACT(Properties, '$.FailureRetentionPeriod') as failure_retention_period,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.VPCConfig.VpcId') as v_pc_config_vpc_id,
              JSON_EXTRACT(Properties, '$.VPCConfig.SubnetIds') as v_pc_config_subnet_ids,
              JSON_EXTRACT(Properties, '$.VPCConfig.SecurityGroupIds') as v_pc_config_security_group_ids,
              JSON_EXTRACT(Properties, '$.RunConfig.TimeoutInSeconds') as run_config_timeout_in_seconds,
              JSON_EXTRACT(Properties, '$.RunConfig.MemoryInMB') as run_config_memory_in_mb,
              JSON_EXTRACT(Properties, '$.RunConfig.ActiveTracing') as run_config_active_tracing,
              JSON_EXTRACT(Properties, '$.RunConfig.EnvironmentVariables') as run_config_environment_variables,
              JSON_EXTRACT(Properties, '$.StartCanaryAfterCreation') as start_canary_after_creation,
              JSON_EXTRACT(Properties, '$.VisualReference.BaseCanaryRunId') as visual_reference_base_canary_run_id,
              JSON_EXTRACT(Properties, '$.VisualReference.BaseScreenshots') as visual_reference_base_screenshots,
              JSON_EXTRACT(Properties, '$.DeleteLambdaResourcesOnCanaryDeletion') as delete_lambda_resources_on_canary_deletion
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Synthetics::Canary'
    groups:
      name: groups
      id: aws.synthetics.groups
      x-cfn-schema-name: Group
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Name') as name
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::Synthetics::Group'
    group:
      name: group
      id: aws.synthetics.group
      x-cfn-schema-name: Group
      x-type: get
      x-identifiers:
        - Name
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.ResourceArns') as resource_arns
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::Synthetics::Group'
