openapi: 3.0.0
info:
  title: VoiceID
  version: 1.0.0
paths: {}
components:
  schemas:
    ServerSideEncryptionConfiguration:
      type: object
      properties:
        KmsKeyId:
          type: string
          maxLength: 2048
          minLength: 1
      required:
        - KmsKeyId
      additionalProperties: false
    Tag:
      type: object
      properties:
        Key:
          type: string
          maxLength: 128
          minLength: 1
          pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
        Value:
          type: string
          maxLength: 256
          minLength: 0
          pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      required:
        - Key
        - Value
      additionalProperties: false
    Domain:
      type: object
      properties:
        Description:
          type: string
          maxLength: 1024
          minLength: 1
          pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-%@]*)$
        DomainId:
          type: string
          maxLength: 22
          minLength: 22
          pattern: ^[a-zA-Z0-9]{22}$
        Name:
          type: string
          maxLength: 256
          minLength: 1
          pattern: ^[a-zA-Z0-9][a-zA-Z0-9_-]*$
        ServerSideEncryptionConfiguration:
          $ref: '#/components/schemas/ServerSideEncryptionConfiguration'
        Tags:
          type: array
          x-insertionOrder: false
          items:
            $ref: '#/components/schemas/Tag'
          maxItems: 200
          minItems: 0
      required:
        - Name
        - ServerSideEncryptionConfiguration
      x-stackql-resource-name: domain
      x-stackql-primaryIdentifier:
        - DomainId
  x-stackQL-resources:
    domains:
      name: domains
      id: aws.voiceid.domains
      x-cfn-schema-name: Domain
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.DomainId') as domain_id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::VoiceID::Domain'
    domain:
      name: domain
      id: aws.voiceid.domain
      x-cfn-schema-name: Domain
      x-type: get
      x-identifiers:
        - DomainId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Description') as description,
              JSON_EXTRACT(Properties, '$.DomainId') as domain_id,
              JSON_EXTRACT(Properties, '$.Name') as name,
              JSON_EXTRACT(Properties, '$.ServerSideEncryptionConfiguration.KmsKeyId') as server_side_encryption_configuration_kms_key_id,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::VoiceID::Domain'
