openapi: 3.0.0
info:
  version: "2019-05-01"
  title: Amazon WorkMail Message Flow
  description: Amazon WorkMail Message Flow
  x-serviceName: workmailmessageflow
  x-serviceAlias: workmailmessageflow
  x-protocol: rest-json
  x-apiVersion: "2019-05-01"
  x-endpointPrefix: workmailmessageflow
  x-jsonVersion: "1.1"
servers:
  - url: https://workmailmessageflow.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
        description: AWS region
    description: Regional endpoint for workmailmessageflow
paths:
  /messages/{message_id}:
    get:
      operationId: GetRawMessageContent
      description: Retrieves the raw content of an in-transit email message, in MIME format.
      parameters:
        - name: message_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/messageIdType"
          description: The identifier of the email message to retrieve.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetRawMessageContentResponse"
    post:
      operationId: PutRawMessageContent
      description: Updates the raw content of an in-transit email message, in MIME format. This example describes how to update in-transit email message. For more information and examples for using this API, see Updating message content with AWS Lambda. Updates to an in-transit message only appear when you call PutRawMessageContent from an AWS Lambda function configured with a synchronous Run Lambda rule. If you call PutRawMessageContent on a delivered or sent message, the message remains unchanged, even though GetRawMessageContent returns an updated message.
      parameters:
        - name: message_id
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/messageIdType"
          description: The identifier of the email message being updated.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  $ref: "#/components/schemas/RawMessageContent"
              required:
                - content
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PutRawMessageContentResponse"
components:
  parameters:
    X-Amz-Content-Sha256:
      in: header
      name: X-Amz-Content-Sha256
      required: false
      schema:
        type: string
    X-Amz-Date:
      in: header
      name: X-Amz-Date
      required: false
      schema:
        type: string
    X-Amz-Algorithm:
      in: header
      name: X-Amz-Algorithm
      required: false
      schema:
        type: string
    X-Amz-Credential:
      in: header
      name: X-Amz-Credential
      required: false
      schema:
        type: string
    X-Amz-Security-Token:
      in: header
      name: X-Amz-Security-Token
      required: false
      schema:
        type: string
    X-Amz-Signature:
      in: header
      name: X-Amz-Signature
      required: false
      schema:
        type: string
    X-Amz-SignedHeaders:
      in: header
      name: X-Amz-SignedHeaders
      required: false
      schema:
        type: string
  schemas:
    messageIdType:
      type: string
      minLength: 1
      maxLength: 120
      pattern: "[a-z0-9\\-]*"
    GetRawMessageContentResponse:
      type: object
      properties:
        messageContent:
          $ref: "#/components/schemas/messageContentBlob"
          description: The raw content of the email message, in MIME format.
      required:
        - messageContent
    messageContentBlob:
      type: string
      format: byte
    RawMessageContent:
      description: "Provides the MIME content of the updated email message as an S3 object. All MIME content must meet the following criteria: Each part of a multipart MIME message must be formatted properly. Attachments must be of a content type that Amazon SES supports. For more information, see Unsupported Attachment Types. If any of the MIME parts in a message contain content that is outside of the 7-bit ASCII character range, we recommend encoding that content. Per RFC 5321, the maximum length of each line of text, including the `<CRLF>`, must not exceed 1,000 characters. The message must contain all the required header fields. Check the returned error message for more information. The value of immutable headers must remain unchanged. Check the returned error message for more information. Certain unique headers can only appear once. Check the returned error message for more information."
      type: object
      properties:
        s3Reference:
          $ref: "#/components/schemas/S3Reference"
          description: The S3 reference of an email message.
      required:
        - s3Reference
    S3Reference:
      description: Amazon S3 object representing the updated message content, in MIME format. The region for the S3 bucket containing the S3 object must match the region used for WorkMail operations. Also, for WorkMail to process an S3 object, it must have permission to access that object. For more information, see Updating message content with AWS Lambda.
      type: object
      properties:
        bucket:
          $ref: "#/components/schemas/s3BucketIdType"
          description: The S3 bucket name.
        key:
          $ref: "#/components/schemas/s3KeyIdType"
          description: The S3 key object name.
        objectVersion:
          $ref: "#/components/schemas/s3VersionType"
          description: If you enable versioning for the bucket, you can specify the object version.
      required:
        - bucket
        - key
    s3BucketIdType:
      type: string
      minLength: 3
      maxLength: 63
      pattern: ^[a-z0-9][a-z0-9\-]*
    s3KeyIdType:
      type: string
      minLength: 1
      maxLength: 1024
      pattern: "[a-zA-Z0-9\\-/]*"
    s3VersionType:
      type: string
      minLength: 1
      maxLength: 1024
      pattern: .+
    PutRawMessageContentResponse:
      type: object
  x-stackQL-resources:
    raw_message_contents:
      id: aws.workmailmessageflow.raw_message_contents
      name: raw_message_contents
      title: raw_message_contents
      methods:
        get_raw_message_content:
          operation:
            $ref: "#/paths/~1messages~1{message_id}/get"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
        put_raw_message_content:
          operation:
            $ref: "#/paths/~1messages~1{message_id}/post"
          response:
            openAPIDocKey: "200"
            mediaType: application/json
          request:
            nativeCasing: pascal
          config:
            requestBodyTranslate:
              algorithm: naive
      sqlVerbs:
        select:
          - $ref: "#/components/x-stackQL-resources/raw_message_contents/methods/get_raw_message_content"
        insert: []
        update: []
        replace:
          - $ref: "#/components/x-stackQL-resources/raw_message_contents/methods/put_raw_message_content"
        delete: []
