openapi: 3.0.0
info:
  title: WorkSpaces
  version: 1.0.0
paths: {}
components:
  schemas:
    ConnectionAliasAssociation:
      type: object
      additionalProperties: false
      properties:
        AssociationStatus:
          type: string
          enum:
            - NOT_ASSOCIATED
            - PENDING_ASSOCIATION
            - ASSOCIATED_WITH_OWNER_ACCOUNT
            - ASSOCIATED_WITH_SHARED_ACCOUNT
            - PENDING_DISASSOCIATION
        AssociatedAccountId:
          type: string
        ResourceId:
          type: string
          pattern: .+
          minLength: 1
          maxLength: 1000
        ConnectionIdentifier:
          type: string
          maxLength: 20
          minLength: 1
          pattern: ^[a-zA-Z0-9]+$
    Tag:
      type: object
      additionalProperties: false
      properties:
        Key:
          type: string
        Value:
          type: string
      required:
        - Value
        - Key
    ConnectionAlias:
      type: object
      properties:
        Associations:
          type: array
          maxLength: 25
          minLength: 1
          items:
            $ref: '#/components/schemas/ConnectionAliasAssociation'
        AliasId:
          type: string
          pattern: ^wsca-[0-9a-z]{8,63}$
          maxLength: 68
          minLength: 13
        ConnectionString:
          type: string
          pattern: ^[.0-9a-zA-Z\-]{1,255}$
          minLength: 1
          maxLength: 255
        ConnectionAliasState:
          type: string
          enum:
            - CREATING
            - CREATED
            - DELETING
        Tags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
      required:
        - ConnectionString
      x-stackql-resource-name: connection_alias
      x-stackql-primaryIdentifier:
        - AliasId
    WorkspaceProperties:
      type: object
      additionalProperties: false
      properties:
        ComputeTypeName:
          type: string
        RootVolumeSizeGib:
          type: integer
        RunningMode:
          type: string
        RunningModeAutoStopTimeoutInMinutes:
          type: integer
        UserVolumeSizeGib:
          type: integer
    Workspace:
      type: object
      properties:
        Id:
          type: string
        BundleId:
          type: string
        DirectoryId:
          type: string
        RootVolumeEncryptionEnabled:
          type: boolean
        Tags:
          type: array
          uniqueItems: false
          items:
            $ref: '#/components/schemas/Tag'
        UserName:
          type: string
        UserVolumeEncryptionEnabled:
          type: boolean
        VolumeEncryptionKey:
          type: string
        WorkspaceProperties:
          $ref: '#/components/schemas/WorkspaceProperties'
      required:
        - BundleId
        - DirectoryId
        - UserName
      x-stackql-resource-name: workspace
      x-stackql-primaryIdentifier:
        - Id
  x-stackQL-resources:
    connection_aliases:
      name: connection_aliases
      id: aws.workspaces.connection_aliases
      x-cfn-schema-name: ConnectionAlias
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.AliasId') as alias_id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::WorkSpaces::ConnectionAlias'
    connection_alias:
      name: connection_alias
      id: aws.workspaces.connection_alias
      x-cfn-schema-name: ConnectionAlias
      x-type: get
      x-identifiers:
        - AliasId
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Associations') as associations,
              JSON_EXTRACT(Properties, '$.AliasId') as alias_id,
              JSON_EXTRACT(Properties, '$.ConnectionString') as connection_string,
              JSON_EXTRACT(Properties, '$.ConnectionAliasState') as connection_alias_state,
              JSON_EXTRACT(Properties, '$.Tags') as tags
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::WorkSpaces::ConnectionAlias'
    workspaces:
      name: workspaces
      id: aws.workspaces.workspaces
      x-cfn-schema-name: Workspace
      x-type: list
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id
              FROM aws.cloud_control.resources WHERE data__TypeName = 'AWS::WorkSpaces::Workspace'
    workspace:
      name: workspace
      id: aws.workspaces.workspace
      x-cfn-schema-name: Workspace
      x-type: get
      x-identifiers:
        - Id
      config:
        views:
          select:
            predicate: sqlDialect == "sqlite3"
            ddl: |-
              SELECT
              region,
              JSON_EXTRACT(Properties, '$.Id') as id,
              JSON_EXTRACT(Properties, '$.BundleId') as bundle_id,
              JSON_EXTRACT(Properties, '$.DirectoryId') as directory_id,
              JSON_EXTRACT(Properties, '$.RootVolumeEncryptionEnabled') as root_volume_encryption_enabled,
              JSON_EXTRACT(Properties, '$.Tags') as tags,
              JSON_EXTRACT(Properties, '$.UserName') as user_name,
              JSON_EXTRACT(Properties, '$.UserVolumeEncryptionEnabled') as user_volume_encryption_enabled,
              JSON_EXTRACT(Properties, '$.VolumeEncryptionKey') as volume_encryption_key,
              JSON_EXTRACT(Properties, '$.WorkspaceProperties.ComputeTypeName') as workspace_properties_compute_type_name,
              JSON_EXTRACT(Properties, '$.WorkspaceProperties.RootVolumeSizeGib') as workspace_properties_root_volume_size_gib,
              JSON_EXTRACT(Properties, '$.WorkspaceProperties.RunningMode') as workspace_properties_running_mode,
              JSON_EXTRACT(Properties, '$.WorkspaceProperties.RunningModeAutoStopTimeoutInMinutes') as workspace_properties_running_mode_auto_stop_timeout_in_minutes,
              JSON_EXTRACT(Properties, '$.WorkspaceProperties.UserVolumeSizeGib') as workspace_properties_user_volume_size_gib
              FROM aws.cloud_control.resource WHERE data__TypeName = 'AWS::WorkSpaces::Workspace'
