openapi: 3.0.3
info:
  title: audit_logs API
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience. To get started using Cloudflare's products
    and services via the API, refer to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources. Using the Cloudflare API requires
    authentication so that Cloudflare knows who is making requests and what
    permissions you have. Create an API token to grant access to the API to
    perform actions. You can also authenticate with [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API. To create an API token, from the
    Cloudflare dashboard, go to My Profile > API Tokens and select Create Token.
    For more information on how to create and troubleshoot API tokens, refer to
    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).
    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).
    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  version: 4.0.0
  contact:
    name: Cloudflare
    url: https://www.cloudflare.com
servers:
  - url: https://api.cloudflare.com/client/v4
security:
  - api_token: []
paths:
  /accounts/{account_id}/audit_logs:
    get:
      description: >-
        Gets a list of audit logs for an account. Can be filtered by who made
        the change, on which zone, and the timeframe of the change.
      operationId: audit-logs-get-account-audit-logs
      parameters:
        - name: account_id
          in: path
          required: true
          description: The Cloudflare account ID.
          schema:
            type: string
        - in: query
          name: id
          schema:
            description: Finds a specific log by its ID.
            type: string
        - in: query
          name: export
          schema:
            description: Indicates that this request is an export of logs in CSV format.
            type: boolean
        - in: query
          name: action.type
          schema:
            description: Filters by the action type.
            type: string
        - in: query
          name: actor.ip
          schema:
            description: >-
              Filters by the IP address of the request that made the change by
              specific IP address or valid CIDR Range.
            type: string
        - in: query
          name: actor.email
          schema:
            description: Filters by the email address of the actor that made the change.
            format: email
            type: string
        - in: query
          name: since
          schema:
            type: string
            format: date
            description: >-
              Limits the returned results to logs newer than the specified date.
              A `full-date` that conforms to RFC3339.
        - in: query
          name: before
          schema:
            type: string
            format: date
            description: >-
              Limits the returned results to logs older than the specified date.
              A `full-date` that conforms to RFC3339.
        - in: query
          name: zone.name
          schema:
            description: Filters by the name of the zone associated to the change.
            type: string
        - in: query
          name: direction
          schema:
            default: desc
            description: Changes the direction of the chronological sorting.
            enum:
              - desc
              - asc
            type: string
        - in: query
          name: per_page
          schema:
            default: 100
            description: Sets the number of results to return per page.
            maximum: 1000
            minimum: 1
            type: number
        - in: query
          name: page
          schema:
            default: 1
            description: Defines which page of results to return.
            minimum: 1
            type: number
        - in: query
          name: hide_user_logs
          schema:
            default: false
            description: Indicates whether or not to hide user level audit logs.
            type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aaaAuditLogsResponseCollection_2'
          description: Get account audit logs response
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/result'
          description: Get account audit logs response failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get account audit logs
      tags:
        - Audit Logs
      x-api-token-group:
        - Account Settings Write
        - Account Settings Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
      x-stackql-sdk:
        service: audit_logs
        resource_chain: []
        method: list
components:
  schemas:
    aaaAuditLogs:
      properties:
        action:
          properties:
            result:
              description: A boolean that indicates if the action attempted was successful.
              example: true
              type: boolean
            type:
              description: A short string that describes the action that was performed.
              example: change_setting
              type: string
          type: object
        actor:
          properties:
            email:
              description: The email of the user that performed the action.
              example: michelle@example.com
              format: email
              type: string
            id:
              description: >-
                The ID of the actor that performed the action. If a user
                performed the action, this will be their User ID.
              example: f6b5de0326bb5182b8a4840ee01ec774
              type: string
            ip:
              description: The IP address of the request that performed the action.
              example: 198.41.129.166
              type: string
            type:
              description: >-
                The type of actor, whether a User, Cloudflare Admin, or an
                Automated System.
              enum:
                - user
                - admin
                - Cloudflare
              example: user
              type: string
          type: object
        id:
          description: A string that uniquely identifies the audit log.
          example: d5b0f326-1232-4452-8858-1089bd7168ef
          type: string
        interface:
          description: The source of the event.
          example: API
          type: string
        metadata:
          description: >-
            An object which can lend more context to the action being logged.
            This is a flexible value and varies between different actions.
          example:
            name: security_level
            type: firewall
            value: high
            zone_name: example.com
          type: object
        newValue:
          description: The new value of the resource that was modified.
          example: low
          type: string
        oldValue:
          description: The value of the resource before it was modified.
          example: high
          type: string
        owner:
          properties:
            id:
              $ref: '#/components/schemas/aaaIdentifier'
          type: object
        resource:
          properties:
            id:
              description: An identifier for the resource that was affected by the action.
              example: 023e105f4ecef8ad9ca31a8372d0c353
              type: string
            type:
              description: >-
                A short string that describes the resource that was affected by
                the action.
              example: zone
              type: string
          type: object
        when:
          description: >-
            A UTC RFC3339 timestamp that specifies when the action being logged
            occured.
          example: '2017-04-26T17:31:07Z'
          format: date-time
          type: string
      type: object
    aaaAuditLogsResponseCollection_2:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/aaaMessages'
        messages:
          $ref: '#/components/schemas/aaaMessages'
        result:
          items:
            $ref: '#/components/schemas/aaaAuditLogs'
          type: array
        success:
          example: true
          type: boolean
      required:
        - errors
        - success
        - messages
    aaaIdentifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    aaaMessages:
      example: []
      items:
        $ref: '#/components/schemas/responseInfo'
      type: array
    responseInfo:
      properties:
        code:
          minimum: 1000
          type: integer
        message:
          type: string
        documentation_url:
          type: string
        source:
          type: object
          properties:
            pointer:
              type: string
      required:
        - code
        - message
      type: object
      uniqueItems: true
    result:
      properties:
        errors:
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
          $ref: '#/components/schemas/aaaMessages'
        messages:
          $ref: '#/components/schemas/aaaMessages'
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
        result:
          items:
            $ref: '#/components/schemas/aaaAuditLogs'
          type: array
      required:
        - errors
        - messages
        - success
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
      description: >-
        The previous authorization scheme for interacting with the Cloudflare
        API, used in conjunction with a Global API key.
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
      description: >-
        The previous authorization scheme for interacting with the Cloudflare
        API. When possible, use API tokens instead of Global API keys.
    api_token:
      scheme: bearer
      type: http
      description: >-
        The preferred authorization scheme for interacting with the Cloudflare
        API. [Create a
        token](https://developers.cloudflare.com/fundamentals/api/get-started/create-token/).
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
      description: >-
        Used when interacting with the Origin CA certificates API. [View/change
        your
        key](https://developers.cloudflare.com/fundamentals/api/get-started/ca-keys/#viewchange-your-origin-ca-keys).
  x-stackQL-resources:
    audit_logs:
      id: cloudflare.audit_logs.audit_logs
      name: audit_logs
      title: Audit Logs
      methods:
        list:
          operation:
            $ref: '#/paths/~1accounts~1{account_id}~1audit_logs/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.result
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/audit_logs/methods/list'
        insert: []
        update: []
        delete: []
        replace: []
