openapi: 3.0.3
info:
  title: certificate_authorities API
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience. To get started using Cloudflare's products
    and services via the API, refer to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources. Using the Cloudflare API requires
    authentication so that Cloudflare knows who is making requests and what
    permissions you have. Create an API token to grant access to the API to
    perform actions. You can also authenticate with [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API. To create an API token, from the
    Cloudflare dashboard, go to My Profile > API Tokens and select Create Token.
    For more information on how to create and troubleshoot API tokens, refer to
    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).
    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).
    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  version: 4.0.0
  contact:
    name: Cloudflare
    url: https://www.cloudflare.com
servers:
  - url: https://api.cloudflare.com/client/v4
security:
  - api_token: []
paths:
  /zones/{zone_id}/certificate_authorities/hostname_associations:
    get:
      description: List Hostname Associations
      operationId: client-certificate-for-a-zone-list-hostname-associations
      parameters:
        - name: zone_id
          in: path
          required: true
          description: The Cloudflare zone ID.
          schema:
            type: string
        - in: query
          name: mtls_certificate_id
          schema:
            description: >-
              The UUID to match against for a certificate that was uploaded to
              the mTLS Certificate Management endpoint. If no
              mtls_certificate_id is given, the results will be the hostnames
              associated to your active Cloudflare Managed CA.
            maxLength: 36
            minLength: 36
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tlsCertificatesAndHostnamesHostnameAssociationsResponse
          description: List Hostname Associations Response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tlsCertificatesAndHostnamesApiResponseCommonFailure
          description: List Hostname Associations Response Failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: List Hostname Associations
      tags:
        - API Shield Client Certificates for a Zone
      x-api-token-group:
        - SSL and Certificates Write
        - SSL and Certificates Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
      x-stackql-sdk:
        service: certificate_authorities
        resource_chain:
          - hostname_associations
        method: get
    put:
      description: Replace Hostname Associations
      operationId: client-certificate-for-a-zone-put-hostname-associations
      parameters:
        - name: zone_id
          in: path
          required: true
          description: The Cloudflare zone ID.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: >-
                #/components/schemas/tlsCertificatesAndHostnamesHostnameAssociation
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tlsCertificatesAndHostnamesHostnameAssociationsResponse
          description: Replace Hostname Associations Response
        4XX:
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/tlsCertificatesAndHostnamesApiResponseCommonFailure
          description: Replace Hostname Associations Response Failure
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Replace Hostname Associations
      tags:
        - API Shield Client Certificates for a Zone
      x-api-token-group:
        - SSL and Certificates Write
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
      x-stackql-sdk:
        service: certificate_authorities
        resource_chain:
          - hostname_associations
        method: update
components:
  schemas:
    tlsCertificatesAndHostnamesApiResponseCommonFailure:
      properties:
        errors:
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
          $ref: '#/components/schemas/tlsCertificatesAndHostnamesMessages'
        messages:
          example: []
          $ref: '#/components/schemas/tlsCertificatesAndHostnamesMessages'
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    tlsCertificatesAndHostnamesHostnameAssociation:
      properties:
        hostnames:
          $ref: '#/components/schemas/tlsCertificatesAndHostnamesSchemasHostnames'
        mtls_certificate_id:
          description: >-
            The UUID for a certificate that was uploaded to the mTLS Certificate
            Management endpoint. If no mtls_certificate_id is given, the
            hostnames will be associated to your active Cloudflare Managed CA.
          maxLength: 36
          minLength: 36
          type: string
          x-auditable: true
      type: object
    tlsCertificatesAndHostnamesHostnameAssociationsResponse:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/tlsCertificatesAndHostnamesMessages'
        messages:
          $ref: '#/components/schemas/tlsCertificatesAndHostnamesMessages'
        success:
          description: Whether the API call was successful.
          enum:
            - true
          example: true
          type: boolean
        result:
          properties:
            hostnames:
              $ref: '#/components/schemas/tlsCertificatesAndHostnamesSchemasHostnames'
          type: object
      required:
        - success
        - errors
        - messages
    tlsCertificatesAndHostnamesMessages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          documentation_url:
            type: string
          message:
            type: string
          source:
            properties:
              pointer:
                type: string
            type: object
        required:
          - code
          - message
        type: object
        uniqueItems: true
      type: array
    tlsCertificatesAndHostnamesSchemasHostnames:
      items:
        example: api.example.com
        type: string
        x-auditable: true
      type: array
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
      description: >-
        The previous authorization scheme for interacting with the Cloudflare
        API, used in conjunction with a Global API key.
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
      description: >-
        The previous authorization scheme for interacting with the Cloudflare
        API. When possible, use API tokens instead of Global API keys.
    api_token:
      scheme: bearer
      type: http
      description: >-
        The preferred authorization scheme for interacting with the Cloudflare
        API. [Create a
        token](https://developers.cloudflare.com/fundamentals/api/get-started/create-token/).
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
      description: >-
        Used when interacting with the Origin CA certificates API. [View/change
        your
        key](https://developers.cloudflare.com/fundamentals/api/get-started/ca-keys/#viewchange-your-origin-ca-keys).
  x-stackQL-resources:
    hostname_associations:
      id: cloudflare.certificate_authorities.hostname_associations
      name: hostname_associations
      title: Hostname Associations
      methods:
        list:
          operation:
            $ref: >-
              #/paths/~1zones~1{zone_id}~1certificate_authorities~1hostname_associations/get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
        update:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: >-
              #/paths/~1zones~1{zone_id}~1certificate_authorities~1hostname_associations/put
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/hostname_associations/methods/list
        insert: []
        update: []
        delete: []
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/hostname_associations/methods/update
