openapi: 3.0.3
servers:
  - description: Client API
    url: 'https://api.cloudflare.com/client/v4'
info:
  description: Cloudflare IPs
  license:
    name: BSD-3-Clause
    url: 'https://opensource.org/licenses/BSD-3-Clause'
  title: Cloudflare API - cloudflare_ips
  version: 4.0.0
components:
  schemas:
    api-response-single:
      allOf:
        - $ref: '#/components/schemas/api-response-common'
        - properties:
            result:
              anyOf:
                - type: object
                - type: string
              nullable: true
    ips:
      properties:
        etag:
          description: A digest of the IP data. Useful for determining if the data has changed.
          example: a8e453d9d129a3769407127936edfdb0
          type: string
        ipv4_cidrs:
          description: List of Cloudflare IPv4 CIDR addresses.
          items:
            description: IPv4 CIDR.
            example: 199.27.128.0/21
            type: string
          type: array
        ipv6_cidrs:
          description: List of Cloudflare IPv6 CIDR addresses.
          items:
            description: IPv6 CIDR.
            example: '2400:cb00::/32'
            type: string
          type: array
      type: object
    api-response-common-failure:
      properties:
        errors:
          allOf:
            - $ref: '#/components/schemas/messages'
          example:
            - code: 7003
              message: No route for the URI
          minLength: 1
        messages:
          allOf:
            - $ref: '#/components/schemas/messages'
          example: []
        result:
          enum:
            - null
          nullable: true
        success:
          description: Whether the API call was successful
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/messages'
        messages:
          $ref: '#/components/schemas/messages'
        result:
          anyOf:
            - type: object
            - items: {}
              type: array
            - type: string
        success:
          description: Whether the API call was successful
          enum:
            - true
          example: true
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
          - code
          - message
        type: object
        uniqueItems: true
      type: array
  responses: {}
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
  x-stackQL-resources:
    ips:
      id: cloudflare.cloudflare_ips.ips
      name: ips
      title: Ips
      methods:
        cloudflare_i_ps_cloudflare_ip_details:
          operation:
            $ref: '#/paths/~1ips/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.result
        _cloudflare_i_ps_cloudflare_ip_details:
          operation:
            $ref: '#/paths/~1ips/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/ips/methods/cloudflare_i_ps_cloudflare_ip_details'
        insert: []
        update: []
        delete: []
paths:
  /ips:
    get:
      description: Get Cloudflare IPs.
      operationId: cloudflare-i-ps-cloudflare-ip-details
      responses:
        '200':
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/api-response-single'
                  - properties:
                      result:
                        $ref: '#/components/schemas/ips'
          description: Cloudflare IP Details response
        4xx:
          content:
            application/json:
              schema:
                allOf:
                  - allOf:
                      - $ref: '#/components/schemas/api-response-single'
                      - properties:
                          result:
                            $ref: '#/components/schemas/ips'
                  - $ref: '#/components/schemas/api-response-common-failure'
          description: Cloudflare IP Details response failure
      security:
        - api_email: []
          api_key: []
        - api_token: []
      summary: Cloudflare IP Details
      tags:
        - Cloudflare IPs
