openapi: 3.0.3
info:
  title: ips API
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience. To get started using Cloudflare's products
    and services via the API, refer to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources. Using the Cloudflare API requires
    authentication so that Cloudflare knows who is making requests and what
    permissions you have. Create an API token to grant access to the API to
    perform actions. You can also authenticate with [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API. To create an API token, from the
    Cloudflare dashboard, go to My Profile > API Tokens and select Create Token.
    For more information on how to create and troubleshoot API tokens, refer to
    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).
    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).
    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  version: 4.0.0
  contact:
    name: Cloudflare
    url: https://www.cloudflare.com
servers:
  - url: https://api.cloudflare.com/client/v4
security:
  - api_token: []
paths:
  /ips:
    get:
      description: >-
        Get IPs used on the Cloudflare/JD Cloud network, see
        https://www.cloudflare.com/ips for Cloudflare IPs or
        https://developers.cloudflare.com/china-network/reference/infrastructure/
        for JD Cloud IPs.
      operationId: cloudflare-ips-cloudflare-ip-details
      parameters:
        - description: Specified as `jdcloud` to list IPs used by JD Cloud data centers.
          in: query
          name: networks
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    $ref: '#/components/schemas/publicIpMessages'
                  messages:
                    $ref: '#/components/schemas/publicIpMessages'
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - true
                    type: boolean
                  result:
                    type: object
                    properties:
                      etag:
                        $ref: '#/components/schemas/publicIpEtag'
                      ipv4_cidrs:
                        $ref: '#/components/schemas/publicIpIpv4Cidrs'
                      ipv6_cidrs:
                        $ref: '#/components/schemas/publicIpIpv6Cidrs'
                      jdcloud_cidrs:
                        $ref: '#/components/schemas/publicIpJdcloudCidrs'
                required:
                  - success
                  - errors
                  - messages
          description: Cloudflare IP Details response
        4XX:
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    $ref: '#/components/schemas/publicIpMessages'
                  messages:
                    $ref: '#/components/schemas/publicIpMessages'
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - true
                      - false
                    type: boolean
                  result:
                    enum:
                      - null
                    type: object
                    properties:
                      etag:
                        $ref: '#/components/schemas/publicIpEtag'
                      ipv4_cidrs:
                        $ref: '#/components/schemas/publicIpIpv4Cidrs'
                      ipv6_cidrs:
                        $ref: '#/components/schemas/publicIpIpv6Cidrs'
                      jdcloud_cidrs:
                        $ref: '#/components/schemas/publicIpJdcloudCidrs'
                required:
                  - success
                  - errors
                  - messages
                  - success
                  - errors
                  - messages
                  - result
          description: Cloudflare IP Details response failure
      security:
        - {}
      summary: Cloudflare/JD Cloud IP Details
      tags:
        - Cloudflare IPs
      x-stackql-sdk:
        service: ips
        resource_chain: []
        method: list
components:
  schemas:
    publicIpEtag:
      description: A digest of the IP data. Useful for determining if the data has changed.
      example: a8e453d9d129a3769407127936edfdb0
      type: string
    publicIpIpv4Cidrs:
      description: List of Cloudflare IPv4 CIDR addresses.
      items:
        description: IPv4 CIDR.
        example: 199.27.128.0/21
        type: string
      type: array
    publicIpIpv6Cidrs:
      description: List of Cloudflare IPv6 CIDR addresses.
      items:
        description: IPv6 CIDR.
        example: 2400:cb00::/32
        type: string
      type: array
    publicIpJdcloudCidrs:
      description: List IPv4 and IPv6 CIDRs, only populated if `?networks=jdcloud` is used.
      items:
        description: IPv4 or IPv6 CIDR.
        example: 199.27.128.0/21
        type: string
      type: array
    publicIpMessages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          documentation_url:
            type: string
          message:
            type: string
          source:
            properties:
              pointer:
                type: string
            type: object
        required:
          - code
          - message
        type: object
        uniqueItems: true
      type: array
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
      description: >-
        The previous authorization scheme for interacting with the Cloudflare
        API, used in conjunction with a Global API key.
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
      description: >-
        The previous authorization scheme for interacting with the Cloudflare
        API. When possible, use API tokens instead of Global API keys.
    api_token:
      scheme: bearer
      type: http
      description: >-
        The preferred authorization scheme for interacting with the Cloudflare
        API. [Create a
        token](https://developers.cloudflare.com/fundamentals/api/get-started/create-token/).
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
      description: >-
        Used when interacting with the Origin CA certificates API. [View/change
        your
        key](https://developers.cloudflare.com/fundamentals/api/get-started/ca-keys/#viewchange-your-origin-ca-keys).
  x-stackQL-resources:
    ips:
      id: cloudflare.ips.ips
      name: ips
      title: Ips
      methods:
        list:
          operation:
            $ref: '#/paths/~1ips/get'
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.result
      sqlVerbs:
        select:
          - $ref: '#/components/x-stackQL-resources/ips/methods/list'
        insert: []
        update: []
        delete: []
        replace: []
