openapi: 3.0.3
info:
  title: origin_post_quantum_encryption API
  description: >-
    Welcome to Cloudflare's API documentation site. We are experimenting with an
    updated version of our API documentation - check out
    [developers.cloudflare.com/api-next/](https://developers.cloudflare.com/api-next/)
    to test out the new experience. To get started using Cloudflare's products
    and services via the API, refer to [how to interact with
    Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/),
    which covers using tools like
    [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform)
    and the [official
    SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to
    maintain your Cloudflare resources. Using the Cloudflare API requires
    authentication so that Cloudflare knows who is making requests and what
    permissions you have. Create an API token to grant access to the API to
    perform actions. You can also authenticate with [API
    keys](https://developers.cloudflare.com/fundamentals/api/get-started/keys/),
    but these keys have [several
    limitations](https://developers.cloudflare.com/fundamentals/api/get-started/keys/#limitations)
    that make them less secure than API tokens. Whenever possible, use API
    tokens to interact with the Cloudflare API. To create an API token, from the
    Cloudflare dashboard, go to My Profile > API Tokens and select Create Token.
    For more information on how to create and troubleshoot API tokens, refer to
    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).
    For information regarding rate limits, refer to our [API Rate
    Limits](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/platform/limits/#api-rate-limits).
    Totally new to Cloudflare? [Start
    here](https://developers.cloudflare.com/fundamentals/get-started/).
  version: 4.0.0
  contact:
    name: Cloudflare
    url: https://www.cloudflare.com
servers:
  - url: https://api.cloudflare.com/client/v4
security:
  - api_token: []
paths:
  /zones/{zone_id}/cache/origin_post_quantum_encryption:
    get:
      description: >-
        Instructs Cloudflare to use Post-Quantum (PQ) key agreement algorithms
        when connecting to your origin. Preferred instructs Cloudflare to
        opportunistically send a Post-Quantum keyshare in the first message to
        the origin (for fastest connections when the origin supports and prefers
        PQ), supported means that PQ algorithms are advertised but only used
        when requested by the origin, and off means that PQ algorithms are not
        advertised.
      operationId: zone-cache-settings-get-origin-post-quantum-encryption-setting
      parameters:
        - name: zone_id
          in: path
          required: true
          description: The Cloudflare zone ID.
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    $ref: '#/components/schemas/cacheRulesMessages'
                  messages:
                    $ref: '#/components/schemas/cacheRulesMessages'
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - true
                    type: boolean
                  result:
                    $ref: >-
                      #/components/schemas/unnamedSchemaRef9444735ca60712dbcf8afd832eb5716a
                required:
                  - success
                  - errors
                  - messages
          description: Get Origin Post-Quantum Encryption setting response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cacheRulesApiResponseCommonFailure'
          description: Get Origin Post-Quantum Encryption setting response failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Get Origin Post-Quantum Encryption setting
      tags:
        - Origin Post-Quantum
      x-api-token-group:
        - Zone Settings Write
        - Zone Settings Read
        - Zone Read
        - Zone Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
      x-stackql-sdk:
        service: origin_post_quantum_encryption
        resource_chain: []
        method: get
    put:
      description: >-
        Instructs Cloudflare to use Post-Quantum (PQ) key agreement algorithms
        when connecting to your origin. Preferred instructs Cloudflare to
        opportunistically send a Post-Quantum keyshare in the first message to
        the origin (for fastest connections when the origin supports and prefers
        PQ), supported means that PQ algorithms are advertised but only used
        when requested by the origin, and off means that PQ algorithms are not
        advertised.
      operationId: zone-cache-settings-change-origin-post-quantum-encryption-setting
      parameters:
        - name: zone_id
          in: path
          required: true
          description: The Cloudflare zone ID.
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                value:
                  $ref: >-
                    #/components/schemas/cacheRulesOriginPostQuantumEncryptionValue
              required:
                - value
              type: object
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    $ref: '#/components/schemas/cacheRulesMessages'
                  messages:
                    $ref: '#/components/schemas/cacheRulesMessages'
                  success:
                    description: Whether the API call was successful.
                    enum:
                      - true
                    type: boolean
                  result:
                    $ref: >-
                      #/components/schemas/unnamedSchemaRef9444735ca60712dbcf8afd832eb5716a
                required:
                  - success
                  - errors
                  - messages
          description: Change Origin Post-Quantum Encryption setting response.
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cacheRulesApiResponseCommonFailure'
          description: Change Origin Post-Quantum Encryption setting response failure.
      security:
        - api_token: []
        - api_email: []
          api_key: []
      summary: Change Origin Post-Quantum Encryption setting
      tags:
        - Origin Post-Quantum
      x-api-token-group:
        - Zone Settings Write
        - Zone Write
      x-cfPermissionsRequired:
        enum:
          - '#zone_settings:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
      x-stackql-sdk:
        service: origin_post_quantum_encryption
        resource_chain: []
        method: update
components:
  schemas:
    cacheRulesApiResponseCommonFailure:
      properties:
        errors:
          example:
            - code: 7003
              message: No route for the URI
          items:
            type: object
          minLength: 1
          type: array
          $ref: '#/components/schemas/cacheRulesMessages'
        messages:
          example: []
          items:
            type: object
          type: array
          $ref: '#/components/schemas/cacheRulesMessages'
        result:
          enum:
            - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
            - false
          example: false
          type: boolean
      required:
        - success
        - errors
        - messages
        - result
      type: object
    cacheRulesEditable:
      description: Whether the setting is editable.
      type: boolean
      x-auditable: true
    cacheRulesMessages:
      example: []
      items:
        $ref: '#/components/schemas/responseInfo'
      type: array
    cacheRulesModifiedOn:
      description: The time when the setting was last modified.
      format: date-time
      type: string
      x-auditable: true
    cacheRulesOriginPostQuantumEncryptionValue:
      default: supported
      description: Value of the Origin Post Quantum Encryption Setting.
      enum:
        - preferred
        - supported
        - 'off'
      type: string
      x-auditable: true
    responseInfo:
      properties:
        code:
          minimum: 1000
          type: integer
        message:
          type: string
        documentation_url:
          type: string
        source:
          type: object
          properties:
            pointer:
              type: string
      required:
        - code
        - message
      type: object
      uniqueItems: true
    unnamedSchemaRef9444735ca60712dbcf8afd832eb5716a:
      properties:
        editable:
          $ref: '#/components/schemas/cacheRulesEditable'
        id:
          description: The identifier of the caching setting.
          type: string
          x-auditable: true
          enum:
            - origin_pqe
        modified_on:
          $ref: '#/components/schemas/cacheRulesModifiedOn'
          description: Last time this setting was modified.
          example: '2014-01-01T05:20:00.12345Z'
          format: date-time
          nullable: true
          readOnly: true
          type: string
          x-auditable: true
        value:
          description: Value of the Origin Post Quantum Encryption Setting.
          type: string
          x-auditable: true
          default: supported
          enum:
            - preferred
            - supported
            - 'off'
      required:
        - id
        - value
        - editable
        - id
        - value
      type: object
      title: Origin Post-Quantum Encryption
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
      description: >-
        The previous authorization scheme for interacting with the Cloudflare
        API, used in conjunction with a Global API key.
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
      description: >-
        The previous authorization scheme for interacting with the Cloudflare
        API. When possible, use API tokens instead of Global API keys.
    api_token:
      scheme: bearer
      type: http
      description: >-
        The preferred authorization scheme for interacting with the Cloudflare
        API. [Create a
        token](https://developers.cloudflare.com/fundamentals/api/get-started/create-token/).
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
      description: >-
        Used when interacting with the Origin CA certificates API. [View/change
        your
        key](https://developers.cloudflare.com/fundamentals/api/get-started/ca-keys/#viewchange-your-origin-ca-keys).
  x-stackQL-resources:
    origin_post_quantum_encryption:
      id: cloudflare.origin_post_quantum_encryption.origin_post_quantum_encryption
      name: origin_post_quantum_encryption
      title: Origin Post Quantum Encryption
      methods:
        list:
          operation:
            $ref: >-
              #/paths/~1zones~1{zone_id}~1cache~1origin_post_quantum_encryption/get
          response:
            mediaType: application/json
            openAPIDocKey: '200'
            objectKey: $.result
        update:
          config:
            requestBodyTranslate:
              algorithm: naive
          operation:
            $ref: >-
              #/paths/~1zones~1{zone_id}~1cache~1origin_post_quantum_encryption/put
          response:
            mediaType: application/json
            openAPIDocKey: '200'
      sqlVerbs:
        select:
          - $ref: >-
              #/components/x-stackQL-resources/origin_post_quantum_encryption/methods/list
        insert: []
        update: []
        delete: []
        replace:
          - $ref: >-
              #/components/x-stackQL-resources/origin_post_quantum_encryption/methods/update
